package jk0.b;
import com.kuaishou.krn.env.KrnDevEnv;
import java.lang.String;
import java.util.List;
import com.kuaishou.krn.jsexecutor.JsExecutorType;

public interface abstract b	// class@002bb9
{

    boolean A();
    void A0(boolean p0);
    boolean B();
    void B0(boolean p0);
    boolean C();
    boolean D();
    void E(boolean p0);
    void F(boolean p0);
    boolean G();
    boolean H();
    void I(boolean p0);
    void J(boolean p0);
    boolean K();
    KrnDevEnv L();
    String M();
    boolean N();
    boolean O();
    boolean P();
    void Q(boolean p0);
    boolean R();
    void S(boolean p0);
    boolean T();
    void U(String p0);
    boolean V();
    void W(boolean p0);
    List X();
    void Y(boolean p0);
    JsExecutorType Z();
    void a(boolean p0);
    void a0(boolean p0);
    boolean b();
    boolean b0();
    void c(boolean p0);
    void c0(List p0);
    void d(boolean p0);
    boolean d0();
    void e(boolean p0);
    void e0(boolean p0);
    void f(boolean p0);
    boolean f0();
    boolean g();
    boolean g0();
    void h(boolean p0);
    boolean h0();
    boolean i();
    void i0(boolean p0);
    boolean j();
    void j0(String p0);
    boolean k();
    void k0(boolean p0);
    boolean l();
    void l0(boolean p0);
    boolean m();
    boolean m0();
    void n(boolean p0);
    boolean n0();
    void o(boolean p0);
    void o0(boolean p0);
    void p(JsExecutorType p0);
    boolean p0();
    void q(KrnDevEnv p0);
    void q0(boolean p0);
    boolean r();
    boolean r0();
    void s(boolean p0);
    String s0();
    void t(String p0);
    boolean t0();
    void u(boolean p0);
    void u0(String p0);
    boolean v();
    void v0(boolean p0);
    void w(boolean p0);
    String w0();
    void x(boolean p0);
    void x0(boolean p0);
    boolean y();
    void y0(boolean p0);
    void z(boolean p0);
    String z0();
}
