package com.kwai.platform.krouter.meta.KRouterMetaConfig;
import java.lang.Object;
import java.lang.Class;
import java.lang.String;
import com.kwai.robust.PatchProxy;
import wh7.d;
import java.util.ArrayList;
import com.yxcorp.gifshow.message.init.router.StickGroupUriHandler;
import java.util.List;
import rh7.a;
import wh7.c;
import com.kuaishou.merchant.router.support.krouter.KRouterMerchantAnnotation$KwaiSchemeMerchantUriHandler;
import com.yxcorp.gifshow.ad.detail.router.AdDetailUriHandler;
import com.yxcorp.gifshow.HomeHandler;
import com.kuaishou.live.external.authenticate.LiveAuthenticateUriRouterHandler;
import com.yxcorp.gifshow.relation.util.KwaiRelationFollowHandler;
import com.yxcorp.gifshow.reminder.news.NewsSlidePlayUriHandler;
import com.yxcorp.gifshow.BringToFrontHandler;
import com.yxcorp.gifshow.reminder.friend.FriendsHandler;
import com.yxcorp.gifshow.message.init.router.rtc.IMRTCUriHandler;
import com.yxcorp.gifshow.detail.DetailUriRouterHandler;
import com.yxcorp.gifshow.FeaturedHandler;
import com.yxcorp.gifshow.message.init.router.NativeRealNameUriHandler;
import com.kuaishou.merchant.router.support.krouter.KRouterMerchantAnnotation$KwaiMerchantSchemeUriHandler;
import com.yxcorp.plugin.search.SearchUriRouterHandler;
import com.yxcorp.gifshow.ad.detail.router.AdCommonWebUriHandler;
import com.yxcorp.gifshow.ad.award.scheme.NeoUriHandler;
import com.kwai.feature.post.api.thirdparty.ThirdPartyKRouterUriHandler;
import com.kuaishou.merchant.router.support.PreloaderUriHandler;
import com.yxcorp.gifshow.message.init.router.MessageUriHandler;
import com.yxcorp.gifshow.growth.push.coin.PushCoinUriHandler;
import com.yxcorp.gifshow.message.init.router.RealNameUriHandler;
import wh7.b;
import com.yxcorp.gifshow.relation.plugin.RelationRouterHandler;
import com.kuaishou.live.external.subscribe.LiveImmediatelySubscribeUriRouterHandler;
import com.yxcorp.plugin.payment.MyWalletRouterUriHandler;
import com.kuaishou.live.core.basic.liveslide.urihandler.LiveSlideUriHandler;
import com.yxcorp.gifshow.relation.intimate.helper.IntimateRouterHandler;
import com.kwai.component.fansgroup.detail.KoiKrnDetailUriHandler2;
import com.kwai.component.fansgroup.fansgrouplist.FansGroupUriHandler;
import com.kuaishou.live.external.subscribe.LiveHalfSubscribeUriRouterHandler;
import com.yxcorp.gifshow.ad.tachikoma.page.AdtkUriHandler;
import com.kuaishou.tuna_core.button.TunaButtonRouterHandler;
import com.kuaishou.tuna.plc.dynamic_container.router.LocalLifeHalfContainerRouterHandler;
import com.kwai.kds.krn.api.page.KwaiKrnDialogUriHandler;
import com.kwai.kds.krn.api.page.KwaiKrnBottomSheetUriHandler;
import com.yxcorp.gifshow.social_arch.debug.OpenRubasDebugUriHandler;
import com.yxcorp.gifshow.ad.detail.router.AdLoginDetectionHandler;
import com.yxcorp.gifshow.ad.tachikoma.page.AdMkUriHandler;
import com.kuaishou.growth.pendant.activity.tools.PendantUriHandler;
import com.yxcorp.gifshow.growth.test.KwaiPopUriHandler;
import com.kuaishou.live.core.show.hotspot.LiveHotSpotRouterHandler;
import com.kwai.feature.platform.misc.logger.OpenLoggerChannelUriHandler;
import com.kuaishou.tuna.plc.dynamic_container.router.PlcDynamicContainerRouterHandler;
import com.yxcorp.gifshow.profile.ProfileEditUriHandler;

public class KRouterMetaConfig	// class@0012cf
{

    public void KRouterMetaConfig(){
       super();
    }
    public static void init(){
       if (PatchProxy.applyVoid(null, null, KRouterMetaConfig.class, "1")) {
          return;
       }
       d uod = new d("chat/group/userProfileGroupList", "com.yxcorp.gifshow.message.init.router.StickGroupUriHandler", new ArrayList(), new StickGroupUriHandler(), "");
       c.d(v0);
       d uod1 = new d("merchant/.*", "com.kuaishou.merchant.router.support.krouter.KRouterMerchantAnnotation$KwaiSchemeMerchantUriHandler", new ArrayList(), new KRouterMerchantAnnotation$KwaiSchemeMerchantUriHandler(), "");
       c.d(v0);
       uod = new d("addetail/.*", "com.yxcorp.gifshow.ad.detail.router.AdDetailUriHandler", new ArrayList(), new AdDetailUriHandler(), "");
       c.d(v0);
       uod1 = new d("moment/detail.*", "com.yxcorp.gifshow.moment.detail.MomentDetailHandler", new ArrayList(), null, "moment");
       c.d(v0);
       uod = new d("work_tablet/.*", "com.yxcorp.gifshow.detail.PhotoDetailActivityTablet", new ArrayList(), null, "");
       c.d(v0);
       uod1 = new d("profile_table/.*", "com.yxcorp.gifshow.profile.activity.UserProfileActivityTablet", new ArrayList(), null, "");
       c.d(v0);
       uod = new d("home/.*", "com.yxcorp.gifshow.HomeHandler", new ArrayList(), new HomeHandler(), "");
       c.d(v0);
       uod1 = new d("live/authenticate.*", "com.kuaishou.live.external.authenticate.LiveAuthenticateUriRouterHandler", new ArrayList(), new LiveAuthenticateUriRouterHandler(), "");
       c.d(v0);
       uod = new d("relation/follow", "com.yxcorp.gifshow.relation.util.KwaiRelationFollowHandler", new ArrayList(), new KwaiRelationFollowHandler(), "");
       c.d(v0);
       uod1 = new d("newsslide/.*", "com.yxcorp.gifshow.reminder.news.NewsSlidePlayUriHandler", new ArrayList(), new NewsSlidePlayUriHandler(), "");
       c.d(v0);
       uod = new d("action/bringToFront.*", "com.yxcorp.gifshow.BringToFrontHandler", new ArrayList(), new BringToFrontHandler(), "");
       c.d(v0);
       uod1 = new d("friends/.*", "com.yxcorp.gifshow.reminder.friend.FriendsHandler", new ArrayList(), new FriendsHandler(), "");
       c.d(v0);
       uod = new d("bind/phone.*", "com.yxcorp.login.bind.BindPhoneControllerActivity", new ArrayList(), null, "");
       c.d(v0);
       uod1 = new d("imMessage/rtc/*", "com.yxcorp.gifshow.message.init.router.rtc.IMRTCUriHandler", new ArrayList(), new IMRTCUriHandler(), "");
       c.d(v0);
       uod = new d("article/.*", "com.yxcorp.gifshow.detail.DetailUriRouterHandler", new ArrayList(), new DetailUriRouterHandler(), "");
       c.d(v0);
       uod1 = new d("live/play/.*", "com.kuaishou.live.core.basic.activity.LivePlayActivity", new ArrayList(), null, "");
       c.d(v0);
       uod = new d("rank/.*", "com.yxcorp.gifshow.billboard.KwaiRankActivity", new ArrayList(), null, "");
       c.d(v0);
       uod1 = new d("retain/.*", "com.yxcorp.gifshow.growth.shortcut.UninstallToStayActivity", new ArrayList(), null, "");
       c.d(v0);
       uod = new d("tube/.*", "com.yxcorp.gifshow.tube.TubeRouterActivity", new ArrayList(), null, "tube_plugin");
       c.d(v0);
       uod1 = new d("featured/.*", "com.yxcorp.gifshow.FeaturedHandler", new ArrayList(), new FeaturedHandler(), "");
       c.d(v0);
       uod = new d("work/.*", "com.yxcorp.gifshow.detail.PhotoDetailActivity", new ArrayList(), null, "");
       c.d(v0);
       uod1 = new d("kwainative://user/realNameAuthentication", "com.yxcorp.gifshow.message.init.router.NativeRealNameUriHandler", new ArrayList(), new NativeRealNameUriHandler(), "");
       c.d(v0);
       uod = new d("kwaimerchant://*", "com.kuaishou.merchant.router.support.krouter.KRouterMerchantAnnotation$KwaiMerchantSchemeUriHandler", new ArrayList(), new KRouterMerchantAnnotation$KwaiMerchantSchemeUriHandler(), "");
       c.d(v0);
       uod1 = new d("search/.*", "com.yxcorp.plugin.search.SearchUriRouterHandler", new ArrayList(), new SearchUriRouterHandler(), "");
       c.d(v0);
       uod = new d("adcommonweb/.*", "com.yxcorp.gifshow.ad.detail.router.AdCommonWebUriHandler", new ArrayList(), new AdCommonWebUriHandler(), "");
       c.d(v0);
       uod1 = new d("adwebview/.*", "com.yxcorp.gifshow.ad.webview.AdYodaActivity", new ArrayList(), null, "");
       c.d(v0);
       uod = new d("neo/.*", "com.yxcorp.gifshow.ad.award.scheme.NeoUriHandler", new ArrayList(), new NeoUriHandler(), "");
       c.d(v0);
       uod1 = new d("sharemedia/.*", "com.kwai.feature.post.api.thirdparty.ThirdPartyKRouterUriHandler", new ArrayList(), new ThirdPartyKRouterUriHandler(), "");
       c.d(v0);
       uod = new d("moment/momentDetail", "com.yxcorp.gifshow.moment.detail.MomentDetailHandlerV2", new ArrayList(), null, "moment");
       c.d(v0);
       uod1 = new d("merchantdetail/.*", "com.kuaishou.merchant.router.support.PreloaderUriHandler", new ArrayList(), new PreloaderUriHandler(), "");
       c.d(v0);
       uod = new d("kwainative://message/*", "com.yxcorp.gifshow.message.init.router.MessageUriHandler", new ArrayList(), new MessageUriHandler(), "");
       c.d(v0);
       uod1 = new d("pushCoin/.*", "com.yxcorp.gifshow.growth.push.coin.PushCoinUriHandler", new ArrayList(), new PushCoinUriHandler(), "");
       c.d(v0);
       uod = new d("user/realNameAuthentication", "com.yxcorp.gifshow.message.init.router.RealNameUriHandler", new ArrayList(), new RealNameUriHandler(), "");
       c.d(v0);
       uod1 = new d("recordalbum/.*", "com.yxcorp.gifshow.camera.record.album.RecordAlbumActivity", new ArrayList(), null, "");
       c.d(v0);
       uod = new d("profile/.*", "com.yxcorp.gifshow.profile.activity.UserProfileActivity", new ArrayList(), null, "");
       c.d(v0);
       uod1 = new d("live_tablet/play/.*", "com.kuaishou.live.core.basic.activity.LivePlayActivityTablet", new ArrayList(), null, "");
       c.d(v0);
       b uob = new b("followFansListSettings", "com.yxcorp.gifshow.relation.plugin.RelationRouterHandler", new ArrayList(), new RelationRouterHandler(), "");
       c.c("followFansListSettings", v0);
       b uob1 = new b("liveReservation", "com.kuaishou.live.external.subscribe.LiveImmediatelySubscribeUriRouterHandler", new ArrayList(), new LiveImmediatelySubscribeUriRouterHandler(), "");
       c.c("liveReservation", v0);
       uob1 = new b("notice/push", "com.yxcorp.gifshow.message.notice.push.NoticePushHandler", new ArrayList(), null, "im_plugin");
       c.c("notice/push", v0);
       uob1 = new b("mywallet", "com.yxcorp.plugin.payment.MyWalletRouterUriHandler", new ArrayList(), new MyWalletRouterUriHandler(), "");
       c.c("mywallet", v0);
       uob1 = new b("settings/clear_cache", "com.yxcorp.plugin.setting.cache.activity.ClearCacheActivity", new ArrayList(), null, "");
       c.c("settings/clear_cache", v0);
       uob1 = new b("autologin/login", "com.yxcorp.login.userlogin.activity.AutoLoginActivity", new ArrayList(), null, "");
       c.c("autologin/login", v0);
       uob1 = new b("liveaggregatesquare", "com.kuaishou.live.core.basic.liveslide.urihandler.LiveSlideUriHandler", new ArrayList(), new LiveSlideUriHandler(), "");
       c.c("liveaggregatesquare", v0);
       uob1 = new b("intimateRelation/invitation", "com.yxcorp.gifshow.relation.intimate.helper.IntimateRouterHandler", new ArrayList(), new IntimateRouterHandler(), "");
       c.c("intimateRelation/invitation", v0);
       uob1 = new b("setting/live", "com.kuaishou.live.external.LiveSettingsActivity", new ArrayList(), null, "");
       c.c("setting/live", v0);
       uob1 = new b("koiPage", "com.kwai.component.fansgroup.detail.KoiKrnDetailUriHandler2", new ArrayList(), new KoiKrnDetailUriHandler2(), "");
       c.c("koiPage", v0);
       uob1 = new b("koiPanelWrapper", "com.kwai.component.fansgroup.detail.KoiKrnDetailUriHandler2", new ArrayList(), new KoiKrnDetailUriHandler2(), "");
       c.c("koiPanelWrapper", v0);
       uob1 = new b("fansGroupList", "com.kwai.component.fansgroup.fansgrouplist.FansGroupUriHandler", new ArrayList(), new FansGroupUriHandler(), "");
       c.c("fansGroupList", v0);
       uob1 = new b("liveHalfReservation", "com.kuaishou.live.external.subscribe.LiveHalfSubscribeUriRouterHandler", new ArrayList(), new LiveHalfSubscribeUriRouterHandler(), "");
       c.c("liveHalfReservation", v0);
       uob1 = new b("adtkpage", "com.yxcorp.gifshow.ad.tachikoma.page.AdtkUriHandler", new ArrayList(), new AdtkUriHandler(), "");
       c.c("adtkpage", v0);
       uob1 = new b("tuna/button", "com.kuaishou.tuna_core.button.TunaButtonRouterHandler", new ArrayList(), new TunaButtonRouterHandler(), "");
       c.c("tuna/button", v0);
       uob1 = new b("merchant/selfdetail", "com.kuaishou.merchant.router.support.PreloaderUriHandler", new ArrayList(), new PreloaderUriHandler(), "");
       c.c("merchant/selfdetail", v0);
       uob1 = new b("merchant/halfselfdetail", "com.kuaishou.merchant.router.support.PreloaderUriHandler", new ArrayList(), new PreloaderUriHandler(), "");
       c.c("merchant/halfselfdetail", v0);
       uob1 = new b("merchant/detailv2", "com.kuaishou.merchant.router.support.PreloaderUriHandler", new ArrayList(), new PreloaderUriHandler(), "");
       c.c("merchant/detailv2", v0);
       uob1 = new b("merchantinterpretation", "com.kuaishou.merchant.router.support.PreloaderUriHandler", new ArrayList(), new PreloaderUriHandler(), "");
       c.c("merchantinterpretation", v0);
       uob1 = new b("locallife/half", "com.kuaishou.tuna.plc.dynamic_container.router.LocalLifeHalfContainerRouterHandler", new ArrayList(), new LocalLifeHalfContainerRouterHandler(), "");
       c.c("locallife/half", v0);
       uob1 = new b("kds/react/dialog", "com.kwai.kds.krn.api.page.KwaiKrnDialogUriHandler", new ArrayList(), new KwaiKrnDialogUriHandler(), "");
       c.c("kds/react/dialog", v0);
       uob1 = new b("kds/vue/dialog", "com.kwai.kds.krn.api.page.KwaiKrnDialogUriHandler", new ArrayList(), new KwaiKrnDialogUriHandler(), "");
       c.c("kds/vue/dialog", v0);
       uob1 = new b("kds/react/bottom_sheet", "com.kwai.kds.krn.api.page.KwaiKrnBottomSheetUriHandler", new ArrayList(), new KwaiKrnBottomSheetUriHandler(), "");
       c.c("kds/react/bottom_sheet", v0);
       uob1 = new b("kds/vue/bottom_sheet", "com.kwai.kds.krn.api.page.KwaiKrnBottomSheetUriHandler", new ArrayList(), new KwaiKrnBottomSheetUriHandler(), "");
       c.c("kds/vue/bottom_sheet", v0);
       uob1 = new b("bind_rubas_ds", "com.yxcorp.gifshow.social_arch.debug.OpenRubasDebugUriHandler", new ArrayList(), new OpenRubasDebugUriHandler(), "");
       c.c("bind_rubas_ds", v0);
       uob1 = new b("aduserlogin", "com.yxcorp.gifshow.ad.detail.router.AdLoginDetectionHandler", new ArrayList(), new AdLoginDetectionHandler(), "");
       c.c("aduserlogin", v0);
       uob1 = new b("adtkpage/moli", "com.yxcorp.gifshow.ad.tachikoma.page.AdMkUriHandler", new ArrayList(), new AdMkUriHandler(), "");
       c.c("adtkpage/moli", v0);
       uob1 = new b("pendant/link", "com.kuaishou.growth.pendant.activity.tools.PendantUriHandler", new ArrayList(), new PendantUriHandler(), "");
       c.c("pendant/link", v0);
       uob1 = new b("kwaiPop/link", "com.yxcorp.gifshow.growth.test.KwaiPopUriHandler", new ArrayList(), new KwaiPopUriHandler(), "");
       c.c("kwaiPop/link", v0);
       uob1 = new b("livehotspotdetail", "com.kuaishou.live.core.show.hotspot.LiveHotSpotRouterHandler", new ArrayList(), new LiveHotSpotRouterHandler(), "");
       c.c("livehotspotdetail", v0);
       uob1 = new b("openloggerchannel", "com.kwai.feature.platform.misc.logger.OpenLoggerChannelUriHandler", new ArrayList(), new OpenLoggerChannelUriHandler(), "");
       c.c("openloggerchannel", v0);
       uob1 = new b("codcontainer", "com.kuaishou.tuna.plc.dynamic_container.router.PlcDynamicContainerRouterHandler", new ArrayList(), new PlcDynamicContainerRouterHandler(), "");
       c.c("codcontainer", v0);
       uob1 = new b("pushCoin", "com.yxcorp.gifshow.growth.push.coin.PushCoinUriHandler", new ArrayList(), new PushCoinUriHandler(), "");
       c.c("pushCoin", v0);
       uob1 = new b("notice/noticeBoxDetail", "com.yxcorp.gifshow.notice.box.detail.NoticeBoxDetailActivity", new ArrayList(), null, "");
       c.c("notice/noticeBoxDetail", v0);
       uob1 = new b("profilesetting", "com.yxcorp.gifshow.profile.ProfileEditUriHandler", new ArrayList(), new ProfileEditUriHandler(), "");
       c.c("profilesetting", v0);
       uob1 = new b("userinfodetailedit/editIntroduction", "com.yxcorp.gifshow.profile.ProfileEditUriHandler", new ArrayList(), new ProfileEditUriHandler(), "");
       c.c("userinfodetailedit/editIntroduction", v0);
       uob1 = new b("school/select", "com.yxcorp.gifshow.profile.ProfileEditUriHandler", new ArrayList(), new ProfileEditUriHandler(), "");
       c.c("school/select", v0);
       return;
    }
}
