package com.kuaishou.ax2c.layouts.X2C_Edit_Tab_Container_Layout;
import com.kuaishou.ax2c.IViewCreator;
import java.lang.Object;
import android.content.Context;
import android.view.View;
import android.content.res.Resources;
import android.widget.RelativeLayout;
import android.widget.RelativeLayout$LayoutParams;
import android.view.ViewGroup$LayoutParams;
import com.kwai.feature.post.api.widget.PostRadioGroupWithIndicator;
import cw9.c;
import com.kwai.feature.post.api.widget.PostGroupWithIndicator;
import android.widget.FrameLayout;
import android.util.DisplayMetrics;
import android.util.TypedValue;
import com.kwai.library.widget.button.KwaiRadioGroup;
import android.widget.FrameLayout$LayoutParams;
import android.widget.RadioGroup;
import com.kwai.library.widget.button.SizeAdjustableRadioButton;
import android.util.AttributeSet;
import android.widget.RadioGroup$LayoutParams;
import android.graphics.drawable.Drawable;
import androidx.appcompat.widget.AppCompatRadioButton;
import android.widget.RadioButton;
import android.text.TextUtils$TruncateAt;

public class X2C_Edit_Tab_Container_Layout implements IViewCreator	// class@0010a5
{

    public void X2C_Edit_Tab_Container_Layout(){
       super();
    }
    public View createView(Context p0){
       Resources resources = p0.getResources();
       RelativeLayout relativeLayo = new RelativeLayout(p0);
       relativeLayo.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       PostRadioGroupWithIndicator postRadioGro = new PostRadioGroupWithIndicator(relativeLayo.getContext());
       RelativeLayout$LayoutParams layoutParams = new RelativeLayout$LayoutParams(-1, c.b(resources, 0x7f070378));
       postRadioGro.setIndicatorBottomMargin(c.b(resources, R.dimen.arg_RES_7f07034b));
       postRadioGro.setIndicatorColor(resources.getColor(R.color.arg_RES_7f061ff3));
       postRadioGro.setIndicatorWidth(c.b(resources, R.dimen.arg_RES_7f070271));
       postRadioGro.setIndicatorHeight(c.b(resources, R.dimen.arg_RES_7f07030a));
       postRadioGro.setId(R.id.tabs_container);
       layoutParams.topMargin = c.b(resources, 0x7f070329);
       layoutParams.bottomMargin = c.b(resources, 0x7f070329);
       layoutParams.rightMargin = c.b(resources, 0x7f0702ac);
       postRadioGro.setIndicatorColor(resources.getColor(R.color.arg_RES_7f0601cb));
       postRadioGro.setIndicatorBottomMargin(c.b(resources, R.dimen.arg_RES_7f070329));
       postRadioGro.setIndicatorWidth(c.b(resources, R.dimen.arg_RES_7f0702b8));
       postRadioGro.setIndicatorHeight(c.b(resources, R.dimen.arg_RES_7f0702e3));
       postRadioGro.setPadding((int)TypedValue.applyDimension(1, 0, c.c(resources)), (int)TypedValue.applyDimension(1, 0, c.c(resources)), (int)TypedValue.applyDimension(1, 0, c.c(resources)), (int)TypedValue.applyDimension(1, 0, c.c(resources)));
       postRadioGro.setLayoutParams(layoutParams);
       relativeLayo.addView(postRadioGro);
       KwaiRadioGroup kwaiRadioGro = new KwaiRadioGroup(postRadioGro.getContext());
       FrameLayout$LayoutParams layoutParams1 = new FrameLayout$LayoutParams(-2, -1);
       kwaiRadioGro.setId(R.id.radio_group);
       layoutParams1.gravity = 17;
       kwaiRadioGro.setOrientation(0);
       kwaiRadioGro.setLayoutParams(layoutParams1);
       postRadioGro.addView(kwaiRadioGro);
       SizeAdjustableRadioButton sizeAdjustab = new SizeAdjustableRadioButton(kwaiRadioGro.getContext(), null, 0);
       sizeAdjustab.setBackgroundDrawable(null);
       sizeAdjustab.setId(R.id.button1);
       sizeAdjustab.setBackgroundDrawable(null);
       sizeAdjustab.setChecked(0);
       sizeAdjustab.setEllipsize(TextUtils$TruncateAt.END);
       sizeAdjustab.setGravity(17);
       sizeAdjustab.setShadowLayer(sizeAdjustab.getShadowRadius(), sizeAdjustab.getShadowDx(), sizeAdjustab.getShadowDy(), resources.getColor(R.color.arg_RES_7f062040));
       sizeAdjustab.setShadowLayer(sizeAdjustab.getShadowRadius(), 0, sizeAdjustab.getShadowDy(), sizeAdjustab.getShadowColor());
       sizeAdjustab.setShadowLayer(sizeAdjustab.getShadowRadius(), sizeAdjustab.getShadowDx(), 0x3f800000, sizeAdjustab.getShadowColor());
       sizeAdjustab.setShadowLayer(3.00f, sizeAdjustab.getShadowDx(), sizeAdjustab.getShadowDy(), sizeAdjustab.getShadowColor());
       sizeAdjustab.setSingleLine(1);
       sizeAdjustab.setText(R.string.arg_RES_7f103c5b);
       sizeAdjustab.setTextColor(resources.getColor(R.color.arg_RES_7f061f5b));
       sizeAdjustab.setTextSize(0, (float)c.b(resources, R.dimen.arg_RES_7f070f72));
       sizeAdjustab.setBackgroundDrawable(null);
       sizeAdjustab.setLayoutParams(new RadioGroup$LayoutParams(-2, -1));
       kwaiRadioGro.addView(sizeAdjustab);
       sizeAdjustab = new SizeAdjustableRadioButton(kwaiRadioGro.getContext(), null, 0);
       sizeAdjustab.setBackgroundDrawable(null);
       sizeAdjustab.setId(R.id.button2);
       sizeAdjustab.setBackgroundDrawable(null);
       sizeAdjustab.setChecked(0);
       sizeAdjustab.setEllipsize(TextUtils$TruncateAt.END);
       sizeAdjustab.setGravity(17);
       sizeAdjustab.setShadowLayer(sizeAdjustab.getShadowRadius(), sizeAdjustab.getShadowDx(), sizeAdjustab.getShadowDy(), resources.getColor(R.color.arg_RES_7f062040));
       sizeAdjustab.setShadowLayer(sizeAdjustab.getShadowRadius(), 0, sizeAdjustab.getShadowDy(), sizeAdjustab.getShadowColor());
       sizeAdjustab.setShadowLayer(sizeAdjustab.getShadowRadius(), sizeAdjustab.getShadowDx(), 0x3f800000, sizeAdjustab.getShadowColor());
       sizeAdjustab.setShadowLayer(3.00f, sizeAdjustab.getShadowDx(), sizeAdjustab.getShadowDy(), sizeAdjustab.getShadowColor());
       sizeAdjustab.setSingleLine(1);
       sizeAdjustab.setText(R.string.arg_RES_7f10162d);
       sizeAdjustab.setTextColor(resources.getColor(R.color.arg_RES_7f061f5b));
       sizeAdjustab.setTextSize(0, (float)c.b(resources, R.dimen.arg_RES_7f070f72));
       sizeAdjustab.setBackgroundDrawable(null);
       sizeAdjustab.setLayoutParams(new RadioGroup$LayoutParams(-2, -1));
       kwaiRadioGro.addView(sizeAdjustab);
       sizeAdjustab = new SizeAdjustableRadioButton(kwaiRadioGro.getContext(), null, 0);
       sizeAdjustab.setBackgroundDrawable(null);
       sizeAdjustab.setId(R.id.button3);
       sizeAdjustab.setBackgroundDrawable(null);
       sizeAdjustab.setChecked(0);
       sizeAdjustab.setEllipsize(TextUtils$TruncateAt.END);
       sizeAdjustab.setGravity(17);
       sizeAdjustab.setShadowLayer(sizeAdjustab.getShadowRadius(), sizeAdjustab.getShadowDx(), sizeAdjustab.getShadowDy(), resources.getColor(R.color.arg_RES_7f062040));
       sizeAdjustab.setShadowLayer(sizeAdjustab.getShadowRadius(), 0, sizeAdjustab.getShadowDy(), sizeAdjustab.getShadowColor());
       sizeAdjustab.setShadowLayer(sizeAdjustab.getShadowRadius(), sizeAdjustab.getShadowDx(), 0x3f800000, sizeAdjustab.getShadowColor());
       sizeAdjustab.setShadowLayer(3.00f, sizeAdjustab.getShadowDx(), sizeAdjustab.getShadowDy(), sizeAdjustab.getShadowColor());
       sizeAdjustab.setSingleLine(1);
       sizeAdjustab.setText(R.string.arg_RES_7f1030c7);
       sizeAdjustab.setTextColor(resources.getColor(R.color.arg_RES_7f061f5b));
       sizeAdjustab.setTextSize(0, (float)c.b(resources, R.dimen.arg_RES_7f070f72));
       sizeAdjustab.setBackgroundDrawable(null);
       sizeAdjustab.setLayoutParams(new RadioGroup$LayoutParams(-2, -1));
       kwaiRadioGro.addView(sizeAdjustab);
       postRadioGro.onFinishInflate();
       return relativeLayo;
    }
}
