package com.kuaishou.ax2c.layouts.X2C_Live_Square_Side_Bar_Layout;
import com.kuaishou.ax2c.IViewCreator;
import java.lang.Object;
import android.content.Context;
import android.view.View;
import android.content.res.Resources;
import android.widget.FrameLayout;
import android.widget.RelativeLayout$LayoutParams;
import android.view.ViewGroup$LayoutParams;
import android.widget.FrameLayout$LayoutParams;
import androidx.constraintlayout.widget.ConstraintLayout;
import android.view.ViewGroup;
import androidx.constraintlayout.widget.ConstraintLayout$LayoutParams;
import android.util.DisplayMetrics;
import cw9.c;
import android.util.TypedValue;
import androidx.appcompat.widget.AppCompatImageView;
import android.view.ViewGroup$MarginLayoutParams;
import android.widget.ImageView;
import com.kwai.feature.component.entry.view.SearchSwitcherEntryView;
import android.widget.LinearLayout;
import com.kwai.feature.component.entry.view.SearchBarEntryView;
import android.view.ViewStub;

public class X2C_Live_Square_Side_Bar_Layout implements IViewCreator	// class@001110
{

    public void X2C_Live_Square_Side_Bar_Layout(){
       super();
    }
    public View createView(Context p0){
       Resources resources = p0.getResources();
       FrameLayout uFrameLayout = new FrameLayout(p0);
       uFrameLayout.setId(R.id.live_slide_square_side_bar_container_layout);
       uFrameLayout.setVisibility(8);
       uFrameLayout.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       View view = new View(uFrameLayout.getContext());
       view.setId(R.id.live_slide_square_side_bar_shadow_layout);
       view.setBackgroundColor(resources.getColor(R.color.arg_RES_7f061c14));
       view.setVisibility(8);
       view.setLayoutParams(new FrameLayout$LayoutParams(-1, -1));
       uFrameLayout.addView(view);
       ConstraintLayout uConstraintL = new ConstraintLayout(uFrameLayout.getContext());
       uConstraintL.setId(R.id.live_slide_square_side_bar_layout);
       uConstraintL.setLayoutParams(new FrameLayout$LayoutParams(-1, -1));
       uFrameLayout.addView(uConstraintL);
       View view1 = new View(uConstraintL.getContext());
       ConstraintLayout$LayoutParams layoutParams = new ConstraintLayout$LayoutParams((int)TypedValue.applyDimension(1, 0, c.c(resources)), -1);
       view1.setBackgroundColor(resources.getColor(R.color.arg_RES_7f06076b));
       layoutParams.e = 0x7f0a25e6;
       layoutParams.g = 0;
       layoutParams.c();
       view1.setLayoutParams(layoutParams);
       uConstraintL.addView(view1);
       view1 = new View(uConstraintL.getContext());
       layoutParams = new ConstraintLayout$LayoutParams(c.b(resources, 0x7f07096f), -1);
       view1.setId(R.id.live_square_side_bar_dark_margin);
       view1.setBackgroundColor(resources.getColor(R.color.arg_RES_7f06076b));
       layoutParams.g = 0x7f0a25e6;
       layoutParams.c();
       view1.setLayoutParams(layoutParams);
       uConstraintL.addView(view1);
       AppCompatImageView uAppCompatIm = new AppCompatImageView(uConstraintL.getContext());
       layoutParams = new ConstraintLayout$LayoutParams((int)TypedValue.applyDimension(1, 28.00f, c.c(resources)), (int)TypedValue.applyDimension(1, 28.00f, c.c(resources)));
       layoutParams.topMargin = c.b(resources, 0x7f07034c);
       layoutParams.rightMargin = c.b(resources, 0x7f070356);
       uAppCompatIm.setImageResource(R.drawable.arg_RES_7f081486);
       layoutParams.f = 0x7f0a25d3;
       layoutParams.h = 0;
       layoutParams.c();
       uAppCompatIm.setLayoutParams(layoutParams);
       uConstraintL.addView(uAppCompatIm);
       view1 = new View(uConstraintL.getContext());
       layoutParams = new ConstraintLayout$LayoutParams(-1, c.b(resources, 0x7f0702ac));
       view1.setId(R.id.live_square_side_bar_layout_place_holder_view);
       layoutParams.h = 0;
       layoutParams.c();
       view1.setLayoutParams(layoutParams);
       uConstraintL.addView(view1);
       FrameLayout uFrameLayout1 = new FrameLayout(uConstraintL.getContext());
       layoutParams = new ConstraintLayout$LayoutParams(c.b(resources, 0x7f07096e), (int)TypedValue.applyDimension(1, 0, c.c(resources)));
       uFrameLayout1.setId(R.id.live_square_side_bar_layout_close_view);
       layoutParams.k = 0;
       layoutParams.d = 0;
       layoutParams.f = 0x7f0a25bb;
       layoutParams.i = 0x7f0a25e7;
       layoutParams.c();
       uFrameLayout1.setLayoutParams(layoutParams);
       uConstraintL.addView(uFrameLayout1);
       SearchSwitcherEntryView searchSwitch = new SearchSwitcherEntryView(uConstraintL.getContext());
       layoutParams = new ConstraintLayout$LayoutParams((int)TypedValue.applyDimension(1, 0, c.c(resources)), c.b(resources, 0x7f0702fe));
       searchSwitch.setId(R.id.live_slide_square_side_bar_search_switch_layout);
       searchSwitch.setGravity(17);
       layoutParams.rightMargin = (int)TypedValue.applyDimension(1, 8.00f, c.c(resources));
       layoutParams.topMargin = c.b(resources, 0x7f07034b);
       layoutParams.d = 0x7f0a25bb;
       layoutParams.f = 0x7f0a25bc;
       layoutParams.i = 0x7f0a25e7;
       searchSwitch.setVisibility(8);
       searchSwitch.setPadding(c.b(resources, R.dimen.arg_RES_7f070271), 0, c.b(resources, R.dimen.arg_RES_7f070271), 0);
       layoutParams.c();
       searchSwitch.setLayoutParams(layoutParams);
       uConstraintL.addView(searchSwitch);
       SearchBarEntryView searchBarEnt = new SearchBarEntryView(uConstraintL.getContext());
       layoutParams = new ConstraintLayout$LayoutParams(-2, c.b(resources, 0x7f0702fe));
       searchBarEnt.setId(R.id.live_slide_square_side_bar_search_right_button);
       layoutParams.leftMargin = c.b(resources, 0x7f07031b);
       layoutParams.rightMargin = c.b(resources, 0x7f07025d);
       searchBarEnt.setGravity(17);
       searchBarEnt.setVisibility(8);
       layoutParams.k = 0x7f0a25bd;
       layoutParams.e = 0x7f0a25bd;
       layoutParams.g = 0;
       layoutParams.h = 0x7f0a25bd;
       layoutParams.c();
       searchBarEnt.setLayoutParams(layoutParams);
       uConstraintL.addView(searchBarEnt);
       FrameLayout uFrameLayout2 = new FrameLayout(uConstraintL.getContext());
       ConstraintLayout$LayoutParams layoutParams1 = new ConstraintLayout$LayoutParams((int)TypedValue.applyDimension(1, 0, c.c(resources)), (int)TypedValue.applyDimension(1, 0, c.c(resources)));
       uFrameLayout2.setId(R.id.live_slide_square_side_bar_layout_fragment_layout);
       layoutParams1.u = (int)TypedValue.applyDimension(1, 0, c.c(resources));
       layoutParams1.topMargin = c.b(resources, 0x7f07031b);
       layoutParams1.rightMargin = c.b(resources, 0x7f07096d);
       layoutParams1.k = 0;
       layoutParams1.e = 0x7f0a25e6;
       layoutParams1.g = 0;
       layoutParams1.i = 0x7f0a25bd;
       layoutParams1.c();
       uFrameLayout2.setLayoutParams(layoutParams1);
       uConstraintL.addView(uFrameLayout2);
       ViewStub viewStub = new ViewStub(uConstraintL.getContext());
       viewStub.setInflatedId(-1);
       ConstraintLayout$LayoutParams layoutParams2 = new ConstraintLayout$LayoutParams(c.b(resources, 0x7f0702bc), c.b(resources, 0x7f070319));
       viewStub.setId(R.id.live_square_start_live_layout_view_stub);
       layoutParams2.bottomMargin = c.b(resources, 0x7f070319);
       viewStub.setLayoutResource(R.layout.arg_RES_7f0d0ddb);
       layoutParams2.k = 0;
       layoutParams2.d = 0x7f0a25bb;
       layoutParams2.g = 0x7f0a25bb;
       layoutParams2.c();
       viewStub.setLayoutParams(layoutParams2);
       uConstraintL.addView(viewStub);
       return uFrameLayout;
    }
}
