package com.kuaishou.ax2c.layouts.X2C_Record_Btn_Fullscreen_V3;
import com.kuaishou.ax2c.IViewCreator;
import java.lang.Object;
import android.content.Context;
import android.view.View;
import android.content.res.Resources;
import com.yxcorp.gifshow.camera.record.widget.RecordButton;
import android.util.AttributeSet;
import androidx.constraintlayout.widget.ConstraintLayout$LayoutParams;
import android.util.DisplayMetrics;
import cw9.c;
import java.lang.Integer;
import android.util.TypedValue;
import android.widget.FrameLayout;
import android.view.ViewGroup$LayoutParams;
import com.yxcorp.widget.selector.view.SelectShapeView;
import android.widget.FrameLayout$LayoutParams;
import android.widget.ImageView;
import com.kuaishou.ax2c.XmlAttrHostImpl;
import com.kuaishou.ax2c.IAttrHost;
import ald.b;
import java.lang.String;
import android.graphics.Color;
import com.yxcorp.gifshow.widget.record.RecordRoundProgressView;
import com.yxcorp.gifshow.camera.record.breakpoint.BreakpointIndicator;
import com.yxcorp.gifshow.camera.record.widget.RecordInnerAnimView;
import com.kwai.library.widget.textview.SizeAdjustableTextView;
import android.widget.TextView;
import androidx.appcompat.widget.AppCompatTextView;
import com.kwai.library.widget.textview.KwaiSizeAdjustableTextView;

public class X2C_Record_Btn_Fullscreen_V3 implements IViewCreator	// class@001120
{

    public void X2C_Record_Btn_Fullscreen_V3(){
       super();
    }
    public View createView(Context p0){
       Resources resources = p0.getResources();
       RecordButton recordButton = new RecordButton(p0, null, 0);
       Integer integer = Integer.valueOf(1);
       recordButton.setId(R.id.record_btn_layout);
       recordButton.setClipChildren(0);
       recordButton.setLayoutParams(new ConstraintLayout$LayoutParams((int)TypedValue.applyDimension(1, 102.00f, c.c(resources)), (int)TypedValue.applyDimension(1, 102.00f, c.c(resources))));
       SelectShapeView selectShapeV = new SelectShapeView(recordButton.getContext());
       FrameLayout$LayoutParams layoutParams = new FrameLayout$LayoutParams(c.b(resources, 0x7f070d7a), c.b(resources, 0x7f070d7a));
       selectShapeV.setId(R.id.record_btn_outer_shadow_ring);
       layoutParams.gravity = 17;
       XmlAttrHostImpl xmlAttrHostI = new XmlAttrHostImpl();
       xmlAttrHostI.addAttr(30, Integer.valueOf(resources.getColor(R.color.arg_RES_7f061f72)));
       xmlAttrHostI.addAttr(26, integer);
       xmlAttrHostI.addAttr(34, Integer.valueOf((int)TypedValue.applyDimension(1, 0x3f800000, c.c(resources))));
       IAttrHost[] iAttrHostArr = new IAttrHost[]{xmlAttrHostI,new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl()};
       selectShapeV.setAttrs(iAttrHostArr);
       selectShapeV.setLayoutParams(layoutParams);
       recordButton.addView(selectShapeV);
       FrameLayout uFrameLayout = new FrameLayout(recordButton.getContext());
       layoutParams = new FrameLayout$LayoutParams((int)TypedValue.applyDimension(1, 78.00f, c.c(resources)), (int)TypedValue.applyDimension(1, 78.00f, c.c(resources)));
       uFrameLayout.setId(R.id.record_btn);
       layoutParams.gravity = 17;
       uFrameLayout.setClipChildren(0);
       uFrameLayout.setLayoutParams(layoutParams);
       recordButton.addView(uFrameLayout);
       SelectShapeView selectShapeV1 = new SelectShapeView(uFrameLayout.getContext());
       selectShapeV1.setId(R.id.record_btn_bg);
       selectShapeV1.setVisibility(4);
       XmlAttrHostImpl xmlAttrHostI1 = new XmlAttrHostImpl();
       xmlAttrHostI1.addAttr(26, integer);
       xmlAttrHostI1.addAttr(29, Integer.valueOf(Color.parseColor("#80D7D7D7")));
       IAttrHost[] iAttrHostArr1 = new IAttrHost[]{xmlAttrHostI1,new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl()};
       selectShapeV1.setAttrs(iAttrHostArr1);
       selectShapeV1.setLayoutParams(new FrameLayout$LayoutParams(-1, -1));
       uFrameLayout.addView(selectShapeV1);
       selectShapeV1 = new SelectShapeView(uFrameLayout.getContext());
       selectShapeV1.setId(R.id.record_ring);
       XmlAttrHostImpl xmlAttrHostI2 = new XmlAttrHostImpl();
       xmlAttrHostI2.addAttr(30, Integer.valueOf(resources.getColor(0x106000b)));
       xmlAttrHostI2.addAttr(26, integer);
       xmlAttrHostI2.addAttr(34, Integer.valueOf((int)TypedValue.applyDimension(1, 4.00f, c.c(resources))));
       iAttrHostArr = new IAttrHost[]{xmlAttrHostI2,new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl()};
       selectShapeV1.setAttrs(iAttrHostArr);
       selectShapeV1.setLayoutParams(new FrameLayout$LayoutParams(-1, -1));
       uFrameLayout.addView(selectShapeV1);
       RecordRoundProgressView recordRoundP = new RecordRoundProgressView(uFrameLayout.getContext());
       FrameLayout$LayoutParams layoutParams1 = new FrameLayout$LayoutParams(-1, -1);
       recordRoundP.setId(R.id.progress);
       layoutParams1.gravity = 17;
       recordRoundP.setMax(100);
       recordRoundP.setProgress(0);
       recordRoundP.setLayoutParams(layoutParams1);
       uFrameLayout.addView(recordRoundP);
       recordRoundP.onFinishInflate();
       BreakpointIndicator uBreakpointI = new BreakpointIndicator(uFrameLayout.getContext());
       layoutParams1 = new FrameLayout$LayoutParams(-1, -1);
       uBreakpointI.setId(R.id.record_btn_breakpoint_indicator);
       layoutParams1.gravity = 17;
       uBreakpointI.setVisibility(8);
       uBreakpointI.setLayoutParams(layoutParams1);
       uFrameLayout.addView(uBreakpointI);
       RecordInnerAnimView recordInnerA = new RecordInnerAnimView(recordButton.getContext());
       layoutParams = new FrameLayout$LayoutParams((int)TypedValue.applyDimension(1, 64.00f, c.c(resources)), (int)TypedValue.applyDimension(1, 64.00f, c.c(resources)));
       recordInnerA.setId(R.id.inner_oval);
       layoutParams.gravity = 17;
       recordInnerA.setLayoutParams(layoutParams);
       recordButton.addView(recordInnerA);
       selectShapeV = new SelectShapeView(recordButton.getContext());
       layoutParams = new FrameLayout$LayoutParams((int)TypedValue.applyDimension(1, 64.00f, c.c(resources)), (int)TypedValue.applyDimension(1, 64.00f, c.c(resources)));
       selectShapeV.setId(R.id.inner_oval_bg);
       layoutParams.gravity = 17;
       selectShapeV.setVisibility(4);
       XmlAttrHostImpl xmlAttrHostI3 = new XmlAttrHostImpl();
       xmlAttrHostI3.addAttr(26, integer);
       xmlAttrHostI3.addAttr(29, Integer.valueOf(resources.getColor(R.color.arg_RES_7f061f71)));
       IAttrHost[] iAttrHostArr2 = new IAttrHost[]{xmlAttrHostI3,new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl()};
       selectShapeV.setAttrs(iAttrHostArr2);
       selectShapeV.setLayoutParams(layoutParams);
       recordButton.addView(selectShapeV);
       View view = new View(recordButton.getContext());
       layoutParams = new FrameLayout$LayoutParams(c.b(resources, 0x7f07030d), c.b(resources, 0x7f07030d));
       view.setId(R.id.icon_record);
       layoutParams.gravity = 17;
       view.setVisibility(8);
       view.setBackgroundResource(R.drawable.arg_RES_7f08200d);
       view.setLayoutParams(layoutParams);
       recordButton.addView(view);
       view = new View(recordButton.getContext());
       layoutParams = new FrameLayout$LayoutParams((int)TypedValue.applyDimension(1, 40.00f, c.c(resources)), (int)TypedValue.applyDimension(1, 40.00f, c.c(resources)));
       view.setId(R.id.icon_pause);
       layoutParams.gravity = 17;
       view.setBackgroundResource(R.drawable.arg_RES_7f081c36);
       view.setVisibility(8);
       view.setLayoutParams(layoutParams);
       recordButton.addView(view);
       view = new View(recordButton.getContext());
       layoutParams = new FrameLayout$LayoutParams((int)TypedValue.applyDimension(1, 40.00f, c.c(resources)), (int)TypedValue.applyDimension(1, 40.00f, c.c(resources)));
       view.setId(R.id.icon_complete);
       layoutParams.gravity = 17;
       view.setBackgroundResource(R.drawable.arg_RES_7f082043);
       view.setVisibility(8);
       view.setLayoutParams(layoutParams);
       recordButton.addView(view);
       SizeAdjustableTextView sizeAdjustab = new SizeAdjustableTextView(recordButton.getContext());
       layoutParams = new FrameLayout$LayoutParams(-2, -2);
       sizeAdjustab.setId(R.id.record_progress_txt);
       layoutParams.gravity = 49;
       sizeAdjustab.setIncludeFontPadding(0);
       sizeAdjustab.setMaxLines(1);
       sizeAdjustab.setTextColor(resources.getColor(R.color.arg_RES_7f061fd5));
       sizeAdjustab.setTextSize(0, (float)c.b(resources, R.dimen.arg_RES_7f070d78));
       sizeAdjustab.setInitTextSize(TypedValue.applyDimension(0, (float)c.b(resources, R.dimen.arg_RES_7f070d78), c.c(resources)));
       sizeAdjustab.setMaxWidth(c.b(resources, R.dimen.arg_RES_7f070256));
       sizeAdjustab.setShadowLayer(sizeAdjustab.getShadowRadius(), 3.00f, sizeAdjustab.getShadowDy(), sizeAdjustab.getShadowColor());
       sizeAdjustab.setShadowLayer(sizeAdjustab.getShadowRadius(), sizeAdjustab.getShadowDx(), 3.00f, sizeAdjustab.getShadowColor());
       sizeAdjustab.setShadowLayer(sizeAdjustab.getShadowRadius(), sizeAdjustab.getShadowDx(), sizeAdjustab.getShadowDy(), resources.getColor(R.color.arg_RES_7f06010e));
       sizeAdjustab.setShadowLayer(0x3f800000, sizeAdjustab.getShadowDx(), sizeAdjustab.getShadowDy(), sizeAdjustab.getShadowColor());
       sizeAdjustab.setMinTextSize(TypedValue.applyDimension(0, (float)c.b(resources, R.dimen.arg_RES_7f070283), c.c(resources)));
       sizeAdjustab.setTextSizeAdjustable(1);
       sizeAdjustab.setLayoutParams(layoutParams);
       recordButton.addView(sizeAdjustab);
       recordButton.onFinishInflate();
       return recordButton;
    }
}
