package com.kuaishou.ax2c.layouts.X2C_Camera_Action_Bar_Magic_Layout;
import com.kuaishou.ax2c.IViewCreator;
import java.lang.Object;
import android.content.Context;
import android.view.View;
import android.content.res.Resources;
import android.widget.LinearLayout;
import androidx.constraintlayout.widget.ConstraintLayout$LayoutParams;
import java.lang.CharSequence;
import android.view.ViewGroup$LayoutParams;
import android.widget.FrameLayout;
import android.widget.LinearLayout$LayoutParams;
import com.yxcorp.widget.selector.view.SelectShapeView;
import android.widget.FrameLayout$LayoutParams;
import cw9.c;
import android.widget.ImageView;
import com.kuaishou.ax2c.XmlAttrHostImpl;
import java.lang.Integer;
import com.kuaishou.ax2c.IAttrHost;
import ald.b;
import com.yxcorp.gifshow.widget.PressedImageView;
import android.util.DisplayMetrics;
import android.util.TypedValue;
import android.graphics.drawable.Drawable;
import android.widget.ImageView$ScaleType;
import ac.b;
import com.facebook.drawee.view.DraweeView;
import yb.a;
import androidx.core.content.ContextCompat;
import xb.t$b;
import com.yxcorp.gifshow.widget.PostTabShaderFrameLayout;
import com.kwai.library.widget.textview.KwaiMarqueeTextView;
import android.widget.TextView;
import android.text.TextUtils$TruncateAt;
import androidx.appcompat.widget.AppCompatTextView;

public class X2C_Camera_Action_Bar_Magic_Layout implements IViewCreator	// class@00108f
{

    public void X2C_Camera_Action_Bar_Magic_Layout(){
       super();
    }
    public View createView(Context p0){
       Context uContext = p0;
       Resources resources = p0.getResources();
       LinearLayout linearLayout = new LinearLayout(uContext);
       linearLayout.setId(R.id.camera_magic_emoji);
       linearLayout.setOrientation(1);
       linearLayout.setContentDescription("magic_face");
       linearLayout.setGravity(1);
       linearLayout.setVisibility(8);
       linearLayout.setMotionEventSplittingEnabled(false);
       linearLayout.setLayoutParams(new ConstraintLayout$LayoutParams(-2, -2));
       FrameLayout uFrameLayout = new FrameLayout(linearLayout.getContext());
       uFrameLayout.setClipChildren(false);
       uFrameLayout.setLayoutParams(new LinearLayout$LayoutParams(-2, -2));
       linearLayout.addView(uFrameLayout);
       SelectShapeView selectShapeV = new SelectShapeView(uFrameLayout.getContext());
       selectShapeV.setId(R.id.button_magic_color_bg);
       selectShapeV.setVisibility(8);
       XmlAttrHostImpl xmlAttrHostI = new XmlAttrHostImpl();
       xmlAttrHostI.addAttr(26, Integer.valueOf(1));
       xmlAttrHostI.addAttr(29, Integer.valueOf(resources.getColor(R.color.arg_RES_7f061cea)));
       IAttrHost[] iAttrHostArr = new IAttrHost[]{xmlAttrHostI,new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl()};
       selectShapeV.setAttrs(iAttrHostArr);
       selectShapeV.setLayoutParams(new FrameLayout$LayoutParams(c.b(resources, R.dimen.arg_RES_7f070319), c.b(resources, R.dimen.arg_RES_7f070319)));
       uFrameLayout.addView(selectShapeV);
       PressedImageView pressedImage = new PressedImageView(uFrameLayout.getContext());
       FrameLayout$LayoutParams layoutParams = new FrameLayout$LayoutParams((int)TypedValue.applyDimension(1, 40.00f, c.c(resources)), (int)TypedValue.applyDimension(1, 40.00f, c.c(resources)));
       pressedImage.setBackgroundDrawable(null);
       pressedImage.setScaleType(ImageView$ScaleType.FIT_CENTER);
       pressedImage.setId(R.id.camera_magic_emoji_btn);
       layoutParams.gravity = 17;
       pressedImage.setClickable(false);
       pressedImage.getHierarchy().F(ContextCompat.getDrawable(uContext, R.drawable.arg_RES_7f081c1c));
       pressedImage.getHierarchy().u(t$b.e);
       pressedImage.setPressedAlpha(0.40f);
       pressedImage.setDisableAlpha(0.40f);
       pressedImage.setLayoutParams(layoutParams);
       uFrameLayout.addView(pressedImage);
       PostTabShaderFrameLayout postTabShade = new PostTabShaderFrameLayout(linearLayout.getContext());
       postTabShade.setFadingEdgeRight((int)TypedValue.applyDimension(1, 8.00f, c.c(resources)));
       postTabShade.setFadingEdgeLeft((int)TypedValue.applyDimension(1, 8.00f, c.c(resources)));
       postTabShade.setLayoutParams(new LinearLayout$LayoutParams(-2, -2));
       linearLayout.addView(postTabShade);
       KwaiMarqueeTextView kwaiMarqueeT = new KwaiMarqueeTextView(postTabShade.getContext());
       kwaiMarqueeT.setId(R.id.camera_magic_emoji_tv);
       kwaiMarqueeT.setEllipsize(TextUtils$TruncateAt.END);
       kwaiMarqueeT.setGravity(17);
       kwaiMarqueeT.setIncludeFontPadding(false);
       kwaiMarqueeT.setMaxWidth(c.b(resources, R.dimen.arg_RES_7f07032e));
       kwaiMarqueeT.setShadowLayer(kwaiMarqueeT.getShadowRadius(), kwaiMarqueeT.getShadowDx(), kwaiMarqueeT.getShadowDy(), resources.getColor(R.color.arg_RES_7f06010e));
       kwaiMarqueeT.setShadowLayer(kwaiMarqueeT.getShadowRadius(), 3.00f, kwaiMarqueeT.getShadowDy(), kwaiMarqueeT.getShadowColor());
       kwaiMarqueeT.setShadowLayer(kwaiMarqueeT.getShadowRadius(), kwaiMarqueeT.getShadowDx(), 3.00f, kwaiMarqueeT.getShadowColor());
       kwaiMarqueeT.setShadowLayer(0x3f800000, kwaiMarqueeT.getShadowDx(), kwaiMarqueeT.getShadowDy(), kwaiMarqueeT.getShadowColor());
       kwaiMarqueeT.setSingleLine(1);
       kwaiMarqueeT.setText(R.string.arg_RES_7f100485);
       kwaiMarqueeT.setTextColor(resources.getColor(R.color.arg_RES_7f0617f4));
       kwaiMarqueeT.setTextSize(false, (float)c.b(resources, R.dimen.arg_RES_7f070f6d));
       kwaiMarqueeT.setLayoutParams(new FrameLayout$LayoutParams(c.b(resources, R.dimen.arg_RES_7f07032a), c.b(resources, R.dimen.arg_RES_7f070120)));
       postTabShade.addView(kwaiMarqueeT);
       return linearLayout;
    }
}
