package com.kuaishou.ax2c.layouts.X2C_Fragment_Photos_Edit_Preview_V3_Full_Screen;
import com.kuaishou.ax2c.IViewCreator;
import java.lang.Object;
import android.content.Context;
import android.view.View;
import android.content.res.Resources;
import android.widget.RelativeLayout;
import android.view.ViewGroup$MarginLayoutParams;
import android.view.ViewGroup$LayoutParams;
import android.widget.RelativeLayout$LayoutParams;
import com.yxcorp.gifshow.v3.customizer.preview.EditorPreviewContainerLayout;
import com.kuaishou.ax2c.layouts.X2C_Pictures_Layout;
import androidx.appcompat.widget.AppCompatImageView;
import android.widget.ImageView;
import android.widget.ImageView$ScaleType;
import com.yxcorp.gifshow.widget.PassThroughEventView;
import com.yxcorp.gifshow.v3.editor.decoration.EditDecorationContainerView;
import android.util.DisplayMetrics;
import cw9.c;
import android.util.TypedValue;
import android.widget.AbsoluteLayout;
import com.yxcorp.gifshow.v3.editor.decoration.EditDecorationContainerViewV2;
import com.yxcorp.gifshow.decoration.widget.DecorationContainerView;
import com.yxcorp.gifshow.widget.EditorCropImageView;
import android.widget.FrameLayout;
import com.yxcorp.gifshow.image.KwaiImageView;
import com.yxcorp.gifshow.v3.editor.decoration.EditDecorationGuideContainer;
import com.yxcorp.gifshow.v3.editor.decoration.guideline.FakeFeedComponent;
import android.widget.FrameLayout$LayoutParams;
import com.kwai.library.widget.textview.SizeAdjustableTextView;
import android.widget.TextView;
import androidx.appcompat.widget.AppCompatTextView;
import com.kwai.library.widget.textview.KwaiSizeAdjustableTextView;
import android.graphics.Typeface;
import com.yxcorp.gifshow.v3.widget.EditorContainer;
import com.kuaishou.ax2c.layouts.X2C_New_Author_Widget_Preview;
import androidx.recyclerview.widget.RecyclerView;
import android.view.ViewGroup;
import com.kwai.feature.post.api.flywheel.widget.FlyWheelFrameLayout;
import android.widget.LinearLayout;
import android.widget.LinearLayout$LayoutParams;
import android.text.TextUtils$TruncateAt;
import android.graphics.drawable.Drawable;
import androidx.core.content.ContextCompat;
import java.lang.CharSequence;

public class X2C_Fragment_Photos_Edit_Preview_V3_Full_Screen implements IViewCreator	// class@0010ac
{

    public void X2C_Fragment_Photos_Edit_Preview_V3_Full_Screen(){
       super();
    }
    public View createView(Context p0){
       Context uContext = p0;
       Resources resources = p0.getResources();
       RelativeLayout relativeLayo = new RelativeLayout(uContext);
       relativeLayo.setClipChildren(false);
       relativeLayo.setClipToPadding(false);
       relativeLayo.setLayoutParams(new ViewGroup$MarginLayoutParams(-1, -1));
       RelativeLayout relativeLayo1 = new RelativeLayout(relativeLayo.getContext());
       relativeLayo1.setId(R.id.preview);
       relativeLayo1.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       relativeLayo.addView(relativeLayo1);
       EditorPreviewContainerLayout uEditorPrevi = new EditorPreviewContainerLayout(relativeLayo1.getContext());
       RelativeLayout$LayoutParams layoutParams = new RelativeLayout$LayoutParams(-1, -1);
       uEditorPrevi.setId(R.id.preview_player_container);
       layoutParams.addRule(13, -1);
       uEditorPrevi.setLayoutParams(layoutParams);
       relativeLayo1.addView(uEditorPrevi);
       View view = new X2C_Pictures_Layout().createView(uEditorPrevi.getContext());
       view.setBackgroundColor(resources.getColor(R.color.arg_RES_7f060624));
       view.setLayoutParams(view.getLayoutParams());
       uEditorPrevi.addView(view);
       AppCompatImageView uAppCompatIm = new AppCompatImageView(uEditorPrevi.getContext());
       uAppCompatIm.setId(R.id.photo_cover_showing_view);
       uAppCompatIm.setScaleType(ImageView$ScaleType.FIT_CENTER);
       uAppCompatIm.setVisibility(8);
       uAppCompatIm.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       uEditorPrevi.addView(uAppCompatIm);
       PassThroughEventView passThroughE = new PassThroughEventView(uEditorPrevi.getContext());
       passThroughE.setId(R.id.touch_view);
       passThroughE.setAlpha(0);
       passThroughE.setVisibility(false);
       passThroughE.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       uEditorPrevi.addView(passThroughE);
       EditDecorationContainerView uEditDecorat = new EditDecorationContainerView(relativeLayo1.getContext());
       layoutParams = new RelativeLayout$LayoutParams((int)TypedValue.applyDimension(1, 0, c.c(resources)), (int)TypedValue.applyDimension(1, 0, c.c(resources)));
       uEditDecorat.setId(R.id.decoration_editor_view);
       layoutParams.addRule(13, -1);
       uEditDecorat.setLayoutParams(layoutParams);
       relativeLayo1.addView(uEditDecorat);
       uEditDecorat.onFinishInflate();
       EditDecorationContainerViewV2 uEditDecorat1 = new EditDecorationContainerViewV2(relativeLayo1.getContext());
       layoutParams = new RelativeLayout$LayoutParams(-1, -1);
       uEditDecorat1.setId(R.id.new_text_decoration_editor_view);
       layoutParams.addRule(13, -1);
       uEditDecorat1.setVisibility(8);
       uEditDecorat1.setLayoutParams(layoutParams);
       relativeLayo1.addView(uEditDecorat1);
       uEditDecorat1.onFinishInflate();
       uEditDecorat = new EditDecorationContainerView(relativeLayo1.getContext());
       layoutParams = new RelativeLayout$LayoutParams((int)TypedValue.applyDimension(1, 0, c.c(resources)), (int)TypedValue.applyDimension(1, 0, c.c(resources)));
       uEditDecorat.setId(R.id.cover_decoration_editor_view);
       layoutParams.addRule(10, -1);
       layoutParams.addRule(14, -1);
       uEditDecorat.setVisibility(8);
       uEditDecorat.setLayoutParams(layoutParams);
       relativeLayo1.addView(uEditDecorat);
       uEditDecorat.onFinishInflate();
       uEditDecorat = new EditDecorationContainerView(relativeLayo1.getContext());
       layoutParams = new RelativeLayout$LayoutParams((int)TypedValue.applyDimension(1, 0, c.c(resources)), (int)TypedValue.applyDimension(1, 0, c.c(resources)));
       uEditDecorat.setId(R.id.lyric_decoration_editor_view);
       layoutParams.addRule(13, -1);
       uEditDecorat.setVisibility(8);
       uEditDecorat.setLayoutParams(layoutParams);
       relativeLayo1.addView(uEditDecorat);
       uEditDecorat.onFinishInflate();
       EditorCropImageView uEditorCropI = new EditorCropImageView(relativeLayo1.getContext());
       uEditorCropI.setId(R.id.photo_crop_view);
       uEditorCropI.setVisibility(4);
       uEditorCropI.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       relativeLayo1.addView(uEditorCropI);
       KwaiImageView kwaiImageVie = new KwaiImageView(relativeLayo1.getContext());
       layoutParams = new RelativeLayout$LayoutParams(-1, c.b(resources, 0x7f070325));
       kwaiImageVie.setId(R.id.long_picture_bottom_blank_mask);
       kwaiImageVie.setBackgroundColor(resources.getColor(R.color.arg_RES_7f0600a6));
       layoutParams.addRule(12, -1);
       kwaiImageVie.setVisibility(8);
       kwaiImageVie.setLayoutParams(layoutParams);
       relativeLayo1.addView(kwaiImageVie);
       EditDecorationGuideContainer uEditDecorat2 = new EditDecorationGuideContainer(relativeLayo.getContext());
       uEditDecorat2.setId(R.id.decoration_guide_container);
       uEditDecorat2.setVisibility(8);
       uEditDecorat2.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       relativeLayo.addView(uEditDecorat2);
       FakeFeedComponent uFakeFeedCom = new FakeFeedComponent(uEditDecorat2.getContext());
       uFakeFeedCom.setId(R.id.decoration_guide_fake_feed_component);
       uFakeFeedCom.setVisibility(8);
       uFakeFeedCom.setLayoutParams(new FrameLayout$LayoutParams(-1, -1));
       uEditDecorat2.addView(uFakeFeedCom);
       uEditDecorat2.onFinishInflate();
       View view1 = new View(relativeLayo.getContext());
       view1.setVisibility(8);
       view1.setId(R.id.intercept_view);
       view1.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       relativeLayo.addView(view1);
       SizeAdjustableTextView sizeAdjustab = new SizeAdjustableTextView(relativeLayo.getContext());
       RelativeLayout$LayoutParams layoutParams1 = new RelativeLayout$LayoutParams(-2, -2);
       sizeAdjustab.setId(R.id.text_tip);
       layoutParams1.addRule(14, -1);
       layoutParams1.topMargin = c.b(resources, 0x7f070273);
       sizeAdjustab.setGravity(17);
       sizeAdjustab.setMaxLines(1);
       sizeAdjustab.setShadowLayer(sizeAdjustab.getShadowRadius(), sizeAdjustab.getShadowDx(), sizeAdjustab.getShadowDy(), resources.getColor(R.color.arg_RES_7f061c12));
       sizeAdjustab.setShadowLayer(sizeAdjustab.getShadowRadius(), sizeAdjustab.getShadowDx(), 0x3f800000, sizeAdjustab.getShadowColor());
       sizeAdjustab.setShadowLayer(3.00f, sizeAdjustab.getShadowDx(), sizeAdjustab.getShadowDy(), sizeAdjustab.getShadowColor());
       sizeAdjustab.setText(R.string.arg_RES_7f104c2c);
       sizeAdjustab.setTextColor(resources.getColor(R.color.arg_RES_7f0606da));
       sizeAdjustab.setTextSize(false, (float)c.b(resources, R.dimen.arg_RES_7f070295));
       sizeAdjustab.setInitTextSize(TypedValue.applyDimension(false, (float)c.b(resources, R.dimen.arg_RES_7f070295), c.c(resources)));
       sizeAdjustab.setTypeface(null, 1);
       sizeAdjustab.setVisibility(4);
       sizeAdjustab.setTextSizeAdjustable(false);
       sizeAdjustab.setLayoutParams(layoutParams1);
       relativeLayo.addView(sizeAdjustab);
       sizeAdjustab = new SizeAdjustableTextView(relativeLayo.getContext());
       layoutParams1 = new RelativeLayout$LayoutParams(-2, -2);
       sizeAdjustab.setId(R.id.sticker_tip);
       layoutParams1.addRule(14, -1);
       layoutParams1.topMargin = c.b(resources, 0x7f070273);
       sizeAdjustab.setGravity(17);
       sizeAdjustab.setMaxLines(1);
       sizeAdjustab.setShadowLayer(sizeAdjustab.getShadowRadius(), sizeAdjustab.getShadowDx(), sizeAdjustab.getShadowDy(), resources.getColor(R.color.arg_RES_7f061c12));
       sizeAdjustab.setShadowLayer(sizeAdjustab.getShadowRadius(), sizeAdjustab.getShadowDx(), 0x3f800000, sizeAdjustab.getShadowColor());
       sizeAdjustab.setShadowLayer(3.00f, sizeAdjustab.getShadowDx(), sizeAdjustab.getShadowDy(), sizeAdjustab.getShadowColor());
       sizeAdjustab.setText(R.string.arg_RES_7f104aaa);
       sizeAdjustab.setTextColor(resources.getColor(R.color.arg_RES_7f0606da));
       sizeAdjustab.setTextSize(false, (float)c.b(resources, R.dimen.arg_RES_7f070295));
       sizeAdjustab.setInitTextSize(TypedValue.applyDimension(false, (float)c.b(resources, R.dimen.arg_RES_7f070295), c.c(resources)));
       sizeAdjustab.setTypeface(null, 1);
       sizeAdjustab.setVisibility(4);
       sizeAdjustab.setTextSizeAdjustable(false);
       sizeAdjustab.setLayoutParams(layoutParams1);
       relativeLayo.addView(sizeAdjustab);
       EditorContainer uEditorConta = new EditorContainer(relativeLayo.getContext());
       RelativeLayout$LayoutParams layoutParams2 = new RelativeLayout$LayoutParams(-1, -2);
       uEditorConta.setId(R.id.container_other);
       layoutParams2.addRule(12, -1);
       uEditorConta.setClipChildren(false);
       uEditorConta.setClipToPadding(false);
       uEditorConta.setLayoutParams(layoutParams2);
       relativeLayo.addView(uEditorConta);
       FrameLayout uFrameLayout = new FrameLayout(relativeLayo.getContext());
       layoutParams2 = new RelativeLayout$LayoutParams(-1, c.b(resources, 0x7f070268));
       uFrameLayout.setId(R.id.edit_tab_mask);
       layoutParams2.addRule(10, -1);
       uFrameLayout.setVisibility(8);
       uFrameLayout.setLayoutParams(layoutParams2);
       relativeLayo.addView(uFrameLayout);
       View view2 = new View(uFrameLayout.getContext());
       view2.setId(R.id.edit_tab_mask_animate);
       view2.setBackgroundResource(R.drawable.arg_RES_7f0808f9);
       view2.setLayoutParams(new FrameLayout$LayoutParams(-1, -1));
       uFrameLayout.addView(view2);
       sizeAdjustab = new SizeAdjustableTextView(relativeLayo.getContext());
       layoutParams2 = new RelativeLayout$LayoutParams(-2, c.b(resources, 0x7f07010b));
       sizeAdjustab.setBackgroundResource(R.drawable.arg_RES_7f0801d6);
       sizeAdjustab.setTextColor(resources.getColor(R.color.arg_RES_7f061fbd));
       sizeAdjustab.setId(R.id.text_edit_done_button);
       layoutParams2.addRule(11, -1);
       layoutParams2.addRule(10, -1);
       layoutParams2.rightMargin = c.b(resources, 0x7f0702ab);
       layoutParams2.topMargin = c.b(resources, 0x7f0702e8);
       sizeAdjustab.setGravity(17);
       sizeAdjustab.setMaxLines(1);
       sizeAdjustab.setText(R.string.arg_RES_7f100f6b);
       sizeAdjustab.setTextSize(false, (float)c.b(resources, R.dimen.arg_RES_7f070271));
       sizeAdjustab.setInitTextSize(TypedValue.applyDimension(false, (float)c.b(resources, R.dimen.arg_RES_7f070271), c.c(resources)));
       sizeAdjustab.setVisibility(8);
       sizeAdjustab.setTextSizeAdjustable(false);
       sizeAdjustab.setPadding(c.b(resources, R.dimen.arg_RES_7f070295), false, c.b(resources, R.dimen.arg_RES_7f070295), false);
       sizeAdjustab.setLayoutParams(layoutParams2);
       relativeLayo.addView(sizeAdjustab);
       uFrameLayout = new FrameLayout(relativeLayo.getContext());
       layoutParams2 = new RelativeLayout$LayoutParams(-1, c.b(resources, 0x7f0702c9));
       uFrameLayout.setId(R.id.edit_bottom_mask);
       layoutParams2.addRule(12, -1);
       uFrameLayout.setVisibility(8);
       uFrameLayout.setLayoutParams(layoutParams2);
       relativeLayo.addView(uFrameLayout);
       view2 = new View(uFrameLayout.getContext());
       view2.setId(R.id.edit_bottom_mask_animate);
       view2.setBackgroundResource(R.drawable.arg_RES_7f080824);
       view2.setLayoutParams(new FrameLayout$LayoutParams(-1, -1));
       uFrameLayout.addView(view2);
       view1 = new X2C_New_Author_Widget_Preview().createView(relativeLayo.getContext());
       layoutParams2 = view1.getLayoutParams();
       view1.setId(R.id.new_author_widget_preview_container);
       layoutParams2.addRule(8, R.id.action_recycler_view);
       view1.setVisibility(8);
       view1.setLayoutParams(layoutParams2);
       relativeLayo.addView(view1);
       view1 = new View(relativeLayo.getContext());
       layoutParams2 = new RelativeLayout$LayoutParams(c.b(resources, 0x7f0702ac), c.b(resources, 0x7f07030d));
       view1.setId(R.id.new_author_widget_divider);
       layoutParams2.addRule(8, R.id.action_recycler_view);
       layoutParams2.addRule(11, -1);
       layoutParams2.bottomMargin = c.b(resources, 0x7f07030a);
       view1.setBackgroundColor(resources.getColor(R.color.arg_RES_7f061bec));
       view1.setVisibility(8);
       view1.setLayoutParams(layoutParams2);
       relativeLayo.addView(view1);
       RecyclerView recyclerView = new RecyclerView(relativeLayo.getContext());
       layoutParams2 = new RelativeLayout$LayoutParams(-1, -2);
       recyclerView.setId(R.id.action_recycler_view);
       layoutParams2.addRule(1, R.id.new_author_widget_preview_container);
       recyclerView.setOverScrollMode(2);
       layoutParams2.addRule(12, -1);
       layoutParams2.bottomMargin = (int)TypedValue.applyDimension(1, 96.00f, c.c(resources));
       recyclerView.setVisibility(4);
       recyclerView.setLayoutParams(layoutParams2);
       relativeLayo.addView(recyclerView);
       relativeLayo1 = new RelativeLayout(relativeLayo.getContext());
       layoutParams2 = new RelativeLayout$LayoutParams(-1, c.b(resources, 0x7f070327));
       relativeLayo1.setId(R.id.merge_edit_post_layout);
       layoutParams2.addRule(12, -1);
       layoutParams2.bottomMargin = c.b(resources, 0x7f0702b8);
       relativeLayo1.setLayoutParams(layoutParams2);
       relativeLayo.addView(relativeLayo1);
       FlyWheelFrameLayout uFlyWheelFra = new FlyWheelFrameLayout(relativeLayo1.getContext());
       RelativeLayout$LayoutParams layoutParams3 = new RelativeLayout$LayoutParams(-1, c.b(resources, 0x7f070107));
       uFlyWheelFra.setId(R.id.post_button_v2);
       layoutParams3.addRule(9, -1);
       layoutParams3.addRule(12, -1);
       layoutParams3.leftMargin = c.b(resources, 0x7f07054b);
       uFlyWheelFra.setVisibility(8);
       uFlyWheelFra.setTextViewId(R.id.post_button_v2_principal);
       uFlyWheelFra.setTKContainerId(R.id.post_button_v2);
       uFlyWheelFra.setLayoutParams(layoutParams3);
       relativeLayo1.addView(uFlyWheelFra);
       LinearLayout linearLayout = new LinearLayout(uFlyWheelFra.getContext());
       linearLayout.setBackgroundResource(R.drawable.arg_RES_7f0808e8);
       linearLayout.setGravity(17);
       linearLayout.setOrientation(1);
       linearLayout.setPadding((int)TypedValue.applyDimension(1, 26.00f, c.c(resources)), false, (int)TypedValue.applyDimension(1, 26.00f, c.c(resources)), false);
       linearLayout.setLayoutParams(new FrameLayout$LayoutParams(-1, -1));
       uFlyWheelFra.addView(linearLayout);
       SizeAdjustableTextView sizeAdjustab1 = new SizeAdjustableTextView(linearLayout.getContext());
       sizeAdjustab1.setId(R.id.post_button_v2_principal);
       sizeAdjustab1.setCompoundDrawablePadding(c.b(resources, R.dimen.arg_RES_7f0702e3));
       sizeAdjustab1.setEllipsize(TextUtils$TruncateAt.END);
       sizeAdjustab1.setGravity(17);
       sizeAdjustab1.setMaxLines(1);
       sizeAdjustab1.setText(R.string.arg_RES_7f10400f);
       sizeAdjustab1.setTextColor(resources.getColor(R.color.arg_RES_7f0609d6));
       sizeAdjustab1.setTextSize(false, (float)c.b(resources, R.dimen.arg_RES_7f07028d));
       sizeAdjustab1.setInitTextSize(TypedValue.applyDimension(false, (float)c.b(resources, R.dimen.arg_RES_7f07028d), c.c(resources)));
       sizeAdjustab1.setTypeface(null, 1);
       sizeAdjustab1.setTextSizeAdjustable(false);
       sizeAdjustab1.setCompoundDrawablesWithIntrinsicBounds(ContextCompat.getDrawable(uContext, R.drawable.arg_RES_7f081bb0), null, null, null);
       sizeAdjustab1.setLayoutParams(new LinearLayout$LayoutParams(-2, -2));
       linearLayout.addView(sizeAdjustab1);
       sizeAdjustab1 = new SizeAdjustableTextView(linearLayout.getContext());
       sizeAdjustab1.setId(R.id.post_button_v2_secondary);
       sizeAdjustab1.setTextColor(resources.getColor(R.color.arg_RES_7f0609d7));
       sizeAdjustab1.setTextSize(false, (float)c.b(resources, R.dimen.pv));
       sizeAdjustab1.setInitTextSize(TypedValue.applyDimension(false, (float)c.b(resources, R.dimen.pv), c.c(resources)));
       sizeAdjustab1.setVisibility(8);
       sizeAdjustab1.setTextSizeAdjustable(false);
       sizeAdjustab1.setLayoutParams(new LinearLayout$LayoutParams(-2, -2));
       linearLayout.addView(sizeAdjustab1);
       uFlyWheelFra = new FlyWheelFrameLayout(relativeLayo1.getContext());
       layoutParams1 = new RelativeLayout$LayoutParams(-2, c.b(resources, 0x7f070107));
       uFlyWheelFra.setId(R.id.next_step_button);
       uFlyWheelFra.setVisibility(4);
       uFlyWheelFra.setBackgroundResource(R.drawable.arg_RES_7f0801a1);
       layoutParams1.addRule(14, -1);
       layoutParams1.addRule(12, -1);
       uFlyWheelFra.setTextViewId(R.id.next_step_button_text);
       uFlyWheelFra.setTKContainerId(R.id.next_step_button);
       uFlyWheelFra.setLayoutParams(layoutParams1);
       relativeLayo1.addView(uFlyWheelFra);
       SizeAdjustableTextView sizeAdjustab2 = new SizeAdjustableTextView(uFlyWheelFra.getContext());
       FrameLayout$LayoutParams layoutParams4 = new FrameLayout$LayoutParams(-2, c.b(resources, 0x7f070107));
       sizeAdjustab2.setTextColor(resources.getColor(R.color.arg_RES_7f061fbd));
       sizeAdjustab2.setId(R.id.next_step_button_text);
       sizeAdjustab2.setBackgroundDrawable(null);
       sizeAdjustab2.setGravity(17);
       sizeAdjustab2.setMaxLines(1);
       sizeAdjustab2.setText(R.string.arg_RES_7f103937);
       sizeAdjustab2.setTextSizeAdjustable(false);
       layoutParams4.gravity = 17;
       sizeAdjustab2.setTextSize(false, (float)c.b(resources, R.dimen.arg_RES_7f07028d));
       sizeAdjustab2.setInitTextSize(TypedValue.applyDimension(false, (float)c.b(resources, R.dimen.arg_RES_7f07028d), c.c(resources)));
       sizeAdjustab2.setCompoundDrawablesWithIntrinsicBounds(null, null, ContextCompat.getDrawable(uContext, R.drawable.arg_RES_7f080864), null);
       sizeAdjustab2.setLayoutParams(layoutParams4);
       uFlyWheelFra.addView(sizeAdjustab2);
       AppCompatTextView uAppCompatTe = new AppCompatTextView(relativeLayo1.getContext());
       layoutParams2 = new RelativeLayout$LayoutParams(-2, c.b(resources, 0x7f07021b));
       uAppCompatTe.setId(R.id.next_step_tip);
       layoutParams2.addRule(11, -1);
       layoutParams2.addRule(12, -1);
       uAppCompatTe.setGravity(17);
       uAppCompatTe.setText("×¬½ð±Ò");
       uAppCompatTe.setTextSize(1, 11.00f);
       uAppCompatTe.setTextColor(resources.getColor(R.color.arg_RES_7f061be0));
       uAppCompatTe.setBackgroundResource(R.drawable.arg_RES_7f081a19);
       uAppCompatTe.setVisibility(4);
       int i = c.b(resources, R.dimen.arg_RES_7f07033f);
       uAppCompatTe.setPadding(i, false, c.b(resources, R.dimen.arg_RES_7f070334), false);
       uAppCompatTe.setLayoutParams(layoutParams2);
       relativeLayo1.addView(uAppCompatTe);
       FrameLayout uFrameLayout1 = new FrameLayout(relativeLayo.getContext());
       RelativeLayout$LayoutParams layoutParams5 = new RelativeLayout$LayoutParams(-1, -2);
       uFrameLayout1.setId(R.id.sticker_container);
       layoutParams5.addRule(12, -1);
       uFrameLayout1.setLayoutParams(layoutParams5);
       relativeLayo.addView(uFrameLayout1);
       return relativeLayo;
    }
}
