package com.kuaishou.ax2c.layouts.X2C_Live_Play_Preload;
import com.kuaishou.ax2c.IViewCreator;
import java.lang.Object;
import android.content.Context;
import android.view.View;
import android.content.res.Resources;
import android.widget.RelativeLayout;
import android.view.ViewGroup$MarginLayoutParams;
import android.view.ViewGroup$LayoutParams;
import android.view.ViewStub;
import android.widget.RelativeLayout$LayoutParams;
import cw9.c;
import android.util.DisplayMetrics;
import android.util.TypedValue;
import android.widget.FrameLayout;
import androidx.appcompat.widget.AppCompatTextView;
import android.widget.TextView;
import com.kuaishou.live.gzone.barrage.BarrageView;
import com.kuaishou.ax2c.layouts.X2C_Live_Play_Right_Pendant_Container_Layout;
import androidx.appcompat.widget.AppCompatImageView;
import android.widget.ImageView;
import android.widget.ImageView$ScaleType;
import com.kuaishou.ax2c.layouts.X2C_Live_Audience_Line_Container_Layout;
import com.kuaishou.live.livestage.videopipe.renderarea.ui.RenderAreaView;
import androidx.constraintlayout.widget.ConstraintLayout;
import android.view.ViewGroup;
import com.kuaishou.ax2c.layouts.X2C_Live_Multi_Chat_Interactive_Layout;
import com.kuaishou.ax2c.layouts.X2C_Live_Play_Clearable_Layer;
import com.yxcorp.gifshow.image.KwaiImageView;
import com.kuaishou.live.common.core.component.gift.domain.combo.animation.LiveGiftBoxGiftParticleAnimationView;
import com.kuaishou.ax2c.layouts.X2C_Live_Gift_Box_Combo_Text_Animation_Layout;

public class X2C_Live_Play_Preload implements IViewCreator	// class@00110b
{

    public void X2C_Live_Play_Preload(){
       super();
    }
    public View createView(Context p0){
       Resources resources = p0.getResources();
       RelativeLayout relativeLayo = new RelativeLayout(p0);
       relativeLayo.setLayoutParams(new ViewGroup$MarginLayoutParams(-1, -1));
       ViewStub viewStub = new ViewStub(relativeLayo.getContext());
       viewStub.setInflatedId(-1);
       viewStub.setId(R.id.live_phone_verified_voice_party_background);
       viewStub.setLayoutResource(R.layout.arg_RES_7f0d0cf1);
       viewStub.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       relativeLayo.addView(viewStub);
       viewStub = new ViewStub(relativeLayo.getContext());
       viewStub.setInflatedId(-1);
       viewStub.setId(R.id.live_merchant_atmosphere_top_bg_stub);
       viewStub.setLayoutResource(R.layout.arg_RES_7f0d0c8b);
       viewStub.setLayoutParams(new RelativeLayout$LayoutParams(-1, -2));
       relativeLayo.addView(viewStub);
       viewStub = new ViewStub(relativeLayo.getContext());
       viewStub.setInflatedId(-1);
       RelativeLayout$LayoutParams layoutParams = new RelativeLayout$LayoutParams(-1, -2);
       viewStub.setId(R.id.live_merchant_atmosphere_bottom_bg_stub);
       layoutParams.addRule(12, -1);
       viewStub.setLayoutResource(R.layout.arg_RES_7f0d0c8a);
       viewStub.setLayoutParams(layoutParams);
       relativeLayo.addView(viewStub);
       viewStub = new ViewStub(relativeLayo.getContext());
       viewStub.setInflatedId(-1);
       layoutParams = new RelativeLayout$LayoutParams(c.b(resources, 0x7f0705d9), c.b(resources, 0x7f0705d8));
       viewStub.setId(R.id.live_audio_audience_avatar_animator_view_stub);
       layoutParams.addRule(14, -1);
       layoutParams.topMargin = (int)TypedValue.applyDimension(1, 141.00f, c.c(resources));
       viewStub.setInflatedId(R.id.live_audio_audience_avatar_animator_layout_view);
       viewStub.setLayoutResource(R.layout.arg_RES_7f0d0a69);
       viewStub.setLayoutParams(layoutParams);
       relativeLayo.addView(viewStub);
       FrameLayout uFrameLayout = new FrameLayout(relativeLayo.getContext());
       uFrameLayout.setId(R.id.live_play_loading_view_container);
       uFrameLayout.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       relativeLayo.addView(uFrameLayout);
       uFrameLayout = new FrameLayout(relativeLayo.getContext());
       layoutParams = new RelativeLayout$LayoutParams(-2, -2);
       uFrameLayout.setId(R.id.live_improper_stop_mask_layout_view);
       layoutParams.addRule(14, -1);
       uFrameLayout.setLayoutParams(layoutParams);
       relativeLayo.addView(uFrameLayout);
       AppCompatTextView uAppCompatTe = new AppCompatTextView(relativeLayo.getContext());
       layoutParams = new RelativeLayout$LayoutParams(-2, -2);
       uAppCompatTe.setId(R.id.live_watermark_view);
       layoutParams.addRule(11, -1);
       layoutParams.addRule(3, R.id.top_bar_place_holder);
       layoutParams.rightMargin = c.b(resources, 0x7f070267);
       uAppCompatTe.setShadowLayer(uAppCompatTe.getShadowRadius(), uAppCompatTe.getShadowDx(), uAppCompatTe.getShadowDy(), resources.getColor(R.color.arg_RES_7f062040));
       uAppCompatTe.setShadowLayer(uAppCompatTe.getShadowRadius(), 0x3f800000, uAppCompatTe.getShadowDy(), uAppCompatTe.getShadowColor());
       uAppCompatTe.setShadowLayer(uAppCompatTe.getShadowRadius(), uAppCompatTe.getShadowDx(), 0x3f800000, uAppCompatTe.getShadowColor());
       uAppCompatTe.setShadowLayer(0x3f800000, uAppCompatTe.getShadowDx(), uAppCompatTe.getShadowDy(), uAppCompatTe.getShadowColor());
       uAppCompatTe.setTextColor(resources.getColor(R.color.arg_RES_7f0620e9));
       uAppCompatTe.setTextSize(1, 6.00f);
       uAppCompatTe.setLayoutParams(layoutParams);
       relativeLayo.addView(uAppCompatTe);
       uFrameLayout = new FrameLayout(relativeLayo.getContext());
       uFrameLayout.setId(R.id.live_heart_particle_container);
       uFrameLayout.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       relativeLayo.addView(uFrameLayout);
       uFrameLayout = new FrameLayout(relativeLayo.getContext());
       uFrameLayout.setId(R.id.live_audience_explain_pendant_container);
       uFrameLayout.setLayoutParams(new RelativeLayout$LayoutParams(-2, -2));
       relativeLayo.addView(uFrameLayout);
       BarrageView uBarrageView = new BarrageView(relativeLayo.getContext());
       uBarrageView.setId(R.id.barrage_view);
       uBarrageView.setVisibility(8);
       uBarrageView.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       relativeLayo.addView(uBarrageView);
       View view = new View(relativeLayo.getContext());
       view.setId(R.id.top_bar_place_holder);
       view.setLayoutParams(new RelativeLayout$LayoutParams((int)TypedValue.applyDimension(1, 0, c.c(resources)), (int)TypedValue.applyDimension(1, 0, c.c(resources))));
       relativeLayo.addView(view);
       view = new X2C_Live_Play_Right_Pendant_Container_Layout().createView(relativeLayo.getContext());
       layoutParams = view.getLayoutParams();
       view.setId(R.id.live_right_pendant_container);
       layoutParams.addRule(11, -1);
       layoutParams.addRule(3, R.id.top_bar_place_holder);
       layoutParams.topMargin = c.b(resources, 0x7f07034b);
       view.setVisibility(8);
       view.setLayoutParams(layoutParams);
       relativeLayo.addView(view);
       AppCompatImageView uAppCompatIm = new AppCompatImageView(relativeLayo.getContext());
       layoutParams = new RelativeLayout$LayoutParams(c.b(resources, 0x7f070601), c.b(resources, 0x7f070601));
       uAppCompatIm.setId(R.id.live_close);
       layoutParams.addRule(8, R.id.top_bar_place_holder);
       layoutParams.addRule(11, -1);
       layoutParams.bottomMargin = c.b(resources, 0x7f0702e3);
       layoutParams.rightMargin = c.b(resources, 0x7f070329);
       uAppCompatIm.setScaleType(ImageView$ScaleType.CENTER_INSIDE);
       uAppCompatIm.setLayoutParams(layoutParams);
       relativeLayo.addView(uAppCompatIm);
       viewStub = new ViewStub(relativeLayo.getContext());
       viewStub.setInflatedId(-1);
       viewStub.setId(R.id.game_interactive_pk_wrapper_view_stub);
       viewStub.setInflatedId(R.id.game_interactive_pk_wrapper_view);
       viewStub.setLayoutResource(R.layout.arg_RES_7f0d0547);
       viewStub.setLayoutParams(new RelativeLayout$LayoutParams(-1, -2));
       relativeLayo.addView(viewStub);
       viewStub = new ViewStub(relativeLayo.getContext());
       viewStub.setInflatedId(-1);
       viewStub.setId(R.id.live_pk_wrapper_view_stub);
       viewStub.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       relativeLayo.addView(viewStub);
       view = new X2C_Live_Audience_Line_Container_Layout().createView(relativeLayo.getContext());
       view.setId(R.id.live_line_container);
       view.setLayoutParams(view.getLayoutParams());
       relativeLayo.addView(view);
       uFrameLayout = new FrameLayout(relativeLayo.getContext());
       uFrameLayout.setId(R.id.live_multi_line_container_layout);
       uFrameLayout.setClipChildren(false);
       uFrameLayout.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       relativeLayo.addView(uFrameLayout);
       RenderAreaView renderAreaVi = new RenderAreaView(relativeLayo.getContext());
       renderAreaVi.setId(R.id.live_multi_line_render_area);
       renderAreaVi.setVisibility(8);
       renderAreaVi.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       relativeLayo.addView(renderAreaVi);
       uFrameLayout = new FrameLayout(relativeLayo.getContext());
       uFrameLayout.setId(R.id.live_multi_pk_container_layout);
       uFrameLayout.setClipChildren(false);
       uFrameLayout.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       relativeLayo.addView(uFrameLayout);
       view = new X2C_Live_Multi_Chat_Interactive_Layout().createView(relativeLayo.getContext());
       view.setLayoutParams(view.getLayoutParams());
       relativeLayo.addView(view);
       RelativeLayout relativeLayo1 = new RelativeLayout(relativeLayo.getContext());
       layoutParams = new RelativeLayout$LayoutParams(-1, -1);
       layoutParams.addRule(3, R.id.top_bar_place_holder);
       relativeLayo1.setClipChildren(false);
       relativeLayo1.setLayoutParams(layoutParams);
       relativeLayo.addView(relativeLayo1);
       FrameLayout uFrameLayout1 = new FrameLayout(relativeLayo1.getContext());
       RelativeLayout$LayoutParams layoutParams1 = new RelativeLayout$LayoutParams(-1, -2);
       uFrameLayout1.setId(R.id.live_voice_party_team_pk_container_view);
       layoutParams1.topMargin = c.b(resources, 0x7f070316);
       uFrameLayout1.setLayoutParams(layoutParams1);
       relativeLayo1.addView(uFrameLayout1);
       uFrameLayout = new FrameLayout(relativeLayo.getContext());
       uFrameLayout.setId(R.id.live_play_voice_party_vc_container);
       uFrameLayout.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       relativeLayo.addView(uFrameLayout);
       viewStub = new ViewStub(relativeLayo.getContext());
       viewStub.setInflatedId(-1);
       layoutParams = new RelativeLayout$LayoutParams(-2, -2);
       viewStub.setId(R.id.live_top_pendant_view_stub);
       layoutParams.addRule(3, R.id.top_bar_place_holder);
       layoutParams.addRule(9, -1);
       layoutParams.topMargin = c.b(resources, 0x7f070271);
       layoutParams.rightMargin = (int)TypedValue.applyDimension(1, 94.00f, c.c(resources));
       layoutParams.leftMargin = c.b(resources, 0x7f07054f);
       viewStub.setInflatedId(R.id.live_top_pendant);
       viewStub.setLayoutResource(R.layout.arg_RES_7f0d0e3f);
       viewStub.setLayoutParams(layoutParams);
       relativeLayo.addView(viewStub);
       viewStub = new ViewStub(relativeLayo.getContext());
       viewStub.setInflatedId(-1);
       viewStub.setId(R.id.live_merchant_fullscreen_pendant_stub);
       viewStub.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       relativeLayo.addView(viewStub);
       view = new X2C_Live_Play_Clearable_Layer().createView(relativeLayo.getContext());
       view.setId(R.id.live_play_clearable_layer);
       view.setLayoutParams(view.getLayoutParams());
       relativeLayo.addView(view);
       viewStub = new ViewStub(relativeLayo.getContext());
       viewStub.setInflatedId(-1);
       layoutParams = new RelativeLayout$LayoutParams(-1, -2);
       viewStub.setId(R.id.live_new_bottom_bar_view_stub);
       layoutParams.addRule(12, -1);
       viewStub.setInflatedId(R.id.live_new_bottom_bar_container);
       viewStub.setLayoutResource(R.layout.arg_RES_7f0d0cd9);
       viewStub.setLayoutParams(layoutParams);
       relativeLayo.addView(viewStub);
       viewStub = new ViewStub(relativeLayo.getContext());
       viewStub.setInflatedId(-1);
       layoutParams = new RelativeLayout$LayoutParams(-1, -1);
       viewStub.setId(R.id.live_high_layer_effect_glview_stub);
       layoutParams.addRule(13, -1);
       viewStub.setLayoutResource(R.layout.arg_RES_7f0d0d18);
       viewStub.setLayoutParams(layoutParams);
       relativeLayo.addView(viewStub);
       uAppCompatIm = new AppCompatImageView(relativeLayo.getContext());
       layoutParams = new RelativeLayout$LayoutParams(c.b(resources, 0x7f0702e8), c.b(resources, 0x7f0702e8));
       uAppCompatIm.setId(R.id.live_effect_glview_top_close);
       layoutParams.addRule(21, -1);
       layoutParams.rightMargin = c.b(resources, 0x7f07025d);
       layoutParams.topMargin = c.b(resources, 0x7f0702d2);
       uAppCompatIm.setScaleType(ImageView$ScaleType.CENTER_CROP);
       uAppCompatIm.setImageResource(R.drawable.arg_RES_7f081141);
       uAppCompatIm.setVisibility(8);
       uAppCompatIm.setLayoutParams(layoutParams);
       relativeLayo.addView(uAppCompatIm);
       viewStub = new ViewStub(relativeLayo.getContext());
       viewStub.setInflatedId(-1);
       viewStub.setId(R.id.live_bottom_bar_wish_light_gift_combo_view_stub);
       viewStub.setLayoutResource(R.layout.arg_RES_7f0d0a7e);
       viewStub.setInflatedId(R.id.live_bottom_bar_wish_light_gift_combo_view);
       viewStub.setLayoutParams(new RelativeLayout$LayoutParams(-2, -2));
       relativeLayo.addView(viewStub);
       relativeLayo1 = new RelativeLayout(relativeLayo.getContext());
       relativeLayo1.setId(R.id.gift_box_fragment_container);
       relativeLayo1.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       relativeLayo.addView(relativeLayo1);
       uFrameLayout = new FrameLayout(relativeLayo.getContext());
       uFrameLayout.setId(R.id.diy_panel_container);
       uFrameLayout.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       relativeLayo.addView(uFrameLayout);
       KwaiImageView kwaiImageVie = new KwaiImageView(relativeLayo.getContext());
       layoutParams = new RelativeLayout$LayoutParams((int)TypedValue.applyDimension(1, 230.00f, c.c(resources)), (int)TypedValue.applyDimension(1, 200.00f, c.c(resources)));
       kwaiImageVie.setId(R.id.combo_btn_long_press_effect);
       layoutParams.addRule(11, -1);
       layoutParams.addRule(12, -1);
       kwaiImageVie.setLayoutParams(layoutParams);
       relativeLayo.addView(kwaiImageVie);
       viewStub = new ViewStub(relativeLayo.getContext());
       viewStub.setInflatedId(-1);
       layoutParams = new RelativeLayout$LayoutParams(c.b(resources, 0x7f070355), c.b(resources, 0x7f070355));
       viewStub.setId(R.id.live_gift_right_bottom_combo_animation_view_stub);
       layoutParams.addRule(11, -1);
       layoutParams.addRule(12, -1);
       viewStub.setInflatedId(R.id.live_gift_box_combo_button);
       viewStub.setLayoutResource(R.layout.arg_RES_7f0d0b1c);
       viewStub.setLayoutParams(layoutParams);
       relativeLayo.addView(viewStub);
       LiveGiftBoxGiftParticleAnimationView liveGiftBoxG = new LiveGiftBoxGiftParticleAnimationView(relativeLayo.getContext());
       liveGiftBoxG.setId(R.id.live_gift_box_gift_particle_animation_view);
       liveGiftBoxG.setVisibility(8);
       liveGiftBoxG.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       relativeLayo.addView(liveGiftBoxG);
       view = new X2C_Live_Gift_Box_Combo_Text_Animation_Layout().createView(relativeLayo.getContext());
       view.setId(R.id.live_gift_box_combo_text_animation_view);
       view.setVisibility(8);
       view.setLayoutParams(view.getLayoutParams());
       relativeLayo.addView(view);
       viewStub = new ViewStub(relativeLayo.getContext());
       viewStub.setInflatedId(-1);
       layoutParams = new RelativeLayout$LayoutParams(c.b(resources, 0x7f0702cd), c.b(resources, 0x7f0702bd));
       viewStub.setId(R.id.live_gift_right_bottom_combo_effect_animation_view_stub);
       viewStub.setInflatedId(R.id.combo_anim_root_view);
       viewStub.setLayoutResource(R.layout.arg_RES_7f0d0a14);
       layoutParams.addRule(11, -1);
       layoutParams.addRule(12, -1);
       viewStub.setLayoutParams(layoutParams);
       relativeLayo.addView(viewStub);
       uFrameLayout = new FrameLayout(relativeLayo.getContext());
       uFrameLayout.setId(R.id.live_like_new_style_container);
       uFrameLayout.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       relativeLayo.addView(uFrameLayout);
       viewStub = new ViewStub(relativeLayo.getContext());
       viewStub.setInflatedId(-1);
       layoutParams = new RelativeLayout$LayoutParams(-2, c.b(resources, 0x7f0702fe));
       viewStub.setId(R.id.live_play_sidebar_square_notice_view_stub);
       layoutParams.addRule(11, -1);
       layoutParams.addRule(3, R.id.top_bar_place_holder);
       layoutParams.topMargin = c.b(resources, 0x7f07034b);
       viewStub.setInflatedId(R.id.live_play_sidebar_square_notice_layout);
       viewStub.setLayoutResource(R.layout.arg_RES_7f0d0d20);
       viewStub.setLayoutParams(layoutParams);
       relativeLayo.addView(viewStub);
       viewStub = new ViewStub(relativeLayo.getContext());
       viewStub.setInflatedId(-1);
       layoutParams = new RelativeLayout$LayoutParams(-2, c.b(resources, 0x7f0702b8));
       viewStub.setId(R.id.live_play_sidebar_square_notice_view_stub_v2);
       layoutParams.addRule(11, -1);
       layoutParams.addRule(3, R.id.top_bar_place_holder);
       layoutParams.topMargin = c.b(resources, 0x7f070334);
       viewStub.setLayoutParams(layoutParams);
       relativeLayo.addView(viewStub);
       uFrameLayout = new FrameLayout(relativeLayo.getContext());
       uFrameLayout.setId(R.id.close_fragment_container);
       uFrameLayout.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       relativeLayo.addView(uFrameLayout);
       viewStub = new ViewStub(relativeLayo.getContext());
       viewStub.setInflatedId(-1);
       viewStub.setId(R.id.live_square_fullscreen_slide_guide_view_stub);
       viewStub.setInflatedId(R.id.live_square_fullscreen_slide_guide_container);
       viewStub.setLayoutResource(R.layout.arg_RES_7f0d0dce);
       viewStub.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       relativeLayo.addView(viewStub);
       viewStub = new ViewStub(relativeLayo.getContext());
       viewStub.setInflatedId(-1);
       viewStub.setId(R.id.live_square_bottom_slide_guide_view_stub);
       viewStub.setInflatedId(R.id.live_square_bottom_slide_guide_container);
       viewStub.setLayoutResource(R.layout.arg_RES_7f0d0dcd);
       viewStub.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       relativeLayo.addView(viewStub);
       viewStub = new ViewStub(relativeLayo.getContext());
       viewStub.setInflatedId(-1);
       layoutParams = new RelativeLayout$LayoutParams(-2, -2);
       viewStub.setId(R.id.live_divert_push_view_stub);
       layoutParams.addRule(14, -1);
       viewStub.setInflatedId(R.id.live_divert_push_view_container);
       viewStub.setLayoutResource(R.layout.arg_RES_7f0d0ae2);
       viewStub.setLayoutParams(layoutParams);
       relativeLayo.addView(viewStub);
       viewStub = new ViewStub(relativeLayo.getContext());
       viewStub.setInflatedId(-1);
       layoutParams = new RelativeLayout$LayoutParams(-1, -2);
       viewStub.setId(R.id.live_merchant_top_bullet_stub);
       layoutParams.addRule(3, R.id.top_bar_place_holder);
       layoutParams.topMargin = c.b(resources, 0x7f070301);
       viewStub.setLayoutResource(R.layout.arg_RES_7f0d0c9e);
       viewStub.setLayoutParams(layoutParams);
       relativeLayo.addView(viewStub);
       uFrameLayout = new FrameLayout(relativeLayo.getContext());
       layoutParams = new RelativeLayout$LayoutParams(-2, -2);
       uFrameLayout.setId(R.id.live_activity_widget_container);
       layoutParams.addRule(9, -1);
       layoutParams.leftMargin = c.b(resources, 0x7f0702b8);
       layoutParams.topMargin = c.b(resources, 0x7f0702cd);
       uFrameLayout.setLayoutParams(layoutParams);
       relativeLayo.addView(uFrameLayout);
       uFrameLayout = new FrameLayout(relativeLayo.getContext());
       uFrameLayout.setId(R.id.live_audience_play_bottom_fragment_container);
       uFrameLayout.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       relativeLayo.addView(uFrameLayout);
       view = new View(relativeLayo.getContext());
       view.setId(R.id.live_audience_full_screen_fragment_shape);
       view.setBackgroundColor(resources.getColor(R.color.arg_RES_7f061d64));
       view.setClickable(1);
       view.setFocusable(1);
       view.setVisibility(8);
       view.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       relativeLayo.addView(view);
       ViewStub viewStub1 = new ViewStub(relativeLayo.getContext());
       viewStub1.setInflatedId(-1);
       viewStub1.setId(R.id.camera_preview_layout_stub);
       viewStub1.setLayoutResource(R.layout.arg_RES_7f0d0189);
       viewStub1.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       relativeLayo.addView(viewStub1);
       FrameLayout uFrameLayout2 = new FrameLayout(relativeLayo.getContext());
       uFrameLayout2.setId(R.id.live_audience_full_screen_fragment_container);
       uFrameLayout2.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       relativeLayo.addView(uFrameLayout2);
       viewStub1 = new ViewStub(relativeLayo.getContext());
       viewStub1.setInflatedId(-1);
       viewStub1.setId(R.id.game_interactive_panel_container_view_stub);
       viewStub1.setInflatedId(R.id.game_interactive_panel_container);
       viewStub1.setLayoutResource(R.layout.arg_RES_7f0d0546);
       viewStub1.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       relativeLayo.addView(viewStub1);
       return relativeLayo;
    }
}
