package com.kuaishou.ax2c.layouts.X2C_Ksa_List_Item_Album_Img_Video;
import com.kuaishou.ax2c.IViewCreator;
import java.lang.Object;
import android.content.Context;
import android.view.View;
import android.content.res.Resources;
import android.widget.FrameLayout;
import android.view.ViewGroup$MarginLayoutParams;
import android.view.ViewGroup$LayoutParams;
import com.yxcorp.gifshow.album.imageloader.CompatImageView;
import android.widget.FrameLayout$LayoutParams;
import android.widget.ImageView;
import java.lang.String;
import java.lang.CharSequence;
import android.widget.TextView;
import android.util.DisplayMetrics;
import cw9.c;
import android.util.TypedValue;
import android.graphics.Color;
import com.yxcorp.gifshow.album.widget.SizeAdjustableTextView;

public class X2C_Ksa_List_Item_Album_Img_Video implements IViewCreator	// class@0010b4
{

    public void X2C_Ksa_List_Item_Album_Img_Video(){
       super();
    }
    public View createView(Context p0){
       Resources resources = p0.getResources();
       FrameLayout uFrameLayout = new FrameLayout(p0);
       uFrameLayout.setId(R.id.preview_container);
       uFrameLayout.setDescendantFocusability(0x60000);
       uFrameLayout.setLayoutParams(new ViewGroup$MarginLayoutParams(-2, -2));
       CompatImageView uCompatImage = new CompatImageView(uFrameLayout.getContext());
       uCompatImage.setId(R.id.media_preview);
       uCompatImage.setContentDescription(resources.getString(R.string.arg_RES_7f1018ba));
       uCompatImage.setLayoutParams(new FrameLayout$LayoutParams(-1, -1));
       uFrameLayout.addView(uCompatImage);
       TextView textView = new TextView(uFrameLayout.getContext());
       FrameLayout$LayoutParams layoutParams = new FrameLayout$LayoutParams(-2, -2);
       textView.setId(R.id.media_duration);
       layoutParams.gravity = 85;
       layoutParams.bottomMargin = (int)TypedValue.applyDimension(1, 5.00f, c.c(resources));
       layoutParams.rightMargin = (int)TypedValue.applyDimension(1, 6.00f, c.c(resources));
       textView.setGravity(16);
       textView.setIncludeFontPadding(false);
       textView.setShadowLayer(textView.getShadowRadius(), textView.getShadowDx(), textView.getShadowDy(), resources.getColor(R.color.arg_RES_7f060b8d));
       textView.setShadowLayer(textView.getShadowRadius(), textView.getShadowDx(), 0x3f800000, textView.getShadowColor());
       textView.setShadowLayer(3.00f, textView.getShadowDx(), textView.getShadowDy(), textView.getShadowColor());
       textView.setTextColor(Color.parseColor("#ffffff"));
       textView.setTextSize(false, (float)c.b(resources, R.dimen.arg_RES_7f07050d));
       textView.setLayoutParams(layoutParams);
       uFrameLayout.addView(textView);
       View view = new View(uFrameLayout.getContext());
       view.setId(R.id.selected_mask);
       view.setBackgroundColor(resources.getColor(R.color.arg_RES_7f060b6f));
       view.setVisibility(8);
       view.setLayoutParams(new FrameLayout$LayoutParams(-1, -1));
       uFrameLayout.addView(view);
       FrameLayout uFrameLayout1 = new FrameLayout(uFrameLayout.getContext());
       layoutParams = new FrameLayout$LayoutParams((int)TypedValue.applyDimension(1, 45.00f, c.c(resources)), (int)TypedValue.applyDimension(1, 45.00f, c.c(resources)));
       uFrameLayout1.setId(R.id.media_pick_num_area);
       layoutParams.gravity = 53;
       uFrameLayout1.setPadding(false, (int)TypedValue.applyDimension(1, 5.00f, c.c(resources)), (int)TypedValue.applyDimension(1, 5.00f, c.c(resources)), false);
       uFrameLayout1.setLayoutParams(layoutParams);
       uFrameLayout.addView(uFrameLayout1);
       FrameLayout uFrameLayout2 = new FrameLayout(uFrameLayout1.getContext());
       FrameLayout$LayoutParams layoutParams1 = new FrameLayout$LayoutParams((int)TypedValue.applyDimension(1, 21.00f, c.c(resources)), (int)TypedValue.applyDimension(1, 21.00f, c.c(resources)));
       layoutParams1.gravity = 5;
       uFrameLayout2.setLayoutParams(layoutParams1);
       uFrameLayout1.addView(uFrameLayout2);
       view = new View(uFrameLayout2.getContext());
       layoutParams1 = new FrameLayout$LayoutParams((int)TypedValue.applyDimension(1, 21.00f, c.c(resources)), (int)TypedValue.applyDimension(1, 21.00f, c.c(resources)));
       view.setId(R.id.item_select_circle);
       layoutParams1.gravity = 17;
       view.setBackgroundResource(R.drawable.arg_RES_7f080fdc);
       view.setLayoutParams(layoutParams1);
       uFrameLayout2.addView(view);
       SizeAdjustableTextView sizeAdjustab = new SizeAdjustableTextView(uFrameLayout2.getContext());
       layoutParams1 = new FrameLayout$LayoutParams((int)TypedValue.applyDimension(1, 19.00f, c.c(resources)), (int)TypedValue.applyDimension(1, 19.00f, c.c(resources)));
       sizeAdjustab.setId(R.id.media_pick_num);
       layoutParams1.gravity = 17;
       sizeAdjustab.setBackgroundResource(R.drawable.arg_RES_7f080fdd);
       sizeAdjustab.setGravity(17);
       sizeAdjustab.setIncludeFontPadding(false);
       sizeAdjustab.setTextColor(resources.getColor(R.color.arg_RES_7f060b37));
       sizeAdjustab.setTextSize(false, (float)c.b(resources, R.dimen.arg_RES_7f070510));
       sizeAdjustab.setInitTextSize(TypedValue.applyDimension(false, (float)c.b(resources, R.dimen.arg_RES_7f070510), c.c(resources)));
       sizeAdjustab.setVisibility(4);
       sizeAdjustab.setLayoutParams(layoutParams1);
       uFrameLayout2.addView(sizeAdjustab);
       view = new View(uFrameLayout.getContext());
       view.setId(R.id.unable_select_mask);
       view.setBackgroundColor(resources.getColor(R.color.arg_RES_7f060b6e));
       view.setVisibility(8);
       view.setLayoutParams(new FrameLayout$LayoutParams(-1, -1));
       uFrameLayout.addView(view);
       return uFrameLayout;
    }
}
