package com.kuaishou.ax2c.layouts.X2C_Element_Right_Action_Bar_Music_Wheel_Layout;
import com.kuaishou.ax2c.IViewCreator;
import java.lang.Object;
import android.content.Context;
import android.view.View;
import android.content.res.Resources;
import android.widget.FrameLayout;
import android.view.ViewGroup$MarginLayoutParams;
import cw9.c;
import android.view.ViewGroup$LayoutParams;
import android.widget.FrameLayout$LayoutParams;
import androidx.appcompat.widget.AppCompatImageView;
import android.widget.ImageView;
import android.view.ViewStub;
import androidx.appcompat.widget.AppCompatTextView;
import android.widget.TextView;
import android.text.TextUtils$TruncateAt;
import com.yxcorp.gifshow.image.KwaiImageView;
import ac.b;
import com.facebook.drawee.view.DraweeView;
import yb.a;
import android.graphics.drawable.Drawable;
import androidx.core.content.ContextCompat;
import com.facebook.drawee.generic.RoundingParams;

public class X2C_Element_Right_Action_Bar_Music_Wheel_Layout implements IViewCreator	// class@0010aa
{

    public void X2C_Element_Right_Action_Bar_Music_Wheel_Layout(){
       super();
    }
    public View createView(Context p0){
       Context uContext = p0;
       Resources resources = p0.getResources();
       FrameLayout uFrameLayout = new FrameLayout(uContext);
       ViewGroup$MarginLayoutParams marginLayout = new ViewGroup$MarginLayoutParams(-1, -2);
       marginLayout.topMargin = c.b(resources, 0x7f070283);
       uFrameLayout.setClipChildren(false);
       uFrameLayout.setLayoutParams(marginLayout);
       FrameLayout uFrameLayout1 = new FrameLayout(uFrameLayout.getContext());
       FrameLayout$LayoutParams layoutParams = new FrameLayout$LayoutParams(-2, -2);
       uFrameLayout1.setId(R.id.music_wheel_container);
       layoutParams.gravity = 0x800015;
       layoutParams.setMarginEnd(c.b(resources, R.dimen.arg_RES_7f07034b));
       uFrameLayout1.setClipChildren(false);
       uFrameLayout1.setLayoutParams(layoutParams);
       uFrameLayout.addView(uFrameLayout1);
       AppCompatImageView uAppCompatIm = new AppCompatImageView(uFrameLayout1.getContext());
       FrameLayout$LayoutParams layoutParams1 = new FrameLayout$LayoutParams(c.b(resources, 0x7f0702ef), c.b(resources, 0x7f0702ef));
       uAppCompatIm.setId(R.id.music_wheel_background);
       layoutParams1.gravity = 0x800015;
       layoutParams1.setMarginEnd(c.b(resources, R.dimen.arg_RES_7f070334));
       uAppCompatIm.setImageResource(R.drawable.arg_RES_7f080272);
       uAppCompatIm.setVisibility(8);
       uAppCompatIm.setLayoutParams(layoutParams1);
       uFrameLayout1.addView(uAppCompatIm);
       FrameLayout uFrameLayout2 = new FrameLayout(uFrameLayout1.getContext());
       layoutParams1 = new FrameLayout$LayoutParams(c.b(resources, 0x7f070313), c.b(resources, 0x7f070313));
       uFrameLayout2.setId(R.id.music_note_layout);
       layoutParams1.gravity = 0x800015;
       uFrameLayout2.setLayoutParams(layoutParams1);
       uFrameLayout1.addView(uFrameLayout2);
       AppCompatImageView uAppCompatIm1 = new AppCompatImageView(uFrameLayout2.getContext());
       uAppCompatIm1.setId(R.id.musical_note1);
       uAppCompatIm1.setImageResource(R.drawable.arg_RES_7f08199e);
       uAppCompatIm1.setVisibility(8);
       uAppCompatIm1.setLayoutParams(new FrameLayout$LayoutParams(-2, -2));
       uFrameLayout2.addView(uAppCompatIm1);
       uAppCompatIm1 = new AppCompatImageView(uFrameLayout2.getContext());
       uAppCompatIm1.setId(R.id.musical_note2);
       uAppCompatIm1.setImageResource(R.drawable.arg_RES_7f08199f);
       uAppCompatIm1.setVisibility(8);
       uAppCompatIm1.setLayoutParams(new FrameLayout$LayoutParams(-2, -2));
       uFrameLayout2.addView(uAppCompatIm1);
       uAppCompatIm1 = new AppCompatImageView(uFrameLayout2.getContext());
       uAppCompatIm1.setId(R.id.musical_note3);
       uAppCompatIm1.setImageResource(R.drawable.arg_RES_7f08199e);
       uAppCompatIm1.setVisibility(8);
       uAppCompatIm1.setLayoutParams(new FrameLayout$LayoutParams(-2, -2));
       uFrameLayout2.addView(uAppCompatIm1);
       uAppCompatIm1 = new AppCompatImageView(uFrameLayout2.getContext());
       uAppCompatIm1.setId(R.id.musical_note4);
       uAppCompatIm1.setImageResource(R.drawable.arg_RES_7f08199f);
       uAppCompatIm1.setVisibility(8);
       uAppCompatIm1.setLayoutParams(new FrameLayout$LayoutParams(-2, -2));
       uFrameLayout2.addView(uAppCompatIm1);
       uAppCompatIm1 = new AppCompatImageView(uFrameLayout2.getContext());
       uAppCompatIm1.setId(R.id.musical_note5);
       uAppCompatIm1.setImageResource(R.drawable.arg_RES_7f08199e);
       uAppCompatIm1.setVisibility(8);
       uAppCompatIm1.setLayoutParams(new FrameLayout$LayoutParams(-2, -2));
       uFrameLayout2.addView(uAppCompatIm1);
       uAppCompatIm1 = new AppCompatImageView(uFrameLayout2.getContext());
       uAppCompatIm1.setId(R.id.musical_note6);
       uAppCompatIm1.setImageResource(R.drawable.arg_RES_7f08199f);
       uAppCompatIm1.setVisibility(8);
       uAppCompatIm1.setLayoutParams(new FrameLayout$LayoutParams(-2, -2));
       uFrameLayout2.addView(uAppCompatIm1);
       ViewStub viewStub = new ViewStub(uFrameLayout2.getContext());
       viewStub.setInflatedId(-1);
       FrameLayout$LayoutParams layoutParams2 = new FrameLayout$LayoutParams(c.b(resources, 0x7f070325), c.b(resources, 0x7f070325));
       viewStub.setId(R.id.musical_note_static_stub);
       layoutParams2.gravity = 0x800055;
       viewStub.setInflatedId(R.id.musical_note_static);
       viewStub.setLayoutResource(R.layout.arg_RES_7f0d03bf);
       viewStub.setLayoutParams(layoutParams2);
       uFrameLayout2.addView(viewStub);
       AppCompatImageView uAppCompatIm2 = new AppCompatImageView(uFrameLayout1.getContext());
       layoutParams = new FrameLayout$LayoutParams(c.b(resources, 0x7f070313), c.b(resources, 0x7f070313));
       uAppCompatIm2.setId(R.id.music_wheel_gramophone);
       layoutParams.gravity = 0x800015;
       uAppCompatIm2.setImageResource(R.drawable.arg_RES_7f080a92);
       uAppCompatIm2.setLayoutParams(layoutParams);
       uFrameLayout1.addView(uAppCompatIm2);
       AppCompatTextView uAppCompatTe = new AppCompatTextView(uFrameLayout1.getContext());
       layoutParams = new FrameLayout$LayoutParams(-2, -2);
       uAppCompatTe.setId(R.id.music_wheel_same_style);
       layoutParams.gravity = 0x800015;
       layoutParams.setMarginEnd(c.b(resources, R.dimen.arg_RES_7f070271));
       uAppCompatTe.setEllipsize(TextUtils$TruncateAt.END);
       uAppCompatTe.setIncludeFontPadding(false);
       uAppCompatTe.setLines(1);
       uAppCompatTe.setShadowLayer(uAppCompatTe.getShadowRadius(), uAppCompatTe.getShadowDx(), uAppCompatTe.getShadowDy(), resources.getColor(R.color.arg_RES_7f061ff1));
       uAppCompatTe.setShadowLayer(uAppCompatTe.getShadowRadius(), 0, uAppCompatTe.getShadowDy(), uAppCompatTe.getShadowColor());
       uAppCompatTe.setShadowLayer(uAppCompatTe.getShadowRadius(), uAppCompatTe.getShadowDx(), 2.00f, uAppCompatTe.getShadowColor());
       uAppCompatTe.setShadowLayer(8.00f, uAppCompatTe.getShadowDx(), uAppCompatTe.getShadowDy(), uAppCompatTe.getShadowColor());
       uAppCompatTe.setText(R.string.arg_RES_7f103bfc);
       uAppCompatTe.setTextColor(resources.getColor(R.color.arg_RES_7f061c32));
       uAppCompatTe.setTextSize(false, (float)c.b(resources, R.dimen.arg_RES_7f070271));
       uAppCompatTe.setVisibility(8);
       uAppCompatTe.setLayoutParams(layoutParams);
       uFrameLayout1.addView(uAppCompatTe);
       KwaiImageView kwaiImageVie = new KwaiImageView(uFrameLayout1.getContext());
       FrameLayout$LayoutParams layoutParams3 = new FrameLayout$LayoutParams(c.b(resources, 0x7f0702cc), c.b(resources, 0x7f0702cc));
       kwaiImageVie.setId(R.id.music_wheel_cover);
       layoutParams3.gravity = 0x800015;
       layoutParams3.setMarginEnd(c.b(resources, R.dimen.arg_RES_7f07025d));
       kwaiImageVie.setBackgroundResource(R.drawable.arg_RES_7f080927);
       kwaiImageVie.getHierarchy().F(ContextCompat.getDrawable(uContext, R.drawable.arg_RES_7f080a93));
       kwaiImageVie.getHierarchy().L(RoundingParams.a());
       kwaiImageVie.setLayoutParams(layoutParams3);
       uFrameLayout1.addView(kwaiImageVie);
       return uFrameLayout;
    }
}
