package com.kuaishou.ax2c.layouts.X2C_Share_V2;
import com.kuaishou.ax2c.IViewCreator;
import java.lang.Object;
import android.content.Context;
import android.view.View;
import android.content.res.Resources;
import android.widget.RelativeLayout;
import android.view.ViewGroup$MarginLayoutParams;
import android.view.ViewGroup$LayoutParams;
import android.view.ViewStub;
import android.widget.RelativeLayout$LayoutParams;
import cw9.c;
import android.widget.LinearLayout;
import com.kuaishou.ax2c.layouts.X2C_Share_Toolbar;
import android.widget.LinearLayout$LayoutParams;
import com.kwai.library.widget.scrollview.ScrollViewEx;
import android.widget.ScrollView;
import com.kwai.library.widget.layout.LinearLayoutEx;
import android.widget.FrameLayout$LayoutParams;
import com.kuaishou.ax2c.layouts.X2C_Share_Un_Match_Topic_Tips_Wrap;
import android.widget.FrameLayout;
import android.util.DisplayMetrics;
import android.util.TypedValue;
import com.kuaishou.ax2c.layouts.X2C_Share_Mini_Program_Layout;
import com.kuaishou.ax2c.layouts.X2C_Share_Cocreator_Info;
import com.kuaishou.ax2c.layouts.X2C_Share_Business_Link_Layout;
import com.kuaishou.ax2c.layouts.X2C_Share_Connect_Hot;
import com.kuaishou.ax2c.layouts.X2C_Share_Custom_Item_V2;
import com.kuaishou.ax2c.layouts.X2C_Share_Topic_List_Container_Layout;
import com.yxcorp.gifshow.activity.share.widget.DragPreviewContainer;

public class X2C_Share_V2 implements IViewCreator	// class@001133
{

    public void X2C_Share_V2(){
       super();
    }
    public View createView(Context p0){
       Resources resources = p0.getResources();
       RelativeLayout relativeLayo = new RelativeLayout(p0);
       relativeLayo.setId(R.id.publish_view);
       relativeLayo.setFitsSystemWindows(true);
       relativeLayo.setLayoutParams(new ViewGroup$MarginLayoutParams(-1, -1));
       ViewStub viewStub = new ViewStub(relativeLayo.getContext());
       viewStub.setInflatedId(-1);
       RelativeLayout$LayoutParams layoutParams = new RelativeLayout$LayoutParams(-1, -2);
       viewStub.setId(R.id.share_publish_stub);
       layoutParams.addRule(12, -1);
       layoutParams.bottomMargin = c.b(resources, 0x7f0702b8);
       layoutParams.leftMargin = c.b(resources, 0x7f070cb5);
       layoutParams.rightMargin = c.b(resources, 0x7f070cb5);
       viewStub.setLayoutParams(layoutParams);
       relativeLayo.addView(viewStub);
       LinearLayout linearLayout = new LinearLayout(relativeLayo.getContext());
       layoutParams = new RelativeLayout$LayoutParams(-1, -1);
       linearLayout.setId(R.id.root);
       linearLayout.setClipChildren(false);
       layoutParams.addRule(2, R.id.publish_button_container);
       linearLayout.setOrientation(true);
       linearLayout.setLayoutParams(layoutParams);
       relativeLayo.addView(linearLayout);
       View view = new X2C_Share_Toolbar().createView(linearLayout.getContext());
       view.setLayoutParams(view.getLayoutParams());
       linearLayout.addView(view);
       LinearLayout linearLayout1 = new LinearLayout(linearLayout.getContext());
       linearLayout1.setLayoutParams(new LinearLayout$LayoutParams(-1, -2));
       linearLayout.addView(linearLayout1);
       ScrollViewEx scrollViewEx = new ScrollViewEx(linearLayout1.getContext());
       scrollViewEx.setId(R.id.scroll_container);
       scrollViewEx.setVerticalScrollBarEnabled(false);
       scrollViewEx.setHorizontalScrollBarEnabled(false);
       scrollViewEx.setLayoutParams(new LinearLayout$LayoutParams(-1, -1));
       linearLayout1.addView(scrollViewEx);
       LinearLayoutEx linearLayout2 = new LinearLayoutEx(scrollViewEx.getContext());
       linearLayout2.setId(R.id.options_container);
       linearLayout2.setClipChildren(false);
       linearLayout2.setClipToPadding(false);
       linearLayout2.setOrientation(true);
       linearLayout2.setLayoutParams(new FrameLayout$LayoutParams(-1, -2));
       scrollViewEx.addView(linearLayout2);
       View view1 = new X2C_Share_Un_Match_Topic_Tips_Wrap().createView(linearLayout2.getContext());
       view1.setLayoutParams(view1.getLayoutParams());
       linearLayout2.addView(view1);
       RelativeLayout relativeLayo1 = new RelativeLayout(linearLayout2.getContext());
       relativeLayo1.setId(R.id.share_content_wrap);
       relativeLayo1.setClipChildren(false);
       relativeLayo1.setLayoutParams(new LinearLayout$LayoutParams(-1, -2));
       linearLayout2.addView(relativeLayo1);
       FrameLayout uFrameLayout = new FrameLayout(relativeLayo1.getContext());
       RelativeLayout$LayoutParams layoutParams1 = new RelativeLayout$LayoutParams(-2, -2);
       uFrameLayout.setId(R.id.topic_guide_wrap);
       uFrameLayout.setClipChildren(false);
       layoutParams1.addRule(3, R.id.preview_root);
       uFrameLayout.setLayoutParams(layoutParams1);
       relativeLayo1.addView(uFrameLayout);
       uFrameLayout = new FrameLayout(relativeLayo1.getContext());
       layoutParams1 = new RelativeLayout$LayoutParams(-2, -2);
       uFrameLayout.setId(R.id.share_location_wrap);
       layoutParams1.addRule(3, R.id.topic_guide_wrap);
       uFrameLayout.setLayoutParams(layoutParams1);
       relativeLayo1.addView(uFrameLayout);
       view = new View(relativeLayo1.getContext());
       layoutParams1 = new RelativeLayout$LayoutParams(-1, (int)TypedValue.applyDimension(false, 0x3f800000, c.c(resources)));
       view.setBackgroundColor(resources.getColor(R.color.arg_RES_7f060a83));
       view.setId(R.id.locationv2_divider);
       layoutParams1.addRule(3, R.id.share_location_wrap);
       layoutParams1.leftMargin = c.b(resources, 0x7f070cb5);
       layoutParams1.rightMargin = c.b(resources, 0x7f070cb5);
       view.setVisibility(8);
       view.setLayoutParams(layoutParams1);
       relativeLayo1.addView(view);
       view = new X2C_Share_Mini_Program_Layout().createView(relativeLayo1.getContext());
       layoutParams1 = view.getLayoutParams();
       view.setId(R.id.share_mini_program_content);
       layoutParams1.addRule(3, R.id.locationv2_divider);
       view.setVisibility(8);
       view.setLayoutParams(layoutParams1);
       relativeLayo1.addView(view);
       View view2 = new View(relativeLayo1.getContext());
       layoutParams = new RelativeLayout$LayoutParams(-1, (int)TypedValue.applyDimension(false, 0x3f800000, c.c(resources)));
       view2.setBackgroundColor(resources.getColor(R.color.arg_RES_7f060a83));
       view2.setId(R.id.share_mini_program_divider);
       layoutParams.addRule(3, R.id.share_mini_program_content);
       layoutParams.leftMargin = c.b(resources, 0x7f070cb5);
       layoutParams.rightMargin = c.b(resources, 0x7f070cb5);
       view2.setVisibility(8);
       view2.setLayoutParams(layoutParams);
       relativeLayo1.addView(view2);
       ViewStub viewStub1 = new ViewStub(relativeLayo1.getContext());
       viewStub1.setInflatedId(-1);
       layoutParams = new RelativeLayout$LayoutParams(-1, -2);
       viewStub1.setId(R.id.photo_visibility_container_v2);
       viewStub1.setLayoutResource(R.layout.arg_RES_7f0d14f5);
       layoutParams.addRule(3, R.id.share_mini_program_divider);
       layoutParams.leftMargin = c.b(resources, 0x7f070e70);
       layoutParams.rightMargin = c.b(resources, 0x7f070e70);
       viewStub1.setLayoutParams(layoutParams);
       relativeLayo1.addView(viewStub1);
       viewStub1 = new ViewStub(relativeLayo1.getContext());
       viewStub1.setInflatedId(-1);
       layoutParams = new RelativeLayout$LayoutParams(-1, -2);
       viewStub1.setId(R.id.photo_visible_24_hours_layout);
       viewStub1.setLayoutResource(R.layout.arg_RES_7f0d14f6);
       layoutParams.addRule(3, R.id.photo_visibility_container_v2);
       layoutParams.leftMargin = c.b(resources, 0x7f070e70);
       layoutParams.rightMargin = c.b(resources, 0x7f070e70);
       viewStub1.setLayoutParams(layoutParams);
       relativeLayo1.addView(viewStub1);
       FrameLayout uFrameLayout1 = new FrameLayout(relativeLayo1.getContext());
       layoutParams = new RelativeLayout$LayoutParams(-1, c.b(resources, 0x7f070e6d));
       uFrameLayout1.setId(R.id.share_cocreator_info_container);
       layoutParams.addRule(3, R.id.photo_visibility_container_v2);
       uFrameLayout1.setVisibility(8);
       uFrameLayout1.setPadding(c.b(resources, R.dimen.arg_RES_7f070e70), false, c.b(resources, R.dimen.arg_RES_7f070e71), false);
       uFrameLayout1.setLayoutParams(layoutParams);
       relativeLayo1.addView(uFrameLayout1);
       view = new X2C_Share_Cocreator_Info().createView(uFrameLayout1.getContext());
       view.setLayoutParams(view.getLayoutParams());
       uFrameLayout1.addView(view);
       uFrameLayout1 = new FrameLayout(relativeLayo1.getContext());
       layoutParams = new RelativeLayout$LayoutParams(-1, c.b(resources, 0x7f070e6d));
       uFrameLayout1.setId(R.id.share_producer_wrap);
       layoutParams.addRule(3, R.id.share_cocreator_info_container);
       uFrameLayout1.setVisibility(8);
       uFrameLayout1.setPadding(c.b(resources, R.dimen.arg_RES_7f070e70), false, c.b(resources, R.dimen.arg_RES_7f070e71), false);
       uFrameLayout1.setLayoutParams(layoutParams);
       relativeLayo1.addView(uFrameLayout1);
       view = new X2C_Share_Business_Link_Layout().createView(uFrameLayout1.getContext());
       view.setLayoutParams(view.getLayoutParams());
       uFrameLayout1.addView(view);
       uFrameLayout1 = new FrameLayout(relativeLayo1.getContext());
       layoutParams = new RelativeLayout$LayoutParams(-1, c.b(resources, 0x7f070e6d));
       uFrameLayout1.setId(R.id.share_connect_hot);
       layoutParams.addRule(3, R.id.share_producer_wrap);
       uFrameLayout1.setVisibility(8);
       uFrameLayout1.setPadding(c.b(resources, R.dimen.arg_RES_7f070e70), false, c.b(resources, R.dimen.arg_RES_7f070e71), false);
       uFrameLayout1.setLayoutParams(layoutParams);
       relativeLayo1.addView(uFrameLayout1);
       view = new X2C_Share_Connect_Hot().createView(uFrameLayout1.getContext());
       view.setLayoutParams(view.getLayoutParams());
       uFrameLayout1.addView(view);
       uFrameLayout1 = new FrameLayout(relativeLayo1.getContext());
       layoutParams = new RelativeLayout$LayoutParams(-1, -2);
       uFrameLayout1.setId(R.id.share_judge_assistant_container);
       layoutParams.addRule(3, R.id.share_connect_hot);
       uFrameLayout1.setLayoutParams(layoutParams);
       relativeLayo1.addView(uFrameLayout1);
       ViewStub viewStub2 = new ViewStub(uFrameLayout1.getContext());
       viewStub2.setInflatedId(-1);
       viewStub2.setId(R.id.share_judge_assistant_stub);
       viewStub2.setLayoutResource(R.layout.arg_RES_7f0d14ed);
       viewStub2.setLayoutParams(new FrameLayout$LayoutParams(-1, -2));
       uFrameLayout1.addView(viewStub2);
       view2 = new X2C_Share_Custom_Item_V2().createView(relativeLayo1.getContext());
       layoutParams = view2.getLayoutParams();
       view2.setId(R.id.share_custom_item_v2);
       layoutParams.addRule(3, R.id.share_judge_assistant_container);
       view2.setVisibility(8);
       view2.setLayoutParams(layoutParams);
       relativeLayo1.addView(view2);
       view2 = new View(relativeLayo1.getContext());
       layoutParams = new RelativeLayout$LayoutParams(-1, -1);
       view2.setId(R.id.options_mask);
       layoutParams.addRule(3, R.id.topic_guide_wrap);
       view2.setMinimumHeight((int)TypedValue.applyDimension(1, 400.00f, c.c(resources)));
       view2.setVisibility(8);
       view2.setLayoutParams(layoutParams);
       relativeLayo1.addView(view2);
       view2 = new X2C_Share_Toolbar().createView(linearLayout.getContext());
       view2.setLayoutParams(view2.getLayoutParams());
       linearLayout.addView(view2);
       View view3 = new X2C_Share_Topic_List_Container_Layout().createView(relativeLayo.getContext());
       view3.setLayoutParams(view3.getLayoutParams());
       relativeLayo.addView(view3);
       DragPreviewContainer uDragPreview = new DragPreviewContainer(relativeLayo.getContext());
       uDragPreview.setId(R.id.preview_container);
       uDragPreview.setBackgroundColor(resources.getColor(R.color.arg_RES_7f060073));
       uDragPreview.setVisibility(8);
       uDragPreview.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       relativeLayo.addView(uDragPreview);
       return relativeLayo;
    }
}
