package com.kuaishou.ax2c.layouts.X2C_Vm_Nasa_Photo_Detail;
import com.kuaishou.ax2c.IViewCreator;
import java.lang.Object;
import android.content.Context;
import android.view.View;
import android.content.res.Resources;
import com.yxcorp.gifshow.detail.slidev2.widget.PressControlSpeedRelativeLayout;
import android.view.ViewGroup$MarginLayoutParams;
import android.widget.RelativeLayout;
import android.view.ViewGroup$LayoutParams;
import com.kuaishou.ax2c.layouts.X2C_Slide_V2_Photo_Detail_Video_Player;
import android.widget.RelativeLayout$LayoutParams;
import android.view.ViewStub;
import com.kwai.library.slide.base.widget.SlidePlayVerticalRelativeLayout;
import com.kwai.library.slide.base.widget.SlidePlayVerticalRelativeLayout$LayoutParams;
import android.util.DisplayMetrics;
import cw9.c;
import android.util.TypedValue;
import android.widget.FrameLayout;
import android.widget.FrameLayout$LayoutParams;
import androidx.appcompat.widget.AppCompatImageView;
import android.widget.ImageView;
import com.kuaishou.ax2c.layouts.X2C_Vm_Nasa_Float_Controller_Opt;
import com.kuaishou.ax2c.layouts.X2C_Vm_Slide_Play_Photo_Image_Tips_Layout;

public class X2C_Vm_Nasa_Photo_Detail implements IViewCreator	// class@00113b
{

    public void X2C_Vm_Nasa_Photo_Detail(){
       super();
    }
    public View createView(Context p0){
       Resources resources = p0.getResources();
       PressControlSpeedRelativeLayout pressControl = new PressControlSpeedRelativeLayout(p0);
       pressControl.setId(R.id.root);
       pressControl.setLayoutParams(new ViewGroup$MarginLayoutParams(-1, -1));
       View view = new X2C_Slide_V2_Photo_Detail_Video_Player().createView(pressControl.getContext());
       view.setLayoutParams(view.getLayoutParams());
       pressControl.addView(view);
       ViewStub viewStub = new ViewStub(pressControl.getContext());
       viewStub.setInflatedId(-1);
       viewStub.setId(R.id.anim_content_view_stub);
       viewStub.setLayoutResource(R.layout.arg_RES_7f0d105b);
       viewStub.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       pressControl.addView(viewStub);
       SlidePlayVerticalRelativeLayout slidePlayVer = new SlidePlayVerticalRelativeLayout(pressControl.getContext());
       slidePlayVer.setId(R.id.slide_v2_content_layout);
       slidePlayVer.setClipChildren(false);
       slidePlayVer.setClipToPadding(false);
       slidePlayVer.f(true);
       slidePlayVer.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       pressControl.addView(slidePlayVer);
       View view1 = new View(slidePlayVer.getContext());
       view1.setId(R.id.top_shadow);
       view1.setBackgroundResource(R.drawable.arg_RES_7f0820f5);
       view1.setVisibility(8);
       view1.setLayoutParams(new SlidePlayVerticalRelativeLayout$LayoutParams(-1, (int)TypedValue.applyDimension(true, 110.00f, c.c(resources))));
       slidePlayVer.addView(view1);
       view1 = new View(slidePlayVer.getContext());
       SlidePlayVerticalRelativeLayout$LayoutParams layoutParams = new SlidePlayVerticalRelativeLayout$LayoutParams(-1, c.b(resources, 0x7f0700db));
       view1.setId(R.id.bottom_shadow);
       layoutParams.addRule(12, -1);
       layoutParams.addRule(6, R.id.group_information_root_layout);
       layoutParams.topMargin = (int)TypedValue.applyDimension(true, -100.00f, c.c(resources));
       view1.setBackgroundResource(R.drawable.arg_RES_7f082082);
       view1.setLayoutParams(layoutParams);
       slidePlayVer.addView(view1);
       FrameLayout uFrameLayout = new FrameLayout(slidePlayVer.getContext());
       layoutParams = new SlidePlayVerticalRelativeLayout$LayoutParams(-1, (int)TypedValue.applyDimension(true, 0, c.c(resources)));
       uFrameLayout.setId(R.id.bottom_shadow_exp);
       layoutParams.addRule(12, -1);
       layoutParams.addRule(6, R.id.group_information_root_layout);
       layoutParams.topMargin = (int)TypedValue.applyDimension(true, -100.00f, c.c(resources));
       uFrameLayout.setVisibility(8);
       uFrameLayout.setLayoutParams(layoutParams);
       slidePlayVer.addView(uFrameLayout);
       View view2 = new View(uFrameLayout.getContext());
       FrameLayout$LayoutParams layoutParams1 = new FrameLayout$LayoutParams(-1, -1);
       layoutParams1.bottomMargin = c.b(resources, 0x7f070bf1);
       view2.setBackgroundResource(R.drawable.arg_RES_7f082082);
       view2.setLayoutParams(layoutParams1);
       uFrameLayout.addView(view2);
       view2 = new View(uFrameLayout.getContext());
       layoutParams1 = new FrameLayout$LayoutParams(-1, c.b(resources, 0x7f070bf1));
       layoutParams1.gravity = 80;
       view2.setBackgroundResource(R.drawable.arg_RES_7f082085);
       view2.setLayoutParams(layoutParams1);
       uFrameLayout.addView(view2);
       view1 = new View(slidePlayVer.getContext());
       SlidePlayVerticalRelativeLayout$LayoutParams layoutParams2 = new SlidePlayVerticalRelativeLayout$LayoutParams(-1, c.b(resources, 0x7f0700db));
       view1.setId(R.id.bottom_shadow_screen_clean);
       layoutParams2.addRule(12, -1);
       view1.setBackgroundResource(R.drawable.arg_RES_7f081987);
       view1.setVisibility(4);
       view1.setLayoutParams(layoutParams2);
       slidePlayVer.addView(view1);
       uFrameLayout = new FrameLayout(slidePlayVer.getContext());
       uFrameLayout.setId(R.id.photo_detail_placeholder);
       uFrameLayout.setLayoutParams(new SlidePlayVerticalRelativeLayout$LayoutParams(-1, -1));
       slidePlayVer.addView(uFrameLayout);
       AppCompatImageView uAppCompatIm = new AppCompatImageView(uFrameLayout.getContext());
       layoutParams1 = new FrameLayout$LayoutParams(-2, -2);
       uAppCompatIm.setId(R.id.photo_detail_placeholder_image);
       layoutParams1.gravity = 49;
       layoutParams1.topMargin = c.b(resources, 0x7f070eef);
       uAppCompatIm.setImageResource(R.drawable.arg_RES_7f080acb);
       uAppCompatIm.setLayoutParams(layoutParams1);
       uFrameLayout.addView(uAppCompatIm);
       View view3 = new X2C_Vm_Nasa_Float_Controller_Opt().createView(slidePlayVer.getContext());
       view3.setLayoutParams(view3.getLayoutParams());
       slidePlayVer.addView(view3);
       view3 = new X2C_Vm_Slide_Play_Photo_Image_Tips_Layout().createView(slidePlayVer.getContext());
       view3.setId(R.id.slide_play_image_tips_content);
       view3.setLayoutParams(view3.getLayoutParams());
       slidePlayVer.addView(view3);
       ViewStub viewStub1 = new ViewStub(slidePlayVer.getContext());
       viewStub1.setInflatedId(-1);
       viewStub1.setId(R.id.pause_broadcast_view_stub);
       viewStub1.setLayoutResource(R.layout.arg_RES_7f0d10fa);
       viewStub1.setLayoutParams(new SlidePlayVerticalRelativeLayout$LayoutParams(-1, -2));
       slidePlayVer.addView(viewStub1);
       viewStub1 = new ViewStub(pressControl.getContext());
       viewStub1.setInflatedId(-1);
       viewStub1.setId(R.id.friend_slide_play_item_place_holder);
       viewStub1.setInflatedId(R.id.friend_slide_play_item_container);
       viewStub1.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       pressControl.addView(viewStub1);
       viewStub1 = new ViewStub(pressControl.getContext());
       viewStub1.setInflatedId(-1);
       viewStub1.setId(R.id.slide_dragging_shadow_layer_view_stub);
       viewStub1.setInflatedId(R.id.slide_dragging_shadow_layer);
       viewStub1.setLayoutResource(R.layout.arg_RES_7f0d151c);
       viewStub1.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       pressControl.addView(viewStub1);
       return pressControl;
    }
}
