package com.kuaishou.ax2c.layouts.X2C_Camera_Actionbar_Fullscreen_V3;
import com.kuaishou.ax2c.IViewCreator;
import java.lang.Object;
import android.content.Context;
import android.view.View;
import android.content.res.Resources;
import androidx.constraintlayout.widget.ConstraintLayout;
import android.widget.FrameLayout$LayoutParams;
import android.util.DisplayMetrics;
import cw9.c;
import java.lang.Integer;
import android.util.TypedValue;
import android.view.ViewGroup;
import android.view.ViewGroup$LayoutParams;
import androidx.constraintlayout.widget.ConstraintLayout$LayoutParams;
import android.view.ViewStub;
import com.yxcorp.gifshow.widget.record.CaptureShadowView;
import com.kuaishou.ax2c.layouts.X2C_Record_Btn_Fullscreen_V3;
import com.kwai.feature.post.api.flywheel.widget.FlyWheelConstraintLayout;
import com.kuaishou.ax2c.layouts.X2C_Camera_Action_Bar_Magic_Layout;
import com.kuaishou.ax2c.layouts.X2C_Camera_Action_Bar_Magic_Banner_Layout;
import com.kuaishou.ax2c.layouts.X2C_Camera_Action_Bar_Prettify_Layout;
import android.widget.LinearLayout;
import android.widget.FrameLayout;
import android.widget.LinearLayout$LayoutParams;
import com.yxcorp.widget.selector.view.SelectShapeView;
import android.widget.ImageView;
import com.kuaishou.ax2c.XmlAttrHostImpl;
import com.kuaishou.ax2c.IAttrHost;
import ald.b;
import com.yxcorp.gifshow.image.KwaiImageView;
import com.facebook.drawee.view.SimpleDraweeView;
import com.yxcorp.gifshow.widget.PressedImageView;
import android.graphics.drawable.Drawable;
import android.widget.ImageView$ScaleType;
import ac.b;
import com.facebook.drawee.view.DraweeView;
import yb.a;
import androidx.core.content.ContextCompat;
import com.kwai.library.widget.textview.AlwaysMarqueeTextView;
import android.widget.TextView;
import android.text.TextUtils$TruncateAt;
import com.kuaishou.ax2c.layouts.X2C_Camera_Action_Bar_Album_Layout;
import android.view.ViewGroup$MarginLayoutParams;
import com.yxcorp.gifshow.widget.textview.PressedDisableWithAlphaImageView;
import androidx.appcompat.widget.AppCompatTextView;
import com.yxcorp.gifshow.widget.record.DeleteSegmentButton;
import android.util.AttributeSet;
import androidx.constraintlayout.widget.Guideline;

public class X2C_Camera_Actionbar_Fullscreen_V3 implements IViewCreator	// class@001092
{

    public void X2C_Camera_Actionbar_Fullscreen_V3(){
       super();
    }
    public View createView(Context p0){
       Context uContext = p0;
       Resources resources = p0.getResources();
       ConstraintLayout uConstraintL = new ConstraintLayout(uContext);
       Integer integer = Integer.valueOf(1);
       FrameLayout$LayoutParams layoutParams = new FrameLayout$LayoutParams(-1, (int)TypedValue.applyDimension(1, 190.00f, c.c(resources)));
       uConstraintL.setId(R.id.action_bar_layout);
       layoutParams.gravity = 80;
       uConstraintL.setClipChildren(false);
       uConstraintL.setClipToPadding(false);
       uConstraintL.setMotionEventSplittingEnabled(false);
       uConstraintL.setLayoutParams(layoutParams);
       View view = new View(uConstraintL.getContext());
       ConstraintLayout$LayoutParams layoutParams1 = new ConstraintLayout$LayoutParams(c.b(resources, 0x7f070f46), -2);
       view.setId(R.id.record_btn_guideline);
       layoutParams1.d = 0;
       layoutParams1.g = 0;
       layoutParams1.c();
       view.setLayoutParams(layoutParams1);
       uConstraintL.addView(view);
       ViewStub viewStub = new ViewStub(uConstraintL.getContext());
       viewStub.setInflatedId(-1);
       layoutParams1 = new ConstraintLayout$LayoutParams(-2, -2);
       viewStub.setId(R.id.assistant_refresh_stub);
       viewStub.setLayoutResource(R.layout.arg_RES_7f0d015e);
       layoutParams1.k = 0x7f0a0ff7;
       layoutParams1.g = 0;
       layoutParams1.h = 0;
       layoutParams1.c();
       viewStub.setLayoutParams(layoutParams1);
       uConstraintL.addView(viewStub);
       CaptureShadowView uCaptureShad = new CaptureShadowView(uConstraintL.getContext());
       layoutParams1 = new ConstraintLayout$LayoutParams((int)TypedValue.applyDimension(1, 112.00f, c.c(resources)), (int)TypedValue.applyDimension(1, 112.00f, c.c(resources)));
       uCaptureShad.setId(R.id.capture_btn_shadow);
       layoutParams1.k = 0x7f0a0ff7;
       layoutParams1.d = 0;
       layoutParams1.g = 0;
       layoutParams1.h = 0;
       layoutParams1.c();
       uCaptureShad.setLayoutParams(layoutParams1);
       uConstraintL.addView(uCaptureShad);
       view = new X2C_Record_Btn_Fullscreen_V3().createView(uConstraintL.getContext());
       layoutParams1 = view.getLayoutParams();
       view.setId(R.id.record_btn_layout);
       view.setVisibility(4);
       layoutParams1.k = 0x7f0a0ff7;
       layoutParams1.d = 0;
       layoutParams1.g = 0;
       layoutParams1.h = 0;
       layoutParams1.c();
       view.setLayoutParams(layoutParams1);
       uConstraintL.addView(view);
       viewStub = new ViewStub(uConstraintL.getContext());
       viewStub.setInflatedId(-1);
       layoutParams1 = new ConstraintLayout$LayoutParams(c.b(resources, 0x7f070269), c.b(resources, 0x7f070269));
       viewStub.setId(R.id.mix_record_btn_stub);
       viewStub.setLayoutResource(R.layout.arg_RES_7f0d0fd6);
       layoutParams1.k = 0x7f0a0ff7;
       layoutParams1.d = 0;
       layoutParams1.g = 0;
       layoutParams1.h = 0;
       layoutParams1.c();
       viewStub.setLayoutParams(layoutParams1);
       uConstraintL.addView(viewStub);
       viewStub = new ViewStub(uConstraintL.getContext());
       viewStub.setInflatedId(-1);
       layoutParams1 = new ConstraintLayout$LayoutParams(-2, -2);
       viewStub.setId(R.id.mix_record_tip_stub);
       layoutParams1.d = 0;
       layoutParams1.g = 0;
       viewStub.setLayoutResource(R.layout.arg_RES_7f0d0fd7);
       layoutParams1.j = 0x7f0a2bbd;
       layoutParams1.c();
       viewStub.setLayoutParams(layoutParams1);
       uConstraintL.addView(viewStub);
       FlyWheelConstraintLayout uFlyWheelCon = new FlyWheelConstraintLayout(uConstraintL.getContext());
       layoutParams1 = new ConstraintLayout$LayoutParams(-2, -2);
       uFlyWheelCon.setId(R.id.camera_magic_emoji_container);
       uFlyWheelCon.setClipChildren(false);
       uFlyWheelCon.setTextViewId(R.id.camera_magic_emoji_tv);
       uFlyWheelCon.setTKContainerId(R.id.fly_wheel_magic_tk_container);
       uFlyWheelCon.setClickViewId(R.id.camera_magic_emoji);
       layoutParams1.k = 0x7f0a05c9;
       layoutParams1.G = 0;
       layoutParams1.d = 0x7f0a29ea;
       layoutParams1.g = 0x7f0a29ea;
       layoutParams1.H = 2;
       layoutParams1.c();
       uFlyWheelCon.setLayoutParams(layoutParams1);
       uConstraintL.addView(uFlyWheelCon);
       View view1 = new X2C_Camera_Action_Bar_Magic_Layout().createView(uFlyWheelCon.getContext());
       ConstraintLayout$LayoutParams layoutParams2 = view1.getLayoutParams();
       view1.setId(R.id.camera_magic_emoji);
       layoutParams2.d = 0;
       layoutParams2.g = 0;
       layoutParams2.k = 0;
       layoutParams2.c();
       view1.setLayoutParams(layoutParams2);
       uFlyWheelCon.addView(view1);
       View view2 = new X2C_Camera_Action_Bar_Magic_Banner_Layout().createView(uFlyWheelCon.getContext());
       view2.setLayoutParams(view2.getLayoutParams());
       uFlyWheelCon.addView(view2);
       ConstraintLayout uConstraintL1 = new ConstraintLayout(uFlyWheelCon.getContext());
       layoutParams1 = new ConstraintLayout$LayoutParams((int)TypedValue.applyDimension(1, 0, c.c(resources)), (int)TypedValue.applyDimension(1, 0, c.c(resources)));
       uConstraintL1.setId(R.id.fly_wheel_magic_tk_container);
       layoutParams1.k = 0;
       layoutParams1.d = 0;
       layoutParams1.g = 0;
       layoutParams1.h = 0;
       layoutParams1.c();
       uConstraintL1.setLayoutParams(layoutParams1);
       uFlyWheelCon.addView(uConstraintL1);
       view = new X2C_Camera_Action_Bar_Prettify_Layout().createView(uConstraintL.getContext());
       ConstraintLayout$LayoutParams layoutParams3 = view.getLayoutParams();
       view.setId(R.id.button_prettify_container);
       layoutParams3.k = 0x7f0a0ff7;
       layoutParams3.G = 0;
       layoutParams3.e = 0x7f0a29ea;
       layoutParams3.f = 0x7f0a34a6;
       layoutParams3.h = 0;
       layoutParams3.H = 2;
       layoutParams3.c();
       view.setLayoutParams(layoutParams3);
       uConstraintL.addView(view);
       view = new View(uConstraintL.getContext());
       layoutParams3 = new ConstraintLayout$LayoutParams(c.b(resources, 0x7f07011e), -2);
       view.setId(R.id.magic_btn_guideline);
       view.setVisibility(4);
       layoutParams3.k = 0x7f0a0ff7;
       layoutParams3.G = 0;
       layoutParams3.d = 0;
       layoutParams3.f = 0x7f0a31bb;
       layoutParams3.h = 0;
       layoutParams3.H = 2;
       layoutParams3.c();
       view.setLayoutParams(layoutParams3);
       uConstraintL.addView(view);
       view = new View(uConstraintL.getContext());
       layoutParams3 = new ConstraintLayout$LayoutParams(c.b(resources, 0x7f07011e), -2);
       view.setId(R.id.prettify_btn_guideline);
       view.setVisibility(4);
       layoutParams3.k = 0x7f0a0ff7;
       layoutParams3.G = 0;
       layoutParams3.e = 0x7f0a29ea;
       layoutParams3.f = 0x7f0a34a6;
       layoutParams3.h = 0;
       layoutParams3.H = 2;
       layoutParams3.c();
       view.setLayoutParams(layoutParams3);
       uConstraintL.addView(view);
       view = new View(uConstraintL.getContext());
       layoutParams3 = new ConstraintLayout$LayoutParams(c.b(resources, 0x7f07011e), -2);
       view.setId(R.id.music_btn_guideline);
       view.setVisibility(4);
       layoutParams3.k = 0x7f0a0ff7;
       layoutParams3.G = 0;
       layoutParams3.e = 0x7f0a34a6;
       layoutParams3.f = 0x7f0a0eaf;
       layoutParams3.h = 0;
       layoutParams3.H = 2;
       layoutParams3.c();
       view.setLayoutParams(layoutParams3);
       uConstraintL.addView(view);
       view = new View(uConstraintL.getContext());
       layoutParams3 = new ConstraintLayout$LayoutParams(c.b(resources, 0x7f07011e), -2);
       view.setId(R.id.finish_btn_guideline);
       view.setVisibility(4);
       layoutParams3.k = 0x7f0a0ff7;
       layoutParams3.G = 0;
       layoutParams3.e = 0x7f0a2c6b;
       layoutParams3.g = 0;
       layoutParams3.h = 0;
       layoutParams3.H = 2;
       layoutParams3.c();
       view.setLayoutParams(layoutParams3);
       uConstraintL.addView(view);
       uFlyWheelCon = new FlyWheelConstraintLayout(uConstraintL.getContext());
       layoutParams3 = new ConstraintLayout$LayoutParams(-2, -2);
       uFlyWheelCon.setId(R.id.button_switch_music_layout);
       uFlyWheelCon.setVisibility(4);
       uFlyWheelCon.setTKContainerId(R.id.fly_wheel_music_tk_container);
       uFlyWheelCon.setTextViewId(R.id.music_name_tv);
       layoutParams3.k = 0x7f0a0ff7;
       layoutParams3.G = 0;
       layoutParams3.d = 0x7f0a2c6b;
       layoutParams3.g = 0x7f0a2c6b;
       layoutParams3.h = 0;
       layoutParams3.H = 2;
       layoutParams3.c();
       uFlyWheelCon.setLayoutParams(layoutParams3);
       uConstraintL.addView(uFlyWheelCon);
       LinearLayout linearLayout = new LinearLayout(uFlyWheelCon.getContext());
       linearLayout.setGravity(1);
       linearLayout.setOrientation(1);
       linearLayout.setLayoutParams(new ConstraintLayout$LayoutParams(-2, -2));
       uFlyWheelCon.addView(linearLayout);
       FrameLayout uFrameLayout = new FrameLayout(linearLayout.getContext());
       uFrameLayout.setLayoutParams(new LinearLayout$LayoutParams(-2, -2));
       linearLayout.addView(uFrameLayout);
       SelectShapeView selectShapeV = new SelectShapeView(uFrameLayout.getContext());
       selectShapeV.setId(R.id.button_music_color_bg);
       selectShapeV.setVisibility(8);
       XmlAttrHostImpl xmlAttrHostI = new XmlAttrHostImpl();
       xmlAttrHostI.addAttr(26, integer);
       xmlAttrHostI.addAttr(29, Integer.valueOf(resources.getColor(R.color.arg_RES_7f061cea)));
       IAttrHost[] iAttrHostArr = new IAttrHost[]{xmlAttrHostI,new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl()};
       selectShapeV.setAttrs(iAttrHostArr);
       selectShapeV.setLayoutParams(new FrameLayout$LayoutParams(c.b(resources, R.dimen.arg_RES_7f070319), c.b(resources, R.dimen.arg_RES_7f070319)));
       uFrameLayout.addView(selectShapeV);
       FrameLayout uFrameLayout1 = new FrameLayout(uFrameLayout.getContext());
       FrameLayout$LayoutParams layoutParams4 = new FrameLayout$LayoutParams(-2, -2);
       uFrameLayout1.setId(R.id.music_disk_layout);
       layoutParams4.gravity = 17;
       uFrameLayout1.setLayoutParams(layoutParams4);
       uFrameLayout.addView(uFrameLayout1);
       KwaiImageView kwaiImageVie = new KwaiImageView(uFrameLayout1.getContext());
       FrameLayout$LayoutParams layoutParams5 = new FrameLayout$LayoutParams(c.b(resources, 0x7f070319), c.b(resources, 0x7f070319));
       kwaiImageVie.setId(R.id.music_play_disk_background);
       layoutParams5.gravity = 17;
       kwaiImageVie.setVisibility(8);
       kwaiImageVie.setActualImageResource(R.drawable.arg_RES_7f081c9e);
       kwaiImageVie.setLayoutParams(layoutParams5);
       uFrameLayout1.addView(kwaiImageVie);
       PressedImageView pressedImage = new PressedImageView(uFrameLayout1.getContext());
       layoutParams5 = new FrameLayout$LayoutParams(c.b(resources, 0x7f07011d), c.b(resources, 0x7f07011d));
       pressedImage.setBackgroundDrawable(null);
       pressedImage.setScaleType(ImageView$ScaleType.FIT_CENTER);
       pressedImage.setId(R.id.button_switch_music);
       layoutParams5.gravity = 17;
       pressedImage.setDisableAlpha(0.40f);
       pressedImage.setPressedAlpha(0.40f);
       pressedImage.getHierarchy().F(ContextCompat.getDrawable(uContext, R.drawable.arg_RES_7f081c25));
       pressedImage.setLayoutParams(layoutParams5);
       uFrameLayout1.addView(pressedImage);
       ViewStub viewStub1 = new ViewStub(uFrameLayout.getContext());
       viewStub1.setInflatedId(-1);
       viewStub1.setId(R.id.button_music_frame_stub);
       viewStub1.setLayoutResource(R.layout.arg_RES_7f0d0157);
       viewStub1.setLayoutParams(new FrameLayout$LayoutParams(c.b(resources, R.dimen.arg_RES_7f07011d), c.b(resources, R.dimen.arg_RES_7f07011d)));
       uFrameLayout.addView(viewStub1);
       viewStub1 = new ViewStub(uFrameLayout.getContext());
       viewStub1.setInflatedId(-1);
       FrameLayout$LayoutParams layoutParams6 = new FrameLayout$LayoutParams(c.b(resources, 0x7f07011d), c.b(resources, 0x7f07011d));
       viewStub1.setId(R.id.button_switch_music_cover_stub);
       layoutParams6.gravity = 1;
       viewStub1.setLayoutResource(R.layout.arg_RES_7f0d0159);
       viewStub1.setLayoutParams(layoutParams6);
       uFrameLayout.addView(viewStub1);
       AlwaysMarqueeTextView uAlwaysMarqu = new AlwaysMarqueeTextView(linearLayout.getContext());
       uAlwaysMarqu.setTextSize(false, (float)c.b(resources, R.dimen.arg_RES_7f070f6d));
       uAlwaysMarqu.setShadowLayer(0x3f800000, uAlwaysMarqu.getShadowDx(), uAlwaysMarqu.getShadowDy(), uAlwaysMarqu.getShadowColor());
       uAlwaysMarqu.setSingleLine(1);
       uAlwaysMarqu.setMaxWidth(c.b(resources, R.dimen.arg_RES_7f07011f));
       uAlwaysMarqu.setShadowLayer(uAlwaysMarqu.getShadowRadius(), 3.00f, uAlwaysMarqu.getShadowDy(), uAlwaysMarqu.getShadowColor());
       uAlwaysMarqu.setShadowLayer(uAlwaysMarqu.getShadowRadius(), uAlwaysMarqu.getShadowDx(), uAlwaysMarqu.getShadowDy(), resources.getColor(R.color.arg_RES_7f06010e));
       uAlwaysMarqu.setTextColor(resources.getColor(R.color.arg_RES_7f060113));
       uAlwaysMarqu.setShadowLayer(uAlwaysMarqu.getShadowRadius(), uAlwaysMarqu.getShadowDx(), 3.00f, uAlwaysMarqu.getShadowColor());
       uAlwaysMarqu.setIncludeFontPadding(false);
       uAlwaysMarqu.setId(R.id.music_name_tv);
       uAlwaysMarqu.setEllipsize(TextUtils$TruncateAt.MARQUEE);
       uAlwaysMarqu.setGravity(17);
       uAlwaysMarqu.setMarqueeRepeatLimit(-1);
       uAlwaysMarqu.setText(R.string.arg_RES_7f103703);
       uAlwaysMarqu.setLayoutParams(new LinearLayout$LayoutParams((int)TypedValue.applyDimension(1, 60.00f, c.c(resources)), c.b(resources, R.dimen.arg_RES_7f070120)));
       linearLayout.addView(uAlwaysMarqu);
       ConstraintLayout uConstraintL2 = new ConstraintLayout(uFlyWheelCon.getContext());
       layoutParams3 = new ConstraintLayout$LayoutParams((int)TypedValue.applyDimension(1, 0, c.c(resources)), (int)TypedValue.applyDimension(1, 0, c.c(resources)));
       uConstraintL2.setId(R.id.fly_wheel_music_tk_container);
       layoutParams3.k = 0;
       layoutParams3.d = 0;
       layoutParams3.g = 0;
       layoutParams3.h = 0;
       layoutParams3.c();
       uConstraintL2.setLayoutParams(layoutParams3);
       uFlyWheelCon.addView(uConstraintL2);
       View view3 = new X2C_Camera_Action_Bar_Album_Layout().createView(uConstraintL.getContext());
       ConstraintLayout$LayoutParams layoutParams7 = view3.getLayoutParams();
       view3.setVisibility(4);
       layoutParams7.k = 0x7f0a0ff7;
       layoutParams7.G = 0;
       layoutParams7.e = 0x7f0a2c6b;
       layoutParams7.g = 0;
       layoutParams7.h = 0;
       layoutParams7.H = 2;
       layoutParams7.c();
       view3.setLayoutParams(layoutParams7);
       uConstraintL.addView(view3);
       viewStub1 = new ViewStub(uConstraintL.getContext());
       viewStub1.setInflatedId(-1);
       layoutParams7 = new ConstraintLayout$LayoutParams(-2, -2);
       viewStub1.setId(R.id.finish_record_layout_stub);
       viewStub1.setLayoutResource(R.layout.arg_RES_7f0d044f);
       layoutParams7.k = 0x7f0a0ff7;
       layoutParams7.G = 0;
       layoutParams7.e = 0x7f0a34a6;
       layoutParams7.f = 0x7f0a1656;
       layoutParams7.g = 0;
       layoutParams7.h = 0;
       layoutParams7.H = 2;
       layoutParams7.c();
       viewStub1.setLayoutParams(layoutParams7);
       uConstraintL.addView(viewStub1);
       viewStub1 = new ViewStub(uConstraintL.getContext());
       viewStub1.setInflatedId(-1);
       layoutParams7 = new ConstraintLayout$LayoutParams(-2, -2);
       viewStub1.setId(R.id.ktv_mv_music_selection_layout_stub);
       viewStub1.setLayoutResource(R.layout.arg_RES_7f0d0711);
       layoutParams7.k = 0x7f0a0ff7;
       layoutParams7.G = 0;
       layoutParams7.e = 0x7f0a34a6;
       layoutParams7.f = 0x7f0a1656;
       layoutParams7.h = 0;
       layoutParams7.H = 2;
       layoutParams7.c();
       viewStub1.setLayoutParams(layoutParams7);
       uConstraintL.addView(viewStub1);
       viewStub1 = new ViewStub(uConstraintL.getContext());
       viewStub1.setInflatedId(-1);
       layoutParams3 = new ConstraintLayout$LayoutParams(-1, c.b(resources, 0x7f07033d));
       viewStub1.setId(R.id.camera_assistant_stub);
       layoutParams3.k = 0x7f0a0ff7;
       layoutParams3.d = 0;
       layoutParams3.g = 0;
       layoutParams3.h = 0;
       layoutParams3.c();
       viewStub1.setLayoutParams(layoutParams3);
       uConstraintL.addView(viewStub1);
       LinearLayout linearLayout1 = new LinearLayout(uConstraintL.getContext());
       layoutParams7 = new ConstraintLayout$LayoutParams(-2, -2);
       linearLayout1.setId(R.id.ktv_mv_voice_option_container);
       layoutParams7.rightMargin = (int)TypedValue.applyDimension(1, 5.00f, c.c(resources));
       linearLayout1.setGravity(1);
       linearLayout1.setOrientation(1);
       linearLayout1.setVisibility(8);
       layoutParams7.k = 0x7f0a0ff7;
       layoutParams7.G = 0;
       layoutParams7.e = 0x7f0a0eb5;
       layoutParams7.g = 0;
       layoutParams7.h = 0;
       layoutParams7.H = 2;
       layoutParams7.c();
       linearLayout1.setLayoutParams(layoutParams7);
       uConstraintL.addView(linearLayout1);
       FrameLayout uFrameLayout2 = new FrameLayout(linearLayout1.getContext());
       uFrameLayout2.setLayoutParams(new LinearLayout$LayoutParams(-2, -2));
       linearLayout1.addView(uFrameLayout2);
       SelectShapeView selectShapeV1 = new SelectShapeView(uFrameLayout2.getContext());
       selectShapeV1.setId(R.id.button_ktv_voice_color_bg);
       selectShapeV1.setVisibility(8);
       XmlAttrHostImpl xmlAttrHostI1 = new XmlAttrHostImpl();
       xmlAttrHostI1.addAttr(26, integer);
       xmlAttrHostI1.addAttr(29, Integer.valueOf(resources.getColor(R.color.arg_RES_7f061cea)));
       iAttrHostArr = new IAttrHost[]{xmlAttrHostI1,new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl()};
       selectShapeV1.setAttrs(iAttrHostArr);
       selectShapeV1.setLayoutParams(new FrameLayout$LayoutParams(c.b(resources, R.dimen.arg_RES_7f070319), c.b(resources, R.dimen.arg_RES_7f070319)));
       uFrameLayout2.addView(selectShapeV1);
       PressedDisableWithAlphaImageView pressedDisab = new PressedDisableWithAlphaImageView(uFrameLayout2.getContext());
       FrameLayout$LayoutParams layoutParams8 = new FrameLayout$LayoutParams(c.b(resources, 0x7f07011d), c.b(resources, 0x7f07011d));
       pressedDisab.setBackgroundDrawable(null);
       pressedDisab.setScaleType(ImageView$ScaleType.FIT_CENTER);
       pressedDisab.setId(R.id.ktv_song_option_btn);
       layoutParams8.gravity = 17;
       pressedDisab.setImageResource(R.drawable.arg_RES_7f081c13);
       pressedDisab.setLayoutParams(layoutParams8);
       uFrameLayout2.addView(pressedDisab);
       AppCompatTextView uAppCompatTe = new AppCompatTextView(linearLayout1.getContext());
       uAppCompatTe.setTextSize(false, (float)c.b(resources, R.dimen.arg_RES_7f070f6d));
       uAppCompatTe.setShadowLayer(0x3f800000, uAppCompatTe.getShadowDx(), uAppCompatTe.getShadowDy(), uAppCompatTe.getShadowColor());
       uAppCompatTe.setSingleLine(1);
       uAppCompatTe.setMaxWidth(c.b(resources, R.dimen.arg_RES_7f07011f));
       uAppCompatTe.setShadowLayer(uAppCompatTe.getShadowRadius(), 3.00f, uAppCompatTe.getShadowDy(), uAppCompatTe.getShadowColor());
       uAppCompatTe.setShadowLayer(uAppCompatTe.getShadowRadius(), uAppCompatTe.getShadowDx(), uAppCompatTe.getShadowDy(), resources.getColor(R.color.arg_RES_7f06010e));
       uAppCompatTe.setTextColor(resources.getColor(R.color.arg_RES_7f060113));
       uAppCompatTe.setEllipsize(TextUtils$TruncateAt.END);
       uAppCompatTe.setShadowLayer(uAppCompatTe.getShadowRadius(), uAppCompatTe.getShadowDx(), 3.00f, uAppCompatTe.getShadowColor());
       uAppCompatTe.setGravity(17);
       uAppCompatTe.setIncludeFontPadding(false);
       uAppCompatTe.setId(R.id.ktv_song_option_text);
       uAppCompatTe.setText(R.string.arg_RES_7f101b1a);
       uAppCompatTe.setLayoutParams(new LinearLayout$LayoutParams(-2, c.b(resources, R.dimen.arg_RES_7f070120)));
       linearLayout1.addView(uAppCompatTe);
       viewStub1 = new ViewStub(uConstraintL.getContext());
       viewStub1.setInflatedId(-1);
       layoutParams7 = new ConstraintLayout$LayoutParams(-2, -2);
       viewStub1.setId(R.id.same_frame_layout_btn_container_stub);
       layoutParams7.k = 0x7f0a0ff7;
       layoutParams7.G = 0;
       layoutParams7.e = 0x7f0a34a6;
       viewStub1.setLayoutResource(R.layout.arg_RES_7f0d132f);
       layoutParams7.g = 0;
       layoutParams7.h = 0;
       layoutParams7.H = 2;
       layoutParams7.c();
       viewStub1.setLayoutParams(layoutParams7);
       uConstraintL.addView(viewStub1);
       viewStub1 = new ViewStub(uConstraintL.getContext());
       viewStub1.setInflatedId(-1);
       layoutParams7 = new ConstraintLayout$LayoutParams(-2, -2);
       viewStub1.setId(R.id.sameframe_use_record_sound_btn_layout_stub);
       viewStub1.setLayoutResource(R.layout.arg_RES_7f0d1334);
       layoutParams7.k = 0x7f0a0ff7;
       layoutParams7.G = 0;
       layoutParams7.e = 0x7f0a2c6b;
       layoutParams7.g = 0;
       layoutParams7.h = 0;
       layoutParams7.H = 2;
       layoutParams7.c();
       viewStub1.setLayoutParams(layoutParams7);
       uConstraintL.addView(viewStub1);
       DeleteSegmentButton uDeleteSegme = new DeleteSegmentButton(uConstraintL.getContext(), null, false);
       layoutParams7 = new ConstraintLayout$LayoutParams(-2, (int)TypedValue.applyDimension(1, 0, c.c(resources)));
       uDeleteSegme.setId(R.id.delete_segment_btn);
       uDeleteSegme.setBackgroundDrawable(null);
       uDeleteSegme.setGravity(17);
       uDeleteSegme.setText(R.string.arg_RES_7f104270);
       uDeleteSegme.setTextColor(resources.getColor(R.color.arg_RES_7f061ce5));
       uDeleteSegme.setTextSize(false, (float)c.b(resources, R.dimen.arg_RES_7f070f6d));
       uDeleteSegme.setVisibility(8);
       layoutParams7.k = 0x7f0a0ff7;
       layoutParams7.d = 0;
       layoutParams7.g = 0;
       layoutParams7.i = 0x7f0a34a7;
       layoutParams7.c();
       uDeleteSegme.setLayoutParams(layoutParams7);
       uConstraintL.addView(uDeleteSegme);
       AppCompatTextView uAppCompatTe1 = new AppCompatTextView(uConstraintL.getContext());
       layoutParams7 = new ConstraintLayout$LayoutParams(-2, (int)TypedValue.applyDimension(1, 0, c.c(resources)));
       uAppCompatTe1.setId(R.id.complete_tv);
       uAppCompatTe1.setBackgroundDrawable(null);
       uAppCompatTe1.setGravity(17);
       uAppCompatTe1.setText(R.string.arg_RES_7f1048b1);
       uAppCompatTe1.setTextColor(resources.getColor(R.color.arg_RES_7f061ce5));
       uAppCompatTe1.setTextSize(false, (float)c.b(resources, R.dimen.arg_RES_7f070f6d));
       uAppCompatTe1.setVisibility(8);
       uAppCompatTe1.setShadowLayer(uAppCompatTe1.getShadowRadius(), 0x3f800000, uAppCompatTe1.getShadowDy(), uAppCompatTe1.getShadowColor());
       uAppCompatTe1.setShadowLayer(uAppCompatTe1.getShadowRadius(), uAppCompatTe1.getShadowDx(), 0x3f800000, uAppCompatTe1.getShadowColor());
       uAppCompatTe1.setShadowLayer(0x3f800000, uAppCompatTe1.getShadowDx(), uAppCompatTe1.getShadowDy(), uAppCompatTe1.getShadowColor());
       uAppCompatTe1.setShadowLayer(uAppCompatTe1.getShadowRadius(), uAppCompatTe1.getShadowDx(), uAppCompatTe1.getShadowDy(), resources.getColor(R.color.arg_RES_7f06010e));
       layoutParams7.k = 0x7f0a0ff7;
       layoutParams7.d = 0;
       layoutParams7.g = 0;
       layoutParams7.i = 0x7f0a34a7;
       layoutParams7.c();
       uAppCompatTe1.setLayoutParams(layoutParams7);
       uConstraintL.addView(uAppCompatTe1);
       Guideline guideline = new Guideline(uConstraintL.getContext());
       layoutParams7 = new ConstraintLayout$LayoutParams(-2, -2);
       guideline.setId(R.id.frame_bottom_guide_line);
       layoutParams7.S = 0;
       layoutParams7.b = (int)TypedValue.applyDimension(1, 0, c.c(resources));
       layoutParams7.c();
       guideline.setLayoutParams(layoutParams7);
       uConstraintL.addView(guideline);
       guideline = new Guideline(uConstraintL.getContext());
       layoutParams7 = new ConstraintLayout$LayoutParams(-2, -2);
       guideline.setId(R.id.action_bar_bottom_black_guide_line);
       layoutParams7.S = 0;
       layoutParams7.b = (int)TypedValue.applyDimension(1, 0, c.c(resources));
       layoutParams7.c();
       guideline.setLayoutParams(layoutParams7);
       uConstraintL.addView(guideline);
       return uConstraintL;
    }
}
