package com.kuaishou.ax2c.layouts.X2C_Kwai_Title_Edit;
import com.kuaishou.ax2c.IViewCreator;
import java.lang.Object;
import android.content.Context;
import android.view.View;
import android.content.res.Resources;
import android.widget.RelativeLayout;
import android.util.TypedValue;
import android.content.res.Resources$Theme;
import android.widget.RelativeLayout$LayoutParams;
import android.util.DisplayMetrics;
import cw9.c;
import android.view.ViewGroup$LayoutParams;
import android.widget.LinearLayout;
import androidx.appcompat.widget.AppCompatImageView;
import android.widget.LinearLayout$LayoutParams;
import android.widget.ImageView;
import android.graphics.drawable.Drawable;
import android.widget.ImageView$ScaleType;
import com.kwai.library.widget.textview.SizeAdjustableTextView;
import android.widget.TextView;
import androidx.appcompat.widget.AppCompatTextView;
import com.kwai.library.widget.textview.KwaiSizeAdjustableTextView;
import androidx.appcompat.widget.AppCompatButton;
import android.util.AttributeSet;
import android.widget.Button;
import android.graphics.Typeface;
import com.yxcorp.gifshow.widget.EmojiTextView;
import androidx.constraintlayout.widget.ConstraintLayout;
import android.view.ViewGroup;
import androidx.constraintlayout.widget.ConstraintLayout$LayoutParams;

public class X2C_Kwai_Title_Edit implements IViewCreator	// class@0010b6
{

    public void X2C_Kwai_Title_Edit(){
       super();
    }
    public View createView(Context p0){
       Resources resources = p0.getResources();
       RelativeLayout relativeLayo = new RelativeLayout(p0);
       TypedValue typedValue = new TypedValue();
       p0.getTheme().resolveAttribute(R.attr.arg_RES_7f0400f6, typedValue, true);
       relativeLayo.setId(R.id.title_root);
       relativeLayo.setLayoutParams(new RelativeLayout$LayoutParams(-1, TypedValue.complexToDimensionPixelOffset(typedValue.data, c.c(resources))));
       View view = new View(relativeLayo.getContext());
       TypedValue typedValue1 = new TypedValue();
       p0.getTheme().resolveAttribute(R.attr.arg_RES_7f0400f6, typedValue1, true);
       view.setId(R.id.ktv_score_shadow);
       view.setBackgroundResource(R.drawable.arg_RES_7f081029);
       view.setVisibility(8);
       view.setLayoutParams(new RelativeLayout$LayoutParams(-1, TypedValue.complexToDimensionPixelOffset(typedValue1.data, c.c(resources))));
       relativeLayo.addView(view);
       LinearLayout linearLayout = new LinearLayout(relativeLayo.getContext());
       RelativeLayout$LayoutParams layoutParams = new RelativeLayout$LayoutParams(-2, -1);
       linearLayout.setId(R.id.left_btn_container);
       layoutParams.addRule(9, -1);
       layoutParams.addRule(15, -1);
       linearLayout.setGravity(19);
       linearLayout.setOrientation(0);
       linearLayout.setLayoutParams(layoutParams);
       relativeLayo.addView(linearLayout);
       AppCompatImageView uAppCompatIm = new AppCompatImageView(linearLayout.getContext());
       TypedValue typedValue2 = new TypedValue();
       p0.getTheme().resolveAttribute(R.attr.arg_RES_7f0400f6, typedValue2, true);
       TypedValue typedValue3 = new TypedValue();
       p0.getTheme().resolveAttribute(R.attr.arg_RES_7f0400f6, typedValue3, true);
       uAppCompatIm.setId(R.id.left_btn);
       uAppCompatIm.setBackgroundDrawable(null);
       uAppCompatIm.setScaleType(ImageView$ScaleType.CENTER_INSIDE);
       uAppCompatIm.setLayoutParams(new LinearLayout$LayoutParams(TypedValue.complexToDimensionPixelOffset(typedValue2.data, c.c(resources)), TypedValue.complexToDimensionPixelOffset(typedValue3.data, c.c(resources))));
       linearLayout.addView(uAppCompatIm);
       SizeAdjustableTextView sizeAdjustab = new SizeAdjustableTextView(linearLayout.getContext());
       LinearLayout$LayoutParams layoutParams1 = new LinearLayout$LayoutParams(-2, (int)TypedValue.applyDimension(true, 23.00f, c.c(resources)));
       sizeAdjustab.setId(R.id.left_btn_text);
       layoutParams1.setMarginStart((int)TypedValue.applyDimension(true, -6.00f, c.c(resources)));
       sizeAdjustab.setGravity(17);
       sizeAdjustab.setShadowLayer(sizeAdjustab.getShadowRadius(), sizeAdjustab.getShadowDx(), sizeAdjustab.getShadowDy(), resources.getColor(R.color.arg_RES_7f061c10));
       sizeAdjustab.setShadowLayer(sizeAdjustab.getShadowRadius(), sizeAdjustab.getShadowDx(), 2.00f, sizeAdjustab.getShadowColor());
       sizeAdjustab.setShadowLayer(2.00f, sizeAdjustab.getShadowDx(), sizeAdjustab.getShadowDy(), sizeAdjustab.getShadowColor());
       sizeAdjustab.setTextColor(resources.getColor(R.color.arg_RES_7f060a05));
       sizeAdjustab.setTextSize(2, 15.00f);
       sizeAdjustab.setInitTextSize(TypedValue.applyDimension(2, 15.00f, c.c(resources)));
       sizeAdjustab.setTextSizeAdjustWithHeight(true);
       sizeAdjustab.setTextSizeAdjustable(true);
       sizeAdjustab.setLayoutParams(layoutParams1);
       linearLayout.addView(sizeAdjustab);
       AppCompatButton uAppCompatBu = new AppCompatButton(relativeLayo.getContext(), null, 0);
       RelativeLayout$LayoutParams layoutParams2 = new RelativeLayout$LayoutParams(-2, (int)TypedValue.applyDimension(true, 28.00f, c.c(resources)));
       uAppCompatBu.setBackgroundResource(R.drawable.arg_RES_7f0801c8);
       uAppCompatBu.setId(R.id.right_btn);
       layoutParams2.addRule(0, R.id.photo_visibility_btn);
       layoutParams2.addRule(11, -1);
       layoutParams2.addRule(15, -1);
       layoutParams2.topMargin = (int)TypedValue.applyDimension(true, 15.00f, c.c(resources));
       layoutParams2.rightMargin = (int)TypedValue.applyDimension(true, 15.00f, c.c(resources));
       uAppCompatBu.setGravity(17);
       uAppCompatBu.setMaxLines(true);
       uAppCompatBu.setText(R.string.arg_RES_7f100f6b);
       uAppCompatBu.setTextColor(resources.getColor(R.color.arg_RES_7f0600e0));
       uAppCompatBu.setTextSize(0, (float)c.b(resources, R.dimen.arg_RES_7f070f67));
       uAppCompatBu.setVisibility(4);
       uAppCompatBu.setPadding((int)TypedValue.applyDimension(true, 10.00f, c.c(resources)), 0, (int)TypedValue.applyDimension(true, 10.00f, c.c(resources)), 0);
       uAppCompatBu.setLayoutParams(layoutParams2);
       relativeLayo.addView(uAppCompatBu);
       uAppCompatBu = new AppCompatButton(relativeLayo.getContext(), null, 0);
       RelativeLayout$LayoutParams layoutParams3 = new RelativeLayout$LayoutParams(-2, c.b(resources, 0x7f0702df));
       uAppCompatBu.setId(R.id.photo_visibility_btn);
       layoutParams3.addRule(11, -1);
       layoutParams3.addRule(15, -1);
       layoutParams3.rightMargin = c.b(resources, 0x7f0702ab);
       uAppCompatBu.setBackgroundResource(R.drawable.arg_RES_7f0801fd);
       uAppCompatBu.setGravity(17);
       uAppCompatBu.setCompoundDrawablePadding(c.b(resources, R.dimen.arg_RES_7f0702e3));
       uAppCompatBu.setText(R.string.arg_RES_7f100ccf);
       uAppCompatBu.setTypeface(null, true);
       uAppCompatBu.setTextColor(resources.getColor(R.color.arg_RES_7f0619f2));
       uAppCompatBu.setTextSize(0, (float)c.b(resources, R.dimen.arg_RES_7f070f6e));
       uAppCompatBu.setVisibility(8);
       uAppCompatBu.setPadding(c.b(resources, R.dimen.arg_RES_7f070271), 0, c.b(resources, R.dimen.arg_RES_7f07034b), 0);
       uAppCompatBu.setLayoutParams(layoutParams3);
       relativeLayo.addView(uAppCompatBu);
       uAppCompatBu = new AppCompatButton(relativeLayo.getContext(), null, 0);
       layoutParams3 = new RelativeLayout$LayoutParams(-2, -2);
       uAppCompatBu.setId(R.id.ktv_title_edit_scores);
       layoutParams3.addRule(11, -1);
       layoutParams3.addRule(15, -1);
       layoutParams3.rightMargin = (int)TypedValue.applyDimension(true, 15.00f, c.c(resources));
       uAppCompatBu.setBackgroundResource(R.drawable.arg_RES_7f08102a);
       uAppCompatBu.setMaxLines(true);
       uAppCompatBu.setTextColor(resources.getColor(R.color.arg_RES_7f061ff3));
       uAppCompatBu.setVisibility(8);
       uAppCompatBu.setPadding((int)TypedValue.applyDimension(true, 12.00f, c.c(resources)), c.b(resources, R.dimen.arg_RES_7f07033f), (int)TypedValue.applyDimension(true, 12.00f, c.c(resources)), c.b(resources, R.dimen.arg_RES_7f07033f));
       uAppCompatBu.setLayoutParams(layoutParams3);
       relativeLayo.addView(uAppCompatBu);
       EmojiTextView uEmojiTextVi = new EmojiTextView(relativeLayo.getContext());
       layoutParams3 = new RelativeLayout$LayoutParams(-1, -1);
       uEmojiTextVi.setId(R.id.title_tv);
       layoutParams3.addRule(13, -1);
       layoutParams3.leftMargin = c.b(resources, 0x7f070165);
       layoutParams3.rightMargin = c.b(resources, 0x7f070165);
       uEmojiTextVi.setGravity(17);
       uEmojiTextVi.setMaxLines(true);
       TypedValue typedValue4 = new TypedValue();
       p0.getTheme().resolveAttribute(R.attr.arg_RES_7f0400f8, typedValue4, true);
       uEmojiTextVi.setTextColor(typedValue4.data);
       typedValue4 = new TypedValue();
       p0.getTheme().resolveAttribute(R.attr.arg_RES_7f0400f9, typedValue4, true);
       uEmojiTextVi.setTextSize(true, TypedValue.complexToFloat(typedValue4.data));
       uEmojiTextVi.setTypeface(null, true);
       uEmojiTextVi.setInitTextSize(TypedValue.applyDimension(0, (float)c.b(resources, R.dimen.arg_RES_7f070f65), c.c(resources)));
       uEmojiTextVi.setTextSizeAdjustable(true);
       uEmojiTextVi.setLayoutParams(layoutParams3);
       relativeLayo.addView(uEmojiTextVi);
       ConstraintLayout uConstraintL = new ConstraintLayout(relativeLayo.getContext());
       layoutParams3 = new RelativeLayout$LayoutParams(-2, -2);
       uConstraintL.setId(R.id.ktv_new_title_info_layout);
       layoutParams3.addRule(13, -1);
       uConstraintL.setVisibility(8);
       uConstraintL.setLayoutParams(layoutParams3);
       relativeLayo.addView(uConstraintL);
       EmojiTextView uEmojiTextVi1 = new EmojiTextView(uConstraintL.getContext());
       ConstraintLayout$LayoutParams layoutParams4 = new ConstraintLayout$LayoutParams(-2, -1);
       uEmojiTextVi1.setId(R.id.ktv_title_tv);
       uEmojiTextVi1.setMaxLines(true);
       layoutParams4.G = 2;
       layoutParams4.T = true;
       layoutParams4.d = 0;
       layoutParams4.f = 0x7f0a1664;
       layoutParams4.h = 0;
       layoutParams4.k = 0;
       TypedValue typedValue5 = new TypedValue();
       p0.getTheme().resolveAttribute(R.attr.arg_RES_7f0400f8, typedValue5, true);
       uEmojiTextVi1.setTextColor(typedValue5.data);
       typedValue5 = new TypedValue();
       p0.getTheme().resolveAttribute(R.attr.arg_RES_7f0400f9, typedValue5, true);
       uEmojiTextVi1.setTextSize(true, TypedValue.complexToFloat(typedValue5.data));
       uEmojiTextVi1.setTypeface(null, true);
       uEmojiTextVi1.setInitTextSize(TypedValue.applyDimension(0, (float)c.b(resources, R.dimen.arg_RES_7f070f65), c.c(resources)));
       uEmojiTextVi1.setTextSizeAdjustable(true);
       layoutParams4.c();
       uEmojiTextVi1.setLayoutParams(layoutParams4);
       uConstraintL.addView(uEmojiTextVi1);
       AppCompatImageView uAppCompatIm1 = new AppCompatImageView(uConstraintL.getContext());
       ConstraintLayout$LayoutParams layoutParams5 = new ConstraintLayout$LayoutParams(c.b(resources, 0x7f07030d), c.b(resources, 0x7f0702b8));
       uAppCompatIm1.setId(R.id.ktv_score_img);
       uAppCompatIm1.setVisibility(8);
       layoutParams5.h = 0;
       layoutParams5.k = 0;
       layoutParams5.e = 0x7f0a1673;
       layoutParams5.g = 0;
       layoutParams5.c();
       uAppCompatIm1.setLayoutParams(layoutParams5);
       uConstraintL.addView(uAppCompatIm1);
       EmojiTextView uEmojiTextVi2 = new EmojiTextView(relativeLayo.getContext());
       RelativeLayout$LayoutParams layoutParams6 = new RelativeLayout$LayoutParams((int)TypedValue.applyDimension(true, 86.00f, c.c(resources)), (int)TypedValue.applyDimension(true, 32.00f, c.c(resources)));
       uEmojiTextVi2.setId(R.id.recover_camera_btn);
       layoutParams6.addRule(13, -1);
       uEmojiTextVi2.setGravity(17);
       uEmojiTextVi2.setMaxLines(true);
       uEmojiTextVi2.setTextColor(resources.getColor(R.color.arg_RES_7f061ff3));
       uEmojiTextVi2.setBackgroundResource(R.drawable.arg_RES_7f080904);
       uEmojiTextVi2.setVisibility(8);
       uEmojiTextVi2.setTextSize(0, (float)c.b(resources, R.dimen.arg_RES_7f070283));
       uEmojiTextVi2.setLayoutParams(layoutParams6);
       relativeLayo.addView(uEmojiTextVi2);
       return relativeLayo;
    }
}
