package com.kuaishou.ax2c.layouts.X2C_Live_Multi_Pk_Game_Container;
import com.kuaishou.ax2c.IViewCreator;
import java.lang.Object;
import android.content.Context;
import android.view.View;
import android.content.res.Resources;
import androidx.constraintlayout.widget.ConstraintLayout;
import android.view.ViewGroup$MarginLayoutParams;
import android.view.ViewGroup;
import android.view.ViewGroup$LayoutParams;
import androidx.constraintlayout.widget.Guideline;
import androidx.constraintlayout.widget.ConstraintLayout$LayoutParams;
import android.widget.FrameLayout;
import cw9.c;
import com.yxcorp.gifshow.image.KwaiImageView;
import android.widget.ImageView;

public class X2C_Live_Multi_Pk_Game_Container implements IViewCreator	// class@001101
{

    public void X2C_Live_Multi_Pk_Game_Container(){
       super();
    }
    public View createView(Context p0){
       Resources resources = p0.getResources();
       ConstraintLayout uConstraintL = new ConstraintLayout(p0);
       uConstraintL.setClipChildren(false);
       uConstraintL.setLayoutParams(new ViewGroup$MarginLayoutParams(-1, -1));
       Guideline guideline = new Guideline(uConstraintL.getContext());
       ConstraintLayout$LayoutParams layoutParams = new ConstraintLayout$LayoutParams(-2, -2);
       guideline.setId(R.id.live_multi_pk_game_center_horizontal_guide_line);
       layoutParams.S = 1;
       layoutParams.c = 0x3f000000;
       layoutParams.c();
       guideline.setLayoutParams(layoutParams);
       uConstraintL.addView(guideline);
       FrameLayout uFrameLayout = new FrameLayout(uConstraintL.getContext());
       layoutParams = new ConstraintLayout$LayoutParams(c.b(resources, 0x7f0706a3), c.b(resources, 0x7f0706a3));
       uFrameLayout.setId(R.id.live_multi_game_anim_container);
       layoutParams.k = 0;
       layoutParams.d = 0;
       layoutParams.g = 0;
       layoutParams.h = 0;
       layoutParams.c();
       uFrameLayout.setLayoutParams(layoutParams);
       uConstraintL.addView(uFrameLayout);
       ConstraintLayout uConstraintL1 = new ConstraintLayout(uConstraintL.getContext());
       layoutParams = new ConstraintLayout$LayoutParams(-1, c.b(resources, 0x7f0708ef));
       uConstraintL1.setId(R.id.live_multi_pk_mvp_container);
       uConstraintL1.setVisibility(8);
       layoutParams.k = 0;
       layoutParams.c();
       uConstraintL1.setLayoutParams(layoutParams);
       uConstraintL.addView(uConstraintL1);
       uConstraintL1 = new ConstraintLayout(uConstraintL.getContext());
       layoutParams = new ConstraintLayout$LayoutParams(-1, c.b(resources, 0x7f0702fe));
       uConstraintL1.setId(R.id.live_pk_score_limit_bar_container);
       layoutParams.k = 0;
       layoutParams.c();
       uConstraintL1.setLayoutParams(layoutParams);
       uConstraintL.addView(uConstraintL1);
       KwaiImageView kwaiImageVie = new KwaiImageView(uConstraintL.getContext());
       ConstraintLayout$LayoutParams layoutParams1 = new ConstraintLayout$LayoutParams(c.b(resources, 0x7f070858), c.b(resources, 0x7f070858));
       kwaiImageVie.setId(R.id.live_multi_pk_result_left);
       kwaiImageVie.setVisibility(8);
       layoutParams1.j = 0x7f0a21d4;
       layoutParams1.d = 0;
       layoutParams1.c();
       kwaiImageVie.setLayoutParams(layoutParams1);
       uConstraintL.addView(kwaiImageVie);
       kwaiImageVie = new KwaiImageView(uConstraintL.getContext());
       layoutParams1 = new ConstraintLayout$LayoutParams(c.b(resources, 0x7f070858), c.b(resources, 0x7f070858));
       kwaiImageVie.setId(R.id.live_multi_pk_result_right);
       kwaiImageVie.setVisibility(8);
       layoutParams1.j = 0x7f0a21d4;
       layoutParams1.e = 0x7f0a21cf;
       layoutParams1.c();
       kwaiImageVie.setLayoutParams(layoutParams1);
       uConstraintL.addView(kwaiImageVie);
       uConstraintL1 = new ConstraintLayout(uConstraintL.getContext());
       layoutParams1 = new ConstraintLayout$LayoutParams(-2, -2);
       layoutParams1.bottomMargin = c.b(resources, 0x7f07033f);
       layoutParams1.w = c.b(resources, 0x7f070311);
       uConstraintL1.setId(R.id.live_multi_pk_reopen_container);
       layoutParams1.T = true;
       layoutParams1.j = 0x7f0a21d4;
       layoutParams1.s = 0;
       layoutParams1.q = 0;
       layoutParams1.c();
       uConstraintL1.setLayoutParams(layoutParams1);
       uConstraintL.addView(uConstraintL1);
       uConstraintL1 = new ConstraintLayout(uConstraintL.getContext());
       ConstraintLayout$LayoutParams layoutParams2 = new ConstraintLayout$LayoutParams(-2, -2);
       uConstraintL1.setId(R.id.live_multi_pk_cohesion_container);
       layoutParams2.j = 0x7f0a21d4;
       layoutParams2.q = 0;
       layoutParams2.c();
       uConstraintL1.setLayoutParams(layoutParams2);
       uConstraintL.addView(uConstraintL1);
       return uConstraintL;
    }
}
