package com.kuaishou.ax2c.layouts.X2C_Ksa_Album_Select_Container;
import com.kuaishou.ax2c.IViewCreator;
import java.lang.Object;
import android.content.Context;
import android.view.View;
import android.content.res.Resources;
import android.widget.RelativeLayout;
import android.widget.FrameLayout$LayoutParams;
import cw9.c;
import android.view.ViewGroup$LayoutParams;
import android.widget.RelativeLayout$LayoutParams;
import com.kuaishou.ax2c.layouts.X2C_Ksa_Album_Selected_Container_Item_Button;
import android.widget.LinearLayout;
import android.widget.FrameLayout;
import android.widget.LinearLayout$LayoutParams;
import android.widget.Button;
import android.util.AttributeSet;
import android.widget.ImageView;
import android.widget.TextView;
import android.util.DisplayMetrics;
import android.util.TypedValue;
import android.text.TextUtils$TruncateAt;
import java.lang.CharSequence;
import android.graphics.Typeface;
import com.yxcorp.gifshow.album.widget.AlbumSelectRecyclerView;
import android.view.ViewGroup;

public class X2C_Ksa_Album_Select_Container implements IViewCreator	// class@0010b2
{

    public void X2C_Ksa_Album_Select_Container(){
       super();
    }
    public View createView(Context p0){
       Resources resources = p0.getResources();
       RelativeLayout relativeLayo = new RelativeLayout(p0);
       relativeLayo.setId(R.id.picked_layout);
       relativeLayo.setClickable(true);
       relativeLayo.setLayoutParams(new FrameLayout$LayoutParams(-1, c.b(resources, R.dimen.arg_RES_7f0704f2)));
       RelativeLayout relativeLayo1 = new RelativeLayout(relativeLayo.getContext());
       relativeLayo1.setId(R.id.picked_background_layout);
       relativeLayo1.setBackgroundColor(resources.getColor(R.color.arg_RES_7f060b38));
       relativeLayo1.setLayoutParams(new RelativeLayout$LayoutParams(-1, c.b(resources, R.dimen.arg_RES_7f0704f2)));
       relativeLayo.addView(relativeLayo1);
       View view = new X2C_Ksa_Album_Selected_Container_Item_Button().createView(relativeLayo.getContext());
       RelativeLayout$LayoutParams layoutParams = view.getLayoutParams();
       view.setId(R.id.selected_container_item_button);
       layoutParams.addRule(9, -1);
       layoutParams.addRule(12, -1);
       layoutParams.leftMargin = c.b(resources, 0x7f0704ff);
       layoutParams.bottomMargin = c.b(resources, 0x7f0704fe);
       view.setVisibility(8);
       view.setLayoutParams(layoutParams);
       relativeLayo.addView(view);
       relativeLayo1 = new RelativeLayout(relativeLayo.getContext());
       layoutParams = new RelativeLayout$LayoutParams(-1, -2);
       layoutParams.addRule(3, R.id.line_divide);
       layoutParams.topMargin = c.b(resources, 0x7f0704b1);
       relativeLayo1.setBackgroundColor(resources.getColor(R.color.arg_RES_7f060b87));
       relativeLayo1.setPadding(c.b(resources, R.dimen.arg_RES_7f0704b3), 0, 0, 0);
       relativeLayo1.setLayoutParams(layoutParams);
       relativeLayo.addView(relativeLayo1);
       LinearLayout linearLayout = new LinearLayout(relativeLayo1.getContext());
       RelativeLayout$LayoutParams layoutParams1 = new RelativeLayout$LayoutParams(-2, -2);
       linearLayout.setId(R.id.right_container);
       linearLayout.setOrientation(0);
       layoutParams1.addRule(15, -1);
       layoutParams1.addRule(11, -1);
       layoutParams1.addRule(21, -1);
       layoutParams1.rightMargin = c.b(resources, 0x7f0704b3);
       layoutParams1.setMarginEnd(c.b(resources, R.dimen.arg_RES_7f0704b3));
       linearLayout.setLayoutParams(layoutParams1);
       relativeLayo1.addView(linearLayout);
       FrameLayout uFrameLayout = new FrameLayout(linearLayout.getContext());
       LinearLayout$LayoutParams layoutParams2 = new LinearLayout$LayoutParams(-2, -2);
       uFrameLayout.setId(R.id.custom_title_area);
       layoutParams2.gravity = 16;
       uFrameLayout.setLayoutParams(layoutParams2);
       linearLayout.addView(uFrameLayout);
       Button uButton = new Button(linearLayout.getContext(), null, 0);
       layoutParams2 = new LinearLayout$LayoutParams(-2, c.b(resources, 0x7f0704ed));
       uButton.setId(R.id.next_step);
       layoutParams2.gravity = 16;
       uButton.setBackgroundResource(R.drawable.arg_RES_7f080f99);
       uButton.setGravity(17);
       uButton.setMaxLines(true);
       uButton.setText(R.string.arg_RES_7f1018aa);
       uButton.setTextColor(resources.getColor(R.color.arg_RES_7f060b5f));
       uButton.setTextSize(0, (float)c.b(resources, R.dimen.arg_RES_7f0704c7));
       uButton.setPadding(c.b(resources, R.dimen.arg_RES_7f0704c5), 0, c.b(resources, R.dimen.arg_RES_7f0704c6), 0);
       uButton.setLayoutParams(layoutParams2);
       linearLayout.addView(uButton);
       ImageView imageView = new ImageView(relativeLayo1.getContext());
       RelativeLayout$LayoutParams layoutParams3 = new RelativeLayout$LayoutParams(-2, -2);
       imageView.setId(R.id.clock_icon);
       layoutParams3.addRule(9, -1);
       layoutParams3.addRule(15, -1);
       layoutParams3.rightMargin = c.b(resources, 0x7f0704e7);
       imageView.setImageResource(R.drawable.arg_RES_7f080fe0);
       imageView.setVisibility(8);
       imageView.setLayoutParams(layoutParams3);
       relativeLayo1.addView(imageView);
       TextView textView = new TextView(relativeLayo1.getContext());
       layoutParams3 = new RelativeLayout$LayoutParams(-1, -2);
       textView.setId(R.id.selected_des);
       layoutParams3.addRule(15, -1);
       layoutParams3.setMarginEnd(c.b(resources, R.dimen.arg_RES_7f0704c4));
       layoutParams3.rightMargin = (int)TypedValue.applyDimension(true, 8.00f, c.c(resources));
       layoutParams3.addRule(17, R.id.selected_duration);
       layoutParams3.addRule(0, R.id.right_container);
       layoutParams3.addRule(true, R.id.selected_duration);
       layoutParams3.addRule(16, R.id.right_container);
       textView.setEllipsize(TextUtils$TruncateAt.END);
       textView.setIncludeFontPadding(0);
       textView.setMaxLines(true);
       textView.setText(R.string.arg_RES_7f1018ce);
       textView.setTextColor(resources.getColor(R.color.arg_RES_7f060b3b));
       textView.setTextSize(0, (float)c.b(resources, R.dimen.arg_RES_7f07050f));
       textView.setLayoutParams(layoutParams3);
       relativeLayo1.addView(textView);
       textView = new TextView(relativeLayo1.getContext());
       layoutParams3 = new RelativeLayout$LayoutParams(-2, -2);
       textView.setId(R.id.selected_duration);
       layoutParams3.addRule(15, -1);
       layoutParams3.rightMargin = c.b(resources, 0x7f0704c4);
       layoutParams3.addRule(true, R.id.clock_icon);
       textView.setIncludeFontPadding(0);
       textView.setText("00:00");
       textView.setTextColor(resources.getColor(R.color.arg_RES_7f060b3a));
       textView.setTextSize(0, (float)c.b(resources, R.dimen.arg_RES_7f070511));
       textView.setVisibility(8);
       textView.setPadding(0, (int)TypedValue.applyDimension(true, 0.10f, c.c(resources)), 0, 0);
       textView.setLayoutParams(layoutParams3);
       relativeLayo1.addView(textView);
       textView = new TextView(relativeLayo1.getContext());
       layoutParams3 = new RelativeLayout$LayoutParams(-2, -2);
       layoutParams3.addRule(9, -1);
       layoutParams3.addRule(15, -1);
       layoutParams3.leftMargin = c.b(resources, 0x7f0704b1);
       textView.setText("00:00");
       textView.setTextColor(resources.getColor(R.color.arg_RES_7f060b3b));
       textView.setTextSize(0, (float)c.b(resources, R.dimen.arg_RES_7f07050f));
       textView.setVisibility(8);
       textView.setLayoutParams(layoutParams3);
       relativeLayo1.addView(textView);
       relativeLayo1 = new RelativeLayout(relativeLayo.getContext());
       layoutParams = new RelativeLayout$LayoutParams(-2, c.b(resources, 0x7f0704ed));
       relativeLayo1.setId(R.id.choice_circle_layout);
       layoutParams.addRule(3, R.id.line_divide);
       layoutParams.topMargin = c.b(resources, 0x7f0704b1);
       relativeLayo1.setVisibility(8);
       relativeLayo1.setPadding(c.b(resources, R.dimen.arg_RES_7f0704b3), 0, 0, 0);
       relativeLayo1.setLayoutParams(layoutParams);
       relativeLayo.addView(relativeLayo1);
       View view1 = new View(relativeLayo1.getContext());
       layoutParams3 = new RelativeLayout$LayoutParams((int)TypedValue.applyDimension(true, 21.00f, c.c(resources)), (int)TypedValue.applyDimension(true, 21.00f, c.c(resources)));
       view1.setBackgroundResource(R.drawable.arg_RES_7f080fdc);
       layoutParams3.addRule(9, -1);
       layoutParams3.addRule(15, -1);
       view1.setLayoutParams(layoutParams3);
       relativeLayo1.addView(view1);
       textView = new TextView(relativeLayo1.getContext());
       layoutParams3 = new RelativeLayout$LayoutParams((int)TypedValue.applyDimension(true, 21.00f, c.c(resources)), (int)TypedValue.applyDimension(true, 21.00f, c.c(resources)));
       textView.setId(R.id.choice_circle);
       textView.setBackgroundResource(R.drawable.arg_RES_7f080fdd);
       layoutParams3.addRule(9, -1);
       layoutParams3.addRule(15, -1);
       textView.setGravity(17);
       textView.setIncludeFontPadding(0);
       textView.setTextColor(resources.getColor(R.color.arg_RES_7f060b37));
       textView.setTextSize(0, (float)c.b(resources, R.dimen.arg_RES_7f070510));
       textView.setVisibility(4);
       textView.setLayoutParams(layoutParams3);
       relativeLayo1.addView(textView);
       textView = new TextView(relativeLayo1.getContext());
       layoutParams3 = new RelativeLayout$LayoutParams(-2, -2);
       textView.setId(R.id.choice_text);
       textView.setGravity(16);
       layoutParams3.addRule(15, -1);
       layoutParams3.addRule(true, R.id.choice_circle);
       layoutParams3.leftMargin = c.b(resources, 0x7f0704c4);
       textView.setText(R.string.arg_RES_7f1018da);
       textView.setTextColor(resources.getColor(R.color.arg_RES_7f060b85));
       textView.setTextSize(0, (float)c.b(resources, R.dimen.arg_RES_7f070514));
       textView.setLayoutParams(layoutParams3);
       relativeLayo1.addView(textView);
       relativeLayo1 = new RelativeLayout(relativeLayo.getContext());
       layoutParams = new RelativeLayout$LayoutParams(-2, -2);
       relativeLayo1.setId(R.id.single_multi_select_layout);
       layoutParams.addRule(3, R.id.line_divide);
       layoutParams.leftMargin = c.b(resources, 0x7f0704b3);
       layoutParams.topMargin = c.b(resources, 0x7f0704b5);
       relativeLayo1.setVisibility(8);
       relativeLayo1.setLayoutParams(layoutParams);
       relativeLayo.addView(relativeLayo1);
       view1 = new View(relativeLayo1.getContext());
       layoutParams3 = new RelativeLayout$LayoutParams((int)TypedValue.applyDimension(true, 24.00f, c.c(resources)), (int)TypedValue.applyDimension(true, 24.00f, c.c(resources)));
       view1.setId(R.id.single_multi_select_icon);
       layoutParams3.addRule(9, -1);
       layoutParams3.addRule(15, -1);
       view1.setBackgroundResource(R.drawable.arg_RES_7f080fdf);
       view1.setLayoutParams(layoutParams3);
       relativeLayo1.addView(view1);
       textView = new TextView(relativeLayo1.getContext());
       layoutParams3 = new RelativeLayout$LayoutParams(-2, -2);
       textView.setId(R.id.single_multi_select_text);
       layoutParams3.addRule(15, -1);
       layoutParams3.leftMargin = c.b(resources, 0x7f0704c2);
       layoutParams3.addRule(true, R.id.single_multi_select_icon);
       textView.setGravity(16);
       textView.setText(R.string.arg_RES_7f1018d3);
       textView.setTextColor(resources.getColor(R.color.arg_RES_7f060b7d));
       textView.setTypeface(null, true);
       textView.setTextSize(0, (float)c.b(resources, R.dimen.arg_RES_7f070514));
       textView.setLayoutParams(layoutParams3);
       relativeLayo1.addView(textView);
       view = new View(relativeLayo.getContext());
       layoutParams = new RelativeLayout$LayoutParams(-1, c.b(resources, 0x7f0704ca));
       view.setId(R.id.line_divide);
       layoutParams.addRule(10, -1);
       view.setBackgroundColor(resources.getColor(R.color.arg_RES_7f060b39));
       view.setLayoutParams(layoutParams);
       relativeLayo.addView(view);
       AlbumSelectRecyclerView uAlbumSelect = new AlbumSelectRecyclerView(relativeLayo.getContext());
       layoutParams = new RelativeLayout$LayoutParams(-1, -1);
       uAlbumSelect.setId(R.id.picked_recycler_view);
       layoutParams.addRule(12, -1);
       uAlbumSelect.setBackgroundColor(resources.getColor(R.color.arg_RES_7f060b87));
       uAlbumSelect.setClickable(0);
       uAlbumSelect.setVerticalScrollBarEnabled(0);
       uAlbumSelect.setHorizontalScrollBarEnabled(0);
       uAlbumSelect.setPadding(c.b(resources, R.dimen.arg_RES_7f0704c3), 0, c.b(resources, R.dimen.arg_RES_7f0704c3), 0);
       uAlbumSelect.setLayoutParams(layoutParams);
       relativeLayo.addView(uAlbumSelect);
       view = new View(relativeLayo.getContext());
       layoutParams = new RelativeLayout$LayoutParams(c.b(resources, 0x7f0704bc), c.b(resources, 0x7f0704fd));
       view.setId(R.id.button_click_view);
       layoutParams.addRule(9, -1);
       layoutParams.addRule(12, -1);
       layoutParams.leftMargin = (int)TypedValue.applyDimension(true, 80.00f, c.c(resources));
       layoutParams.bottomMargin = c.b(resources, 0x7f0704fe);
       view.setVisibility(8);
       view.setLayoutParams(layoutParams);
       relativeLayo.addView(view);
       return relativeLayo;
    }
}
