package com.kuaishou.ax2c.layouts.X2C_Live_Gift_Slot_View_Item;
import com.kuaishou.ax2c.IViewCreator;
import java.lang.Object;
import android.content.Context;
import android.view.View;
import android.content.res.Resources;
import com.yxcorp.widget.selector.view.SelectShapeRelativeLayout;
import android.view.ViewGroup$MarginLayoutParams;
import cw9.c;
import android.widget.RelativeLayout;
import com.kuaishou.ax2c.XmlAttrHostImpl;
import java.lang.Integer;
import com.kuaishou.ax2c.IAttrHost;
import ald.b;
import android.view.ViewGroup$LayoutParams;
import com.kuaishou.live.core.basic.widget.LiveGradientBackgroundView;
import android.widget.RelativeLayout$LayoutParams;
import com.yxcorp.gifshow.image.KwaiImageView;
import android.widget.ImageView;
import ac.b;
import com.facebook.drawee.view.DraweeView;
import yb.a;
import xb.t$b;
import com.kuaishou.live.core.basic.widget.LiveGradientBorderView;
import android.util.DisplayMetrics;
import android.util.TypedValue;
import android.graphics.drawable.Drawable;
import androidx.core.content.ContextCompat;
import com.facebook.drawee.generic.RoundingParams;
import android.widget.LinearLayout;
import androidx.appcompat.widget.AppCompatTextView;
import android.widget.LinearLayout$LayoutParams;
import android.widget.TextView;
import android.text.TextUtils$TruncateAt;
import com.yxcorp.gifshow.image.KwaiAnimImageView;
import android.widget.ImageView$ScaleType;
import com.kuaishou.live.core.basic.widget.LiveGradientTextView;
import android.graphics.Typeface;
import com.kuaishou.live.common.core.component.gift.domain.slot.springnaming.LiveGiftSlotSpringNamingView;

public class X2C_Live_Gift_Slot_View_Item implements IViewCreator	// class@0010e4
{

    public void X2C_Live_Gift_Slot_View_Item(){
       super();
    }
    public View createView(Context p0){
       Context uContext = p0;
       Resources resources = p0.getResources();
       SelectShapeRelativeLayout selectShapeR = new SelectShapeRelativeLayout(uContext);
       selectShapeR.setClipChildren(false);
       XmlAttrHostImpl xmlAttrHostI = new XmlAttrHostImpl();
       xmlAttrHostI.addAttr(2, Integer.valueOf(c.b(resources, R.dimen.arg_RES_7f07042c)));
       IAttrHost[] iAttrHostArr = new IAttrHost[]{new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),xmlAttrHostI};
       selectShapeR.setAttrs(iAttrHostArr);
       selectShapeR.setLayoutParams(new ViewGroup$MarginLayoutParams(-2, c.b(resources, R.dimen.arg_RES_7f0702fe)));
       LiveGradientBackgroundView liveGradient = new LiveGradientBackgroundView(selectShapeR.getContext());
       RelativeLayout$LayoutParams layoutParams = new RelativeLayout$LayoutParams(-1, -1);
       liveGradient.setId(R.id.gift_slot_bg_view);
       layoutParams.addRule(8, R.id.gift_slot_content_container);
       layoutParams.addRule(5, R.id.gift_slot_content_container);
       layoutParams.addRule(7, R.id.gift_slot_content_container);
       layoutParams.addRule(6, R.id.gift_slot_content_container);
       liveGradient.setLayoutParams(layoutParams);
       selectShapeR.addView(liveGradient);
       RelativeLayout relativeLayo = new RelativeLayout(selectShapeR.getContext());
       layoutParams = new RelativeLayout$LayoutParams(-1, c.b(resources, 0x7f0702fe));
       relativeLayo.setId(R.id.live_gift_slot_bg_container);
       layoutParams.addRule(8, R.id.gift_slot_content_container);
       layoutParams.addRule(5, R.id.gift_slot_content_container);
       layoutParams.addRule(7, R.id.gift_slot_content_container);
       layoutParams.addRule(6, R.id.gift_slot_content_container);
       relativeLayo.setLayoutParams(layoutParams);
       selectShapeR.addView(relativeLayo);
       KwaiImageView kwaiImageVie = new KwaiImageView(relativeLayo.getContext());
       kwaiImageVie.setId(R.id.gift_anim_item_halo_view);
       kwaiImageVie.getHierarchy().u(t$b.a);
       kwaiImageVie.setVisibility(8);
       kwaiImageVie.setLayoutParams(new RelativeLayout$LayoutParams(-1, c.b(resources, R.dimen.arg_RES_7f0702fe)));
       relativeLayo.addView(kwaiImageVie);
       LiveGradientBorderView liveGradient1 = new LiveGradientBorderView(selectShapeR.getContext());
       RelativeLayout$LayoutParams layoutParams1 = new RelativeLayout$LayoutParams(-1, -1);
       liveGradient1.setId(R.id.gift_slot_border_view);
       layoutParams1.addRule(8, R.id.gift_slot_content_container);
       layoutParams1.addRule(5, R.id.gift_slot_content_container);
       layoutParams1.addRule(7, R.id.gift_slot_content_container);
       layoutParams1.addRule(6, R.id.gift_slot_content_container);
       liveGradient1.setLayoutParams(layoutParams1);
       selectShapeR.addView(liveGradient1);
       relativeLayo = new RelativeLayout(selectShapeR.getContext());
       relativeLayo.setId(R.id.gift_slot_content_container);
       relativeLayo.setClipChildren(false);
       relativeLayo.setLayoutParams(new RelativeLayout$LayoutParams(-2, c.b(resources, R.dimen.arg_RES_7f0702fe)));
       selectShapeR.addView(relativeLayo);
       KwaiImageView kwaiImageVie1 = new KwaiImageView(relativeLayo.getContext());
       RelativeLayout$LayoutParams layoutParams2 = new RelativeLayout$LayoutParams((int)TypedValue.applyDimension(1, 28.00f, c.c(resources)), (int)TypedValue.applyDimension(1, 28.00f, c.c(resources)));
       kwaiImageVie1.setId(R.id.live_gift_slot_avatar);
       layoutParams2.addRule(15, -1);
       layoutParams2.leftMargin = (int)TypedValue.applyDimension(1, 4.00f, c.c(resources));
       kwaiImageVie1.getHierarchy().G(ContextCompat.getDrawable(uContext, R.drawable.detail_avatar_secret), t$b.i);
       kwaiImageVie1.getHierarchy().L(RoundingParams.a());
       kwaiImageVie1.setLayoutParams(layoutParams2);
       relativeLayo.addView(kwaiImageVie1);
       KwaiImageView kwaiImageVie2 = new KwaiImageView(relativeLayo.getContext());
       layoutParams1 = new RelativeLayout$LayoutParams(c.b(resources, 0x7f0702ef), c.b(resources, 0x7f0702ef));
       kwaiImageVie2.setId(R.id.live_gift_slot_avatar_ring_view);
       layoutParams1.addRule(5, R.id.live_gift_slot_avatar);
       layoutParams1.addRule(6, R.id.live_gift_slot_avatar);
       layoutParams1.leftMargin = (int)TypedValue.applyDimension(1, -2.00f, c.c(resources));
       layoutParams1.topMargin = (int)TypedValue.applyDimension(1, -2.00f, c.c(resources));
       kwaiImageVie2.setVisibility(8);
       kwaiImageVie2.getHierarchy().u(t$b.e);
       kwaiImageVie2.setLayoutParams(layoutParams1);
       relativeLayo.addView(kwaiImageVie2);
       LinearLayout linearLayout = new LinearLayout(relativeLayo.getContext());
       layoutParams1 = new RelativeLayout$LayoutParams((int)TypedValue.applyDimension(1, 58.00f, c.c(resources)), -2);
       linearLayout.setId(R.id.live_gift_slot_desc_container);
       layoutParams1.addRule(15, -1);
       layoutParams1.leftMargin = (int)TypedValue.applyDimension(1, 4.00f, c.c(resources));
       layoutParams1.addRule(1, R.id.live_gift_slot_avatar);
       linearLayout.setOrientation(1);
       linearLayout.setLayoutParams(layoutParams1);
       relativeLayo.addView(linearLayout);
       AppCompatTextView uAppCompatTe = new AppCompatTextView(linearLayout.getContext());
       uAppCompatTe.setId(R.id.live_gift_slot_username);
       uAppCompatTe.setEllipsize(TextUtils$TruncateAt.END);
       uAppCompatTe.setMaxLines(1);
       uAppCompatTe.setTextColor(resources.getColor(R.color.arg_RES_7f061ff3));
       uAppCompatTe.setTextSize(0, (float)c.b(resources, R.dimen.arg_RES_7f070271));
       uAppCompatTe.setLayoutParams(new LinearLayout$LayoutParams(-2, -2));
       linearLayout.addView(uAppCompatTe);
       uAppCompatTe = new AppCompatTextView(linearLayout.getContext());
       uAppCompatTe.setId(R.id.live_gift_slot_gift_des);
       uAppCompatTe.setEllipsize(TextUtils$TruncateAt.END);
       uAppCompatTe.setMaxLines(1);
       uAppCompatTe.setTextColor(resources.getColor(R.color.arg_RES_7f061ff3));
       uAppCompatTe.setTextSize(0, (float)c.b(resources, R.dimen.arg_RES_7f07025d));
       uAppCompatTe.setLayoutParams(new LinearLayout$LayoutParams(-2, -2));
       linearLayout.addView(uAppCompatTe);
       KwaiAnimImageView kwaiAnimImag = new KwaiAnimImageView(relativeLayo.getContext());
       layoutParams1 = new RelativeLayout$LayoutParams(c.b(resources, 0x7f0702fe), c.b(resources, 0x7f0702fe));
       kwaiAnimImag.setId(R.id.live_gift_slot_gift_icon);
       layoutParams1.leftMargin = c.b(resources, 0x7f07031b);
       layoutParams1.addRule(1, R.id.live_gift_slot_desc_container);
       kwaiAnimImag.setScaleType(ImageView$ScaleType.CENTER_INSIDE);
       kwaiAnimImag.getHierarchy().x(0);
       kwaiAnimImag.setLayoutParams(layoutParams1);
       relativeLayo.addView(kwaiAnimImag);
       RelativeLayout relativeLayo1 = new RelativeLayout(relativeLayo.getContext());
       layoutParams1 = new RelativeLayout$LayoutParams(-2, c.b(resources, 0x7f0702fe));
       relativeLayo1.setId(R.id.live_gift_slot_combo_and_batch_size_layout);
       layoutParams1.addRule(1, R.id.live_gift_slot_gift_icon);
       relativeLayo1.setClipChildren(false);
       relativeLayo1.setLayoutParams(layoutParams1);
       relativeLayo.addView(relativeLayo1);
       LiveGradientTextView liveGradient2 = new LiveGradientTextView(relativeLayo1.getContext());
       layoutParams2 = new RelativeLayout$LayoutParams(-2, -2);
       liveGradient2.setId(R.id.live_gift_slot_gift_batch_count);
       layoutParams2.leftMargin = (int)TypedValue.applyDimension(1, 4.00f, c.c(resources));
       layoutParams2.topMargin = c.b(resources, 0x7f0702ac);
       liveGradient2.setTextSize(0, (float)c.b(resources, R.dimen.arg_RES_7f07025d));
       liveGradient2.setTypeface(Typeface.SANS_SERIF, 3);
       liveGradient2.setGradientEndColorList(resources.getColor(R.color.arg_RES_7f061e2b));
       liveGradient2.setGradientStartColorList(resources.getColor(R.color.arg_RES_7f060357));
       liveGradient2.setLayoutParams(layoutParams2);
       relativeLayo1.addView(liveGradient2);
       uAppCompatTe = new AppCompatTextView(relativeLayo1.getContext());
       layoutParams2 = new RelativeLayout$LayoutParams(-2, -2);
       uAppCompatTe.setId(R.id.live_gift_slot_combo_count);
       layoutParams2.addRule(12, -1);
       layoutParams2.leftMargin = (int)TypedValue.applyDimension(1, 4.00f, c.c(resources));
       uAppCompatTe.setTextColor(resources.getColor(R.color.arg_RES_7f061f86));
       uAppCompatTe.setTextSize(0, (float)c.b(resources, R.dimen.arg_RES_7f0702b8));
       uAppCompatTe.setTypeface(Typeface.SANS_SERIF, 3);
       uAppCompatTe.setLayoutParams(layoutParams2);
       relativeLayo1.addView(uAppCompatTe);
       View view = new View(relativeLayo.getContext());
       RelativeLayout$LayoutParams layoutParams3 = new RelativeLayout$LayoutParams(c.b(resources, 0x7f07025d), c.b(resources, 0x7f0702fe));
       layoutParams3.addRule(1, R.id.live_gift_slot_combo_and_batch_size_layout);
       view.setLayoutParams(layoutParams3);
       relativeLayo.addView(view);
       LiveGiftSlotSpringNamingView liveGiftSlot = new LiveGiftSlotSpringNamingView(selectShapeR.getContext());
       RelativeLayout$LayoutParams layoutParams4 = new RelativeLayout$LayoutParams(c.b(resources, 0x7f070273), c.b(resources, 0x7f0702cc));
       liveGiftSlot.setId(R.id.live_live_gift_slot_spring_naming_layout);
       layoutParams4.leftMargin = (int)TypedValue.applyDimension(1, -20.00f, c.c(resources));
       layoutParams4.topMargin = c.b(resources, 0x7f070334);
       layoutParams4.addRule(1, R.id.gift_slot_content_container);
       liveGiftSlot.setLayoutParams(layoutParams4);
       selectShapeR.addView(liveGiftSlot);
       return selectShapeR;
    }
}
