package com.kuaishou.ax2c.layouts.X2C_Live_Gift_Side_Bar_Layout;
import com.kuaishou.ax2c.IViewCreator;
import java.lang.Object;
import android.content.Context;
import android.view.View;
import android.content.res.Resources;
import com.kuaishou.live.common.core.basic.widget.LivePressAlphaRelativeLayout;
import android.view.ViewGroup$MarginLayoutParams;
import cw9.c;
import android.widget.RelativeLayout;
import android.view.ViewGroup$LayoutParams;
import android.widget.FrameLayout;
import android.widget.RelativeLayout$LayoutParams;
import com.kuaishou.live.widget.LiveLottieAnimationView;
import android.widget.FrameLayout$LayoutParams;
import android.widget.ImageView;
import com.airbnb.lottie.LottieAnimationView;
import com.kuaishou.live.common.core.component.gift.update.LiveRoundViewFlipper;
import android.widget.ViewFlipper;
import com.kuaishou.live.core.basic.widget.LiveCustomViewFlipper;
import com.yxcorp.gifshow.image.KwaiImageView;
import ac.b;
import com.facebook.drawee.view.DraweeView;
import yb.a;
import android.widget.ImageView$ScaleType;
import androidx.appcompat.widget.AppCompatImageView;
import androidx.appcompat.widget.AppCompatTextView;
import android.util.DisplayMetrics;
import android.util.TypedValue;
import android.widget.TextView;
import android.graphics.Typeface;

public class X2C_Live_Gift_Side_Bar_Layout implements IViewCreator	// class@0010e2
{

    public void X2C_Live_Gift_Side_Bar_Layout(){
       super();
    }
    public View createView(Context p0){
       Context uContext = p0;
       Resources resources = p0.getResources();
       LivePressAlphaRelativeLayout livePressAlp = new LivePressAlphaRelativeLayout(uContext);
       livePressAlp.setGravity(17);
       livePressAlp.setMinimumHeight(c.b(resources, R.dimen.arg_RES_7f070335));
       livePressAlp.setMinimumWidth(c.b(resources, R.dimen.arg_RES_7f07032a));
       livePressAlp.setLayoutParams(new ViewGroup$MarginLayoutParams(c.b(resources, R.dimen.arg_RES_7f07032a), c.b(resources, R.dimen.arg_RES_7f070335)));
       FrameLayout uFrameLayout = new FrameLayout(livePressAlp.getContext());
       RelativeLayout$LayoutParams layoutParams = new RelativeLayout$LayoutParams(c.b(resources, 0x7f070325), c.b(resources, 0x7f070325));
       uFrameLayout.setId(R.id.live_sidebar_item_icon_layout);
       layoutParams.addRule(14, -1);
       uFrameLayout.setLayoutParams(layoutParams);
       livePressAlp.addView(uFrameLayout);
       LiveLottieAnimationView liveLottieAn = new LiveLottieAnimationView(uFrameLayout.getContext());
       liveLottieAn.setId(R.id.live_gift_enhance_animation);
       liveLottieAn.setVisibility(8);
       liveLottieAn.setAutoPlay(false);
       liveLottieAn.setRepeatCount(2);
       liveLottieAn.setLayoutParams(new FrameLayout$LayoutParams(-1, -1));
       uFrameLayout.addView(liveLottieAn);
       LiveRoundViewFlipper liveRoundVie = new LiveRoundViewFlipper(uFrameLayout.getContext());
       FrameLayout$LayoutParams layoutParams1 = new FrameLayout$LayoutParams(c.b(resources, 0x7f0702fe), c.b(resources, 0x7f0702fe));
       liveRoundVie.setId(R.id.live_gift_update_flipper);
       layoutParams1.gravity = 17;
       liveRoundVie.setBackgroundResource(R.drawable.arg_RES_7f08131f);
       liveRoundVie.setInAnimation(uContext, R.anim.arg_RES_7f01007c);
       liveRoundVie.setOutAnimation(uContext, R.anim.arg_RES_7f01007d);
       liveRoundVie.setVisibility(8);
       liveRoundVie.setLayoutParams(layoutParams1);
       uFrameLayout.addView(liveRoundVie);
       KwaiImageView kwaiImageVie = new KwaiImageView(uFrameLayout.getContext());
       kwaiImageVie.setId(R.id.live_gift_sidebar_icon);
       kwaiImageVie.getHierarchy().x(false);
       kwaiImageVie.setVisibility(false);
       kwaiImageVie.setLayoutParams(new FrameLayout$LayoutParams(-1, -1));
       uFrameLayout.addView(kwaiImageVie);
       kwaiImageVie = new KwaiImageView(uFrameLayout.getContext());
       FrameLayout$LayoutParams layoutParams2 = new FrameLayout$LayoutParams(c.b(resources, 0x7f070325), c.b(resources, 0x7f070325));
       kwaiImageVie.setId(R.id.live_gift_sidebar_default_icon);
       layoutParams2.gravity = 81;
       kwaiImageVie.setBackgroundResource(R.drawable.arg_RES_7f081318);
       kwaiImageVie.setScaleType(ImageView$ScaleType.FIT_XY);
       kwaiImageVie.setVisibility(8);
       kwaiImageVie.getHierarchy().x(false);
       kwaiImageVie.setLayoutParams(layoutParams2);
       uFrameLayout.addView(kwaiImageVie);
       AppCompatImageView uAppCompatIm = new AppCompatImageView(uFrameLayout.getContext());
       layoutParams2 = new FrameLayout$LayoutParams(c.b(resources, 0x7f070334), c.b(resources, 0x7f070334));
       uAppCompatIm.setId(R.id.live_gift_dot_notify);
       layoutParams2.gravity = 53;
       layoutParams2.topMargin = c.b(resources, 0x7f07030a);
       layoutParams2.rightMargin = c.b(resources, 0x7f07030a);
       uAppCompatIm.setImageResource(R.drawable.arg_RES_7f080e8a);
       uAppCompatIm.setVisibility(8);
       uAppCompatIm.setLayoutParams(layoutParams2);
       uFrameLayout.addView(uAppCompatIm);
       kwaiImageVie = new KwaiImageView(uFrameLayout.getContext());
       layoutParams2 = new FrameLayout$LayoutParams(c.b(resources, 0x7f0702c5), c.b(resources, 0x7f070271));
       kwaiImageVie.setId(R.id.live_gift_new_notify);
       layoutParams2.topMargin = c.b(resources, 0x7f070334);
       layoutParams2.rightMargin = c.b(resources, 0x7f07034b);
       layoutParams2.gravity = 53;
       kwaiImageVie.setScaleType(ImageView$ScaleType.CENTER_CROP);
       kwaiImageVie.setVisibility(8);
       kwaiImageVie.setLayoutParams(layoutParams2);
       uFrameLayout.addView(kwaiImageVie);
       AppCompatTextView uAppCompatTe = new AppCompatTextView(livePressAlp.getContext());
       RelativeLayout$LayoutParams layoutParams3 = new RelativeLayout$LayoutParams(-2, (int)TypedValue.applyDimension(1, 16.00f, c.c(resources)));
       uAppCompatTe.setId(R.id.live_sidebar_item_text);
       layoutParams3.addRule(3, R.id.live_sidebar_item_icon_layout);
       layoutParams3.addRule(14, -1);
       layoutParams3.topMargin = (int)TypedValue.applyDimension(1, -8.00f, c.c(resources));
       uAppCompatTe.setGravity(17);
       uAppCompatTe.setShadowLayer(uAppCompatTe.getShadowRadius(), uAppCompatTe.getShadowDx(), uAppCompatTe.getShadowDy(), resources.getColor(R.color.arg_RES_7f0601e4));
       uAppCompatTe.setShadowLayer(uAppCompatTe.getShadowRadius(), 0x3f800000, uAppCompatTe.getShadowDy(), uAppCompatTe.getShadowColor());
       uAppCompatTe.setShadowLayer(uAppCompatTe.getShadowRadius(), uAppCompatTe.getShadowDx(), 0x3f800000, uAppCompatTe.getShadowColor());
       uAppCompatTe.setShadowLayer(0x3f800000, uAppCompatTe.getShadowDx(), uAppCompatTe.getShadowDy(), uAppCompatTe.getShadowColor());
       uAppCompatTe.setTextColor(resources.getColor(R.color.arg_RES_7f0620c7));
       uAppCompatTe.setTextSize(false, (float)c.b(resources, R.dimen.arg_RES_7f070271));
       uAppCompatTe.setTypeface(null, 1);
       uAppCompatTe.setLayoutParams(layoutParams3);
       livePressAlp.addView(uAppCompatTe);
       return livePressAlp;
    }
}
