package com.kuaishou.ax2c.layouts.X2C_Live_Play_Clearable_Layer;
import com.kuaishou.ax2c.IViewCreator;
import java.lang.Object;
import android.content.Context;
import android.view.View;
import android.content.res.Resources;
import android.widget.RelativeLayout;
import android.widget.RelativeLayout$LayoutParams;
import android.view.ViewGroup$LayoutParams;
import com.kuaishou.ax2c.layouts.X2C_Live_Audience_Player_Float_Element_Container;
import android.view.ViewStub;
import android.util.DisplayMetrics;
import cw9.c;
import android.util.TypedValue;
import com.yxcorp.widget.selector.view.SelectShapeView;
import android.widget.ImageView;
import com.kuaishou.ax2c.XmlAttrHostImpl;
import java.lang.Integer;
import com.kuaishou.ax2c.IAttrHost;
import ald.b;
import com.kuaishou.ax2c.layouts.X2C_Live_Audience_Left_Top_Pendant_Layout;
import com.kuaishou.ax2c.layouts.X2C_Live_Audience_Common_Info_View_Layout;
import com.kuaishou.live.common.core.component.notification.LiveOperationNotificationView;
import android.widget.FrameLayout;
import com.kuaishou.live.common.core.component.notification.LiveCustomNoticeView;
import com.kuaishou.live.common.core.component.gift.DrawingGiftDisplayView;
import android.widget.ListView;
import android.graphics.drawable.Drawable;
import androidx.core.content.ContextCompat;
import com.yxcorp.gifshow.image.KwaiImageView;
import com.kuaishou.ax2c.layouts.X2C_Live_Gzone_Scene_Container;
import android.widget.LinearLayout;
import android.widget.LinearLayout$LayoutParams;
import com.kuaishou.live.common.core.component.chat.widget.LiveChatApplyButton;
import android.util.AttributeSet;
import androidx.appcompat.widget.AppCompatTextView;
import android.graphics.Typeface;
import android.text.TextUtils$TruncateAt;
import android.widget.TextView;
import android.widget.FrameLayout$LayoutParams;
import com.kuaishou.ax2c.layouts.X2C_Live_Play_Top_Bar_Popup_Head;
import com.kuaishou.ax2c.layouts.X2C_Live_Audience_Fullscreen_Left_Center_Pendant_Layout;
import com.kuaishou.ax2c.layouts.X2C_Live_Gzone_Right_Bottom_Pendant_Container;
import com.kuaishou.live.core.show.enterroom.mount.LiveEnterRoomMountView;
import com.kuaishou.live.common.core.component.gift.domain.combo.animation.LiveGiftBoxGiftParticleAnimationView;
import com.kuaishou.ax2c.layouts.X2C_Live_Gift_Box_Combo_Text_Animation_Layout;

public class X2C_Live_Play_Clearable_Layer implements IViewCreator	// class@001109
{

    public void X2C_Live_Play_Clearable_Layer(){
       super();
    }
    public View createView(Context p0){
       Context uContext = p0;
       Resources resources = p0.getResources();
       RelativeLayout relativeLayo = new RelativeLayout(uContext);
       relativeLayo.setClipChildren(false);
       relativeLayo.setClipToPadding(false);
       relativeLayo.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       View view = new X2C_Live_Audience_Player_Float_Element_Container().createView(relativeLayo.getContext());
       view.setLayoutParams(view.getLayoutParams());
       relativeLayo.addView(view);
       ViewStub viewStub = new ViewStub(relativeLayo.getContext());
       viewStub.setInflatedId(-1);
       viewStub.setId(R.id.live_audience_sticker_view_container_stub);
       viewStub.setInflatedId(R.id.live_audience_sticker_layout);
       viewStub.setLayoutResource(R.layout.live_audience_sticker_container);
       viewStub.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       relativeLayo.addView(viewStub);
       viewStub = new ViewStub(relativeLayo.getContext());
       viewStub.setInflatedId(-1);
       viewStub.setId(R.id.live_gzone_color_barrage_tip_stub);
       viewStub.setLayoutResource(R.layout.arg_RES_7f0d0ba2);
       viewStub.setLayoutParams(new RelativeLayout$LayoutParams(-2, (int)TypedValue.applyDimension(1, 32.00f, c.c(resources))));
       relativeLayo.addView(viewStub);
       viewStub = new ViewStub(relativeLayo.getContext());
       viewStub.setInflatedId(-1);
       RelativeLayout$LayoutParams layoutParams = new RelativeLayout$LayoutParams(-2, (int)TypedValue.applyDimension(1, 35.00f, c.c(resources)));
       viewStub.setId(R.id.live_gzone_follow_fullscreen_tip_stub);
       layoutParams.addRule(14, -1);
       layoutParams.topMargin = (int)TypedValue.applyDimension(1, 60.00f, c.c(resources));
       viewStub.setLayoutParams(layoutParams);
       relativeLayo.addView(viewStub);
       viewStub = new ViewStub(relativeLayo.getContext());
       viewStub.setInflatedId(-1);
       viewStub.setId(R.id.live_play_view_quality_stub);
       viewStub.setLayoutResource(R.layout.arg_RES_7f0d0d27);
       viewStub.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       relativeLayo.addView(viewStub);
       viewStub = new ViewStub(relativeLayo.getContext());
       viewStub.setInflatedId(-1);
       viewStub.setId(R.id.live_fullscreen_float_element_background_viewstub);
       viewStub.setLayoutResource(R.layout.arg_RES_7f0d0b15);
       viewStub.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       relativeLayo.addView(viewStub);
       SelectShapeView selectShapeV = new SelectShapeView(relativeLayo.getContext());
       layoutParams = new RelativeLayout$LayoutParams(-1, c.b(resources, 0x7f0702c9));
       selectShapeV.setId(R.id.live_audience_bottom_mask_view);
       layoutParams.addRule(12, -1);
       selectShapeV.setVisibility(8);
       XmlAttrHostImpl xmlAttrHostI = new XmlAttrHostImpl();
       xmlAttrHostI.addAttr(12, Integer.valueOf(resources.getColor(R.color.arg_RES_7f06020e)));
       xmlAttrHostI.addAttr(8, Integer.valueOf(90));
       xmlAttrHostI.addAttr(14, Integer.valueOf(resources.getColor(R.color.arg_RES_7f060508)));
       IAttrHost[] iAttrHostArr = new IAttrHost[]{xmlAttrHostI,new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl()};
       selectShapeV.setAttrs(iAttrHostArr);
       selectShapeV.setLayoutParams(layoutParams);
       relativeLayo.addView(selectShapeV);
       view = new X2C_Live_Audience_Left_Top_Pendant_Layout().createView(relativeLayo.getContext());
       layoutParams = view.getLayoutParams();
       layoutParams.addRule(3, R.id.top_bar);
       layoutParams.topMargin = c.b(resources, 0x7f0708aa);
       view.setLayoutParams(layoutParams);
       relativeLayo.addView(view);
       viewStub = new ViewStub(relativeLayo.getContext());
       viewStub.setInflatedId(-1);
       layoutParams = new RelativeLayout$LayoutParams(-2, -2);
       viewStub.setId(R.id.live_wish_list_complete_result_view_stub);
       layoutParams.addRule(3, R.id.top_bar);
       layoutParams.topMargin = c.b(resources, 0x7f0708aa);
       viewStub.setInflatedId(R.id.live_wish_list_complete_result_root_view);
       viewStub.setLayoutResource(R.layout.arg_RES_7f0d0e8a);
       viewStub.setLayoutParams(layoutParams);
       relativeLayo.addView(viewStub);
       viewStub = new ViewStub(relativeLayo.getContext());
       viewStub.setInflatedId(-1);
       layoutParams = new RelativeLayout$LayoutParams(-2, -2);
       viewStub.setId(R.id.live_gather_popularity_commodity_stub);
       layoutParams.addRule(21, -1);
       layoutParams.addRule(3, R.id.live_top_pendant_container);
       layoutParams.topMargin = c.b(resources, 0x7f07034b);
       layoutParams.setMarginEnd(c.b(resources, R.dimen.pv));
       viewStub.setLayoutParams(layoutParams);
       relativeLayo.addView(viewStub);
       viewStub = new ViewStub(relativeLayo.getContext());
       viewStub.setInflatedId(-1);
       RelativeLayout$LayoutParams layoutParams1 = new RelativeLayout$LayoutParams(-1, -2);
       viewStub.setId(R.id.live_new_top_pendant_view_stub);
       layoutParams1.addRule(3, R.id.top_bar);
       viewStub.setLayoutResource(R.layout.arg_RES_7f0d0e10);
       viewStub.setInflatedId(R.id.live_top_pendant_container);
       layoutParams1.topMargin = c.b(resources, 0x7f0708aa);
       viewStub.setLayoutParams(layoutParams1);
       relativeLayo.addView(viewStub);
       viewStub = new ViewStub(relativeLayo.getContext());
       viewStub.setInflatedId(-1);
       layoutParams1 = new RelativeLayout$LayoutParams(-1, -2);
       viewStub.setId(R.id.live_new_top_pendant_view_stub_perf);
       layoutParams1.addRule(3, R.id.top_bar);
       viewStub.setLayoutResource(R.layout.arg_RES_7f0d0e11);
       viewStub.setInflatedId(R.id.live_top_pendant_container);
       layoutParams1.topMargin = c.b(resources, 0x7f0708aa);
       viewStub.setLayoutParams(layoutParams1);
       relativeLayo.addView(viewStub);
       viewStub = new ViewStub(relativeLayo.getContext());
       viewStub.setInflatedId(-1);
       layoutParams1 = new RelativeLayout$LayoutParams(-1, -2);
       viewStub.setId(R.id.live_merchant_top_pendant_view_stub);
       layoutParams1.addRule(3, R.id.live_top_pendant_container);
       layoutParams1.topMargin = c.b(resources, 0x7f07034b);
       viewStub.setLayoutResource(R.layout.arg_RES_7f0d0c9f);
       viewStub.setLayoutParams(layoutParams1);
       relativeLayo.addView(viewStub);
       viewStub = new ViewStub(relativeLayo.getContext());
       viewStub.setInflatedId(-1);
       layoutParams1 = new RelativeLayout$LayoutParams(-2, -2);
       viewStub.setId(R.id.live_top_pendant_square_source_back_entrance_stub);
       layoutParams1.addRule(6, R.id.live_top_pendant_container);
       layoutParams1.addRule(5, R.id.live_top_pendant_container);
       viewStub.setLayoutResource(R.layout.arg_RES_7f0d0e14);
       viewStub.setLayoutParams(layoutParams1);
       relativeLayo.addView(viewStub);
       viewStub = new ViewStub(relativeLayo.getContext());
       viewStub.setInflatedId(-1);
       layoutParams1 = new RelativeLayout$LayoutParams(-2, -2);
       viewStub.setId(R.id.live_top_pendant_square_source_back_entrance_stub_new);
       layoutParams1.addRule(6, R.id.live_top_pendant_container);
       layoutParams1.addRule(5, R.id.live_top_pendant_container);
       viewStub.setLayoutResource(R.layout.arg_RES_7f0d0e15);
       viewStub.setLayoutParams(layoutParams1);
       relativeLayo.addView(viewStub);
       viewStub = new ViewStub(relativeLayo.getContext());
       viewStub.setInflatedId(-1);
       viewStub.setId(R.id.live_announcement_view_stub);
       viewStub.setInflatedId(R.id.live_announcement_linear_layout);
       viewStub.setLayoutResource(R.layout.arg_RES_7f0d09da);
       viewStub.setLayoutParams(new RelativeLayout$LayoutParams(-1, -2));
       relativeLayo.addView(viewStub);
       view = new X2C_Live_Audience_Common_Info_View_Layout().createView(relativeLayo.getContext());
       layoutParams1 = view.getLayoutParams();
       layoutParams1.addRule(3, R.id.top_bar);
       layoutParams1.addRule(9, -1);
       layoutParams1.leftMargin = c.b(resources, 0x7f07025d);
       layoutParams1.topMargin = c.b(resources, 0x7f07034b);
       view.setLayoutParams(layoutParams1);
       relativeLayo.addView(view);
       viewStub = new ViewStub(relativeLayo.getContext());
       viewStub.setInflatedId(-1);
       layoutParams1 = new RelativeLayout$LayoutParams(-2, c.b(resources, 0x7f070985));
       viewStub.setId(R.id.live_top_broadcast_view_stub);
       viewStub.setInflatedId(R.id.live_top_broadcast_container);
       viewStub.setLayoutResource(R.layout.arg_RES_7f0d0e0c);
       layoutParams1.addRule(6, R.id.live_top_pendant_container);
       layoutParams1.topMargin = (int)TypedValue.applyDimension(1, -2.00f, c.c(resources));
       viewStub.setLayoutParams(layoutParams1);
       relativeLayo.addView(viewStub);
       viewStub = new ViewStub(relativeLayo.getContext());
       viewStub.setInflatedId(-1);
       layoutParams1 = new RelativeLayout$LayoutParams(-1, -2);
       viewStub.setId(R.id.live_guest_activity_top_list_view_stub);
       layoutParams1.addRule(3, R.id.top_bar);
       layoutParams1.topMargin = c.b(resources, 0x7f070356);
       viewStub.setLayoutResource(R.layout.arg_RES_7f0d0b54);
       viewStub.setLayoutParams(layoutParams1);
       relativeLayo.addView(viewStub);
       LiveOperationNotificationView liveOperatio = new LiveOperationNotificationView(relativeLayo.getContext());
       layoutParams1 = new RelativeLayout$LayoutParams(-2, c.b(resources, 0x7f070897));
       liveOperatio.setId(R.id.live_operation_notify_view);
       liveOperatio.setClipChildren(false);
       liveOperatio.setClipToPadding(false);
       layoutParams1.addRule(3, R.id.top_bar);
       layoutParams1.leftMargin = c.b(resources, 0x7f07025d);
       layoutParams1.topMargin = (int)TypedValue.applyDimension(1, 8.00f, c.c(resources));
       layoutParams1.rightMargin = c.b(resources, 0x7f07025d);
       liveOperatio.setVisibility(8);
       liveOperatio.setLayoutParams(layoutParams1);
       relativeLayo.addView(liveOperatio);
       liveOperatio.onFinishInflate();
       LiveCustomNoticeView liveCustomNo = new LiveCustomNoticeView(relativeLayo.getContext());
       layoutParams1 = new RelativeLayout$LayoutParams(-2, c.b(resources, 0x7f070897));
       liveCustomNo.setId(R.id.live_customer_notify_view);
       liveCustomNo.setClipChildren(false);
       liveCustomNo.setClipToPadding(false);
       layoutParams1.addRule(3, R.id.top_bar);
       layoutParams1.leftMargin = c.b(resources, 0x7f07025d);
       layoutParams1.topMargin = (int)TypedValue.applyDimension(1, 8.00f, c.c(resources));
       layoutParams1.rightMargin = c.b(resources, 0x7f07025d);
       liveCustomNo.setVisibility(8);
       liveCustomNo.setLayoutParams(layoutParams1);
       relativeLayo.addView(liveCustomNo);
       liveCustomNo.onFinishInflate();
       viewStub = new ViewStub(relativeLayo.getContext());
       viewStub.setInflatedId(-1);
       layoutParams1 = new RelativeLayout$LayoutParams(-2, -2);
       viewStub.setId(R.id.live_hourly_rank_temp_view_stub);
       layoutParams1.addRule(3, R.id.top_bar);
       layoutParams1.leftMargin = c.b(resources, 0x7f07025d);
       layoutParams1.topMargin = c.b(resources, 0x7f07034b);
       viewStub.setLayoutResource(R.layout.arg_RES_7f0d0c35);
       viewStub.setLayoutParams(layoutParams1);
       relativeLayo.addView(viewStub);
       viewStub = new ViewStub(relativeLayo.getContext());
       viewStub.setInflatedId(-1);
       layoutParams1 = new RelativeLayout$LayoutParams(-2, c.b(resources, 0x7f0702d2));
       viewStub.setId(R.id.live_normal_rank_notice_view_stub);
       layoutParams1.addRule(3, R.id.top_bar);
       layoutParams1.addRule(9, -1);
       layoutParams1.leftMargin = c.b(resources, 0x7f07025d);
       layoutParams1.topMargin = c.b(resources, 0x7f07034b);
       viewStub.setLayoutResource(R.layout.arg_RES_7f0d0ce7);
       viewStub.setLayoutParams(layoutParams1);
       relativeLayo.addView(viewStub);
       DrawingGiftDisplayView uDrawingGift = new DrawingGiftDisplayView(relativeLayo.getContext());
       layoutParams1 = new RelativeLayout$LayoutParams(-1, -1);
       uDrawingGift.setId(R.id.drawing_display_view);
       layoutParams1.addRule(10, -1);
       layoutParams1.addRule(14, -1);
       layoutParams1.topMargin = (int)TypedValue.applyDimension(1, 51.00f, c.c(resources));
       uDrawingGift.setLayoutParams(layoutParams1);
       relativeLayo.addView(uDrawingGift);
       viewStub = new ViewStub(relativeLayo.getContext());
       viewStub.setInflatedId(-1);
       layoutParams1 = new RelativeLayout$LayoutParams(-1, -1);
       viewStub.setId(R.id.live_low_layer_effect_glview_stub);
       layoutParams1.addRule(13, -1);
       viewStub.setLayoutResource(R.layout.arg_RES_7f0d0d19);
       viewStub.setLayoutParams(layoutParams1);
       relativeLayo.addView(viewStub);
       ListView listView = new ListView(relativeLayo.getContext());
       listView.setSelector(R.drawable.arg_RES_7f08022c);
       listView.setDivider(ContextCompat.getDrawable(uContext, R.color.arg_RES_7f060c42));
       listView.setFooterDividersEnabled(false);
       listView.setOverScrollMode(2);
       listView.setDividerHeight(c.b(resources, R.dimen.arg_RES_7f070195));
       listView.setHeaderDividersEnabled(1);
       listView.setId(R.id.pending_list);
       listView.setVisibility(8);
       listView.setLayoutParams(new RelativeLayout$LayoutParams(-1, (int)TypedValue.applyDimension(1, 100.00f, c.c(resources))));
       relativeLayo.addView(listView);
       RelativeLayout relativeLayo1 = new RelativeLayout(relativeLayo.getContext());
       layoutParams1 = new RelativeLayout$LayoutParams(-2, -1);
       relativeLayo1.setId(R.id.live_right_pendant_group_container_view);
       layoutParams1.addRule(12, -1);
       layoutParams1.addRule(21, -1);
       layoutParams1.topMargin = (int)TypedValue.applyDimension(1, 100.00f, c.c(resources));
       layoutParams1.bottomMargin = (int)TypedValue.applyDimension(1, 55.00f, c.c(resources));
       relativeLayo1.setLayoutParams(layoutParams1);
       relativeLayo.addView(relativeLayo1);
       viewStub = new ViewStub(relativeLayo.getContext());
       viewStub.setInflatedId(-1);
       layoutParams1 = new RelativeLayout$LayoutParams(-2, -2);
       viewStub.setId(R.id.live_merchant_right_pendant_container_stub);
       layoutParams1.addRule(21, -1);
       layoutParams1.addRule(3, R.id.live_top_pendant_container);
       layoutParams1.topMargin = c.b(resources, 0x7f07034b);
       viewStub.setLayoutParams(layoutParams1);
       relativeLayo.addView(viewStub);
       KwaiImageView kwaiImageVie = new KwaiImageView(relativeLayo.getContext());
       layoutParams1 = new RelativeLayout$LayoutParams(c.b(resources, 0x7f070261), c.b(resources, 0x7f0702bd));
       kwaiImageVie.setId(R.id.live_right_bottom_activity_widget_animation_view);
       layoutParams1.addRule(12, -1);
       layoutParams1.bottomMargin = c.b(resources, 0x7f070221);
       layoutParams1.addRule(21, -1);
       layoutParams1.rightMargin = c.b(resources, 0x7f07025d);
       kwaiImageVie.setVisibility(8);
       kwaiImageVie.setLayoutParams(layoutParams1);
       relativeLayo.addView(kwaiImageVie);
       FrameLayout uFrameLayout = new FrameLayout(relativeLayo.getContext());
       layoutParams1 = new RelativeLayout$LayoutParams(-1, -1);
       uFrameLayout.setId(R.id.live_danmaku_container);
       layoutParams1.addRule(2, R.id.bottom_bar);
       layoutParams1.bottomMargin = c.b(resources, 0x7f0705c2);
       uFrameLayout.setPadding(0, (int)TypedValue.applyDimension(1, 12.00f, c.c(resources)), 0, c.b(resources, R.dimen.arg_RES_7f0702b8));
       uFrameLayout.setLayoutParams(layoutParams1);
       relativeLayo.addView(uFrameLayout);
       viewStub = new ViewStub(relativeLayo.getContext());
       viewStub.setInflatedId(-1);
       layoutParams1 = new RelativeLayout$LayoutParams(-1, -1);
       viewStub.setId(R.id.live_show_layout_stub);
       layoutParams1.addRule(2, R.id.bottom_bar);
       viewStub.setInflatedId(R.id.live_show_layout);
       viewStub.setLayoutResource(R.layout.arg_RES_7f0d0d0a);
       viewStub.setLayoutParams(layoutParams1);
       relativeLayo.addView(viewStub);
       uFrameLayout = new FrameLayout(relativeLayo.getContext());
       layoutParams1 = new RelativeLayout$LayoutParams(-1, -2);
       uFrameLayout.setId(R.id.live_left_bottom_bubble);
       layoutParams1.addRule(8, R.id.live_show_layout);
       layoutParams1.addRule(5, R.id.live_show_layout);
       uFrameLayout.setLayoutParams(layoutParams1);
       relativeLayo.addView(uFrameLayout);
       viewStub = new ViewStub(relativeLayo.getContext());
       viewStub.setInflatedId(-1);
       viewStub.setId(R.id.live_right_pendant_group_container_view_higher_stub);
       viewStub.setInflatedId(R.id.live_right_pendant_group_container_view_higher);
       viewStub.setLayoutResource(R.layout.arg_RES_7f0d0db7);
       viewStub.setLayoutParams(new RelativeLayout$LayoutParams(-2, -2));
       relativeLayo.addView(viewStub);
       view = new X2C_Live_Gzone_Scene_Container().createView(relativeLayo.getContext());
       view.setId(R.id.live_gzone_audience_scene_container);
       view.setLayoutParams(view.getLayoutParams());
       relativeLayo.addView(view);
       LinearLayout linearLayout = new LinearLayout(relativeLayo.getContext());
       layoutParams1 = new RelativeLayout$LayoutParams(-1, -2);
       linearLayout.setId(R.id.live_central_enter_room_message_area);
       layoutParams1.addRule(12, -1);
       linearLayout.setOrientation(1);
       linearLayout.setClipChildren(false);
       linearLayout.setLayoutParams(layoutParams1);
       relativeLayo.addView(linearLayout);
       LinearLayout linearLayout1 = new LinearLayout(linearLayout.getContext());
       linearLayout1.setBackgroundDrawable(null);
       linearLayout1.setId(R.id.live_central_enter_room_message_area_animate_area);
       linearLayout1.setOrientation(1);
       linearLayout1.setClipChildren(false);
       linearLayout1.setLayoutParams(new LinearLayout$LayoutParams(-1, -2));
       linearLayout.addView(linearLayout1);
       linearLayout = new LinearLayout(relativeLayo.getContext());
       layoutParams1 = new RelativeLayout$LayoutParams(-2, -2);
       layoutParams1.addRule(11, -1);
       layoutParams1.addRule(12, -1);
       linearLayout.setOrientation(1);
       layoutParams1.bottomMargin = (int)TypedValue.applyDimension(1, 60.00f, c.c(resources));
       linearLayout.setLayoutParams(layoutParams1);
       relativeLayo.addView(linearLayout);
       LiveChatApplyButton liveChatAppl = new LiveChatApplyButton(linearLayout.getContext(), null, 0);
       LinearLayout$LayoutParams layoutParams2 = new LinearLayout$LayoutParams((int)TypedValue.applyDimension(1, 104.00f, c.c(resources)), (int)TypedValue.applyDimension(1, 36.00f, c.c(resources)));
       liveChatAppl.setBackgroundResource(R.drawable.arg_RES_7f0802a2);
       liveChatAppl.setTypeface(null, 1);
       liveChatAppl.setTextSize(1, 12.00f);
       liveChatAppl.setEllipsize(TextUtils$TruncateAt.END);
       liveChatAppl.setMaxLines(1);
       liveChatAppl.setGravity(19);
       liveChatAppl.setCompoundDrawablePadding((int)TypedValue.applyDimension(1, 8.00f, c.c(resources)));
       liveChatAppl.setTextColor(resources.getColor(R.color.arg_RES_7f060ca0));
       liveChatAppl.setId(R.id.live_chat_apply_button);
       layoutParams2.topMargin = (int)TypedValue.applyDimension(1, 8.00f, c.c(resources));
       layoutParams2.rightMargin = (int)TypedValue.applyDimension(1, 11.00f, c.c(resources));
       liveChatAppl.setVisibility(8);
       liveChatAppl.setCompoundDrawablesWithIntrinsicBounds(ContextCompat.getDrawable(uContext, R.drawable.arg_RES_7f0810b9), null, null, null);
       liveChatAppl.setPadding(c.b(resources, R.dimen.arg_RES_7f070283), 0, 0, 0);
       liveChatAppl.setLayoutParams(layoutParams2);
       linearLayout.addView(liveChatAppl);
       ViewStub viewStub1 = new ViewStub(relativeLayo.getContext());
       viewStub1.setInflatedId(-1);
       RelativeLayout$LayoutParams layoutParams3 = new RelativeLayout$LayoutParams(c.b(resources, 0x7f0707fa), -2);
       viewStub1.setId(R.id.live_gzone_vote_card_view_stub);
       layoutParams3.addRule(12, -1);
       layoutParams3.leftMargin = (int)TypedValue.applyDimension(1, 11.00f, c.c(resources));
       layoutParams3.bottomMargin = c.b(resources, 0x7f0707f9);
       viewStub1.setLayoutParams(layoutParams3);
       relativeLayo.addView(viewStub1);
       viewStub1 = new ViewStub(relativeLayo.getContext());
       viewStub1.setInflatedId(-1);
       viewStub1.setId(R.id.live_gzone_activity_banner_view_stub);
       viewStub1.setInflatedId(R.id.live_gzone_activity_banner_container);
       viewStub1.setLayoutResource(R.layout.arg_RES_7f0d0b73);
       viewStub1.setLayoutParams(new RelativeLayout$LayoutParams(-1, -2));
       relativeLayo.addView(viewStub1);
       viewStub1 = new ViewStub(relativeLayo.getContext());
       viewStub1.setInflatedId(-1);
       layoutParams3 = new RelativeLayout$LayoutParams(-2, -2);
       viewStub1.setId(R.id.live_music_audience_lyrics_view_stub);
       layoutParams3.addRule(3, R.id.live_left_top_pendant);
       layoutParams3.leftMargin = c.b(resources, 0x7f07025d);
       layoutParams3.topMargin = c.b(resources, 0x7f07034b);
       viewStub1.setLayoutParams(layoutParams3);
       relativeLayo.addView(viewStub1);
       FrameLayout uFrameLayout1 = new FrameLayout(relativeLayo.getContext());
       layoutParams3 = new RelativeLayout$LayoutParams(-1, -1);
       uFrameLayout1.setId(R.id.live_subscribe_draggable_views_container);
       layoutParams3.addRule(3, R.id.top_bar);
       layoutParams3.topMargin = c.b(resources, 0x7f070338);
       uFrameLayout1.setVisibility(8);
       uFrameLayout1.setLayoutParams(layoutParams3);
       relativeLayo.addView(uFrameLayout1);
       viewStub = new ViewStub(uFrameLayout1.getContext());
       viewStub.setInflatedId(-1);
       viewStub.setId(R.id.live_subscribe_pendant_view_stub);
       viewStub.setInflatedId(R.id.live_subscribe_pendant_view);
       viewStub.setLayoutResource(R.layout.live_subscribe_pendant_view);
       viewStub.setLayoutParams(new FrameLayout$LayoutParams(-2, -2));
       uFrameLayout1.addView(viewStub);
       uFrameLayout1 = new FrameLayout(relativeLayo.getContext());
       uFrameLayout1.setId(R.id.live_audience_encourage_treasure_box_draggable_container);
       uFrameLayout1.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       relativeLayo.addView(uFrameLayout1);
       viewStub1 = new ViewStub(relativeLayo.getContext());
       viewStub1.setInflatedId(-1);
       layoutParams3 = new RelativeLayout$LayoutParams(-2, -2);
       viewStub1.setId(R.id.live_fancy_rank_result_view_stub);
       layoutParams3.addRule(3, R.id.top_bar);
       layoutParams3.leftMargin = c.b(resources, 0x7f07025d);
       layoutParams3.topMargin = c.b(resources, 0x7f07034b);
       viewStub1.setLayoutResource(R.layout.arg_RES_7f0d0afd);
       viewStub1.setLayoutParams(layoutParams3);
       relativeLayo.addView(viewStub1);
       uFrameLayout1 = new FrameLayout(relativeLayo.getContext());
       layoutParams3 = new RelativeLayout$LayoutParams(-2, -2);
       uFrameLayout1.setId(R.id.live_left_top_notice_layout);
       layoutParams3.addRule(6, R.id.live_top_pendant_container);
       layoutParams3.addRule(9, -1);
       uFrameLayout1.setLayoutParams(layoutParams3);
       relativeLayo.addView(uFrameLayout1);
       viewStub1 = new ViewStub(relativeLayo.getContext());
       viewStub1.setInflatedId(-1);
       viewStub1.setId(R.id.live_bottom_rebroadcast_view_stub);
       viewStub1.setInflatedId(R.id.live_gzone_bottom_rebroadcast_pendent_container);
       viewStub1.setLayoutParams(new RelativeLayout$LayoutParams(-1, c.b(resources, R.dimen.arg_RES_7f0707e8)));
       relativeLayo.addView(viewStub1);
       viewStub1 = new ViewStub(relativeLayo.getContext());
       viewStub1.setInflatedId(-1);
       layoutParams3 = new RelativeLayout$LayoutParams((int)TypedValue.applyDimension(1, 0x42f00000, c.c(resources)), c.b(resources, 0x7f0702d2));
       viewStub1.setId(R.id.live_left_top_rebroadcast_view_stub);
       layoutParams3.addRule(3, R.id.top_bar);
       layoutParams3.topMargin = c.b(resources, 0x7f0708aa);
       layoutParams3.leftMargin = c.b(resources, 0x7f070a7f);
       viewStub1.setLayoutResource(R.layout.arg_RES_7f0d0c4a);
       viewStub1.setLayoutParams(layoutParams3);
       relativeLayo.addView(viewStub1);
       View view1 = new View(relativeLayo.getContext());
       layoutParams3 = new RelativeLayout$LayoutParams(-1, (int)TypedValue.applyDimension(1, 0x3f800000, c.c(resources)));
       layoutParams3.addRule(3, R.id.bottom_bar);
       layoutParams3.topMargin = (int)TypedValue.applyDimension(1, 0xbf800000, c.c(resources));
       view1.setBackgroundColor(resources.getColor(R.color.arg_RES_7f0619a2));
       view1.setLayoutParams(layoutParams3);
       relativeLayo.addView(view1);
       view1 = new View(relativeLayo.getContext());
       view1.setId(R.id.live_play_music_station_top_shadow);
       view1.setVisibility(8);
       view1.setLayoutParams(new RelativeLayout$LayoutParams(-1, (int)TypedValue.applyDimension(1, 136.00f, c.c(resources))));
       relativeLayo.addView(view1);
       view1 = new X2C_Live_Play_Top_Bar_Popup_Head().createView(relativeLayo.getContext());
       view1.setId(R.id.top_bar);
       view1.setLayoutParams(view1.getLayoutParams());
       relativeLayo.addView(view1);
       viewStub1 = new ViewStub(relativeLayo.getContext());
       viewStub1.setInflatedId(-1);
       layoutParams3 = new RelativeLayout$LayoutParams(-2, -2);
       viewStub1.setId(R.id.live_broadcast_banner_container_view_stub);
       layoutParams3.addRule(3, R.id.top_bar);
       layoutParams3.topMargin = c.b(resources, 0x7f07034b);
       viewStub1.setInflatedId(R.id.live_broadcast_banner_container_view);
       viewStub1.setLayoutResource(R.layout.arg_RES_7f0d0a8f);
       viewStub1.setLayoutParams(layoutParams3);
       relativeLayo.addView(viewStub1);
       view1 = new X2C_Live_Audience_Fullscreen_Left_Center_Pendant_Layout().createView(relativeLayo.getContext());
       view1.setLayoutParams(view1.getLayoutParams());
       relativeLayo.addView(view1);
       viewStub1 = new ViewStub(relativeLayo.getContext());
       viewStub1.setInflatedId(-1);
       layoutParams3 = new RelativeLayout$LayoutParams((int)TypedValue.applyDimension(1, 140.00f, c.c(resources)), (int)TypedValue.applyDimension(1, 140.00f, c.c(resources)));
       viewStub1.setId(R.id.live_landscape_elements_view_stub);
       layoutParams3.addRule(13, -1);
       viewStub1.setInflatedId(R.id.step_progress_panel);
       viewStub1.setLayoutResource(R.layout.arg_RES_7f0d0c40);
       viewStub1.setLayoutParams(layoutParams3);
       relativeLayo.addView(viewStub1);
       view1 = new X2C_Live_Gzone_Right_Bottom_Pendant_Container().createView(relativeLayo.getContext());
       view1.setLayoutParams(view1.getLayoutParams());
       relativeLayo.addView(view1);
       viewStub1 = new ViewStub(relativeLayo.getContext());
       viewStub1.setInflatedId(-1);
       layoutParams3 = new RelativeLayout$LayoutParams(-2, -2);
       viewStub1.setId(R.id.live_gzone_distribute_card_view_stub);
       viewStub1.setInflatedId(R.id.live_gzone_distribute_card_view);
       viewStub1.setLayoutResource(R.layout.arg_RES_7f0d0bb0);
       layoutParams3.leftMargin = (int)TypedValue.applyDimension(1, 11.00f, c.c(resources));
       layoutParams3.addRule(2, R.id.bottom_bar);
       viewStub1.setLayoutParams(layoutParams3);
       relativeLayo.addView(viewStub1);
       viewStub1 = new ViewStub(relativeLayo.getContext());
       viewStub1.setInflatedId(-1);
       viewStub1.setId(R.id.live_ktv_rating_popup_stub);
       viewStub1.setInflatedId(R.id.live_ktv_rating_popup);
       viewStub1.setLayoutResource(R.layout.arg_RES_7f0d0c3e);
       viewStub1.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       relativeLayo.addView(viewStub1);
       viewStub1 = new ViewStub(relativeLayo.getContext());
       viewStub1.setInflatedId(-1);
       viewStub1.setId(R.id.live_voice_party_channel_feed_stub);
       viewStub1.setInflatedId(R.id.live_voice_party_channel_feed);
       viewStub1.setLayoutResource(R.layout.arg_RES_7f0d0e3d);
       viewStub1.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       relativeLayo.addView(viewStub1);
       viewStub1 = new ViewStub(relativeLayo.getContext());
       viewStub1.setInflatedId(-1);
       layoutParams3 = new RelativeLayout$LayoutParams(-1, -1);
       viewStub1.setId(R.id.live_middle_layer_multi_effect_glview_stub);
       layoutParams3.addRule(13, -1);
       viewStub1.setLayoutResource(R.layout.arg_RES_7f0d0d1b);
       viewStub1.setLayoutParams(layoutParams3);
       relativeLayo.addView(viewStub1);
       viewStub1 = new ViewStub(relativeLayo.getContext());
       viewStub1.setInflatedId(-1);
       layoutParams3 = new RelativeLayout$LayoutParams(-1, -1);
       viewStub1.setId(R.id.live_middle_layer_effect_glview_stub);
       layoutParams3.addRule(13, -1);
       viewStub1.setLayoutResource(R.layout.arg_RES_7f0d0d1a);
       viewStub1.setLayoutParams(layoutParams3);
       relativeLayo.addView(viewStub1);
       LinearLayout linearLayout2 = new LinearLayout(relativeLayo.getContext());
       layoutParams3 = new RelativeLayout$LayoutParams(-1, -2);
       linearLayout2.setId(R.id.live_enter_room_above_bottom_bar_container);
       layoutParams3.addRule(2, R.id.bottom_bar);
       linearLayout2.setOrientation(1);
       linearLayout2.setGravity(1);
       linearLayout2.setVisibility(0);
       linearLayout2.setLayoutParams(layoutParams3);
       relativeLayo.addView(linearLayout2);
       linearLayout = new LinearLayout(linearLayout2.getContext());
       linearLayout.setId(R.id.live_enter_room_above_bottom_bar_animate_area);
       linearLayout.setOrientation(1);
       linearLayout.setClipChildren(0);
       linearLayout.setLayoutParams(new LinearLayout$LayoutParams(-1, -2));
       linearLayout2.addView(linearLayout);
       LiveEnterRoomMountView liveEnterRoo = new LiveEnterRoomMountView(linearLayout2.getContext());
       LinearLayout$LayoutParams layoutParams4 = new LinearLayout$LayoutParams(-1, c.b(resources, 0x7f0702e5));
       liveEnterRoo.setId(R.id.live_enter_room_noble_mount_image);
       layoutParams4.bottomMargin = c.b(resources, 0x7f0702ab);
       layoutParams4.topMargin = c.b(resources, 0x7f0702ab);
       liveEnterRoo.setLayoutParams(layoutParams4);
       linearLayout2.addView(liveEnterRoo);
       uFrameLayout1 = new FrameLayout(relativeLayo.getContext());
       layoutParams3 = new RelativeLayout$LayoutParams(-1, -2);
       uFrameLayout1.setId(R.id.bottom_bar);
       layoutParams3.addRule(12, -1);
       uFrameLayout1.setMinimumHeight(c.b(resources, R.dimen.arg_RES_7f0705b7));
       uFrameLayout1.setVisibility(4);
       uFrameLayout1.setPadding(c.b(resources, R.dimen.arg_RES_7f070a81), 0, 0, 0);
       uFrameLayout1.setLayoutParams(layoutParams3);
       relativeLayo.addView(uFrameLayout1);
       viewStub1 = new ViewStub(relativeLayo.getContext());
       viewStub1.setInflatedId(-1);
       int i = c.b(resources, R.dimen.arg_RES_7f070319);
       viewStub1.setId(R.id.live_lucky_time_combo_send_gift_view_stub);
       viewStub1.setLayoutResource(R.layout.arg_RES_7f0d0a7e);
       viewStub1.setLayoutParams(new RelativeLayout$LayoutParams(i, c.b(resources, R.dimen.arg_RES_7f070319)));
       relativeLayo.addView(viewStub1);
       LiveGiftBoxGiftParticleAnimationView liveGiftBoxG = new LiveGiftBoxGiftParticleAnimationView(relativeLayo.getContext());
       liveGiftBoxG.setId(R.id.live_bottom_bar_gift_combo_particle_anim_view);
       liveGiftBoxG.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       relativeLayo.addView(liveGiftBoxG);
       view1 = new X2C_Live_Gift_Box_Combo_Text_Animation_Layout().createView(relativeLayo.getContext());
       view1.setId(R.id.live_bottom_bar_gift_combo_text_anim_view);
       view1.setVisibility(8);
       view1.setLayoutParams(view1.getLayoutParams());
       relativeLayo.addView(view1);
       viewStub1 = new ViewStub(relativeLayo.getContext());
       viewStub1.setInflatedId(-1);
       viewStub1.setId(R.id.live_bottom_bar_wish_light_gift_combo_text_anim_view);
       viewStub1.setLayoutResource(R.layout.arg_RES_7f0d0e8b);
       viewStub1.setLayoutParams(new RelativeLayout$LayoutParams(-2, -2));
       relativeLayo.addView(viewStub1);
       viewStub1 = new ViewStub(relativeLayo.getContext());
       viewStub1.setInflatedId(-1);
       viewStub1.setId(R.id.live_waring_mask_container_view_stub);
       viewStub1.setLayoutResource(R.layout.arg_RES_7f0d0e82);
       viewStub1.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       relativeLayo.addView(viewStub1);
       viewStub1 = new ViewStub(relativeLayo.getContext());
       viewStub1.setInflatedId(-1);
       viewStub1.setId(R.id.live_banned_layout_container_view_stub_v2);
       viewStub1.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       relativeLayo.addView(viewStub1);
       viewStub1 = new ViewStub(relativeLayo.getContext());
       viewStub1.setInflatedId(-1);
       viewStub1.setId(R.id.live_banned_layout_container_view_stub);
       viewStub1.setLayoutResource(R.layout.arg_RES_7f0d0a6c);
       viewStub1.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       relativeLayo.addView(viewStub1);
       return relativeLayo;
    }
}
