package com.kuaishou.ax2c.layouts.X2C_Live_Audience_Bottom_Bar_Comment_Layout;
import com.kuaishou.ax2c.IViewCreator;
import java.lang.Object;
import android.content.Context;
import android.view.View;
import android.content.res.Resources;
import android.widget.LinearLayout;
import android.view.ViewGroup$MarginLayoutParams;
import android.view.ViewGroup$LayoutParams;
import android.widget.LinearLayout$LayoutParams;
import cw9.c;
import android.view.ViewStub;
import android.util.DisplayMetrics;
import android.util.TypedValue;
import com.yxcorp.gifshow.image.KwaiImageView;
import android.widget.ImageView;
import android.widget.ImageView$ScaleType;
import com.facebook.drawee.generic.RoundingParams;
import ac.b;
import com.facebook.drawee.view.DraweeView;
import yb.a;
import com.kuaishou.live.common.core.component.comments.widget.LiveAudienceCommentPlaceholderTextSwitcher;
import android.widget.TextSwitcher;
import com.kuaishou.live.common.core.component.comments.widget.VoiceInputGestureView;
import androidx.appcompat.widget.AppCompatImageView;

public class X2C_Live_Audience_Bottom_Bar_Comment_Layout implements IViewCreator	// class@0010cf
{

    public void X2C_Live_Audience_Bottom_Bar_Comment_Layout(){
       super();
    }
    public View createView(Context p0){
       Resources resources = p0.getResources();
       LinearLayout linearLayout = new LinearLayout(p0);
       linearLayout.setClipChildren(false);
       linearLayout.setClipToPadding(false);
       linearLayout.setOrientation(false);
       linearLayout.setLayoutParams(new ViewGroup$MarginLayoutParams(-2, -2));
       LinearLayout linearLayout1 = new LinearLayout(linearLayout.getContext());
       linearLayout1.setId(R.id.live_comment_container_v2);
       linearLayout1.setBackgroundResource(R.drawable.arg_RES_7f081172);
       linearLayout1.setClipChildren(false);
       linearLayout1.setClipToPadding(false);
       linearLayout1.setOrientation(false);
       linearLayout1.setLayoutParams(new LinearLayout$LayoutParams(c.b(resources, R.dimen.arg_RES_7f0705bf), c.b(resources, R.dimen.arg_RES_7f0705e4)));
       linearLayout.addView(linearLayout1);
       ViewStub viewStub = new ViewStub(linearLayout1.getContext());
       viewStub.setInflatedId(-1);
       LinearLayout$LayoutParams layoutParams = new LinearLayout$LayoutParams(-2, -2);
       viewStub.setId(R.id.live_gzone_audience_hot_words_container_view_stub);
       layoutParams.gravity = 16;
       viewStub.setInflatedId(R.id.live_gzone_audience_hot_words_container);
       viewStub.setLayoutResource(R.layout.arg_RES_7f0d0b90);
       layoutParams.rightMargin = (int)TypedValue.applyDimension(1, -2.00f, c.c(resources));
       viewStub.setLayoutParams(layoutParams);
       linearLayout1.addView(viewStub);
       KwaiImageView kwaiImageVie = new KwaiImageView(linearLayout1.getContext());
       layoutParams = new LinearLayout$LayoutParams(c.b(resources, 0x7f0705be), c.b(resources, 0x7f0705be));
       kwaiImageVie.setId(R.id.live_comment_left_icon_image_view);
       layoutParams.gravity = 16;
       layoutParams.rightMargin = c.b(resources, 0x7f0705c7);
       layoutParams.leftMargin = c.b(resources, 0x7f0705bd);
       kwaiImageVie.setScaleType(ImageView$ScaleType.FIT_XY);
       kwaiImageVie.setVisibility(8);
       kwaiImageVie.getHierarchy().L(RoundingParams.a());
       kwaiImageVie.setLayoutParams(layoutParams);
       linearLayout1.addView(kwaiImageVie);
       LiveAudienceCommentPlaceholderTextSwitcher liveAudience = new LiveAudienceCommentPlaceholderTextSwitcher(linearLayout1.getContext());
       layoutParams = new LinearLayout$LayoutParams((int)TypedValue.applyDimension(1, 0, c.c(resources)), -1);
       liveAudience.setId(R.id.live_comment_text_view);
       layoutParams.weight = 0x3f800000;
       layoutParams.setMarginStart(c.b(resources, R.dimen.arg_RES_7f070271));
       liveAudience.setLayoutParams(layoutParams);
       linearLayout1.addView(liveAudience);
       kwaiImageVie = new KwaiImageView(linearLayout1.getContext());
       LinearLayout$LayoutParams layoutParams1 = new LinearLayout$LayoutParams(c.b(resources, 0x7f0705be), c.b(resources, 0x7f0705be));
       kwaiImageVie.setId(R.id.live_comment_small_image_view);
       layoutParams1.gravity = 16;
       layoutParams1.leftMargin = c.b(resources, 0x7f070334);
       layoutParams1.rightMargin = c.b(resources, 0x7f07030a);
       kwaiImageVie.setScaleType(ImageView$ScaleType.FIT_XY);
       kwaiImageVie.setImageResource(R.drawable.arg_RES_7f081125);
       kwaiImageVie.setVisibility(8);
       kwaiImageVie.setLayoutParams(layoutParams1);
       linearLayout1.addView(kwaiImageVie);
       VoiceInputGestureView voiceInputGe = new VoiceInputGestureView(linearLayout1.getContext());
       layoutParams1 = new LinearLayout$LayoutParams(c.b(resources, 0x7f0705be), c.b(resources, 0x7f0705be));
       voiceInputGe.setId(R.id.live_comment_voice_view);
       layoutParams1.gravity = 16;
       layoutParams1.leftMargin = c.b(resources, 0x7f07031b);
       layoutParams1.rightMargin = c.b(resources, 0x7f0705bd);
       voiceInputGe.setScaleType(ImageView$ScaleType.CENTER);
       voiceInputGe.setImageResource(R.drawable.arg_RES_7f08113c);
       voiceInputGe.setVisibility(8);
       voiceInputGe.setLayoutParams(layoutParams1);
       linearLayout1.addView(voiceInputGe);
       AppCompatImageView uAppCompatIm = new AppCompatImageView(linearLayout1.getContext());
       layoutParams1 = new LinearLayout$LayoutParams(c.b(resources, 0x7f0705be), c.b(resources, 0x7f0705be));
       uAppCompatIm.setId(R.id.live_comment_emoji_view);
       layoutParams1.gravity = 16;
       layoutParams1.leftMargin = c.b(resources, 0x7f07031b);
       layoutParams1.rightMargin = c.b(resources, 0x7f0705bd);
       uAppCompatIm.setScaleType(ImageView$ScaleType.CENTER);
       uAppCompatIm.setVisibility(8);
       uAppCompatIm.setLayoutParams(layoutParams1);
       linearLayout1.addView(uAppCompatIm);
       return linearLayout;
    }
}
