package com.kuaishou.ax2c.layouts.X2C_Live_Audience_Bottom_Bar_Gift_Item;
import com.kuaishou.ax2c.IViewCreator;
import java.lang.Object;
import android.content.Context;
import android.view.View;
import android.content.res.Resources;
import android.widget.FrameLayout;
import android.view.ViewGroup$MarginLayoutParams;
import cw9.c;
import android.view.ViewGroup$LayoutParams;
import com.kuaishou.live.common.core.component.gift.update.LiveRoundViewFlipper;
import android.widget.FrameLayout$LayoutParams;
import android.widget.ViewFlipper;
import com.kuaishou.live.core.basic.widget.LiveCustomViewFlipper;
import com.yxcorp.gifshow.image.KwaiImageView;
import android.widget.ImageView;
import android.widget.ImageView$ScaleType;
import ac.b;
import com.facebook.drawee.view.DraweeView;
import yb.a;
import android.graphics.drawable.Drawable;
import androidx.core.content.ContextCompat;
import com.kuaishou.live.widget.LiveOptLottieAnimationView;
import android.util.DisplayMetrics;
import android.util.TypedValue;
import androidx.appcompat.widget.AppCompatImageView;
import com.yxcorp.widget.selector.view.SelectShapeLinearLayout;
import android.widget.LinearLayout;
import com.kuaishou.ax2c.XmlAttrHostImpl;
import java.lang.Integer;
import com.kuaishou.ax2c.IAttrHost;
import ald.b;
import android.widget.LinearLayout$LayoutParams;
import androidx.appcompat.widget.AppCompatTextView;
import android.widget.TextView;

public class X2C_Live_Audience_Bottom_Bar_Gift_Item implements IViewCreator	// class@0010d1
{

    public void X2C_Live_Audience_Bottom_Bar_Gift_Item(){
       super();
    }
    public View createView(Context p0){
       Resources resources = p0.getResources();
       FrameLayout uFrameLayout = new FrameLayout(p0);
       uFrameLayout.setId(R.id.live_bottom_bar_gift_container);
       uFrameLayout.setClipChildren(false);
       uFrameLayout.setLayoutParams(new ViewGroup$MarginLayoutParams(c.b(resources, R.dimen.arg_RES_7f0705e4), c.b(resources, R.dimen.arg_RES_7f0705e4)));
       LiveRoundViewFlipper liveRoundVie = new LiveRoundViewFlipper(uFrameLayout.getContext());
       liveRoundVie.setId(R.id.live_gift_update_flipper);
       liveRoundVie.setBackgroundResource(R.drawable.arg_RES_7f081100);
       liveRoundVie.setInAnimation(p0, R.anim.arg_RES_7f01007c);
       liveRoundVie.setOutAnimation(p0, R.anim.arg_RES_7f01007d);
       liveRoundVie.setVisibility(8);
       liveRoundVie.setLayoutParams(new FrameLayout$LayoutParams(-1, -1));
       uFrameLayout.addView(liveRoundVie);
       KwaiImageView kwaiImageVie = new KwaiImageView(uFrameLayout.getContext());
       kwaiImageVie.setId(R.id.live_gift);
       kwaiImageVie.setScaleType(ImageView$ScaleType.CENTER_INSIDE);
       kwaiImageVie.getHierarchy().F(ContextCompat.getDrawable(p0, R.drawable.arg_RES_7f081144));
       kwaiImageVie.setLayoutParams(new FrameLayout$LayoutParams(c.b(resources, R.dimen.arg_RES_7f0705e4), c.b(resources, R.dimen.arg_RES_7f0705e4)));
       uFrameLayout.addView(kwaiImageVie);
       LiveOptLottieAnimationView liveOptLotti = new LiveOptLottieAnimationView(uFrameLayout.getContext());
       FrameLayout$LayoutParams layoutParams = new FrameLayout$LayoutParams((int)TypedValue.applyDimension(1, 50.50f, c.c(resources)), (int)TypedValue.applyDimension(1, 50.50f, c.c(resources)));
       liveOptLotti.setId(R.id.live_gift_animation_view);
       layoutParams.gravity = 17;
       liveOptLotti.setVisibility(8);
       liveOptLotti.setLayoutParams(layoutParams);
       uFrameLayout.addView(liveOptLotti);
       AppCompatImageView uAppCompatIm = new AppCompatImageView(uFrameLayout.getContext());
       layoutParams = new FrameLayout$LayoutParams(c.b(resources, 0x7f070334), c.b(resources, 0x7f070334));
       uAppCompatIm.setId(R.id.live_gift_dot_notify);
       layoutParams.gravity = 53;
       layoutParams.topMargin = c.b(resources, 0x7f07030a);
       layoutParams.rightMargin = c.b(resources, 0x7f07030a);
       uAppCompatIm.setImageResource(R.drawable.arg_RES_7f080e8a);
       uAppCompatIm.setVisibility(8);
       uAppCompatIm.setLayoutParams(layoutParams);
       uFrameLayout.addView(uAppCompatIm);
       uAppCompatIm = new AppCompatImageView(uFrameLayout.getContext());
       layoutParams = new FrameLayout$LayoutParams(c.b(resources, 0x7f070334), c.b(resources, 0x7f070334));
       uAppCompatIm.setId(R.id.live_gift_popular_rank_free_ticket_dot_notify);
       layoutParams.gravity = 53;
       layoutParams.topMargin = c.b(resources, 0x7f07030a);
       layoutParams.rightMargin = c.b(resources, 0x7f07030a);
       uAppCompatIm.setImageResource(R.drawable.arg_RES_7f080e8a);
       uAppCompatIm.setVisibility(8);
       uAppCompatIm.setLayoutParams(layoutParams);
       uFrameLayout.addView(uAppCompatIm);
       kwaiImageVie = new KwaiImageView(uFrameLayout.getContext());
       layoutParams = new FrameLayout$LayoutParams(c.b(resources, 0x7f070267), c.b(resources, 0x7f070267));
       kwaiImageVie.setId(R.id.live_gift_new_notify);
       layoutParams.gravity = 53;
       kwaiImageVie.setScaleType(ImageView$ScaleType.CENTER_CROP);
       kwaiImageVie.setVisibility(8);
       kwaiImageVie.getHierarchy().F(ContextCompat.getDrawable(p0, R.drawable.arg_RES_7f081101));
       kwaiImageVie.setLayoutParams(layoutParams);
       uFrameLayout.addView(kwaiImageVie);
       SelectShapeLinearLayout selectShapeL = new SelectShapeLinearLayout(uFrameLayout.getContext());
       FrameLayout$LayoutParams layoutParams1 = new FrameLayout$LayoutParams(c.b(resources, 0x7f0702df), c.b(resources, 0x7f070271));
       selectShapeL.setId(R.id.live_audience_gift_bottom_coin_container);
       layoutParams1.gravity = 81;
       selectShapeL.setGravity(17);
       selectShapeL.setOrientation(false);
       selectShapeL.setVisibility(8);
       XmlAttrHostImpl xmlAttrHostI = new XmlAttrHostImpl();
       xmlAttrHostI.addAttr(29, Integer.valueOf(resources.getColor(R.color.arg_RES_7f06019f)));
       XmlAttrHostImpl xmlAttrHostI1 = new XmlAttrHostImpl();
       xmlAttrHostI1.addAttr(2, Integer.valueOf(c.b(resources, R.dimen.arg_RES_7f07042c)));
       IAttrHost[] iAttrHostArr = new IAttrHost[]{xmlAttrHostI,new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),xmlAttrHostI1};
       selectShapeL.setAttrs(iAttrHostArr);
       selectShapeL.setLayoutParams(layoutParams1);
       uFrameLayout.addView(selectShapeL);
       uAppCompatIm = new AppCompatImageView(selectShapeL.getContext());
       uAppCompatIm.setId(R.id.live_audience_gift_bottom_coin_icon);
       uAppCompatIm.setImageResource(R.drawable.arg_RES_7f081474);
       uAppCompatIm.setVisibility(8);
       uAppCompatIm.setLayoutParams(new LinearLayout$LayoutParams(c.b(resources, R.dimen.arg_RES_7f07025d), c.b(resources, R.dimen.arg_RES_7f07025d)));
       selectShapeL.addView(uAppCompatIm);
       AppCompatTextView uAppCompatTe = new AppCompatTextView(selectShapeL.getContext());
       LinearLayout$LayoutParams layoutParams2 = new LinearLayout$LayoutParams(-2, -2);
       uAppCompatTe.setId(R.id.live_audience_gift_bottom_money_count);
       layoutParams2.leftMargin = c.b(resources, 0x7f0702e3);
       uAppCompatTe.setTextColor(resources.getColor(R.color.arg_RES_7f0601cb));
       uAppCompatTe.setTextSize(false, (float)c.b(resources, R.dimen.arg_RES_7f070356));
       uAppCompatTe.setLayoutParams(layoutParams2);
       selectShapeL.addView(uAppCompatTe);
       return uFrameLayout;
    }
}
