package com.kuaishou.ax2c.layouts.X2C_Smartalbum_Card_Horizontal_Item_Layout;
import com.kuaishou.ax2c.IViewCreator;
import java.lang.Object;
import android.content.Context;
import android.view.View;
import android.content.res.Resources;
import android.widget.FrameLayout;
import android.view.ViewGroup$MarginLayoutParams;
import cw9.c;
import android.view.ViewGroup$LayoutParams;
import com.yxcorp.gifshow.image.KwaiImageView;
import android.widget.FrameLayout$LayoutParams;
import android.widget.ImageView;
import android.widget.ImageView$ScaleType;
import ac.b;
import com.facebook.drawee.view.DraweeView;
import yb.a;
import android.graphics.drawable.Drawable;
import androidx.core.content.ContextCompat;
import com.facebook.drawee.generic.RoundingParams;
import com.yxcorp.widget.selector.view.SelectShapeView;
import com.kuaishou.ax2c.XmlAttrHostImpl;
import java.lang.Integer;
import com.kuaishou.ax2c.IAttrHost;
import ald.b;
import android.util.DisplayMetrics;
import android.util.TypedValue;
import com.yxcorp.widget.selector.view.SelectShapeTextView;
import android.widget.TextView;
import androidx.appcompat.widget.AppCompatTextView;
import com.kuaishou.gifshow.smartalbum.utils.TextBubbleImageView;
import android.widget.LinearLayout;
import android.widget.LinearLayout$LayoutParams;
import android.text.TextUtils$TruncateAt;
import android.graphics.Typeface;
import androidx.appcompat.widget.AppCompatImageView;

public class X2C_Smartalbum_Card_Horizontal_Item_Layout implements IViewCreator	// class@001136
{

    public void X2C_Smartalbum_Card_Horizontal_Item_Layout(){
       super();
    }
    public View createView(Context p0){
       Context uContext = p0;
       Resources resources = p0.getResources();
       FrameLayout uFrameLayout = new FrameLayout(uContext);
       uFrameLayout.setLayoutParams(new ViewGroup$MarginLayoutParams(c.b(resources, R.dimen.arg_RES_7f070c00), c.b(resources, R.dimen.arg_RES_7f070c00)));
       KwaiImageView kwaiImageVie = new KwaiImageView(uFrameLayout.getContext());
       int i = -1;
       FrameLayout$LayoutParams layoutParams = new FrameLayout$LayoutParams(i, i);
       kwaiImageVie.setId(R.id.cover_image);
       kwaiImageVie.setScaleType(ImageView$ScaleType.CENTER_CROP);
       kwaiImageVie.getHierarchy().F(ContextCompat.getDrawable(uContext, R.color.arg_RES_7f061edd));
       if (kwaiImageVie.getHierarchy().n() == null) {
          kwaiImageVie.getHierarchy().L(new RoundingParams());
       }
       kwaiImageVie.getHierarchy().n().n((float)c.b(resources, R.dimen.arg_RES_7f07042b));
       kwaiImageVie.setLayoutParams(layoutParams);
       uFrameLayout.addView(kwaiImageVie);
       SelectShapeView selectShapeV = new SelectShapeView(uFrameLayout.getContext());
       selectShapeV.setId(R.id.shadow_layer);
       XmlAttrHostImpl xmlAttrHostI = new XmlAttrHostImpl();
       xmlAttrHostI.addAttr(29, Integer.valueOf(resources.getColor(R.color.bg)));
       XmlAttrHostImpl xmlAttrHostI1 = new XmlAttrHostImpl();
       xmlAttrHostI1.addAttr(2, Integer.valueOf(c.b(resources, R.dimen.arg_RES_7f07042b)));
       IAttrHost[] iAttrHostArr = new IAttrHost[]{xmlAttrHostI,new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),xmlAttrHostI1};
       selectShapeV.setAttrs(iAttrHostArr);
       selectShapeV.setLayoutParams(new FrameLayout$LayoutParams(i, i));
       uFrameLayout.addView(selectShapeV);
       selectShapeV = new SelectShapeView(uFrameLayout.getContext());
       FrameLayout$LayoutParams layoutParams1 = new FrameLayout$LayoutParams(i, (int)TypedValue.applyDimension(1, 50.00f, c.c(resources)));
       selectShapeV.setId(R.id.shadow_layer_new);
       layoutParams1.gravity = 80;
       selectShapeV.setVisibility(8);
       xmlAttrHostI1 = new XmlAttrHostImpl();
       xmlAttrHostI1.addAttr(12, Integer.valueOf(resources.getColor(0x106000d)));
       xmlAttrHostI1.addAttr(8, Integer.valueOf(90));
       xmlAttrHostI1.addAttr(14, Integer.valueOf(resources.getColor(R.color.bg)));
       XmlAttrHostImpl xmlAttrHostI2 = new XmlAttrHostImpl();
       xmlAttrHostI2.addAttr(2, Integer.valueOf(c.b(resources, R.dimen.arg_RES_7f07042b)));
       IAttrHost[] iAttrHostArr1 = new IAttrHost[]{xmlAttrHostI1,new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),xmlAttrHostI2};
       selectShapeV.setAttrs(iAttrHostArr1);
       selectShapeV.setLayoutParams(layoutParams1);
       uFrameLayout.addView(selectShapeV);
       SelectShapeTextView selectShapeT = new SelectShapeTextView(uFrameLayout.getContext());
       layoutParams1 = new FrameLayout$LayoutParams(-2, (int)TypedValue.applyDimension(1, 17.00f, c.c(resources)));
       selectShapeT.setId(R.id.new_tag);
       layoutParams1.gravity = 51;
       layoutParams1.leftMargin = (int)TypedValue.applyDimension(1, 4.00f, c.c(resources));
       layoutParams1.topMargin = (int)TypedValue.applyDimension(1, 4.00f, c.c(resources));
       selectShapeT.setGravity(17);
       selectShapeT.setIncludeFontPadding(0);
       selectShapeT.setText(R.string.arg_RES_7f104897);
       selectShapeT.setTextColor(resources.getColor(R.color.arg_RES_7f0607e1));
       selectShapeT.setTextSize(2, 12.00f);
       selectShapeT.setVisibility(8);
       selectShapeT.setPadding((int)TypedValue.applyDimension(1, 3.00f, c.c(resources)), (int)TypedValue.applyDimension(1, 0x3f000000, c.c(resources)), (int)TypedValue.applyDimension(1, 3.00f, c.c(resources)), 0);
       XmlAttrHostImpl xmlAttrHostI3 = new XmlAttrHostImpl();
       xmlAttrHostI3.addAttr(29, Integer.valueOf(resources.getColor(R.color.arg_RES_7f060751)));
       XmlAttrHostImpl xmlAttrHostI4 = new XmlAttrHostImpl();
       xmlAttrHostI4.addAttr(2, Integer.valueOf(c.b(resources, R.dimen.arg_RES_7f070426)));
       IAttrHost[] iAttrHostArr2 = new IAttrHost[]{xmlAttrHostI3,new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),xmlAttrHostI4};
       selectShapeT.setAttrs(iAttrHostArr2);
       selectShapeT.setLayoutParams(layoutParams1);
       uFrameLayout.addView(selectShapeT);
       TextBubbleImageView textBubbleIm = new TextBubbleImageView(uFrameLayout.getContext());
       layoutParams1 = new FrameLayout$LayoutParams(-2, -2);
       textBubbleIm.setId(R.id.cover_image_with_title_iv);
       layoutParams1.gravity = 17;
       layoutParams1.leftMargin = (int)TypedValue.applyDimension(1, 10.00f, c.c(resources));
       layoutParams1.rightMargin = (int)TypedValue.applyDimension(1, 10.00f, c.c(resources));
       textBubbleIm.setLayoutParams(layoutParams1);
       uFrameLayout.addView(textBubbleIm);
       LinearLayout linearLayout = new LinearLayout(uFrameLayout.getContext());
       layoutParams1 = new FrameLayout$LayoutParams(-1, -2);
       linearLayout.setId(R.id.cover_text_title_view);
       layoutParams1.gravity = 80;
       layoutParams1.bottomMargin = (int)TypedValue.applyDimension(1, 8.00f, c.c(resources));
       linearLayout.setGravity(17);
       linearLayout.setOrientation(1);
       linearLayout.setVisibility(8);
       linearLayout.setLayoutParams(layoutParams1);
       uFrameLayout.addView(linearLayout);
       AppCompatTextView uAppCompatTe = new AppCompatTextView(linearLayout.getContext());
       uAppCompatTe.setId(R.id.cover_text_title);
       uAppCompatTe.setEllipsize(TextUtils$TruncateAt.MIDDLE);
       uAppCompatTe.setGravity(17);
       uAppCompatTe.setSingleLine(1);
       uAppCompatTe.setTextColor(resources.getColor(R.color.arg_RES_7f061ff3));
       uAppCompatTe.setTextSize(1, 14.00f);
       uAppCompatTe.setTypeface(null, 1);
       uAppCompatTe.setLayoutParams(new LinearLayout$LayoutParams(-2, (int)TypedValue.applyDimension(1, 20.00f, c.c(resources))));
       linearLayout.addView(uAppCompatTe);
       uAppCompatTe = new AppCompatTextView(linearLayout.getContext());
       LinearLayout$LayoutParams layoutParams2 = new LinearLayout$LayoutParams(-2, (int)TypedValue.applyDimension(1, 12.00f, c.c(resources)));
       uAppCompatTe.setId(R.id.cover_text_sub_title);
       layoutParams2.topMargin = (int)TypedValue.applyDimension(1, 0x3f800000, c.c(resources));
       uAppCompatTe.setEllipsize(TextUtils$TruncateAt.END);
       uAppCompatTe.setGravity(17);
       uAppCompatTe.setSingleLine(1);
       uAppCompatTe.setTextColor(resources.getColor(R.color.arg_RES_7f061ff3));
       uAppCompatTe.setTextSize(1, 9.00f);
       uAppCompatTe.setLayoutParams(layoutParams2);
       linearLayout.addView(uAppCompatTe);
       AppCompatImageView uAppCompatIm = new AppCompatImageView(uFrameLayout.getContext());
       layoutParams1 = new FrameLayout$LayoutParams(c.b(resources, 0x7f07030f), c.b(resources, 0x7f0702a4));
       uAppCompatIm.setId(R.id.top_left_label);
       layoutParams1.gravity = 0x800033;
       layoutParams1.setMarginStart(c.b(resources, R.dimen.arg_RES_7f07031b));
       layoutParams1.topMargin = c.b(resources, 0x7f07031b);
       uAppCompatIm.setImageResource(R.drawable.arg_RES_7f081b10);
       uAppCompatIm.setVisibility(8);
       uAppCompatIm.setLayoutParams(layoutParams1);
       uFrameLayout.addView(uAppCompatIm);
       return uFrameLayout;
    }
}
