package com.kuaishou.ax2c.layouts.X2C_Live_Gift_Side_Bar_Big_Layout;
import com.kuaishou.ax2c.IViewCreator;
import java.lang.Object;
import android.content.Context;
import android.view.View;
import android.content.res.Resources;
import com.kuaishou.live.common.core.basic.widget.LivePressAlphaRelativeLayout;
import android.view.ViewGroup$MarginLayoutParams;
import cw9.c;
import android.widget.RelativeLayout;
import android.view.ViewGroup$LayoutParams;
import android.widget.FrameLayout;
import android.widget.RelativeLayout$LayoutParams;
import com.yxcorp.widget.selector.view.SelectShapeView;
import android.widget.FrameLayout$LayoutParams;
import android.widget.ImageView;
import com.kuaishou.ax2c.XmlAttrHostImpl;
import java.lang.Integer;
import com.kuaishou.ax2c.IAttrHost;
import ald.b;
import com.kuaishou.live.widget.LiveLottieAnimationView;
import com.airbnb.lottie.LottieAnimationView;
import com.kuaishou.live.common.core.component.gift.update.LiveRoundViewFlipper;
import android.widget.ViewFlipper;
import com.kuaishou.live.core.basic.widget.LiveCustomViewFlipper;
import com.yxcorp.gifshow.image.KwaiImageView;
import ac.b;
import com.facebook.drawee.view.DraweeView;
import yb.a;
import android.widget.ImageView$ScaleType;
import androidx.appcompat.widget.AppCompatImageView;
import android.util.DisplayMetrics;
import android.util.TypedValue;
import android.graphics.drawable.Drawable;
import androidx.core.content.ContextCompat;
import androidx.appcompat.widget.AppCompatTextView;
import android.widget.TextView;
import android.graphics.Typeface;

public class X2C_Live_Gift_Side_Bar_Big_Layout implements IViewCreator	// class@0010e1
{

    public void X2C_Live_Gift_Side_Bar_Big_Layout(){
       super();
    }
    public View createView(Context p0){
       Context uContext = p0;
       Resources resources = p0.getResources();
       LivePressAlphaRelativeLayout livePressAlp = new LivePressAlphaRelativeLayout(uContext);
       livePressAlp.setClipChildren(false);
       livePressAlp.setGravity(17);
       livePressAlp.setLayoutParams(new ViewGroup$MarginLayoutParams(c.b(resources, R.dimen.arg_RES_7f07032a), c.b(resources, R.dimen.arg_RES_7f070319)));
       FrameLayout uFrameLayout = new FrameLayout(livePressAlp.getContext());
       RelativeLayout$LayoutParams layoutParams = new RelativeLayout$LayoutParams(c.b(resources, 0x7f07030d), c.b(resources, 0x7f07030d));
       uFrameLayout.setId(R.id.live_sidebar_item_icon_layout);
       layoutParams.topMargin = c.b(resources, 0x7f07034b);
       uFrameLayout.setClipChildren(false);
       layoutParams.addRule(14, -1);
       uFrameLayout.setLayoutParams(layoutParams);
       livePressAlp.addView(uFrameLayout);
       SelectShapeView selectShapeV = new SelectShapeView(uFrameLayout.getContext());
       FrameLayout$LayoutParams layoutParams1 = new FrameLayout$LayoutParams(c.b(resources, 0x7f07030d), c.b(resources, 0x7f07030d));
       selectShapeV.setId(R.id.live_gift_background_view);
       layoutParams1.gravity = 1;
       XmlAttrHostImpl xmlAttrHostI = new XmlAttrHostImpl();
       xmlAttrHostI.addAttr(2, Integer.valueOf(c.b(resources, R.dimen.arg_RES_7f07042c)));
       IAttrHost[] iAttrHostArr = new IAttrHost[]{new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),xmlAttrHostI};
       selectShapeV.setAttrs(iAttrHostArr);
       selectShapeV.setLayoutParams(layoutParams1);
       uFrameLayout.addView(selectShapeV);
       LiveLottieAnimationView liveLottieAn = new LiveLottieAnimationView(uFrameLayout.getContext());
       FrameLayout$LayoutParams layoutParams2 = new FrameLayout$LayoutParams(c.b(resources, 0x7f07031f), c.b(resources, 0x7f07031f));
       liveLottieAn.setId(R.id.live_gift_enhance_animation);
       layoutParams2.gravity = 17;
       liveLottieAn.setVisibility(8);
       liveLottieAn.setAutoPlay(false);
       liveLottieAn.setRepeatCount(2);
       liveLottieAn.setLayoutParams(layoutParams2);
       uFrameLayout.addView(liveLottieAn);
       LiveRoundViewFlipper liveRoundVie = new LiveRoundViewFlipper(uFrameLayout.getContext());
       FrameLayout$LayoutParams layoutParams3 = new FrameLayout$LayoutParams(c.b(resources, 0x7f07030d), c.b(resources, 0x7f07030d));
       liveRoundVie.setId(R.id.live_gift_update_flipper);
       layoutParams3.gravity = 17;
       liveRoundVie.setInAnimation(uContext, R.anim.arg_RES_7f01007c);
       liveRoundVie.setOutAnimation(uContext, R.anim.arg_RES_7f01007d);
       liveRoundVie.setVisibility(8);
       liveRoundVie.setLayoutParams(layoutParams3);
       uFrameLayout.addView(liveRoundVie);
       KwaiImageView kwaiImageVie = new KwaiImageView(uFrameLayout.getContext());
       layoutParams3 = new FrameLayout$LayoutParams(c.b(resources, 0x7f0702df), c.b(resources, 0x7f0702df));
       kwaiImageVie.setId(R.id.live_gift_sidebar_icon);
       layoutParams3.gravity = 17;
       kwaiImageVie.getHierarchy().x(false);
       kwaiImageVie.setVisibility(false);
       kwaiImageVie.setLayoutParams(layoutParams3);
       uFrameLayout.addView(kwaiImageVie);
       kwaiImageVie = new KwaiImageView(uFrameLayout.getContext());
       layoutParams3 = new FrameLayout$LayoutParams(c.b(resources, 0x7f07030d), c.b(resources, 0x7f07030d));
       kwaiImageVie.setId(R.id.live_gift_sidebar_default_icon);
       layoutParams3.gravity = 81;
       kwaiImageVie.setBackgroundResource(R.drawable.arg_RES_7f08131e);
       kwaiImageVie.setScaleType(ImageView$ScaleType.FIT_XY);
       kwaiImageVie.setVisibility(8);
       kwaiImageVie.getHierarchy().x(false);
       kwaiImageVie.setLayoutParams(layoutParams3);
       uFrameLayout.addView(kwaiImageVie);
       AppCompatImageView uAppCompatIm = new AppCompatImageView(uFrameLayout.getContext());
       FrameLayout$LayoutParams layoutParams4 = new FrameLayout$LayoutParams(c.b(resources, 0x7f070334), c.b(resources, 0x7f070334));
       uAppCompatIm.setId(R.id.live_gift_dot_notify);
       layoutParams4.gravity = 53;
       layoutParams4.topMargin = c.b(resources, 0x7f07030a);
       layoutParams4.rightMargin = c.b(resources, 0x7f07030a);
       uAppCompatIm.setImageResource(R.drawable.arg_RES_7f080e8a);
       uAppCompatIm.setVisibility(8);
       uAppCompatIm.setLayoutParams(layoutParams4);
       uFrameLayout.addView(uAppCompatIm);
       kwaiImageVie = new KwaiImageView(uFrameLayout.getContext());
       layoutParams4 = new FrameLayout$LayoutParams(c.b(resources, 0x7f0702c5), c.b(resources, 0x7f070271));
       kwaiImageVie.setId(R.id.live_gift_new_notify);
       layoutParams4.topMargin = (int)TypedValue.applyDimension(1, -4.00f, c.c(resources));
       layoutParams4.rightMargin = (int)TypedValue.applyDimension(1, -2.00f, c.c(resources));
       layoutParams4.gravity = 53;
       kwaiImageVie.setScaleType(ImageView$ScaleType.CENTER_CROP);
       kwaiImageVie.setVisibility(8);
       kwaiImageVie.getHierarchy().F(ContextCompat.getDrawable(uContext, R.drawable.arg_RES_7f081101));
       kwaiImageVie.setLayoutParams(layoutParams4);
       uFrameLayout.addView(kwaiImageVie);
       AppCompatTextView uAppCompatTe = new AppCompatTextView(livePressAlp.getContext());
       RelativeLayout$LayoutParams layoutParams5 = new RelativeLayout$LayoutParams(-2, (int)TypedValue.applyDimension(1, 16.00f, c.c(resources)));
       uAppCompatTe.setId(R.id.live_sidebar_item_text);
       layoutParams5.addRule(3, R.id.live_sidebar_item_icon_layout);
       layoutParams5.addRule(14, -1);
       layoutParams5.topMargin = (int)TypedValue.applyDimension(1, -8.00f, c.c(resources));
       uAppCompatTe.setGravity(17);
       uAppCompatTe.setShadowLayer(uAppCompatTe.getShadowRadius(), uAppCompatTe.getShadowDx(), uAppCompatTe.getShadowDy(), resources.getColor(R.color.arg_RES_7f0601e4));
       uAppCompatTe.setShadowLayer(uAppCompatTe.getShadowRadius(), 0x3f800000, uAppCompatTe.getShadowDy(), uAppCompatTe.getShadowColor());
       uAppCompatTe.setShadowLayer(uAppCompatTe.getShadowRadius(), uAppCompatTe.getShadowDx(), 0x3f800000, uAppCompatTe.getShadowColor());
       uAppCompatTe.setShadowLayer(0x3f800000, uAppCompatTe.getShadowDx(), uAppCompatTe.getShadowDy(), uAppCompatTe.getShadowColor());
       uAppCompatTe.setTextColor(resources.getColor(R.color.arg_RES_7f0620c7));
       uAppCompatTe.setTextSize(false, (float)c.b(resources, R.dimen.arg_RES_7f070271));
       uAppCompatTe.setTypeface(null, 1);
       uAppCompatTe.setVisibility(8);
       uAppCompatTe.setLayoutParams(layoutParams5);
       livePressAlp.addView(uAppCompatTe);
       return livePressAlp;
    }
}
