package com.kuaishou.ax2c.layouts.X2C_Element_Layout_Nasa_Caption;
import com.kuaishou.ax2c.IViewCreator;
import java.lang.Object;
import android.content.Context;
import android.view.View;
import android.content.res.Resources;
import androidx.constraintlayout.widget.ConstraintLayout;
import android.view.ViewGroup$MarginLayoutParams;
import android.view.ViewGroup$LayoutParams;
import android.view.ViewGroup;
import androidx.constraintlayout.widget.ConstraintLayout$LayoutParams;
import com.kwai.slide.play.detail.information.caption.CaptionScrollView;
import android.widget.ScrollView;
import com.yxcorp.gifshow.widget.textview.ClickablePressedSpanTextView;
import android.widget.FrameLayout$LayoutParams;
import android.widget.TextView;
import cw9.c;
import androidx.appcompat.widget.AppCompatTextView;
import android.widget.FrameLayout;
import android.util.DisplayMetrics;
import android.util.TypedValue;
import com.kwai.library.widget.textview.KwaiSizeAdjustableTextView;
import android.graphics.drawable.Drawable;
import com.kwai.slide.play.detail.information.caption.CaptionTextView;

public class X2C_Element_Layout_Nasa_Caption implements IViewCreator	// class@0010a6
{

    public void X2C_Element_Layout_Nasa_Caption(){
       super();
    }
    public View createView(Context p0){
       Resources resources = p0.getResources();
       ConstraintLayout uConstraintL = new ConstraintLayout(p0);
       uConstraintL.setId(R.id.element_caption_root);
       uConstraintL.setLayoutParams(new ViewGroup$MarginLayoutParams(-2, -2));
       ConstraintLayout uConstraintL1 = new ConstraintLayout(uConstraintL.getContext());
       ConstraintLayout$LayoutParams layoutParams = new ConstraintLayout$LayoutParams(-2, -2);
       uConstraintL1.setId(R.id.caption_unfold_container);
       layoutParams.d = 0;
       layoutParams.g = 0;
       uConstraintL1.setVisibility(8);
       layoutParams.h = 0;
       layoutParams.c();
       uConstraintL1.setLayoutParams(layoutParams);
       uConstraintL.addView(uConstraintL1);
       CaptionScrollView uCaptionScro = new CaptionScrollView(uConstraintL1.getContext());
       ConstraintLayout$LayoutParams layoutParams1 = new ConstraintLayout$LayoutParams(-2, -2);
       uCaptionScro.setId(R.id.caption_scroll_container_unfold);
       uCaptionScro.setFillViewport(true);
       uCaptionScro.setVerticalScrollBarEnabled(0);
       uCaptionScro.setHorizontalScrollBarEnabled(0);
       layoutParams1.d = 0;
       layoutParams1.g = 0;
       layoutParams1.h = 0;
       layoutParams1.c();
       uCaptionScro.setLayoutParams(layoutParams1);
       uConstraintL1.addView(uCaptionScro);
       ClickablePressedSpanTextView uClickablePr = new ClickablePressedSpanTextView(uCaptionScro.getContext());
       uClickablePr.setId(R.id.element_caption_label_unfold);
       uClickablePr.setClickable(true);
       uClickablePr.setIncludeFontPadding(0);
       uClickablePr.setLinksClickable(true);
       uClickablePr.setVerticalScrollBarEnabled(0);
       uClickablePr.setHorizontalScrollBarEnabled(0);
       uClickablePr.setTextColor(resources.getColor(R.color.arg_RES_7f061ff3));
       uClickablePr.setTextDirection(3);
       uClickablePr.setTextSize(0, (float)c.b(resources, R.dimen.arg_RES_7f070f71));
       uClickablePr.setLayoutParams(new FrameLayout$LayoutParams(-2, -2));
       uCaptionScro.addView(uClickablePr);
       FrameLayout uFrameLayout = new FrameLayout(uConstraintL1.getContext());
       layoutParams1 = new ConstraintLayout$LayoutParams((int)TypedValue.applyDimension(true, 0, c.c(resources)), -2);
       uFrameLayout.setId(R.id.element_caption_state_fold_touch_view);
       layoutParams1.d = 0x7f0a065b;
       layoutParams1.g = 0x7f0a065b;
       layoutParams1.i = 0x7f0a065b;
       uFrameLayout.setPadding(0, c.b(resources, R.dimen.arg_RES_7f07034b), 0, 0);
       layoutParams1.c();
       uFrameLayout.setLayoutParams(layoutParams1);
       uConstraintL1.addView(uFrameLayout);
       KwaiSizeAdjustableTextView kwaiSizeAdju = new KwaiSizeAdjustableTextView(uFrameLayout.getContext());
       FrameLayout$LayoutParams layoutParams2 = new FrameLayout$LayoutParams(-2, -2);
       kwaiSizeAdju.setId(R.id.element_caption_state_fold);
       layoutParams2.gravity = 85;
       layoutParams2.leftMargin = c.b(resources, 0x7f07028d);
       layoutParams2.rightMargin = c.b(resources, 0x7f0702ac);
       kwaiSizeAdju.setBackgroundDrawable(null);
       kwaiSizeAdju.setIncludeFontPadding(0);
       kwaiSizeAdju.setText(R.string.arg_RES_7f1004cc);
       kwaiSizeAdju.setTextColor(resources.getColor(R.color.arg_RES_7f061ff3));
       kwaiSizeAdju.setTextSize(0, (float)c.b(resources, R.dimen.arg_RES_7f070f71));
       kwaiSizeAdju.setInitTextSize(TypedValue.applyDimension(0, (float)c.b(resources, R.dimen.arg_RES_7f070f71), c.c(resources)));
       kwaiSizeAdju.setLayoutParams(layoutParams2);
       uFrameLayout.addView(kwaiSizeAdju);
       CaptionScrollView uCaptionScro1 = new CaptionScrollView(uConstraintL.getContext());
       layoutParams = new ConstraintLayout$LayoutParams(-2, -2);
       uCaptionScro1.setId(R.id.caption_scroll_container);
       uCaptionScro1.setVerticalScrollBarEnabled(0);
       uCaptionScro1.setHorizontalScrollBarEnabled(0);
       layoutParams.d = 0;
       layoutParams.g = 0;
       layoutParams.h = 0;
       layoutParams.c();
       uCaptionScro1.setLayoutParams(layoutParams);
       uConstraintL.addView(uCaptionScro1);
       CaptionTextView uCaptionText = new CaptionTextView(uCaptionScro1.getContext());
       uCaptionText.setId(R.id.element_caption_label);
       uCaptionText.setClickable(true);
       uCaptionText.setIncludeFontPadding(0);
       uCaptionText.setLinksClickable(true);
       uCaptionText.setVerticalScrollBarEnabled(0);
       uCaptionText.setHorizontalScrollBarEnabled(0);
       uCaptionText.setTextColor(resources.getColor(R.color.arg_RES_7f061ff3));
       uCaptionText.setTextDirection(3);
       uCaptionText.setTextSize(0, (float)c.b(resources, R.dimen.arg_RES_7f070e95));
       uCaptionText.setLayoutParams(new FrameLayout$LayoutParams(-2, -2));
       uCaptionScro1.addView(uCaptionText);
       return uConstraintL;
    }
}
