package com.kuaishou.ax2c.layouts.X2C_Live_Lite_Gift_Guide_Side_Bar_Item_Layout;
import com.kuaishou.ax2c.IViewCreator;
import java.lang.Object;
import android.content.Context;
import android.view.View;
import android.content.res.Resources;
import android.widget.FrameLayout;
import android.view.ViewGroup$MarginLayoutParams;
import cw9.c;
import android.view.ViewGroup$LayoutParams;
import com.yxcorp.widget.selector.view.SelectShapeView;
import android.widget.FrameLayout$LayoutParams;
import android.widget.ImageView;
import com.kuaishou.ax2c.XmlAttrHostImpl;
import java.lang.Integer;
import com.kuaishou.ax2c.IAttrHost;
import ald.b;
import com.yxcorp.gifshow.image.KwaiImageView;
import android.widget.ImageView$ScaleType;
import ac.b;
import com.facebook.drawee.view.DraweeView;
import yb.a;
import android.widget.RelativeLayout;
import android.widget.RelativeLayout$LayoutParams;
import com.kuaishou.live.common.core.component.gift.domain.giftguide.view.LiveGuideGiftAnimationView;
import android.util.DisplayMetrics;
import android.util.TypedValue;
import com.facebook.drawee.generic.RoundingParams;

public class X2C_Live_Lite_Gift_Guide_Side_Bar_Item_Layout implements IViewCreator	// class@0010f0
{

    public void X2C_Live_Lite_Gift_Guide_Side_Bar_Item_Layout(){
       super();
    }
    public View createView(Context p0){
       Resources resources = p0.getResources();
       FrameLayout uFrameLayout = new FrameLayout(p0);
       uFrameLayout.setClipChildren(false);
       uFrameLayout.setClipToPadding(false);
       uFrameLayout.setLayoutParams(new ViewGroup$MarginLayoutParams(c.b(resources, R.dimen.arg_RES_7f07032a), c.b(resources, R.dimen.arg_RES_7f070319)));
       SelectShapeView selectShapeV = new SelectShapeView(uFrameLayout.getContext());
       FrameLayout$LayoutParams layoutParams = new FrameLayout$LayoutParams(c.b(resources, 0x7f07030d), c.b(resources, 0x7f07030d));
       selectShapeV.setId(R.id.live_side_bar_guide_gift_background_view);
       layoutParams.gravity = 81;
       XmlAttrHostImpl xmlAttrHostI = new XmlAttrHostImpl();
       xmlAttrHostI.addAttr(2, Integer.valueOf(c.b(resources, R.dimen.arg_RES_7f07042c)));
       IAttrHost[] iAttrHostArr = new IAttrHost[]{new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),xmlAttrHostI};
       selectShapeV.setAttrs(iAttrHostArr);
       selectShapeV.setLayoutParams(layoutParams);
       uFrameLayout.addView(selectShapeV);
       KwaiImageView kwaiImageVie = new KwaiImageView(uFrameLayout.getContext());
       layoutParams = new FrameLayout$LayoutParams(c.b(resources, 0x7f07030d), c.b(resources, 0x7f07030d));
       kwaiImageVie.setId(R.id.live_side_bar_guide_gift_default_view);
       layoutParams.gravity = 81;
       kwaiImageVie.setBackgroundResource(R.drawable.arg_RES_7f08131e);
       kwaiImageVie.setScaleType(ImageView$ScaleType.FIT_XY);
       kwaiImageVie.setVisibility(8);
       kwaiImageVie.getHierarchy().x(false);
       kwaiImageVie.setLayoutParams(layoutParams);
       uFrameLayout.addView(kwaiImageVie);
       RelativeLayout relativeLayo = new RelativeLayout(uFrameLayout.getContext());
       layoutParams = new FrameLayout$LayoutParams(c.b(resources, 0x7f07030d), c.b(resources, 0x7f07030d));
       relativeLayo.setId(R.id.live_side_bar_guide_gift_container);
       layoutParams.gravity = 81;
       relativeLayo.setClipChildren(false);
       relativeLayo.setClipToPadding(false);
       relativeLayo.setLayoutParams(layoutParams);
       uFrameLayout.addView(relativeLayo);
       KwaiImageView kwaiImageVie1 = new KwaiImageView(relativeLayo.getContext());
       RelativeLayout$LayoutParams layoutParams1 = new RelativeLayout$LayoutParams(c.b(resources, 0x7f07030d), c.b(resources, 0x7f07030d));
       kwaiImageVie1.setId(R.id.live_side_bar_guide_gift_view);
       layoutParams1.addRule(15, -1);
       kwaiImageVie1.setScaleType(ImageView$ScaleType.FIT_XY);
       kwaiImageVie1.getHierarchy().x(false);
       kwaiImageVie1.setPadding(c.b(resources, R.dimen.arg_RES_7f07031b), c.b(resources, R.dimen.arg_RES_7f07031b), c.b(resources, R.dimen.arg_RES_7f07031b), c.b(resources, R.dimen.arg_RES_7f07031b));
       kwaiImageVie1.setLayoutParams(layoutParams1);
       relativeLayo.addView(kwaiImageVie1);
       LiveGuideGiftAnimationView liveGuideGif = new LiveGuideGiftAnimationView(relativeLayo.getContext());
       layoutParams1 = new RelativeLayout$LayoutParams(c.b(resources, 0x7f07030d), c.b(resources, 0x7f07030d));
       liveGuideGif.setId(R.id.live_side_bar_guide_gift_combo);
       layoutParams1.addRule(13, -1);
       liveGuideGif.setVisibility(8);
       liveGuideGif.setTextSize((float)(int)TypedValue.applyDimension(2, 18.00f, c.c(resources)));
       liveGuideGif.setCircleRadius((float)(int)TypedValue.applyDimension(1, 20.00f, c.c(resources)));
       liveGuideGif.setLayoutParams(layoutParams1);
       relativeLayo.addView(liveGuideGif);
       FrameLayout uFrameLayout1 = new FrameLayout(relativeLayo.getContext());
       uFrameLayout1.setClipChildren(false);
       uFrameLayout1.setClipToPadding(false);
       uFrameLayout1.setLayoutParams(new RelativeLayout$LayoutParams(-2, -2));
       relativeLayo.addView(uFrameLayout1);
       kwaiImageVie = new KwaiImageView(uFrameLayout1.getContext());
       int i = c.b(resources, R.dimen.arg_RES_7f070325);
       FrameLayout$LayoutParams layoutParams2 = new FrameLayout$LayoutParams(i, c.b(resources, 0x7f070325));
       kwaiImageVie.setId(R.id.live_side_bar_guide_gift_notice);
       kwaiImageVie.getHierarchy().L(RoundingParams.a());
       layoutParams2.gravity = 17;
       kwaiImageVie.setVisibility(8);
       kwaiImageVie.setLayoutParams(layoutParams2);
       uFrameLayout1.addView(kwaiImageVie);
       return uFrameLayout;
    }
}
