package com.kuaishou.ax2c.layouts.X2C_Ksa_Album_Fragment_Select_Container_Top;
import com.kuaishou.ax2c.IViewCreator;
import java.lang.Object;
import android.content.Context;
import android.view.View;
import android.content.res.Resources;
import android.widget.FrameLayout;
import android.view.ViewGroup$MarginLayoutParams;
import android.view.ViewGroup$LayoutParams;
import android.widget.FrameLayout$LayoutParams;
import cw9.c;
import android.widget.ImageButton;
import android.util.AttributeSet;
import android.graphics.drawable.Drawable;
import java.lang.String;
import java.lang.CharSequence;
import android.widget.ImageView$ScaleType;
import androidx.core.content.ContextCompat;
import android.content.res.ColorStateList;
import android.widget.ImageView;
import e2.d;
import com.kwai.library.widget.viewpager.tabstrip.PagerSlidingTabStrip;
import android.util.DisplayMetrics;
import android.util.TypedValue;
import android.widget.HorizontalScrollView;
import androidx.viewpager.widget.ViewPager;
import android.view.ViewGroup;
import com.kuaishou.ax2c.layouts.X2C_Ksa_Album_Select_Container;

public class X2C_Ksa_Album_Fragment_Select_Container_Top implements IViewCreator	// class@0010b0
{

    public void X2C_Ksa_Album_Fragment_Select_Container_Top(){
       super();
    }
    public View createView(Context p0){
       Resources resources = p0.getResources();
       FrameLayout uFrameLayout = new FrameLayout(p0);
       uFrameLayout.setLayoutParams(new ViewGroup$MarginLayoutParams(-1, -1));
       FrameLayout uFrameLayout1 = new FrameLayout(uFrameLayout.getContext());
       uFrameLayout1.setBackgroundResource(R.drawable.arg_RES_7f080f88);
       uFrameLayout1.setId(R.id.photo_container);
       uFrameLayout1.setLayoutParams(new FrameLayout$LayoutParams(-1, -1));
       uFrameLayout.addView(uFrameLayout1);
       FrameLayout uFrameLayout2 = new FrameLayout(uFrameLayout1.getContext());
       uFrameLayout2.setId(R.id.photo_picker_title_bar);
       uFrameLayout2.setLayoutParams(new FrameLayout$LayoutParams(-1, c.b(resources, R.dimen.arg_RES_7f070517)));
       uFrameLayout1.addView(uFrameLayout2);
       ImageButton imageButton = new ImageButton(uFrameLayout2.getContext(), null, 0);
       FrameLayout$LayoutParams layoutParams = new FrameLayout$LayoutParams(c.b(resources, 0x7f070517), c.b(resources, 0x7f070517));
       imageButton.setId(R.id.left_btn);
       layoutParams.leftMargin = c.b(resources, 0x7f0704b4);
       imageButton.setBackgroundDrawable(null);
       imageButton.setClickable(true);
       imageButton.setContentDescription(resources.getString(R.string.arg_RES_7f10189f));
       imageButton.setScaleType(ImageView$ScaleType.CENTER_INSIDE);
       imageButton.setImageResource(R.drawable.arg_RES_7f080fc6);
       d.c(imageButton, ColorStateList.valueOf(ContextCompat.getColor(p0, R.color.arg_RES_7f060b41)));
       imageButton.setLayoutParams(layoutParams);
       uFrameLayout2.addView(imageButton);
       PagerSlidingTabStrip pagerSliding = new PagerSlidingTabStrip(uFrameLayout2.getContext());
       FrameLayout$LayoutParams layoutParams1 = new FrameLayout$LayoutParams(-2, (int)TypedValue.applyDimension(true, 50.00f, c.c(resources)));
       pagerSliding.setId(R.id.tabs);
       layoutParams1.gravity = 1;
       pagerSliding.setBackgroundColor(resources.getColor(R.color.arg_RES_7f060b44));
       pagerSliding.setTextColor(R.color.arg_RES_7f060b78);
       pagerSliding.setTabPadding((int)TypedValue.applyDimension(true, 12.00f, c.c(resources)));
       pagerSliding.setUnderlineHeight((int)TypedValue.applyDimension(true, 0, c.c(resources)));
       pagerSliding.x((int)TypedValue.applyDimension(true, 5.00f, c.c(resources)));
       pagerSliding.y((int)TypedValue.applyDimension(true, 20.00f, c.c(resources)));
       pagerSliding.w((int)TypedValue.applyDimension(true, 2.00f, c.c(resources)));
       pagerSliding.setIndicatorPadding((int)TypedValue.applyDimension(true, 8.00f, c.c(resources)));
       pagerSliding.setDividerPadding((int)TypedValue.applyDimension(true, 0, c.c(resources)));
       pagerSliding.setDividerColorInt(resources.getColor(0x106000d));
       pagerSliding.setUnderlineColorInt(resources.getColor(0x106000d));
       pagerSliding.setTabTextSize(c.b(resources, R.dimen.arg_RES_7f070514));
       pagerSliding.setAverageWidth(0);
       pagerSliding.setIndicatorColorInt(resources.getColor(R.color.arg_RES_7f060b2d));
       pagerSliding.setShouldExpand(true);
       pagerSliding.setLayoutParams(layoutParams1);
       uFrameLayout2.addView(pagerSliding);
       ImageView imageView = new ImageView(uFrameLayout2.getContext());
       layoutParams1 = new FrameLayout$LayoutParams(-2, c.b(resources, 0x7f070517));
       imageView.setId(R.id.album_indicator);
       layoutParams1.leftMargin = c.b(resources, 0x7f0704ea);
       imageView.setClickable(0);
       imageView.setImageResource(R.drawable.arg_RES_7f080fbc);
       imageView.setVisibility(8);
       imageView.setLayoutParams(layoutParams1);
       uFrameLayout2.addView(imageView);
       ViewPager viewPager = new ViewPager(uFrameLayout1.getContext());
       FrameLayout$LayoutParams layoutParams2 = new FrameLayout$LayoutParams(-1, -1);
       viewPager.setId(R.id.view_pager);
       layoutParams2.topMargin = c.b(resources, 0x7f070517);
       viewPager.setLayoutParams(layoutParams2);
       uFrameLayout1.addView(viewPager);
       View view = new View(uFrameLayout1.getContext());
       layoutParams2 = new FrameLayout$LayoutParams(-1, (int)TypedValue.applyDimension(true, 0x3f800000, c.c(resources)));
       view.setId(R.id.album_list_divider);
       layoutParams2.topMargin = c.b(resources, 0x7f070517);
       view.setBackgroundColor(resources.getColor(R.color.arg_RES_7f060b2b));
       view.setVisibility(4);
       view.setLayoutParams(layoutParams2);
       uFrameLayout1.addView(view);
       FrameLayout uFrameLayout3 = new FrameLayout(uFrameLayout1.getContext());
       uFrameLayout3.setId(R.id.preview);
       uFrameLayout3.setLayoutParams(new FrameLayout$LayoutParams(-1, -1));
       uFrameLayout1.addView(uFrameLayout3);
       uFrameLayout2 = new FrameLayout(uFrameLayout3.getContext());
       uFrameLayout2.setId(R.id.preview_frame_cover);
       uFrameLayout2.setLayoutParams(new FrameLayout$LayoutParams(-1, -1));
       uFrameLayout3.addView(uFrameLayout2);
       uFrameLayout2 = new FrameLayout(uFrameLayout3.getContext());
       uFrameLayout2.setId(R.id.preview_frame);
       uFrameLayout2.setLayoutParams(new FrameLayout$LayoutParams(-1, -1));
       uFrameLayout3.addView(uFrameLayout2);
       view = new X2C_Ksa_Album_Select_Container().createView(uFrameLayout1.getContext());
       layoutParams2 = view.getLayoutParams();
       layoutParams2.gravity = 80;
       view.setLayoutParams(layoutParams2);
       uFrameLayout1.addView(view);
       uFrameLayout3 = new FrameLayout(uFrameLayout1.getContext());
       layoutParams2 = new FrameLayout$LayoutParams(-1, -1);
       uFrameLayout3.setId(R.id.album_list_container);
       layoutParams2.topMargin = (int)TypedValue.applyDimension(true, 51.00f, c.c(resources));
       uFrameLayout3.setVisibility(8);
       uFrameLayout3.setLayoutParams(layoutParams2);
       uFrameLayout1.addView(uFrameLayout3);
       uFrameLayout3 = new FrameLayout(uFrameLayout.getContext());
       uFrameLayout3.setId(R.id.preview_click_container);
       uFrameLayout3.setVisibility(8);
       uFrameLayout3.setLayoutParams(new FrameLayout$LayoutParams(-1, -1));
       uFrameLayout.addView(uFrameLayout3);
       uFrameLayout3 = new FrameLayout(uFrameLayout.getContext());
       FrameLayout$LayoutParams layoutParams3 = new FrameLayout$LayoutParams(-1, -2);
       uFrameLayout3.setId(R.id.bottom_container);
       layoutParams3.gravity = 80;
       uFrameLayout3.setVisibility(8);
       uFrameLayout3.setLayoutParams(layoutParams3);
       uFrameLayout.addView(uFrameLayout3);
       return uFrameLayout;
    }
}
