package com.kuaishou.ax2c.layouts.X2C_Cover_Editor_V3;
import com.kuaishou.ax2c.IViewCreator;
import java.lang.Object;
import android.content.Context;
import android.view.View;
import android.content.res.Resources;
import android.widget.RelativeLayout;
import android.view.ViewGroup$MarginLayoutParams;
import android.view.ViewGroup$LayoutParams;
import android.widget.LinearLayout;
import android.widget.RelativeLayout$LayoutParams;
import cw9.c;
import android.widget.LinearLayout$LayoutParams;
import androidx.appcompat.widget.AppCompatTextView;
import android.widget.TextView;
import com.yxcorp.gifshow.v3.widget.FadingEdgeContainer;
import android.widget.FrameLayout;
import androidx.recyclerview.widget.RecyclerView;
import android.widget.FrameLayout$LayoutParams;
import android.view.ViewGroup;
import com.yxcorp.gifshow.image.KwaiImageView;
import android.widget.ImageView;
import android.util.DisplayMetrics;
import android.util.TypedValue;
import androidx.appcompat.widget.AppCompatImageView;
import com.kwai.library.widget.refresh.KwaiLoadingView;
import com.kuaishou.ax2c.layouts.X2C_Import_Cover_Thumbnail_Layout;
import com.kuaishou.ax2c.layouts.X2C_Add_Import_Cover_Layout;
import com.yxcorp.gifshow.widget.RoundCornerFrameLayout;
import com.yxcorp.gifshow.v3.editor.cover.widget.HorizontalAutoFillRecyclerView;
import com.yxcorp.gifshow.widget.EditCoverSeekBar;
import android.util.AttributeSet;
import android.os.Looper;
import java.lang.Thread;
import android.widget.ProgressBar;
import java.lang.String;
import java.lang.reflect.Field;
import java.lang.Class;
import java.lang.Long;
import java.lang.Exception;
import com.yxcorp.gifshow.v3.widget.ExpandFoldHelperView;
import com.yxcorp.gifshow.widget.PassThroughEventView;

public class X2C_Cover_Editor_V3 implements IViewCreator	// class@0010a2
{

    public void X2C_Cover_Editor_V3(){
       super();
    }
    public View createView(Context p0){
       long id;
       View view1;
       ExpandFoldHelperView uExpandFoldH;
       PassThroughEventView passThroughE;
       RelativeLayout$LayoutParams layoutParams8;
       Resources resources = p0.getResources();
       RelativeLayout relativeLayo = new RelativeLayout(p0);
       int i = -1;
       int i1 = -2;
       relativeLayo.setLayoutParams(new ViewGroup$MarginLayoutParams(i, i1));
       LinearLayout linearLayout = new LinearLayout(relativeLayo.getContext());
       RelativeLayout$LayoutParams layoutParams = new RelativeLayout$LayoutParams(i, i1);
       linearLayout.setId(R.id.cover_text_library_container);
       layoutParams.addRule(12, i);
       linearLayout.setOrientation(1);
       linearLayout.setVisibility(8);
       linearLayout.setClickable(1);
       linearLayout.setFocusable(1);
       linearLayout.setElevation((float)c.b(resources, R.dimen.arg_RES_7f0702ac));
       linearLayout.setLayoutParams(layoutParams);
       relativeLayo.addView(linearLayout);
       LinearLayout linearLayout1 = new LinearLayout(relativeLayo.getContext());
       RelativeLayout$LayoutParams layoutParams1 = new RelativeLayout$LayoutParams(i, i1);
       linearLayout1.setId(R.id.fragment_root);
       layoutParams1.addRule(12, i);
       linearLayout1.setBackgroundResource(R.drawable.arg_RES_7f0801fe);
       linearLayout1.setClickable(1);
       linearLayout1.setFocusable(1);
       linearLayout1.setOrientation(1);
       linearLayout1.setPadding(0, c.b(resources, R.dimen.arg_RES_7f07029e), 0, 0);
       linearLayout1.setLayoutParams(layoutParams1);
       relativeLayo.addView(linearLayout1);
       RelativeLayout relativeLayo1 = new RelativeLayout(linearLayout1.getContext());
       LinearLayout$LayoutParams layoutParams2 = new LinearLayout$LayoutParams(i, i1);
       relativeLayo1.setId(R.id.recommend_cover_text_container);
       layoutParams2.bottomMargin = c.b(resources, 0x7f07027a);
       layoutParams2.leftMargin = c.b(resources, 0x7f07029e);
       relativeLayo1.setVisibility(8);
       relativeLayo1.setLayoutParams(layoutParams2);
       linearLayout1.addView(relativeLayo1);
       AppCompatTextView uAppCompatTe = new AppCompatTextView(relativeLayo1.getContext());
       RelativeLayout$LayoutParams layoutParams3 = new RelativeLayout$LayoutParams(i1, i1);
       uAppCompatTe.setId(R.id.recommend_cover_text_title);
       layoutParams3.addRule(9, i);
       layoutParams3.addRule(10, i);
       layoutParams3.topMargin = c.b(resources, 0x7f070329);
       uAppCompatTe.setText(R.string.arg_RES_7f104199);
       uAppCompatTe.setTextColor(resources.getColor(R.color.arg_RES_7f060624));
       uAppCompatTe.setTextSize(0, (float)c.b(resources, R.dimen.arg_RES_7f070271));
       uAppCompatTe.setLayoutParams(layoutParams3);
       relativeLayo1.addView(uAppCompatTe);
       FadingEdgeContainer uFadingEdgeC = new FadingEdgeContainer(relativeLayo1.getContext());
       layoutParams3 = new RelativeLayout$LayoutParams(i, i1);
       uFadingEdgeC.setId(R.id.fading_edge_container);
       layoutParams3.addRule(10, i);
       layoutParams3.leftMargin = c.b(resources, 0x7f07025d);
       layoutParams3.addRule(1, R.id.recommend_cover_text_title);
       uFadingEdgeC.setLayoutParams(layoutParams3);
       relativeLayo1.addView(uFadingEdgeC);
       RecyclerView recyclerView = new RecyclerView(uFadingEdgeC.getContext());
       recyclerView.setId(R.id.recommend_cover_text_recycler_view);
       recyclerView.setOverScrollMode(2);
       recyclerView.setLayoutParams(new FrameLayout$LayoutParams(i, i1));
       uFadingEdgeC.addView(recyclerView);
       relativeLayo1 = new RelativeLayout(linearLayout1.getContext());
       LinearLayout$LayoutParams layoutParams4 = new LinearLayout$LayoutParams(i, i1);
       relativeLayo1.setId(R.id.text_box);
       layoutParams4.topMargin = c.b(resources, 0x7f070283);
       relativeLayo1.setLayoutParams(layoutParams4);
       linearLayout1.addView(relativeLayo1);
       LinearLayout linearLayout2 = new LinearLayout(relativeLayo1.getContext());
       linearLayout2.setId(R.id.cover_text_library);
       linearLayout2.setVisibility(8);
       linearLayout2.setPadding(c.b(resources, R.dimen.arg_RES_7f0702ab), 0, c.b(resources, R.dimen.arg_RES_7f0702ab), 0);
       linearLayout2.setLayoutParams(new RelativeLayout$LayoutParams(c.b(resources, R.dimen.arg_RES_7f070337), c.b(resources, R.dimen.arg_RES_7f0702f8)));
       relativeLayo1.addView(linearLayout2);
       LinearLayout linearLayout3 = new LinearLayout(linearLayout2.getContext());
       linearLayout3.setGravity(1);
       linearLayout3.setOrientation(1);
       linearLayout3.setBackgroundResource(R.drawable.arg_RES_7f08066f);
       linearLayout3.setPadding(0, c.b(resources, R.dimen.arg_RES_7f07033f), 0, c.b(resources, R.dimen.arg_RES_7f070329));
       linearLayout3.setLayoutParams(new LinearLayout$LayoutParams(c.b(resources, R.dimen.arg_RES_7f0702f8), c.b(resources, R.dimen.arg_RES_7f0702f8)));
       linearLayout2.addView(linearLayout3);
       KwaiImageView kwaiImageVie = new KwaiImageView(linearLayout3.getContext());
       layoutParams2 = new LinearLayout$LayoutParams(c.b(resources, 0x7f07025d), c.b(resources, 0x7f07025d));
       kwaiImageVie.setBackgroundResource(R.drawable.arg_RES_7f081b6e);
       layoutParams2.gravity = 1;
       kwaiImageVie.setLayoutParams(layoutParams2);
       linearLayout3.addView(kwaiImageVie);
       uAppCompatTe = new AppCompatTextView(linearLayout3.getContext());
       layoutParams2 = new LinearLayout$LayoutParams(i1, i1);
       uAppCompatTe.setTextSize(0, (float)c.b(resources, R.dimen.arg_RES_7f07033f));
       uAppCompatTe.setTextAlignment(4);
       layoutParams2.gravity = 81;
       layoutParams2.topMargin = c.b(resources, 0x7f0702e3);
       uAppCompatTe.setTextColor(resources.getColor(R.color.arg_RES_7f0620c7));
       uAppCompatTe.setText(R.string.arg_RES_7f1036b7);
       uAppCompatTe.setLayoutParams(layoutParams2);
       linearLayout3.addView(uAppCompatTe);
       RecyclerView recyclerView1 = new RecyclerView(relativeLayo1.getContext());
       RelativeLayout$LayoutParams layoutParams5 = new RelativeLayout$LayoutParams(i, (int)TypedValue.applyDimension(1, 35.00f, c.c(resources)));
       recyclerView1.setId(R.id.text_gallery);
       layoutParams5.addRule(15, i);
       layoutParams5.addRule(1, R.id.cover_text_library);
       recyclerView1.setClipToPadding(0);
       recyclerView1.setPadding(c.b(resources, R.dimen.arg_RES_7f07054b), 0, c.b(resources, R.dimen.arg_RES_7f070549), 0);
       recyclerView1.setLayoutParams(layoutParams5);
       relativeLayo1.addView(recyclerView1);
       linearLayout2 = new LinearLayout(relativeLayo1.getContext());
       layoutParams5 = new RelativeLayout$LayoutParams(i1, c.b(resources, 0x7f0702fd));
       linearLayout2.setId(R.id.cover_text_load_failed);
       layoutParams5.addRule(13, i);
       linearLayout2.setGravity(16);
       linearLayout2.setOrientation(0);
       linearLayout2.setLayoutParams(layoutParams5);
       relativeLayo1.addView(linearLayout2);
       AppCompatImageView uAppCompatIm = new AppCompatImageView(linearLayout2.getContext());
       uAppCompatIm.setId(R.id.image_view);
       uAppCompatIm.setImageResource(R.drawable.arg_RES_7f0807e6);
       uAppCompatIm.setLayoutParams(new LinearLayout$LayoutParams(c.b(resources, R.dimen.arg_RES_7f0702a4), c.b(resources, R.dimen.arg_RES_7f0702a4)));
       linearLayout2.addView(uAppCompatIm);
       AppCompatTextView uAppCompatTe1 = new AppCompatTextView(linearLayout2.getContext());
       LinearLayout$LayoutParams layoutParams6 = new LinearLayout$LayoutParams(i1, i1);
       uAppCompatTe1.setId(R.id.text_view);
       layoutParams6.leftMargin = c.b(resources, 0x7f070334);
       uAppCompatTe1.setGravity(17);
       uAppCompatTe1.setText(R.string.arg_RES_7f103d52);
       uAppCompatTe1.setTextAlignment(4);
       uAppCompatTe1.setTextColor(resources.getColor(R.color.arg_RES_7f06204e));
       uAppCompatTe1.setTextSize(0, (float)c.b(resources, R.dimen.arg_RES_7f070272));
       uAppCompatTe1.setLayoutParams(layoutParams6);
       linearLayout2.addView(uAppCompatTe1);
       KwaiLoadingView kwaiLoadingV = new KwaiLoadingView(relativeLayo1.getContext());
       RelativeLayout$LayoutParams layoutParams7 = new RelativeLayout$LayoutParams(c.b(resources, 0x7f0702fd), c.b(resources, 0x7f0702fd));
       kwaiLoadingV.setId(R.id.cover_text_loading_view);
       layoutParams7.addRule(13, i);
       kwaiLoadingV.setVisibility(8);
       kwaiLoadingV.setLayoutParams(layoutParams7);
       relativeLayo1.addView(kwaiLoadingV);
       relativeLayo1 = new RelativeLayout(linearLayout1.getContext());
       layoutParams4 = new LinearLayout$LayoutParams(i1, i1);
       layoutParams4.bottomMargin = (int)TypedValue.applyDimension(1, 33.00f, c.c(resources));
       layoutParams4.topMargin = (int)TypedValue.applyDimension(1, 43.00f, c.c(resources));
       relativeLayo1.setLayoutParams(layoutParams4);
       linearLayout1.addView(relativeLayo1);
       RelativeLayout relativeLayo2 = new RelativeLayout(relativeLayo1.getContext());
       layoutParams7 = new RelativeLayout$LayoutParams(i1, i1);
       relativeLayo2.setId(R.id.import_cover_root_rl);
       int i2 = 0x7f07028d;
       layoutParams7.leftMargin = c.b(resources, i2);
       relativeLayo2.setVisibility(8);
       relativeLayo2.setLayoutParams(layoutParams7);
       relativeLayo1.addView(relativeLayo2);
       View view = new X2C_Import_Cover_Thumbnail_Layout().createView(relativeLayo2.getContext());
       view.setLayoutParams(view.getLayoutParams());
       relativeLayo2.addView(view);
       view = new X2C_Add_Import_Cover_Layout().createView(relativeLayo2.getContext());
       view.setLayoutParams(view.getLayoutParams());
       relativeLayo2.addView(view);
       relativeLayo2 = new RelativeLayout(relativeLayo1.getContext());
       layoutParams7 = new RelativeLayout$LayoutParams(i, i1);
       relativeLayo2.setId(R.id.thumb_layout);
       layoutParams7.addRule(1, R.id.import_cover_root_rl);
       relativeLayo2.setLayoutParams(layoutParams7);
       relativeLayo1.addView(relativeLayo2);
       RoundCornerFrameLayout roundCornerF = new RoundCornerFrameLayout(relativeLayo2.getContext());
       layoutParams7 = new RelativeLayout$LayoutParams(i, i1);
       layoutParams7.addRule(15, i);
       layoutParams7.leftMargin = c.b(resources, 0x7f0702a4);
       layoutParams7.rightMargin = c.b(resources, 0x7f0702a4);
       roundCornerF.setAllRadius(c.b(resources, R.dimen.arg_RES_7f070fda));
       roundCornerF.setEnableCorner(true);
       roundCornerF.setLayoutParams(layoutParams7);
       relativeLayo2.addView(roundCornerF);
       HorizontalAutoFillRecyclerView horizontalAu = new HorizontalAutoFillRecyclerView(roundCornerF.getContext());
       horizontalAu.setId(R.id.thumb_list);
       horizontalAu.setLayoutParams(new FrameLayout$LayoutParams(i, i1));
       roundCornerF.addView(horizontalAu);
       EditCoverSeekBar uEditCoverSe = new EditCoverSeekBar(relativeLayo2.getContext(), null);
       id = Looper.getMainLooper().getThread().getId();
       if (id - Thread.currentThread().getId()) {
          try{
             Field declaredFiel = ProgressBar.class.getDeclaredField("mUiThreadId");
             declaredFiel.setAccessible(true);
             declaredFiel.set(uEditCoverSe, Long.valueOf(id));
          }catch(java.lang.Exception e0){
             e0.printStackTrace();
          }
       }
    }
}
