package com.kuaishou.ax2c.layouts.X2C_Live_Lite_Layout;
import com.kuaishou.ax2c.IViewCreator;
import java.lang.Object;
import android.content.Context;
import android.view.View;
import android.content.res.Resources;
import com.kuaishou.live.lite.framework.layoutmanager.widget.LayoutManagerRootView;
import android.view.ViewGroup$MarginLayoutParams;
import android.view.ViewGroup;
import android.view.ViewGroup$LayoutParams;
import android.widget.FrameLayout;
import androidx.constraintlayout.widget.ConstraintLayout$LayoutParams;
import android.util.DisplayMetrics;
import cw9.c;
import android.util.TypedValue;
import com.kuaishou.live.lite.performance.LivePerformanceMonitorFrameLayout;
import android.widget.FrameLayout$LayoutParams;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.constraintlayout.widget.Guideline;
import android.widget.Space;

public class X2C_Live_Lite_Layout implements IViewCreator	// class@0010f4
{

    public void X2C_Live_Lite_Layout(){
       super();
    }
    public View createView(Context p0){
       Resources resources = p0.getResources();
       LayoutManagerRootView layoutManage = new LayoutManagerRootView(p0);
       layoutManage.setClipChildren(false);
       layoutManage.setLayoutParams(new ViewGroup$MarginLayoutParams(-1, -1));
       FrameLayout uFrameLayout = new FrameLayout(layoutManage.getContext());
       ConstraintLayout$LayoutParams layoutParams = new ConstraintLayout$LayoutParams((int)TypedValue.applyDimension(1, 0, c.c(resources)), (int)TypedValue.applyDimension(1, 0, c.c(resources)));
       uFrameLayout.setId(R.id.live_lite_player_card_view_container_place_holder);
       layoutParams.h = 0;
       layoutParams.d = 0;
       layoutParams.c();
       uFrameLayout.setLayoutParams(layoutParams);
       layoutManage.addView(uFrameLayout);
       LivePerformanceMonitorFrameLayout livePerforma = new LivePerformanceMonitorFrameLayout(uFrameLayout.getContext());
       FrameLayout$LayoutParams layoutParams1 = new FrameLayout$LayoutParams((int)TypedValue.applyDimension(1, 0, c.c(resources)), (int)TypedValue.applyDimension(1, 0, c.c(resources)));
       livePerforma.setId(R.id.live_lite_player_multi_chat_container_place_holder);
       layoutParams1.gravity = 51;
       livePerforma.setLayoutParams(layoutParams1);
       uFrameLayout.addView(livePerforma);
       LivePerformanceMonitorFrameLayout livePerforma1 = new LivePerformanceMonitorFrameLayout(layoutManage.getContext());
       layoutParams = new ConstraintLayout$LayoutParams((int)TypedValue.applyDimension(1, 0, c.c(resources)), (int)TypedValue.applyDimension(1, 0, c.c(resources)));
       livePerforma1.setId(R.id.pk_stage_container);
       livePerforma1.setClipChildren(false);
       layoutParams.h = 0x7f0a20db;
       layoutParams.d = 0x7f0a20db;
       layoutParams.g = 0x7f0a20db;
       layoutParams.k = 0x7f0a20db;
       layoutParams.c();
       livePerforma1.setLayoutParams(layoutParams);
       layoutManage.addView(livePerforma1);
       livePerforma1 = new LivePerformanceMonitorFrameLayout(layoutManage.getContext());
       livePerforma1.setId(R.id.player_view_mask);
       livePerforma1.setLayoutParams(new ConstraintLayout$LayoutParams(-1, -1));
       layoutManage.addView(livePerforma1);
       livePerforma1 = new LivePerformanceMonitorFrameLayout(layoutManage.getContext());
       layoutParams = new ConstraintLayout$LayoutParams(-1, -1);
       livePerforma1.setId(R.id.voice_party_content);
       layoutParams.d = 0;
       layoutParams.g = 0;
       layoutParams.h = 0;
       layoutParams.k = 0;
       layoutParams.c();
       livePerforma1.setLayoutParams(layoutParams);
       layoutManage.addView(livePerforma1);
       livePerforma1 = new LivePerformanceMonitorFrameLayout(layoutManage.getContext());
       layoutParams = new ConstraintLayout$LayoutParams((int)TypedValue.applyDimension(1, 0, c.c(resources)), (int)TypedValue.applyDimension(1, 84.00f, c.c(resources)));
       livePerforma1.setId(R.id.gift_slot_container);
       livePerforma1.setClipChildren(false);
       layoutParams.d = 0;
       layoutParams.j = 0x7f0a059e;
       layoutParams.g = 0x7f0a046b;
       layoutParams.setMarginStart(c.b(resources, R.dimen.pv));
       layoutParams.c();
       livePerforma1.setLayoutParams(layoutParams);
       layoutManage.addView(livePerforma1);
       ConstraintLayout uConstraintL = new ConstraintLayout(layoutManage.getContext());
       layoutParams = new ConstraintLayout$LayoutParams((int)TypedValue.applyDimension(1, 0, c.c(resources)), (int)TypedValue.applyDimension(1, 94.00f, c.c(resources)));
       uConstraintL.setId(R.id.bulletin_area);
       layoutParams.d = 0;
       layoutParams.j = 0x7f0a1ae4;
       layoutParams.g = 0;
       layoutParams.z = 0;
       uConstraintL.setPadding((int)TypedValue.applyDimension(1, 11.00f, c.c(resources)), false, (int)TypedValue.applyDimension(1, 10.00f, c.c(resources)), false);
       layoutParams.c();
       uConstraintL.setLayoutParams(layoutParams);
       layoutManage.addView(uConstraintL);
       livePerforma = new LivePerformanceMonitorFrameLayout(uConstraintL.getContext());
       ConstraintLayout$LayoutParams layoutParams2 = new ConstraintLayout$LayoutParams(-1, -2);
       livePerforma.setId(R.id.combo_comment_area);
       layoutParams2.h = 0;
       layoutParams2.c();
       livePerforma.setLayoutParams(layoutParams2);
       uConstraintL.addView(livePerforma);
       livePerforma = new LivePerformanceMonitorFrameLayout(uConstraintL.getContext());
       layoutParams2 = new ConstraintLayout$LayoutParams(-1, (int)TypedValue.applyDimension(1, 0, c.c(resources)));
       livePerforma.setId(R.id.comment_list_container);
       layoutParams2.i = 0x7f0a0840;
       layoutParams2.j = 0x7f0a1418;
       layoutParams2.c();
       livePerforma.setLayoutParams(layoutParams2);
       uConstraintL.addView(livePerforma);
       livePerforma = new LivePerformanceMonitorFrameLayout(uConstraintL.getContext());
       layoutParams2 = new ConstraintLayout$LayoutParams(-1, -2);
       livePerforma.setId(R.id.interactive_message_container);
       layoutParams2.j = 0x7f0a0485;
       layoutParams2.c();
       livePerforma.setLayoutParams(layoutParams2);
       uConstraintL.addView(livePerforma);
       Guideline guideline = new Guideline(uConstraintL.getContext());
       layoutParams2 = new ConstraintLayout$LayoutParams((int)TypedValue.applyDimension(1, 0, c.c(resources)), (int)TypedValue.applyDimension(1, 0, c.c(resources)));
       guideline.setId(R.id.bottom_bubble_top_guideline);
       layoutParams2.S = 0;
       layoutParams2.b = (int)TypedValue.applyDimension(1, 0, c.c(resources));
       layoutParams2.c();
       guideline.setLayoutParams(layoutParams2);
       uConstraintL.addView(guideline);
       livePerforma = new LivePerformanceMonitorFrameLayout(uConstraintL.getContext());
       ConstraintLayout$LayoutParams layoutParams3 = new ConstraintLayout$LayoutParams(-1, -2);
       livePerforma.setId(R.id.bottom_bubble);
       layoutParams3.k = 0;
       layoutParams3.c();
       livePerforma.setLayoutParams(layoutParams3);
       uConstraintL.addView(livePerforma);
       View view = new View(layoutManage.getContext());
       layoutParams = new ConstraintLayout$LayoutParams(-1, (int)TypedValue.applyDimension(1, 10.00f, c.c(resources)));
       view.setId(R.id.live_bulletin_spacing);
       layoutParams.j = 0x7f0a046b;
       layoutParams.c();
       view.setLayoutParams(layoutParams);
       layoutManage.addView(view);
       uFrameLayout = new FrameLayout(layoutManage.getContext());
       layoutParams = new ConstraintLayout$LayoutParams(-2, -2);
       uFrameLayout.setId(R.id.like_effect_container);
       uFrameLayout.setClipChildren(false);
       layoutParams.f = 0x7f0a363b;
       layoutParams.j = 0x7f0a046b;
       layoutParams.bottomMargin = (int)TypedValue.applyDimension(1, 12.00f, c.c(resources));
       layoutParams.c();
       uFrameLayout.setLayoutParams(layoutParams);
       layoutManage.addView(uFrameLayout);
       view = new View(layoutManage.getContext());
       layoutParams = new ConstraintLayout$LayoutParams(-1, (int)TypedValue.applyDimension(false, 0x3f800000, c.c(resources)));
       view.setId(R.id.layout_topbar_line);
       layoutParams.h = 0;
       layoutParams.topMargin = c.b(resources, 0x7f07033b);
       layoutParams.c();
       view.setLayoutParams(layoutParams);
       layoutManage.addView(view);
       Guideline guideline1 = new Guideline(layoutManage.getContext());
       layoutParams = new ConstraintLayout$LayoutParams(-2, -2);
       guideline1.setId(R.id.live_lite_top_navbar_guideline);
       layoutParams.S = 0;
       layoutParams.a = c.b(resources, 0x7f07033b);
       layoutParams.d = 0;
       layoutParams.h = 0;
       layoutParams.c();
       guideline1.setLayoutParams(layoutParams);
       layoutManage.addView(guideline1);
       livePerforma1 = new LivePerformanceMonitorFrameLayout(layoutManage.getContext());
       layoutParams = new ConstraintLayout$LayoutParams(-1, -2);
       livePerforma1.setId(R.id.anchor_info_container);
       layoutParams.d = 0;
       layoutParams.i = 0x7f0a20f5;
       layoutParams.f = 0x7f0a02da;
       layoutParams.topMargin = c.b(resources, 0x7f07031b);
       layoutParams.setMarginStart(c.b(resources, R.dimen.pv));
       layoutParams.setMarginEnd(c.b(resources, R.dimen.pv));
       layoutParams.c();
       livePerforma1.setLayoutParams(layoutParams);
       layoutManage.addView(livePerforma1);
       livePerforma1 = new LivePerformanceMonitorFrameLayout(layoutManage.getContext());
       layoutParams = new ConstraintLayout$LayoutParams(-1, -2);
       livePerforma1.setId(R.id.recommend_anchor_info_container);
       layoutParams.d = 0;
       layoutParams.i = 0x7f0a20f5;
       layoutParams.f = 0x7f0a02da;
       layoutParams.topMargin = c.b(resources, 0x7f07031b);
       layoutParams.setMarginStart(c.b(resources, R.dimen.pv));
       layoutParams.setMarginEnd(c.b(resources, R.dimen.pv));
       layoutParams.c();
       livePerforma1.setLayoutParams(layoutParams);
       layoutManage.addView(livePerforma1);
       livePerforma1 = new LivePerformanceMonitorFrameLayout(layoutManage.getContext());
       layoutParams = new ConstraintLayout$LayoutParams(-1, -2);
       livePerforma1.setId(R.id.temp_play_area);
       layoutParams.d = 0;
       layoutParams.g = 0;
       layoutParams.i = 0x7f0a01fc;
       livePerforma1.setClipChildren(false);
       livePerforma1.setClipToPadding(false);
       layoutParams.c();
       livePerforma1.setLayoutParams(layoutParams);
       layoutManage.addView(livePerforma1);
       livePerforma1 = new LivePerformanceMonitorFrameLayout(layoutManage.getContext());
       layoutParams = new ConstraintLayout$LayoutParams(-2, -2);
       livePerforma1.setId(R.id.live_square_entry_container);
       layoutParams.g = 0;
       layoutParams.i = 0x7f0a01fc;
       layoutParams.topMargin = c.b(resources, 0x7f070334);
       layoutParams.c();
       livePerforma1.setLayoutParams(layoutParams);
       layoutManage.addView(livePerforma1);
       livePerforma1 = new LivePerformanceMonitorFrameLayout(layoutManage.getContext());
       layoutParams = new ConstraintLayout$LayoutParams((int)TypedValue.applyDimension(1, 0, c.c(resources)), -2);
       livePerforma1.setId(R.id.comment_area_animation_container);
       layoutParams.d = 0x7f0a059e;
       layoutParams.g = 0x7f0a059e;
       layoutParams.k = 0x7f0a059e;
       livePerforma1.setPadding((int)TypedValue.applyDimension(1, 11.00f, c.c(resources)), false, (int)TypedValue.applyDimension(1, 10.00f, c.c(resources)), false);
       layoutParams.c();
       livePerforma1.setLayoutParams(layoutParams);
       layoutManage.addView(livePerforma1);
       livePerforma1 = new LivePerformanceMonitorFrameLayout(layoutManage.getContext());
       livePerforma1.setId(R.id.gift_effect_container);
       livePerforma1.setLayoutParams(new ConstraintLayout$LayoutParams(-1, -1));
       layoutManage.addView(livePerforma1);
       livePerforma1 = new LivePerformanceMonitorFrameLayout(layoutManage.getContext());
       layoutParams = new ConstraintLayout$LayoutParams(c.b(resources, 0x7f070592), -2);
       livePerforma1.setId(R.id.right_bottom_bar_container);
       layoutParams.g = 0;
       layoutParams.j = 0x7f0a16d0;
       layoutParams.bottomMargin = (int)TypedValue.applyDimension(1, 14.00f, c.c(resources));
       livePerforma1.setClipChildren(false);
       livePerforma1.setClipToPadding(false);
       layoutParams.c();
       livePerforma1.setLayoutParams(layoutParams);
       layoutManage.addView(livePerforma1);
       uConstraintL = new ConstraintLayout(layoutManage.getContext());
       layoutParams = new ConstraintLayout$LayoutParams(-1, -2);
       uConstraintL.setId(R.id.bottom_area);
       uConstraintL.setClipChildren(false);
       layoutParams.k = 0x7f0a16d0;
       layoutParams.bottomMargin = (int)TypedValue.applyDimension(1, 14.00f, c.c(resources));
       layoutParams.c();
       uConstraintL.setLayoutParams(layoutParams);
       layoutManage.addView(uConstraintL);
       livePerforma = new LivePerformanceMonitorFrameLayout(uConstraintL.getContext());
       ConstraintLayout$LayoutParams layoutParams4 = new ConstraintLayout$LayoutParams((int)TypedValue.applyDimension(1, 0, c.c(resources)), -2);
       livePerforma.setId(R.id.bottom_bar_container);
       layoutParams4.d = 0;
       layoutParams4.f = 0x7f0a0478;
       layoutParams4.k = 0;
       layoutParams4.setMarginStart(c.b(resources, R.dimen.pv));
       layoutParams4.setMarginEnd(c.b(resources, R.dimen.arg_RES_7f07025d));
       livePerforma.setClipChildren(false);
       layoutParams4.c();
       livePerforma.setLayoutParams(layoutParams4);
       uConstraintL.addView(livePerforma);
       Space space = new Space(uConstraintL.getContext());
       layoutParams4 = new ConstraintLayout$LayoutParams((int)TypedValue.applyDimension(1, 78.00f, c.c(resources)), (int)TypedValue.applyDimension(1, 0, c.c(resources)));
       space.setId(R.id.bottom_bar_guide_line);
       layoutParams4.k = 0;
       layoutParams4.s = 0;
       layoutParams4.c();
       space.setLayoutParams(layoutParams4);
       uConstraintL.addView(space);
       view = new View(layoutManage.getContext());
       layoutParams = new ConstraintLayout$LayoutParams(-1, (int)TypedValue.applyDimension(false, 0x3f800000, c.c(resources)));
       view.setId(R.id.layout_bottom_line);
       layoutParams.k = 0;
       layoutParams.c();
       view.setLayoutParams(layoutParams);
       layoutManage.addView(view);
       LivePerformanceMonitorFrameLayout livePerforma2 = new LivePerformanceMonitorFrameLayout(layoutManage.getContext());
       livePerforma2.setId(R.id.fullscreen_like_effect_container);
       livePerforma2.setLayoutParams(new ConstraintLayout$LayoutParams(-1, -1));
       layoutManage.addView(livePerforma2);
       FrameLayout uFrameLayout1 = new FrameLayout(layoutManage.getContext());
       uFrameLayout1.setId(R.id.live_lite_encourage_treasure_box_draggable_container);
       uFrameLayout1.setLayoutParams(new ConstraintLayout$LayoutParams(-1, -1));
       layoutManage.addView(uFrameLayout1);
       livePerforma2 = new LivePerformanceMonitorFrameLayout(layoutManage.getContext());
       livePerforma2.setId(R.id.lite_player_debug_info);
       livePerforma2.setLayoutParams(new ConstraintLayout$LayoutParams(-1, -1));
       layoutManage.addView(livePerforma2);
       livePerforma2 = new LivePerformanceMonitorFrameLayout(layoutManage.getContext());
       livePerforma2.setId(R.id.lite_debug_view_container);
       livePerforma2.setLayoutParams(new ConstraintLayout$LayoutParams(-1, -1));
       layoutManage.addView(livePerforma2);
       return layoutManage;
    }
}
