package com.kuaishou.ax2c.layouts.X2C_Live_Subscribe_Pendant_Item;
import com.kuaishou.ax2c.IViewCreator;
import java.lang.Object;
import android.content.Context;
import android.view.View;
import android.content.res.Resources;
import com.kuaishou.live.core.show.subscribe.pendant.LiveSubscribePendantItemView;
import android.view.ViewGroup$MarginLayoutParams;
import android.view.ViewGroup$LayoutParams;
import android.view.ViewGroup;
import com.yxcorp.gifshow.image.KwaiImageView;
import androidx.constraintlayout.widget.ConstraintLayout$LayoutParams;
import android.widget.ImageView;
import ac.b;
import com.facebook.drawee.view.DraweeView;
import yb.a;
import xb.t$b;
import com.kuaishou.live.core.show.subscribe.pendant.LiveSubScribePendantCarouselTextView;
import cw9.c;
import android.widget.TextView;
import com.yxcorp.widget.selector.view.SelectShapeRelativeLayout;
import android.widget.RelativeLayout;
import com.kuaishou.ax2c.XmlAttrHostImpl;
import java.lang.Integer;
import com.kuaishou.ax2c.IAttrHost;
import ald.b;
import androidx.appcompat.widget.AppCompatImageView;
import android.widget.RelativeLayout$LayoutParams;
import com.kuaishou.live.core.basic.widget.LiveBarrier;
import java.lang.String;
import android.graphics.drawable.Drawable;
import androidx.core.content.ContextCompat;
import androidx.appcompat.widget.LinearLayoutCompat;
import androidx.appcompat.widget.AppCompatTextView;
import androidx.appcompat.widget.LinearLayoutCompat$LayoutParams;
import java.lang.CharSequence;

public class X2C_Live_Subscribe_Pendant_Item implements IViewCreator	// class@001111
{

    public void X2C_Live_Subscribe_Pendant_Item(){
       super();
    }
    public View createView(Context p0){
       Context uContext = p0;
       Resources resources = p0.getResources();
       LiveSubscribePendantItemView liveSubscrib = new LiveSubscribePendantItemView(uContext);
       liveSubscrib.setLayoutParams(new ViewGroup$MarginLayoutParams(-1, -1));
       KwaiImageView kwaiImageVie = new KwaiImageView(liveSubscrib.getContext());
       kwaiImageVie.setId(R.id.live_subscribe_pendant_bg);
       t$b a = t$b.a;
       kwaiImageVie.getHierarchy().u(a);
       kwaiImageVie.setLayoutParams(new ConstraintLayout$LayoutParams(-1, -1));
       liveSubscrib.addView(kwaiImageVie);
       LiveSubScribePendantCarouselTextView liveSubScrib = new LiveSubScribePendantCarouselTextView(liveSubscrib.getContext());
       ConstraintLayout$LayoutParams layoutParams = new ConstraintLayout$LayoutParams(c.b(resources, 0x7f07032e), -2);
       liveSubScrib.setId(R.id.live_subscribe_pendant_date_time_text_view);
       layoutParams.bottomMargin = c.b(resources, 0x7f07031b);
       layoutParams.setMarginEnd(c.b(resources, R.dimen.arg_RES_7f0702e3));
       layoutParams.setMarginStart(c.b(resources, R.dimen.arg_RES_7f070334));
       liveSubScrib.setMaxLines(1);
       liveSubScrib.setTextColor(resources.getColor(R.color.arg_RES_7f060874));
       liveSubScrib.setTextSize(0, (float)c.b(resources, R.dimen.arg_RES_7f070356));
       layoutParams.k = 0;
       layoutParams.d = 0;
       layoutParams.f = 0x7f0a03e9;
       layoutParams.z = 0;
       layoutParams.c();
       liveSubScrib.setLayoutParams(layoutParams);
       liveSubscrib.addView(liveSubScrib);
       SelectShapeRelativeLayout selectShapeR = new SelectShapeRelativeLayout(liveSubscrib.getContext());
       layoutParams = new ConstraintLayout$LayoutParams(c.b(resources, 0x7f070283), c.b(resources, 0x7f070283));
       selectShapeR.setId(R.id.live_subscribe_pendant_close_view);
       selectShapeR.setGravity(17);
       layoutParams.g = 0;
       layoutParams.c();
       XmlAttrHostImpl xmlAttrHostI = new XmlAttrHostImpl();
       xmlAttrHostI.addAttr(29, Integer.valueOf(resources.getColor(R.color.arg_RES_7f060635)));
       XmlAttrHostImpl xmlAttrHostI1 = new XmlAttrHostImpl();
       xmlAttrHostI1.addAttr(2, Integer.valueOf(c.b(resources, R.dimen.arg_RES_7f07042c)));
       IAttrHost[] iAttrHostArr = new IAttrHost[]{xmlAttrHostI,new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),xmlAttrHostI1};
       selectShapeR.setAttrs(iAttrHostArr);
       selectShapeR.setLayoutParams(layoutParams);
       liveSubscrib.addView(selectShapeR);
       AppCompatImageView uAppCompatIm = new AppCompatImageView(selectShapeR.getContext());
       uAppCompatIm.setImageResource(R.drawable.arg_RES_7f0814b9);
       uAppCompatIm.setLayoutParams(new RelativeLayout$LayoutParams(c.b(resources, R.dimen.arg_RES_7f070271), c.b(resources, R.dimen.arg_RES_7f070271)));
       selectShapeR.addView(uAppCompatIm);
       LiveBarrier liveBarrier = new LiveBarrier(liveSubscrib.getContext());
       liveBarrier.setId(R.id.barrier);
       liveBarrier.setReferencedIds("live_subscribe_pendant_action_text_view,live_subscribe_pendant_text_view");
       liveBarrier.setLayoutParams(new ConstraintLayout$LayoutParams(-2, -2));
       liveSubscrib.addView(liveBarrier);
       selectShapeR = new SelectShapeRelativeLayout(liveSubscrib.getContext());
       layoutParams = new ConstraintLayout$LayoutParams(c.b(resources, 0x7f0702df), c.b(resources, 0x7f070295));
       selectShapeR.setId(R.id.live_subscribe_pendant_action_text_view);
       layoutParams.bottomMargin = c.b(resources, 0x7f0702e3);
       layoutParams.setMarginEnd(c.b(resources, R.dimen.arg_RES_7f0702e3));
       selectShapeR.setVisibility(8);
       layoutParams.k = 0;
       layoutParams.g = 0;
       layoutParams.c();
       XmlAttrHostImpl xmlAttrHostI2 = new XmlAttrHostImpl();
       xmlAttrHostI2.addAttr(2, Integer.valueOf(c.b(resources, R.dimen.arg_RES_7f07042b)));
       IAttrHost[] iAttrHostArr1 = new IAttrHost[]{new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),xmlAttrHostI2};
       selectShapeR.setAttrs(iAttrHostArr1);
       selectShapeR.setLayoutParams(layoutParams);
       liveSubscrib.addView(selectShapeR);
       KwaiImageView kwaiImageVie1 = new KwaiImageView(selectShapeR.getContext());
       kwaiImageVie1.setId(R.id.live_subscribe_btn_bg);
       kwaiImageVie1.getHierarchy().u(a);
       kwaiImageVie1.getHierarchy().G(ContextCompat.getDrawable(uContext, R.drawable.arg_RES_7f081489), a);
       kwaiImageVie1.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       selectShapeR.addView(kwaiImageVie1);
       LinearLayoutCompat linearLayout = new LinearLayoutCompat(liveSubscrib.getContext());
       ConstraintLayout$LayoutParams layoutParams1 = new ConstraintLayout$LayoutParams(c.b(resources, 0x7f070307), -2);
       linearLayout.setId(R.id.live_subscribe_pendant_text_view);
       layoutParams1.bottomMargin = c.b(resources, 0x7f07030a);
       layoutParams1.setMarginEnd(c.b(resources, R.dimen.arg_RES_7f0702e3));
       linearLayout.setGravity(17);
       layoutParams1.k = 0;
       layoutParams1.g = 0;
       layoutParams1.c();
       linearLayout.setLayoutParams(layoutParams1);
       liveSubscrib.addView(linearLayout);
       AppCompatTextView uAppCompatTe = new AppCompatTextView(linearLayout.getContext());
       uAppCompatTe.setId(R.id.live_subscribe_pendant_number_text_view);
       uAppCompatTe.setMaxLines(1);
       uAppCompatTe.setTextColor(resources.getColor(R.color.arg_RES_7f060626));
       uAppCompatTe.setTextSize(0, (float)c.b(resources, R.dimen.arg_RES_7f07033f));
       uAppCompatTe.setLayoutParams(new LinearLayoutCompat$LayoutParams(-2, -2));
       linearLayout.addView(uAppCompatTe);
       uAppCompatTe = new AppCompatTextView(linearLayout.getContext());
       uAppCompatTe.setText("ÒÑÔ¤Ô¼");
       uAppCompatTe.setTextColor(resources.getColor(R.color.arg_RES_7f060626));
       uAppCompatTe.setTextSize(0, (float)c.b(resources, R.dimen.arg_RES_7f070329));
       uAppCompatTe.setLayoutParams(new LinearLayoutCompat$LayoutParams(-2, -2));
       linearLayout.addView(uAppCompatTe);
       liveSubscrib.onFinishInflate();
       return liveSubscrib;
    }
}
