package com.kuaishou.ax2c.layouts.X2C_Vm_Nasa_Photo_Detail_Horizontal;
import com.kuaishou.ax2c.IViewCreator;
import java.lang.Object;
import android.content.Context;
import android.view.View;
import android.content.res.Resources;
import com.yxcorp.gifshow.detail.slidev2.widget.PressControlSpeedRelativeLayout;
import android.view.ViewGroup$MarginLayoutParams;
import android.widget.RelativeLayout;
import android.view.ViewGroup$LayoutParams;
import androidx.recyclerview.widget.SlideHorizontalAtlasPlayer;
import android.widget.RelativeLayout$LayoutParams;
import android.view.ViewGroup;
import com.kwai.library.widget.imageview.scale.PhotosScaleHelpView;
import android.widget.ImageView;
import androidx.appcompat.widget.AppCompatTextView;
import cw9.c;
import android.widget.TextView;
import com.kwai.library.slide.base.widget.SlidePlayVerticalRelativeLayout;
import com.kwai.library.slide.base.widget.SlidePlayVerticalRelativeLayout$LayoutParams;
import android.util.DisplayMetrics;
import android.util.TypedValue;
import android.widget.FrameLayout;
import android.widget.FrameLayout$LayoutParams;
import com.kuaishou.ax2c.layouts.X2C_Vm_Slide_Play_Photo_Image_Tips_Layout;
import com.kuaishou.ax2c.layouts.X2C_Nasa_Float_Controller;
import android.view.ViewStub;

public class X2C_Vm_Nasa_Photo_Detail_Horizontal implements IViewCreator	// class@00113c
{

    public void X2C_Vm_Nasa_Photo_Detail_Horizontal(){
       super();
    }
    public View createView(Context p0){
       Resources resources = p0.getResources();
       PressControlSpeedRelativeLayout pressControl = new PressControlSpeedRelativeLayout(p0);
       pressControl.setId(R.id.root);
       pressControl.setLayoutParams(new ViewGroup$MarginLayoutParams(-1, -1));
       SlideHorizontalAtlasPlayer slideHorizon = new SlideHorizontalAtlasPlayer(pressControl.getContext());
       slideHorizon.setId(R.id.autoplay_cover_view_page_style);
       slideHorizon.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       pressControl.addView(slideHorizon);
       PhotosScaleHelpView photosScaleH = new PhotosScaleHelpView(pressControl.getContext());
       photosScaleH.setId(R.id.out_mask);
       photosScaleH.setBackgroundColor(resources.getColor(R.color.arg_RES_7f062057));
       photosScaleH.setVisibility(8);
       photosScaleH.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       pressControl.addView(photosScaleH);
       AppCompatTextView uAppCompatTe = new AppCompatTextView(pressControl.getContext());
       RelativeLayout$LayoutParams layoutParams = new RelativeLayout$LayoutParams(-2, c.b(resources, 0x7f0702cc));
       uAppCompatTe.setId(R.id.atlas_position_view);
       layoutParams.addRule(21, -1);
       layoutParams.rightMargin = c.b(resources, 0x7f0702ab);
       layoutParams.topMargin = c.b(resources, 0x7f07034c);
       uAppCompatTe.setGravity(17);
       uAppCompatTe.setVisibility(8);
       uAppCompatTe.setIncludeFontPadding(false);
       uAppCompatTe.setTextColor(resources.getColor(R.color.arg_RES_7f061c32));
       uAppCompatTe.setTextSize(false, (float)c.b(resources, R.dimen.arg_RES_7f070271));
       uAppCompatTe.setPadding(c.b(resources, R.dimen.arg_RES_7f070356), c.b(resources, R.dimen.arg_RES_7f07031b), c.b(resources, R.dimen.arg_RES_7f070356), c.b(resources, R.dimen.arg_RES_7f07031b));
       uAppCompatTe.setLayoutParams(layoutParams);
       pressControl.addView(uAppCompatTe);
       SlidePlayVerticalRelativeLayout slidePlayVer = new SlidePlayVerticalRelativeLayout(pressControl.getContext());
       slidePlayVer.f(true);
       slidePlayVer.setId(R.id.slide_v2_content_layout);
       slidePlayVer.setClipChildren(false);
       slidePlayVer.setClipToPadding(false);
       slidePlayVer.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       pressControl.addView(slidePlayVer);
       View view = new View(slidePlayVer.getContext());
       view.setId(R.id.top_shadow);
       view.setVisibility(8);
       view.setBackgroundResource(R.drawable.arg_RES_7f0820f5);
       view.setLayoutParams(new SlidePlayVerticalRelativeLayout$LayoutParams(-1, (int)TypedValue.applyDimension(true, 110.00f, c.c(resources))));
       slidePlayVer.addView(view);
       view = new View(slidePlayVer.getContext());
       SlidePlayVerticalRelativeLayout$LayoutParams layoutParams1 = new SlidePlayVerticalRelativeLayout$LayoutParams(-1, c.b(resources, 0x7f0700db));
       view.setId(R.id.bottom_shadow);
       layoutParams1.topMargin = (int)TypedValue.applyDimension(true, -100.00f, c.c(resources));
       layoutParams1.addRule(6, R.id.group_information_root_layout);
       layoutParams1.addRule(12, -1);
       view.setBackgroundResource(R.drawable.arg_RES_7f082082);
       view.setLayoutParams(layoutParams1);
       slidePlayVer.addView(view);
       FrameLayout uFrameLayout = new FrameLayout(slidePlayVer.getContext());
       layoutParams1 = new SlidePlayVerticalRelativeLayout$LayoutParams(-1, (int)TypedValue.applyDimension(true, 0, c.c(resources)));
       uFrameLayout.setId(R.id.bottom_shadow_exp);
       layoutParams1.addRule(12, -1);
       layoutParams1.addRule(6, R.id.group_information_root_layout);
       layoutParams1.topMargin = (int)TypedValue.applyDimension(true, -100.00f, c.c(resources));
       uFrameLayout.setVisibility(8);
       uFrameLayout.setLayoutParams(layoutParams1);
       slidePlayVer.addView(uFrameLayout);
       View view1 = new View(uFrameLayout.getContext());
       FrameLayout$LayoutParams layoutParams2 = new FrameLayout$LayoutParams(-1, -1);
       layoutParams2.bottomMargin = c.b(resources, 0x7f070bf1);
       view1.setBackgroundResource(R.drawable.arg_RES_7f082082);
       view1.setLayoutParams(layoutParams2);
       uFrameLayout.addView(view1);
       view1 = new View(uFrameLayout.getContext());
       layoutParams2 = new FrameLayout$LayoutParams(-1, c.b(resources, 0x7f070bf1));
       layoutParams2.gravity = 80;
       view1.setBackgroundResource(R.drawable.arg_RES_7f082085);
       view1.setLayoutParams(layoutParams2);
       uFrameLayout.addView(view1);
       view = new View(slidePlayVer.getContext());
       layoutParams1 = new SlidePlayVerticalRelativeLayout$LayoutParams(-1, c.b(resources, 0x7f0700db));
       view.setId(R.id.bottom_shadow_screen_clean);
       layoutParams1.addRule(12, -1);
       view.setBackgroundResource(R.drawable.arg_RES_7f081987);
       view.setVisibility(4);
       view.setLayoutParams(layoutParams1);
       slidePlayVer.addView(view);
       view = new View(slidePlayVer.getContext());
       layoutParams1 = new SlidePlayVerticalRelativeLayout$LayoutParams(-1, c.b(resources, 0x7f0702ef));
       view.setId(R.id.atlas_screen_clean_shadow);
       layoutParams1.addRule(12, -1);
       view.setBackgroundResource(R.drawable.arg_RES_7f08018d);
       view.setVisibility(4);
       view.setLayoutParams(layoutParams1);
       slidePlayVer.addView(view);
       view = new X2C_Vm_Slide_Play_Photo_Image_Tips_Layout().createView(slidePlayVer.getContext());
       view.setId(R.id.slide_play_image_tips_content);
       view.setLayoutParams(view.getLayoutParams());
       slidePlayVer.addView(view);
       view = new X2C_Nasa_Float_Controller().createView(slidePlayVer.getContext());
       view.setLayoutParams(view.getLayoutParams());
       slidePlayVer.addView(view);
       view = new View(slidePlayVer.getContext());
       layoutParams1 = new SlidePlayVerticalRelativeLayout$LayoutParams((int)TypedValue.applyDimension(true, 40.00f, c.c(resources)), (int)TypedValue.applyDimension(true, 40.00f, c.c(resources)));
       view.setId(R.id.slide_close_atlas_btn);
       layoutParams1.addRule(9, -1);
       layoutParams1.leftMargin = (int)TypedValue.applyDimension(true, 8.00f, c.c(resources));
       layoutParams1.topMargin = (int)TypedValue.applyDimension(true, 4.00f, c.c(resources));
       view.setBackgroundResource(R.drawable.arg_RES_7f081994);
       view.setVisibility(8);
       view.setLayoutParams(layoutParams1);
       slidePlayVer.addView(view);
       ViewStub viewStub = new ViewStub(pressControl.getContext());
       viewStub.setInflatedId(-1);
       layoutParams = new RelativeLayout$LayoutParams(-1, c.b(resources, 0x7f07028e));
       viewStub.setId(R.id.detail_op_panel);
       layoutParams.addRule(12, -1);
       viewStub.setLayoutResource(R.layout.arg_RES_7f0d061b);
       viewStub.setLayoutParams(layoutParams);
       pressControl.addView(viewStub);
       ViewStub viewStub1 = new ViewStub(pressControl.getContext());
       viewStub1.setInflatedId(-1);
       viewStub1.setId(R.id.friend_slide_play_item_place_holder);
       viewStub1.setInflatedId(R.id.friend_slide_play_item_container);
       viewStub1.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       pressControl.addView(viewStub1);
       viewStub1 = new ViewStub(pressControl.getContext());
       viewStub1.setInflatedId(-1);
       viewStub1.setId(R.id.slide_dragging_shadow_layer_view_stub);
       viewStub1.setLayoutResource(R.layout.arg_RES_7f0d151c);
       viewStub1.setInflatedId(R.id.slide_dragging_shadow_layer);
       viewStub1.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       pressControl.addView(viewStub1);
       return pressControl;
    }
}
