package com.kuaishou.ax2c.layouts.X2C_Camera_Action_Bar_Magic_Banner_Layout;
import com.kuaishou.ax2c.IViewCreator;
import java.lang.Object;
import android.content.Context;
import android.view.View;
import android.content.res.Resources;
import android.widget.FrameLayout;
import androidx.constraintlayout.widget.ConstraintLayout$LayoutParams;
import android.util.DisplayMetrics;
import cw9.c;
import android.util.TypedValue;
import android.view.ViewGroup$MarginLayoutParams;
import android.view.ViewGroup$LayoutParams;
import android.widget.FrameLayout$LayoutParams;
import com.yxcorp.gifshow.image.KwaiImageView;
import android.widget.ImageView;
import android.graphics.drawable.Drawable;
import android.widget.ImageView$ScaleType;
import ac.b;
import com.facebook.drawee.view.DraweeView;
import yb.a;
import xb.t$b;
import android.widget.LinearLayout;
import android.widget.LinearLayout$LayoutParams;
import androidx.core.content.ContextCompat;
import androidx.appcompat.widget.AppCompatTextView;
import android.widget.TextView;
import androidx.appcompat.widget.AppCompatImageView;

public class X2C_Camera_Action_Bar_Magic_Banner_Layout implements IViewCreator	// class@00108e
{

    public void X2C_Camera_Action_Bar_Magic_Banner_Layout(){
       super();
    }
    public View createView(Context p0){
       Resources resources = p0.getResources();
       FrameLayout uFrameLayout = new FrameLayout(p0);
       ConstraintLayout$LayoutParams layoutParams = new ConstraintLayout$LayoutParams(-2, -2);
       uFrameLayout.setId(R.id.camera_magic_cover_layout);
       layoutParams.bottomMargin = (int)TypedValue.applyDimension(1, 14.00f, c.c(resources));
       uFrameLayout.setAlpha(0);
       uFrameLayout.setClipChildren(false);
       uFrameLayout.setVisibility(4);
       layoutParams.h = 0x7f0a0620;
       layoutParams.d = 0x7f0a0620;
       layoutParams.g = 0x7f0a0620;
       layoutParams.c();
       uFrameLayout.setLayoutParams(layoutParams);
       FrameLayout uFrameLayout1 = new FrameLayout(uFrameLayout.getContext());
       FrameLayout$LayoutParams layoutParams1 = new FrameLayout$LayoutParams(-2, -2);
       uFrameLayout1.setId(R.id.camera_magic_banner_icon_limit_container);
       layoutParams1.gravity = 81;
       uFrameLayout1.setClipChildren(1);
       uFrameLayout1.setLayoutParams(layoutParams1);
       uFrameLayout.addView(uFrameLayout1);
       KwaiImageView kwaiImageVie = new KwaiImageView(uFrameLayout1.getContext());
       FrameLayout$LayoutParams layoutParams2 = new FrameLayout$LayoutParams((int)TypedValue.applyDimension(1, 40.00f, c.c(resources)), (int)TypedValue.applyDimension(1, 40.00f, c.c(resources)));
       kwaiImageVie.setId(R.id.camera_magic_banner_icon_btn);
       layoutParams2.gravity = 81;
       kwaiImageVie.setBackgroundDrawable(null);
       kwaiImageVie.setScaleType(ImageView$ScaleType.FIT_CENTER);
       kwaiImageVie.getHierarchy().u(t$b.e);
       kwaiImageVie.setPadding((int)TypedValue.applyDimension(1, 0x3f800000, c.c(resources)), (int)TypedValue.applyDimension(1, 0x3f800000, c.c(resources)), (int)TypedValue.applyDimension(1, 0x3f800000, c.c(resources)), (int)TypedValue.applyDimension(1, 0x3f800000, c.c(resources)));
       kwaiImageVie.setLayoutParams(layoutParams2);
       uFrameLayout1.addView(kwaiImageVie);
       LinearLayout linearLayout = new LinearLayout(uFrameLayout.getContext());
       layoutParams1 = new FrameLayout$LayoutParams(-2, c.b(resources, 0x7f070283));
       linearLayout.setId(R.id.magic_face_tip_layout);
       linearLayout.setOrientation(false);
       layoutParams1.gravity = 53;
       layoutParams1.topMargin = (int)TypedValue.applyDimension(1, -3.00f, c.c(resources));
       layoutParams1.rightMargin = (int)TypedValue.applyDimension(1, -3.00f, c.c(resources));
       linearLayout.setVisibility(8);
       linearLayout.setLayoutParams(layoutParams1);
       uFrameLayout.addView(linearLayout);
       kwaiImageVie = new KwaiImageView(linearLayout.getContext());
       LinearLayout$LayoutParams layoutParams3 = new LinearLayout$LayoutParams(c.b(resources, 0x7f07025d), c.b(resources, 0x7f07025d));
       kwaiImageVie.setId(R.id.magic_face_tip_icon);
       layoutParams3.gravity = 16;
       kwaiImageVie.getHierarchy().F(ContextCompat.getDrawable(p0, R.drawable.arg_RES_7f081cee));
       kwaiImageVie.setLayoutParams(layoutParams3);
       linearLayout.addView(kwaiImageVie);
       AppCompatTextView uAppCompatTe = new AppCompatTextView(linearLayout.getContext());
       LinearLayout$LayoutParams layoutParams4 = new LinearLayout$LayoutParams(-2, -2);
       uAppCompatTe.setId(R.id.magic_face_tip_text);
       uAppCompatTe.setTextSize(false, (float)c.b(resources, R.dimen.arg_RES_7f070f87));
       layoutParams4.gravity = 16;
       layoutParams4.bottomMargin = (int)TypedValue.applyDimension(1, 0x3f000000, c.c(resources));
       uAppCompatTe.setSingleLine(1);
       uAppCompatTe.setLayoutParams(layoutParams4);
       linearLayout.addView(uAppCompatTe);
       FrameLayout uFrameLayout2 = new FrameLayout(uFrameLayout.getContext());
       uFrameLayout2.setId(R.id.camera_magic_banner_icon_sweep_light_container);
       uFrameLayout2.setClipChildren(1);
       int i = c.b(resources, R.dimen.arg_RES_7f0702ac);
       int i1 = c.b(resources, R.dimen.arg_RES_7f0702ac);
       int i2 = c.b(resources, R.dimen.arg_RES_7f0702ac);
       uFrameLayout2.setPadding(i, i1, i2, c.b(resources, R.dimen.arg_RES_7f0702ac));
       uFrameLayout2.setLayoutParams(new FrameLayout$LayoutParams(c.b(resources, R.dimen.arg_RES_7f07030d), c.b(resources, R.dimen.arg_RES_7f07030d)));
       uFrameLayout.addView(uFrameLayout2);
       AppCompatImageView uAppCompatIm = new AppCompatImageView(uFrameLayout2.getContext());
       FrameLayout$LayoutParams layoutParams5 = new FrameLayout$LayoutParams(-1, -1);
       uAppCompatIm.setId(R.id.camera_magic_banner_icon_sweep_light);
       layoutParams5.gravity = 1;
       uAppCompatIm.setVisibility(4);
       uAppCompatIm.setBackgroundResource(R.drawable.arg_RES_7f080e46);
       uAppCompatIm.setLayoutParams(layoutParams5);
       uFrameLayout2.addView(uAppCompatIm);
       return uFrameLayout;
    }
}
