package com.kuaishou.ax2c.layouts.X2C_New_Fragment_Video_Edit_Preview_Full_Screen;
import com.kuaishou.ax2c.IViewCreator;
import java.lang.Object;
import android.content.Context;
import android.view.View;
import android.content.res.Resources;
import android.widget.RelativeLayout;
import android.view.ViewGroup$MarginLayoutParams;
import android.view.ViewGroup$LayoutParams;
import com.yxcorp.gifshow.widget.PassThroughEventView;
import android.widget.RelativeLayout$LayoutParams;
import com.yxcorp.gifshow.v3.customizer.preview.EditorPreviewContainerLayout;
import android.util.DisplayMetrics;
import cw9.c;
import android.util.TypedValue;
import com.yxcorp.gifshow.widget.adv.VideoSDKPlayerView;
import androidx.appcompat.widget.AppCompatImageView;
import android.widget.ImageView;
import android.widget.ImageView$ScaleType;
import com.yxcorp.gifshow.v3.editor.cover.proportion.VideoCoverCropView;
import com.yxcorp.gifshow.v3.editor.decoration.EditDecorationContainerView;
import android.widget.AbsoluteLayout;
import com.yxcorp.gifshow.decoration.widget.DecorationContainerView;
import com.yxcorp.gifshow.v3.editor.decoration.EditDecorationContainerViewV2;
import com.yxcorp.gifshow.v3.editor.decoration.EditDecorationGuideContainer;
import android.widget.FrameLayout;
import com.yxcorp.gifshow.v3.editor.decoration.guideline.FakeFeedComponent;
import android.widget.FrameLayout$LayoutParams;
import com.kwai.library.widget.textview.SizeAdjustableTextView;
import android.widget.TextView;
import androidx.appcompat.widget.AppCompatTextView;
import com.kwai.library.widget.textview.KwaiSizeAdjustableTextView;
import android.graphics.Typeface;
import android.widget.ProgressBar;
import android.view.ContextThemeWrapper;
import android.util.AttributeSet;
import android.os.Looper;
import java.lang.Thread;
import java.lang.String;
import java.lang.reflect.Field;
import java.lang.Class;
import java.lang.Long;
import java.lang.Exception;
import android.graphics.drawable.Drawable;
import androidx.core.content.ContextCompat;
import com.kuaishou.ax2c.layouts.X2C_Music_Button_Layout;
import com.kuaishou.ax2c.layouts.X2C_New_Author_Widget_Preview;
import com.yxcorp.gifshow.widget.ExtensibleRecyclerView;
import android.view.ViewGroup;
import com.yxcorp.gifshow.v3.widget.EditPreviewPlayControlView;
import com.yxcorp.gifshow.v3.widget.EditPreviewControllerView;
import com.kwai.feature.post.api.flywheel.widget.FlyWheelFrameLayout;
import android.widget.LinearLayout;
import android.widget.LinearLayout$LayoutParams;
import android.text.TextUtils$TruncateAt;
import java.lang.CharSequence;
import android.graphics.Color;
import com.yxcorp.gifshow.v3.widget.EditorContainer;
import com.kuaishou.ax2c.layouts.X2C_Edit_Prompt_Layout;

public class X2C_New_Fragment_Video_Edit_Preview_Full_Screen implements IViewCreator	// class@00111b
{

    public void X2C_New_Fragment_Video_Edit_Preview_Full_Screen(){
       super();
    }
    public View createView(Context p0){
       long id;
       RelativeLayout$LayoutParams layoutParams2;
       ExtensibleRecyclerView uExtensibleR;
       EditPreviewPlayControlView uEditPreview;
       EditPreviewControllerView uEditPreview1;
       RelativeLayout relativeLayo1;
       FlyWheelFrameLayout uFlyWheelFra;
       RelativeLayout$LayoutParams layoutParams3;
       LinearLayout linearLayout;
       SizeAdjustableTextView sizeAdjustab1;
       SizeAdjustableTextView sizeAdjustab2;
       FrameLayout$LayoutParams layoutParams4;
       AppCompatTextView uAppCompatTe;
       EditorContainer uEditorConta;
       RelativeLayout$LayoutParams layoutParams5;
       Context uContext = p0;
       Resources resources = p0.getResources();
       RelativeLayout relativeLayo = new RelativeLayout(uContext);
       relativeLayo.setClipChildren(false);
       relativeLayo.setClipToPadding(false);
       relativeLayo.setLayoutParams(new ViewGroup$MarginLayoutParams(-1, -1));
       PassThroughEventView passThroughE = new PassThroughEventView(relativeLayo.getContext());
       passThroughE.setId(R.id.touch_view);
       passThroughE.setAlpha(0);
       passThroughE.setVisibility(false);
       passThroughE.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       relativeLayo.addView(passThroughE);
       View view = new View(relativeLayo.getContext());
       view.setVisibility(8);
       view.setId(R.id.text_player_event_view);
       view.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       relativeLayo.addView(view);
       EditorPreviewContainerLayout uEditorPrevi = new EditorPreviewContainerLayout(relativeLayo.getContext());
       RelativeLayout$LayoutParams layoutParams = new RelativeLayout$LayoutParams((int)TypedValue.applyDimension(1, 0, c.c(resources)), (int)TypedValue.applyDimension(1, 0, c.c(resources)));
       uEditorPrevi.setId(R.id.preview);
       layoutParams.addRule(10, -1);
       uEditorPrevi.setLayoutParams(layoutParams);
       relativeLayo.addView(uEditorPrevi);
       VideoSDKPlayerView videoSDKPlay = new VideoSDKPlayerView(uEditorPrevi.getContext());
       videoSDKPlay.setId(R.id.player);
       int i = 4;
       videoSDKPlay.setVisibility(i);
       videoSDKPlay.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       uEditorPrevi.addView(videoSDKPlay);
       AppCompatImageView uAppCompatIm = new AppCompatImageView(uEditorPrevi.getContext());
       uAppCompatIm.setId(R.id.import_cover_preview);
       uAppCompatIm.setScaleType(ImageView$ScaleType.FIT_CENTER);
       uAppCompatIm.setVisibility(8);
       uAppCompatIm.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       uEditorPrevi.addView(uAppCompatIm);
       VideoCoverCropView videoCoverCr = new VideoCoverCropView(uEditorPrevi.getContext());
       videoCoverCr.setId(R.id.cover_crop_select);
       videoCoverCr.setVisibility(8);
       videoCoverCr.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       uEditorPrevi.addView(videoCoverCr);
       EditDecorationContainerView uEditDecorat = new EditDecorationContainerView(uEditorPrevi.getContext());
       uEditDecorat.setId(R.id.decoration_editor_view);
       uEditDecorat.setVisibility(8);
       uEditDecorat.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       uEditorPrevi.addView(uEditDecorat);
       uEditDecorat.onFinishInflate();
       EditDecorationContainerViewV2 uEditDecorat1 = new EditDecorationContainerViewV2(uEditorPrevi.getContext());
       uEditDecorat1.setId(R.id.new_text_decoration_editor_view);
       uEditDecorat1.setVisibility(8);
       uEditDecorat1.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       uEditorPrevi.addView(uEditDecorat1);
       uEditDecorat1.onFinishInflate();
       uEditDecorat = new EditDecorationContainerView(uEditorPrevi.getContext());
       uEditDecorat.setId(R.id.cover_decoration_editor_view);
       uEditDecorat.setVisibility(8);
       uEditDecorat.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       uEditorPrevi.addView(uEditDecorat);
       uEditDecorat.onFinishInflate();
       uEditDecorat = new EditDecorationContainerView(uEditorPrevi.getContext());
       uEditDecorat.setId(R.id.lyric_decoration_editor_view);
       uEditDecorat.setVisibility(8);
       uEditDecorat.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       uEditorPrevi.addView(uEditDecorat);
       uEditDecorat.onFinishInflate();
       View view1 = new View(uEditorPrevi.getContext());
       view1.setId(R.id.frame_delete_shadow);
       view1.setBackgroundColor(resources.getColor(R.color.arg_RES_7f0618c1));
       view1.setVisibility(8);
       view1.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       uEditorPrevi.addView(view1);
       EditDecorationGuideContainer uEditDecorat2 = new EditDecorationGuideContainer(relativeLayo.getContext());
       uEditDecorat2.setId(R.id.decoration_guide_container);
       uEditDecorat2.setVisibility(8);
       uEditDecorat2.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       relativeLayo.addView(uEditDecorat2);
       FakeFeedComponent uFakeFeedCom = new FakeFeedComponent(uEditDecorat2.getContext());
       uFakeFeedCom.setId(R.id.decoration_guide_fake_feed_component);
       uFakeFeedCom.setVisibility(8);
       uFakeFeedCom.setLayoutParams(new FrameLayout$LayoutParams(-1, -1));
       uEditDecorat2.addView(uFakeFeedCom);
       uEditDecorat2.onFinishInflate();
       view = new View(relativeLayo.getContext());
       view.setVisibility(8);
       view.setId(R.id.intercept_view);
       view.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       relativeLayo.addView(view);
       SizeAdjustableTextView sizeAdjustab = new SizeAdjustableTextView(relativeLayo.getContext());
       layoutParams = new RelativeLayout$LayoutParams(-2, -2);
       sizeAdjustab.setId(R.id.text_tip);
       layoutParams.addRule(14, -1);
       layoutParams.topMargin = c.b(resources, 0x7f070273);
       sizeAdjustab.setGravity(17);
       sizeAdjustab.setMaxLines(1);
       int i1 = 0x7f061c12;
       sizeAdjustab.setShadowLayer(sizeAdjustab.getShadowRadius(), sizeAdjustab.getShadowDx(), sizeAdjustab.getShadowDy(), resources.getColor(i1));
       sizeAdjustab.setShadowLayer(sizeAdjustab.getShadowRadius(), sizeAdjustab.getShadowDx(), 0x3f800000, sizeAdjustab.getShadowColor());
       float f = 3.00f;
       sizeAdjustab.setShadowLayer(f, sizeAdjustab.getShadowDx(), sizeAdjustab.getShadowDy(), sizeAdjustab.getShadowColor());
       sizeAdjustab.setText(R.string.arg_RES_7f104c2c);
       sizeAdjustab.setTextColor(resources.getColor(R.color.arg_RES_7f0606da));
       sizeAdjustab.setTextSize(false, (float)c.b(resources, R.dimen.arg_RES_7f070295));
       sizeAdjustab.setInitTextSize(TypedValue.applyDimension(false, (float)c.b(resources, R.dimen.arg_RES_7f070295), c.c(resources)));
       Typeface typeface = null;
       sizeAdjustab.setTypeface(typeface, 1);
       sizeAdjustab.setVisibility(i);
       sizeAdjustab.setTextSizeAdjustable(false);
       sizeAdjustab.setLayoutParams(layoutParams);
       relativeLayo.addView(sizeAdjustab);
       sizeAdjustab = new SizeAdjustableTextView(relativeLayo.getContext());
       layoutParams = new RelativeLayout$LayoutParams(-2, -2);
       sizeAdjustab.setId(R.id.sticker_tip);
       layoutParams.addRule(14, -1);
       layoutParams.topMargin = c.b(resources, 0x7f070273);
       sizeAdjustab.setGravity(17);
       sizeAdjustab.setMaxLines(1);
       sizeAdjustab.setShadowLayer(sizeAdjustab.getShadowRadius(), sizeAdjustab.getShadowDx(), sizeAdjustab.getShadowDy(), resources.getColor(i1));
       sizeAdjustab.setShadowLayer(sizeAdjustab.getShadowRadius(), sizeAdjustab.getShadowDx(), 0x3f800000, sizeAdjustab.getShadowColor());
       sizeAdjustab.setShadowLayer(f, sizeAdjustab.getShadowDx(), sizeAdjustab.getShadowDy(), sizeAdjustab.getShadowColor());
       sizeAdjustab.setText(R.string.arg_RES_7f104aaa);
       sizeAdjustab.setTextColor(resources.getColor(R.color.arg_RES_7f0606da));
       sizeAdjustab.setTextSize(false, (float)c.b(resources, R.dimen.arg_RES_7f070295));
       sizeAdjustab.setInitTextSize(TypedValue.applyDimension(false, (float)c.b(resources, R.dimen.arg_RES_7f070295), c.c(resources)));
       sizeAdjustab.setTypeface(typeface, 1);
       sizeAdjustab.setVisibility(i);
       sizeAdjustab.setTextSizeAdjustable(false);
       sizeAdjustab.setLayoutParams(layoutParams);
       relativeLayo.addView(sizeAdjustab);
       sizeAdjustab = new SizeAdjustableTextView(relativeLayo.getContext());
       RelativeLayout$LayoutParams layoutParams1 = new RelativeLayout$LayoutParams(-2, -2);
       sizeAdjustab.setId(R.id.subtitle_tip);
       layoutParams1.addRule(14, -1);
       layoutParams1.topMargin = c.b(resources, 0x7f070273);
       sizeAdjustab.setGravity(17);
       sizeAdjustab.setMaxLines(1);
       sizeAdjustab.setShadowLayer(sizeAdjustab.getShadowRadius(), sizeAdjustab.getShadowDx(), sizeAdjustab.getShadowDy(), resources.getColor(i1));
       sizeAdjustab.setShadowLayer(sizeAdjustab.getShadowRadius(), sizeAdjustab.getShadowDx(), 0x3f800000, sizeAdjustab.getShadowColor());
       sizeAdjustab.setShadowLayer(f, sizeAdjustab.getShadowDx(), sizeAdjustab.getShadowDy(), sizeAdjustab.getShadowColor());
       sizeAdjustab.setText(R.string.arg_RES_7f104b1a);
       sizeAdjustab.setTextColor(resources.getColor(R.color.arg_RES_7f0606da));
       sizeAdjustab.setTextSize(false, (float)c.b(resources, R.dimen.arg_RES_7f070295));
       sizeAdjustab.setInitTextSize(TypedValue.applyDimension(false, (float)c.b(resources, R.dimen.arg_RES_7f070295), c.c(resources)));
       sizeAdjustab.setTypeface(typeface, 1);
       sizeAdjustab.setVisibility(i);
       sizeAdjustab.setTextSizeAdjustable(false);
       sizeAdjustab.setLayoutParams(layoutParams1);
       relativeLayo.addView(sizeAdjustab);
       sizeAdjustab = new SizeAdjustableTextView(relativeLayo.getContext());
       layoutParams1 = new RelativeLayout$LayoutParams(-2, -2);
       sizeAdjustab.setId(R.id.text_continue_play_tip);
       layoutParams1.addRule(14, -1);
       layoutParams1.topMargin = c.b(resources, 0x7f070273);
       sizeAdjustab.setGravity(17);
       sizeAdjustab.setMaxLines(1);
       sizeAdjustab.setShadowLayer(sizeAdjustab.getShadowRadius(), sizeAdjustab.getShadowDx(), sizeAdjustab.getShadowDy(), resources.getColor(i1));
       sizeAdjustab.setShadowLayer(sizeAdjustab.getShadowRadius(), sizeAdjustab.getShadowDx(), 0x3f800000, sizeAdjustab.getShadowColor());
       sizeAdjustab.setShadowLayer(f, sizeAdjustab.getShadowDx(), sizeAdjustab.getShadowDy(), sizeAdjustab.getShadowColor());
       sizeAdjustab.setText(R.string.arg_RES_7f104c31);
       sizeAdjustab.setTextColor(resources.getColor(R.color.arg_RES_7f0606da));
       sizeAdjustab.setTextSize(false, (float)c.b(resources, R.dimen.arg_RES_7f070295));
       sizeAdjustab.setInitTextSize(TypedValue.applyDimension(false, (float)c.b(resources, R.dimen.arg_RES_7f070295), c.c(resources)));
       sizeAdjustab.setTypeface(typeface, 1);
       sizeAdjustab.setVisibility(i);
       sizeAdjustab.setTextSizeAdjustable(false);
       sizeAdjustab.setLayoutParams(layoutParams1);
       relativeLayo.addView(sizeAdjustab);
       AppCompatImageView uAppCompatIm1 = new AppCompatImageView(relativeLayo.getContext());
       uAppCompatIm1.setScaleType(ImageView$ScaleType.FIT_XY);
       uAppCompatIm1.setVisibility(8);
       uAppCompatIm1.setLayoutParams(new RelativeLayout$LayoutParams((int)TypedValue.applyDimension(1, 0, c.c(resources)), (int)TypedValue.applyDimension(1, 0, c.c(resources))));
       relativeLayo.addView(uAppCompatIm1);
       FrameLayout uFrameLayout = new FrameLayout(relativeLayo.getContext());
       uFrameLayout.setId(R.id.extra_component_container);
       uFrameLayout.setFocusable(false);
       uFrameLayout.setClickable(false);
       uFrameLayout.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       relativeLayo.addView(uFrameLayout);
       ProgressBar progressBar = new ProgressBar(new ContextThemeWrapper(relativeLayo.getContext(), 0x7f110414), typeface, false);
       id = Looper.getMainLooper().getThread().getId();
       if (id - Thread.currentThread().getId()) {
          try{
             Field declaredFiel = ProgressBar.class.getDeclaredField("mUiThreadId");
             declaredFiel.setAccessible(1);
             declaredFiel.set(progressBar, Long.valueOf(id));
          }catch(java.lang.Exception e0){
             e0.printStackTrace();
          }
       }
    }
}
