package com.kuaishou.ax2c.layouts.X2C_Smartalbum_Horizontal_Cardlist_Fragment;
import com.kuaishou.ax2c.IViewCreator;
import java.lang.Object;
import android.content.Context;
import android.view.View;
import android.content.res.Resources;
import android.widget.FrameLayout;
import android.view.ViewGroup$MarginLayoutParams;
import cw9.c;
import android.view.ViewGroup$LayoutParams;
import android.widget.FrameLayout$LayoutParams;
import android.util.DisplayMetrics;
import android.util.TypedValue;
import com.kuaishou.gifshow.smartalbum.ui.horizontal.CollapsedSmartAlbumView;
import android.widget.LinearLayout;
import androidx.recyclerview.widget.RecyclerView;
import android.view.ViewGroup;
import androidx.appcompat.widget.AppCompatImageView;
import android.widget.ImageView;
import android.widget.ImageView$ScaleType;
import com.yxcorp.widget.selector.view.SelectShapeTextView;
import android.widget.TextView;
import androidx.appcompat.widget.AppCompatTextView;
import com.kuaishou.ax2c.XmlAttrHostImpl;
import java.lang.Integer;
import com.kuaishou.ax2c.IAttrHost;
import ald.b;
import com.yxcorp.widget.selector.view.SelectShapeImageView;

public class X2C_Smartalbum_Horizontal_Cardlist_Fragment implements IViewCreator	// class@001137
{

    public void X2C_Smartalbum_Horizontal_Cardlist_Fragment(){
       super();
    }
    public View createView(Context p0){
       Resources resources = p0.getResources();
       FrameLayout uFrameLayout = new FrameLayout(p0);
       uFrameLayout.setBackgroundResource(R.drawable.arg_RES_7f08210d);
       uFrameLayout.setLayoutParams(new ViewGroup$MarginLayoutParams(-1, c.b(resources, R.dimen.arg_RES_7f07008a)));
       View view = new View(uFrameLayout.getContext());
       FrameLayout$LayoutParams layoutParams = new FrameLayout$LayoutParams((int)TypedValue.applyDimension(1, 112.00f, c.c(resources)), (int)TypedValue.applyDimension(1, 50.00f, c.c(resources)));
       layoutParams.gravity = 0x800035;
       layoutParams.setMarginEnd((int)TypedValue.applyDimension(1, 0x42f00000, c.c(resources)));
       view.setBackgroundResource(R.drawable.arg_RES_7f08210f);
       view.setLayoutParams(layoutParams);
       uFrameLayout.addView(view);
       CollapsedSmartAlbumView uCollapsedSm = new CollapsedSmartAlbumView(uFrameLayout.getContext());
       layoutParams = new FrameLayout$LayoutParams(-2, c.b(resources, 0x7f0702e8));
       uCollapsedSm.setId(R.id.collapse_smart_album);
       layoutParams.gravity = 0x800035;
       layoutParams.topMargin = (int)TypedValue.applyDimension(1, 10.00f, c.c(resources));
       uCollapsedSm.setAlpha(0);
       uCollapsedSm.setOrientation(0);
       uCollapsedSm.setPadding(0, 0, (int)TypedValue.applyDimension(1, 52.00f, c.c(resources)), 0);
       uCollapsedSm.setLayoutParams(layoutParams);
       uFrameLayout.addView(uCollapsedSm);
       RecyclerView recyclerView = new RecyclerView(uFrameLayout.getContext());
       layoutParams = new FrameLayout$LayoutParams(-1, c.b(resources, 0x7f070c00));
       recyclerView.setId(R.id.album_list_recyclerview);
       layoutParams.gravity = 0x800035;
       layoutParams.topMargin = c.b(resources, 0x7f07008c);
       recyclerView.setClipToPadding(0);
       recyclerView.setVerticalScrollBarEnabled(0);
       recyclerView.setHorizontalScrollBarEnabled(0);
       recyclerView.setTag("album_animation_album_card_list");
       recyclerView.setPadding(c.b(resources, R.dimen.arg_RES_7f07025d), 0, c.b(resources, R.dimen.arg_RES_7f070549), 0);
       recyclerView.setLayoutParams(layoutParams);
       uFrameLayout.addView(recyclerView);
       AppCompatImageView uAppCompatIm = new AppCompatImageView(uFrameLayout.getContext());
       layoutParams = new FrameLayout$LayoutParams(-2, (int)TypedValue.applyDimension(1, 26.00f, c.c(resources)));
       uAppCompatIm.setId(R.id.album_list_title_tv);
       layoutParams.gravity = 0x800033;
       layoutParams.setMarginStart(c.b(resources, R.dimen.arg_RES_7f07054b));
       layoutParams.topMargin = (int)TypedValue.applyDimension(1, 12.00f, c.c(resources));
       uAppCompatIm.setClickable(0);
       uAppCompatIm.setScaleType(ImageView$ScaleType.FIT_START);
       uAppCompatIm.setImageResource(R.drawable.arg_RES_7f082110);
       uAppCompatIm.setLayoutParams(layoutParams);
       uFrameLayout.addView(uAppCompatIm);
       SelectShapeTextView selectShapeT = new SelectShapeTextView(uFrameLayout.getContext());
       layoutParams = new FrameLayout$LayoutParams((int)TypedValue.applyDimension(1, 66.00f, c.c(resources)), (int)TypedValue.applyDimension(1, 24.00f, c.c(resources)));
       selectShapeT.setId(R.id.album_cardlist_more);
       layoutParams.gravity = 0x800035;
       layoutParams.setMarginEnd((int)TypedValue.applyDimension(1, 59.00f, c.c(resources)));
       layoutParams.topMargin = (int)TypedValue.applyDimension(1, 13.00f, c.c(resources));
       selectShapeT.setGravity(17);
       selectShapeT.setText(R.string.arg_RES_7f100526);
       selectShapeT.setTextColor(resources.getColor(R.color.arg_RES_7f0618cc));
       selectShapeT.setTextSize(1, 12.00f);
       XmlAttrHostImpl xmlAttrHostI = new XmlAttrHostImpl();
       xmlAttrHostI.addAttr(30, Integer.valueOf(resources.getColor(R.color.arg_RES_7f0618cb)));
       xmlAttrHostI.addAttr(34, Integer.valueOf((int)TypedValue.applyDimension(1, 0x3f800000, c.c(resources))));
       XmlAttrHostImpl xmlAttrHostI1 = new XmlAttrHostImpl();
       xmlAttrHostI1.addAttr(2, Integer.valueOf(c.b(resources, R.dimen.arg_RES_7f07042c)));
       IAttrHost[] iAttrHostArr = new IAttrHost[]{xmlAttrHostI,new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),xmlAttrHostI1};
       selectShapeT.setAttrs(iAttrHostArr);
       selectShapeT.setLayoutParams(layoutParams);
       uFrameLayout.addView(selectShapeT);
       SelectShapeImageView selectShapeI = new SelectShapeImageView(uFrameLayout.getContext());
       layoutParams = new FrameLayout$LayoutParams((int)TypedValue.applyDimension(1, 24.00f, c.c(resources)), (int)TypedValue.applyDimension(1, 24.00f, c.c(resources)));
       selectShapeI.setId(R.id.album_cardlist_arrow);
       layoutParams.gravity = 0x800035;
       layoutParams.setMarginEnd(c.b(resources, R.dimen.arg_RES_7f0702ab));
       layoutParams.topMargin = c.b(resources, 0x7f07027a);
       selectShapeI.setScaleType(ImageView$ScaleType.CENTER_INSIDE);
       selectShapeI.setImageResource(R.drawable.arg_RES_7f08210e);
       XmlAttrHostImpl xmlAttrHostI2 = new XmlAttrHostImpl();
       xmlAttrHostI2.addAttr(30, Integer.valueOf(resources.getColor(R.color.arg_RES_7f0618cb)));
       xmlAttrHostI2.addAttr(34, Integer.valueOf((int)TypedValue.applyDimension(1, 0x3f800000, c.c(resources))));
       XmlAttrHostImpl xmlAttrHostI3 = new XmlAttrHostImpl();
       xmlAttrHostI3.addAttr(2, Integer.valueOf(c.b(resources, R.dimen.arg_RES_7f07042c)));
       IAttrHost[] iAttrHostArr1 = new IAttrHost[]{xmlAttrHostI2,new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),xmlAttrHostI3};
       selectShapeI.setAttrs(iAttrHostArr1);
       selectShapeI.setLayoutParams(layoutParams);
       uFrameLayout.addView(selectShapeI);
       AppCompatTextView uAppCompatTe = new AppCompatTextView(uFrameLayout.getContext());
       layoutParams = new FrameLayout$LayoutParams(-2, -2);
       uAppCompatTe.setId(R.id.album_new_count_tip);
       layoutParams.gravity = 1;
       layoutParams.topMargin = c.b(resources, 0x7f07034b);
       uAppCompatTe.setBackgroundResource(R.drawable.arg_RES_7f082109);
       uAppCompatTe.setTextColor(resources.getColor(R.color.arg_RES_7f060751));
       uAppCompatTe.setTextSize(2, 14.00f);
       uAppCompatTe.setVisibility(8);
       uAppCompatTe.setLayoutParams(layoutParams);
       uFrameLayout.addView(uAppCompatTe);
       return uFrameLayout;
    }
}
