package com.kuaishou.ax2c.layouts.X2C_Live_Play_Top_Bar_Popup_Head;
import com.kuaishou.ax2c.IViewCreator;
import java.lang.Object;
import android.content.Context;
import android.view.View;
import android.content.res.Resources;
import android.widget.LinearLayout;
import android.widget.RelativeLayout$LayoutParams;
import android.view.ViewGroup$LayoutParams;
import android.view.ViewStub;
import android.widget.LinearLayout$LayoutParams;
import android.util.DisplayMetrics;
import cw9.c;
import android.util.TypedValue;
import android.widget.RelativeLayout;
import com.kuaishou.ax2c.layouts.X2C_Live_Play_Top_Bar_Popup_Head_Right_Container_Layout;
import com.yxcorp.widget.selector.view.SelectShapeView;
import android.widget.ImageView;
import androidx.appcompat.widget.AppCompatImageView;
import com.kuaishou.ax2c.XmlAttrHostImpl;
import com.kuaishou.ax2c.IAttrHost;
import ald.b;
import android.widget.FrameLayout;
import android.widget.FrameLayout$LayoutParams;
import com.yxcorp.gifshow.image.KwaiImageView;
import com.facebook.drawee.view.SimpleDraweeView;
import com.kwai.library.widget.textview.StrokedTextView;
import android.widget.TextView;
import androidx.appcompat.widget.AppCompatTextView;
import android.graphics.Typeface;
import com.kuaishou.live.core.basic.widget.LiveTextView;
import android.text.TextUtils$TruncateAt;
import android.graphics.drawable.Drawable;
import androidx.core.content.ContextCompat;
import com.kuaishou.live.common.core.basic.widget.LiveViewFlipper;
import android.widget.ViewFlipper;
import com.kuaishou.ax2c.layouts.X2C_Live_Top_Bar_Like_Layout;
import com.kuaishou.ax2c.layouts.X2C_Live_Top_Bar_Anchor_Avatar_Container_Layout;
import com.yxcorp.widget.selector.view.SelectShapeTextView;
import java.lang.Integer;

public class X2C_Live_Play_Top_Bar_Popup_Head implements IViewCreator	// class@00110e
{

    public void X2C_Live_Play_Top_Bar_Popup_Head(){
       super();
    }
    public View createView(Context p0){
       Context uContext = p0;
       Resources resources = p0.getResources();
       LinearLayout linearLayout = new LinearLayout(uContext);
       RelativeLayout$LayoutParams layoutParams = new RelativeLayout$LayoutParams(-1, -2);
       linearLayout.setId(R.id.top_bar);
       layoutParams.addRule(10, -1);
       linearLayout.setClipChildren(false);
       linearLayout.setGravity(16);
       linearLayout.setVisibility(4);
       linearLayout.setOrientation(1);
       linearLayout.setLayoutParams(layoutParams);
       ViewStub viewStub = new ViewStub(linearLayout.getContext());
       viewStub.setInflatedId(-1);
       viewStub.setId(R.id.live_landscape_status_bar_viewstub);
       viewStub.setLayoutResource(R.layout.arg_RES_7f0d0c43);
       viewStub.setLayoutParams(new LinearLayout$LayoutParams(-1, (int)TypedValue.applyDimension(1, 20.00f, c.c(resources))));
       linearLayout.addView(viewStub);
       RelativeLayout relativeLayo = new RelativeLayout(linearLayout.getContext());
       LinearLayout$LayoutParams layoutParams1 = new LinearLayout$LayoutParams(-1, -2);
       layoutParams1.rightMargin = c.b(resources, 0x7f07025d);
       relativeLayo.setClipChildren(false);
       relativeLayo.setGravity(16);
       relativeLayo.setLayoutParams(layoutParams1);
       linearLayout.addView(relativeLayo);
       ViewStub viewStub1 = new ViewStub(relativeLayo.getContext());
       viewStub1.setInflatedId(-1);
       RelativeLayout$LayoutParams layoutParams2 = new RelativeLayout$LayoutParams(-2, -2);
       viewStub1.setId(R.id.live_square_source_back_entrance_stub);
       layoutParams2.addRule(3, R.id.live_play_top_bar_left_container);
       layoutParams2.addRule(9, -1);
       layoutParams2.topMargin = c.b(resources, 0x7f0708fc);
       viewStub1.setInflatedId(R.id.live_square_source_back_entrance);
       viewStub1.setLayoutResource(R.layout.arg_RES_7f0d0a1c);
       viewStub1.setLayoutParams(layoutParams2);
       relativeLayo.addView(viewStub1);
       LinearLayout linearLayout1 = new LinearLayout(relativeLayo.getContext());
       RelativeLayout$LayoutParams layoutParams3 = new RelativeLayout$LayoutParams(-2, -2);
       linearLayout1.setId(R.id.live_play_top_bar_left_container);
       layoutParams3.addRule(3, R.id.live_play_audience_skin_top_bar_container);
       linearLayout1.setVisibility(8);
       linearLayout1.setLayoutParams(layoutParams3);
       relativeLayo.addView(linearLayout1);
       View view = new View(linearLayout1.getContext());
       view.setId(R.id.live_play_top_bar_music_station_left_placeholder);
       view.setVisibility(8);
       view.setLayoutParams(new LinearLayout$LayoutParams((int)TypedValue.applyDimension(1, 153.00f, c.c(resources)), (int)TypedValue.applyDimension(1, 32.00f, c.c(resources))));
       linearLayout1.addView(view);
       LinearLayout linearLayout2 = new LinearLayout(linearLayout1.getContext());
       LinearLayout$LayoutParams layoutParams4 = new LinearLayout$LayoutParams(-2, -2);
       linearLayout2.setId(R.id.live_play_top_bar_merchant_left_container);
       layoutParams4.setMarginStart(c.b(resources, R.dimen.arg_RES_7f07034b));
       linearLayout2.setOrientation(false);
       linearLayout2.setVisibility(8);
       linearLayout2.setLayoutParams(layoutParams4);
       linearLayout1.addView(linearLayout2);
       ViewStub viewStub2 = new ViewStub(relativeLayo.getContext());
       viewStub2.setInflatedId(-1);
       RelativeLayout$LayoutParams layoutParams5 = new RelativeLayout$LayoutParams(-2, c.b(resources, 0x7f070984));
       viewStub2.setId(R.id.live_new_pendant_play_top_bar_audience_skin_anchor_info_view_stub);
       layoutParams5.addRule(3, R.id.live_play_top_bar_left_container);
       layoutParams5.leftMargin = c.b(resources, 0x7f070a7f);
       layoutParams5.topMargin = (int)TypedValue.applyDimension(1, 2.00f, c.c(resources));
       viewStub2.setInflatedId(R.id.live_new_pendant_play_top_bar_audience_skin_anchor_info_container);
       viewStub2.setLayoutResource(R.layout.arg_RES_7f0d0ce2);
       viewStub2.setLayoutParams(layoutParams5);
       relativeLayo.addView(viewStub2);
       View view1 = new X2C_Live_Play_Top_Bar_Popup_Head_Right_Container_Layout().createView(relativeLayo.getContext());
       layoutParams5 = view1.getLayoutParams();
       layoutParams5.addRule(11, -1);
       layoutParams5.addRule(6, R.id.live_anchor_info_container);
       layoutParams5.addRule(8, R.id.live_anchor_info_container);
       layoutParams5.addRule(1, R.id.live_anchor_info_container);
       layoutParams5.leftMargin = (int)TypedValue.applyDimension(1, 4.00f, c.c(resources));
       view1.setLayoutParams(layoutParams5);
       relativeLayo.addView(view1);
       RelativeLayout relativeLayo1 = new RelativeLayout(relativeLayo.getContext());
       layoutParams5 = new RelativeLayout$LayoutParams(-2, -2);
       relativeLayo1.setId(R.id.live_anchor_info_container);
       layoutParams5.addRule(3, R.id.live_play_top_bar_left_container);
       layoutParams5.leftMargin = c.b(resources, 0x7f070a7f);
       layoutParams5.topMargin = c.b(resources, 0x7f0708fc);
       relativeLayo1.setClickable(1);
       relativeLayo1.setClipToPadding(false);
       relativeLayo1.setGravity(19);
       relativeLayo1.setClipChildren(false);
       relativeLayo1.setLayoutParams(layoutParams5);
       relativeLayo.addView(relativeLayo1);
       RelativeLayout relativeLayo2 = new RelativeLayout(relativeLayo1.getContext());
       relativeLayo2.setId(R.id.normal_live_anchor_info);
       relativeLayo2.setClipChildren(false);
       relativeLayo2.setLayoutParams(new RelativeLayout$LayoutParams(-2, c.b(resources, R.dimen.arg_RES_7f070984)));
       relativeLayo1.addView(relativeLayo2);
       SelectShapeView selectShapeV = new SelectShapeView(relativeLayo2.getContext());
       RelativeLayout$LayoutParams layoutParams6 = new RelativeLayout$LayoutParams((int)TypedValue.applyDimension(1, 0, c.c(resources)), (int)TypedValue.applyDimension(1, 0, c.c(resources)));
       selectShapeV.setId(R.id.live_anchor_top_bar_area_background_view);
       selectShapeV.setBackgroundResource(R.drawable.arg_RES_7f08022d);
       layoutParams6.addRule(9, -1);
       layoutParams6.addRule(7, R.id.live_follow_text_container);
       layoutParams6.addRule(12, -1);
       layoutParams6.addRule(10, -1);
       IAttrHost[] iAttrHostArr = new IAttrHost[]{new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl()};
       selectShapeV.setAttrs(iAttrHostArr);
       selectShapeV.setLayoutParams(layoutParams6);
       relativeLayo2.addView(selectShapeV);
       FrameLayout uFrameLayout = new FrameLayout(relativeLayo2.getContext());
       layoutParams6 = new RelativeLayout$LayoutParams(-2, -1);
       uFrameLayout.setId(R.id.live_follow_text_container);
       layoutParams6.leftMargin = c.b(resources, 0x7f07031b);
       uFrameLayout.setClipChildren(false);
       layoutParams6.addRule(1, R.id.live_top_bar_name_like_count_container);
       uFrameLayout.setPadding(false, false, c.b(resources, R.dimen.arg_RES_7f0705cf), false);
       uFrameLayout.setLayoutParams(layoutParams6);
       relativeLayo2.addView(uFrameLayout);
       RelativeLayout relativeLayo3 = new RelativeLayout(uFrameLayout.getContext());
       FrameLayout$LayoutParams layoutParams7 = new FrameLayout$LayoutParams((int)TypedValue.applyDimension(1, 40.00f, c.c(resources)), c.b(resources, 0x7f070983));
       relativeLayo3.setId(R.id.live_play_top_bar_fans_group_entrance_container);
       layoutParams7.gravity = 16;
       relativeLayo3.setVisibility(8);
       relativeLayo3.setBackgroundResource(R.drawable.arg_RES_7f080234);
       relativeLayo3.setLayoutParams(layoutParams7);
       uFrameLayout.addView(relativeLayo3);
       RelativeLayout relativeLayo4 = new RelativeLayout(relativeLayo3.getContext());
       relativeLayo4.setId(R.id.live_play_top_bar_fans_group_icon_container);
       relativeLayo4.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       relativeLayo3.addView(relativeLayo4);
       KwaiImageView kwaiImageVie = new KwaiImageView(relativeLayo4.getContext());
       RelativeLayout$LayoutParams layoutParams8 = new RelativeLayout$LayoutParams(c.b(resources, 0x7f07030d), c.b(resources, 0x7f070983));
       kwaiImageVie.setId(R.id.live_play_top_bar_fans_group_entrance_icon);
       layoutParams8.addRule(13, -1);
       kwaiImageVie.setActualImageResource(R.drawable.arg_RES_7f0810e0);
       kwaiImageVie.setLayoutParams(layoutParams8);
       relativeLayo4.addView(kwaiImageVie);
       StrokedTextView strokedTextV = new StrokedTextView(relativeLayo4.getContext());
       layoutParams2 = new RelativeLayout$LayoutParams(-2, -2);
       strokedTextV.setId(R.id.live_play_top_bar_fans_group_entrance_level);
       layoutParams2.addRule(13, -1);
       strokedTextV.setGravity(17);
       strokedTextV.setIncludeFontPadding(false);
       strokedTextV.setTextColor(resources.getColor(R.color.arg_RES_7f0620d1));
       strokedTextV.setTextSize(1, 10.00f);
       strokedTextV.setTypeface(null, 1);
       strokedTextV.setPadding((int)TypedValue.applyDimension(1, 0x3fc00000, c.c(resources)), false, false, false);
       strokedTextV.setLayoutParams(layoutParams2);
       relativeLayo4.addView(strokedTextV);
       RelativeLayout relativeLayo5 = new RelativeLayout(relativeLayo3.getContext());
       relativeLayo5.setId(R.id.live_play_top_bar_fans_group_icon_temp_container);
       relativeLayo5.setVisibility(8);
       relativeLayo5.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       relativeLayo3.addView(relativeLayo5);
       KwaiImageView kwaiImageVie1 = new KwaiImageView(relativeLayo5.getContext());
       RelativeLayout$LayoutParams layoutParams9 = new RelativeLayout$LayoutParams(c.b(resources, 0x7f07030d), c.b(resources, 0x7f070983));
       kwaiImageVie1.setId(R.id.live_play_top_bar_fans_group_entrance_temp_icon);
       layoutParams9.addRule(13, -1);
       kwaiImageVie1.setImageResource(R.drawable.arg_RES_7f0810e0);
       kwaiImageVie1.setLayoutParams(layoutParams9);
       relativeLayo5.addView(kwaiImageVie1);
       StrokedTextView strokedTextV1 = new StrokedTextView(relativeLayo5.getContext());
       layoutParams9 = new RelativeLayout$LayoutParams(-2, -2);
       strokedTextV1.setId(R.id.live_play_top_bar_fans_group_entrance_temp_level);
       layoutParams9.addRule(13, -1);
       strokedTextV1.setGravity(17);
       strokedTextV1.setIncludeFontPadding(false);
       strokedTextV1.setTextColor(resources.getColor(R.color.arg_RES_7f061d96));
       strokedTextV1.setTextSize(1, 10.00f);
       strokedTextV1.setTypeface(null, 1);
       strokedTextV1.setPadding((int)TypedValue.applyDimension(1, 0x3fc00000, c.c(resources)), false, false, false);
       strokedTextV1.setLayoutParams(layoutParams9);
       relativeLayo5.addView(strokedTextV1);
       LiveTextView liveTextView = new LiveTextView(uFrameLayout.getContext());
       FrameLayout$LayoutParams layoutParams10 = new FrameLayout$LayoutParams((int)TypedValue.applyDimension(1, 40.00f, c.c(resources)), c.b(resources, 0x7f070983));
       liveTextView.setId(R.id.live_follow_text);
       layoutParams10.gravity = 16;
       liveTextView.setBackgroundResource(R.drawable.arg_RES_7f08022f);
       liveTextView.setEllipsize(TextUtils$TruncateAt.END);
       liveTextView.setGravity(17);
       liveTextView.setSingleLine(true);
       liveTextView.setText(R.string.arg_RES_7f100f8f);
       liveTextView.setTextColor(resources.getColor(R.color.arg_RES_7f061fbd));
       liveTextView.setTextSize(true, 12.00f);
       liveTextView.setVisibility(8);
       liveTextView.setEnableMediumFontFamily(true);
       liveTextView.setLayoutParams(layoutParams10);
       uFrameLayout.addView(liveTextView);
       liveTextView = new LiveTextView(uFrameLayout.getContext());
       layoutParams10 = new FrameLayout$LayoutParams((int)TypedValue.applyDimension(true, 48.00f, c.c(resources)), c.b(resources, 0x7f070983));
       liveTextView.setId(R.id.live_follow_text_new_style);
       layoutParams10.gravity = 16;
       liveTextView.setBackgroundResource(R.drawable.arg_RES_7f080230);
       liveTextView.setEllipsize(TextUtils$TruncateAt.END);
       liveTextView.setGravity(16);
       liveTextView.setMaxLines(1);
       liveTextView.setTextSize(1, 12.00f);
       liveTextView.setVisibility(8);
       liveTextView.setTextColor(resources.getColor(R.color.arg_RES_7f061fbd));
       liveTextView.setTypeface(null, 1);
       liveTextView.setText(R.string.arg_RES_7f100f8f);
       liveTextView.setCompoundDrawablePadding(c.b(resources, R.dimen.arg_RES_7f0702e3));
       liveTextView.setCompoundDrawablesWithIntrinsicBounds(ContextCompat.getDrawable(uContext, R.drawable.arg_RES_7f0810e4), null, null, null);
       liveTextView.setLayoutParams(layoutParams10);
       uFrameLayout.addView(liveTextView);
       LinearLayout linearLayout3 = new LinearLayout(relativeLayo2.getContext());
       RelativeLayout$LayoutParams layoutParams11 = new RelativeLayout$LayoutParams(-2, -2);
       linearLayout3.setId(R.id.live_top_bar_name_like_count_container);
       layoutParams11.leftMargin = c.b(resources, 0x7f070334);
       linearLayout3.setOrientation(1);
       layoutParams11.addRule(1, R.id.live_anchor_avatar_container);
       layoutParams11.addRule(15, -1);
       linearLayout3.setClipChildren(false);
       linearLayout3.setLayoutParams(layoutParams11);
       relativeLayo2.addView(linearLayout3);
       LinearLayout linearLayout4 = new LinearLayout(linearLayout3.getContext());
       linearLayout4.setLayoutParams(new LinearLayout$LayoutParams(-2, -2));
       linearLayout3.addView(linearLayout4);
       KwaiImageView kwaiImageVie2 = new KwaiImageView(linearLayout4.getContext());
       layoutParams4 = new LinearLayout$LayoutParams(c.b(resources, 0x7f070267), c.b(resources, 0x7f070267));
       kwaiImageVie2.setId(R.id.live_verified_image_view);
       layoutParams4.rightMargin = c.b(resources, 0x7f0702e3);
       layoutParams4.topMargin = c.b(resources, 0x7f0702ac);
       layoutParams4.gravity = 16;
       kwaiImageVie2.setVisibility(8);
       kwaiImageVie2.setLayoutParams(layoutParams4);
       linearLayout4.addView(kwaiImageVie2);
       LiveTextView liveTextView1 = new LiveTextView(linearLayout4.getContext());
       liveTextView1.setId(R.id.live_name_text);
       liveTextView1.setSingleLine(true);
       liveTextView1.setTextColor(resources.getColor(R.color.arg_RES_7f061fd5));
       liveTextView1.setTextSize(true, 12.00f);
       liveTextView1.setEnableMediumFontFamily(true);
       liveTextView1.setLayoutParams(new LinearLayout$LayoutParams(-2, -2));
       linearLayout4.addView(liveTextView1);
       FrameLayout uFrameLayout1 = new FrameLayout(linearLayout3.getContext());
       LinearLayout$LayoutParams layoutParams12 = new LinearLayout$LayoutParams(-2, -2);
       layoutParams12.topMargin = c.b(resources, 0x7f0702ac);
       uFrameLayout1.setLayoutParams(layoutParams12);
       linearLayout3.addView(uFrameLayout1);
       LiveViewFlipper liveViewFlip = new LiveViewFlipper(uFrameLayout1.getContext());
       liveViewFlip.setId(R.id.live_top_bar_head_pendant_flipper);
       liveViewFlip.setLayoutParams(new FrameLayout$LayoutParams(-2, -2));
       uFrameLayout1.addView(liveViewFlip);
       ViewStub viewStub3 = new ViewStub(relativeLayo2.getContext());
       viewStub3.setInflatedId(-1);
       layoutParams11 = new RelativeLayout$LayoutParams(-2, (int)TypedValue.applyDimension(1, 0, c.c(resources)));
       viewStub3.setId(R.id.live_audience_info_slide_bar_stub);
       viewStub3.setLayoutResource(R.layout.arg_RES_7f0d0a17);
       layoutParams11.addRule(8, R.id.live_anchor_avatar_container);
       layoutParams11.addRule(9, -1);
       layoutParams11.addRule(6, R.id.live_anchor_avatar_container);
       viewStub3.setLayoutParams(layoutParams11);
       relativeLayo2.addView(viewStub3);
       View view2 = new X2C_Live_Top_Bar_Like_Layout().createView(relativeLayo2.getContext());
       view2.setLayoutParams(view2.getLayoutParams());
       relativeLayo2.addView(view2);
       view2 = new X2C_Live_Top_Bar_Anchor_Avatar_Container_Layout().createView(relativeLayo2.getContext());
       view2.setLayoutParams(view2.getLayoutParams());
       relativeLayo2.addView(view2);
       SelectShapeTextView selectShapeT = new SelectShapeTextView(relativeLayo.getContext());
       layoutParams11 = new RelativeLayout$LayoutParams(-2, -2);
       selectShapeT.setId(R.id.live_play_top_bar_fans_group_tag_text_view);
       layoutParams11.addRule(1, R.id.live_anchor_info_container);
       layoutParams11.addRule(10, -1);
       layoutParams11.setMarginStart((int)TypedValue.applyDimension(1, -15.00f, c.c(resources)));
       selectShapeT.setGravity(17);
       selectShapeT.setTextColor(resources.getColor(R.color.arg_RES_7f061e52));
       selectShapeT.setTextSize(false, (float)c.b(resources, R.dimen.arg_RES_7f070356));
       selectShapeT.setIncludeFontPadding(false);
       selectShapeT.setVisibility(8);
       selectShapeT.setPadding(c.b(resources, R.dimen.arg_RES_7f07031b), c.b(resources, R.dimen.arg_RES_7f0702ac), c.b(resources, R.dimen.arg_RES_7f07031b), c.b(resources, R.dimen.arg_RES_7f0702ac));
       XmlAttrHostImpl xmlAttrHostI = new XmlAttrHostImpl();
       xmlAttrHostI.addAttr(29, Integer.valueOf(resources.getColor(R.color.arg_RES_7f061de2)));
       XmlAttrHostImpl xmlAttrHostI1 = new XmlAttrHostImpl();
       xmlAttrHostI1.addAttr(2, Integer.valueOf(c.b(resources, R.dimen.arg_RES_7f07042c)));
       IAttrHost[] iAttrHostArr1 = new IAttrHost[]{xmlAttrHostI,new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),xmlAttrHostI1};
       selectShapeT.setAttrs(iAttrHostArr1);
       selectShapeT.setLayoutParams(layoutParams11);
       relativeLayo.addView(selectShapeT);
       return linearLayout;
    }
}
