package com.kuaishou.ax2c.layouts.X2C_Vm_Nasa_Photo_Detail_Vertical;
import com.kuaishou.ax2c.IViewCreator;
import java.lang.Object;
import android.content.Context;
import android.view.View;
import android.content.res.Resources;
import com.yxcorp.gifshow.detail.slidev2.widget.PressControlSpeedRelativeLayout;
import android.view.ViewGroup$MarginLayoutParams;
import android.widget.RelativeLayout;
import android.view.ViewGroup$LayoutParams;
import android.view.ViewStub;
import android.widget.RelativeLayout$LayoutParams;
import androidx.appcompat.widget.AppCompatTextView;
import cw9.c;
import android.widget.TextView;
import com.kwai.library.widget.imageview.scale.PhotosScaleHelpView;
import android.widget.ImageView;
import com.kwai.library.slide.base.widget.SlidePlayVerticalRelativeLayout;
import com.kwai.library.slide.base.widget.SlidePlayVerticalRelativeLayout$LayoutParams;
import android.util.TypedValue;
import android.content.res.Resources$Theme;
import android.util.DisplayMetrics;
import android.widget.FrameLayout;
import android.widget.FrameLayout$LayoutParams;
import com.kuaishou.ax2c.layouts.X2C_Vm_Slide_Play_Photo_Image_Tips_Layout;
import com.kuaishou.ax2c.layouts.X2C_Nasa_Float_Controller;

public class X2C_Vm_Nasa_Photo_Detail_Vertical implements IViewCreator	// class@00113f
{

    public void X2C_Vm_Nasa_Photo_Detail_Vertical(){
       super();
    }
    public View createView(Context p0){
       int i1;
       TypedValue typedValue;
       Resources resources = p0.getResources();
       PressControlSpeedRelativeLayout pressControl = new PressControlSpeedRelativeLayout(p0);
       pressControl.setId(R.id.root);
       pressControl.setLayoutParams(new ViewGroup$MarginLayoutParams(-1, -1));
       ViewStub viewStub = new ViewStub(pressControl.getContext());
       viewStub.setInflatedId(-1);
       viewStub.setId(R.id.slide_vertical_atlas_view_stub);
       viewStub.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       pressControl.addView(viewStub);
       viewStub = new ViewStub(pressControl.getContext());
       viewStub.setInflatedId(-1);
       viewStub.setId(R.id.nasa_long_photo_screen_clean_view_stub);
       viewStub.setLayoutResource(R.layout.arg_RES_7f0d1055);
       viewStub.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       pressControl.addView(viewStub);
       AppCompatTextView uAppCompatTe = new AppCompatTextView(pressControl.getContext());
       RelativeLayout$LayoutParams layoutParams = new RelativeLayout$LayoutParams(-2, c.b(resources, 0x7f0702cc));
       uAppCompatTe.setId(R.id.long_atlas_position_view);
       layoutParams.addRule(21, -1);
       layoutParams.rightMargin = c.b(resources, 0x7f0702ab);
       layoutParams.topMargin = c.b(resources, 0x7f07034c);
       uAppCompatTe.setGravity(17);
       int i = 8;
       uAppCompatTe.setVisibility(i);
       uAppCompatTe.setIncludeFontPadding(false);
       uAppCompatTe.setTextColor(resources.getColor(R.color.arg_RES_7f061c32));
       uAppCompatTe.setTextSize(false, (float)c.b(resources, R.dimen.arg_RES_7f070271));
       uAppCompatTe.setPadding(c.b(resources, R.dimen.arg_RES_7f070356), c.b(resources, R.dimen.arg_RES_7f07031b), c.b(resources, R.dimen.arg_RES_7f070356), c.b(resources, R.dimen.arg_RES_7f07031b));
       uAppCompatTe.setLayoutParams(layoutParams);
       pressControl.addView(uAppCompatTe);
       PhotosScaleHelpView photosScaleH = new PhotosScaleHelpView(pressControl.getContext());
       layoutParams = new RelativeLayout$LayoutParams(-1, -1);
       photosScaleH.setId(R.id.out_mask);
       layoutParams.addRule(13, -1);
       photosScaleH.setBackgroundColor(resources.getColor(R.color.arg_RES_7f062057));
       photosScaleH.setLayoutParams(layoutParams);
       pressControl.addView(photosScaleH);
       SlidePlayVerticalRelativeLayout slidePlayVer = new SlidePlayVerticalRelativeLayout(pressControl.getContext());
       boolean b = true;
       slidePlayVer.f(b);
       slidePlayVer.setId(R.id.slide_v2_content_layout);
       slidePlayVer.setClipChildren(false);
       slidePlayVer.setClipToPadding(false);
       slidePlayVer.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       pressControl.addView(slidePlayVer);
       View view = new View(slidePlayVer.getContext());
       SlidePlayVerticalRelativeLayout$LayoutParams layoutParams1 = new SlidePlayVerticalRelativeLayout$LayoutParams(-1, -1);
       view.setId(R.id.out_fill);
       try{
          i1 = 0x7f04023f;
          typedValue = new TypedValue();
          p0.getTheme().resolveAttribute(i1, typedValue, b);
          view.setBackgroundColor(typedValue.data);
       }catch(java.lang.Exception e0){
          typedValue = new TypedValue();
          p0.getTheme().resolveAttribute(i1, typedValue, b);
          view.setBackgroundResource(typedValue.data);
       }
       view.setVisibility(i);
       view.setLayoutParams(layoutParams1);
       slidePlayVer.addView(view);
       View view1 = new View(slidePlayVer.getContext());
       view1.setId(R.id.top_shadow);
       view1.setVisibility(i);
       view1.setBackgroundResource(R.drawable.arg_RES_7f0820f5);
       view1.setLayoutParams(new SlidePlayVerticalRelativeLayout$LayoutParams(-1, (int)TypedValue.applyDimension(b, 110.00f, c.c(e0))));
       slidePlayVer.addView(view1);
       view1 = new View(slidePlayVer.getContext());
       SlidePlayVerticalRelativeLayout$LayoutParams layoutParams2 = new SlidePlayVerticalRelativeLayout$LayoutParams(-1, c.b(e0, 0x7f0700db));
       view1.setId(R.id.bottom_shadow);
       layoutParams2.topMargin = (int)TypedValue.applyDimension(b, -100.00f, c.c(e0));
       layoutParams2.addRule(6, R.id.group_information_root_layout);
       layoutParams2.addRule(12, -1);
       view1.setBackgroundResource(R.drawable.arg_RES_7f082082);
       view1.setLayoutParams(layoutParams2);
       slidePlayVer.addView(view1);
       FrameLayout uFrameLayout = new FrameLayout(slidePlayVer.getContext());
       layoutParams2 = new SlidePlayVerticalRelativeLayout$LayoutParams(-1, (int)TypedValue.applyDimension(b, 0, c.c(e0)));
       uFrameLayout.setId(R.id.bottom_shadow_exp);
       layoutParams2.addRule(12, -1);
       layoutParams2.addRule(6, R.id.group_information_root_layout);
       layoutParams2.topMargin = (int)TypedValue.applyDimension(b, -100.00f, c.c(e0));
       uFrameLayout.setVisibility(i);
       uFrameLayout.setLayoutParams(layoutParams2);
       slidePlayVer.addView(uFrameLayout);
       view = new View(uFrameLayout.getContext());
       FrameLayout$LayoutParams layoutParams3 = new FrameLayout$LayoutParams(-1, -1);
       layoutParams3.bottomMargin = c.b(e0, 0x7f070bf1);
       view.setBackgroundResource(R.drawable.arg_RES_7f082082);
       view.setLayoutParams(layoutParams3);
       uFrameLayout.addView(view);
       view = new View(uFrameLayout.getContext());
       layoutParams3 = new FrameLayout$LayoutParams(-1, c.b(e0, 0x7f070bf1));
       layoutParams3.gravity = 80;
       view.setBackgroundResource(R.drawable.arg_RES_7f082085);
       view.setLayoutParams(layoutParams3);
       uFrameLayout.addView(view);
       view1 = new View(slidePlayVer.getContext());
       layoutParams2 = new SlidePlayVerticalRelativeLayout$LayoutParams(-1, c.b(e0, 0x7f0700db));
       view1.setId(R.id.bottom_shadow_screen_clean);
       layoutParams2.addRule(12, -1);
       view1.setBackgroundResource(R.drawable.arg_RES_7f081987);
       view1.setVisibility(4);
       view1.setLayoutParams(layoutParams2);
       slidePlayVer.addView(view1);
       View view2 = new X2C_Vm_Slide_Play_Photo_Image_Tips_Layout().createView(slidePlayVer.getContext());
       view2.setId(R.id.slide_play_image_tips_content);
       view2.setLayoutParams(view2.getLayoutParams());
       slidePlayVer.addView(view2);
       view2 = new X2C_Nasa_Float_Controller().createView(slidePlayVer.getContext());
       view2.setLayoutParams(view2.getLayoutParams());
       slidePlayVer.addView(view2);
       ViewStub viewStub1 = new ViewStub(pressControl.getContext());
       viewStub1.setInflatedId(-1);
       viewStub1.setId(R.id.friend_slide_play_item_place_holder);
       viewStub1.setInflatedId(R.id.friend_slide_play_item_container);
       viewStub1.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       pressControl.addView(viewStub1);
       viewStub1 = new ViewStub(pressControl.getContext());
       viewStub1.setInflatedId(-1);
       viewStub1.setId(R.id.slide_dragging_shadow_layer_view_stub);
       viewStub1.setLayoutResource(R.layout.arg_RES_7f0d151c);
       viewStub1.setInflatedId(R.id.slide_dragging_shadow_layer);
       viewStub1.setLayoutParams(new RelativeLayout$LayoutParams(-1, -1));
       pressControl.addView(viewStub1);
       return pressControl;
    }
}
