package com.kuaishou.ax2c.layouts.X2C_Live_Audience_Player_Float_Element_Container;
import com.kuaishou.ax2c.IViewCreator;
import java.lang.Object;
import android.content.Context;
import android.view.View;
import android.content.res.Resources;
import androidx.constraintlayout.widget.ConstraintLayout;
import android.widget.RelativeLayout$LayoutParams;
import cw9.c;
import android.view.ViewGroup;
import android.view.ViewGroup$LayoutParams;
import android.widget.Space;
import androidx.constraintlayout.widget.ConstraintLayout$LayoutParams;
import androidx.constraintlayout.widget.Group;
import android.widget.FrameLayout;
import androidx.appcompat.widget.AppCompatImageView;
import android.widget.ImageView;
import android.view.ViewGroup$MarginLayoutParams;
import com.yxcorp.widget.selector.view.SelectShapeTextView;
import android.widget.TextView;
import android.util.DisplayMetrics;
import android.util.TypedValue;
import androidx.appcompat.widget.AppCompatTextView;
import com.kuaishou.ax2c.XmlAttrHostImpl;
import java.lang.Integer;
import com.kuaishou.ax2c.IAttrHost;
import ald.b;
import androidx.constraintlayout.widget.Guideline;
import android.graphics.drawable.Drawable;
import androidx.core.content.ContextCompat;

public class X2C_Live_Audience_Player_Float_Element_Container implements IViewCreator	// class@0010de
{

    public void X2C_Live_Audience_Player_Float_Element_Container(){
       super();
    }
    public View createView(Context p0){
       Context uContext = p0;
       Resources resources = p0.getResources();
       ConstraintLayout uConstraintL = new ConstraintLayout(uContext);
       uConstraintL.setId(R.id.live_player_float_element_container);
       uConstraintL.setVisibility(8);
       uConstraintL.setLayoutParams(new RelativeLayout$LayoutParams(-1, c.b(resources, R.dimen.arg_RES_7f07090a)));
       Space space = new Space(uConstraintL.getContext());
       ConstraintLayout$LayoutParams layoutParams = new ConstraintLayout$LayoutParams(c.b(resources, 0x7f070253), c.b(resources, 0x7f070253));
       space.setId(R.id.bottom_space);
       layoutParams.k = 0;
       layoutParams.d = 0;
       layoutParams.g = 0;
       layoutParams.c();
       space.setLayoutParams(layoutParams);
       uConstraintL.addView(space);
       Group group = new Group(uConstraintL.getContext());
       group.setId(R.id.live_player_float_element_group);
       group.setVisibility(8);
       group.setLayoutParams(new ConstraintLayout$LayoutParams(-2, -2));
       uConstraintL.addView(group);
       FrameLayout uFrameLayout = new FrameLayout(uConstraintL.getContext());
       uFrameLayout.setId(R.id.live_player_float_element_background);
       uFrameLayout.setVisibility(8);
       uFrameLayout.setLayoutParams(new ConstraintLayout$LayoutParams(-1, -1));
       uConstraintL.addView(uFrameLayout);
       AppCompatImageView uAppCompatIm = new AppCompatImageView(uConstraintL.getContext());
       layoutParams = new ConstraintLayout$LayoutParams(c.b(resources, 0x7f0705e4), c.b(resources, 0x7f0705e4));
       uAppCompatIm.setId(R.id.live_player_bottom_orientation_button);
       layoutParams.bottomMargin = c.b(resources, 0x7f07025d);
       uAppCompatIm.setImageResource(R.drawable.arg_RES_7f0813e0);
       uAppCompatIm.setVisibility(8);
       layoutParams.j = 0x7f0a04e8;
       layoutParams.g = 0x7f0a2327;
       layoutParams.c();
       uAppCompatIm.setLayoutParams(layoutParams);
       uConstraintL.addView(uAppCompatIm);
       SelectShapeTextView selectShapeT = new SelectShapeTextView(uConstraintL.getContext());
       layoutParams = new ConstraintLayout$LayoutParams(-2, c.b(resources, 0x7f0705e4));
       selectShapeT.setId(R.id.live_player_bottom_quality_button);
       layoutParams.rightMargin = c.b(resources, 0x7f0705e3);
       layoutParams.bottomMargin = c.b(resources, 0x7f07025d);
       selectShapeT.setGravity(17);
       selectShapeT.setMinWidth((int)TypedValue.applyDimension(1, 58.00f, c.c(resources)));
       selectShapeT.setSingleLine(1);
       selectShapeT.setTextColor(resources.getColor(0x106000b));
       selectShapeT.setTextSize(1, 14.00f);
       selectShapeT.setVisibility(8);
       layoutParams.j = 0x7f0a04e8;
       layoutParams.f = 0x7f0a2328;
       selectShapeT.setPadding((int)TypedValue.applyDimension(1, 12.00f, c.c(resources)), 0, (int)TypedValue.applyDimension(1, 12.00f, c.c(resources)), 0);
       layoutParams.c();
       XmlAttrHostImpl xmlAttrHostI = new XmlAttrHostImpl();
       xmlAttrHostI.addAttr(29, Integer.valueOf(resources.getColor(R.color.arg_RES_7f062040)));
       XmlAttrHostImpl xmlAttrHostI1 = new XmlAttrHostImpl();
       xmlAttrHostI1.addAttr(2, Integer.valueOf(c.b(resources, R.dimen.arg_RES_7f07042c)));
       IAttrHost[] iAttrHostArr = new IAttrHost[]{xmlAttrHostI,new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),xmlAttrHostI1};
       selectShapeT.setAttrs(iAttrHostArr);
       selectShapeT.setLayoutParams(layoutParams);
       uConstraintL.addView(selectShapeT);
       Guideline guideline = new Guideline(uConstraintL.getContext());
       ConstraintLayout$LayoutParams layoutParams1 = new ConstraintLayout$LayoutParams(-2, -2);
       guideline.setId(R.id.live_player_bottom_guideline);
       layoutParams1.S = 1;
       layoutParams1.b = (int)TypedValue.applyDimension(1, 10.00f, c.c(resources));
       layoutParams1.c();
       guideline.setLayoutParams(layoutParams1);
       uConstraintL.addView(guideline);
       selectShapeT = new SelectShapeTextView(uConstraintL.getContext());
       layoutParams1 = new ConstraintLayout$LayoutParams(-1, c.b(resources, 0x7f070319));
       selectShapeT.setId(R.id.live_gzone_competition_title_tv);
       selectShapeT.setTextColor(resources.getColor(R.color.arg_RES_7f0620c7));
       selectShapeT.setTextSize(0, (float)c.b(resources, R.dimen.arg_RES_7f070f70));
       selectShapeT.setVisibility(8);
       layoutParams1.d = 0;
       layoutParams1.h = 0;
       selectShapeT.setPadding((int)TypedValue.applyDimension(1, 11.00f, c.c(resources)), (int)TypedValue.applyDimension(1, 4.00f, c.c(resources)), 0, 0);
       layoutParams1.c();
       XmlAttrHostImpl xmlAttrHostI2 = new XmlAttrHostImpl();
       xmlAttrHostI2.addAttr(12, Integer.valueOf(resources.getColor(R.color.arg_RES_7f062057)));
       xmlAttrHostI2.addAttr(9, Integer.valueOf(resources.getColor(R.color.arg_RES_7f06141c)));
       xmlAttrHostI2.addAttr(14, Integer.valueOf(resources.getColor(R.color.arg_RES_7f061d74)));
       IAttrHost[] iAttrHostArr1 = new IAttrHost[]{xmlAttrHostI2,new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl()};
       selectShapeT.setAttrs(iAttrHostArr1);
       selectShapeT.setLayoutParams(layoutParams1);
       uConstraintL.addView(selectShapeT);
       selectShapeT = new SelectShapeTextView(uConstraintL.getContext());
       layoutParams1 = new ConstraintLayout$LayoutParams(-2, c.b(resources, 0x7f0705e4));
       selectShapeT.setId(R.id.live_gzone_competition_diversion_entrance_view);
       selectShapeT.setCompoundDrawablePadding((int)TypedValue.applyDimension(1, 4.00f, c.c(resources)));
       selectShapeT.setGravity(17);
       selectShapeT.setText(R.string.arg_RES_7f102410);
       selectShapeT.setTextColor(resources.getColor(0x106000b));
       selectShapeT.setTextSize(1, 14.00f);
       selectShapeT.setVisibility(8);
       layoutParams1.bottomMargin = c.b(resources, 0x7f07025d);
       layoutParams1.j = 0x7f0a04e8;
       layoutParams1.d = 0;
       selectShapeT.setCompoundDrawablesWithIntrinsicBounds(null, null, ContextCompat.getDrawable(uContext, R.drawable.arg_RES_7f081289), null);
       selectShapeT.setPadding((int)TypedValue.applyDimension(1, 16.00f, c.c(resources)), 0, (int)TypedValue.applyDimension(1, 16.00f, c.c(resources)), 0);
       layoutParams1.c();
       XmlAttrHostImpl xmlAttrHostI3 = new XmlAttrHostImpl();
       xmlAttrHostI3.addAttr(29, Integer.valueOf(resources.getColor(R.color.arg_RES_7f062040)));
       xmlAttrHostI1 = new XmlAttrHostImpl();
       xmlAttrHostI1.addAttr(2, Integer.valueOf(c.b(resources, R.dimen.arg_RES_7f07042c)));
       IAttrHost[] iAttrHostArr2 = new IAttrHost[]{xmlAttrHostI3,new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),xmlAttrHostI1};
       selectShapeT.setAttrs(iAttrHostArr2);
       selectShapeT.setLayoutParams(layoutParams1);
       uConstraintL.addView(selectShapeT);
       return uConstraintL;
    }
}
