package com.kuaishou.ax2c.layouts.X2C_Camera_Action_Bar_Prettify_Layout;
import com.kuaishou.ax2c.IViewCreator;
import java.lang.Object;
import android.content.Context;
import android.view.View;
import android.content.res.Resources;
import com.kwai.feature.post.api.flywheel.widget.FlyWheelConstraintLayout;
import androidx.constraintlayout.widget.ConstraintLayout$LayoutParams;
import android.view.ViewGroup;
import android.view.ViewGroup$LayoutParams;
import android.widget.LinearLayout;
import android.widget.FrameLayout;
import android.widget.LinearLayout$LayoutParams;
import com.yxcorp.widget.selector.view.SelectShapeView;
import android.widget.FrameLayout$LayoutParams;
import cw9.c;
import android.widget.ImageView;
import com.kuaishou.ax2c.XmlAttrHostImpl;
import java.lang.Integer;
import com.kuaishou.ax2c.IAttrHost;
import ald.b;
import com.yxcorp.gifshow.widget.PressedImageView;
import android.graphics.drawable.Drawable;
import android.widget.ImageView$ScaleType;
import ac.b;
import com.facebook.drawee.view.DraweeView;
import yb.a;
import androidx.core.content.ContextCompat;
import androidx.appcompat.widget.AppCompatTextView;
import android.widget.TextView;
import android.text.TextUtils$TruncateAt;
import androidx.constraintlayout.widget.ConstraintLayout;
import android.util.DisplayMetrics;
import android.util.TypedValue;

public class X2C_Camera_Action_Bar_Prettify_Layout implements IViewCreator	// class@001090
{

    public void X2C_Camera_Action_Bar_Prettify_Layout(){
       super();
    }
    public View createView(Context p0){
       Context uContext = p0;
       Resources resources = p0.getResources();
       FlyWheelConstraintLayout uFlyWheelCon = new FlyWheelConstraintLayout(uContext);
       uFlyWheelCon.setVisibility(8);
       uFlyWheelCon.setTKContainerId(R.id.fly_wheel_prettify_tk_container);
       uFlyWheelCon.setTextViewId(R.id.button_prettify_tv);
       uFlyWheelCon.setLayoutParams(new ConstraintLayout$LayoutParams(-2, -2));
       LinearLayout linearLayout = new LinearLayout(uFlyWheelCon.getContext());
       ConstraintLayout$LayoutParams layoutParams = new ConstraintLayout$LayoutParams(-2, -2);
       linearLayout.setOrientation(1);
       layoutParams.d = 0;
       layoutParams.g = 0;
       layoutParams.h = 0;
       layoutParams.k = 0;
       layoutParams.c();
       linearLayout.setLayoutParams(layoutParams);
       uFlyWheelCon.addView(linearLayout);
       FrameLayout uFrameLayout = new FrameLayout(linearLayout.getContext());
       uFrameLayout.setLayoutParams(new LinearLayout$LayoutParams(-2, -2));
       linearLayout.addView(uFrameLayout);
       SelectShapeView selectShapeV = new SelectShapeView(uFrameLayout.getContext());
       selectShapeV.setId(R.id.button_prettify_color_bg);
       selectShapeV.setVisibility(8);
       XmlAttrHostImpl xmlAttrHostI = new XmlAttrHostImpl();
       xmlAttrHostI.addAttr(26, Integer.valueOf(1));
       xmlAttrHostI.addAttr(29, Integer.valueOf(resources.getColor(R.color.arg_RES_7f061cea)));
       IAttrHost[] iAttrHostArr = new IAttrHost[]{xmlAttrHostI,new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl(),new XmlAttrHostImpl()};
       selectShapeV.setAttrs(iAttrHostArr);
       selectShapeV.setLayoutParams(new FrameLayout$LayoutParams(c.b(resources, R.dimen.arg_RES_7f070319), c.b(resources, R.dimen.arg_RES_7f070319)));
       uFrameLayout.addView(selectShapeV);
       PressedImageView pressedImage = new PressedImageView(uFrameLayout.getContext());
       FrameLayout$LayoutParams layoutParams1 = new FrameLayout$LayoutParams(c.b(resources, 0x7f07011d), c.b(resources, 0x7f07011d));
       pressedImage.setBackgroundDrawable(null);
       pressedImage.setScaleType(ImageView$ScaleType.FIT_CENTER);
       pressedImage.setId(R.id.button_switch_prettify);
       layoutParams1.gravity = 17;
       pressedImage.setDisableAlpha(0.40f);
       pressedImage.setPressedAlpha(0.40f);
       pressedImage.getHierarchy().F(ContextCompat.getDrawable(uContext, R.drawable.arg_RES_7f080444));
       pressedImage.setLayoutParams(layoutParams1);
       uFrameLayout.addView(pressedImage);
       AppCompatTextView uAppCompatTe = new AppCompatTextView(linearLayout.getContext());
       LinearLayout$LayoutParams layoutParams2 = new LinearLayout$LayoutParams(-2, c.b(resources, 0x7f070120));
       uAppCompatTe.setTextSize(0, (float)c.b(resources, R.dimen.arg_RES_7f070f6d));
       uAppCompatTe.setShadowLayer(0x3f800000, uAppCompatTe.getShadowDx(), uAppCompatTe.getShadowDy(), uAppCompatTe.getShadowColor());
       uAppCompatTe.setSingleLine(1);
       uAppCompatTe.setMaxWidth(c.b(resources, R.dimen.arg_RES_7f07011f));
       uAppCompatTe.setShadowLayer(uAppCompatTe.getShadowRadius(), 3.00f, uAppCompatTe.getShadowDy(), uAppCompatTe.getShadowColor());
       uAppCompatTe.setShadowLayer(uAppCompatTe.getShadowRadius(), uAppCompatTe.getShadowDx(), uAppCompatTe.getShadowDy(), resources.getColor(R.color.arg_RES_7f06010e));
       uAppCompatTe.setTextColor(resources.getColor(R.color.arg_RES_7f060113));
       uAppCompatTe.setEllipsize(TextUtils$TruncateAt.END);
       uAppCompatTe.setShadowLayer(uAppCompatTe.getShadowRadius(), uAppCompatTe.getShadowDx(), 3.00f, uAppCompatTe.getShadowColor());
       uAppCompatTe.setGravity(17);
       uAppCompatTe.setIncludeFontPadding(0);
       uAppCompatTe.setId(R.id.button_prettify_tv);
       layoutParams2.gravity = 1;
       uAppCompatTe.setText(R.string.arg_RES_7f103e0b);
       uAppCompatTe.setLayoutParams(layoutParams2);
       linearLayout.addView(uAppCompatTe);
       ConstraintLayout uConstraintL = new ConstraintLayout(uFlyWheelCon.getContext());
       ConstraintLayout$LayoutParams layoutParams3 = new ConstraintLayout$LayoutParams((int)TypedValue.applyDimension(1, 0, c.c(resources)), (int)TypedValue.applyDimension(1, 0, c.c(resources)));
       uConstraintL.setId(R.id.fly_wheel_prettify_tk_container);
       layoutParams3.k = 0;
       layoutParams3.d = 0;
       layoutParams3.g = 0;
       layoutParams3.h = 0;
       layoutParams3.c();
       uConstraintL.setLayoutParams(layoutParams3);
       uFlyWheelCon.addView(uConstraintL);
       return uFlyWheelCon;
    }
}
