package com.kwai.video.krtc.a;
import java.lang.Object;
import com.kwai.video.krtc.AryaManager$LogParam;
import com.kwai.video.krtc.observers.AryaLogObserver;
import java.lang.Class;
import java.lang.String;
import com.kwai.robust.PatchProxy;
import com.kwai.video.stannis.Stannis$LogParam;
import com.kwai.video.krtc.a$1;
import com.kwai.video.stannis.Stannis;
import com.kwai.video.krtc.a$a;
import com.kwai.video.krtc.a$c;
import android.content.Context;
import com.kwai.video.krtc.Arya$AryaAudioDeviceStatusListener;
import com.kwai.video.krtc.Arya$AryaAudioRouteListener;
import com.kwai.video.krtc.Arya$AryaConfig;
import com.kwai.video.krtc.AryaContext;
import com.kwai.video.krtc.AudioServerConfig;
import com.kwai.video.krtc.observers.AryaRawAudioFrameObserver;
import com.kwai.video.krtc.observers.AudioSceneObserver;
import com.kwai.video.krtc.observers.RawAudioObserver;
import com.kwai.video.stannis.observers.DataReadyObserver;
import com.kwai.video.krtc.observers.a;
import com.kwai.video.krtc.observers.AudioSegmentPlayerObserver;
import com.kwai.video.krtc.observers.AudioBufferPlayObserver;
import java.util.ArrayList;
import com.kwai.video.krtc.a$b;
import com.kwai.video.stannis.Stannis$KWStannisAudioEffectParam;
import android.media.projection.MediaProjection;
import com.kwai.video.krtc.AryaAudioConfigQosInfo;
import com.kwai.video.krtc.Arya$AryaMicrophoneInfo;
import java.util.List;
import com.kwai.video.krtc.Arya$AryaDeviceInfo;

public abstract class a	// class@000772
{

    public void a(){
       super();
    }
    public static void a(AryaManager$LogParam p0,AryaLogObserver p1){
       if (PatchProxy.applyVoidTwoRefs(p0, p1, null, a.class, "1")) {
          return;
       }
       Stannis$LogParam logParam = new Stannis$LogParam();
       logParam.logLevel = p0.logLevel;
       logParam.isConsoleEnable = false;
       logParam.isFileEnable = false;
       logParam.filePath = p0.filePath;
       logParam.maxFileNum = p0.maxFileNum;
       logParam.maxFileSize = p0.maxFileSize;
       logParam.logCb = new a$1(p1);
       Stannis.setLogParam(logParam);
       return;
    }
    public abstract void A();
    public abstract void B();
    public abstract void C();
    public abstract void D();
    public abstract void E();
    public abstract void F();
    public abstract void G();
    public abstract void H();
    public abstract void I();
    public abstract boolean J();
    public abstract void K();
    public abstract void L();
    public abstract boolean M();
    public abstract void N();
    public abstract void O();
    public abstract void P();
    public abstract float[] Q();
    public abstract void a();
    public abstract void a(float p0);
    public abstract void a(int p0);
    public abstract void a(int p0,int p1);
    public abstract void a(int p0,int p1,int p2,int p3);
    public abstract void a(int p0,a$a p1,int p2);
    public abstract void a(int p0,a$a p1,int p2,int p3,String p4);
    public abstract void a(int p0,a$a p1,int p2,int p3,String p4,boolean p5,int p6);
    public abstract void a(int p0,boolean p1);
    public abstract void a(int p0,byte[] p1,int p2,int p3,int p4,long p5);
    public abstract void a(int p0,byte[] p1,long p2);
    public abstract void a(long p0,String p1,String p2,String p3,String p4,String p5,int p6,int p7,a$c p8);
    public abstract void a(Context p0);
    public abstract void a(Arya$AryaAudioDeviceStatusListener p0);
    public abstract void a(Arya$AryaAudioRouteListener p0);
    public abstract void a(Arya$AryaConfig p0);
    public abstract void a(AryaContext p0);
    public abstract void a(AudioServerConfig p0);
    public abstract void a(a$a p0);
    public abstract void a(AryaRawAudioFrameObserver p0);
    public abstract void a(AudioSceneObserver p0);
    public abstract void a(RawAudioObserver p0,int p1);
    public abstract void a(DataReadyObserver p0);
    public abstract void a(String p0);
    public abstract void a(String p0,float p1);
    public abstract void a(String p0,a p1);
    public abstract void a(String p0,String p1,AudioSegmentPlayerObserver p2);
    public abstract void a(String p0,boolean p1,float p2);
    public abstract void a(String p0,byte[] p1,float p2,boolean p3,AudioBufferPlayObserver p4);
    public abstract void a(ArrayList p0);
    public abstract void a(ArrayList p0,ArrayList p1,boolean p2,int p3,a$b p4);
    public abstract void a(boolean p0);
    public abstract void a(boolean p0,int p1,int p2);
    public abstract void a(boolean p0,Stannis$KWStannisAudioEffectParam p1);
    public abstract void a(boolean p0,String p1);
    public abstract void a(boolean p0,boolean p1);
    public abstract void a(byte[] p0,int p1,int p2,int p3,long p4);
    public abstract void a(int[] p0);
    public abstract void a(int[] p0,float[] p1,float[] p2,float[] p3);
    public abstract boolean a(MediaProjection p0);
    public abstract int b(String p0);
    public abstract String b(int p0);
    public abstract void b();
    public abstract void b(float p0);
    public abstract void b(int p0,int p1);
    public abstract void b(int p0,int p1,int p2,int p3);
    public abstract void b(int p0,boolean p1);
    public abstract void b(a$a p0);
    public abstract void b(AudioSceneObserver p0);
    public abstract void b(boolean p0);
    public abstract void b(boolean p0,String p1);
    public abstract void b(byte[] p0,int p1,int p2,int p3,long p4);
    public abstract AryaAudioConfigQosInfo c(int p0);
    public abstract void c();
    public abstract void c(float p0);
    public abstract void c(int p0,int p1);
    public abstract void c(int p0,int p1,int p2,int p3);
    public abstract void c(a$a p0);
    public abstract void c(String p0);
    public abstract void c(boolean p0);
    public abstract void c(byte[] p0,int p1,int p2,int p3,long p4);
    public abstract int d();
    public abstract void d(float p0);
    public abstract void d(int p0);
    public abstract void d(String p0);
    public abstract void d(boolean p0);
    public abstract void e(float p0);
    public abstract void e(int p0);
    public abstract void e(String p0);
    public abstract void e(boolean p0);
    public abstract String[] e();
    public abstract int f();
    public abstract void f(float p0);
    public abstract void f(int p0);
    public abstract void f(String p0);
    public abstract void f(boolean p0);
    public abstract String g();
    public abstract void g(float p0);
    public abstract void g(int p0);
    public abstract void g(String p0);
    public abstract void g(boolean p0);
    public abstract String h();
    public abstract void h(float p0);
    public abstract void h(int p0);
    public abstract void h(String p0);
    public abstract void h(boolean p0);
    public abstract void i(float p0);
    public abstract void i(int p0);
    public abstract void i(String p0);
    public abstract void i(boolean p0);
    public abstract boolean i();
    public abstract void j();
    public abstract void j(float p0);
    public abstract void j(int p0);
    public abstract void j(String p0);
    public abstract void j(boolean p0);
    public abstract int k();
    public abstract void k(int p0);
    public abstract void k(boolean p0);
    public abstract void l(int p0);
    public abstract void l(boolean p0);
    public abstract int[] l();
    public abstract int m();
    public abstract void m(int p0);
    public abstract void m(boolean p0);
    public abstract Arya$AryaMicrophoneInfo n();
    public abstract void n(int p0);
    public abstract void n(boolean p0);
    public abstract void o();
    public abstract void o(boolean p0);
    public abstract boolean o(int p0);
    public abstract List p(int p0);
    public abstract void p();
    public abstract void p(boolean p0);
    public abstract void q();
    public abstract void q(int p0);
    public abstract void q(boolean p0);
    public abstract void r();
    public abstract void r(int p0);
    public abstract boolean r(boolean p0);
    public abstract void s();
    public abstract void s(int p0);
    public abstract void s(boolean p0);
    public abstract void t();
    public abstract void t(int p0);
    public abstract void t(boolean p0);
    public abstract void u();
    public abstract void u(int p0);
    public abstract void u(boolean p0);
    public abstract void v();
    public abstract void v(int p0);
    public abstract void v(boolean p0);
    public abstract Arya$AryaDeviceInfo w(int p0);
    public abstract void w();
    public abstract void w(boolean p0);
    public abstract int x();
    public abstract Arya$AryaDeviceInfo[] x(int p0);
    public abstract int y();
    public abstract int z();
}
