package lg.g;
import java.lang.Object;
import com.facebook.yoga.YogaEdge;
import lg.i;
import lg.e;
import com.facebook.yoga.YogaOverflow;
import com.facebook.yoga.YogaPositionType;
import com.facebook.yoga.YogaDirection;
import com.facebook.yoga.YogaWrap;
import com.facebook.yoga.YogaAlign;
import lg.a;
import com.facebook.yoga.YogaDisplay;
import com.facebook.yoga.YogaFlexDirection;
import com.facebook.yoga.YogaJustify;

public abstract class g	// class@002556
{

    public void g(){
       super();
    }
    public abstract float A();
    public abstract void A0(float p0);
    public abstract float B();
    public abstract void B0(float p0);
    public abstract float C();
    public abstract void C0(float p0);
    public abstract i D(YogaEdge p0);
    public abstract void D0(e p0);
    public abstract i E();
    public abstract void E0(float p0);
    public abstract i F();
    public abstract void F0(float p0);
    public abstract i G();
    public abstract void G0(float p0);
    public abstract i H();
    public abstract void H0(float p0);
    public abstract YogaOverflow I();
    public abstract void I0(YogaOverflow p0);
    public abstract g J();
    public abstract void J0(YogaEdge p0,float p1);
    public abstract i K(YogaEdge p0);
    public abstract void K0(YogaEdge p0,float p1);
    public abstract g L();
    public abstract void L0(YogaEdge p0,float p1);
    public abstract i M(YogaEdge p0);
    public abstract void M0(YogaEdge p0,float p1);
    public abstract YogaPositionType N();
    public abstract void N0(YogaPositionType p0);
    public abstract YogaDirection O();
    public abstract void O0(float p0);
    public abstract i P();
    public abstract void P0();
    public abstract YogaWrap Q();
    public abstract void Q0(float p0);
    public abstract boolean R();
    public abstract void R0(YogaWrap p0);
    public abstract int S(g p0);
    public abstract boolean T();
    public abstract boolean U();
    public abstract boolean V();
    public abstract boolean W();
    public abstract void X();
    public abstract void Y();
    public abstract g Z(int p0);
    public abstract void a(g p0,int p1);
    public abstract void a0();
    public abstract void b(float p0,float p1);
    public abstract void b0(YogaAlign p0);
    public abstract g c();
    public abstract void c0(YogaAlign p0);
    public abstract void d(g p0);
    public abstract void d0(YogaAlign p0);
    public abstract void e();
    public abstract void e0(float p0);
    public abstract YogaAlign f();
    public abstract void f0(a p0);
    public abstract YogaAlign g();
    public abstract void g0(YogaEdge p0,float p1);
    public abstract YogaAlign h();
    public abstract void h0(Object p0);
    public abstract float i();
    public abstract void i0(YogaDirection p0);
    public abstract float j(YogaEdge p0);
    public abstract void j0(YogaDisplay p0);
    public abstract g k(int p0);
    public abstract void k0(float p0);
    public abstract int l();
    public abstract void l0(float p0);
    public abstract Object m();
    public abstract void m0();
    public abstract YogaDisplay n();
    public abstract void n0(float p0);
    public abstract float o();
    public abstract void o0(YogaFlexDirection p0);
    public abstract i p();
    public abstract void p0(float p0);
    public abstract YogaFlexDirection q();
    public abstract void q0(float p0);
    public abstract float r();
    public abstract void r0(float p0);
    public abstract float s();
    public abstract void s0();
    public abstract i t();
    public abstract void t0(float p0);
    public abstract YogaJustify u();
    public abstract void u0(boolean p0);
    public abstract float v(YogaEdge p0);
    public abstract void v0(YogaJustify p0);
    public abstract YogaDirection w();
    public abstract void w0(YogaEdge p0,float p1);
    public abstract float x();
    public abstract void x0(YogaEdge p0);
    public abstract float y(YogaEdge p0);
    public abstract void y0(YogaEdge p0,float p1);
    public abstract float z(YogaEdge p0);
    public abstract void z0(float p0);
}
