package com.kwai.video.westeros.models.EffectDescriptionOrBuilder;
import com.google.protobuf.MessageLiteOrBuilder;
import java.lang.String;
import com.kwai.video.westeros.models.AdjustIntensityConfig;
import com.kwai.video.westeros.models.ARConfig;
import com.kwai.video.westeros.models.ARSpec;
import com.google.protobuf.ByteString;
import java.util.Map;
import com.kwai.video.westeros.models.CameraFacing;
import com.kwai.video.westeros.models.CaptureOriginalConfig;
import com.kwai.video.westeros.models.EditAudioType;
import com.kwai.video.westeros.models.EffectPerformance;
import java.util.List;
import com.kwai.video.westeros.models.EmbeddedPickingMedia;
import com.kwai.video.westeros.models.GuideConfig;
import com.kwai.video.westeros.models.ImageLocaleTips;
import com.kwai.video.westeros.models.TriggerInputTextGroupConfig;
import com.kwai.video.westeros.models.LookupConfig;
import com.kwai.video.westeros.models.PickMoreMediaInfo;
import com.kwai.video.westeros.models.PickingVideoConfig;
import com.kwai.video.westeros.models.PopupWindowConfig;
import com.kwai.video.westeros.models.TitleDatas;
import com.kwai.video.westeros.models.EffectErrorCode;
import com.kwai.video.westeros.models.EffectSlot;
import com.kwai.video.westeros.models.ServerProcessingInfo;
import com.kwai.video.westeros.models.TriggerInputTextConfig;
import com.kwai.video.westeros.models.VideoLength;

public interface abstract EffectDescriptionOrBuilder implements MessageLiteOrBuilder	// class@000f17
{

    boolean containsBackCameraLocaleTips(String p0);
    boolean containsCustomStickerJson(String p0);
    boolean containsFrontCameraLocaleTips(String p0);
    boolean containsGuideConfig(String p0);
    boolean containsLocaleTips(String p0);
    boolean containsPopupWindowDisplayTitles(String p0);
    boolean containsTopic(String p0);
    int getActivityId();
    AdjustIntensityConfig getAdjustIntensityConfig();
    int getAndroidFrameworkVersion();
    ARConfig getArConfig();
    ARSpec getArSpec();
    int getArSpecValue();
    String getAudioPath();
    ByteString getAudioPathBytes();
    double getAudioPosition();
    Map getBackCameraLocaleTips();
    int getBackCameraLocaleTipsCount();
    Map getBackCameraLocaleTipsMap();
    String getBackCameraLocaleTipsOrDefault(String p0,String p1);
    String getBackCameraLocaleTipsOrThrow(String p0);
    CameraFacing getCameraFacing();
    int getCameraFacingValue();
    CaptureOriginalConfig getCaptureOriginalConfig();
    Map getCustomStickerJson();
    int getCustomStickerJsonCount();
    Map getCustomStickerJsonMap();
    String getCustomStickerJsonOrDefault(String p0,String p1);
    String getCustomStickerJsonOrThrow(String p0);
    boolean getDefaultCountdown();
    int getDelayRecordTime();
    boolean getDisableBackgroundMusic();
    boolean getDisableCustomBeautify();
    boolean getDisableCustomColorFilter();
    boolean getDisableCustomDeform();
    boolean getDisableCustomMakeup();
    boolean getDisableCustomSlimming();
    EditAudioType getEditAudioType();
    int getEditAudioTypeValue();
    boolean getEffectHasAudio();
    boolean getEffectLoadFailed();
    EffectPerformance getEffectPerformance();
    int getEffectPerformanceValue();
    String getEffects(int p0);
    ByteString getEffectsBytes(int p0);
    int getEffectsCount();
    List getEffectsList();
    EmbeddedPickingMedia getEmbeddedPickingMedias(int p0);
    int getEmbeddedPickingMediasCount();
    List getEmbeddedPickingMediasList();
    boolean getEnableVideoStabilization();
    boolean getEraseAudio();
    String getFaceMagicEncodeProfile();
    ByteString getFaceMagicEncodeProfileBytes();
    Map getFrontCameraLocaleTips();
    int getFrontCameraLocaleTipsCount();
    Map getFrontCameraLocaleTipsMap();
    String getFrontCameraLocaleTipsOrDefault(String p0,String p1);
    String getFrontCameraLocaleTipsOrThrow(String p0);
    float getGiftDisplayTime();
    Map getGuideConfig();
    int getGuideConfigCount();
    Map getGuideConfigMap();
    GuideConfig getGuideConfigOrDefault(String p0,GuideConfig p1);
    GuideConfig getGuideConfigOrThrow(String p0);
    boolean getHasBoomgameEffect();
    boolean getHasMmuVoiceChange();
    ImageLocaleTips getImageLocaleTips();
    TriggerInputTextGroupConfig getInputTextGroupInfo();
    boolean getIsMemojiEffect();
    boolean getKeepAlive();
    Map getLocaleTips();
    int getLocaleTipsCount();
    Map getLocaleTipsMap();
    String getLocaleTipsOrDefault(String p0,String p1);
    String getLocaleTipsOrThrow(String p0);
    LookupConfig getLookupConfig();
    PickMoreMediaInfo getMediaInfo();
    String getMemojiStyleConfigJson();
    ByteString getMemojiStyleConfigJsonBytes();
    boolean getNeedClientWorkProcess();
    boolean getNeedLocation();
    boolean getNeedMusicWave();
    boolean getNeedPickFirstMedia();
    int getNeedPickMediaResourceType();
    boolean getNeedPinch();
    boolean getNeedReversePlay();
    boolean getNeedSubFrame();
    boolean getNeedSwapFace();
    boolean getNeedSwipe();
    boolean getNeedTouch();
    boolean getOrientationLocked();
    PickingVideoConfig getPickingVideoConfig();
    PopupWindowConfig getPopupConfig(int p0);
    int getPopupConfigCount();
    List getPopupConfigList();
    Map getPopupWindowDisplayTitles();
    int getPopupWindowDisplayTitlesCount();
    Map getPopupWindowDisplayTitlesMap();
    TitleDatas getPopupWindowDisplayTitlesOrDefault(String p0,TitleDatas p1);
    TitleDatas getPopupWindowDisplayTitlesOrThrow(String p0);
    EffectErrorCode getRenderCode();
    String getRenderCodeReason();
    ByteString getRenderCodeReasonBytes();
    int getRenderCodeValue();
    EffectSlot getRenderSlot();
    int getRenderSlotValue();
    boolean getRequireFacialReco();
    boolean getRequirePreviewLayerRender();
    boolean getResetWhenRecord();
    ServerProcessingInfo getServerProcessingInfo();
    int getSubCount();
    String getSwapFaceEmbededIcon(int p0);
    ByteString getSwapFaceEmbededIconBytes(int p0);
    int getSwapFaceEmbededIconCount();
    List getSwapFaceEmbededIconList();
    String getSwapFaceEmbededImages(int p0);
    ByteString getSwapFaceEmbededImagesBytes(int p0);
    int getSwapFaceEmbededImagesCount();
    List getSwapFaceEmbededImagesList();
    Map getTopic();
    int getTopicCount();
    Map getTopicMap();
    String getTopicOrDefault(String p0,String p1);
    String getTopicOrThrow(String p0);
    long getTrackId();
    TriggerInputTextConfig getTriggerInputTextConfig();
    TriggerInputTextConfig getTriggerInputTextsConfig(int p0);
    int getTriggerInputTextsConfigCount();
    List getTriggerInputTextsConfigList();
    boolean getUseAudioStream();
    boolean getUseClientTimeStamp();
    boolean getUseLastFrameForCover();
    VideoLength getVideoLength();
    int getVideoLengthMs();
    int getVideoLengthValue();
    boolean hasAdjustIntensityConfig();
    boolean hasArConfig();
    boolean hasCaptureOriginalConfig();
    boolean hasImageLocaleTips();
    boolean hasInputTextGroupInfo();
    boolean hasLookupConfig();
    boolean hasMediaInfo();
    boolean hasPickingVideoConfig();
    boolean hasServerProcessingInfo();
    boolean hasTriggerInputTextConfig();
}
