package com.yxcorp.gifshow.plugin.impl.SharePlugin.KwaiOp;
import java.lang.Enum;
import java.lang.String;
import java.lang.Object;
import java.lang.Class;
import com.kwai.robust.PatchProxy;
import com.kwai.robust.PatchProxyResult;
import java.lang.CharSequence;
import com.yxcorp.utility.TextUtils;

public final class KwaiOp extends Enum	// class@000fb9
{
    public String mName;
    public static final KwaiOp[] $VALUES;
    public static final KwaiOp AUTHOR_BLACK;
    public static final KwaiOp AUTHOR_UNFOLLOW;
    public static final KwaiOp AUTO_MODE;
    public static final KwaiOp BLOCK;
    public static final KwaiOp CANCEL;
    public static final KwaiOp COPY_LINK;
    public static final KwaiOp EDIT_PHOTO;
    public static final KwaiOp FANS_PROMOTE;
    public static final KwaiOp FANS_TOP;
    public static final KwaiOp FAVOURITE;
    public static final KwaiOp FORWARD_FACEBOOK;
    public static final KwaiOp FORWARD_IMFRIEND;
    public static final KwaiOp FORWARD_INS;
    public static final KwaiOp FORWARD_MORE_SYSTEM_SHARE;
    public static final KwaiOp FORWARD_QQ;
    public static final KwaiOp FORWARD_QZONE;
    public static final KwaiOp FORWARD_WECHAT_FRIEND;
    public static final KwaiOp FORWARD_WECHAT_MOMENT;
    public static final KwaiOp FORWARD_WECHAT_WOW;
    public static final KwaiOp FORWARD_WEIBO;
    public static final KwaiOp FORWARD_YOUTUBE;
    public static final KwaiOp HIGH_QUALITY_FEEDBACK;
    public static final KwaiOp LIVE_FANS_TOP_LIVE_PROMOTION;
    public static final KwaiOp LIVE_SHARE_FOLLOWER;
    public static final KwaiOp LIVE_STREAM_FRAGMENT;
    public static final KwaiOp LIVE_STREAM_PROMOTION;
    public static final KwaiOp MOMENT;
    public static final KwaiOp NONE;
    public static final KwaiOp PHOTO_ALLOW_REWARD;
    public static final KwaiOp PHOTO_COLLECTION;
    public static final KwaiOp PHOTO_COMMENT_LIMIT;
    public static final KwaiOp PHOTO_DELETE;
    public static final KwaiOp PHOTO_DISLIKE;
    public static final KwaiOp PHOTO_DOWNLOAD;
    public static final KwaiOp PHOTO_FEEDBACK;
    public static final KwaiOp PHOTO_FOLLOW_SHOOT;
    public static final KwaiOp PHOTO_FRIENDS;
    public static final KwaiOp PHOTO_INFORM;
    public static final KwaiOp PHOTO_KTV_CHORUS;
    public static final KwaiOp PHOTO_KTV_RECORD;
    public static final KwaiOp PHOTO_LIPS_SYNC;
    public static final KwaiOp PHOTO_PRIVATE;
    public static final KwaiOp PHOTO_PUBLIC;
    public static final KwaiOp PHOTO_QUESTION;
    public static final KwaiOp PHOTO_REDUCE;
    public static final KwaiOp PHOTO_REWARDV2;
    public static final KwaiOp PHOTO_SAME_FRAME;
    public static final KwaiOp PHOTO_TOP_CANCEL;
    public static final KwaiOp PHOTO_TOP_SET;
    public static final KwaiOp PHOTO_TOP_TAG;
    public static final KwaiOp PHOTO_UNPICK_TAG;
    public static final KwaiOp PHOTO_UNTOP_TAG;
    public static final KwaiOp PHOTO_USE_MAGIC;
    public static final KwaiOp PHOTO_USE_MUSIC;
    public static final KwaiOp PHOTO_USE_SOUNDTRACK;
    public static final KwaiOp QR_CODE;
    public static final KwaiOp REPORT_ACCOUNT;
    public static final KwaiOp SAVE_ALBUM;
    public static final KwaiOp THANOS_PHOTO_ALLOW_REWARD;
    public static final KwaiOp UNBLOCK;
    public static final KwaiOp UNFAVOURITE;
    public static final KwaiOp VIDEO_DISABLE_RECREATION;
    public static final KwaiOp VIDEO_QUALITY_SWITCH;
    public static final KwaiOp VIDEO_RECREATION;
    public static final KwaiOp WALL_PAPER_ENTRANCE;

    static {
       KwaiOp kwaiOp = new KwaiOp("AUTHOR_BLACK", 0, "authorBlack");
       KwaiOp.AUTHOR_BLACK = kwaiOp;
       KwaiOp kwaiOp1 = new KwaiOp("AUTHOR_UNFOLLOW", 1, "authorUnfollow");
       KwaiOp.AUTHOR_UNFOLLOW = kwaiOp1;
       KwaiOp kwaiOp2 = new KwaiOp("COPY_LINK", 2, "copyLink");
       KwaiOp.COPY_LINK = kwaiOp2;
       KwaiOp kwaiOp3 = new KwaiOp("UNBLOCK", 3, "unblock");
       KwaiOp.UNBLOCK = kwaiOp3;
       KwaiOp kwaiOp4 = new KwaiOp("BLOCK", 4, "block");
       KwaiOp.BLOCK = kwaiOp4;
       KwaiOp kwaiOp5 = new KwaiOp("FAVOURITE", 5, "favourite");
       KwaiOp.FAVOURITE = kwaiOp5;
       KwaiOp kwaiOp6 = new KwaiOp("UNFAVOURITE", 6, "unfavourite");
       KwaiOp.UNFAVOURITE = kwaiOp6;
       KwaiOp kwaiOp7 = new KwaiOp("REPORT_ACCOUNT", 7, "reportAccount");
       KwaiOp.REPORT_ACCOUNT = kwaiOp7;
       KwaiOp kwaiOp8 = new KwaiOp("AUTO_MODE", 8, "autoMode");
       KwaiOp.AUTO_MODE = kwaiOp8;
       KwaiOp kwaiOp9 = new KwaiOp("FANS_TOP", 9, "fansTop");
       KwaiOp.FANS_TOP = kwaiOp9;
       KwaiOp kwaiOp10 = new KwaiOp("LIVE_STREAM_PROMOTION", 10, "liveStreamPromotion");
       KwaiOp.LIVE_STREAM_PROMOTION = kwaiOp10;
       KwaiOp kwaiOp11 = new KwaiOp("LIVE_SHARE_FOLLOWER", 11, "");
       KwaiOp.LIVE_SHARE_FOLLOWER = kwaiOp11;
       KwaiOp kwaiOp12 = new KwaiOp("PHOTO_DELETE", 12, "photoDelete");
       KwaiOp.PHOTO_DELETE = kwaiOp12;
       KwaiOp kwaiOp13 = kwaiOp12;
       KwaiOp kwaiOp14 = new KwaiOp("PHOTO_DOWNLOAD", 13, "photoDownload");
       KwaiOp.PHOTO_DOWNLOAD = kwaiOp14;
       KwaiOp kwaiOp15 = kwaiOp14;
       kwaiOp12 = new KwaiOp("VIDEO_QUALITY_SWITCH", 14, "videoQualitySwitch");
       KwaiOp.VIDEO_QUALITY_SWITCH = kwaiOp12;
       KwaiOp kwaiOp16 = kwaiOp12;
       kwaiOp14 = new KwaiOp("WALL_PAPER_ENTRANCE", 15, "wallPaperEntrance");
       KwaiOp.WALL_PAPER_ENTRANCE = kwaiOp14;
       KwaiOp kwaiOp17 = kwaiOp14;
       kwaiOp12 = new KwaiOp("PHOTO_REWARDV2", 16, "photoRewardv2");
       KwaiOp.PHOTO_REWARDV2 = kwaiOp12;
       KwaiOp kwaiOp18 = kwaiOp12;
       kwaiOp14 = new KwaiOp("PHOTO_INFORM", 17, "photoInform");
       KwaiOp.PHOTO_INFORM = kwaiOp14;
       KwaiOp kwaiOp19 = kwaiOp14;
       kwaiOp12 = new KwaiOp("PHOTO_PRIVATE", 18, "photoPrivate");
       KwaiOp.PHOTO_PRIVATE = kwaiOp12;
       KwaiOp kwaiOp20 = kwaiOp12;
       kwaiOp14 = new KwaiOp("PHOTO_FRIENDS", 19, "photoFriends");
       KwaiOp.PHOTO_FRIENDS = kwaiOp14;
       KwaiOp kwaiOp21 = kwaiOp14;
       kwaiOp12 = new KwaiOp("PHOTO_PUBLIC", 20, "photoPublic");
       KwaiOp.PHOTO_PUBLIC = kwaiOp12;
       KwaiOp kwaiOp22 = kwaiOp12;
       kwaiOp14 = new KwaiOp("PHOTO_QUESTION", 21, "photoQuestion");
       KwaiOp.PHOTO_QUESTION = kwaiOp14;
       KwaiOp kwaiOp23 = kwaiOp14;
       kwaiOp12 = new KwaiOp("PHOTO_REDUCE", 22, "photoReduce");
       KwaiOp.PHOTO_REDUCE = kwaiOp12;
       KwaiOp kwaiOp24 = kwaiOp12;
       kwaiOp14 = new KwaiOp("PHOTO_SAME_FRAME", 23, "photoSameFrame");
       KwaiOp.PHOTO_SAME_FRAME = kwaiOp14;
       KwaiOp kwaiOp25 = kwaiOp14;
       kwaiOp12 = new KwaiOp("PHOTO_KTV_CHORUS", 24, "photoChorus");
       KwaiOp.PHOTO_KTV_CHORUS = kwaiOp12;
       KwaiOp kwaiOp26 = kwaiOp12;
       kwaiOp14 = new KwaiOp("PHOTO_KTV_RECORD", 25, "photoKtvRecord");
       KwaiOp.PHOTO_KTV_RECORD = kwaiOp14;
       KwaiOp kwaiOp27 = kwaiOp14;
       kwaiOp12 = new KwaiOp("PHOTO_FOLLOW_SHOOT", 26, "photoFollowShoot");
       KwaiOp.PHOTO_FOLLOW_SHOOT = kwaiOp12;
       KwaiOp kwaiOp28 = kwaiOp12;
       kwaiOp14 = new KwaiOp("VIDEO_RECREATION", 27, "videoRecreation");
       KwaiOp.VIDEO_RECREATION = kwaiOp14;
       KwaiOp kwaiOp29 = kwaiOp14;
       kwaiOp12 = new KwaiOp("VIDEO_DISABLE_RECREATION", 28, "videoDisableRecreation");
       KwaiOp.VIDEO_DISABLE_RECREATION = kwaiOp12;
       KwaiOp kwaiOp30 = kwaiOp12;
       kwaiOp14 = new KwaiOp("PHOTO_LIPS_SYNC", 29, "photoLipsSync");
       KwaiOp.PHOTO_LIPS_SYNC = kwaiOp14;
       KwaiOp kwaiOp31 = kwaiOp14;
       kwaiOp12 = new KwaiOp("PHOTO_FEEDBACK", 30, "photoFeedback");
       KwaiOp.PHOTO_FEEDBACK = kwaiOp12;
       KwaiOp kwaiOp32 = kwaiOp12;
       kwaiOp14 = new KwaiOp("PHOTO_USE_MUSIC", 31, "photoMusic");
       KwaiOp.PHOTO_USE_MUSIC = kwaiOp14;
       KwaiOp kwaiOp33 = kwaiOp14;
       kwaiOp12 = new KwaiOp("PHOTO_USE_SOUNDTRACK", 32, "photoSoundTrack");
       KwaiOp.PHOTO_USE_SOUNDTRACK = kwaiOp12;
       KwaiOp kwaiOp34 = kwaiOp12;
       kwaiOp14 = new KwaiOp("PHOTO_USE_MAGIC", 33, "photoMagic");
       KwaiOp.PHOTO_USE_MAGIC = kwaiOp14;
       KwaiOp kwaiOp35 = kwaiOp14;
       kwaiOp12 = new KwaiOp("PHOTO_TOP_SET", 34, "set_top");
       KwaiOp.PHOTO_TOP_SET = kwaiOp12;
       KwaiOp kwaiOp36 = kwaiOp12;
       kwaiOp14 = new KwaiOp("PHOTO_TOP_CANCEL", 35, "cancel_top");
       KwaiOp.PHOTO_TOP_CANCEL = kwaiOp14;
       kwaiOp12 = new KwaiOp("PHOTO_TOP_TAG", 36);
       KwaiOp.PHOTO_TOP_TAG = kwaiOp12;
       KwaiOp kwaiOp37 = kwaiOp12;
       KwaiOp kwaiOp38 = new KwaiOp("CANCEL", 37);
       KwaiOp.CANCEL = kwaiOp38;
       KwaiOp kwaiOp39 = kwaiOp38;
       kwaiOp12 = new KwaiOp("PHOTO_UNTOP_TAG", 38);
       KwaiOp.PHOTO_UNTOP_TAG = kwaiOp12;
       KwaiOp kwaiOp40 = kwaiOp12;
       kwaiOp38 = new KwaiOp("PHOTO_UNPICK_TAG", 39);
       KwaiOp.PHOTO_UNPICK_TAG = kwaiOp38;
       KwaiOp kwaiOp41 = kwaiOp38;
       KwaiOp kwaiOp42 = kwaiOp14;
       kwaiOp12 = new KwaiOp("PHOTO_COLLECTION", 40, "photoCollection");
       KwaiOp.PHOTO_COLLECTION = kwaiOp12;
       KwaiOp kwaiOp43 = kwaiOp12;
       kwaiOp14 = new KwaiOp("FORWARD_QQ", 41, "qq");
       KwaiOp.FORWARD_QQ = kwaiOp14;
       KwaiOp kwaiOp44 = kwaiOp14;
       kwaiOp12 = new KwaiOp("FORWARD_QZONE", 42, "qzone");
       KwaiOp.FORWARD_QZONE = kwaiOp12;
       KwaiOp kwaiOp45 = kwaiOp12;
       kwaiOp14 = new KwaiOp("FORWARD_WECHAT_FRIEND", 43, "wechat");
       KwaiOp.FORWARD_WECHAT_FRIEND = kwaiOp14;
       KwaiOp kwaiOp46 = kwaiOp14;
       kwaiOp12 = new KwaiOp("FORWARD_WECHAT_MOMENT", 44, "wechatMoment");
       KwaiOp.FORWARD_WECHAT_MOMENT = kwaiOp12;
       KwaiOp kwaiOp47 = kwaiOp12;
       kwaiOp14 = new KwaiOp("FORWARD_WECHAT_WOW", 45, "wechatWow");
       KwaiOp.FORWARD_WECHAT_WOW = kwaiOp14;
       KwaiOp kwaiOp48 = kwaiOp14;
       kwaiOp12 = new KwaiOp("FORWARD_FACEBOOK", 46, "facebook");
       KwaiOp.FORWARD_FACEBOOK = kwaiOp12;
       KwaiOp kwaiOp49 = kwaiOp12;
       kwaiOp14 = new KwaiOp("FORWARD_INS", 47, "ins");
       KwaiOp.FORWARD_INS = kwaiOp14;
       KwaiOp kwaiOp50 = kwaiOp14;
       kwaiOp12 = new KwaiOp("FORWARD_IMFRIEND", 48, "imfriend");
       KwaiOp.FORWARD_IMFRIEND = kwaiOp12;
       KwaiOp kwaiOp51 = kwaiOp12;
       kwaiOp14 = new KwaiOp("FORWARD_WEIBO", 49, "weibo");
       KwaiOp.FORWARD_WEIBO = kwaiOp14;
       KwaiOp kwaiOp52 = kwaiOp14;
       kwaiOp12 = new KwaiOp("FORWARD_MORE_SYSTEM_SHARE", 50, "more");
       KwaiOp.FORWARD_MORE_SYSTEM_SHARE = kwaiOp12;
       KwaiOp kwaiOp53 = kwaiOp12;
       kwaiOp14 = new KwaiOp("FORWARD_YOUTUBE", 51, "youtube");
       KwaiOp.FORWARD_YOUTUBE = kwaiOp14;
       KwaiOp kwaiOp54 = kwaiOp14;
       kwaiOp12 = new KwaiOp("SAVE_ALBUM", 52, "download");
       KwaiOp.SAVE_ALBUM = kwaiOp12;
       KwaiOp kwaiOp55 = kwaiOp12;
       kwaiOp14 = new KwaiOp("FANS_PROMOTE", 53, "fansPromote");
       KwaiOp.FANS_PROMOTE = kwaiOp14;
       kwaiOp12 = new KwaiOp("LIVE_FANS_TOP_LIVE_PROMOTION", 54);
       KwaiOp.LIVE_FANS_TOP_LIVE_PROMOTION = kwaiOp12;
       KwaiOp kwaiOp56 = kwaiOp12;
       kwaiOp38 = new KwaiOp("EDIT_PHOTO", 55);
       KwaiOp.EDIT_PHOTO = kwaiOp38;
       KwaiOp kwaiOp57 = kwaiOp38;
       kwaiOp12 = new KwaiOp("MOMENT", 56);
       KwaiOp.MOMENT = kwaiOp12;
       KwaiOp kwaiOp58 = kwaiOp12;
       KwaiOp kwaiOp59 = kwaiOp14;
       kwaiOp38 = new KwaiOp("HIGH_QUALITY_FEEDBACK", 57, "high_quality_feedback");
       KwaiOp.HIGH_QUALITY_FEEDBACK = kwaiOp38;
       KwaiOp kwaiOp60 = kwaiOp38;
       kwaiOp14 = new KwaiOp("PHOTO_DISLIKE", 58, "photo_dislike");
       KwaiOp.PHOTO_DISLIKE = kwaiOp14;
       KwaiOp kwaiOp61 = kwaiOp14;
       kwaiOp12 = new KwaiOp("LIVE_STREAM_FRAGMENT", 59, "liveStreamFragment");
       KwaiOp.LIVE_STREAM_FRAGMENT = kwaiOp12;
       KwaiOp kwaiOp62 = kwaiOp12;
       kwaiOp14 = new KwaiOp("NONE", 60, "none");
       KwaiOp.NONE = kwaiOp14;
       KwaiOp kwaiOp63 = kwaiOp14;
       kwaiOp12 = new KwaiOp("QR_CODE", 61, "faceToFaceQRCode");
       KwaiOp.QR_CODE = kwaiOp12;
       KwaiOp kwaiOp64 = kwaiOp12;
       kwaiOp14 = new KwaiOp("PHOTO_COMMENT_LIMIT", 62, "photoCommentLimit");
       KwaiOp.PHOTO_COMMENT_LIMIT = kwaiOp14;
       KwaiOp kwaiOp65 = kwaiOp14;
       kwaiOp12 = new KwaiOp("PHOTO_ALLOW_REWARD", 63, "photoAllowReward");
       KwaiOp.PHOTO_ALLOW_REWARD = kwaiOp12;
       KwaiOp kwaiOp66 = kwaiOp12;
       kwaiOp14 = new KwaiOp("THANOS_PHOTO_ALLOW_REWARD", 64, "thanosPhotoAllowReward");
       KwaiOp.THANOS_PHOTO_ALLOW_REWARD = kwaiOp14;
       KwaiOp[] kwaiOpArray = new KwaiOp[65];
       kwaiOpArray[0] = kwaiOp;
       kwaiOpArray[1] = kwaiOp1;
       kwaiOpArray[2] = kwaiOp2;
       kwaiOpArray[3] = kwaiOp3;
       kwaiOpArray[4] = kwaiOp4;
       kwaiOpArray[5] = kwaiOp5;
       kwaiOpArray[6] = kwaiOp6;
       kwaiOpArray[7] = kwaiOp7;
       kwaiOpArray[8] = kwaiOp8;
       kwaiOpArray[9] = kwaiOp9;
       kwaiOpArray[10] = kwaiOp10;
       kwaiOpArray[11] = kwaiOp11;
       kwaiOpArray[12] = kwaiOp13;
       kwaiOpArray[13] = kwaiOp15;
       kwaiOpArray[14] = kwaiOp16;
       kwaiOpArray[15] = kwaiOp17;
       kwaiOpArray[16] = kwaiOp18;
       kwaiOpArray[17] = kwaiOp19;
       kwaiOpArray[18] = kwaiOp20;
       kwaiOpArray[19] = kwaiOp21;
       kwaiOpArray[20] = kwaiOp22;
       kwaiOpArray[21] = kwaiOp23;
       kwaiOpArray[22] = kwaiOp24;
       kwaiOpArray[23] = kwaiOp25;
       kwaiOpArray[24] = kwaiOp26;
       kwaiOpArray[25] = kwaiOp27;
       kwaiOpArray[26] = kwaiOp28;
       kwaiOpArray[27] = kwaiOp29;
       kwaiOpArray[28] = kwaiOp30;
       kwaiOpArray[29] = kwaiOp31;
       kwaiOpArray[30] = kwaiOp32;
       kwaiOpArray[31] = kwaiOp33;
       kwaiOpArray[32] = kwaiOp34;
       kwaiOpArray[33] = kwaiOp35;
       kwaiOpArray[34] = kwaiOp36;
       kwaiOpArray[35] = kwaiOp42;
       kwaiOpArray[36] = kwaiOp37;
       kwaiOpArray[37] = kwaiOp39;
       kwaiOpArray[38] = kwaiOp40;
       kwaiOpArray[39] = kwaiOp41;
       kwaiOpArray[40] = kwaiOp43;
       kwaiOpArray[41] = kwaiOp44;
       kwaiOpArray[42] = kwaiOp45;
       kwaiOpArray[43] = kwaiOp46;
       kwaiOpArray[44] = kwaiOp47;
       kwaiOpArray[45] = kwaiOp48;
       kwaiOpArray[46] = kwaiOp49;
       kwaiOpArray[47] = kwaiOp50;
       kwaiOpArray[48] = kwaiOp51;
       kwaiOpArray[49] = kwaiOp52;
       kwaiOpArray[50] = kwaiOp53;
       kwaiOpArray[51] = kwaiOp54;
       kwaiOpArray[52] = kwaiOp55;
       kwaiOpArray[53] = kwaiOp59;
       kwaiOpArray[54] = kwaiOp56;
       kwaiOpArray[55] = kwaiOp57;
       kwaiOpArray[56] = kwaiOp58;
       kwaiOpArray[57] = kwaiOp60;
       kwaiOpArray[58] = kwaiOp61;
       kwaiOpArray[59] = kwaiOp62;
       kwaiOpArray[60] = kwaiOp63;
       kwaiOpArray[61] = kwaiOp64;
       kwaiOpArray[62] = kwaiOp65;
       kwaiOpArray[63] = kwaiOp66;
       kwaiOpArray[64] = kwaiOp14;
       KwaiOp.$VALUES = kwaiOpArray;
    }
    public void KwaiOp(String p0,int p1){
       super(p0, p1, null);
    }
    public void KwaiOp(String p0,int p1,String p2){
       super(p0, p1);
       this.mName = p2;
    }
    public static KwaiOp fromName(String p0){
       object oobject;
       KwaiOp[] obj = PatchProxy.applyOneRefs(p0, null, KwaiOp.class, "3");
       if (obj != PatchProxyResult.class) {
          return obj;
       }
       if (TextUtils.x(p0)) {
          return null;
       }
       obj = KwaiOp.values();
       int len = obj.length;
       int i = 0;
       while (true) {
          if (i >= len) {
             return null;
          }
          oobject = obj[i];
          if (p0.equals(oobject.mName)) {
             break ;
          }else {
             i = i + 1;
          }
       }
       return oobject;
    }
    public static KwaiOp valueOf(String p0){
       Object obj = PatchProxy.applyOneRefs(p0, null, KwaiOp.class, "2");
       if (obj != PatchProxyResult.class) {
          return obj;
       }
       return Enum.valueOf(KwaiOp.class, p0);
    }
    public static KwaiOp[] values(){
       Object obj = PatchProxy.apply(null, null, KwaiOp.class, "1");
       if (obj != PatchProxyResult.class) {
          return obj;
       }
       return KwaiOp.$VALUES.clone();
    }
    public String getName(){
       return this.mName;
    }
}
