package com.yxcorp.gifshow.album.IAlbumMainFragment;
import ga9.a;
import android.view.View;
import com.yxcorp.gifshow.album.IAlbumMainFragment$IPreviewIntentConfig;
import androidx.recyclerview.widget.RecyclerView;
import com.yxcorp.gifshow.album.IAlbumMainFragment$d;
import java.util.List;
import w69.i0;
import com.kwai.moved.ks_page.fragment.KsAlbumTabHostFragment;
import com.yxcorp.gifshow.models.QMedia;
import w69.e0;
import com.yxcorp.gifshow.album.IAlbumMainFragment$a;
import android.widget.FrameLayout;
import java.lang.String;
import com.yxcorp.gifshow.album.selected.interact.a;
import com.yxcorp.gifshow.album.IAlbumMainFragment$c;
import androidx.viewpager.widget.ViewPager;
import com.yxcorp.gifshow.album.IAlbumMainFragment$h;
import com.yxcorp.gifshow.album.IAlbumMainFragment$g;
import w69.l0;
import com.yxcorp.gifshow.album.IAlbumMainFragment$b;
import w69.d0;
import com.yxcorp.gifshow.album.IAlbumMainFragment$f;
import com.yxcorp.gifshow.album.IAlbumMainFragment$e;

public interface abstract IAlbumMainFragment implements a	// class@0019cc
{

    View B3();
    void C8(IAlbumMainFragment$IPreviewIntentConfig p0);
    void Eb();
    void Ec(boolean p0);
    RecyclerView Ed();
    void Gc();
    void Jf(boolean p0);
    void Ma(int p0);
    void Nd(boolean p0);
    void O2();
    boolean R4(boolean p0);
    void S4();
    boolean Sc();
    View Sg();
    void Ta(IAlbumMainFragment$d p0);
    void U6(List p0);
    void Wb(i0 p0);
    KsAlbumTabHostFragment Xe();
    void Y4(List p0);
    void Yc();
    void Zf(float p0);
    void bb(float p0);
    void d3(boolean p0);
    void d7();
    void db(QMedia p0,int p1);
    void e6(boolean p0);
    void e9(boolean p0);
    void f5(e0 p0);
    void f6(IAlbumMainFragment$a p0);
    FrameLayout fa();
    String getTaskId();
    void hd();
    boolean isAdded();
    boolean isVisible();
    void ja();
    a m8();
    int o5();
    void onResume();
    void pd(QMedia p0);
    void pf(IAlbumMainFragment$c p0);
    ViewPager s2();
    void s5(float p0);
    void t3(boolean p0);
    void ta(IAlbumMainFragment$h p0);
    void u3(IAlbumMainFragment$g p0);
    void uc(l0 p0);
    void v5(IAlbumMainFragment$b p0);
    void x3(d0 p0);
    void x4();
    void x6(IAlbumMainFragment$f p0);
    void x8();
    void y5(IAlbumMainFragment$e p0);
    void y8();
}
