package jz8.n;
import y8c.f$b;
import io.reactivex.subjects.PublishSubject;
import java.lang.Integer;
import java.lang.Float;
import java.util.HashSet;
import rd5.e;
import com.kwai.component.photo.detail.core.tag.TagPackageListHelper;
import java.util.ArrayList;
import java.util.LinkedList;
import brd.t;
import androidx.collection.ArraySet;
import brd.y;
import xl8.b;
import java.lang.Boolean;
import java.lang.Object;
import sc6.c;
import com.yxcorp.gifshow.comment.e;
import gr.c;
import java.lang.String;
import java.lang.Class;
import com.kwai.robust.PatchProxy;
import com.kwai.robust.PatchProxyResult;
import jz8.c4;
import java.util.Map;

public class n extends f$b	// class@002a30
{
    public boolean A;
    public boolean A1;
    public PublishSubject B;
    public PublishSubject B1;
    public boolean C;
    public PublishSubject C1;
    public e D;
    public PublishSubject D1;
    public PublishSubject E;
    public PublishSubject E1;
    public boolean F;
    public PublishSubject F1;
    public PublishSubject G;
    public PublishSubject G1;
    public PublishSubject H;
    public b H1;
    public PublishSubject I;
    public boolean I1;
    public PublishSubject J;
    public h J1;
    public PublishSubject K;
    public boolean K1;
    public a L;
    public PublishSubject L1;
    public TagPackageListHelper M;
    public b M1;
    public List N;
    public b N1;
    public List O;
    public PublishSubject O1;
    public final c P;
    public c P1;
    public t Q;
    public ScreenCleanController Q1;
    public PublishSubject R;
    public ScreenCleanController R1;
    public PublishSubject S;
    public ScreenCleanController S1;
    public b0 T;
    public ScreenCleanController T1;
    public PublishSubject U;
    public float U0;
    public ScreenCleanController U1;
    public View$OnClickListener V;
    public int V0;
    public DislikeViewModel V1;
    public PublishSubject W;
    public Set W0;
    public e W1;
    public PublishSubject X;
    public PublishSubject X0;
    public PublishSubject X1;
    public PublishSubject Y;
    public PublishSubject Y0;
    public PublishSubject Y1;
    public float Z;
    public List Z0;
    public PublishSubject Z1;
    public List a1;
    public h a2;
    public List b1;
    public PublishSubject b2;
    public int c1;
    public PublishSubject c2;
    public PublishSubject d1;
    public PublishSubject d2;
    public PublishSubject e1;
    public float e2;
    public PublishSubject f1;
    public c f2;
    public PublishSubject g1;
    public b g2;
    public a h;
    public PublishSubject h1;
    public PublishSubject h2;
    public b i;
    public List i1;
    public String i2;
    public j j;
    public boolean j1;
    public f j2;
    public b k;
    public boolean k1;
    public MagicVideoInfo k2;
    public f4 l;
    public PublishSubject l1;
    public TextureView l2;
    public PublishSubject m;
    public PublishSubject m1;
    public c m2;
    public Integer n;
    public boolean n1;
    public PublishSubject n2;
    public RecyclerView o;
    public PublishSubject o1;
    public PublishSubject o2;
    public PublishSubject p;
    public t p1;
    public PublishSubject q;
    public y q1;
    public Float r;
    public boolean r1;
    public Set s;
    public PublishSubject s1;
    public PublishSubject t;
    public c t1;
    public PublishSubject u;
    public t u1;
    public PublishSubject v;
    public y v1;
    public PublishSubject w;
    public c w1;
    public a0 x;
    public c x1;
    public o y;
    public c y1;
    public boolean z;
    public boolean z1;

    public void n(){
       super();
       this.m = PublishSubject.g();
       this.n = Integer.valueOf(0);
       this.p = PublishSubject.g();
       this.q = PublishSubject.g();
       this.r = Float.valueOf(0x3f800000);
       this.s = new HashSet();
       this.t = PublishSubject.g();
       this.u = PublishSubject.g();
       this.v = PublishSubject.g();
       this.w = PublishSubject.g();
       this.B = PublishSubject.g();
       this.D = new e();
       this.E = PublishSubject.g();
       this.G = PublishSubject.g();
       this.H = PublishSubject.g();
       this.I = PublishSubject.g();
       this.J = PublishSubject.g();
       this.K = PublishSubject.g();
       this.M = new TagPackageListHelper();
       this.N = new ArrayList();
       this.O = new LinkedList();
       PublishSubject publishSubje = PublishSubject.g();
       this.P = publishSubje;
       this.Q = publishSubje.hide();
       this.R = PublishSubject.g();
       this.S = PublishSubject.g();
       this.U = PublishSubject.g();
       this.W = PublishSubject.g();
       this.X = PublishSubject.g();
       this.Y = PublishSubject.g();
       this.W0 = new ArraySet();
       this.X0 = PublishSubject.g();
       this.Y0 = PublishSubject.g();
       this.Z0 = new ArrayList();
       this.a1 = new ArrayList();
       this.b1 = new ArrayList();
       this.d1 = PublishSubject.g();
       this.e1 = PublishSubject.g();
       this.f1 = PublishSubject.g();
       this.g1 = PublishSubject.g();
       this.h1 = PublishSubject.g();
       this.i1 = new ArrayList();
       this.k1 = true;
       this.l1 = PublishSubject.g();
       this.m1 = PublishSubject.g();
       this.o1 = PublishSubject.g();
       publishSubje = PublishSubject.g();
       this.p1 = publishSubje;
       this.q1 = publishSubje;
       this.s1 = PublishSubject.g();
       publishSubje = PublishSubject.g();
       this.u1 = publishSubje;
       this.v1 = publishSubje;
       this.w1 = PublishSubject.g();
       this.x1 = PublishSubject.g();
       this.y1 = PublishSubject.g();
       this.B1 = PublishSubject.g();
       this.C1 = PublishSubject.g();
       this.D1 = PublishSubject.g();
       this.E1 = PublishSubject.g();
       this.F1 = PublishSubject.g();
       this.G1 = PublishSubject.g();
       this.L1 = PublishSubject.g();
       this.M1 = new b(Boolean.FALSE);
       this.N1 = new b(null);
       this.O1 = PublishSubject.g();
       this.P1 = new c();
       this.W1 = new e();
       this.X1 = PublishSubject.g();
       this.Y1 = PublishSubject.g();
       this.Z1 = PublishSubject.g();
       this.b2 = PublishSubject.g();
       this.c2 = PublishSubject.g();
       this.d2 = PublishSubject.g();
       this.e2 = 0x3f800000;
       this.f2 = new c();
       this.h2 = PublishSubject.g();
       this.n2 = PublishSubject.g();
       this.o2 = PublishSubject.g();
    }
    public Object getObjectByTag(String p0){
       Object obj = PatchProxy.applyOneRefs(p0, this, n.class, "3");
       if (obj != PatchProxyResult.class) {
          return obj;
       }
       if (p0.equals("provider")) {
          return new c4();
       }
       return null;
    }
    public Map getObjectsByTag(String p0){
       Map obj = PatchProxy.applyOneRefs(p0, this, n.class, "4");
       if (obj != PatchProxyResult.class) {
          return obj;
       }
       obj = super.getObjectsByTag(p0);
       if (p0.equals("provider")) {
          obj.put(n.class, new c4());
       }else {
          obj.put(n.class, null);
       }
       return obj;
    }
}
