package j69.c;
import java.lang.String;
import brd.g;
import com.yxcorp.gifshow.aicut.api.AICutMusicInfo;
import brd.t;
import com.kwai.video.minecraft.model.EditorSdk2V2$VideoEditorProject;
import java.io.File;
import com.yxcorp.gifshow.aicut.api.AICutGroupType;
import com.kwai.video.minecraft.model.EditorSdk2V2$AudioAsset;
import android.app.Activity;
import i69.i;
import android.graphics.Bitmap;
import com.yxcorp.gifshow.models.QMedia;
import java.util.List;
import com.yxcorp.gifshow.aicut.api.AICutStyle;
import i69.j;

public interface abstract c	// class@002761
{

    void A2(String p0,g p1);
    t B2(AICutMusicInfo p0);
    void C2(EditorSdk2V2$VideoEditorProject p0);
    File D2(String p0);
    AICutGroupType E2();
    AICutMusicInfo F2();
    EditorSdk2V2$AudioAsset G2(EditorSdk2V2$VideoEditorProject p0);
    void H2();
    boolean I2();
    t J0(String p0,double p1,double p2);
    void J2(EditorSdk2V2$VideoEditorProject p0);
    EditorSdk2V2$AudioAsset K2(EditorSdk2V2$VideoEditorProject p0);
    void L2(String p0);
    boolean M2();
    t N2(EditorSdk2V2$VideoEditorProject p0);
    t O2(File p0);
    void a();
    t c2();
    t d2();
    long e2();
    void f2();
    String g2();
    long getMaxDuration();
    boolean h2(Activity p0);
    void i2(AICutMusicInfo p0,i p1);
    t j1(String p0);
    t j2(String p0,double p1,double p2,AICutMusicInfo p3,double p4,boolean p5);
    Bitmap k2();
    void l2(Bitmap p0,Activity p1);
    String m2();
    t n2(QMedia p0);
    t o2(String p0,int p1);
    String p2();
    File q2(AICutMusicInfo p0);
    void r2();
    int s2(EditorSdk2V2$VideoEditorProject p0);
    List t2(EditorSdk2V2$VideoEditorProject p0);
    t u2(String p0);
    void v2();
    boolean w2();
    t x2();
    void y2(AICutStyle p0,j p1);
    t z2(List p0);
}
