package com.kwai.feature.api.live.base.service.pendant.pendantgroup.LivePendantRelation;
import java.lang.Enum;
import java.lang.String;
import java.lang.Object;
import java.lang.Class;
import com.kwai.robust.PatchProxy;
import com.kwai.robust.PatchProxyResult;

public final class LivePendantRelation extends Enum	// class@000fa0
{
    public static final LivePendantRelation[] $VALUES;
    public static final LivePendantRelation ANSWERING_QUESTION;
    public static final LivePendantRelation ASK_QUESTION;
    public static final LivePendantRelation CHAT;
    public static final LivePendantRelation COMMERCIAL_NEO_LIVE_COUPON;
    public static final LivePendantRelation GZOME_FEATURE_PAGER;
    public static final LivePendantRelation GZONE_GAME_PROMOTION;
    public static final LivePendantRelation GZONE_LIVE;
    public static final LivePendantRelation HOUSE_CONSULT_PENDANT;
    public static final LivePendantRelation LARGE_STYLE_ACTIVITY_WIDGET;
    public static final LivePendantRelation LIVE_ANCHOR_CONTENT_PROMOTION;
    public static final LivePendantRelation LIVE_BLIND;
    public static final LivePendantRelation LIVE_INTERACTIVE_GUIDE;
    public static final LivePendantRelation LIVE_LINE;
    public static final LivePendantRelation LIVE_PK;
    public static final LivePendantRelation LIVE_PK_RANK;
    public static final LivePendantRelation LIVE_PK_SMALL_WINDOW;
    public static final LivePendantRelation LIVE_PLUS;
    public static final LivePendantRelation LOCAL_LIFE_HOT_BUBBLE;
    public static final LivePendantRelation LOCAL_LIFE_PENDANT;
    public static final LivePendantRelation MERCHANT_616_NOTICE_PENDANT;
    public static final LivePendantRelation MERCHANT_616_PENDANT;
    public static final LivePendantRelation MERCHANT_DYNAMIC_PENDANT;
    public static final LivePendantRelation MERCHANT_FAST_PAY_BUBBLE;
    public static final LivePendantRelation MERCHANT_INTERPRET;
    public static final LivePendantRelation MERCHANT_SPIKE_PENDANT;
    public static final LivePendantRelation PK_CRITICAL_HIT_ANIMATION;
    public static final LivePendantRelation RECRUIT_EXPLAIN;
    public static final LivePendantRelation RECRUIT_INTERPRET;
    public static final LivePendantRelation RED_PACKET;
    public static final LivePendantRelation SCORE_RANK;
    public static final LivePendantRelation SCREEN_LANDSCAPE;
    public static final LivePendantRelation TUNA_EXPLAIN_PENDANT;
    public static final LivePendantRelation VOICE_PARTY_KTV_ORDER_MUSIC;
    public static final LivePendantRelation VOICE_PARTY_SCENE;
    public static final LivePendantRelation VOICE_PARTY_THEATER_PLAY_LIST;

    static {
       LivePendantRelation livePendantR = new LivePendantRelation("HOUSE_CONSULT_PENDANT", 0);
       LivePendantRelation.HOUSE_CONSULT_PENDANT = livePendantR;
       LivePendantRelation livePendantR1 = new LivePendantRelation("LOCAL_LIFE_PENDANT", 1);
       LivePendantRelation.LOCAL_LIFE_PENDANT = livePendantR1;
       LivePendantRelation livePendantR2 = new LivePendantRelation("MERCHANT_616_PENDANT", 2);
       LivePendantRelation.MERCHANT_616_PENDANT = livePendantR2;
       LivePendantRelation livePendantR3 = new LivePendantRelation("MERCHANT_SPIKE_PENDANT", 3);
       LivePendantRelation.MERCHANT_SPIKE_PENDANT = livePendantR3;
       LivePendantRelation livePendantR4 = new LivePendantRelation("MERCHANT_616_NOTICE_PENDANT", 4);
       LivePendantRelation.MERCHANT_616_NOTICE_PENDANT = livePendantR4;
       LivePendantRelation livePendantR5 = new LivePendantRelation("LIVE_PK_SMALL_WINDOW", 5);
       LivePendantRelation.LIVE_PK_SMALL_WINDOW = livePendantR5;
       LivePendantRelation livePendantR6 = new LivePendantRelation("RED_PACKET", 6);
       LivePendantRelation.RED_PACKET = livePendantR6;
       LivePendantRelation livePendantR7 = new LivePendantRelation("LIVE_PK_RANK", 7);
       LivePendantRelation.LIVE_PK_RANK = livePendantR7;
       LivePendantRelation livePendantR8 = new LivePendantRelation("LIVE_LINE", 8);
       LivePendantRelation.LIVE_LINE = livePendantR8;
       LivePendantRelation livePendantR9 = new LivePendantRelation("LIVE_PK", 9);
       LivePendantRelation.LIVE_PK = livePendantR9;
       LivePendantRelation livePendantR10 = new LivePendantRelation("RECRUIT_EXPLAIN", 10);
       LivePendantRelation.RECRUIT_EXPLAIN = livePendantR10;
       LivePendantRelation livePendantR11 = new LivePendantRelation("CHAT", 11);
       LivePendantRelation.CHAT = livePendantR11;
       LivePendantRelation livePendantR12 = new LivePendantRelation("ANSWERING_QUESTION", 12);
       LivePendantRelation.ANSWERING_QUESTION = livePendantR12;
       LivePendantRelation livePendantR13 = new LivePendantRelation("ASK_QUESTION", 13);
       LivePendantRelation.ASK_QUESTION = livePendantR13;
       LivePendantRelation livePendantR14 = livePendantR13;
       LivePendantRelation livePendantR15 = new LivePendantRelation("VOICE_PARTY_KTV_ORDER_MUSIC", 14);
       LivePendantRelation.VOICE_PARTY_KTV_ORDER_MUSIC = livePendantR15;
       LivePendantRelation livePendantR16 = livePendantR15;
       LivePendantRelation livePendantR17 = new LivePendantRelation("VOICE_PARTY_THEATER_PLAY_LIST", 15);
       LivePendantRelation.VOICE_PARTY_THEATER_PLAY_LIST = livePendantR17;
       LivePendantRelation livePendantR18 = livePendantR17;
       livePendantR13 = new LivePendantRelation("SCORE_RANK", 16);
       LivePendantRelation.SCORE_RANK = livePendantR13;
       LivePendantRelation livePendantR19 = livePendantR13;
       livePendantR15 = new LivePendantRelation("VOICE_PARTY_SCENE", 17);
       LivePendantRelation.VOICE_PARTY_SCENE = livePendantR15;
       LivePendantRelation livePendantR20 = livePendantR15;
       livePendantR17 = new LivePendantRelation("PK_CRITICAL_HIT_ANIMATION", 18);
       LivePendantRelation.PK_CRITICAL_HIT_ANIMATION = livePendantR17;
       LivePendantRelation livePendantR21 = livePendantR17;
       livePendantR13 = new LivePendantRelation("SCREEN_LANDSCAPE", 19);
       LivePendantRelation.SCREEN_LANDSCAPE = livePendantR13;
       LivePendantRelation livePendantR22 = livePendantR13;
       livePendantR15 = new LivePendantRelation("MERCHANT_INTERPRET", 20);
       LivePendantRelation.MERCHANT_INTERPRET = livePendantR15;
       LivePendantRelation livePendantR23 = livePendantR15;
       livePendantR17 = new LivePendantRelation("TUNA_EXPLAIN_PENDANT", 21);
       LivePendantRelation.TUNA_EXPLAIN_PENDANT = livePendantR17;
       LivePendantRelation livePendantR24 = livePendantR17;
       livePendantR13 = new LivePendantRelation("LIVE_BLIND", 22);
       LivePendantRelation.LIVE_BLIND = livePendantR13;
       LivePendantRelation livePendantR25 = livePendantR13;
       livePendantR17 = new LivePendantRelation("RECRUIT_INTERPRET", 23);
       LivePendantRelation.RECRUIT_INTERPRET = livePendantR17;
       LivePendantRelation livePendantR26 = livePendantR17;
       livePendantR15 = new LivePendantRelation("LIVE_INTERACTIVE_GUIDE", 24);
       LivePendantRelation.LIVE_INTERACTIVE_GUIDE = livePendantR15;
       LivePendantRelation livePendantR27 = livePendantR15;
       livePendantR17 = new LivePendantRelation("LARGE_STYLE_ACTIVITY_WIDGET", 25);
       LivePendantRelation.LARGE_STYLE_ACTIVITY_WIDGET = livePendantR17;
       LivePendantRelation livePendantR28 = livePendantR17;
       livePendantR15 = new LivePendantRelation("GZONE_GAME_PROMOTION", 26);
       LivePendantRelation.GZONE_GAME_PROMOTION = livePendantR15;
       LivePendantRelation livePendantR29 = livePendantR15;
       livePendantR17 = new LivePendantRelation("COMMERCIAL_NEO_LIVE_COUPON", 27);
       LivePendantRelation.COMMERCIAL_NEO_LIVE_COUPON = livePendantR17;
       LivePendantRelation livePendantR30 = livePendantR17;
       livePendantR15 = new LivePendantRelation("MERCHANT_DYNAMIC_PENDANT", 28);
       LivePendantRelation.MERCHANT_DYNAMIC_PENDANT = livePendantR15;
       LivePendantRelation livePendantR31 = livePendantR15;
       livePendantR17 = new LivePendantRelation("GZOME_FEATURE_PAGER", 29);
       LivePendantRelation.GZOME_FEATURE_PAGER = livePendantR17;
       LivePendantRelation livePendantR32 = livePendantR17;
       livePendantR15 = new LivePendantRelation("LIVE_ANCHOR_CONTENT_PROMOTION", 30);
       LivePendantRelation.LIVE_ANCHOR_CONTENT_PROMOTION = livePendantR15;
       LivePendantRelation livePendantR33 = livePendantR15;
       livePendantR17 = new LivePendantRelation("GZONE_LIVE", 31);
       LivePendantRelation.GZONE_LIVE = livePendantR17;
       LivePendantRelation livePendantR34 = livePendantR17;
       livePendantR15 = new LivePendantRelation("MERCHANT_FAST_PAY_BUBBLE", 32);
       LivePendantRelation.MERCHANT_FAST_PAY_BUBBLE = livePendantR15;
       LivePendantRelation livePendantR35 = livePendantR15;
       livePendantR17 = new LivePendantRelation("LOCAL_LIFE_HOT_BUBBLE", 33);
       LivePendantRelation.LOCAL_LIFE_HOT_BUBBLE = livePendantR17;
       LivePendantRelation livePendantR36 = livePendantR17;
       livePendantR15 = new LivePendantRelation("LIVE_PLUS", 34);
       LivePendantRelation.LIVE_PLUS = livePendantR15;
       LivePendantRelation[] livePendantR37 = new LivePendantRelation[35];
       livePendantR37[0] = livePendantR;
       livePendantR37[1] = livePendantR1;
       livePendantR37[2] = livePendantR2;
       livePendantR37[3] = livePendantR3;
       livePendantR37[4] = livePendantR4;
       livePendantR37[5] = livePendantR5;
       livePendantR37[6] = livePendantR6;
       livePendantR37[7] = livePendantR7;
       livePendantR37[8] = livePendantR8;
       livePendantR37[9] = livePendantR9;
       livePendantR37[10] = livePendantR10;
       livePendantR37[11] = livePendantR11;
       livePendantR37[12] = livePendantR12;
       livePendantR37[13] = livePendantR14;
       livePendantR37[14] = livePendantR16;
       livePendantR37[15] = livePendantR18;
       livePendantR37[16] = livePendantR19;
       livePendantR37[17] = livePendantR20;
       livePendantR37[18] = livePendantR21;
       livePendantR37[19] = livePendantR22;
       livePendantR37[20] = livePendantR23;
       livePendantR37[21] = livePendantR24;
       livePendantR37[22] = livePendantR25;
       livePendantR37[23] = livePendantR26;
       livePendantR37[24] = livePendantR27;
       livePendantR37[25] = livePendantR28;
       livePendantR37[26] = livePendantR29;
       livePendantR37[27] = livePendantR30;
       livePendantR37[28] = livePendantR31;
       livePendantR37[29] = livePendantR32;
       livePendantR37[30] = livePendantR33;
       livePendantR37[31] = livePendantR34;
       livePendantR37[32] = livePendantR35;
       livePendantR37[33] = livePendantR36;
       livePendantR37[34] = livePendantR15;
       LivePendantRelation.$VALUES = livePendantR37;
    }
    public void LivePendantRelation(String p0,int p1){
       super(p0, p1);
    }
    public static LivePendantRelation valueOf(String p0){
       Object obj = PatchProxy.applyOneRefs(p0, null, LivePendantRelation.class, "2");
       if (obj != PatchProxyResult.class) {
          return obj;
       }
       return Enum.valueOf(LivePendantRelation.class, p0);
    }
    public static LivePendantRelation[] values(){
       Object obj = PatchProxy.apply(null, null, LivePendantRelation.class, "1");
       if (obj != PatchProxyResult.class) {
          return obj;
       }
       return LivePendantRelation.$VALUES.clone();
    }
}
