package xi9.n;
import java.util.Map;
import com.kwai.video.westeros.v2.faceless.FaceMagicController$FaceMagicInputTextsRequestListener;
import com.kwai.video.westeros.v2.faceless.FaceMagicController$FaceMagicPickingServerMediaListener;
import com.yxcorp.gifshow.model.MagicEmoji$SeekBarType;
import java.lang.String;
import java.util.List;
import com.kwai.video.westeros.v2.faceless.FaceMagicController$FaceMagicUserInfoListener;
import elb.k;
import com.kwai.video.westeros.models.AdjustIntensityConfig;
import com.kwai.video.westeros.models.GuideConfig;
import vi9.a;
import com.kwai.video.westeros.models.TitleDatas;
import elb.v;
import com.yxcorp.gifshow.model.MagicEmoji$MagicFace;
import com.kwai.video.westeros.v2.faceless.FaceMagicController$FaceMagicInputTextRequestWithConfigListener;
import com.kwai.video.westeros.v2.faceless.FaceMagicController$FaceMagicLockExposureListener;
import android.view.MotionEvent;
import com.kwai.video.westeros.v2.faceless.FaceMagicController$FaceMagicPickFaceImageListener;
import com.kwai.video.westeros.models.UserInfo;
import com.kwai.video.westeros.models.EffectDescription;
import com.kwai.video.westeros.models.SafeUIArea;

public interface abstract n	// class@00452f
{

    void A(int p0);
    void B(Map p0);
    boolean C();
    boolean D();
    void F(FaceMagicController$FaceMagicInputTextsRequestListener p0);
    void G(FaceMagicController$FaceMagicPickingServerMediaListener p0);
    void H(boolean p0);
    void K();
    void O(float p0,MagicEmoji$SeekBarType p1);
    void P(Map p0);
    boolean Q();
    void S(String p0);
    void T(boolean p0);
    void U(List p0);
    void V();
    boolean Z();
    void b(String p0);
    Map b1();
    String c(boolean p0);
    void c0(String p0,int p1);
    void d(List p0);
    String e();
    void f(FaceMagicController$FaceMagicUserInfoListener p0);
    void f0(k p0);
    List g();
    Map g0();
    int getActivityId();
    AdjustIntensityConfig getAdjustIntensityConfig();
    String getAudioPath();
    String getFaceMagicEncodeProfile();
    GuideConfig getGuideConfig();
    String getInputText();
    String getLanguage();
    String getTopic();
    a getVideoLength();
    void h(int p0,String p1,String p2);
    TitleDatas i();
    void i0(v p0);
    void j(MagicEmoji$MagicFace p0,String p1);
    void j0(long p0);
    void k(List p0);
    void k0(FaceMagicController$FaceMagicInputTextRequestWithConfigListener p0);
    void l();
    List m();
    List m0();
    void n(FaceMagicController$FaceMagicLockExposureListener p0);
    void o(boolean p0);
    void onTouch(MotionEvent p0);
    void p(FaceMagicController$FaceMagicPickFaceImageListener p0);
    boolean p0();
    void q(String p0);
    boolean r();
    void s(UserInfo p0);
    boolean t();
    boolean t0();
    void u(String p0);
    void v(int p0);
    boolean v0();
    boolean w();
    EffectDescription w0();
    void x(SafeUIArea p0);
    boolean y();
    boolean y0();
}
