package k2b.o0;
import com.kuaishou.client.log.packages.nano.ClientLog$ReportEvent;
import q2b.c;
import er.m;
import b3b.a;
import java.lang.String;
import k2b.x1;
import q2b.g;
import java.lang.Long;
import java.util.Map;
import java.util.List;
import k2b.z;

public interface abstract o0	// class@001bb0
{

    boolean A1(ClientLog$ReportEvent p0);
    c B1();
    m C1();
    boolean D1();
    a E1();
    m F1();
    boolean G1();
    String H1();
    int I();
    x1 I1();
    int J1();
    String a();
    boolean b();
    int e();
    boolean g1();
    String getAppName();
    String getChannel();
    String getDeviceId();
    String getGlobalId();
    g getLocation();
    String getOAID();
    String getPackageName();
    int getPlatform();
    String getStyleType();
    Long getUserId();
    String h();
    int h1();
    Map i1();
    String j();
    int j1();
    m k1();
    String l1();
    List m1();
    boolean n1();
    String o1();
    String p1();
    String q();
    String q1(ClientLog$ReportEvent p0);
    int r1();
    m s1();
    Long t1();
    boolean u1();
    String v1();
    String w();
    boolean w1();
    z x1();
    String y1();
    String z1();
}
