package androidx.core.content.ContextCompat$a;
import java.util.HashMap;
import android.os.Build$VERSION;
import android.telephony.SubscriptionManager;
import java.lang.Object;
import android.app.usage.UsageStatsManager;
import android.appwidget.AppWidgetManager;
import android.os.BatteryManager;
import android.hardware.camera2.CameraManager;
import android.app.job.JobScheduler;
import android.content.pm.LauncherApps;
import android.media.projection.MediaProjectionManager;
import android.media.session.MediaSessionManager;
import android.content.RestrictionsManager;
import android.telecom.TelecomManager;
import android.media.tv.TvInputManager;
import android.app.AppOpsManager;
import android.view.accessibility.CaptioningManager;
import android.hardware.ConsumerIrManager;
import android.print.PrintManager;
import android.bluetooth.BluetoothManager;
import android.hardware.display.DisplayManager;
import android.os.UserManager;
import android.hardware.input.InputManager;
import android.media.MediaRouter;
import android.net.nsd.NsdManager;
import android.view.accessibility.AccessibilityManager;
import android.accounts.AccountManager;
import android.app.ActivityManager;
import android.app.AlarmManager;
import android.media.AudioManager;
import android.content.ClipboardManager;
import android.net.ConnectivityManager;
import android.app.admin.DevicePolicyManager;
import android.app.DownloadManager;
import android.os.DropBoxManager;
import android.view.inputmethod.InputMethodManager;
import android.app.KeyguardManager;
import android.view.LayoutInflater;
import android.location.LocationManager;
import android.nfc.NfcManager;
import android.app.NotificationManager;
import android.os.PowerManager;
import android.app.SearchManager;
import android.hardware.SensorManager;
import android.os.storage.StorageManager;
import android.telephony.TelephonyManager;
import android.view.textservice.TextServicesManager;
import android.app.UiModeManager;
import android.hardware.usb.UsbManager;
import android.os.Vibrator;
import android.app.WallpaperManager;
import android.net.wifi.p2p.WifiP2pManager;
import android.net.wifi.WifiManager;
import android.view.WindowManager;

public final class ContextCompat$a	// class@000709
{
    public static final HashMap a;

    static {
       HashMap hashMap = new HashMap();
       ContextCompat$a.a = hashMap;
       if (Build$VERSION.SDK_INT >= 22) {
          hashMap.put(SubscriptionManager.class, "telephony_subscription_service");
          hashMap.put(UsageStatsManager.class, "usagestats");
       }
       hashMap.put(AppWidgetManager.class, "appwidget");
       hashMap.put(BatteryManager.class, "batterymanager");
       hashMap.put(CameraManager.class, "camera");
       hashMap.put(JobScheduler.class, "jobscheduler");
       hashMap.put(LauncherApps.class, "launcherapps");
       hashMap.put(MediaProjectionManager.class, "media_projection");
       hashMap.put(MediaSessionManager.class, "media_session");
       hashMap.put(RestrictionsManager.class, "restrictions");
       hashMap.put(TelecomManager.class, "telecom");
       hashMap.put(TvInputManager.class, "tv_input");
       hashMap.put(AppOpsManager.class, "appops");
       hashMap.put(CaptioningManager.class, "captioning");
       hashMap.put(ConsumerIrManager.class, "consumer_ir");
       hashMap.put(PrintManager.class, "print");
       hashMap.put(BluetoothManager.class, "bluetooth");
       hashMap.put(DisplayManager.class, "display");
       hashMap.put(UserManager.class, "user");
       hashMap.put(InputManager.class, "input");
       hashMap.put(MediaRouter.class, "media_router");
       hashMap.put(NsdManager.class, "servicediscovery");
       hashMap.put(AccessibilityManager.class, "accessibility");
       hashMap.put(AccountManager.class, "account");
       hashMap.put(ActivityManager.class, "activity");
       hashMap.put(AlarmManager.class, "alarm");
       hashMap.put(AudioManager.class, "audio");
       hashMap.put(ClipboardManager.class, "clipboard");
       hashMap.put(ConnectivityManager.class, "connectivity");
       hashMap.put(DevicePolicyManager.class, "device_policy");
       hashMap.put(DownloadManager.class, "download");
       hashMap.put(DropBoxManager.class, "dropbox");
       hashMap.put(InputMethodManager.class, "input_method");
       hashMap.put(KeyguardManager.class, "keyguard");
       hashMap.put(LayoutInflater.class, "layout_inflater");
       hashMap.put(LocationManager.class, "location");
       hashMap.put(NfcManager.class, "nfc");
       hashMap.put(NotificationManager.class, "notification");
       hashMap.put(PowerManager.class, "power");
       hashMap.put(SearchManager.class, "search");
       hashMap.put(SensorManager.class, "sensor");
       hashMap.put(StorageManager.class, "storage");
       hashMap.put(TelephonyManager.class, "phone");
       hashMap.put(TextServicesManager.class, "textservices");
       hashMap.put(UiModeManager.class, "uimode");
       hashMap.put(UsbManager.class, "usb");
       hashMap.put(Vibrator.class, "vibrator");
       hashMap.put(WallpaperManager.class, "wallpaper");
       hashMap.put(WifiP2pManager.class, "wifip2p");
       hashMap.put(WifiManager.class, "wifi");
       hashMap.put(WindowManager.class, "window");
    }
}
