package com.yxcorp.gifshow.util.cdnresource.CdnResource$ResourceKey;
import java.lang.Enum;
import java.lang.String;
import java.lang.Class;
import java.lang.Object;

public final class CdnResource$ResourceKey extends Enum	// class@001f60
{
    public static final CdnResource$ResourceKey[] $VALUES;
    public static final CdnResource$ResourceKey bt_comment_dislike;
    public static final CdnResource$ResourceKey bt_comment_like;
    public static final CdnResource$ResourceKey bt_detail_center_like;
    public static final CdnResource$ResourceKey bt_sidebar_dislike;
    public static final CdnResource$ResourceKey bt_sidebar_dislike_ab;
    public static final CdnResource$ResourceKey bt_sidebar_like;
    public static final CdnResource$ResourceKey bt_sidebar_like_ab;
    public static final CdnResource$ResourceKey combo_number_0;
    public static final CdnResource$ResourceKey combo_number_1;
    public static final CdnResource$ResourceKey combo_number_2;
    public static final CdnResource$ResourceKey combo_number_3;
    public static final CdnResource$ResourceKey combo_number_4;
    public static final CdnResource$ResourceKey combo_number_5;
    public static final CdnResource$ResourceKey combo_number_6;
    public static final CdnResource$ResourceKey combo_number_7;
    public static final CdnResource$ResourceKey combo_number_8;
    public static final CdnResource$ResourceKey combo_number_9;
    public static final CdnResource$ResourceKey combo_particle;
    public static final CdnResource$ResourceKey combo_text_0;
    public static final CdnResource$ResourceKey combo_text_1;
    public static final CdnResource$ResourceKey combo_text_2;
    public static final CdnResource$ResourceKey combo_text_3;
    public static final CdnResource$ResourceKey combo_text_4;
    public static final CdnResource$ResourceKey combo_text_5;
    public static final CdnResource$ResourceKey comment_like;
    public static final CdnResource$ResourceKey comment_unlike_b;
    public static final CdnResource$ResourceKey corona_detail_like_image;
    public static final CdnResource$ResourceKey corona_detail_like_lottie;
    public static final CdnResource$ResourceKey corona_detail_unlike_image;
    public static final CdnResource$ResourceKey corona_detail_unlike_lottie;
    public static final CdnResource$ResourceKey detail_center_like;
    public static final CdnResource$ResourceKey detail_center_like_b;
    public static final CdnResource$ResourceKey detail_like_bubbles;
    public static final CdnResource$ResourceKey detail_like_bubbles_size_arr;
    public static final CdnResource$ResourceKey detail_like_random_bubbles;
    public static final CdnResource$ResourceKey detail_like_random_bubbles_around_lottie;
    public static final CdnResource$ResourceKey detail_nav_like;
    public static final CdnResource$ResourceKey detail_nav_unlike_b;
    public static final CdnResource$ResourceKey home_card_like_image;
    public static final CdnResource$ResourceKey home_card_unlike_image;
    public static final CdnResource$ResourceKey home_card_v4_like_image;
    public static final CdnResource$ResourceKey home_card_v4_unlike_image;
    public static final CdnResource$ResourceKey landscape_like_image;
    public static final CdnResource$ResourceKey landscape_like_lottie;
    public static final CdnResource$ResourceKey landscape_unlike_image;
    public static final CdnResource$ResourceKey landscape_unlike_lottie;
    public static final CdnResource$ResourceKey loading_background_image;
    public static final CdnResource$ResourceKey loading_pull_lottie;
    public static final CdnResource$ResourceKey loading_refresh_lottie;
    public static final CdnResource$ResourceKey normal_detail_like_image;
    public static final CdnResource$ResourceKey normal_detail_unlike_image;
    public static final CdnResource$ResourceKey slide_play_like_image;
    public static final CdnResource$ResourceKey slide_play_unlike_image;

    static {
       CdnResource$ResourceKey resourceKey = new CdnResource$ResourceKey("detail_center_like", 0);
       CdnResource$ResourceKey.detail_center_like = resourceKey;
       CdnResource$ResourceKey resourceKey1 = new CdnResource$ResourceKey("detail_center_like_b", 1);
       CdnResource$ResourceKey.detail_center_like_b = resourceKey1;
       CdnResource$ResourceKey resourceKey2 = new CdnResource$ResourceKey("comment_like", 2);
       CdnResource$ResourceKey.comment_like = resourceKey2;
       CdnResource$ResourceKey resourceKey3 = new CdnResource$ResourceKey("comment_unlike_b", 3);
       CdnResource$ResourceKey.comment_unlike_b = resourceKey3;
       CdnResource$ResourceKey resourceKey4 = new CdnResource$ResourceKey("detail_nav_like", 4);
       CdnResource$ResourceKey.detail_nav_like = resourceKey4;
       CdnResource$ResourceKey resourceKey5 = new CdnResource$ResourceKey("detail_nav_unlike_b", 5);
       CdnResource$ResourceKey.detail_nav_unlike_b = resourceKey5;
       CdnResource$ResourceKey resourceKey6 = new CdnResource$ResourceKey("combo_number_0", 6);
       CdnResource$ResourceKey.combo_number_0 = resourceKey6;
       CdnResource$ResourceKey resourceKey7 = new CdnResource$ResourceKey("combo_number_1", 7);
       CdnResource$ResourceKey.combo_number_1 = resourceKey7;
       CdnResource$ResourceKey resourceKey8 = new CdnResource$ResourceKey("combo_number_2", 8);
       CdnResource$ResourceKey.combo_number_2 = resourceKey8;
       CdnResource$ResourceKey resourceKey9 = new CdnResource$ResourceKey("combo_number_3", 9);
       CdnResource$ResourceKey.combo_number_3 = resourceKey9;
       CdnResource$ResourceKey resourceKey10 = new CdnResource$ResourceKey("combo_number_4", 10);
       CdnResource$ResourceKey.combo_number_4 = resourceKey10;
       CdnResource$ResourceKey resourceKey11 = new CdnResource$ResourceKey("combo_number_5", 11);
       CdnResource$ResourceKey.combo_number_5 = resourceKey11;
       CdnResource$ResourceKey resourceKey12 = new CdnResource$ResourceKey("combo_number_6", 12);
       CdnResource$ResourceKey.combo_number_6 = resourceKey12;
       CdnResource$ResourceKey resourceKey13 = new CdnResource$ResourceKey("combo_number_7", 13);
       CdnResource$ResourceKey.combo_number_7 = resourceKey13;
       CdnResource$ResourceKey resourceKey14 = resourceKey13;
       CdnResource$ResourceKey resourceKey15 = new CdnResource$ResourceKey("combo_number_8", 14);
       CdnResource$ResourceKey.combo_number_8 = resourceKey15;
       CdnResource$ResourceKey resourceKey16 = resourceKey15;
       CdnResource$ResourceKey resourceKey17 = new CdnResource$ResourceKey("combo_number_9", 15);
       CdnResource$ResourceKey.combo_number_9 = resourceKey17;
       CdnResource$ResourceKey resourceKey18 = resourceKey17;
       resourceKey13 = new CdnResource$ResourceKey("combo_text_0", 16);
       CdnResource$ResourceKey.combo_text_0 = resourceKey13;
       CdnResource$ResourceKey resourceKey19 = resourceKey13;
       resourceKey15 = new CdnResource$ResourceKey("combo_text_1", 17);
       CdnResource$ResourceKey.combo_text_1 = resourceKey15;
       CdnResource$ResourceKey resourceKey20 = resourceKey15;
       resourceKey17 = new CdnResource$ResourceKey("combo_text_2", 18);
       CdnResource$ResourceKey.combo_text_2 = resourceKey17;
       CdnResource$ResourceKey resourceKey21 = resourceKey17;
       resourceKey13 = new CdnResource$ResourceKey("combo_text_3", 19);
       CdnResource$ResourceKey.combo_text_3 = resourceKey13;
       CdnResource$ResourceKey resourceKey22 = resourceKey13;
       resourceKey15 = new CdnResource$ResourceKey("combo_text_4", 20);
       CdnResource$ResourceKey.combo_text_4 = resourceKey15;
       CdnResource$ResourceKey resourceKey23 = resourceKey15;
       resourceKey17 = new CdnResource$ResourceKey("combo_text_5", 21);
       CdnResource$ResourceKey.combo_text_5 = resourceKey17;
       CdnResource$ResourceKey resourceKey24 = resourceKey17;
       resourceKey13 = new CdnResource$ResourceKey("combo_particle", 22);
       CdnResource$ResourceKey.combo_particle = resourceKey13;
       CdnResource$ResourceKey resourceKey25 = resourceKey13;
       resourceKey17 = new CdnResource$ResourceKey("detail_like_bubbles", 23);
       CdnResource$ResourceKey.detail_like_bubbles = resourceKey17;
       CdnResource$ResourceKey resourceKey26 = resourceKey17;
       resourceKey15 = new CdnResource$ResourceKey("detail_like_random_bubbles", 24);
       CdnResource$ResourceKey.detail_like_random_bubbles = resourceKey15;
       CdnResource$ResourceKey resourceKey27 = resourceKey15;
       resourceKey17 = new CdnResource$ResourceKey("detail_like_random_bubbles_around_lottie", 25);
       CdnResource$ResourceKey.detail_like_random_bubbles_around_lottie = resourceKey17;
       CdnResource$ResourceKey resourceKey28 = resourceKey17;
       resourceKey15 = new CdnResource$ResourceKey("detail_like_bubbles_size_arr", 26);
       CdnResource$ResourceKey.detail_like_bubbles_size_arr = resourceKey15;
       CdnResource$ResourceKey resourceKey29 = resourceKey15;
       resourceKey17 = new CdnResource$ResourceKey("bt_detail_center_like", 27);
       CdnResource$ResourceKey.bt_detail_center_like = resourceKey17;
       CdnResource$ResourceKey resourceKey30 = resourceKey17;
       resourceKey15 = new CdnResource$ResourceKey("bt_sidebar_like", 28);
       CdnResource$ResourceKey.bt_sidebar_like = resourceKey15;
       CdnResource$ResourceKey resourceKey31 = resourceKey15;
       resourceKey17 = new CdnResource$ResourceKey("bt_sidebar_like_ab", 29);
       CdnResource$ResourceKey.bt_sidebar_like_ab = resourceKey17;
       CdnResource$ResourceKey resourceKey32 = resourceKey17;
       resourceKey15 = new CdnResource$ResourceKey("bt_sidebar_dislike", 30);
       CdnResource$ResourceKey.bt_sidebar_dislike = resourceKey15;
       CdnResource$ResourceKey resourceKey33 = resourceKey15;
       resourceKey17 = new CdnResource$ResourceKey("bt_sidebar_dislike_ab", 31);
       CdnResource$ResourceKey.bt_sidebar_dislike_ab = resourceKey17;
       CdnResource$ResourceKey resourceKey34 = resourceKey17;
       resourceKey15 = new CdnResource$ResourceKey("bt_comment_like", 32);
       CdnResource$ResourceKey.bt_comment_like = resourceKey15;
       CdnResource$ResourceKey resourceKey35 = resourceKey15;
       resourceKey17 = new CdnResource$ResourceKey("bt_comment_dislike", 33);
       CdnResource$ResourceKey.bt_comment_dislike = resourceKey17;
       CdnResource$ResourceKey resourceKey36 = resourceKey17;
       resourceKey15 = new CdnResource$ResourceKey("loading_pull_lottie", 34);
       CdnResource$ResourceKey.loading_pull_lottie = resourceKey15;
       CdnResource$ResourceKey resourceKey37 = resourceKey15;
       resourceKey17 = new CdnResource$ResourceKey("loading_refresh_lottie", 35);
       CdnResource$ResourceKey.loading_refresh_lottie = resourceKey17;
       CdnResource$ResourceKey resourceKey38 = resourceKey17;
       resourceKey15 = new CdnResource$ResourceKey("loading_background_image", 36);
       CdnResource$ResourceKey.loading_background_image = resourceKey15;
       CdnResource$ResourceKey resourceKey39 = resourceKey15;
       resourceKey17 = new CdnResource$ResourceKey("slide_play_unlike_image", 37);
       CdnResource$ResourceKey.slide_play_unlike_image = resourceKey17;
       CdnResource$ResourceKey resourceKey40 = resourceKey17;
       resourceKey15 = new CdnResource$ResourceKey("slide_play_like_image", 38);
       CdnResource$ResourceKey.slide_play_like_image = resourceKey15;
       CdnResource$ResourceKey resourceKey41 = resourceKey15;
       resourceKey17 = new CdnResource$ResourceKey("home_card_unlike_image", 39);
       CdnResource$ResourceKey.home_card_unlike_image = resourceKey17;
       CdnResource$ResourceKey resourceKey42 = resourceKey17;
       resourceKey15 = new CdnResource$ResourceKey("home_card_like_image", 40);
       CdnResource$ResourceKey.home_card_like_image = resourceKey15;
       CdnResource$ResourceKey resourceKey43 = resourceKey15;
       resourceKey17 = new CdnResource$ResourceKey("home_card_v4_unlike_image", 41);
       CdnResource$ResourceKey.home_card_v4_unlike_image = resourceKey17;
       CdnResource$ResourceKey resourceKey44 = resourceKey17;
       resourceKey15 = new CdnResource$ResourceKey("home_card_v4_like_image", 42);
       CdnResource$ResourceKey.home_card_v4_like_image = resourceKey15;
       CdnResource$ResourceKey resourceKey45 = resourceKey15;
       resourceKey17 = new CdnResource$ResourceKey("normal_detail_unlike_image", 43);
       CdnResource$ResourceKey.normal_detail_unlike_image = resourceKey17;
       CdnResource$ResourceKey resourceKey46 = resourceKey17;
       resourceKey15 = new CdnResource$ResourceKey("normal_detail_like_image", 44);
       CdnResource$ResourceKey.normal_detail_like_image = resourceKey15;
       CdnResource$ResourceKey resourceKey47 = resourceKey15;
       resourceKey17 = new CdnResource$ResourceKey("landscape_unlike_image", 45);
       CdnResource$ResourceKey.landscape_unlike_image = resourceKey17;
       CdnResource$ResourceKey resourceKey48 = resourceKey17;
       resourceKey15 = new CdnResource$ResourceKey("landscape_like_image", 46);
       CdnResource$ResourceKey.landscape_like_image = resourceKey15;
       CdnResource$ResourceKey resourceKey49 = resourceKey15;
       resourceKey17 = new CdnResource$ResourceKey("landscape_unlike_lottie", 47);
       CdnResource$ResourceKey.landscape_unlike_lottie = resourceKey17;
       CdnResource$ResourceKey resourceKey50 = resourceKey17;
       resourceKey15 = new CdnResource$ResourceKey("landscape_like_lottie", 48);
       CdnResource$ResourceKey.landscape_like_lottie = resourceKey15;
       CdnResource$ResourceKey resourceKey51 = resourceKey15;
       resourceKey17 = new CdnResource$ResourceKey("corona_detail_unlike_image", 49);
       CdnResource$ResourceKey.corona_detail_unlike_image = resourceKey17;
       CdnResource$ResourceKey resourceKey52 = resourceKey17;
       resourceKey15 = new CdnResource$ResourceKey("corona_detail_like_image", 50);
       CdnResource$ResourceKey.corona_detail_like_image = resourceKey15;
       CdnResource$ResourceKey resourceKey53 = resourceKey15;
       resourceKey17 = new CdnResource$ResourceKey("corona_detail_unlike_lottie", 51);
       CdnResource$ResourceKey.corona_detail_unlike_lottie = resourceKey17;
       CdnResource$ResourceKey resourceKey54 = resourceKey17;
       resourceKey15 = new CdnResource$ResourceKey("corona_detail_like_lottie", 52);
       CdnResource$ResourceKey.corona_detail_like_lottie = resourceKey15;
       CdnResource$ResourceKey[] resourceKeyA = new CdnResource$ResourceKey[53];
       resourceKeyA[0] = resourceKey;
       resourceKeyA[1] = resourceKey1;
       resourceKeyA[2] = resourceKey2;
       resourceKeyA[3] = resourceKey3;
       resourceKeyA[4] = resourceKey4;
       resourceKeyA[5] = resourceKey5;
       resourceKeyA[6] = resourceKey6;
       resourceKeyA[7] = resourceKey7;
       resourceKeyA[8] = resourceKey8;
       resourceKeyA[9] = resourceKey9;
       resourceKeyA[10] = resourceKey10;
       resourceKeyA[11] = resourceKey11;
       resourceKeyA[12] = resourceKey12;
       resourceKeyA[13] = resourceKey14;
       resourceKeyA[14] = resourceKey16;
       resourceKeyA[15] = resourceKey18;
       resourceKeyA[16] = resourceKey19;
       resourceKeyA[17] = resourceKey20;
       resourceKeyA[18] = resourceKey21;
       resourceKeyA[19] = resourceKey22;
       resourceKeyA[20] = resourceKey23;
       resourceKeyA[21] = resourceKey24;
       resourceKeyA[22] = resourceKey25;
       resourceKeyA[23] = resourceKey26;
       resourceKeyA[24] = resourceKey27;
       resourceKeyA[25] = resourceKey28;
       resourceKeyA[26] = resourceKey29;
       resourceKeyA[27] = resourceKey30;
       resourceKeyA[28] = resourceKey31;
       resourceKeyA[29] = resourceKey32;
       resourceKeyA[30] = resourceKey33;
       resourceKeyA[31] = resourceKey34;
       resourceKeyA[32] = resourceKey35;
       resourceKeyA[33] = resourceKey36;
       resourceKeyA[34] = resourceKey37;
       resourceKeyA[35] = resourceKey38;
       resourceKeyA[36] = resourceKey39;
       resourceKeyA[37] = resourceKey40;
       resourceKeyA[38] = resourceKey41;
       resourceKeyA[39] = resourceKey42;
       resourceKeyA[40] = resourceKey43;
       resourceKeyA[41] = resourceKey44;
       resourceKeyA[42] = resourceKey45;
       resourceKeyA[43] = resourceKey46;
       resourceKeyA[44] = resourceKey47;
       resourceKeyA[45] = resourceKey48;
       resourceKeyA[46] = resourceKey49;
       resourceKeyA[47] = resourceKey50;
       resourceKeyA[48] = resourceKey51;
       resourceKeyA[49] = resourceKey52;
       resourceKeyA[50] = resourceKey53;
       resourceKeyA[51] = resourceKey54;
       resourceKeyA[52] = resourceKey15;
       CdnResource$ResourceKey.$VALUES = resourceKeyA;
    }
    public void CdnResource$ResourceKey(String p0,int p1){
       super(p0, p1);
    }
    public static CdnResource$ResourceKey valueOf(String p0){
       return Enum.valueOf(CdnResource$ResourceKey.class, p0);
    }
    public static CdnResource$ResourceKey[] values(){
       return CdnResource$ResourceKey.$VALUES.clone();
    }
}
