package com.kwai.feature.post.api.feature.memory.MemoryActivityConfig;
import java.io.Serializable;
import java.lang.Object;
import com.yxcorp.gifshow.model.CDNUrl;
import java.util.HashMap;

public class MemoryActivityConfig implements Serializable	// class@0013ab
{
    public String[] coverTexts;
    public String mActivityId;
    public Map mAssetContents;
    public CDNUrl[] mAssetZipForClientUrls;
    public CDNUrl[] mAssetZipUrls;
    public CDNUrl[] mClientMusicUrls;
    public CDNUrl[] mClientVideoUrls;
    public CDNUrl[] mCoverUrls;
    public String mDefaultMusicId;
    public int mDefaultMusicType;
    public String mDefaultStyleId;
    public CDNUrl[] mDefaultStyleUrls;
    public int mDpi;
    public boolean mEncourage;
    public String mEncourageText;
    public String mEncourageToast;
    public long mFansCount;
    public long mFirstLandingTimeStamp;
    public long mFriendCount;
    public int mGenerateAlbumCount;
    public CDNUrl[] mIconUrls;
    public boolean mIsGenerated;
    public boolean mIsGeneratedSummary;
    public boolean mIsUploadAlbum;
    public boolean mIsUploadSummary;
    public CDNUrl[] mLoadingPictureUrls;
    public int mLocalTemplateIdFast;
    public int mLocalTemplateIdMedium;
    public int mLocalTemplateIdSlow;
    public String mPendantToast;
    public long mPhotoCount;
    public long mPhotoLikeCount;
    public long mPhotoViewCount;
    public String mPreviewTitle;
    public String mPublishTitle;
    public long mRecordDays;
    public String mSeasonAlbumMark;
    public boolean mSendCoin;
    public HashMap mServerContents;
    public CDNUrl[] mServerMusicUrls;
    public CDNUrl[] mServerVideoUrls;
    public boolean mShowLocalAlbumEntrance;
    public String mSummaryPublishTitle;
    public CDNUrl[] mSummaryVideoUrls;
    public List mVideoStartEndList;
    public boolean sendPendant;
    public Double summaryCoverFrameTime;
    public String[] summaryCoverText;
    public static final MemoryActivityConfig DEFAULT_MEMORY_ACTIVITY_CONFIG;
    public static final long serialVersionUID;

    static {
       MemoryActivityConfig.DEFAULT_MEMORY_ACTIVITY_CONFIG = new MemoryActivityConfig();
    }
    public void MemoryActivityConfig(){
       super();
       this.mSeasonAlbumMark = "";
       this.mActivityId = "";
       this.mIsGenerated = false;
       this.mIsGeneratedSummary = false;
       this.mIsUploadAlbum = false;
       this.mIsUploadSummary = false;
       this.mShowLocalAlbumEntrance = false;
       this.mSendCoin = false;
       this.mDefaultStyleId = "";
       this.mDefaultMusicId = "";
       this.mPreviewTitle = "";
       this.mEncourageText = "";
       this.mEncourage = false;
       this.sendPendant = false;
       this.mPublishTitle = "";
       this.mSummaryPublishTitle = "";
       this.mFirstLandingTimeStamp = 0;
       CDNUrl[] uCDNUrlArray = new CDNUrl[false];
       this.mIconUrls = uCDNUrlArray;
       uCDNUrlArray = new CDNUrl[false];
       this.mCoverUrls = uCDNUrlArray;
       uCDNUrlArray = new CDNUrl[false];
       this.mLoadingPictureUrls = uCDNUrlArray;
       uCDNUrlArray = new CDNUrl[false];
       this.mAssetZipUrls = uCDNUrlArray;
       uCDNUrlArray = new CDNUrl[false];
       this.mAssetZipForClientUrls = uCDNUrlArray;
       uCDNUrlArray = new CDNUrl[false];
       this.mDefaultStyleUrls = uCDNUrlArray;
       uCDNUrlArray = new CDNUrl[false];
       this.mServerVideoUrls = uCDNUrlArray;
       uCDNUrlArray = new CDNUrl[false];
       this.mServerMusicUrls = uCDNUrlArray;
       uCDNUrlArray = new CDNUrl[false];
       this.mClientVideoUrls = uCDNUrlArray;
       uCDNUrlArray = new CDNUrl[false];
       this.mClientMusicUrls = uCDNUrlArray;
       this.mServerContents = null;
       this.coverTexts = null;
       this.summaryCoverText = null;
       this.summaryCoverFrameTime = null;
       CDNUrl[] uCDNUrlArray1 = new CDNUrl[false];
       this.mSummaryVideoUrls = uCDNUrlArray1;
       this.mEncourageToast = "";
       this.mPendantToast = "";
       this.mAssetContents = new HashMap();
    }
}
