package com.kwai.video.stannis.AudioProcess;
import java.lang.Object;
import java.lang.String;
import com.kwai.video.stannis.AudioProcess$AudioEffectParam;
import com.kwai.video.stannis.AudioProcess$AudioPitchParam;
import com.kwai.video.stannis.AudioProcess$AudioChangeParam;

public class AudioProcess	// class@000bbf
{

    public void AudioProcess(){
       super();
    }
    public native long nativeAgcCreate(int p0,int p1);
    public native void nativeAgcDestroy(long p0);
    public native int nativeAgcGetVadStatus(long p0);
    public native boolean nativeAgcProcess(long p0,byte[] p1,byte[] p2);
    public native void nativeAgcSetAgcLevel(long p0,int p1,int p2,int p3);
    public native void nativeAgcSetNsEnable(long p0,boolean p1);
    public native void nativeAgcSetNsLevel(long p0,int p1);
    public native void nativeAgcSetQuality(long p0,int p1);
    public native void nativeAudioGainControlDestroy(long p0);
    public native long nativeAudioGainControlInterface(int p0,int p1,float p2);
    public native long nativeAudioGainControlInterface(int p0,int p1,float p2,float p3);
    public native int nativeAudioGainControlProcess(long p0,byte[] p1,int p2);
    public native void nativeAudioMixerClear(long p0);
    public native long nativeAudioMixerCreate(int p0,int p1);
    public native void nativeAudioMixerDestroy(long p0);
    public native int nativeAudioMixerProcess(long p0,byte[] p1,byte[] p2,byte[] p3,int p4);
    public native boolean nativeAudioMixerSetGain(long p0,float p1,float p2);
    public native void nativeAudioPostEffectClear(long p0);
    public native void nativeAudioPostEffectDestroy(long p0);
    public native long nativeAudioPostEffectInterface(int p0,int p1);
    public native int nativeAudioPostEffectProcess(long p0,short[] p1,int p2);
    public native int nativeAudioPostEffectSetHeadsetMode(long p0,int p1);
    public native boolean nativeAudioPostEffectSetOption(long p0,int p1);
    public native int nativeAudioPostEffectSetOutputChannel(long p0,int p1);
    public native int nativeAudioPostEffectSetPitch(long p0,int p1);
    public native void nativeAudioVoiceDetectDestroy(long p0);
    public native long nativeAudioVoiceDetectInterface(int p0,int p1,String p2);
    public native int nativeAudioVoiceDetectProcess(long p0,byte[] p1,int p2,float[] p3);
    public native int nativeAudioWatermarkAddProcess(long p0,short[] p1,int p2);
    public native void nativeAudioWatermarkDecodeDestroy(long p0);
    public native int nativeAudioWatermarkDecodeGetWaterMark(long p0,byte[] p1);
    public native long nativeAudioWatermarkDecodeInterface(int p0,int p1);
    public native int nativeAudioWatermarkDecodeProcess(long p0,short[] p1,int p2);
    public native void nativeAudioWatermarkDestroy(long p0);
    public native int nativeAudioWatermarkFetchRestAduioData(long p0,short[] p1,int p2);
    public native long nativeAudioWatermarkInterface(int p0,int p1,byte[] p2);
    public native void nativeAutoTuneDestroy(long p0);
    public native int nativeAutuTuneGetResult(long p0,float[] p1,String p2,float p3,float p4);
    public native int nativeAutuTuneGetResultByData(long p0,float[] p1,byte[] p2,int p3,int p4,float p5,float p6);
    public native long nativeAutuTuneInterface(int p0,int p1);
    public native void nativeBeatsTrackDestroy(long p0);
    public native int nativeBeatsTrackGetBeats(long p0,float[] p1,float[] p2,int[] p3,int p4);
    public native int nativeBeatsTrackProcess(long p0,byte[] p1,int p2);
    public native long nativeCreateBeatsTrackInterface(int p0,int p1);
    public native long nativeCreatePreciseVadInterface(int p0,int p1);
    public native long nativeCreateSpectrumInterface(int p0,int p1);
    public native void nativeDspClear(long p0);
    public native long nativeDspCreate(int p0,int p1);
    public native void nativeDspDestroy(long p0);
    public native void nativeDspFreePitch(long p0);
    public native AudioProcess$AudioEffectParam nativeDspGetParameters(long p0);
    public native AudioProcess$AudioPitchParam nativeDspGetPitch(long p0,byte[] p1,int p2);
    public native int nativeDspInitPitch(long p0);
    public native int nativeDspProcess(long p0,byte[] p1,int p2);
    public native void nativeDspSetOutChannels(long p0,int p1);
    public native void nativeDspSetParameters(long p0,AudioProcess$AudioEffectParam p1);
    public native void nativeDspSetPitch(long p0,float p1);
    public native void nativeDspSetVcoMode(long p0,int p1);
    public native void nativeDspSetVcoParameters(long p0,AudioProcess$AudioChangeParam p1);
    public native void nativeDspSetVeoMode(long p0,int p1);
    public native boolean nativeNsProcess(long p0,byte[] p1,byte[] p2);
    public native void nativePitchChangeClear(long p0);
    public native long nativePitchChangeCreate(int p0,int p1);
    public native void nativePitchChangeDestroy(long p0);
    public native int nativePitchChangeProcess(long p0,byte[] p1,int p2);
    public native boolean nativePitchChangeSetPitch(long p0,int p1);
    public native void nativePreciseVadDestroy(long p0);
    public native int nativePreciseVadProcess(long p0,byte[] p1,int p2);
    public native void nativeSpectrumDestroy(long p0);
    public native int nativeSpectrumProcess(long p0,float[] p1,byte[] p2,int p3);
    public native int nativeTempoBpmDetect(long p0,byte[] p1,int p2);
    public native long nativeTempoCreate(int p0,int p1);
    public native void nativeTempoDestroy(long p0);
    public native int nativeTempoGetBeatsNum(long p0);
    public native int nativeTempoGetBeatsResult(long p0,float[] p1,float[] p2,int p3);
    public native int nativeTempoProcess(long p0,byte[] p1,int p2);
    public native void nativeTempoSetRate(long p0,float p1);
    public native void nativeTempoSetTempo(long p0,float p1);
    public native void nativeTimbreChangeClear(long p0);
    public native long nativeTimbreChangeCreate(int p0,int p1);
    public native void nativeTimbreChangeDestroy(long p0);
    public native int nativeTimbreChangeProcess(long p0,byte[] p1,int p2);
    public native boolean nativeTimbreChangeSetTimbre(long p0,int p1);
}
