package com.kwai.video.player.IKwaiMediaPlayer;
import com.kwai.video.player.IMediaPlayer;
import ci7.a;
import com.kwai.player.debuginfo.KwaiPlayerDebugInfoProvider;
import ai7.b;
import java.lang.String;
import com.kwai.player.debuginfo.model.AppLiveQosDebugInfo;
import com.kwai.video.player.kwai_player.AspectAwesomeCache;
import com.kwai.video.player.kwai_player.AspectKFlv;
import com.kwai.video.player.kwai_player.AspectKwaiVodAdaptive;
import com.kwai.player.KwaiRepresentation;
import java.util.Map;
import android.os.Bundle;
import android.graphics.Bitmap;
import com.kwai.player.qos.KwaiQosInfo;
import android.view.MotionEvent;
import ai7.e;
import org.json.JSONObject;
import android.view.Surface;
import android.graphics.SurfaceTexture;
import com.kwai.video.player.IKwaiRepresentationListener;
import com.kwai.video.player.IKwaiBulletScreenListener;
import com.kwai.video.player.IKwaiInjectHttpCallback;
import com.kwai.video.player.IKwaiSubtitleListener;
import com.kwai.video.player.IKwaiVodDrmCallback;
import com.kwai.video.player.IMediaPlayer$OnLiveAdaptiveQosStatListener;
import com.kwai.video.player.IMediaPlayer$OnQosStatListener;
import com.kwai.video.player.IMediaPlayer$OnABLoopEndOfCounterListener;
import com.kwai.video.player.KsMediaPlayer$OnAudioProcessPCMListener;
import com.kwai.video.player.IMediaPlayer$OnLiveEventListener;
import com.kwai.video.player.IKwaiMediaPlayer$OnLiveExtraInfoListener;
import com.kwai.video.player.IKwaiMediaPlayer$OnLiveInterActiveListener;
import com.kwai.video.player.IKwaiMediaPlayer$OnLiveInterActiveListener$ListenerType;
import com.kwai.video.player.IKwaiMediaPlayer$OnLiveSeiInfoListener;
import com.kwai.video.player.IKwaiMediaPlayer$OnLiveSrvTsptInfoListener;
import com.kwai.video.player.IMediaPlayer$OnLiveVoiceCommentListener;
import com.kwai.video.player.OnQosEventInfoListener;
import com.kwai.video.player.IKwaiMediaPlayer$OnVideoRenderListener;
import com.kwai.player.KwaiPlayerConfig;

public interface abstract IKwaiMediaPlayer implements IMediaPlayer, a, KwaiPlayerDebugInfoProvider	// class@000ab6
{

    int addBulletScreen(b p0);
    int addBulletScreenWithParam(int p0,int p1,int p2,String p3);
    int addSubtitle(String p0,boolean p1);
    void audioOnly(boolean p0);
    int bufferEmptyCount();
    int bufferEmptyCountOld();
    long bufferEmptyDuration();
    long bufferEmptyDurationOld();
    boolean checkCanStartPlay();
    void disableSoftVideoDecode(boolean p0);
    void enableAudioMono(int p0);
    void enableLoopOnBlock(int p0,int p1,long p2);
    void enableMediacodecDummy(boolean p0);
    boolean getAPJoySoundSwitchStatus();
    AppLiveQosDebugInfo getAppLiveQosDebugInfo();
    AspectAwesomeCache getAspectAwesomeCache();
    AspectKFlv getAspectKFlv();
    AspectKwaiVodAdaptive getAspectVodAdaptive();
    float getAudioRawLatencySeconds();
    float getAverageDisplayFps();
    long getBitrate();
    String getBriefVodStatJson();
    float getBufferTimeMax();
    long getCurAbsTime();
    int getCurrentAudioRepresentationId();
    KwaiRepresentation getCurrentRepresentation();
    int getCurrentRepresentationId();
    String getCurrentTranscodeType();
    long getCurrentVideoPosition();
    long getDecodeVideoFrameCount();
    long getDecodedDataSize();
    long getDecodedVideoHeight();
    long getDecodedVideoWidth();
    long getDisplayFrameCount();
    long getDownloadDataSize();
    int getDownloadedPercent();
    long getDroppedDuration();
    long getDtsDuration();
    Map getExtraQosInfo();
    long getFirstVideoPts();
    String getKwaiLiveVoiceComment(long p0);
    String getKwaivppFilters();
    long getLastVideoPts();
    String getLiveRealTimeQosJson(int p0,int p1,long p2,long p3,long p4);
    String getLiveStatJson();
    Bundle getMediaMeta();
    int getOrientationDegrees();
    long getPlayerId();
    String getPlayerTsJson();
    float getProbeFps();
    long getReadVideoFrameCount();
    Bitmap getScreenShot();
    long getSourceDeviceType();
    float getSpeed(float p0);
    KwaiQosInfo getStreamQosInfo();
    int getTotalPlayBackDuration();
    int getVideoAlphaType();
    float getVideoAvgFps();
    long getVideoDecErrorCount();
    int getVideoDecoder();
    float getVideoOutputFramesPerSecond();
    String getVodAdaptiveCacheKey();
    String getVodAdaptiveHdrType();
    String getVodAdaptiveHostName();
    int getVodAdaptiveRepID();
    String getVodAdaptiveUrl();
    String getVodStatJson();
    boolean handleTouchEvent(MotionEvent p0);
    boolean hasNativeCdnRetry();
    boolean isAudioOnly();
    boolean isMediaPlayerValid();
    boolean isRepresentationEnableAdaptive(int p0);
    void notifyKwaiOnInfo(int p0,int p1);
    void registerSensorEvent();
    void releaseAsync();
    void releaseAsync(e p0);
    int removeBulletScreen(int p0);
    void setAPJoySoundSwitchStatus(boolean p0);
    void setAbLoop(long p0,long p1,int p2);
    void setAbLoop(long p0,long p1,int p2,boolean p3);
    void setAppQosStatJson(JSONObject p0);
    void setAudioRepresentation(int p0);
    void setCencKey(String p0);
    void setClickCoordForOpaque(float p0,float p1);
    void setDataSource(String p0,Map p1);
    void setDrmKeyInfo(String p0,int p1,int p2);
    void setEnableAudioSpectrum(boolean p0);
    void setExtOption(int p0,int p1);
    void setExtOption(int p0,String p1);
    void setExtSurface(Surface p0);
    void setExtSurfaceCrop(float p0,float p1,float p2,float p3);
    void setExtSurfaceCrop(int p0,int p1,int p2,int p3);
    void setExtSurfaceTexture(SurfaceTexture p0);
    void setIndexContent(String p0,String p1,String p2,Map p3);
    void setInteractiveMode(int p0);
    void setKwaiAudioRepresentationListener(IKwaiRepresentationListener p0);
    void setKwaiBulletScreenListener(IKwaiBulletScreenListener p0);
    void setKwaiInjectHttpCallback(IKwaiInjectHttpCallback p0);
    void setKwaiManifest(String p0,String p1,Map p2);
    void setKwaiRepresentationListener(IKwaiRepresentationListener p0);
    void setKwaiSubtitleListener(IKwaiSubtitleListener p0);
    void setKwaiVodDrmCallback(IKwaiVodDrmCallback p0);
    void setKwaivppExtJson(int p0,String p1);
    void setKwaivppFilters(int p0,String p1);
    void setKwaivppKswitchJson(int p0,String p1);
    void setLastTryFlag(boolean p0);
    void setLiveManifestSwitchMode(int p0);
    void setLiveOnPeriodicalLiveAdaptiveQosStatListener(IMediaPlayer$OnLiveAdaptiveQosStatListener p0);
    void setLiveOnQosStatListener(IMediaPlayer$OnQosStatListener p0);
    void setNetworkRetryScene(String p0);
    void setOnABLoopEndOfCounterListener(IMediaPlayer$OnABLoopEndOfCounterListener p0);
    void setOnAudioProcessPCMAvailableListener(KsMediaPlayer$OnAudioProcessPCMListener p0);
    void setOnLiveEventListener(IMediaPlayer$OnLiveEventListener p0);
    void setOnLiveExtraInfoListener(IKwaiMediaPlayer$OnLiveExtraInfoListener p0);
    void setOnLiveInterActiveListener(IKwaiMediaPlayer$OnLiveInterActiveListener p0);
    void setOnLiveInterActiveListener(IKwaiMediaPlayer$OnLiveInterActiveListener p0,IKwaiMediaPlayer$OnLiveInterActiveListener$ListenerType p1);
    void setOnLiveSeiInfoListener(IKwaiMediaPlayer$OnLiveSeiInfoListener p0);
    void setOnLiveSrvTsptInfoListener(IKwaiMediaPlayer$OnLiveSrvTsptInfoListener p0);
    void setOnLiveVoiceCommentListener(IMediaPlayer$OnLiveVoiceCommentListener p0);
    void setOnQosEventInfoListener(OnQosEventInfoListener p0);
    void setOnVideoRenderListener(IKwaiMediaPlayer$OnVideoRenderListener p0);
    void setOption(int p0,String p1,long p2);
    void setOption(int p0,String p1,String p2);
    void setPlayerMute(boolean p0);
    void setRepresentation(int p0);
    void setSpeed(float p0);
    void setSutitleSelected(int p0,boolean p1);
    void setTag1(int p0);
    void setTone(int p0);
    void setVideoScalingMode(int p0);
    void setViewSize(int p0,int p1);
    void setViewSize(int p0,int p1,float p2);
    void shutdownWaitStop();
    void startLiveStatTimer(KwaiPlayerConfig p0);
    void stepFrame();
    void stopLiveStatTimerImmediately();
    void unRegisterSensorEvent();
    void updateAdaptiveMode(int p0);
    void updateCurrentMaxWallClockOffset(long p0);
    void updateCurrentWallClock(long p0);
    int updateKwaiManfiest(String p0);
    void updateRepresentationAdaptiveFlag(int p0,boolean p1);
}
