package com.kwai.video.player.IMediaPlayer;
import java.lang.String;
import com.kwai.video.player.MediaInfo;
import android.view.Surface;
import com.kwai.video.player.misc.ITrackInfo;
import android.content.Context;
import android.net.Uri;
import java.util.Map;
import com.kwai.video.player.misc.IMediaDataSource;
import java.io.FileDescriptor;
import android.view.SurfaceHolder;
import com.kwai.video.player.IMediaPlayer$OnBufferingUpdateListener;
import com.kwai.video.player.IMediaPlayer$OnCompletionListener;
import com.kwai.video.player.IMediaPlayer$OnDecodeFirstFrameListener;
import com.kwai.video.player.IMediaPlayer$OnErrorListener;
import com.kwai.video.player.IMediaPlayer$OnFftDataCaptureListener;
import com.kwai.video.player.IMediaPlayer$OnInfoExtraListener;
import com.kwai.video.player.IMediaPlayer$OnInfoListener;
import com.kwai.video.player.IMediaPlayer$OnLogEventListener;
import com.kwai.video.player.IMediaPlayer$OnPreparedListener;
import com.kwai.video.player.IMediaPlayer$OnRenderingStartListener;
import com.kwai.video.player.IMediaPlayer$OnSeekCompleteListener;
import com.kwai.video.player.IMediaPlayer$OnVideoSizeChangedListener;
import android.graphics.SurfaceTexture;
import com.kwai.video.player.IMediaPlayer$OnVideoRawDataListener;

public interface abstract IMediaPlayer	// class@000acc
{

    void addVideoRawBuffer(byte[] p0);
    int getAudioSessionId();
    long getCurrentPosition();
    String getDataSource();
    long getDuration();
    MediaInfo getMediaInfo();
    Surface getSurface();
    ITrackInfo[] getTrackInfo();
    int getVideoHeight();
    int getVideoSarDen();
    int getVideoSarNum();
    int getVideoWidth();
    boolean isLooping();
    boolean isPlayable();
    boolean isPlaying();
    void pause();
    void prepareAsync();
    void release();
    void reset();
    void seekTo(long p0);
    void setAudioStreamType(int p0);
    void setDataSource(Context p0,Uri p1);
    void setDataSource(Context p0,Uri p1,Map p2);
    void setDataSource(IMediaDataSource p0);
    void setDataSource(FileDescriptor p0);
    void setDataSource(String p0);
    void setDisplay(SurfaceHolder p0);
    void setKeepInBackground(boolean p0);
    void setLooping(boolean p0);
    void setOnBufferingUpdateListener(IMediaPlayer$OnBufferingUpdateListener p0);
    void setOnCompletionListener(IMediaPlayer$OnCompletionListener p0);
    void setOnDecodeFirstFrameListener(IMediaPlayer$OnDecodeFirstFrameListener p0);
    void setOnErrorListener(IMediaPlayer$OnErrorListener p0);
    void setOnFftDataCaptureListener(IMediaPlayer$OnFftDataCaptureListener p0);
    void setOnInfoExtraListener(IMediaPlayer$OnInfoExtraListener p0);
    void setOnInfoListener(IMediaPlayer$OnInfoListener p0);
    void setOnLogEventListener(IMediaPlayer$OnLogEventListener p0);
    void setOnPreparedListener(IMediaPlayer$OnPreparedListener p0);
    void setOnRenderingStartListener(IMediaPlayer$OnRenderingStartListener p0);
    void setOnSeekCompleteListener(IMediaPlayer$OnSeekCompleteListener p0);
    void setOnVideoSizeChangedListener(IMediaPlayer$OnVideoSizeChangedListener p0);
    void setScreenOnWhilePlaying(boolean p0);
    void setSurface(Surface p0);
    void setSurfaceTexture(SurfaceTexture p0);
    void setVideoRawDataListener(IMediaPlayer$OnVideoRawDataListener p0);
    void setVolume(float p0,float p1);
    void setWakeMode(Context p0,int p1);
    void start();
    void stop();
}
