package com.kwai.video.minecraft.model.MinecraftModelDefine$EffectType;
import java.lang.Enum;
import java.lang.String;
import java.lang.Object;
import java.lang.Class;
import com.kwai.robust.PatchProxy;
import com.kwai.robust.PatchProxyResult;

public final class MinecraftModelDefine$EffectType extends Enum	// class@000a05
{
    public static final MinecraftModelDefine$EffectType[] $VALUES;
    public static final MinecraftModelDefine$EffectType EffectType_AudioEffectParam;
    public static final MinecraftModelDefine$EffectType EffectType_AudioFilterParam;
    public static final MinecraftModelDefine$EffectType EffectType_AudioPitchShifts;
    public static final MinecraftModelDefine$EffectType EffectType_AudioVolumeKeyFrame;
    public static final MinecraftModelDefine$EffectType EffectType_AudioVolumeRangeParam;
    public static final MinecraftModelDefine$EffectType EffectType_BeautyFilterParam;
    public static final MinecraftModelDefine$EffectType EffectType_BlurOptions;
    public static final MinecraftModelDefine$EffectType EffectType_ChromaKeyConfig;
    public static final MinecraftModelDefine$EffectType EffectType_ClipBodyParam;
    public static final MinecraftModelDefine$EffectType EffectType_ColorFilterParam;
    public static final MinecraftModelDefine$EffectType EffectType_Default;
    public static final MinecraftModelDefine$EffectType EffectType_DeformParam;
    public static final MinecraftModelDefine$EffectType EffectType_EnhanceEffect;
    public static final MinecraftModelDefine$EffectType EffectType_EnhanceFilterParam;
    public static final MinecraftModelDefine$EffectType EffectType_ExternalFilterEffect;
    public static final MinecraftModelDefine$EffectType EffectType_GradientColorOptions;
    public static final MinecraftModelDefine$EffectType EffectType_LegacyAE2Effect;
    public static final MinecraftModelDefine$EffectType EffectType_MagicTouchEffectParam;
    public static final MinecraftModelDefine$EffectType EffectType_PaddingAreaOptions;
    public static final MinecraftModelDefine$EffectType EffectType_PictureAdjustmentParam;
    public static final MinecraftModelDefine$EffectType EffectType_PointChaseParam;
    public static final MinecraftModelDefine$EffectType EffectType_PointChaseTransforms;
    public static final MinecraftModelDefine$EffectType EffectType_ShadowOptions;
    public static final MinecraftModelDefine$EffectType EffectType_StabilizationParam;
    public static final MinecraftModelDefine$EffectType EffectType_TextEffect;
    public static final MinecraftModelDefine$EffectType EffectType_TimeEffectParam;
    public static final MinecraftModelDefine$EffectType EffectType_VESharpenFilterParam;
    public static final MinecraftModelDefine$EffectType EffectType_VideoAdjustAssetModel;
    public static final MinecraftModelDefine$EffectType EffectType_VideoEffectModel;
    public static final MinecraftModelDefine$EffectType EffectType_VideoFilterModel;
    public static final MinecraftModelDefine$EffectType EffectType_VisualEffectCameraMovementParams;
    public static final MinecraftModelDefine$EffectType EffectType_VisualEffectParam;
    public static final MinecraftModelDefine$EffectType EffectType_WesterosBeautyFilterParam;
    public static final MinecraftModelDefine$EffectType EffectType_WesterosBeautyZeroOptParam;
    public static final MinecraftModelDefine$EffectType EffectType_WesterosBodySlimmingParam;
    public static final MinecraftModelDefine$EffectType EffectType_WesterosEffectLookupParam;
    public static final MinecraftModelDefine$EffectType EffectType_WesterosFaceMagicParam;
    public static final MinecraftModelDefine$EffectType EffectType_WesterosMakeupParam;
    public static final MinecraftModelDefine$EffectType EffectType_YKitCutoutParam;

    static {
       MinecraftModelDefine$EffectType uEffectType = new MinecraftModelDefine$EffectType("EffectType_Default", 0);
       MinecraftModelDefine$EffectType.EffectType_Default = uEffectType;
       MinecraftModelDefine$EffectType uEffectType1 = new MinecraftModelDefine$EffectType("EffectType_ChromaKeyConfig", 1);
       MinecraftModelDefine$EffectType.EffectType_ChromaKeyConfig = uEffectType1;
       MinecraftModelDefine$EffectType uEffectType2 = new MinecraftModelDefine$EffectType("EffectType_VESharpenFilterParam", 2);
       MinecraftModelDefine$EffectType.EffectType_VESharpenFilterParam = uEffectType2;
       MinecraftModelDefine$EffectType uEffectType3 = new MinecraftModelDefine$EffectType("EffectType_ExternalFilterEffect", 3);
       MinecraftModelDefine$EffectType.EffectType_ExternalFilterEffect = uEffectType3;
       MinecraftModelDefine$EffectType uEffectType4 = new MinecraftModelDefine$EffectType("EffectType_AudioEffectParam", 4);
       MinecraftModelDefine$EffectType.EffectType_AudioEffectParam = uEffectType4;
       MinecraftModelDefine$EffectType uEffectType5 = new MinecraftModelDefine$EffectType("EffectType_ColorFilterParam", 5);
       MinecraftModelDefine$EffectType.EffectType_ColorFilterParam = uEffectType5;
       MinecraftModelDefine$EffectType uEffectType6 = new MinecraftModelDefine$EffectType("EffectType_BeautyFilterParam", 6);
       MinecraftModelDefine$EffectType.EffectType_BeautyFilterParam = uEffectType6;
       MinecraftModelDefine$EffectType uEffectType7 = new MinecraftModelDefine$EffectType("EffectType_AudioVolumeRangeParam", 7);
       MinecraftModelDefine$EffectType.EffectType_AudioVolumeRangeParam = uEffectType7;
       MinecraftModelDefine$EffectType uEffectType8 = new MinecraftModelDefine$EffectType("EffectType_AudioVolumeKeyFrame", 8);
       MinecraftModelDefine$EffectType.EffectType_AudioVolumeKeyFrame = uEffectType8;
       MinecraftModelDefine$EffectType uEffectType9 = new MinecraftModelDefine$EffectType("EffectType_AudioPitchShifts", 9);
       MinecraftModelDefine$EffectType.EffectType_AudioPitchShifts = uEffectType9;
       MinecraftModelDefine$EffectType uEffectType10 = new MinecraftModelDefine$EffectType("EffectType_AudioFilterParam", 10);
       MinecraftModelDefine$EffectType.EffectType_AudioFilterParam = uEffectType10;
       MinecraftModelDefine$EffectType uEffectType11 = new MinecraftModelDefine$EffectType("EffectType_PictureAdjustmentParam", 11);
       MinecraftModelDefine$EffectType.EffectType_PictureAdjustmentParam = uEffectType11;
       MinecraftModelDefine$EffectType uEffectType12 = new MinecraftModelDefine$EffectType("EffectType_BlurOptions", 12);
       MinecraftModelDefine$EffectType.EffectType_BlurOptions = uEffectType12;
       MinecraftModelDefine$EffectType uEffectType13 = new MinecraftModelDefine$EffectType("EffectType_ShadowOptions", 13);
       MinecraftModelDefine$EffectType.EffectType_ShadowOptions = uEffectType13;
       MinecraftModelDefine$EffectType uEffectType14 = uEffectType13;
       MinecraftModelDefine$EffectType uEffectType15 = new MinecraftModelDefine$EffectType("EffectType_GradientColorOptions", 14);
       MinecraftModelDefine$EffectType.EffectType_GradientColorOptions = uEffectType15;
       MinecraftModelDefine$EffectType uEffectType16 = uEffectType15;
       MinecraftModelDefine$EffectType uEffectType17 = new MinecraftModelDefine$EffectType("EffectType_PaddingAreaOptions", 15);
       MinecraftModelDefine$EffectType.EffectType_PaddingAreaOptions = uEffectType17;
       MinecraftModelDefine$EffectType uEffectType18 = uEffectType17;
       uEffectType13 = new MinecraftModelDefine$EffectType("EffectType_DeformParam", 16);
       MinecraftModelDefine$EffectType.EffectType_DeformParam = uEffectType13;
       MinecraftModelDefine$EffectType uEffectType19 = uEffectType13;
       uEffectType15 = new MinecraftModelDefine$EffectType("EffectType_WesterosBeautyFilterParam", 17);
       MinecraftModelDefine$EffectType.EffectType_WesterosBeautyFilterParam = uEffectType15;
       MinecraftModelDefine$EffectType uEffectType20 = uEffectType15;
       uEffectType17 = new MinecraftModelDefine$EffectType("EffectType_WesterosMakeupParam", 18);
       MinecraftModelDefine$EffectType.EffectType_WesterosMakeupParam = uEffectType17;
       MinecraftModelDefine$EffectType uEffectType21 = uEffectType17;
       uEffectType13 = new MinecraftModelDefine$EffectType("EffectType_WesterosBodySlimmingParam", 19);
       MinecraftModelDefine$EffectType.EffectType_WesterosBodySlimmingParam = uEffectType13;
       MinecraftModelDefine$EffectType uEffectType22 = uEffectType13;
       uEffectType15 = new MinecraftModelDefine$EffectType("EffectType_WesterosBeautyZeroOptParam", 20);
       MinecraftModelDefine$EffectType.EffectType_WesterosBeautyZeroOptParam = uEffectType15;
       MinecraftModelDefine$EffectType uEffectType23 = uEffectType15;
       uEffectType17 = new MinecraftModelDefine$EffectType("EffectType_WesterosEffectLookupParam", 21);
       MinecraftModelDefine$EffectType.EffectType_WesterosEffectLookupParam = uEffectType17;
       MinecraftModelDefine$EffectType uEffectType24 = uEffectType17;
       uEffectType13 = new MinecraftModelDefine$EffectType("EffectType_WesterosFaceMagicParam", 22);
       MinecraftModelDefine$EffectType.EffectType_WesterosFaceMagicParam = uEffectType13;
       MinecraftModelDefine$EffectType uEffectType25 = uEffectType13;
       uEffectType17 = new MinecraftModelDefine$EffectType("EffectType_LegacyAE2Effect", 23);
       MinecraftModelDefine$EffectType.EffectType_LegacyAE2Effect = uEffectType17;
       MinecraftModelDefine$EffectType uEffectType26 = uEffectType17;
       uEffectType15 = new MinecraftModelDefine$EffectType("EffectType_ClipBodyParam", 24);
       MinecraftModelDefine$EffectType.EffectType_ClipBodyParam = uEffectType15;
       MinecraftModelDefine$EffectType uEffectType27 = uEffectType15;
       uEffectType17 = new MinecraftModelDefine$EffectType("EffectType_VisualEffectCameraMovementParams", 25);
       MinecraftModelDefine$EffectType.EffectType_VisualEffectCameraMovementParams = uEffectType17;
       MinecraftModelDefine$EffectType uEffectType28 = uEffectType17;
       uEffectType15 = new MinecraftModelDefine$EffectType("EffectType_VisualEffectParam", 26);
       MinecraftModelDefine$EffectType.EffectType_VisualEffectParam = uEffectType15;
       MinecraftModelDefine$EffectType uEffectType29 = uEffectType15;
       uEffectType17 = new MinecraftModelDefine$EffectType("EffectType_TimeEffectParam", 27);
       MinecraftModelDefine$EffectType.EffectType_TimeEffectParam = uEffectType17;
       MinecraftModelDefine$EffectType uEffectType30 = uEffectType17;
       uEffectType15 = new MinecraftModelDefine$EffectType("EffectType_MagicTouchEffectParam", 28);
       MinecraftModelDefine$EffectType.EffectType_MagicTouchEffectParam = uEffectType15;
       MinecraftModelDefine$EffectType uEffectType31 = uEffectType15;
       uEffectType17 = new MinecraftModelDefine$EffectType("EffectType_EnhanceFilterParam", 29);
       MinecraftModelDefine$EffectType.EffectType_EnhanceFilterParam = uEffectType17;
       MinecraftModelDefine$EffectType uEffectType32 = uEffectType17;
       uEffectType15 = new MinecraftModelDefine$EffectType("EffectType_YKitCutoutParam", 30);
       MinecraftModelDefine$EffectType.EffectType_YKitCutoutParam = uEffectType15;
       MinecraftModelDefine$EffectType uEffectType33 = uEffectType15;
       uEffectType17 = new MinecraftModelDefine$EffectType("EffectType_StabilizationParam", 31);
       MinecraftModelDefine$EffectType.EffectType_StabilizationParam = uEffectType17;
       MinecraftModelDefine$EffectType uEffectType34 = uEffectType17;
       uEffectType15 = new MinecraftModelDefine$EffectType("EffectType_PointChaseTransforms", 32);
       MinecraftModelDefine$EffectType.EffectType_PointChaseTransforms = uEffectType15;
       MinecraftModelDefine$EffectType uEffectType35 = uEffectType15;
       uEffectType17 = new MinecraftModelDefine$EffectType("EffectType_PointChaseParam", 33);
       MinecraftModelDefine$EffectType.EffectType_PointChaseParam = uEffectType17;
       MinecraftModelDefine$EffectType uEffectType36 = uEffectType17;
       uEffectType15 = new MinecraftModelDefine$EffectType("EffectType_VideoEffectModel", 34);
       MinecraftModelDefine$EffectType.EffectType_VideoEffectModel = uEffectType15;
       MinecraftModelDefine$EffectType uEffectType37 = uEffectType15;
       uEffectType17 = new MinecraftModelDefine$EffectType("EffectType_TextEffect", 35);
       MinecraftModelDefine$EffectType.EffectType_TextEffect = uEffectType17;
       MinecraftModelDefine$EffectType uEffectType38 = uEffectType17;
       uEffectType15 = new MinecraftModelDefine$EffectType("EffectType_VideoFilterModel", 36);
       MinecraftModelDefine$EffectType.EffectType_VideoFilterModel = uEffectType15;
       MinecraftModelDefine$EffectType uEffectType39 = uEffectType15;
       uEffectType17 = new MinecraftModelDefine$EffectType("EffectType_EnhanceEffect", 37);
       MinecraftModelDefine$EffectType.EffectType_EnhanceEffect = uEffectType17;
       MinecraftModelDefine$EffectType uEffectType40 = uEffectType17;
       uEffectType15 = new MinecraftModelDefine$EffectType("EffectType_VideoAdjustAssetModel", 38);
       MinecraftModelDefine$EffectType.EffectType_VideoAdjustAssetModel = uEffectType15;
       MinecraftModelDefine$EffectType[] uEffectTypeA = new MinecraftModelDefine$EffectType[39];
       uEffectTypeA[0] = uEffectType;
       uEffectTypeA[1] = uEffectType1;
       uEffectTypeA[2] = uEffectType2;
       uEffectTypeA[3] = uEffectType3;
       uEffectTypeA[4] = uEffectType4;
       uEffectTypeA[5] = uEffectType5;
       uEffectTypeA[6] = uEffectType6;
       uEffectTypeA[7] = uEffectType7;
       uEffectTypeA[8] = uEffectType8;
       uEffectTypeA[9] = uEffectType9;
       uEffectTypeA[10] = uEffectType10;
       uEffectTypeA[11] = uEffectType11;
       uEffectTypeA[12] = uEffectType12;
       uEffectTypeA[13] = uEffectType14;
       uEffectTypeA[14] = uEffectType16;
       uEffectTypeA[15] = uEffectType18;
       uEffectTypeA[16] = uEffectType19;
       uEffectTypeA[17] = uEffectType20;
       uEffectTypeA[18] = uEffectType21;
       uEffectTypeA[19] = uEffectType22;
       uEffectTypeA[20] = uEffectType23;
       uEffectTypeA[21] = uEffectType24;
       uEffectTypeA[22] = uEffectType25;
       uEffectTypeA[23] = uEffectType26;
       uEffectTypeA[24] = uEffectType27;
       uEffectTypeA[25] = uEffectType28;
       uEffectTypeA[26] = uEffectType29;
       uEffectTypeA[27] = uEffectType30;
       uEffectTypeA[28] = uEffectType31;
       uEffectTypeA[29] = uEffectType32;
       uEffectTypeA[30] = uEffectType33;
       uEffectTypeA[31] = uEffectType34;
       uEffectTypeA[32] = uEffectType35;
       uEffectTypeA[33] = uEffectType36;
       uEffectTypeA[34] = uEffectType37;
       uEffectTypeA[35] = uEffectType38;
       uEffectTypeA[36] = uEffectType39;
       uEffectTypeA[37] = uEffectType40;
       uEffectTypeA[38] = uEffectType15;
       MinecraftModelDefine$EffectType.$VALUES = uEffectTypeA;
    }
    public void MinecraftModelDefine$EffectType(String p0,int p1){
       super(p0, p1);
    }
    public static MinecraftModelDefine$EffectType valueOf(String p0){
       Object obj = PatchProxy.applyOneRefs(p0, null, MinecraftModelDefine$EffectType.class, "2");
       if (obj != PatchProxyResult.class) {
          return obj;
       }
       return Enum.valueOf(MinecraftModelDefine$EffectType.class, p0);
    }
    public static MinecraftModelDefine$EffectType[] values(){
       Object obj = PatchProxy.apply(null, null, MinecraftModelDefine$EffectType.class, "1");
       if (obj != PatchProxyResult.class) {
          return obj;
       }
       return MinecraftModelDefine$EffectType.$VALUES.clone();
    }
}
