package av5.d;
import f55.c;
import android.app.Activity;
import com.kwai.feature.api.social.bridge.beans.JsNoticeParams;
import f55.g;
import com.kwai.feature.api.social.bridge.beans.JsSendImFriendMessageParams;
import p55.a;
import com.kwai.feature.api.social.bridge.beans.JsPreloadImagesParam;
import java.lang.String;
import com.kwai.feature.api.social.bridge.beans.JsRecommendStatParams;
import com.kwai.feature.api.social.bridge.beans.JsMobileLoginInfoParams;
import com.kwai.feature.api.social.bridge.beans.JsEnterGroupChatParams;
import com.kwai.feature.api.social.bridge.beans.JsFollowActivityIdParams;
import com.kwai.feature.api.social.bridge.beans.JsEncryptedNameParams;
import com.kwai.sharelib.jsshare.StartShareParam;
import android.content.Context;
import com.kwai.feature.api.social.bridge.beans.JsTokenBlockShareIdParams;
import com.kwai.feature.api.social.bridge.beans.JsJoinGroupParams;
import com.kwai.feature.api.social.bridge.beans.JsVerifySMSCodeParams;
import com.kwai.feature.api.social.bridge.beans.JsSetClipParams;
import com.kwai.feature.api.social.bridge.beans.JsFollowRequestParams;
import com.kwai.feature.api.social.bridge.beans.JsFollowReferParams;
import com.kwai.feature.api.social.bridge.beans.JsThirdPartyLoginParams;
import com.kwai.feature.api.social.bridge.beans.JsSlideEntranceParams;
import com.kwai.feature.api.social.bridge.beans.JsLoginParams;
import com.kwai.feature.api.social.bridge.beans.JsMultiChooseMessageParams;
import com.yxcorp.gifshow.activity.GifshowActivity;
import com.kwai.feature.api.social.bridge.beans.JsAuthParams;

public interface abstract d implements c	// class@0003be
{

    void C1(Activity p0,JsNoticeParams p1,g p2);
    void E0(Activity p0,g p1);
    void E8(JsSendImFriendMessageParams p0,g p1);
    void I7(a p0,Activity p1,JsPreloadImagesParam p2,g p3);
    void K7(String p0);
    void K8(a p0,Activity p1,JsRecommendStatParams p2,g p3);
    void M2(Activity p0,JsNoticeParams p1,g p2);
    void M9(Activity p0,JsMobileLoginInfoParams p1,g p2);
    void Q0(Activity p0,JsNoticeParams p1,g p2);
    void Q6(Activity p0,JsEnterGroupChatParams p1,g p2);
    void S7(Activity p0,JsFollowActivityIdParams p1,g p2);
    void S8(Activity p0,JsEncryptedNameParams p1,g p2);
    void T(Activity p0,g p1);
    void V9(a p0,Activity p1,StartShareParam p2,g p3);
    void X3(Activity p0,JsNoticeParams p1,g p2);
    void Y3();
    void Z3(Context p0,JsTokenBlockShareIdParams p1,g p2);
    void a4(Activity p0,JsJoinGroupParams p1,g p2);
    void aa(Activity p0,g p1);
    void b4(Activity p0,g p1);
    void b5(Activity p0,JsVerifySMSCodeParams p1,g p2);
    void b6(Activity p0,JsVerifySMSCodeParams p1,g p2);
    void c4(Activity p0,g p1);
    void d4(Activity p0,g p1);
    void d7(Context p0,JsSetClipParams p1,g p2);
    void e4(a p0,Activity p1,JsFollowRequestParams p2,g p3);
    void f4(Activity p0,g p1);
    void g4(a p0,Activity p1,JsFollowRequestParams p2,g p3);
    String getNameSpace();
    void h4(Activity p0,a p1,g p2);
    void i4(Activity p0,g p1);
    void j4(a p0,Activity p1,JsFollowReferParams p2,g p3);
    void j6(Activity p0,JsThirdPartyLoginParams p1,a p2,g p3);
    void logout();
    void m3(Activity p0,JsNoticeParams p1,g p2);
    void o8(Activity p0,String p1,g p2);
    void p0(Activity p0,JsSlideEntranceParams p1,g p2);
    void q9(Activity p0,JsLoginParams p1,a p2,g p3);
    void t1(Activity p0,JsNoticeParams p1,g p2);
    void t9(Activity p0,JsMultiChooseMessageParams p1,g p2);
    void v4(GifshowActivity p0,JsSendImFriendMessageParams p1,g p2);
    void v8(Activity p0,g p1);
    void y5(Activity p0,a p1,JsAuthParams p2,g p3);
}
