package o02.f;
import java.lang.String;
import brd.t;
import com.kuaishou.gifshow.network.degrade.RequestTiming;
import okhttp3.MultipartBody$Part;

public interface abstract f	// class@00344f
{

    t A(String p0,int p1);
    t B(String p0);
    t C(String p0,int p1,int p2,String p3);
    t D(String p0,String p1);
    t E(String p0,String p1,String p2,String p3,int p4,String p5,long p6);
    t F();
    t G();
    t H(String p0,String p1,String p2,String p3,String p4,String p5,int p6,String p7,boolean p8,int p9,String p10,int p11,String p12,String p13);
    t I();
    t J(String p0,long p1);
    t K(String p0,String p1);
    t L(String p0);
    t M(String p0,String p1,String p2,int p3,String p4,String p5,String p6);
    t N(boolean p0,boolean p1,boolean p2);
    t O(String p0,String p1,int p2,String p3);
    t P(String p0,String p1,String p2,String p3);
    t Q(RequestTiming p0);
    t R(String p0,String p1,String p2);
    t S(String p0,String p1,String p2,String p3);
    t T();
    t U(String p0);
    t V(String p0);
    t W(String p0);
    t X(int p0,String p1,MultipartBody$Part p2,String p3,boolean p4,String p5,boolean p6,String p7,boolean p8,String p9,boolean p10,boolean p11,String p12,int p13,int p14,String p15,long p16,String p17,int p18,String p19,String p20);
    t Y();
    t Z(String p0,String p1);
    t a(String p0);
    t a0(int p0,String p1,MultipartBody$Part p2,String p3,boolean p4,boolean p5,String p6,boolean p7,boolean p8,String p9,int p10,int p11,long p12,int p13,String p14,String p15);
    t b(String p0);
    t b0(String p0);
    t c(String p0);
    t c0(RequestTiming p0);
    t d(String p0,String p1);
    t d0(String p0,String p1);
    t e(String p0,String p1);
    t e0(String p0);
    t f(String p0);
    t f0(int p0,String p1,MultipartBody$Part p2,String p3,boolean p4,String p5,boolean p6,String p7,boolean p8,String p9,boolean p10,String p11,int p12,int p13,long p14,int p15,String p16,String p17);
    t g(String p0);
    t g0(String p0,String p1,String p2,String p3,String p4,String p5,int p6,String p7,String p8,int p9,String p10);
    t h(String p0,int p1);
    t h0(String p0);
    t i(String p0,String p1);
    t i0(String p0,String p1);
    t j(String p0,int p1);
    t j0(String p0,String p1);
    t k(String p0,String p1);
    t k0(String p0,String p1);
    t l();
    t l0(int p0,String p1,String p2,String p3,MultipartBody$Part p4,String p5,boolean p6,boolean p7,boolean p8,int p9,String p10,String p11);
    t m(String p0,String p1,int p2,int p3,String p4);
    t m0();
    t n();
    t n0(boolean p0);
    t o();
    t o0(String p0);
    t p(String p0,String p1,String p2,String p3,String p4,String p5,int p6,String p7,String p8,int p9,String p10);
    t p0(String p0,String p1,String p2);
    t q(String p0);
    t q0(int p0);
    t r(String p0,String p1,String p2);
    t r0(int p0);
    t s();
    t s0(String p0);
    t t(int p0,int p1,String p2,String p3,String p4,String p5,boolean p6,boolean p7,String p8,String p9,String p10,boolean p11,String p12,String p13,String p14);
    t t0(int p0,String p1,MultipartBody$Part p2,String p3,boolean p4,boolean p5,String p6,boolean p7,boolean p8,boolean p9,String p10,int p11,int p12,String p13,long p14,String p15,int p16,String p17,String p18);
    t u(int p0,int p1,double p2,boolean p3,String p4);
    t u0(String p0);
    t v(String p0,String p1,int p2);
    t v0();
    t w(String p0);
    t x(String p0);
    t y(String p0,String p1,int p2,String p3,String p4,String p5,boolean p6);
    t z(String p0,int p1,String p2);
}
