package com.yxcorp.gifshow.camerasdk.util.BlackListData$2;
import java.util.HashSet;
import java.lang.Object;

public class BlackListData$2 extends HashSet	// class@00104d
{

    public void BlackListData$2(){
       super();
       this.add("A5\(A5\)");
       this.add("A552 JOY Max\(A552 JOY Max\)");
       this.add("Ark Electronic Technology\(Benefit_M505\)");
       this.add("BLACKFOX\(BMM 431D\)");
       this.add("BLUBOO\(Picasso\)");
       this.add("BQ\(BQ-5071\)");
       this.add("BQ\(BQS-5060\)");
       this.add("BRAVIS\(BRAVIS X500\)");
       this.add("Blackview\(E7s\)");
       this.add("Bravis\(A503 Joy\)");
       this.add("Bravis\(A505 Joy Plus\)");
       this.add("CUBOT\(CUBOT ECHO\)");
       this.add("CMDC\(M651CY\)");
       this.add("CMDC\(M652\)");
       this.add("DOOGEE\(X5max\)");
       this.add("DOOGEE\(X9 Mini\)");
       this.add("Ergo\(A502_Aurum\)");
       this.add("Explay\(Fresh\)");
       this.add("FPT X58\(FPT X58\)");
       this.add("Fly\(FS507\)");
       this.add("Fly\(FS510\)");
       this.add("Fly\(FS514\)");
       this.add("GIGI\(Dream 9\)");
       this.add("GIONEE\(M3S\)");
       this.add("GiONEE\(M5\)");
       this.add("HOMTOM\(HT37\)");
       this.add("HUAWEI\(ANE-LX2\)");
       this.add("HUAWEI\(CAM-UL00\)");
       this.add("HUAWEI\(CHE-TL00\)");
       this.add("HUAWEI\(CHE-TL00H\)");
       this.add("HUAWEI\(CHE2-TL00\)");
       this.add("HUAWEI\(CHE2-TL00M\)");
       this.add("HUAWEI\(CHM-TL00\)");
       this.add("HUAWEI\(CHM-TL00H\)");
       this.add("HUAWEI\(CHM-UL00\)");
       this.add("Haier\(Haier A45\)");
       this.add("Jinga\(A450\)");
       this.add("Jinga\(Fresh\)");
       this.add("LEAGOO\(A504 Trace\)");
       this.add("LEAGOO\(LEAGOO M8\)");
       this.add("MANTA_MSP95014\(MSP95014\)");
       this.add("Meizu\(M5s\)");
       this.add("Meizu\(PRO 5\)");
       this.add("Meizu\(m2\)");
       this.add("Micromax\(Micromax Q354\)");
       this.add("Mobiistar\(Mobiistar_LAI_Zumbo_J_2017\)");
       this.add("Nomi\(i5030\)");
       this.add("OALE\(X2\)");
       this.add("OPPO\(6607\)");
       this.add("OPPO\(A37fw\)");
       this.add("OPPO\(OPPO R11 Pluskt\)");
       this.add("OPPO\(OPPO R11t\)");
       this.add("OPPO\(OPPO R7\)");
       this.add("OPPO\(OPPO R7s\)");
       this.add("OPPO\(R7c\)");
       this.add("OUKITEL\(C3\)");
       this.add("Positivo\(Positivo Twist S\)");
       this.add("Prestigio\(PSP3512DUO\)");
       this.add("Prestigio\(PSP3533DUO\)");
       this.add("Prestigio\(PSP5530DUO\)");
       this.add("Prestigio\(PSP7511DUO\)");
       this.add("Shark 5000\(Shark 5000\)");
       this.add("TCL\(5023F\)");
       this.add("TCL\(8050D\)");
       this.add("TCL\(8050E\)");
       this.add("TCL\(9010X\)");
       this.add("TWOE\(E500A\)");
       this.add("Texet\(TM-5005\)");
       this.add("Texet\(X-Plus\(TM-5577\)\)");
       this.add("VENSO\(RX-505\)");
       this.add("VERTEX\(Impress Style\)");
       this.add("Vertex\(Impress Eagle\)");
       this.add("Vertex\(Impress_Luck\)");
       this.add("Xiaomi\(HM 2A\)");
       this.add("Xiaomi\(HM NOTE 1S\)");
       this.add("alps\(A450\)");
       this.add("alps\(Bluboo  D2\)");
       this.add("alps\(Maya\)");
       this.add("alps\(X3\)");
       this.add("asus\(ASUS_T00J\)");
       this.add("asus\(ASUS_T00J-D\)");
       this.add("asus\(ASUS_X00BD\)");
       this.add("asus\(ASUS_X014D\)");
       this.add("asus\(ZB500KG\)");
       this.add("bravis\(bravis_A506\)");
       this.add("mobiistar\(mobiistar LAI ZORO 2\)");
       this.add("mobiistar\(mobiistar LAI ZORO 3\)");
       this.add("samsung\(GT-I9505\)");
       this.add("vivo\(vivo X5Max+\)");
       this.add("vivo\(vivo Y66i A\)");
       this.add("weixin\(Nova S2\)");
    }
}
