package com.kwai.component.photo.detail.slide.milano.MilanoContainerEventBus;
import java.lang.Object;
import io.reactivex.subjects.PublishSubject;
import brd.t;
import mrd.a;
import xl8.b;
import java.lang.Boolean;

public class MilanoContainerEventBus	// class@000a60
{
    public PublishSubject A;
    public PublishSubject B;
    public PublishSubject C;
    public PublishSubject D;
    public PublishSubject E;
    public PublishSubject F;
    public PublishSubject G;
    public PublishSubject H;
    public PublishSubject I;
    public PublishSubject J;
    public PublishSubject K;
    public PublishSubject L;
    public PublishSubject M;
    public PublishSubject N;
    public PublishSubject O;
    public final PublishSubject P;
    public final PublishSubject Q;
    public final PublishSubject R;
    public final PublishSubject S;
    public final PublishSubject T;
    public final PublishSubject U;
    public PublishSubject V;
    public PublishSubject W;
    public final PublishSubject a;
    public PublishSubject b;
    public PublishSubject c;
    public PublishSubject d;
    public final PublishSubject e;
    public final t f;
    public final y g;
    public final PublishSubject h;
    public final PublishSubject i;
    public final c j;
    public b k;
    public b l;
    public b m;
    public b n;
    public b o;
    public PublishSubject p;
    public PublishSubject q;
    public PublishSubject r;
    public PublishSubject s;
    public PublishSubject t;
    public PublishSubject u;
    public PublishSubject v;
    public PublishSubject w;
    public PublishSubject x;
    public PublishSubject y;
    public p z;

    public void MilanoContainerEventBus(){
       super();
       this.a = PublishSubject.g();
       this.b = PublishSubject.g();
       this.c = PublishSubject.g();
       this.d = PublishSubject.g();
       PublishSubject publishSubje = PublishSubject.g();
       this.e = publishSubje;
       this.f = publishSubje.hide();
       this.g = publishSubje;
       this.h = PublishSubject.g();
       this.i = PublishSubject.g();
       this.j = a.g();
       this.k = new b(Boolean.FALSE);
       Boolean tRUE = Boolean.TRUE;
       this.l = new b(tRUE);
       this.m = new b(tRUE);
       this.n = new b(tRUE);
       this.o = new b(tRUE);
       this.p = PublishSubject.g();
       this.q = PublishSubject.g();
       this.r = PublishSubject.g();
       this.s = PublishSubject.g();
       this.t = PublishSubject.g();
       this.u = PublishSubject.g();
       this.v = PublishSubject.g();
       this.w = PublishSubject.g();
       this.x = PublishSubject.g();
       this.y = PublishSubject.g();
       this.A = PublishSubject.g();
       this.B = PublishSubject.g();
       this.C = PublishSubject.g();
       this.D = PublishSubject.g();
       this.E = PublishSubject.g();
       this.F = PublishSubject.g();
       this.G = PublishSubject.g();
       this.H = PublishSubject.g();
       this.I = PublishSubject.g();
       this.J = PublishSubject.g();
       this.K = PublishSubject.g();
       this.L = PublishSubject.g();
       this.M = PublishSubject.g();
       this.N = PublishSubject.g();
       this.O = PublishSubject.g();
       this.P = PublishSubject.g();
       this.Q = PublishSubject.g();
       this.R = PublishSubject.g();
       this.S = PublishSubject.g();
       this.T = PublishSubject.g();
       this.U = PublishSubject.g();
       this.V = PublishSubject.g();
       this.W = PublishSubject.g();
    }
}
