package com.kwai.feature.api.live.base.service.bizrelation.AnchorBizRelation;
import aq5.a;
import java.lang.Enum;
import java.lang.String;
import java.util.HashMap;
import java.lang.Object;
import java.util.ArrayList;
import ekd.j;
import java.util.Map;
import java.lang.Class;
import com.kwai.robust.PatchProxy;
import com.kwai.robust.PatchProxyResult;
import java.lang.Number;
import java.lang.Long;
import java.util.List;
import java.util.Collection;
import ekd.q;

public final class AnchorBizRelation extends Enum implements a	// class@000f94
{
    public int mPriority;
    public Long mRelationBits;
    public static final AnchorBizRelation[] $VALUES;
    public static final AnchorBizRelation ARROW_RED_PACKET;
    public static final AnchorBizRelation BGM;
    public static final AnchorBizRelation BUSINESS_PROMOTION;
    public static final AnchorBizRelation CHAT_BETWEEN_ANCHORS;
    public static final AnchorBizRelation CHAT_CENTER_VIEW;
    public static final AnchorBizRelation CHAT_CHOOSE_GUEST;
    public static final AnchorBizRelation CHAT_WITH_GUEST;
    public static final AnchorBizRelation FANS_GROUP;
    public static final AnchorBizRelation FANS_TOP;
    public static final AnchorBizRelation LIVE_BGM_CHANNEL_PLAY;
    public static final AnchorBizRelation LIVE_CHAT_BE_INVITED_DIALOG;
    public static final AnchorBizRelation LIVE_GIFT_RAMPAGE;
    public static final AnchorBizRelation LIVE_LINE;
    public static final AnchorBizRelation LIVE_LINE_PENDANT;
    public static final AnchorBizRelation LIVE_MULTI_LINE;
    public static final AnchorBizRelation LIVE_MULTI_PK;
    public static final AnchorBizRelation LIVE_PAID_SHOW;
    public static final AnchorBizRelation LIVE_PET_ACTION;
    public static final AnchorBizRelation LIVE_PK_PENDANT;
    public static final AnchorBizRelation LIVE_PK_WAITING;
    public static final AnchorBizRelation MAGIC_GIFT;
    public static final AnchorBizRelation MERCHANT_AUCTION_BUBBLE;
    public static final AnchorBizRelation MERCHANT_NEW_PENDANT;
    public static final AnchorBizRelation MUSIC_STATION_APPLY;
    public static final AnchorBizRelation NATURE_LOOK;
    public static final AnchorBizRelation PK;
    public static final AnchorBizRelation PK_GIFT_MOMENT;
    public static final AnchorBizRelation RECRUIT_EXPLAIN_PANEL;
    public static final AnchorBizRelation RED_PACKET_CONTAINER;
    public static final AnchorBizRelation ROBOT;
    public static final AnchorBizRelation ROBOT_LONG_AUDIO;
    public static final AnchorBizRelation SEND_COMMENT;
    public static final AnchorBizRelation VIEW_PAGER_PENDANT;
    public static final AnchorBizRelation VOICE_COMMENT;
    public static final AnchorBizRelation VOICE_PARTY;
    public static final AnchorBizRelation VOICE_PARTY_AUDIO;
    public static final AnchorBizRelation VOICE_PARTY_CROSS_ROOM_PK;
    public static final AnchorBizRelation VOICE_PARTY_GRID_CHAT;
    public static final AnchorBizRelation VOICE_PARTY_KTV;
    public static final AnchorBizRelation VOICE_PARTY_TEAM_PK;
    public static final AnchorBizRelation VOICE_PARTY_THEATER;
    public static final AnchorBizRelation VOICE_PARTY_THEATER_FULL_SCREEN;
    public static final AnchorBizRelation VOICE_PARTY_VIDEO;
    public static final AnchorBizRelation WISH_LIST;
    public static Map mBizRelationMap;

    static {
       AnchorBizRelation uAnchorBizRe = new AnchorBizRelation("VOICE_PARTY", 0, 999);
       AnchorBizRelation.VOICE_PARTY = uAnchorBizRe;
       AnchorBizRelation uAnchorBizRe1 = new AnchorBizRelation("CHAT_CHOOSE_GUEST", 1, 500);
       AnchorBizRelation.CHAT_CHOOSE_GUEST = uAnchorBizRe1;
       AnchorBizRelation uAnchorBizRe2 = new AnchorBizRelation("PK", 2, 999);
       AnchorBizRelation.PK = uAnchorBizRe2;
       AnchorBizRelation uAnchorBizRe3 = new AnchorBizRelation("LIVE_LINE", 3, 999);
       AnchorBizRelation.LIVE_LINE = uAnchorBizRe3;
       AnchorBizRelation uAnchorBizRe4 = new AnchorBizRelation("LIVE_MULTI_LINE", 4, 999);
       AnchorBizRelation.LIVE_MULTI_LINE = uAnchorBizRe4;
       AnchorBizRelation uAnchorBizRe5 = new AnchorBizRelation("LIVE_MULTI_PK", 5, 999);
       AnchorBizRelation.LIVE_MULTI_PK = uAnchorBizRe5;
       AnchorBizRelation uAnchorBizRe6 = new AnchorBizRelation("VOICE_COMMENT", 6, 500);
       AnchorBizRelation.VOICE_COMMENT = uAnchorBizRe6;
       AnchorBizRelation uAnchorBizRe7 = new AnchorBizRelation("CHAT_WITH_GUEST", 7, 999);
       AnchorBizRelation.CHAT_WITH_GUEST = uAnchorBizRe7;
       AnchorBizRelation uAnchorBizRe8 = new AnchorBizRelation("CHAT_CENTER_VIEW", 8, 999);
       AnchorBizRelation.CHAT_CENTER_VIEW = uAnchorBizRe8;
       AnchorBizRelation uAnchorBizRe9 = new AnchorBizRelation("MUSIC_STATION_APPLY", 9, 100);
       AnchorBizRelation.MUSIC_STATION_APPLY = uAnchorBizRe9;
       AnchorBizRelation uAnchorBizRe10 = new AnchorBizRelation("BGM", 10, 90);
       AnchorBizRelation.BGM = uAnchorBizRe10;
       AnchorBizRelation uAnchorBizRe11 = new AnchorBizRelation("NATURE_LOOK", 11, 90);
       AnchorBizRelation.NATURE_LOOK = uAnchorBizRe11;
       AnchorBizRelation uAnchorBizRe12 = new AnchorBizRelation("VOICE_PARTY_KTV", 12, 999);
       AnchorBizRelation.VOICE_PARTY_KTV = uAnchorBizRe12;
       AnchorBizRelation uAnchorBizRe13 = uAnchorBizRe12;
       AnchorBizRelation uAnchorBizRe14 = new AnchorBizRelation("CHAT_BETWEEN_ANCHORS", 13, 999);
       AnchorBizRelation.CHAT_BETWEEN_ANCHORS = uAnchorBizRe14;
       AnchorBizRelation uAnchorBizRe15 = uAnchorBizRe14;
       AnchorBizRelation uAnchorBizRe16 = new AnchorBizRelation("SEND_COMMENT", 14, 1);
       AnchorBizRelation.SEND_COMMENT = uAnchorBizRe16;
       AnchorBizRelation uAnchorBizRe17 = uAnchorBizRe16;
       uAnchorBizRe14 = new AnchorBizRelation("WISH_LIST", 15, 90);
       AnchorBizRelation.WISH_LIST = uAnchorBizRe14;
       AnchorBizRelation uAnchorBizRe18 = uAnchorBizRe14;
       uAnchorBizRe12 = new AnchorBizRelation("FANS_TOP", 16, 90);
       AnchorBizRelation.FANS_TOP = uAnchorBizRe12;
       AnchorBizRelation uAnchorBizRe19 = uAnchorBizRe12;
       AnchorBizRelation uAnchorBizRe20 = new AnchorBizRelation("VIEW_PAGER_PENDANT", 17, 90);
       AnchorBizRelation.VIEW_PAGER_PENDANT = uAnchorBizRe20;
       AnchorBizRelation uAnchorBizRe21 = uAnchorBizRe20;
       uAnchorBizRe14 = new AnchorBizRelation("LIVE_BGM_CHANNEL_PLAY", 18, 90);
       AnchorBizRelation.LIVE_BGM_CHANNEL_PLAY = uAnchorBizRe14;
       AnchorBizRelation uAnchorBizRe22 = uAnchorBizRe14;
       uAnchorBizRe12 = new AnchorBizRelation("MAGIC_GIFT", 19, 90);
       AnchorBizRelation.MAGIC_GIFT = uAnchorBizRe12;
       AnchorBizRelation uAnchorBizRe23 = uAnchorBizRe12;
       uAnchorBizRe16 = new AnchorBizRelation("FANS_GROUP", 20, 1);
       AnchorBizRelation.FANS_GROUP = uAnchorBizRe16;
       AnchorBizRelation uAnchorBizRe24 = uAnchorBizRe16;
       uAnchorBizRe20 = new AnchorBizRelation("ARROW_RED_PACKET", 21, 0);
       AnchorBizRelation.ARROW_RED_PACKET = uAnchorBizRe20;
       AnchorBizRelation uAnchorBizRe25 = uAnchorBizRe20;
       uAnchorBizRe16 = new AnchorBizRelation("ROBOT", 22, 1);
       AnchorBizRelation.ROBOT = uAnchorBizRe16;
       AnchorBizRelation uAnchorBizRe26 = uAnchorBizRe16;
       uAnchorBizRe20 = new AnchorBizRelation("ROBOT_LONG_AUDIO", 23, 90);
       AnchorBizRelation.ROBOT_LONG_AUDIO = uAnchorBizRe20;
       AnchorBizRelation uAnchorBizRe27 = uAnchorBizRe20;
       uAnchorBizRe16 = new AnchorBizRelation("LIVE_CHAT_BE_INVITED_DIALOG", 24, 0);
       AnchorBizRelation.LIVE_CHAT_BE_INVITED_DIALOG = uAnchorBizRe16;
       AnchorBizRelation uAnchorBizRe28 = uAnchorBizRe16;
       uAnchorBizRe14 = new AnchorBizRelation("LIVE_PET_ACTION", 25, 91);
       AnchorBizRelation.LIVE_PET_ACTION = uAnchorBizRe14;
       AnchorBizRelation uAnchorBizRe29 = uAnchorBizRe14;
       uAnchorBizRe16 = new AnchorBizRelation("PK_GIFT_MOMENT", 26, 0);
       AnchorBizRelation.PK_GIFT_MOMENT = uAnchorBizRe16;
       AnchorBizRelation uAnchorBizRe30 = uAnchorBizRe16;
       uAnchorBizRe20 = new AnchorBizRelation("VOICE_PARTY_THEATER_FULL_SCREEN", 27, 10);
       AnchorBizRelation.VOICE_PARTY_THEATER_FULL_SCREEN = uAnchorBizRe20;
       AnchorBizRelation uAnchorBizRe31 = uAnchorBizRe20;
       uAnchorBizRe16 = new AnchorBizRelation("VOICE_PARTY_THEATER", 28, 0);
       AnchorBizRelation.VOICE_PARTY_THEATER = uAnchorBizRe16;
       AnchorBizRelation uAnchorBizRe32 = uAnchorBizRe16;
       uAnchorBizRe14 = new AnchorBizRelation("VOICE_PARTY_VIDEO", 29, 0);
       AnchorBizRelation.VOICE_PARTY_VIDEO = uAnchorBizRe14;
       AnchorBizRelation uAnchorBizRe33 = uAnchorBizRe14;
       uAnchorBizRe16 = new AnchorBizRelation("VOICE_PARTY_AUDIO", 30, 0);
       AnchorBizRelation.VOICE_PARTY_AUDIO = uAnchorBizRe16;
       AnchorBizRelation uAnchorBizRe34 = uAnchorBizRe16;
       uAnchorBizRe14 = new AnchorBizRelation("VOICE_PARTY_CROSS_ROOM_PK", 31, 0);
       AnchorBizRelation.VOICE_PARTY_CROSS_ROOM_PK = uAnchorBizRe14;
       AnchorBizRelation uAnchorBizRe35 = uAnchorBizRe14;
       uAnchorBizRe16 = new AnchorBizRelation("RED_PACKET_CONTAINER", 32, 0);
       AnchorBizRelation.RED_PACKET_CONTAINER = uAnchorBizRe16;
       AnchorBizRelation uAnchorBizRe36 = uAnchorBizRe16;
       uAnchorBizRe14 = new AnchorBizRelation("VOICE_PARTY_TEAM_PK", 33, 0);
       AnchorBizRelation.VOICE_PARTY_TEAM_PK = uAnchorBizRe14;
       AnchorBizRelation uAnchorBizRe37 = uAnchorBizRe14;
       uAnchorBizRe16 = new AnchorBizRelation("VOICE_PARTY_GRID_CHAT", 34, 0);
       AnchorBizRelation.VOICE_PARTY_GRID_CHAT = uAnchorBizRe16;
       AnchorBizRelation uAnchorBizRe38 = uAnchorBizRe16;
       uAnchorBizRe20 = new AnchorBizRelation("BUSINESS_PROMOTION", 35, 500);
       AnchorBizRelation.BUSINESS_PROMOTION = uAnchorBizRe20;
       AnchorBizRelation uAnchorBizRe39 = uAnchorBizRe20;
       uAnchorBizRe16 = new AnchorBizRelation("LIVE_PAID_SHOW", 36, 999);
       AnchorBizRelation.LIVE_PAID_SHOW = uAnchorBizRe16;
       AnchorBizRelation uAnchorBizRe40 = uAnchorBizRe16;
       uAnchorBizRe14 = new AnchorBizRelation("LIVE_LINE_PENDANT", 37, 999);
       AnchorBizRelation.LIVE_LINE_PENDANT = uAnchorBizRe14;
       AnchorBizRelation uAnchorBizRe41 = uAnchorBizRe14;
       uAnchorBizRe16 = new AnchorBizRelation("LIVE_PK_PENDANT", 38, 999);
       AnchorBizRelation.LIVE_PK_PENDANT = uAnchorBizRe16;
       AnchorBizRelation uAnchorBizRe42 = uAnchorBizRe16;
       uAnchorBizRe14 = new AnchorBizRelation("LIVE_PK_WAITING", 39, 999);
       AnchorBizRelation.LIVE_PK_WAITING = uAnchorBizRe14;
       AnchorBizRelation uAnchorBizRe43 = uAnchorBizRe14;
       uAnchorBizRe16 = new AnchorBizRelation("LIVE_GIFT_RAMPAGE", 40, 200);
       AnchorBizRelation.LIVE_GIFT_RAMPAGE = uAnchorBizRe16;
       AnchorBizRelation uAnchorBizRe44 = uAnchorBizRe16;
       uAnchorBizRe20 = new AnchorBizRelation("MERCHANT_AUCTION_BUBBLE", 41, 999);
       AnchorBizRelation.MERCHANT_AUCTION_BUBBLE = uAnchorBizRe20;
       AnchorBizRelation uAnchorBizRe45 = uAnchorBizRe20;
       uAnchorBizRe14 = new AnchorBizRelation("MERCHANT_NEW_PENDANT", 42, 999);
       AnchorBizRelation.MERCHANT_NEW_PENDANT = uAnchorBizRe14;
       AnchorBizRelation uAnchorBizRe46 = uAnchorBizRe14;
       uAnchorBizRe20 = new AnchorBizRelation("RECRUIT_EXPLAIN_PANEL", 43, 999);
       AnchorBizRelation.RECRUIT_EXPLAIN_PANEL = uAnchorBizRe20;
       AnchorBizRelation[] uAnchorBizRe47 = new AnchorBizRelation[44];
       uAnchorBizRe47[0] = uAnchorBizRe;
       uAnchorBizRe47[1] = uAnchorBizRe1;
       uAnchorBizRe47[2] = uAnchorBizRe2;
       uAnchorBizRe47[3] = uAnchorBizRe3;
       uAnchorBizRe47[4] = uAnchorBizRe4;
       uAnchorBizRe47[5] = uAnchorBizRe5;
       uAnchorBizRe47[6] = uAnchorBizRe6;
       uAnchorBizRe47[7] = uAnchorBizRe7;
       uAnchorBizRe47[8] = uAnchorBizRe8;
       uAnchorBizRe47[9] = uAnchorBizRe9;
       uAnchorBizRe47[10] = uAnchorBizRe10;
       uAnchorBizRe47[11] = uAnchorBizRe11;
       uAnchorBizRe47[12] = uAnchorBizRe13;
       uAnchorBizRe47[13] = uAnchorBizRe15;
       uAnchorBizRe47[14] = uAnchorBizRe17;
       uAnchorBizRe47[15] = uAnchorBizRe18;
       uAnchorBizRe47[16] = uAnchorBizRe19;
       uAnchorBizRe47[17] = uAnchorBizRe21;
       uAnchorBizRe47[18] = uAnchorBizRe22;
       uAnchorBizRe47[19] = uAnchorBizRe23;
       uAnchorBizRe47[20] = uAnchorBizRe24;
       uAnchorBizRe47[21] = uAnchorBizRe25;
       uAnchorBizRe47[22] = uAnchorBizRe26;
       uAnchorBizRe47[23] = uAnchorBizRe27;
       uAnchorBizRe47[24] = uAnchorBizRe28;
       uAnchorBizRe47[25] = uAnchorBizRe29;
       uAnchorBizRe47[26] = uAnchorBizRe30;
       uAnchorBizRe47[27] = uAnchorBizRe31;
       uAnchorBizRe47[28] = uAnchorBizRe32;
       uAnchorBizRe47[29] = uAnchorBizRe33;
       uAnchorBizRe47[30] = uAnchorBizRe34;
       uAnchorBizRe47[31] = uAnchorBizRe35;
       uAnchorBizRe47[32] = uAnchorBizRe36;
       uAnchorBizRe47[33] = uAnchorBizRe37;
       uAnchorBizRe47[34] = uAnchorBizRe38;
       uAnchorBizRe47[35] = uAnchorBizRe39;
       uAnchorBizRe47[36] = uAnchorBizRe40;
       uAnchorBizRe47[37] = uAnchorBizRe41;
       uAnchorBizRe47[38] = uAnchorBizRe42;
       uAnchorBizRe47[39] = uAnchorBizRe43;
       uAnchorBizRe47[40] = uAnchorBizRe44;
       uAnchorBizRe47[41] = uAnchorBizRe45;
       uAnchorBizRe47[42] = uAnchorBizRe46;
       uAnchorBizRe47[43] = uAnchorBizRe20;
       AnchorBizRelation.$VALUES = uAnchorBizRe47;
       HashMap hashMap = new HashMap();
       AnchorBizRelation.mBizRelationMap = hashMap;
       AnchorBizRelation[] uAnchorBizRe48 = new AnchorBizRelation[12];
       uAnchorBizRe48[0] = uAnchorBizRe1;
       uAnchorBizRe48[1] = uAnchorBizRe2;
       uAnchorBizRe48[2] = uAnchorBizRe3;
       uAnchorBizRe48[3] = uAnchorBizRe4;
       uAnchorBizRe48[4] = uAnchorBizRe5;
       uAnchorBizRe48[5] = uAnchorBizRe6;
       uAnchorBizRe48[6] = uAnchorBizRe7;
       uAnchorBizRe48[7] = uAnchorBizRe9;
       uAnchorBizRe48[8] = uAnchorBizRe15;
       uAnchorBizRe48[9] = uAnchorBizRe19;
       uAnchorBizRe48[10] = uAnchorBizRe21;
       uAnchorBizRe48[11] = uAnchorBizRe40;
       hashMap.put(uAnchorBizRe, j.a(uAnchorBizRe48));
       uAnchorBizRe48 = new AnchorBizRelation[9];
       uAnchorBizRe48[0] = uAnchorBizRe;
       uAnchorBizRe48[1] = uAnchorBizRe2;
       uAnchorBizRe48[2] = uAnchorBizRe3;
       uAnchorBizRe48[3] = uAnchorBizRe4;
       uAnchorBizRe48[4] = uAnchorBizRe5;
       uAnchorBizRe48[5] = uAnchorBizRe40;
       uAnchorBizRe48[6] = uAnchorBizRe42;
       uAnchorBizRe48[7] = uAnchorBizRe43;
       uAnchorBizRe48[8] = uAnchorBizRe41;
       AnchorBizRelation.mBizRelationMap.put(uAnchorBizRe1, j.a(uAnchorBizRe48));
       uAnchorBizRe48 = new AnchorBizRelation[]{uAnchorBizRe3,uAnchorBizRe4,uAnchorBizRe2,uAnchorBizRe5,uAnchorBizRe,uAnchorBizRe8};
       AnchorBizRelation.mBizRelationMap.put(uAnchorBizRe20, j.a(uAnchorBizRe48));
       uAnchorBizRe39 = uAnchorBizRe11;
       AnchorBizRelation[] uAnchorBizRe49 = new AnchorBizRelation[13];
       uAnchorBizRe49[0] = uAnchorBizRe3;
       uAnchorBizRe49[1] = uAnchorBizRe4;
       uAnchorBizRe49[2] = uAnchorBizRe5;
       uAnchorBizRe49[3] = uAnchorBizRe;
       uAnchorBizRe49[4] = uAnchorBizRe1;
       uAnchorBizRe49[5] = uAnchorBizRe7;
       uAnchorBizRe49[6] = uAnchorBizRe20;
       uAnchorBizRe49[7] = uAnchorBizRe9;
       uAnchorBizRe49[8] = uAnchorBizRe15;
       uAnchorBizRe49[9] = uAnchorBizRe23;
       uAnchorBizRe49[10] = uAnchorBizRe26;
       uAnchorBizRe49[11] = uAnchorBizRe28;
       uAnchorBizRe49[12] = uAnchorBizRe40;
       AnchorBizRelation.mBizRelationMap.put(uAnchorBizRe2, j.a(uAnchorBizRe49));
       uAnchorBizRe48 = new AnchorBizRelation[13];
       uAnchorBizRe48[0] = uAnchorBizRe2;
       uAnchorBizRe48[1] = uAnchorBizRe;
       uAnchorBizRe48[2] = uAnchorBizRe1;
       uAnchorBizRe48[3] = uAnchorBizRe7;
       uAnchorBizRe48[4] = uAnchorBizRe9;
       uAnchorBizRe48[5] = uAnchorBizRe15;
       uAnchorBizRe48[6] = uAnchorBizRe20;
       uAnchorBizRe48[7] = uAnchorBizRe23;
       uAnchorBizRe48[8] = uAnchorBizRe26;
       uAnchorBizRe48[9] = uAnchorBizRe28;
       uAnchorBizRe48[10] = uAnchorBizRe40;
       uAnchorBizRe48[11] = uAnchorBizRe4;
       uAnchorBizRe48[12] = uAnchorBizRe5;
       AnchorBizRelation.mBizRelationMap.put(uAnchorBizRe3, j.a(uAnchorBizRe48));
       uAnchorBizRe48 = new AnchorBizRelation[13];
       uAnchorBizRe48[0] = uAnchorBizRe2;
       uAnchorBizRe48[1] = uAnchorBizRe;
       uAnchorBizRe48[2] = uAnchorBizRe1;
       uAnchorBizRe48[3] = uAnchorBizRe7;
       uAnchorBizRe48[4] = uAnchorBizRe9;
       uAnchorBizRe48[5] = uAnchorBizRe15;
       uAnchorBizRe48[6] = uAnchorBizRe20;
       uAnchorBizRe48[7] = uAnchorBizRe23;
       uAnchorBizRe48[8] = uAnchorBizRe26;
       uAnchorBizRe48[9] = uAnchorBizRe28;
       uAnchorBizRe48[10] = uAnchorBizRe40;
       uAnchorBizRe48[11] = uAnchorBizRe3;
       uAnchorBizRe48[12] = uAnchorBizRe5;
       AnchorBizRelation.mBizRelationMap.put(uAnchorBizRe4, j.a(uAnchorBizRe48));
       AnchorBizRelation[] uAnchorBizRe50 = new AnchorBizRelation[13];
       uAnchorBizRe50[0] = uAnchorBizRe2;
       uAnchorBizRe50[1] = uAnchorBizRe;
       uAnchorBizRe50[2] = uAnchorBizRe1;
       uAnchorBizRe50[3] = uAnchorBizRe7;
       uAnchorBizRe50[4] = uAnchorBizRe9;
       uAnchorBizRe50[5] = uAnchorBizRe15;
       uAnchorBizRe50[6] = uAnchorBizRe20;
       uAnchorBizRe50[7] = uAnchorBizRe23;
       uAnchorBizRe50[8] = uAnchorBizRe26;
       uAnchorBizRe50[9] = uAnchorBizRe28;
       uAnchorBizRe50[10] = uAnchorBizRe40;
       uAnchorBizRe50[11] = uAnchorBizRe3;
       uAnchorBizRe50[12] = uAnchorBizRe4;
       AnchorBizRelation.mBizRelationMap.put(uAnchorBizRe5, j.a(uAnchorBizRe50));
       uAnchorBizRe50 = new AnchorBizRelation[]{uAnchorBizRe,uAnchorBizRe7,uAnchorBizRe9,uAnchorBizRe15,uAnchorBizRe40};
       AnchorBizRelation.mBizRelationMap.put(uAnchorBizRe6, j.a(uAnchorBizRe50));
       uAnchorBizRe49 = new AnchorBizRelation[10];
       uAnchorBizRe49[0] = uAnchorBizRe;
       uAnchorBizRe49[1] = uAnchorBizRe2;
       uAnchorBizRe49[2] = uAnchorBizRe3;
       uAnchorBizRe49[3] = uAnchorBizRe4;
       uAnchorBizRe49[4] = uAnchorBizRe5;
       uAnchorBizRe49[5] = uAnchorBizRe6;
       uAnchorBizRe49[6] = uAnchorBizRe9;
       uAnchorBizRe49[7] = uAnchorBizRe15;
       uAnchorBizRe49[8] = uAnchorBizRe40;
       uAnchorBizRe49[9] = uAnchorBizRe13;
       AnchorBizRelation.mBizRelationMap.put(uAnchorBizRe7, j.a(uAnchorBizRe49));
       AnchorBizRelation[] uAnchorBizRe51 = new AnchorBizRelation[]{uAnchorBizRe20};
       AnchorBizRelation.mBizRelationMap.put(uAnchorBizRe8, j.a(uAnchorBizRe51));
       AnchorBizRelation[] uAnchorBizRe52 = new AnchorBizRelation[]{uAnchorBizRe,uAnchorBizRe2,uAnchorBizRe3,uAnchorBizRe4,uAnchorBizRe5,uAnchorBizRe6,uAnchorBizRe7,uAnchorBizRe15};
       AnchorBizRelation.mBizRelationMap.put(uAnchorBizRe9, j.a(uAnchorBizRe52));
       uAnchorBizRe52 = new AnchorBizRelation[]{uAnchorBizRe,uAnchorBizRe13};
       uAnchorBizRe8 = uAnchorBizRe39;
       AnchorBizRelation.mBizRelationMap.put(uAnchorBizRe8, j.a(uAnchorBizRe52));
       uAnchorBizRe52 = new AnchorBizRelation[]{uAnchorBizRe8,uAnchorBizRe15,uAnchorBizRe7,uAnchorBizRe19,uAnchorBizRe21,uAnchorBizRe22,uAnchorBizRe40};
       uAnchorBizRe8 = uAnchorBizRe13;
       AnchorBizRelation.mBizRelationMap.put(uAnchorBizRe8, j.a(uAnchorBizRe52));
       uAnchorBizRe48 = new AnchorBizRelation[10];
       uAnchorBizRe48[0] = uAnchorBizRe;
       uAnchorBizRe48[1] = uAnchorBizRe2;
       uAnchorBizRe48[2] = uAnchorBizRe3;
       uAnchorBizRe48[3] = uAnchorBizRe4;
       uAnchorBizRe48[4] = uAnchorBizRe5;
       uAnchorBizRe48[5] = uAnchorBizRe6;
       uAnchorBizRe48[6] = uAnchorBizRe7;
       uAnchorBizRe48[7] = uAnchorBizRe9;
       uAnchorBizRe48[8] = uAnchorBizRe8;
       uAnchorBizRe48[9] = uAnchorBizRe26;
       uAnchorBizRe10 = uAnchorBizRe15;
       AnchorBizRelation.mBizRelationMap.put(uAnchorBizRe10, j.a(uAnchorBizRe48));
       uAnchorBizRe52 = new AnchorBizRelation[]{uAnchorBizRe,uAnchorBizRe8};
       AnchorBizRelation.mBizRelationMap.put(uAnchorBizRe19, j.a(uAnchorBizRe52));
       uAnchorBizRe52 = new AnchorBizRelation[]{uAnchorBizRe,uAnchorBizRe8};
       AnchorBizRelation.mBizRelationMap.put(uAnchorBizRe21, j.a(uAnchorBizRe52));
       uAnchorBizRe52 = new AnchorBizRelation[]{uAnchorBizRe8};
       AnchorBizRelation.mBizRelationMap.put(uAnchorBizRe22, j.a(uAnchorBizRe52));
       uAnchorBizRe50 = new AnchorBizRelation[]{uAnchorBizRe2,uAnchorBizRe3,uAnchorBizRe4,uAnchorBizRe5};
       uAnchorBizRe20 = uAnchorBizRe23;
       AnchorBizRelation.mBizRelationMap.put(uAnchorBizRe20, j.a(uAnchorBizRe50));
       uAnchorBizRe51 = new AnchorBizRelation[]{uAnchorBizRe17};
       AnchorBizRelation.mBizRelationMap.put(uAnchorBizRe24, j.a(uAnchorBizRe51));
       uAnchorBizRe51 = new AnchorBizRelation[]{uAnchorBizRe2,uAnchorBizRe3,uAnchorBizRe4,uAnchorBizRe5,uAnchorBizRe10,uAnchorBizRe29};
       uAnchorBizRe14 = uAnchorBizRe26;
       AnchorBizRelation.mBizRelationMap.put(uAnchorBizRe14, j.a(uAnchorBizRe51));
       uAnchorBizRe49 = new AnchorBizRelation[]{uAnchorBizRe2,uAnchorBizRe3,uAnchorBizRe4,uAnchorBizRe5};
       AnchorBizRelation.mBizRelationMap.put(uAnchorBizRe28, j.a(uAnchorBizRe49));
       uAnchorBizRe51 = new AnchorBizRelation[]{uAnchorBizRe2,uAnchorBizRe3,uAnchorBizRe4,uAnchorBizRe5,uAnchorBizRe14};
       AnchorBizRelation.mBizRelationMap.put(uAnchorBizRe29, j.a(uAnchorBizRe51));
       uAnchorBizRe49 = new AnchorBizRelation[]{uAnchorBizRe31};
       AnchorBizRelation.mBizRelationMap.put(uAnchorBizRe36, j.a(uAnchorBizRe49));
       uAnchorBizRe49 = new AnchorBizRelation[9];
       uAnchorBizRe49[0] = uAnchorBizRe;
       uAnchorBizRe49[1] = uAnchorBizRe1;
       uAnchorBizRe49[2] = uAnchorBizRe2;
       uAnchorBizRe49[3] = uAnchorBizRe3;
       uAnchorBizRe49[4] = uAnchorBizRe4;
       uAnchorBizRe49[5] = uAnchorBizRe5;
       uAnchorBizRe49[6] = uAnchorBizRe7;
       uAnchorBizRe49[7] = uAnchorBizRe6;
       uAnchorBizRe49[8] = uAnchorBizRe8;
       AnchorBizRelation.mBizRelationMap.put(uAnchorBizRe40, j.a(uAnchorBizRe49));
       AnchorBizRelation[] uAnchorBizRe53 = new AnchorBizRelation[12];
       uAnchorBizRe53[0] = uAnchorBizRe;
       uAnchorBizRe53[1] = uAnchorBizRe1;
       uAnchorBizRe53[2] = uAnchorBizRe7;
       uAnchorBizRe53[3] = uAnchorBizRe9;
       uAnchorBizRe53[4] = uAnchorBizRe10;
       uAnchorBizRe53[5] = uAnchorBizRe20;
       uAnchorBizRe53[6] = uAnchorBizRe14;
       uAnchorBizRe53[7] = uAnchorBizRe28;
       uAnchorBizRe53[8] = uAnchorBizRe41;
       uAnchorBizRe53[9] = uAnchorBizRe3;
       uAnchorBizRe53[10] = uAnchorBizRe4;
       uAnchorBizRe53[11] = uAnchorBizRe5;
       uAnchorBizRe8 = uAnchorBizRe42;
       AnchorBizRelation.mBizRelationMap.put(uAnchorBizRe8, j.a(uAnchorBizRe53));
       uAnchorBizRe49 = new AnchorBizRelation[12];
       uAnchorBizRe49[0] = uAnchorBizRe;
       uAnchorBizRe49[1] = uAnchorBizRe1;
       uAnchorBizRe49[2] = uAnchorBizRe7;
       uAnchorBizRe49[3] = uAnchorBizRe9;
       uAnchorBizRe49[4] = uAnchorBizRe10;
       uAnchorBizRe49[5] = uAnchorBizRe20;
       uAnchorBizRe49[6] = uAnchorBizRe14;
       uAnchorBizRe49[7] = uAnchorBizRe28;
       uAnchorBizRe49[8] = uAnchorBizRe41;
       uAnchorBizRe49[9] = uAnchorBizRe3;
       uAnchorBizRe49[10] = uAnchorBizRe4;
       uAnchorBizRe49[11] = uAnchorBizRe5;
       uAnchorBizRe12 = uAnchorBizRe43;
       AnchorBizRelation.mBizRelationMap.put(uAnchorBizRe12, j.a(uAnchorBizRe49));
       uAnchorBizRe39 = uAnchorBizRe6;
       AnchorBizRelation[] uAnchorBizRe54 = new AnchorBizRelation[11];
       uAnchorBizRe54[0] = uAnchorBizRe;
       uAnchorBizRe54[1] = uAnchorBizRe1;
       uAnchorBizRe54[2] = uAnchorBizRe7;
       uAnchorBizRe54[3] = uAnchorBizRe9;
       uAnchorBizRe54[4] = uAnchorBizRe10;
       uAnchorBizRe54[5] = uAnchorBizRe20;
       uAnchorBizRe54[6] = uAnchorBizRe14;
       uAnchorBizRe54[7] = uAnchorBizRe28;
       uAnchorBizRe54[8] = uAnchorBizRe8;
       uAnchorBizRe54[9] = uAnchorBizRe12;
       uAnchorBizRe54[10] = uAnchorBizRe2;
       AnchorBizRelation.mBizRelationMap.put(uAnchorBizRe41, j.a(uAnchorBizRe54));
       uAnchorBizRe47 = new AnchorBizRelation[12];
       uAnchorBizRe47[0] = uAnchorBizRe1;
       uAnchorBizRe47[1] = uAnchorBizRe2;
       uAnchorBizRe47[2] = uAnchorBizRe3;
       uAnchorBizRe47[3] = uAnchorBizRe4;
       uAnchorBizRe47[4] = uAnchorBizRe5;
       uAnchorBizRe47[5] = uAnchorBizRe39;
       uAnchorBizRe47[6] = uAnchorBizRe7;
       uAnchorBizRe47[7] = uAnchorBizRe9;
       uAnchorBizRe47[8] = uAnchorBizRe10;
       uAnchorBizRe47[9] = uAnchorBizRe19;
       uAnchorBizRe47[10] = uAnchorBizRe21;
       uAnchorBizRe47[11] = uAnchorBizRe40;
       AnchorBizRelation.mBizRelationMap.put(uAnchorBizRe34, j.a(uAnchorBizRe47));
    }
    public void AnchorBizRelation(String p0,int p1,int p2){
       super(p0, p1);
       this.mPriority = p2;
    }
    public static AnchorBizRelation valueOf(String p0){
       Object obj = PatchProxy.applyOneRefs(p0, null, AnchorBizRelation.class, "2");
       if (obj != PatchProxyResult.class) {
          return obj;
       }
       return Enum.valueOf(AnchorBizRelation.class, p0);
    }
    public static AnchorBizRelation[] values(){
       Object obj = PatchProxy.apply(null, null, AnchorBizRelation.class, "1");
       if (obj != PatchProxyResult.class) {
          return obj;
       }
       return AnchorBizRelation.$VALUES.clone();
    }
    public int getPositionInStatusBits(){
       Object obj = PatchProxy.apply(null, this, AnchorBizRelation.class, "3");
       if (obj != PatchProxyResult.class) {
          return obj.intValue();
       }
       return this.ordinal();
    }
    public int getPriority(){
       return this.mPriority;
    }
    public long getRelationBits(){
       List obj = PatchProxy.apply(null, this, AnchorBizRelation.class, "4");
       if (obj != PatchProxyResult.class) {
          return obj.longValue();
       }
       if (this.mRelationBits == null) {
          this.mRelationBits = Long.valueOf(0);
          obj = AnchorBizRelation.mBizRelationMap.get(this);
          if (!q.f(obj)) {
             for (int i = 0; i < obj.size(); i = i + 1) {
                long l = 1 << obj.get(i).ordinal();
                long l1 = this.mRelationBits.longValue() | l;
                this.mRelationBits = Long.valueOf(l1);
             }
          }
       }
       return this.mRelationBits.longValue();
    }
}
