package com.kwai.feature.api.live.base.service.bizrelation.AudienceBizRelation;
import aq5.a;
import java.lang.Enum;
import java.lang.String;
import java.util.HashMap;
import java.lang.Object;
import java.util.ArrayList;
import ekd.j;
import java.util.Map;
import java.lang.Class;
import com.kwai.robust.PatchProxy;
import com.kwai.robust.PatchProxyResult;
import java.lang.Number;
import java.lang.Long;
import java.util.List;
import java.util.Collection;
import ekd.q;

public final class AudienceBizRelation extends Enum implements a	// class@000f95
{
    public final int mPriority;
    public Long mRelationBits;
    public static final AudienceBizRelation[] $VALUES;
    public static final AudienceBizRelation ALIPAY_RECHARGE_ACTIVITY;
    public static final AudienceBizRelation ASK_QUESTION;
    public static final AudienceBizRelation AUCTION_BUBBLE;
    public static final AudienceBizRelation BOTTOM_BAR_SHOP;
    public static final AudienceBizRelation BOTTOM_BAR_TIP;
    public static final AudienceBizRelation BUSINESS_PROMOTION;
    public static final AudienceBizRelation CHAT;
    public static final AudienceBizRelation CHAT_APPLY;
    public static final AudienceBizRelation CHAT_APPLY_BOTTOM_BAR;
    public static final AudienceBizRelation CHAT_AUDIO_STATUS_VIEW;
    public static final AudienceBizRelation CHAT_CENTER_STATUS_VIEW;
    public static final AudienceBizRelation CHAT_NEW_STYLE_APPLY_ENTRANCE;
    public static final AudienceBizRelation CHAT_VIDEO_STATUS_VIEW;
    public static final AudienceBizRelation CHAT_VIDEO_VIEW;
    public static final AudienceBizRelation COMMENT_EDITOR;
    public static final AudienceBizRelation DISTRICT_RANK;
    public static final AudienceBizRelation FANS_GROUP;
    public static final AudienceBizRelation FOLLOW_USER_PHOTO_FEED_PENDANT;
    public static final AudienceBizRelation GAME_INTERACTIVE;
    public static final AudienceBizRelation GAME_INTERACTIVE_PK;
    public static final AudienceBizRelation GAME_INTERACTIVE_VOICE_GUEST;
    public static final AudienceBizRelation GIFT_BOX;
    public static final AudienceBizRelation GIFT_COMBO;
    public static final AudienceBizRelation GUEST_ACTIVITY;
    public static final AudienceBizRelation GZONE_COMPETITION_DIVERSION;
    public static final AudienceBizRelation LIVE_GIFT_RAMPAGE;
    public static final AudienceBizRelation LIVE_LINE;
    public static final AudienceBizRelation LIVE_MULTI_LINE;
    public static final AudienceBizRelation LIVE_MULTI_PK;
    public static final AudienceBizRelation LIVE_SCREEN_RECORD;
    public static final AudienceBizRelation LOCAL_LIFE_BUBBLE_PENDANT;
    public static final AudienceBizRelation MERCHANT_FAST_PAY_BUBBLE;
    public static final AudienceBizRelation MERCHANT_LIVE;
    public static final AudienceBizRelation MERCHANT_NEW_PENDANT;
    public static final AudienceBizRelation MERCHANT_POPULAR_COMMODITY;
    public static final AudienceBizRelation NATURE_LOOK;
    public static final AudienceBizRelation PAID_SHOW_BOTTOM_BAR_ICON;
    public static final AudienceBizRelation PK;
    public static final AudienceBizRelation PK_GIFT_MOMENT;
    public static final AudienceBizRelation PK_SMALL_WINDOW;
    public static final AudienceBizRelation RECHARGE_ACTIVITY;
    public static final AudienceBizRelation RECRUIT_EXPLAIN_PANEL;
    public static final AudienceBizRelation RED_PACKET_CONTAINER;
    public static final AudienceBizRelation RED_PACK_RAIN_ING;
    public static final AudienceBizRelation SHOP_LIVE;
    public static final AudienceBizRelation SPECIAL_ROLE;
    public static final AudienceBizRelation TOP_DIVERT_PUSH;
    public static final AudienceBizRelation VIEW_PAGER_PENDANT;
    public static final AudienceBizRelation VOICE_COMMENT;
    public static final AudienceBizRelation VOICE_PARTY;
    public static final AudienceBizRelation VOICE_PARTY_AUDIO;
    public static final AudienceBizRelation VOICE_PARTY_CROSS_ROOM_PK;
    public static final AudienceBizRelation VOICE_PARTY_GRID_CHAT;
    public static final AudienceBizRelation VOICE_PARTY_GUEST;
    public static final AudienceBizRelation VOICE_PARTY_KTV;
    public static final AudienceBizRelation VOICE_PARTY_TEAM_PK;
    public static final AudienceBizRelation VOICE_PARTY_THEATER;
    public static final AudienceBizRelation VOICE_PARTY_THEATER_LANDSCAPE_FULL_SCREEN;
    public static final AudienceBizRelation VOICE_PARTY_THEATER_PORTRAIT_FULL_SCREEN;
    public static final AudienceBizRelation VOICE_PARTY_VIDEO;
    public static final AudienceBizRelation VOICE_TO_TEXT;
    public static final AudienceBizRelation WISH_LIST;
    public static final Map mBizRelationMap;

    static {
       AudienceBizRelation uAudienceBiz = new AudienceBizRelation("VOICE_PARTY", 0, 999);
       AudienceBizRelation.VOICE_PARTY = uAudienceBiz;
       AudienceBizRelation uAudienceBiz1 = new AudienceBizRelation("CHAT", 1, 500);
       AudienceBizRelation.CHAT = uAudienceBiz1;
       AudienceBizRelation uAudienceBiz2 = new AudienceBizRelation("VOICE_COMMENT", 2, 200);
       AudienceBizRelation.VOICE_COMMENT = uAudienceBiz2;
       AudienceBizRelation uAudienceBiz3 = new AudienceBizRelation("VOICE_TO_TEXT", 3, 200);
       AudienceBizRelation.VOICE_TO_TEXT = uAudienceBiz3;
       AudienceBizRelation uAudienceBiz4 = new AudienceBizRelation("GIFT_COMBO", 4, 200);
       AudienceBizRelation.GIFT_COMBO = uAudienceBiz4;
       AudienceBizRelation uAudienceBiz5 = new AudienceBizRelation("VOICE_PARTY_GUEST", 5, 200);
       AudienceBizRelation.VOICE_PARTY_GUEST = uAudienceBiz5;
       AudienceBizRelation uAudienceBiz6 = new AudienceBizRelation("NATURE_LOOK", 6, 200);
       AudienceBizRelation.NATURE_LOOK = uAudienceBiz6;
       AudienceBizRelation uAudienceBiz7 = new AudienceBizRelation("CHAT_AUDIO_STATUS_VIEW", 7, 500);
       AudienceBizRelation.CHAT_AUDIO_STATUS_VIEW = uAudienceBiz7;
       AudienceBizRelation uAudienceBiz8 = new AudienceBizRelation("CHAT_VIDEO_STATUS_VIEW", 8, 500);
       AudienceBizRelation.CHAT_VIDEO_STATUS_VIEW = uAudienceBiz8;
       AudienceBizRelation uAudienceBiz9 = new AudienceBizRelation("CHAT_VIDEO_VIEW", 9, 500);
       AudienceBizRelation.CHAT_VIDEO_VIEW = uAudienceBiz9;
       AudienceBizRelation uAudienceBiz10 = new AudienceBizRelation("CHAT_CENTER_STATUS_VIEW", 10, 500);
       AudienceBizRelation.CHAT_CENTER_STATUS_VIEW = uAudienceBiz10;
       AudienceBizRelation uAudienceBiz11 = new AudienceBizRelation("CHAT_NEW_STYLE_APPLY_ENTRANCE", 11, 500);
       AudienceBizRelation.CHAT_NEW_STYLE_APPLY_ENTRANCE = uAudienceBiz11;
       AudienceBizRelation uAudienceBiz12 = new AudienceBizRelation("PK", 12, 500);
       AudienceBizRelation.PK = uAudienceBiz12;
       AudienceBizRelation uAudienceBiz13 = uAudienceBiz12;
       AudienceBizRelation uAudienceBiz14 = new AudienceBizRelation("PK_SMALL_WINDOW", 13, 500);
       AudienceBizRelation.PK_SMALL_WINDOW = uAudienceBiz14;
       AudienceBizRelation uAudienceBiz15 = uAudienceBiz14;
       AudienceBizRelation uAudienceBiz16 = new AudienceBizRelation("LIVE_LINE", 14, 500);
       AudienceBizRelation.LIVE_LINE = uAudienceBiz16;
       AudienceBizRelation uAudienceBiz17 = uAudienceBiz16;
       uAudienceBiz12 = new AudienceBizRelation("LIVE_MULTI_LINE", 15, 500);
       AudienceBizRelation.LIVE_MULTI_LINE = uAudienceBiz12;
       AudienceBizRelation uAudienceBiz18 = uAudienceBiz12;
       uAudienceBiz14 = new AudienceBizRelation("LIVE_MULTI_PK", 16, 500);
       AudienceBizRelation.LIVE_MULTI_PK = uAudienceBiz14;
       AudienceBizRelation uAudienceBiz19 = uAudienceBiz14;
       uAudienceBiz16 = new AudienceBizRelation("VOICE_PARTY_KTV", 17, 999);
       AudienceBizRelation.VOICE_PARTY_KTV = uAudienceBiz16;
       AudienceBizRelation uAudienceBiz20 = uAudienceBiz16;
       uAudienceBiz12 = new AudienceBizRelation("WISH_LIST", 18, 200);
       AudienceBizRelation.WISH_LIST = uAudienceBiz12;
       AudienceBizRelation uAudienceBiz21 = uAudienceBiz12;
       AudienceBizRelation uAudienceBiz22 = new AudienceBizRelation("VIEW_PAGER_PENDANT", 19, 200);
       AudienceBizRelation.VIEW_PAGER_PENDANT = uAudienceBiz22;
       AudienceBizRelation uAudienceBiz23 = uAudienceBiz22;
       uAudienceBiz12 = new AudienceBizRelation("BOTTOM_BAR_TIP", 20, 0);
       AudienceBizRelation.BOTTOM_BAR_TIP = uAudienceBiz12;
       AudienceBizRelation uAudienceBiz24 = uAudienceBiz12;
       uAudienceBiz16 = new AudienceBizRelation("BOTTOM_BAR_SHOP", 21, 0);
       AudienceBizRelation.BOTTOM_BAR_SHOP = uAudienceBiz16;
       AudienceBizRelation uAudienceBiz25 = uAudienceBiz16;
       uAudienceBiz12 = new AudienceBizRelation("FOLLOW_USER_PHOTO_FEED_PENDANT", 22, 0);
       AudienceBizRelation.FOLLOW_USER_PHOTO_FEED_PENDANT = uAudienceBiz12;
       AudienceBizRelation uAudienceBiz26 = uAudienceBiz12;
       uAudienceBiz16 = new AudienceBizRelation("CHAT_APPLY", 23, 500);
       AudienceBizRelation.CHAT_APPLY = uAudienceBiz16;
       AudienceBizRelation uAudienceBiz27 = uAudienceBiz16;
       uAudienceBiz22 = new AudienceBizRelation("CHAT_APPLY_BOTTOM_BAR", 24, 500);
       AudienceBizRelation.CHAT_APPLY_BOTTOM_BAR = uAudienceBiz22;
       AudienceBizRelation uAudienceBiz28 = uAudienceBiz22;
       uAudienceBiz16 = new AudienceBizRelation("ASK_QUESTION", 25, 500);
       AudienceBizRelation.ASK_QUESTION = uAudienceBiz16;
       AudienceBizRelation uAudienceBiz29 = uAudienceBiz16;
       uAudienceBiz22 = new AudienceBizRelation("COMMENT_EDITOR", 26, 500);
       AudienceBizRelation.COMMENT_EDITOR = uAudienceBiz22;
       AudienceBizRelation uAudienceBiz30 = uAudienceBiz22;
       uAudienceBiz16 = new AudienceBizRelation("FANS_GROUP", 27, 500);
       AudienceBizRelation.FANS_GROUP = uAudienceBiz16;
       AudienceBizRelation uAudienceBiz31 = uAudienceBiz16;
       uAudienceBiz12 = new AudienceBizRelation("DISTRICT_RANK", 28, 0);
       AudienceBizRelation.DISTRICT_RANK = uAudienceBiz12;
       AudienceBizRelation uAudienceBiz32 = uAudienceBiz12;
       uAudienceBiz22 = new AudienceBizRelation("PK_GIFT_MOMENT", 29, 0);
       AudienceBizRelation.PK_GIFT_MOMENT = uAudienceBiz22;
       AudienceBizRelation uAudienceBiz33 = uAudienceBiz22;
       uAudienceBiz12 = new AudienceBizRelation("RED_PACK_RAIN_ING", 30, 999);
       AudienceBizRelation.RED_PACK_RAIN_ING = uAudienceBiz12;
       AudienceBizRelation uAudienceBiz34 = uAudienceBiz12;
       uAudienceBiz16 = new AudienceBizRelation("VOICE_PARTY_THEATER_PORTRAIT_FULL_SCREEN", 31, 10);
       AudienceBizRelation.VOICE_PARTY_THEATER_PORTRAIT_FULL_SCREEN = uAudienceBiz16;
       AudienceBizRelation uAudienceBiz35 = uAudienceBiz16;
       uAudienceBiz22 = new AudienceBizRelation("VOICE_PARTY_THEATER_LANDSCAPE_FULL_SCREEN", 32, 10);
       AudienceBizRelation.VOICE_PARTY_THEATER_LANDSCAPE_FULL_SCREEN = uAudienceBiz22;
       AudienceBizRelation uAudienceBiz36 = uAudienceBiz22;
       uAudienceBiz12 = new AudienceBizRelation("VOICE_PARTY_THEATER", 33, 50);
       AudienceBizRelation.VOICE_PARTY_THEATER = uAudienceBiz12;
       AudienceBizRelation uAudienceBiz37 = uAudienceBiz12;
       uAudienceBiz16 = new AudienceBizRelation("VOICE_PARTY_VIDEO", 34, 50);
       AudienceBizRelation.VOICE_PARTY_VIDEO = uAudienceBiz16;
       AudienceBizRelation uAudienceBiz38 = uAudienceBiz16;
       uAudienceBiz12 = new AudienceBizRelation("VOICE_PARTY_AUDIO", 35, 50);
       AudienceBizRelation.VOICE_PARTY_AUDIO = uAudienceBiz12;
       AudienceBizRelation uAudienceBiz39 = uAudienceBiz12;
       uAudienceBiz16 = new AudienceBizRelation("VOICE_PARTY_GRID_CHAT", 36, 50);
       AudienceBizRelation.VOICE_PARTY_GRID_CHAT = uAudienceBiz16;
       AudienceBizRelation uAudienceBiz40 = uAudienceBiz16;
       uAudienceBiz12 = new AudienceBizRelation("VOICE_PARTY_TEAM_PK", 37, 50);
       AudienceBizRelation.VOICE_PARTY_TEAM_PK = uAudienceBiz12;
       AudienceBizRelation uAudienceBiz41 = uAudienceBiz12;
       uAudienceBiz16 = new AudienceBizRelation("VOICE_PARTY_CROSS_ROOM_PK", 38, 50);
       AudienceBizRelation.VOICE_PARTY_CROSS_ROOM_PK = uAudienceBiz16;
       AudienceBizRelation uAudienceBiz42 = uAudienceBiz16;
       uAudienceBiz12 = new AudienceBizRelation("RED_PACKET_CONTAINER", 39, 0);
       AudienceBizRelation.RED_PACKET_CONTAINER = uAudienceBiz12;
       AudienceBizRelation uAudienceBiz43 = uAudienceBiz12;
       uAudienceBiz16 = new AudienceBizRelation("GIFT_BOX", 40, 2);
       AudienceBizRelation.GIFT_BOX = uAudienceBiz16;
       AudienceBizRelation uAudienceBiz44 = uAudienceBiz16;
       uAudienceBiz12 = new AudienceBizRelation("RECHARGE_ACTIVITY", 41, 1);
       AudienceBizRelation.RECHARGE_ACTIVITY = uAudienceBiz12;
       AudienceBizRelation uAudienceBiz45 = uAudienceBiz12;
       uAudienceBiz22 = new AudienceBizRelation("ALIPAY_RECHARGE_ACTIVITY", 42, 1);
       AudienceBizRelation.ALIPAY_RECHARGE_ACTIVITY = uAudienceBiz22;
       AudienceBizRelation uAudienceBiz46 = uAudienceBiz22;
       uAudienceBiz12 = new AudienceBizRelation("BUSINESS_PROMOTION", 43, 500);
       AudienceBizRelation.BUSINESS_PROMOTION = uAudienceBiz12;
       AudienceBizRelation uAudienceBiz47 = uAudienceBiz12;
       uAudienceBiz16 = new AudienceBizRelation("PAID_SHOW_BOTTOM_BAR_ICON", 44, 999);
       AudienceBizRelation.PAID_SHOW_BOTTOM_BAR_ICON = uAudienceBiz16;
       AudienceBizRelation uAudienceBiz48 = uAudienceBiz16;
       uAudienceBiz22 = new AudienceBizRelation("GUEST_ACTIVITY", 45, 999);
       AudienceBizRelation.GUEST_ACTIVITY = uAudienceBiz22;
       AudienceBizRelation uAudienceBiz49 = uAudienceBiz22;
       uAudienceBiz12 = new AudienceBizRelation("LIVE_SCREEN_RECORD", 46, 0);
       AudienceBizRelation.LIVE_SCREEN_RECORD = uAudienceBiz12;
       AudienceBizRelation uAudienceBiz50 = uAudienceBiz12;
       uAudienceBiz16 = new AudienceBizRelation("GZONE_COMPETITION_DIVERSION", 47, 200);
       AudienceBizRelation.GZONE_COMPETITION_DIVERSION = uAudienceBiz16;
       AudienceBizRelation uAudienceBiz51 = uAudienceBiz16;
       uAudienceBiz22 = new AudienceBizRelation("LIVE_GIFT_RAMPAGE", 48, 200);
       AudienceBizRelation.LIVE_GIFT_RAMPAGE = uAudienceBiz22;
       AudienceBizRelation uAudienceBiz52 = uAudienceBiz22;
       uAudienceBiz12 = new AudienceBizRelation("AUCTION_BUBBLE", 49, 999);
       AudienceBizRelation.AUCTION_BUBBLE = uAudienceBiz12;
       AudienceBizRelation uAudienceBiz53 = uAudienceBiz12;
       uAudienceBiz16 = new AudienceBizRelation("MERCHANT_POPULAR_COMMODITY", 50, 999);
       AudienceBizRelation.MERCHANT_POPULAR_COMMODITY = uAudienceBiz16;
       AudienceBizRelation uAudienceBiz54 = uAudienceBiz16;
       uAudienceBiz12 = new AudienceBizRelation("SPECIAL_ROLE", 51, 999);
       AudienceBizRelation.SPECIAL_ROLE = uAudienceBiz12;
       AudienceBizRelation uAudienceBiz55 = uAudienceBiz12;
       uAudienceBiz16 = new AudienceBizRelation("GAME_INTERACTIVE", 52, 999);
       AudienceBizRelation.GAME_INTERACTIVE = uAudienceBiz16;
       AudienceBizRelation uAudienceBiz56 = uAudienceBiz16;
       uAudienceBiz12 = new AudienceBizRelation("GAME_INTERACTIVE_VOICE_GUEST", 53, 999);
       AudienceBizRelation.GAME_INTERACTIVE_VOICE_GUEST = uAudienceBiz12;
       AudienceBizRelation uAudienceBiz57 = uAudienceBiz12;
       uAudienceBiz16 = new AudienceBizRelation("GAME_INTERACTIVE_PK", 54, 999);
       AudienceBizRelation.GAME_INTERACTIVE_PK = uAudienceBiz16;
       AudienceBizRelation uAudienceBiz58 = uAudienceBiz16;
       uAudienceBiz12 = new AudienceBizRelation("TOP_DIVERT_PUSH", 55, 0);
       AudienceBizRelation.TOP_DIVERT_PUSH = uAudienceBiz12;
       AudienceBizRelation uAudienceBiz59 = uAudienceBiz12;
       uAudienceBiz16 = new AudienceBizRelation("MERCHANT_NEW_PENDANT", 56, 999);
       AudienceBizRelation.MERCHANT_NEW_PENDANT = uAudienceBiz16;
       AudienceBizRelation uAudienceBiz60 = uAudienceBiz16;
       uAudienceBiz22 = new AudienceBizRelation("RECRUIT_EXPLAIN_PANEL", 57, 999);
       AudienceBizRelation.RECRUIT_EXPLAIN_PANEL = uAudienceBiz22;
       AudienceBizRelation uAudienceBiz61 = uAudienceBiz22;
       uAudienceBiz16 = new AudienceBizRelation("MERCHANT_FAST_PAY_BUBBLE", 58, 999);
       AudienceBizRelation.MERCHANT_FAST_PAY_BUBBLE = uAudienceBiz16;
       AudienceBizRelation uAudienceBiz62 = uAudienceBiz16;
       uAudienceBiz12 = new AudienceBizRelation("LOCAL_LIFE_BUBBLE_PENDANT", 59, 0);
       AudienceBizRelation.LOCAL_LIFE_BUBBLE_PENDANT = uAudienceBiz12;
       AudienceBizRelation uAudienceBiz63 = uAudienceBiz12;
       uAudienceBiz22 = new AudienceBizRelation("SHOP_LIVE", 60, 0);
       AudienceBizRelation.SHOP_LIVE = uAudienceBiz22;
       AudienceBizRelation uAudienceBiz64 = uAudienceBiz22;
       uAudienceBiz12 = new AudienceBizRelation("MERCHANT_LIVE", 61, 0);
       AudienceBizRelation.MERCHANT_LIVE = uAudienceBiz12;
       AudienceBizRelation[] uAudienceBiz65 = new AudienceBizRelation[62];
       uAudienceBiz65[0] = uAudienceBiz;
       uAudienceBiz65[1] = uAudienceBiz1;
       uAudienceBiz65[2] = uAudienceBiz2;
       uAudienceBiz65[3] = uAudienceBiz3;
       uAudienceBiz65[4] = uAudienceBiz4;
       uAudienceBiz65[5] = uAudienceBiz5;
       uAudienceBiz65[6] = uAudienceBiz6;
       uAudienceBiz65[7] = uAudienceBiz7;
       uAudienceBiz65[8] = uAudienceBiz8;
       uAudienceBiz65[9] = uAudienceBiz9;
       uAudienceBiz65[10] = uAudienceBiz10;
       uAudienceBiz65[11] = uAudienceBiz11;
       uAudienceBiz65[12] = uAudienceBiz13;
       uAudienceBiz65[13] = uAudienceBiz15;
       uAudienceBiz65[14] = uAudienceBiz17;
       uAudienceBiz65[15] = uAudienceBiz18;
       uAudienceBiz65[16] = uAudienceBiz19;
       uAudienceBiz65[17] = uAudienceBiz20;
       uAudienceBiz65[18] = uAudienceBiz21;
       uAudienceBiz65[19] = uAudienceBiz23;
       uAudienceBiz65[20] = uAudienceBiz24;
       uAudienceBiz65[21] = uAudienceBiz25;
       uAudienceBiz65[22] = uAudienceBiz26;
       uAudienceBiz65[23] = uAudienceBiz27;
       uAudienceBiz65[24] = uAudienceBiz28;
       uAudienceBiz65[25] = uAudienceBiz29;
       uAudienceBiz65[26] = uAudienceBiz30;
       uAudienceBiz65[27] = uAudienceBiz31;
       uAudienceBiz65[28] = uAudienceBiz32;
       uAudienceBiz65[29] = uAudienceBiz33;
       uAudienceBiz65[30] = uAudienceBiz34;
       uAudienceBiz65[31] = uAudienceBiz35;
       uAudienceBiz65[32] = uAudienceBiz36;
       uAudienceBiz65[33] = uAudienceBiz37;
       uAudienceBiz65[34] = uAudienceBiz38;
       uAudienceBiz65[35] = uAudienceBiz39;
       uAudienceBiz65[36] = uAudienceBiz40;
       uAudienceBiz65[37] = uAudienceBiz41;
       uAudienceBiz65[38] = uAudienceBiz42;
       uAudienceBiz65[39] = uAudienceBiz43;
       uAudienceBiz65[40] = uAudienceBiz44;
       uAudienceBiz65[41] = uAudienceBiz45;
       uAudienceBiz65[42] = uAudienceBiz46;
       uAudienceBiz65[43] = uAudienceBiz47;
       uAudienceBiz65[44] = uAudienceBiz48;
       uAudienceBiz65[45] = uAudienceBiz49;
       uAudienceBiz65[46] = uAudienceBiz50;
       uAudienceBiz65[47] = uAudienceBiz51;
       uAudienceBiz65[48] = uAudienceBiz52;
       uAudienceBiz65[49] = uAudienceBiz53;
       uAudienceBiz65[50] = uAudienceBiz54;
       uAudienceBiz65[51] = uAudienceBiz55;
       uAudienceBiz65[52] = uAudienceBiz56;
       uAudienceBiz65[53] = uAudienceBiz57;
       uAudienceBiz65[54] = uAudienceBiz58;
       uAudienceBiz65[55] = uAudienceBiz59;
       uAudienceBiz65[56] = uAudienceBiz60;
       uAudienceBiz65[57] = uAudienceBiz61;
       uAudienceBiz65[58] = uAudienceBiz62;
       uAudienceBiz65[59] = uAudienceBiz63;
       uAudienceBiz65[60] = uAudienceBiz64;
       uAudienceBiz65[61] = uAudienceBiz12;
       AudienceBizRelation.$VALUES = uAudienceBiz65;
       HashMap hashMap = new HashMap();
       AudienceBizRelation.mBizRelationMap = hashMap;
       AudienceBizRelation[] uAudienceBiz66 = new AudienceBizRelation[12];
       uAudienceBiz66[0] = uAudienceBiz1;
       uAudienceBiz66[1] = uAudienceBiz6;
       uAudienceBiz66[2] = uAudienceBiz8;
       uAudienceBiz66[3] = uAudienceBiz7;
       uAudienceBiz66[4] = uAudienceBiz13;
       uAudienceBiz66[5] = uAudienceBiz17;
       uAudienceBiz66[6] = uAudienceBiz18;
       uAudienceBiz66[7] = uAudienceBiz19;
       uAudienceBiz66[8] = uAudienceBiz23;
       uAudienceBiz66[9] = uAudienceBiz27;
       uAudienceBiz66[10] = uAudienceBiz28;
       uAudienceBiz66[11] = uAudienceBiz61;
       hashMap.put(uAudienceBiz, j.a(uAudienceBiz66));
       uAudienceBiz66 = new AudienceBizRelation[]{uAudienceBiz,uAudienceBiz13,uAudienceBiz17,uAudienceBiz20};
       hashMap.put(uAudienceBiz1, j.a(uAudienceBiz66));
       AudienceBizRelation[] uAudienceBiz67 = new AudienceBizRelation[]{uAudienceBiz8,uAudienceBiz7,uAudienceBiz13,uAudienceBiz17,uAudienceBiz18,uAudienceBiz19,uAudienceBiz61};
       hashMap.put(uAudienceBiz5, j.a(uAudienceBiz67));
       AudienceBizRelation[] uAudienceBiz68 = new AudienceBizRelation[]{uAudienceBiz,uAudienceBiz20};
       hashMap.put(uAudienceBiz6, j.a(uAudienceBiz68));
       uAudienceBiz68 = new AudienceBizRelation[]{uAudienceBiz,uAudienceBiz5,uAudienceBiz13,uAudienceBiz17};
       hashMap.put(uAudienceBiz7, j.a(uAudienceBiz68));
       uAudienceBiz67 = new AudienceBizRelation[]{uAudienceBiz,uAudienceBiz5,uAudienceBiz13,uAudienceBiz17,uAudienceBiz61};
       hashMap.put(uAudienceBiz8, j.a(uAudienceBiz67));
       uAudienceBiz68 = new AudienceBizRelation[]{uAudienceBiz13,uAudienceBiz19,uAudienceBiz17,uAudienceBiz,uAudienceBiz5,uAudienceBiz8};
       uAudienceBiz4 = uAudienceBiz61;
       hashMap.put(uAudienceBiz4, j.a(uAudienceBiz68));
       uAudienceBiz66 = new AudienceBizRelation[]{uAudienceBiz17,uAudienceBiz,uAudienceBiz1,uAudienceBiz5,uAudienceBiz8,uAudienceBiz7,uAudienceBiz4};
       uAudienceBiz14 = uAudienceBiz13;
       hashMap.put(uAudienceBiz14, j.a(uAudienceBiz66));
       AudienceBizRelation[] uAudienceBiz69 = new AudienceBizRelation[9];
       uAudienceBiz69[0] = uAudienceBiz14;
       uAudienceBiz69[1] = uAudienceBiz;
       uAudienceBiz69[2] = uAudienceBiz1;
       uAudienceBiz69[3] = uAudienceBiz5;
       uAudienceBiz69[4] = uAudienceBiz8;
       uAudienceBiz69[5] = uAudienceBiz7;
       uAudienceBiz69[6] = uAudienceBiz18;
       uAudienceBiz69[7] = uAudienceBiz19;
       uAudienceBiz69[8] = uAudienceBiz4;
       uAudienceBiz3 = uAudienceBiz17;
       hashMap.put(uAudienceBiz3, j.a(uAudienceBiz69));
       uAudienceBiz65 = new AudienceBizRelation[]{uAudienceBiz,uAudienceBiz5,uAudienceBiz3};
       uAudienceBiz16 = uAudienceBiz18;
       hashMap.put(uAudienceBiz16, j.a(uAudienceBiz65));
       uAudienceBiz51 = uAudienceBiz10;
       AudienceBizRelation[] uAudienceBiz70 = new AudienceBizRelation[]{uAudienceBiz,uAudienceBiz5,uAudienceBiz3,uAudienceBiz16,uAudienceBiz4};
       uAudienceBiz4 = uAudienceBiz19;
       hashMap.put(uAudienceBiz4, j.a(uAudienceBiz70));
       uAudienceBiz70 = new AudienceBizRelation[]{uAudienceBiz1,uAudienceBiz6,uAudienceBiz23,uAudienceBiz27,uAudienceBiz28};
       uAudienceBiz11 = uAudienceBiz20;
       hashMap.put(uAudienceBiz11, j.a(uAudienceBiz70));
       uAudienceBiz70 = new AudienceBizRelation[]{uAudienceBiz,uAudienceBiz11};
       hashMap.put(uAudienceBiz23, j.a(uAudienceBiz70));
       uAudienceBiz53 = uAudienceBiz9;
       AudienceBizRelation[] uAudienceBiz71 = new AudienceBizRelation[]{uAudienceBiz,uAudienceBiz11,uAudienceBiz14,uAudienceBiz3,uAudienceBiz16,uAudienceBiz4,uAudienceBiz29};
       uAudienceBiz22 = uAudienceBiz27;
       hashMap.put(uAudienceBiz22, j.a(uAudienceBiz71));
       uAudienceBiz71 = new AudienceBizRelation[]{uAudienceBiz,uAudienceBiz11,uAudienceBiz14,uAudienceBiz3,uAudienceBiz16,uAudienceBiz4,uAudienceBiz55};
       uAudienceBiz5 = uAudienceBiz28;
       hashMap.put(uAudienceBiz5, j.a(uAudienceBiz71));
       uAudienceBiz71 = new AudienceBizRelation[]{uAudienceBiz,uAudienceBiz11,uAudienceBiz22};
       hashMap.put(uAudienceBiz29, j.a(uAudienceBiz71));
       uAudienceBiz69 = new AudienceBizRelation[]{uAudienceBiz31};
       uAudienceBiz9 = uAudienceBiz30;
       hashMap.put(uAudienceBiz9, j.a(uAudienceBiz69));
       uAudienceBiz69 = new AudienceBizRelation[]{uAudienceBiz9};
       hashMap.put(uAudienceBiz31, j.a(uAudienceBiz69));
       uAudienceBiz71 = new AudienceBizRelation[]{uAudienceBiz35,uAudienceBiz36};
       hashMap.put(uAudienceBiz43, j.a(uAudienceBiz71));
       uAudienceBiz69 = new AudienceBizRelation[]{uAudienceBiz48};
       hashMap.put(uAudienceBiz47, j.a(uAudienceBiz69));
       uAudienceBiz69 = new AudienceBizRelation[]{uAudienceBiz5};
       hashMap.put(uAudienceBiz55, j.a(uAudienceBiz69));
       uAudienceBiz69 = new AudienceBizRelation[]{uAudienceBiz56};
       hashMap.put(uAudienceBiz2, j.a(uAudienceBiz69));
       AudienceBizRelation[] uAudienceBiz72 = new AudienceBizRelation[11];
       uAudienceBiz72[0] = uAudienceBiz1;
       uAudienceBiz72[1] = uAudienceBiz6;
       uAudienceBiz72[2] = uAudienceBiz8;
       uAudienceBiz72[3] = uAudienceBiz7;
       uAudienceBiz72[4] = uAudienceBiz14;
       uAudienceBiz72[5] = uAudienceBiz3;
       uAudienceBiz72[6] = uAudienceBiz16;
       uAudienceBiz72[7] = uAudienceBiz4;
       uAudienceBiz72[8] = uAudienceBiz23;
       uAudienceBiz72[9] = uAudienceBiz22;
       uAudienceBiz72[10] = uAudienceBiz5;
       hashMap.put(uAudienceBiz39, j.a(uAudienceBiz72));
       AudienceBizRelation[] uAudienceBiz73 = new AudienceBizRelation[]{uAudienceBiz1,uAudienceBiz7,uAudienceBiz8,uAudienceBiz53,uAudienceBiz51,uAudienceBiz40};
       hashMap.put(uAudienceBiz63, j.a(uAudienceBiz73));
    }
    public void AudienceBizRelation(String p0,int p1,int p2){
       super(p0, p1);
       this.mPriority = p2;
    }
    public static AudienceBizRelation valueOf(String p0){
       Object obj = PatchProxy.applyOneRefs(p0, null, AudienceBizRelation.class, "2");
       if (obj != PatchProxyResult.class) {
          return obj;
       }
       return Enum.valueOf(AudienceBizRelation.class, p0);
    }
    public static AudienceBizRelation[] values(){
       Object obj = PatchProxy.apply(null, null, AudienceBizRelation.class, "1");
       if (obj != PatchProxyResult.class) {
          return obj;
       }
       return AudienceBizRelation.$VALUES.clone();
    }
    public int getPositionInStatusBits(){
       Object obj = PatchProxy.apply(null, this, AudienceBizRelation.class, "3");
       if (obj != PatchProxyResult.class) {
          return obj.intValue();
       }
       return this.ordinal();
    }
    public int getPriority(){
       return this.mPriority;
    }
    public long getRelationBits(){
       List obj = PatchProxy.apply(null, this, AudienceBizRelation.class, "4");
       if (obj != PatchProxyResult.class) {
          return obj.longValue();
       }
       if (this.mRelationBits == null) {
          this.mRelationBits = Long.valueOf(0);
          obj = AudienceBizRelation.mBizRelationMap.get(this);
          if (!q.f(obj)) {
             for (int i = 0; i < obj.size(); i = i + 1) {
                long l = 1 << obj.get(i).ordinal();
                long l1 = this.mRelationBits.longValue() | l;
                this.mRelationBits = Long.valueOf(l1);
             }
          }
       }
       return this.mRelationBits.longValue();
    }
}
