package boc.e;
import com.yxcorp.gifshow.util.resource.MagicModel;
import java.lang.String;

public final class e	// class@000440
{
    public static final MagicModel A;
    public static final MagicModel B;
    public static final MagicModel C;
    public static final MagicModel D;
    public static final MagicModel E;
    public static final MagicModel F;
    public static final MagicModel G;
    public static final MagicModel H;
    public static final MagicModel I;
    public static final MagicModel J;
    public static final MagicModel K;
    public static final MagicModel L;
    public static final MagicModel M;
    public static final MagicModel a;
    public static final MagicModel b;
    public static final MagicModel c;
    public static final MagicModel d;
    public static final MagicModel e;
    public static final MagicModel f;
    public static final MagicModel g;
    public static final MagicModel h;
    public static final MagicModel i;
    public static final MagicModel j;
    public static final MagicModel k;
    public static final MagicModel l;
    public static final MagicModel m;
    public static final MagicModel n;
    public static final MagicModel o;
    public static final MagicModel p;
    public static final MagicModel q;
    public static final MagicModel r;
    public static final MagicModel s;
    public static final MagicModel t;
    public static final MagicModel u;
    public static final MagicModel v;
    public static final MagicModel w;
    public static final MagicModel x;
    public static final MagicModel y;
    public static final MagicModel z;

    static {
       e.a = new MagicModel("magic_ycnn_face_3d_resource").addToMagicModelsResourceList();
       e.b = new MagicModel("magic_mmu_model_animoji1").addToMagicModelsResourceList();
       e.c = new MagicModel("magic_ycnn_model_landmark").addToMagicModelsResourceList();
       e.d = new MagicModel("magic_ycnn_model_animal_landmarks").addToMagicModelsResourceList();
       e.e = new MagicModel("magic_mmu_model_basewhite").addToMagicModelsResourceList();
       e.f = new MagicModel("magic_mmu_model_ear").addToMagicModelsResourceList();
       e.g = new MagicModel("magic_mmu_model_faceblend").addToMagicModelsResourceList();
       e.h = new MagicModel("magic_mmu_model_faceprop").addToMagicModelsResourceList();
       e.i = new MagicModel("magic_ycnn_model_cloth_seg").addToMagicModelsResourceList();
       e.j = new MagicModel("magic_ycnn_model_ar").addToMagicModelsResourceList();
       e.k = new MagicModel("magic_mmu_model_memoji").addToMagicModelsResourceList();
       e.l = new MagicModel("magic_ycnn_model_face_attributes").addToMagicModelsResourceList();
       e.m = new MagicModel("magic_ycnn_model_face_seg").addToMagicModelsResourceList();
       e.n = new MagicModel("magic_ycnn_model_hair_dir").addToMagicModelsResourceList();
       e.o = new MagicModel("magic_ycnn_model_human_keypoint").addToMagicModelsResourceList();
       e.p = new MagicModel("magic_ycnn_model_skin_seg").addToMagicModelsResourceList();
       e.q = new MagicModel("magic_ycnn_model_nail_seg").addToMagicModelsResourceList();
       e.r = new MagicModel("magic_ycnn_model_general_handpose").addToMagicModelsResourceList();
       e.s = new MagicModel("magic_ycnn_model_hair").addToMagicModelsResourceList();
       e.t = new MagicModel("magic_ycnn_model_hand_seg").addToMagicModelsResourceList();
       e.u = new MagicModel("magic_ycnn_model_head_seg").addToMagicModelsResourceList();
       e.v = new MagicModel("magic_ycnn_model_humanpose").addToMagicModelsResourceList();
       e.w = new MagicModel("magic_ycnn_model_matting").addToMagicModelsResourceList();
       e.x = new MagicModel("magic_ycnn_model_plane").addToMagicModelsResourceList();
       e.y = new MagicModel("magic_ycnn_model_sky").addToMagicModelsResourceList();
       e.z = new MagicModel("magic_ycnn_model_gesture").addToMagicModelsResourceList();
       e.A = new MagicModel("magic_ycnn_model_general_recog").addToMagicModelsResourceList();
       e.B = new MagicModel("magic_ycnn_beautify_assets").addToMagicModelsResourceList();
       e.C = new MagicModel("magic_ycnn_beauty_smart_assets").addToMagicModelsResourceList();
       e.D = new MagicModel("magic_ycnn_beautify_strategy").addToMagicModelsResourceList();
       e.E = new MagicModel("magic_ycnn_model_aibright").addToMagicModelsResourceList();
       e.F = new MagicModel("magic_ycnn_model_backlight").addToMagicModelsResourceList();
       e.G = new MagicModel("magic_ycnn_model_aideflaw").addToMagicModelsResourceList();
       e.H = new MagicModel("magic_ycnn_common_strategy").addToMagicModelsResourceList();
       e.I = new MagicModel("magic_ycnn_model_gan_gf").addToMagicModelsResourceList();
       e.J = new MagicModel("magic_ycnn_model_security_classifier").addToMagicModelsResourceList();
       e.K = new MagicModel("magic_ycnn_model_aieyelid").addToMagicModelsResourceList();
       e.L = new MagicModel("magic_ycnn_beautify_assets_manual").addToMagicModelsResourceList();
       e.M = new MagicModel("magic_ycnn_beautify_assets_live").addToMagicModelsResourceList();
    }
}
