package com.xiaomi.push.hm;
import java.lang.Enum;
import java.lang.String;
import java.lang.Class;
import java.lang.Object;

public final class hm extends Enum	// class@001115
{
    public final int a;
    public static final hm A;
    public static final hm B;
    public static final hm C;
    public static final hm D;
    public static final hm E;
    public static final hm F;
    public static final hm G;
    public static final hm H;
    public static final hm I;
    public static final hm J;
    public static final hm K;
    public static final hm L;
    public static final hm M;
    public static final hm N;
    public static final hm O;
    public static final hm P;
    public static final hm Q;
    public static final hm R;
    public static final hm S;
    public static final hm T;
    public static final hm U;
    public static final hm V;
    public static final hm W;
    public static final hm X;
    public static final hm Y;
    public static final hm Z;
    public static final hm a;
    public static final hm[] a;
    public static final hm aA;
    public static final hm aB;
    public static final hm aC;
    public static final hm aD;
    public static final hm aE;
    public static final hm aF;
    public static final hm aG;
    public static final hm aH;
    public static final hm aI;
    public static final hm aJ;
    public static final hm aK;
    public static final hm aL;
    public static final hm aM;
    public static final hm aN;
    public static final hm aO;
    public static final hm aP;
    public static final hm aQ;
    public static final hm aR;
    public static final hm aS;
    public static final hm aT;
    public static final hm aU;
    public static final hm aV;
    public static final hm aW;
    public static final hm aX;
    public static final hm aY;
    public static final hm aZ;
    public static final hm aa;
    public static final hm ab;
    public static final hm ac;
    public static final hm ad;
    public static final hm ae;
    public static final hm af;
    public static final hm ag;
    public static final hm ah;
    public static final hm ai;
    public static final hm aj;
    public static final hm ak;
    public static final hm al;
    public static final hm am;
    public static final hm an;
    public static final hm ao;
    public static final hm ap;
    public static final hm aq;
    public static final hm ar;
    public static final hm as;
    public static final hm at;
    public static final hm au;
    public static final hm av;
    public static final hm aw;
    public static final hm ax;
    public static final hm ay;
    public static final hm az;
    public static final hm b;
    public static final hm ba;
    public static final hm bb;
    public static final hm bc;
    public static final hm bd;
    public static final hm be;
    public static final hm bf;
    public static final hm bg;
    public static final hm bh;
    public static final hm bi;
    public static final hm bj;
    public static final hm bk;
    public static final hm bl;
    public static final hm bm;
    public static final hm bn;
    public static final hm bo;
    public static final hm bp;
    public static final hm bq;
    public static final hm br;
    public static final hm bs;
    public static final hm bt;
    public static final hm bu;
    public static final hm bv;
    public static final hm c;
    public static final hm d;
    public static final hm e;
    public static final hm f;
    public static final hm g;
    public static final hm h;
    public static final hm i;
    public static final hm j;
    public static final hm k;
    public static final hm l;
    public static final hm m;
    public static final hm n;
    public static final hm o;
    public static final hm p;
    public static final hm q;
    public static final hm r;
    public static final hm s;
    public static final hm t;
    public static final hm u;
    public static final hm v;
    public static final hm w;
    public static final hm x;
    public static final hm y;
    public static final hm z;

    static {
       hm ohm = new hm("UploadSwitch", 0, 1);
       hm.a = ohm;
       hm ohm1 = new hm("UploadFrequency", 1, 2);
       hm.b = ohm1;
       hm ohm2 = new hm("ScreenSizeCollectionSwitch", 2, 3);
       hm.c = ohm2;
       hm ohm3 = new hm("MacCollectionSwitch", 3, 4);
       hm.d = ohm3;
       hm ohm4 = new hm("IMSICollectionSwitch", 4, 5);
       hm.e = ohm4;
       hm ohm5 = new hm("AndroidVnCollectionSwitch", 5, 6);
       hm.f = ohm5;
       hm ohm6 = new hm("AndroidVcCollectionSwitch", 6, 7);
       hm.g = ohm6;
       hm ohm7 = new hm("AndroidIdCollectionSwitch", 7, 8);
       hm.h = ohm7;
       hm ohm8 = new hm("DeviceInfoCollectionFrequency", 8, 9);
       hm.i = ohm8;
       hm ohm9 = new hm("AppInstallListCollectionSwitch", 9, 10);
       hm.j = ohm9;
       hm ohm10 = new hm("AppInstallListCollectionFrequency", 10, 11);
       hm.k = ohm10;
       hm ohm11 = new hm("AppActiveListCollectionSwitch", 11, 12);
       hm.l = ohm11;
       hm ohm12 = new hm("AppActiveListCollectionFrequency", 12, 13);
       hm.m = ohm12;
       hm ohm13 = ohm12;
       hm ohm14 = new hm("BluetoothCollectionSwitch", 13, 14);
       hm.n = ohm14;
       hm ohm15 = ohm14;
       hm ohm16 = new hm("BluetoothCollectionFrequency", 14, 15);
       hm.o = ohm16;
       hm ohm17 = ohm16;
       hm ohm18 = new hm("LocationCollectionSwitch", 15, 16);
       hm.p = ohm18;
       hm ohm19 = ohm18;
       ohm12 = new hm("LocationCollectionFrequency", 16, 17);
       hm.q = ohm12;
       hm ohm20 = ohm12;
       ohm14 = new hm("AccountCollectionSwitch", 17, 18);
       hm.r = ohm14;
       hm ohm21 = ohm14;
       ohm16 = new hm("AccountCollectionFrequency", 18, 19);
       hm.s = ohm16;
       hm ohm22 = ohm16;
       ohm18 = new hm("WifiCollectionSwitch", 19, 20);
       hm.t = ohm18;
       hm ohm23 = ohm18;
       ohm12 = new hm("WifiCollectionFrequency", 20, 21);
       hm.u = ohm12;
       hm ohm24 = ohm12;
       ohm14 = new hm("CellularCollectionSwitch", 21, 22);
       hm.v = ohm14;
       hm ohm25 = ohm14;
       ohm16 = new hm("CellularCollectionFrequency", 22, 23);
       hm.w = ohm16;
       hm ohm26 = ohm16;
       ohm18 = new hm("TopAppCollectionSwitch", 23, 24);
       hm.x = ohm18;
       hm ohm27 = ohm18;
       ohm16 = new hm("TopAppCollectionFrequency", 24, 25);
       hm.y = ohm16;
       hm ohm28 = ohm16;
       ohm18 = new hm("DataCollectionSwitch", 25, 26);
       hm.z = ohm18;
       hm ohm29 = ohm18;
       ohm16 = new hm("OcVersionCheckFrequency", 26, 27);
       hm.A = ohm16;
       hm ohm30 = ohm16;
       ohm18 = new hm("SyncInfoFrequency", 27, 28);
       hm.B = ohm18;
       hm ohm31 = ohm18;
       ohm16 = new hm("UploadNotificationInfoFrequency", 28, 29);
       hm.C = ohm16;
       hm ohm32 = ohm16;
       ohm18 = new hm("UploadNotificationInfoMaxNum", 29, 30);
       hm.D = ohm18;
       hm ohm33 = ohm18;
       ohm16 = new hm("CollectionNotificationInfoBaseSwitch", 30, 31);
       hm.E = ohm16;
       hm ohm34 = ohm16;
       ohm18 = new hm("CollectionNotificationInfoAppSwitch", 31, 32);
       hm.F = ohm18;
       hm ohm35 = ohm18;
       ohm16 = new hm("CollectionNotificationInfoRemovedSwitch", 32, 33);
       hm.G = ohm16;
       hm ohm36 = ohm16;
       ohm18 = new hm("ForegroundServiceSwitch", 33, 34);
       hm.H = ohm18;
       hm ohm37 = ohm18;
       ohm16 = new hm("SyncMIIDFrequency", 34, 35);
       hm.I = ohm16;
       hm ohm38 = ohm16;
       ohm18 = new hm("Upload4GSwitch", 35, 36);
       hm.J = ohm18;
       hm ohm39 = ohm18;
       ohm16 = new hm("Upload4GFrequency", 36, 37);
       hm.K = ohm16;
       hm ohm40 = ohm16;
       ohm18 = new hm("Upload3GSwitch", 37, 38);
       hm.L = ohm18;
       hm ohm41 = ohm18;
       ohm16 = new hm("Upload3GFrequency", 38, 39);
       hm.M = ohm16;
       hm ohm42 = ohm16;
       ohm18 = new hm("ShieldTypeConfig", 39, 40);
       hm.N = ohm18;
       hm ohm43 = ohm18;
       ohm16 = new hm("UploadWIFIGeoLocFrequency", 40, 41);
       hm.O = ohm16;
       hm ohm44 = ohm16;
       ohm18 = new hm("UploadNOWIFIGeoLocFrequency", 41, 42);
       hm.P = ohm18;
       hm ohm45 = ohm18;
       ohm16 = new hm("BroadcastActionCollectionSwitch", 42, 43);
       hm.Q = ohm16;
       hm ohm46 = ohm16;
       ohm18 = new hm("BroadcastActionCollectionFrequency", 43, 44);
       hm.R = ohm18;
       hm ohm47 = ohm18;
       ohm16 = new hm("UploadGeoLocSwitch", 44, 45);
       hm.S = ohm16;
       hm ohm48 = ohm16;
       ohm18 = new hm("ServiceBootMode", 45, 46);
       hm.T = ohm18;
       hm ohm49 = ohm18;
       ohm16 = new hm("AppPermissionCollectionSwitch", 46, 47);
       hm.U = ohm16;
       hm ohm50 = ohm16;
       ohm18 = new hm("AppPermissionCollectionFrequency", 47, 48);
       hm.V = ohm18;
       hm ohm51 = ohm18;
       ohm16 = new hm("WifiDevicesMacCollectionSwitch", 48, 49);
       hm.W = ohm16;
       hm ohm52 = ohm16;
       ohm18 = new hm("WifiDevicesMacCollectionFrequency", 49, 50);
       hm.X = ohm18;
       hm ohm53 = ohm18;
       ohm16 = new hm("WifiDevicesMacWifiUnchangedCollectionFrequency", 50, 51);
       hm.Y = ohm16;
       hm ohm54 = ohm16;
       ohm18 = new hm("AggregationSdkMonitorSwitch", 51, 52);
       hm.Z = ohm18;
       hm ohm55 = ohm18;
       ohm16 = new hm("AggregationSdkMonitorFrequency", 52, 53);
       hm.aa = ohm16;
       hm ohm56 = ohm16;
       ohm18 = new hm("AggregationSdkMonitorDepth", 53, 54);
       hm.ab = ohm18;
       hm ohm57 = ohm18;
       ohm16 = new hm("UploadGeoAppLocSwitch", 54, 55);
       hm.ac = ohm16;
       hm ohm58 = ohm16;
       ohm18 = new hm("ThirdPushControlSwitch", 55, 56);
       hm.ad = ohm18;
       hm ohm59 = ohm18;
       ohm16 = new hm("ThirdPushComponentKeyWords", 56, 57);
       hm.ae = ohm16;
       hm ohm60 = ohm16;
       ohm18 = new hm("ThirdPushWhiteList", 57, 58);
       hm.af = ohm18;
       hm ohm61 = ohm18;
       ohm16 = new hm("XmsfScanWhitelist", 58, 59);
       hm.ag = ohm16;
       hm ohm62 = ohm16;
       ohm18 = new hm("IccidCollectionSwitch", 59, 60);
       hm.ah = ohm18;
       hm ohm63 = ohm18;
       ohm16 = new hm("LimitThridPushStrategyMode", 60, 61);
       hm.ai = ohm16;
       hm ohm64 = ohm16;
       ohm18 = new hm("GlobalPushChannelException", 61, 62);
       hm.aj = ohm18;
       hm ohm65 = ohm18;
       ohm16 = new hm("TinyDataUploadSwitch", 62, 63);
       hm.ak = ohm16;
       hm ohm66 = ohm16;
       ohm18 = new hm("TinyDataUploadFrequency", 63, 64);
       hm.al = ohm18;
       hm ohm67 = ohm18;
       ohm16 = new hm("GlobalRegionIOSwitch", 64, 65);
       hm.am = ohm16;
       hm ohm68 = ohm16;
       ohm18 = new hm("GlobalRegionIOWait", 65, 66);
       hm.an = ohm18;
       hm ohm69 = ohm18;
       ohm16 = new hm("AggregatePushSwitch", 66, 67);
       hm.ao = ohm16;
       hm ohm70 = ohm16;
       ohm18 = new hm("ActivityTSSwitch", 67, 68);
       hm.ap = ohm18;
       hm ohm71 = ohm18;
       ohm16 = new hm("OperatorSwitch", 68, 69);
       hm.aq = ohm16;
       hm ohm72 = ohm16;
       ohm18 = new hm("DeviceIdSwitch", 69, 70);
       hm.ar = ohm18;
       hm ohm73 = ohm18;
       ohm16 = new hm("DeviceBaseInfoCollectionFrequency", 70, 71);
       hm.as = ohm16;
       hm ohm74 = ohm16;
       ohm18 = new hm("UsageStatsCollectionFrequency", 71, 72);
       hm.at = ohm18;
       hm ohm75 = ohm18;
       ohm16 = new hm("UsageStatsCollectionWhiteList", 72, 73);
       hm.au = ohm16;
       hm ohm76 = ohm16;
       ohm18 = new hm("ForceHandleCrashSwitch", 73, 74);
       hm.av = ohm18;
       hm ohm77 = ohm18;
       ohm16 = new hm("Crash4GUploadSwitch", 74, 75);
       hm.aw = ohm16;
       hm ohm78 = ohm16;
       ohm18 = new hm("Crash4GUploadFrequency", 75, 76);
       hm.ax = ohm18;
       hm ohm79 = ohm18;
       ohm16 = new hm("CrashWIFIUploadFrequency", 76, 77);
       hm.ay = ohm16;
       hm ohm80 = ohm16;
       ohm18 = new hm("EventUploadSwitch", 77, 78);
       hm.az = ohm18;
       hm ohm81 = ohm18;
       ohm16 = new hm("PerfUploadSwitch", 78, 79);
       hm.aA = ohm16;
       hm ohm82 = ohm16;
       ohm18 = new hm("EventUploadFrequency", 79, 80);
       hm.aB = ohm18;
       hm ohm83 = ohm18;
       ohm16 = new hm("PerfUploadFrequency", 80, 81);
       hm.aC = ohm16;
       hm ohm84 = ohm16;
       ohm18 = new hm("BatteryCollectionSwitch", 81, 82);
       hm.aD = ohm18;
       hm ohm85 = ohm18;
       ohm16 = new hm("BatteryCollectionFrequency", 82, 83);
       hm.aE = ohm16;
       hm ohm86 = ohm16;
       ohm18 = new hm("AwakeInfoUploadWaySwitch", 83, 84);
       hm.aF = ohm18;
       hm ohm87 = ohm18;
       ohm16 = new hm("AwakeAppPingSwitch", 84, 85);
       hm.aG = ohm16;
       hm ohm88 = ohm16;
       ohm18 = new hm("AwakeAppPingFrequency", 85, 86);
       hm.aH = ohm18;
       hm ohm89 = ohm18;
       ohm16 = new hm("StorageCollectionSwitch", 86, 87);
       hm.aI = ohm16;
       hm ohm90 = ohm16;
       ohm18 = new hm("StorageCollectionFrequency", 87, 88);
       hm.aJ = ohm18;
       hm ohm91 = ohm18;
       ohm16 = new hm("PopupDialogWhiteList", 88, 94);
       hm.aK = ohm16;
       hm ohm92 = ohm16;
       ohm18 = new hm("PopupDialogContent", 89, 95);
       hm.aL = ohm18;
       hm ohm93 = ohm18;
       ohm16 = new hm("PopupDialogSwitch", 90, 96);
       hm.aM = ohm16;
       hm ohm94 = ohm16;
       ohm18 = new hm("FallDownTimeRange", 91, 97);
       hm.aN = ohm18;
       hm ohm95 = ohm18;
       ohm16 = new hm("AppIsInstalledCollectionSwitch", 92, 98);
       hm.aO = ohm16;
       hm ohm96 = ohm16;
       ohm18 = new hm("AppIsInstalledCollectionFrequency", 93, 99);
       hm.aP = ohm18;
       hm ohm97 = ohm18;
       ohm16 = new hm("AppIsInstalledList", 94, 100);
       hm.aQ = ohm16;
       hm ohm98 = ohm16;
       ohm18 = new hm("TopNotificationUpdateFrequency", 95, 101);
       hm.aR = ohm18;
       hm ohm99 = ohm18;
       ohm16 = new hm("TopNotificationUpdatePeriod", 96, 102);
       hm.aS = ohm16;
       hm ohm100 = ohm16;
       ohm18 = new hm("TopNotificationUpdateSwitch", 97, 103);
       hm.aT = ohm18;
       hm ohm101 = ohm18;
       ohm16 = new hm("EventUploadNewSwitch", 98, 104);
       hm.aU = ohm16;
       hm ohm102 = ohm16;
       ohm18 = new hm("ScreenOnOrChargingTinyDataUploadSwitch", 99, 105);
       hm.aV = ohm18;
       hm ohm103 = ohm18;
       ohm16 = new hm("NotificationAutoGroupSwitch", 100, 106);
       hm.aW = ohm16;
       hm ohm104 = ohm16;
       ohm18 = new hm("LatestNotificationNotIntoGroupSwitch", 101, 107);
       hm.aX = ohm18;
       hm ohm105 = ohm18;
       ohm16 = new hm("DCJobMutualSwitch", 102, 108);
       hm.aY = ohm16;
       hm ohm106 = ohm16;
       ohm18 = new hm("NotificationBelongToAppSwitch", 103, 109);
       hm.aZ = ohm18;
       hm ohm107 = ohm18;
       ohm16 = new hm("DCJobUploadRepeatedInterval", 104, 110);
       hm.ba = ohm16;
       hm ohm108 = ohm16;
       ohm18 = new hm("LauncherAppListCollectionSwitch", 105, 111);
       hm.bb = ohm18;
       hm ohm109 = ohm18;
       ohm16 = new hm("LauncherAppListCollectionFrequency", 106, 112);
       hm.bc = ohm16;
       hm ohm110 = ohm16;
       ohm18 = new hm("ScenePushForegroundDuration", 107, 113);
       hm.bd = ohm18;
       hm ohm111 = ohm18;
       ohm16 = new hm("ScenePushForegroundDurationLong", 108, 114);
       hm.be = ohm16;
       hm ohm112 = ohm16;
       ohm18 = new hm("ExceptionMonitorSwitch", 109, 115);
       hm.bf = ohm18;
       hm ohm113 = ohm18;
       ohm16 = new hm("IntelligentHeartbeatSwitchBoolean", 110, 116);
       hm.bg = ohm16;
       hm ohm114 = ohm16;
       ohm18 = new hm("IntelligentHeartbeatDataCollectSwitchBoolean", 111, 117);
       hm.bh = ohm18;
       hm ohm115 = ohm18;
       ohm16 = new hm("IntelligentHeartbeatNATCountInt", 112, 118);
       hm.bi = ohm16;
       hm ohm116 = ohm16;
       ohm18 = new hm("IntelligentHeartbeatUseInMobileNetworkBoolean", 113, 119);
       hm.bj = ohm18;
       hm ohm117 = ohm18;
       ohm16 = new hm("StatDataUploadFrequency", 114, 120);
       hm.bk = ohm16;
       hm ohm118 = ohm16;
       ohm18 = new hm("StatDataUploadNum", 115, 121);
       hm.bl = ohm18;
       hm ohm119 = ohm18;
       ohm16 = new hm("StatDataProcessFrequency", 116, 122);
       hm.bm = ohm16;
       hm ohm120 = ohm16;
       ohm18 = new hm("StatDataSwitch", 117, 123);
       hm.bn = ohm18;
       hm ohm121 = ohm18;
       ohm16 = new hm("StatDataUploadWay", 118, 124);
       hm.bo = ohm16;
       hm ohm122 = ohm16;
       ohm18 = new hm("StatDataDeleteFrequency", 119, 125);
       hm.bp = ohm18;
       hm ohm123 = ohm18;
       ohm16 = new hm("SdkExceptionMonitorSwitch", 120, 126);
       hm.bq = ohm16;
       hm ohm124 = ohm16;
       ohm18 = new hm("ShortHeartbeatEffectivePeriodMsLong", 121, 130);
       hm.br = ohm18;
       hm ohm125 = ohm18;
       ohm16 = new hm("CollectionDataPluginVersion", 122, 1001);
       hm.bs = ohm16;
       hm ohm126 = ohm16;
       ohm18 = new hm("CollectionPluginDownloadUrl", 123, 1002);
       hm.bt = ohm18;
       hm ohm127 = ohm18;
       ohm16 = new hm("CollectionPluginMd5", 124, 1003);
       hm.bu = ohm16;
       hm ohm128 = ohm16;
       ohm18 = new hm("CollectionPluginForceStop", 125, 1004);
       hm.bv = ohm18;
       hm[] ohmArray = new hm[126];
       ohmArray[0] = ohm;
       ohmArray[1] = ohm1;
       ohmArray[2] = ohm2;
       ohmArray[3] = ohm3;
       ohmArray[4] = ohm4;
       ohmArray[5] = ohm5;
       ohmArray[6] = ohm6;
       ohmArray[7] = ohm7;
       ohmArray[8] = ohm8;
       ohmArray[9] = ohm9;
       ohmArray[10] = ohm10;
       ohmArray[11] = ohm11;
       ohmArray[12] = ohm13;
       ohmArray[13] = ohm15;
       ohmArray[14] = ohm17;
       ohmArray[15] = ohm19;
       ohmArray[16] = ohm20;
       ohmArray[17] = ohm21;
       ohmArray[18] = ohm22;
       ohmArray[19] = ohm23;
       ohmArray[20] = ohm24;
       ohmArray[21] = ohm25;
       ohmArray[22] = ohm26;
       ohmArray[23] = ohm27;
       ohmArray[24] = ohm28;
       ohmArray[25] = ohm29;
       ohmArray[26] = ohm30;
       ohmArray[27] = ohm31;
       ohmArray[28] = ohm32;
       ohmArray[29] = ohm33;
       ohmArray[30] = ohm34;
       ohmArray[31] = ohm35;
       ohmArray[32] = ohm36;
       ohmArray[33] = ohm37;
       ohmArray[34] = ohm38;
       ohmArray[35] = ohm39;
       ohmArray[36] = ohm40;
       ohmArray[37] = ohm41;
       ohmArray[38] = ohm42;
       ohmArray[39] = ohm43;
       ohmArray[40] = ohm44;
       ohmArray[41] = ohm45;
       ohmArray[42] = ohm46;
       ohmArray[43] = ohm47;
       ohmArray[44] = ohm48;
       ohmArray[45] = ohm49;
       ohmArray[46] = ohm50;
       ohmArray[47] = ohm51;
       ohmArray[48] = ohm52;
       ohmArray[49] = ohm53;
       ohmArray[50] = ohm54;
       ohmArray[51] = ohm55;
       ohmArray[52] = ohm56;
       ohmArray[53] = ohm57;
       ohmArray[54] = ohm58;
       ohmArray[55] = ohm59;
       ohmArray[56] = ohm60;
       ohmArray[57] = ohm61;
       ohmArray[58] = ohm62;
       ohmArray[59] = ohm63;
       ohmArray[60] = ohm64;
       ohmArray[61] = ohm65;
       ohmArray[62] = ohm66;
       ohmArray[63] = ohm67;
       ohmArray[64] = ohm68;
       ohmArray[65] = ohm69;
       ohmArray[66] = ohm70;
       ohmArray[67] = ohm71;
       ohmArray[68] = ohm72;
       ohmArray[69] = ohm73;
       ohmArray[70] = ohm74;
       ohmArray[71] = ohm75;
       ohmArray[72] = ohm76;
       ohmArray[73] = ohm77;
       ohmArray[74] = ohm78;
       ohmArray[75] = ohm79;
       ohmArray[76] = ohm80;
       ohmArray[77] = ohm81;
       ohmArray[78] = ohm82;
       ohmArray[79] = ohm83;
       ohmArray[80] = ohm84;
       ohmArray[81] = ohm85;
       ohmArray[82] = ohm86;
       ohmArray[83] = ohm87;
       ohmArray[84] = ohm88;
       ohmArray[85] = ohm89;
       ohmArray[86] = ohm90;
       ohmArray[87] = ohm91;
       ohmArray[88] = ohm92;
       ohmArray[89] = ohm93;
       ohmArray[90] = ohm94;
       ohmArray[91] = ohm95;
       ohmArray[92] = ohm96;
       ohmArray[93] = ohm97;
       ohmArray[94] = ohm98;
       ohmArray[95] = ohm99;
       ohmArray[96] = ohm100;
       ohmArray[97] = ohm101;
       ohmArray[98] = ohm102;
       ohmArray[99] = ohm103;
       ohmArray[100] = ohm104;
       ohmArray[101] = ohm105;
       ohmArray[102] = ohm106;
       ohmArray[103] = ohm107;
       ohmArray[104] = ohm108;
       ohmArray[105] = ohm109;
       ohmArray[106] = ohm110;
       ohmArray[107] = ohm111;
       ohmArray[108] = ohm112;
       ohmArray[109] = ohm113;
       ohmArray[110] = ohm114;
       ohmArray[111] = ohm115;
       ohmArray[112] = ohm116;
       ohmArray[113] = ohm117;
       ohmArray[114] = ohm118;
       ohmArray[115] = ohm119;
       ohmArray[116] = ohm120;
       ohmArray[117] = ohm121;
       ohmArray[118] = ohm122;
       ohmArray[119] = ohm123;
       ohmArray[120] = ohm124;
       ohmArray[121] = ohm125;
       ohmArray[122] = ohm126;
       ohmArray[123] = ohm127;
       ohmArray[124] = ohm128;
       ohmArray[125] = ohm18;
       hm.a = ohmArray;
    }
    public void hm(String p0,int p1,int p2){
       this.a = p2;
    }
    public static hm valueOf(String p0){
       return Enum.valueOf(hm.class, p0);
    }
    public static hm[] values(){
       return hm.a.clone();
    }
    public int a(){
       return this.a;
    }
}
