package com.xiaomi.push.hr;
import java.lang.Enum;
import java.lang.String;
import java.lang.Class;
import java.lang.Object;

public final class hr extends Enum	// class@00111a
{
    public final String a;
    public static final hr A;
    public static final hr B;
    public static final hr C;
    public static final hr D;
    public static final hr E;
    public static final hr F;
    public static final hr G;
    public static final hr H;
    public static final hr I;
    public static final hr J;
    public static final hr K;
    public static final hr L;
    public static final hr M;
    public static final hr N;
    public static final hr O;
    public static final hr P;
    public static final hr Q;
    public static final hr R;
    public static final hr S;
    public static final hr T;
    public static final hr U;
    public static final hr V;
    public static final hr W;
    public static final hr X;
    public static final hr Y;
    public static final hr Z;
    public static final hr a;
    public static final hr[] a;
    public static final hr aa;
    public static final hr ab;
    public static final hr ac;
    public static final hr ad;
    public static final hr ae;
    public static final hr af;
    public static final hr ag;
    public static final hr b;
    public static final hr c;
    public static final hr d;
    public static final hr e;
    public static final hr f;
    public static final hr g;
    public static final hr h;
    public static final hr i;
    public static final hr j;
    public static final hr k;
    public static final hr l;
    public static final hr m;
    public static final hr n;
    public static final hr o;
    public static final hr p;
    public static final hr q;
    public static final hr r;
    public static final hr s;
    public static final hr t;
    public static final hr u;
    public static final hr v;
    public static final hr w;
    public static final hr x;
    public static final hr y;
    public static final hr z;

    static {
       hr ohr = new hr("Invalid", 0, "INVALID");
       hr.a = ohr;
       hr ohr1 = new hr("BarClick", 1, "bar:click");
       hr.b = ohr1;
       hr ohr2 = new hr("BarCancel", 2, "bar:cancel");
       hr.c = ohr2;
       hr ohr3 = new hr("AppOpen", 3, "app:open");
       hr.d = ohr3;
       hr ohr4 = new hr("PackageUninstall", 4, "package uninstalled");
       hr.e = ohr4;
       hr ohr5 = new hr("AppUninstall", 5, "app_uninstalled");
       hr.f = ohr5;
       hr ohr6 = new hr("ClientInfoUpdate", 6, "client_info_update");
       hr.g = ohr6;
       hr ohr7 = new hr("ClientInfoUpdateOk", 7, "client_info_update_ok");
       hr.h = ohr7;
       hr ohr8 = new hr("ClientMIIDUpdate", 8, "client_miid_update");
       hr.i = ohr8;
       hr ohr9 = new hr("PullOfflineMessage", 9, "pull");
       hr.j = ohr9;
       hr ohr10 = new hr("IosSleep", 10, "ios_sleep");
       hr.k = ohr10;
       hr ohr11 = new hr("IosWakeUp", 11, "ios_wakeup");
       hr.l = ohr11;
       hr ohr12 = new hr("AwakeApp", 12, "awake_app");
       hr.m = ohr12;
       hr ohr13 = ohr12;
       hr ohr14 = new hr("NormalClientConfigUpdate", 13, "normal_client_config_update");
       hr.n = ohr14;
       hr ohr15 = ohr14;
       ohr12 = new hr("CustomClientConfigUpdate", 14, "custom_client_config_update");
       hr.o = ohr12;
       hr ohr16 = ohr12;
       ohr14 = new hr("DailyCheckClientConfig", 15, "daily_check_client_config");
       hr.p = ohr14;
       hr ohr17 = ohr14;
       ohr12 = new hr("DataCollection", 16, "data_collection");
       hr.q = ohr12;
       hr ohr18 = ohr12;
       ohr14 = new hr("RegIdExpired", 17, "registration id expired");
       hr.r = ohr14;
       hr ohr19 = ohr14;
       ohr12 = new hr("ConnectionDisabled", 18, "!!!MILINK CONNECTION DISABLED!!!");
       hr.s = ohr12;
       hr ohr20 = ohr12;
       ohr14 = new hr("PackageUnregistered", 19, "package_unregistered");
       hr.t = ohr14;
       hr ohr21 = ohr14;
       ohr12 = new hr("DecryptMessageFail", 20, "decrypt_msg_fail");
       hr.u = ohr12;
       hr ohr22 = ohr12;
       ohr14 = new hr("SyncInfo", 21, "sync_info");
       hr.v = ohr14;
       hr ohr23 = ohr14;
       ohr12 = new hr("SyncInfoResult", 22, "sync_info_result");
       hr.w = ohr12;
       hr ohr24 = ohr12;
       ohr14 = new hr("ForceSync", 23, "force_sync");
       hr.x = ohr14;
       hr ohr25 = ohr14;
       ohr12 = new hr("UploadClientLog", 24, "upload_client_log");
       hr.y = ohr12;
       hr ohr26 = ohr12;
       ohr14 = new hr("NotificationBarInfo", 25, "notification_bar_info");
       hr.z = ohr14;
       hr ohr27 = ohr14;
       ohr12 = new hr("SyncMIID", 26, "sync_miid");
       hr.A = ohr12;
       hr ohr28 = ohr12;
       ohr14 = new hr("UploadTinyData", 27, "upload");
       hr.B = ohr14;
       hr ohr29 = ohr14;
       ohr12 = new hr("CancelPushMessage", 28, "clear_push_message");
       hr.C = ohr12;
       hr ohr30 = ohr12;
       ohr14 = new hr("CancelPushMessageACK", 29, "clear_push_message_ack");
       hr.D = ohr14;
       hr ohr31 = ohr14;
       ohr12 = new hr("DisablePushMessage", 30, "disable_push");
       hr.E = ohr12;
       hr ohr32 = ohr12;
       ohr14 = new hr("EnablePushMessage", 31, "enable_push");
       hr.F = ohr14;
       hr ohr33 = ohr14;
       ohr12 = new hr("ClientABTest", 32, "client_ab_test");
       hr.G = ohr12;
       hr ohr34 = ohr12;
       ohr14 = new hr("AwakeSystemApp", 33, "awake_system_app");
       hr.H = ohr14;
       hr ohr35 = ohr14;
       ohr12 = new hr("AwakeAppResponse", 34, "awake_app_response");
       hr.I = ohr12;
       hr ohr36 = ohr12;
       ohr14 = new hr("HybridRegister", 35, "hb_register");
       hr.J = ohr14;
       hr ohr37 = ohr14;
       ohr12 = new hr("HybridRegisterResult", 36, "hb_register_res");
       hr.K = ohr12;
       hr ohr38 = ohr12;
       ohr14 = new hr("HybridUnregister", 37, "hb_unregister");
       hr.L = ohr14;
       hr ohr39 = ohr14;
       ohr12 = new hr("HybridUnregisterResult", 38, "hb_unregister_res");
       hr.M = ohr12;
       hr ohr40 = ohr12;
       ohr14 = new hr("ThirdPartyRegUpdate", 39, "3rd_party_reg_update");
       hr.N = ohr14;
       hr ohr41 = ohr14;
       ohr12 = new hr("VRUpload", 40, "vr_upload");
       hr.O = ohr12;
       hr ohr42 = ohr12;
       ohr14 = new hr("PushLogUpload", 41, "log_upload");
       hr.P = ohr14;
       hr ohr43 = ohr14;
       ohr12 = new hr("APP_WAKEUP", 42, "app_wakeup");
       hr.Q = ohr12;
       hr ohr44 = ohr12;
       ohr14 = new hr("APP_SLEEP", 43, "app_sleep");
       hr.R = ohr14;
       hr ohr45 = ohr14;
       ohr12 = new hr("NOTIFICATION_SWITCH", 44, "notification_switch");
       hr.S = ohr12;
       hr ohr46 = ohr12;
       ohr14 = new hr("ACTIVITY_RESUMED", 45, "activity_resumed");
       hr.T = ohr14;
       hr ohr47 = ohr14;
       ohr12 = new hr("HeadsUpReporter", 46, "headsup_reporter");
       hr.U = ohr12;
       hr ohr48 = ohr12;
       ohr14 = new hr("ScenePushRuleUpdate", 47, "scene_push_rule_update");
       hr.V = ohr14;
       hr ohr49 = ohr14;
       ohr12 = new hr("ScenePushRuleDelete", 48, "scene_push_rule_delete");
       hr.W = ohr12;
       hr ohr50 = ohr12;
       ohr14 = new hr("ScenePushRuleTrigger", 49, "scene_push_rule_trigger");
       hr.X = ohr14;
       hr ohr51 = ohr14;
       ohr12 = new hr("NotificationRemoved", 50, "notification_removed");
       hr.Y = ohr12;
       hr ohr52 = ohr12;
       ohr14 = new hr("NotificationArrived", 51, "notification_arrived");
       hr.Z = ohr14;
       hr ohr53 = ohr14;
       ohr12 = new hr("NotificationClicked", 52, "notification_clicked");
       hr.aa = ohr12;
       hr ohr54 = ohr12;
       ohr14 = new hr("PullDownPop", 53, "pull_down_pop");
       hr.ab = ohr14;
       hr ohr55 = ohr14;
       ohr12 = new hr("AppDataCleared", 54, "app_data_cleared");
       hr.ac = ohr12;
       hr ohr56 = ohr12;
       ohr14 = new hr("TtsReporter", 55, "tts_data_reporter");
       hr.ad = ohr14;
       hr ohr57 = ohr14;
       ohr12 = new hr("SDK_START_ACTIVITY", 56, "sdk_start_activity");
       hr.ae = ohr12;
       hr ohr58 = ohr12;
       ohr14 = new hr("DetectAppAlive", 57, "detect_app_alive");
       hr.af = ohr14;
       hr ohr59 = ohr14;
       ohr12 = new hr("DetectAppAliveResult", 58, "detect_app_alive_result");
       hr.ag = ohr12;
       hr[] ohrArray = new hr[59];
       ohrArray[0] = ohr;
       ohrArray[1] = ohr1;
       ohrArray[2] = ohr2;
       ohrArray[3] = ohr3;
       ohrArray[4] = ohr4;
       ohrArray[5] = ohr5;
       ohrArray[6] = ohr6;
       ohrArray[7] = ohr7;
       ohrArray[8] = ohr8;
       ohrArray[9] = ohr9;
       ohrArray[10] = ohr10;
       ohrArray[11] = ohr11;
       ohrArray[12] = ohr13;
       ohrArray[13] = ohr15;
       ohrArray[14] = ohr16;
       ohrArray[15] = ohr17;
       ohrArray[16] = ohr18;
       ohrArray[17] = ohr19;
       ohrArray[18] = ohr20;
       ohrArray[19] = ohr21;
       ohrArray[20] = ohr22;
       ohrArray[21] = ohr23;
       ohrArray[22] = ohr24;
       ohrArray[23] = ohr25;
       ohrArray[24] = ohr26;
       ohrArray[25] = ohr27;
       ohrArray[26] = ohr28;
       ohrArray[27] = ohr29;
       ohrArray[28] = ohr30;
       ohrArray[29] = ohr31;
       ohrArray[30] = ohr32;
       ohrArray[31] = ohr33;
       ohrArray[32] = ohr34;
       ohrArray[33] = ohr35;
       ohrArray[34] = ohr36;
       ohrArray[35] = ohr37;
       ohrArray[36] = ohr38;
       ohrArray[37] = ohr39;
       ohrArray[38] = ohr40;
       ohrArray[39] = ohr41;
       ohrArray[40] = ohr42;
       ohrArray[41] = ohr43;
       ohrArray[42] = ohr44;
       ohrArray[43] = ohr45;
       ohrArray[44] = ohr46;
       ohrArray[45] = ohr47;
       ohrArray[46] = ohr48;
       ohrArray[47] = ohr49;
       ohrArray[48] = ohr50;
       ohrArray[49] = ohr51;
       ohrArray[50] = ohr52;
       ohrArray[51] = ohr53;
       ohrArray[52] = ohr54;
       ohrArray[53] = ohr55;
       ohrArray[54] = ohr56;
       ohrArray[55] = ohr57;
       ohrArray[56] = ohr58;
       ohrArray[57] = ohr59;
       ohrArray[58] = ohr12;
       hr.a = ohrArray;
    }
    public void hr(String p0,int p1,String p2){
       this.a = p2;
    }
    public static hr valueOf(String p0){
       return Enum.valueOf(hr.class, p0);
    }
    public static hr[] values(){
       return hr.a.clone();
    }
    public String toString(){
       return this.a;
    }
}
