package ca.a;
import java.lang.Object;
import ekd.e0;
import android.content.Context;
import com.yxcorp.utility.n;
import android.graphics.Typeface;
import com.contrarywind.view.WheelView$DividerType;

public class a	// class@000cfe
{
    public boolean A;
    public boolean B;
    public int C;
    public String D;
    public String E;
    public String F;
    public String G;
    public String H;
    public String I;
    public int J;
    public int K;
    public int L;
    public int M;
    public int N;
    public int O;
    public int P;
    public ViewGroup Q;
    public int R;
    public Context S;
    public String T;
    public String U;
    public String V;
    public int W;
    public int X;
    public int Y;
    public int Z;
    public e a;
    public int a0;
    public g b;
    public int b0;
    public f c;
    public int c0;
    public d d;
    public int d0;
    public a e;
    public int e0;
    public String f;
    public int f0;
    public String g;
    public int g0;
    public String h;
    public int h0;
    public int i;
    public int i0;
    public int j;
    public int j0;
    public int k;
    public float k0;
    public int l;
    public boolean l0;
    public int m;
    public boolean m0;
    public int n;
    public boolean n0;
    public boolean o;
    public boolean o0;
    public boolean p;
    public Typeface p0;
    public boolean q;
    public WheelView$DividerType q0;
    public boolean r;
    public float s;
    public boolean t;
    public boolean[] u;
    public Calendar v;
    public Calendar w;
    public Calendar x;
    public int y;
    public int z;

    public void a(int p0){
       super();
       this.o = false;
       this.p = false;
       this.q = false;
       this.r = false;
       this.u = new boolean[6]{0x01,0x01,0x01,0x00,0x00,0x00};
       this.A = false;
       this.B = false;
       this.C = 0;
       this.R = 17;
       this.W = -16417281;
       this.X = -16417281;
       this.Y = 0xff000000;
       this.Z = -1;
       this.a0 = -657931;
       this.b0 = 17;
       this.c0 = 18;
       this.d0 = 18;
       this.e0 = n.c0(e0.b, 16.00f);
       this.f0 = n.c0(e0.b, 20.00f);
       this.g0 = -5723992;
       this.h0 = -14013910;
       this.i0 = -2763307;
       this.j0 = -1;
       this.k0 = 0x3fcccccd;
       this.n0 = true;
       this.o0 = false;
       this.p0 = Typeface.MONOSPACE;
       this.q0 = WheelView$DividerType.FILL;
       this.P = (p0 == 1)? 0x7f0d114e: 0x7f0d114f;
       return;
    }
}
