package ca.b;
import java.lang.Object;
import ekd.e0;
import android.content.Context;
import com.yxcorp.utility.n;
import android.graphics.Typeface;
import com.contrarywind.view.WheelView$DividerType;

public class b	// class@000cff
{
    public boolean A;
    public String B;
    public String C;
    public String D;
    public String E;
    public String F;
    public String G;
    public int H;
    public int I;
    public int J;
    public int K;
    public int L;
    public int M;
    public int N;
    public ViewGroup O;
    public int P;
    public Context Q;
    public String R;
    public String S;
    public String T;
    public int U;
    public int V;
    public int W;
    public int X;
    public int Y;
    public int Z;
    public e a;
    public int a0;
    public g b;
    public int b0;
    public f c;
    public int c0;
    public d d;
    public int d0;
    public a e;
    public int e0;
    public String f;
    public int f0;
    public String g;
    public float g0;
    public String h;
    public boolean h0;
    public int i;
    public boolean i0;
    public int j;
    public boolean j0;
    public int k;
    public Typeface k0;
    public int l;
    public WheelView$DividerType l0;
    public int m;
    public int n;
    public boolean o;
    public boolean p;
    public boolean q;
    public boolean r;
    public boolean s;
    public boolean[] t;
    public Calendar u;
    public Calendar v;
    public Calendar w;
    public int x;
    public int y;
    public boolean z;

    public void b(int p0){
       super();
       this.o = false;
       this.p = false;
       this.q = false;
       this.r = false;
       this.t = new boolean[6]{0x01,0x01,0x01,0x00,0x00,0x00};
       this.z = false;
       this.A = false;
       this.P = 17;
       this.U = -16417281;
       this.V = -16417281;
       this.W = 0xff000000;
       this.X = -1;
       this.Y = -657931;
       this.Z = 17;
       this.a0 = 18;
       this.b0 = n.c0(e0.b, 18.00f);
       this.c0 = -5723992;
       this.d0 = -14013910;
       this.e0 = -2763307;
       this.f0 = -1;
       this.g0 = 0x3fcccccd;
       this.i0 = true;
       this.j0 = false;
       this.k0 = Typeface.MONOSPACE;
       this.l0 = WheelView$DividerType.FILL;
       this.N = (p0 == 1)? 0x7f0d114e: 0x7f0d114f;
       return;
    }
}
