package io.netty.buffer.d;
import wqd.n;
import java.lang.Comparable;
import java.lang.Object;
import java.io.InputStream;
import java.nio.channels.ScatteringByteChannel;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import io.netty.util.a;
import java.nio.channels.GatheringByteChannel;
import kqd.e;
import java.io.OutputStream;
import java.nio.charset.Charset;
import java.lang.String;

public abstract class d implements n, Comparable	// class@001045
{

    public void d(){
       super();
    }
    public abstract long A4(int p0);
    public abstract short A5();
    public abstract int A6(InputStream p0,int p1);
    public abstract int B4(int p0);
    public abstract short B5();
    public abstract int B6(ScatteringByteChannel p0,int p1);
    public abstract d C3(int p0);
    public abstract int C4(int p0);
    public abstract d C5(int p0);
    public abstract d C6(d p0);
    public abstract d D2(int p0,int p1);
    public abstract short D4(int p0);
    public abstract short D5();
    public abstract d D6(d p0,int p1);
    public abstract short E4(int p0);
    public abstract long E5();
    public abstract d E6(d p0,int p1,int p2);
    public abstract d F2();
    public abstract short F4(int p0);
    public abstract long F5();
    public abstract d F6(ByteBuffer p0);
    public abstract long G4(int p0);
    public abstract int G5();
    public abstract d G6(byte[] p0);
    public abstract long H4(int p0);
    public abstract int H5();
    public abstract d H6(byte[] p0,int p1,int p2);
    public abstract int I4(int p0);
    public abstract int I5();
    public abstract d I6(int p0);
    public abstract int J4(int p0);
    public abstract int J5();
    public abstract d J6(double p0);
    public abstract int K4(int p0);
    public abstract d K6(float p0);
    public abstract int L0();
    public abstract int L4(int p0);
    public abstract int L5();
    public abstract d L6(int p0);
    public abstract boolean M4();
    public abstract int M5();
    public abstract d M6(int p0);
    public abstract boolean N4();
    public abstract d N5(int p0);
    public abstract d N6(long p0);
    public abstract int O4(int p0,int p1,byte p2);
    public abstract d O5();
    public abstract d O6(long p0);
    public abstract ByteBuffer P4(int p0,int p1);
    public abstract d P5();
    public abstract d P6(int p0);
    public abstract boolean Q4();
    public abstract d Q5();
    public abstract d Q6(int p0);
    public abstract boolean R4();
    public abstract d R5(int p0);
    public abstract d R6(int p0);
    public abstract boolean S4(int p0);
    public abstract d S5(int p0,boolean p1);
    public abstract d S6(int p0);
    public abstract boolean T4(int p0);
    public abstract d T5(int p0,int p1);
    public abstract d T6(int p0);
    public abstract d U4();
    public abstract int U5(int p0,InputStream p1,int p2);
    public abstract int U6();
    public abstract d V1(int p0);
    public abstract boolean V2();
    public abstract d V4();
    public abstract int V5(int p0,ScatteringByteChannel p1,int p2);
    public abstract d V6(int p0);
    public abstract int W4();
    public abstract d W5(int p0,d p1);
    public abstract int X0(byte p0);
    public abstract int X4();
    public abstract d X5(int p0,d p1,int p2);
    public abstract d Y1();
    public abstract long Y4();
    public abstract d Y5(int p0,d p1,int p2,int p3);
    public abstract ByteBuffer Z4();
    public abstract d Z5(int p0,ByteBuffer p1);
    public abstract ByteBuffer a5(int p0,int p1);
    public abstract d a6(int p0,byte[] p1);
    public n b(){
       return this.u6();
    }
    public abstract int b5();
    public abstract d b6(int p0,byte[] p1,int p2,int p3);
    public abstract ByteBuffer[] c5();
    public abstract d c6(int p0,int p1);
    public int compareTo(Object p0){
       return this.l2(p0);
    }
    public n d(Object p0){
       return this.v6(p0);
    }
    public abstract ByteBuffer[] d5(int p0,int p1);
    public abstract d d6(int p0,double p1);
    public abstract d e5(ByteOrder p0);
    public abstract d e6(int p0,float p1);
    public abstract boolean equals(Object p0);
    public abstract ByteOrder f5();
    public abstract d f6(int p0,int p1);
    public abstract boolean g5();
    public abstract d g6(int p0,int p1);
    public abstract boolean getBoolean(int p0);
    public abstract double getDouble(int p0);
    public abstract float getFloat(int p0);
    public abstract int getInt(int p0);
    public abstract long getLong(int p0);
    public abstract int h4(int p0,int p1,a p2);
    public abstract byte h5();
    public abstract d h6(int p0,int p1);
    public abstract int hashCode();
    public abstract int i5(GatheringByteChannel p0,int p1);
    public abstract d i6(int p0,long p1);
    public abstract d j5(int p0);
    public abstract d j6(int p0,long p1);
    public abstract d k5(d p0);
    public abstract d k6(int p0,int p1);
    public n l(int p0){
       return this.R5(p0);
    }
    public abstract int l2(d p0);
    public abstract int l4(a p0);
    public abstract d l5(d p0,int p1);
    public abstract d l6(int p0,int p1);
    public abstract e m0();
    public abstract d m3();
    public abstract d m5(d p0,int p1,int p2);
    public abstract d m6(int p0,int p1);
    public abstract int n1(int p0,byte p1);
    public abstract d n3();
    public abstract int n4(int p0,int p1,a p2);
    public abstract d n5(OutputStream p0,int p1);
    public abstract d n6(int p0,int p1);
    public abstract int o4(a p0);
    public abstract d o5(ByteBuffer p0);
    public abstract d o6(int p0,int p1);
    public abstract byte p4(int p0);
    public abstract d p5(byte[] p0);
    public abstract d p6(int p0);
    public abstract d q2();
    public abstract int q4(int p0,GatheringByteChannel p1,int p2);
    public abstract d q5(byte[] p0,int p1,int p2);
    public abstract d q6();
    public abstract d r4(int p0,d p1);
    public abstract char r5();
    public abstract d r6(int p0,int p1);
    public n retain(){
       return this.Q5();
    }
    public abstract d s4(int p0,d p1,int p2);
    public abstract double s5();
    public abstract String s6(int p0,int p1,Charset p2);
    public abstract d t4(int p0,d p1,int p2,int p3);
    public abstract float t5();
    public abstract String t6(Charset p0);
    public abstract String toString();
    public abstract d u4(int p0,OutputStream p1,int p2);
    public abstract int u5();
    public abstract d u6();
    public abstract d v4(int p0,ByteBuffer p1);
    public abstract int v5();
    public abstract d v6(Object p0);
    public abstract byte[] w0();
    public abstract int w1(int p0,int p1,byte p2);
    public abstract d w4(int p0,byte[] p1);
    public abstract long w5();
    public abstract d w6();
    public abstract d x4(int p0,byte[] p1,int p2,int p3);
    public abstract long x5();
    public abstract int x6();
    public abstract int y1();
    public abstract int y3(int p0,boolean p1);
    public abstract char y4(int p0);
    public abstract int y5();
    public abstract d y6(boolean p0);
    public abstract int z4(int p0);
    public abstract int z5();
    public abstract d z6(int p0);
}
