package com.facebook.yoga.YogaNative;
import java.lang.String;
import com.facebook.soloader.SoLoader;
import java.lang.Object;
import com.facebook.yoga.YogaLogger;
import com.facebook.yoga.YogaNodeJNIBase;

public class YogaNative	// class@00145b
{

    static {
       SoLoader.b("yoga");
    }
    public void YogaNative(){
       super();
    }
    public static native void jni_YGConfigFreeJNI(long p0);
    public static native long jni_YGConfigNewJNI();
    public static native void jni_YGConfigSetExperimentalFeatureEnabledJNI(long p0,int p1,boolean p2);
    public static native void jni_YGConfigSetLoggerJNI(long p0,YogaLogger p1);
    public static native void jni_YGConfigSetPointScaleFactorJNI(long p0,float p1);
    public static native void jni_YGConfigSetPrintTreeFlagJNI(long p0,boolean p1);
    public static native void jni_YGConfigSetShouldDiffLayoutWithoutLegacyStretchBehaviourJNI(long p0,boolean p1);
    public static native void jni_YGConfigSetUseLegacyStretchBehaviourJNI(long p0,boolean p1);
    public static native void jni_YGConfigSetUseWebDefaultsJNI(long p0,boolean p1);
    public static native void jni_YGNodeCalculateLayoutJNI(long p0,float p1,float p2,long[] p3,YogaNodeJNIBase[] p4);
    public static native void jni_YGNodeClearChildrenJNI(long p0);
    public static native long jni_YGNodeCloneJNI(long p0);
    public static native void jni_YGNodeCopyStyleJNI(long p0,long p1);
    public static native void jni_YGNodeFreeJNI(long p0);
    public static native void jni_YGNodeInsertChildJNI(long p0,long p1,int p2);
    public static native boolean jni_YGNodeIsDirtyJNI(long p0);
    public static native boolean jni_YGNodeIsReferenceBaselineJNI(long p0);
    public static native void jni_YGNodeMarkDirtyAndPropogateToDescendantsJNI(long p0);
    public static native void jni_YGNodeMarkDirtyJNI(long p0);
    public static native long jni_YGNodeNewJNI();
    public static native long jni_YGNodeNewWithConfigJNI(long p0);
    public static native void jni_YGNodePrintJNI(long p0);
    public static native void jni_YGNodeRemoveChildJNI(long p0,long p1);
    public static native void jni_YGNodeResetJNI(long p0);
    public static native void jni_YGNodeSetHasBaselineFuncJNI(long p0,boolean p1);
    public static native void jni_YGNodeSetHasMeasureFuncJNI(long p0,boolean p1);
    public static native void jni_YGNodeSetIsReferenceBaselineJNI(long p0,boolean p1);
    public static native void jni_YGNodeSetStyleInputsJNI(long p0,float[] p1,int p2);
    public static native int jni_YGNodeStyleGetAlignContentJNI(long p0);
    public static native int jni_YGNodeStyleGetAlignItemsJNI(long p0);
    public static native int jni_YGNodeStyleGetAlignSelfJNI(long p0);
    public static native float jni_YGNodeStyleGetAspectRatioJNI(long p0);
    public static native float jni_YGNodeStyleGetBorderJNI(long p0,int p1);
    public static native int jni_YGNodeStyleGetDirectionJNI(long p0);
    public static native int jni_YGNodeStyleGetDisplayJNI(long p0);
    public static native long jni_YGNodeStyleGetFlexBasisJNI(long p0);
    public static native int jni_YGNodeStyleGetFlexDirectionJNI(long p0);
    public static native float jni_YGNodeStyleGetFlexGrowJNI(long p0);
    public static native float jni_YGNodeStyleGetFlexJNI(long p0);
    public static native float jni_YGNodeStyleGetFlexShrinkJNI(long p0);
    public static native int jni_YGNodeStyleGetFlexWrapJNI(long p0);
    public static native long jni_YGNodeStyleGetHeightJNI(long p0);
    public static native int jni_YGNodeStyleGetJustifyContentJNI(long p0);
    public static native long jni_YGNodeStyleGetMarginJNI(long p0,int p1);
    public static native long jni_YGNodeStyleGetMaxHeightJNI(long p0);
    public static native long jni_YGNodeStyleGetMaxWidthJNI(long p0);
    public static native long jni_YGNodeStyleGetMinHeightJNI(long p0);
    public static native long jni_YGNodeStyleGetMinWidthJNI(long p0);
    public static native int jni_YGNodeStyleGetOverflowJNI(long p0);
    public static native long jni_YGNodeStyleGetPaddingJNI(long p0,int p1);
    public static native long jni_YGNodeStyleGetPositionJNI(long p0,int p1);
    public static native int jni_YGNodeStyleGetPositionTypeJNI(long p0);
    public static native long jni_YGNodeStyleGetWidthJNI(long p0);
    public static native void jni_YGNodeStyleSetAlignContentJNI(long p0,int p1);
    public static native void jni_YGNodeStyleSetAlignItemsJNI(long p0,int p1);
    public static native void jni_YGNodeStyleSetAlignSelfJNI(long p0,int p1);
    public static native void jni_YGNodeStyleSetAspectRatioJNI(long p0,float p1);
    public static native void jni_YGNodeStyleSetBorderJNI(long p0,int p1,float p2);
    public static native void jni_YGNodeStyleSetDirectionJNI(long p0,int p1);
    public static native void jni_YGNodeStyleSetDisplayJNI(long p0,int p1);
    public static native void jni_YGNodeStyleSetFlexBasisAutoJNI(long p0);
    public static native void jni_YGNodeStyleSetFlexBasisJNI(long p0,float p1);
    public static native void jni_YGNodeStyleSetFlexBasisPercentJNI(long p0,float p1);
    public static native void jni_YGNodeStyleSetFlexDirectionJNI(long p0,int p1);
    public static native void jni_YGNodeStyleSetFlexGrowJNI(long p0,float p1);
    public static native void jni_YGNodeStyleSetFlexJNI(long p0,float p1);
    public static native void jni_YGNodeStyleSetFlexShrinkJNI(long p0,float p1);
    public static native void jni_YGNodeStyleSetFlexWrapJNI(long p0,int p1);
    public static native void jni_YGNodeStyleSetHeightAutoJNI(long p0);
    public static native void jni_YGNodeStyleSetHeightJNI(long p0,float p1);
    public static native void jni_YGNodeStyleSetHeightPercentJNI(long p0,float p1);
    public static native void jni_YGNodeStyleSetJustifyContentJNI(long p0,int p1);
    public static native void jni_YGNodeStyleSetMarginAutoJNI(long p0,int p1);
    public static native void jni_YGNodeStyleSetMarginJNI(long p0,int p1,float p2);
    public static native void jni_YGNodeStyleSetMarginPercentJNI(long p0,int p1,float p2);
    public static native void jni_YGNodeStyleSetMaxHeightJNI(long p0,float p1);
    public static native void jni_YGNodeStyleSetMaxHeightPercentJNI(long p0,float p1);
    public static native void jni_YGNodeStyleSetMaxWidthJNI(long p0,float p1);
    public static native void jni_YGNodeStyleSetMaxWidthPercentJNI(long p0,float p1);
    public static native void jni_YGNodeStyleSetMinHeightJNI(long p0,float p1);
    public static native void jni_YGNodeStyleSetMinHeightPercentJNI(long p0,float p1);
    public static native void jni_YGNodeStyleSetMinWidthJNI(long p0,float p1);
    public static native void jni_YGNodeStyleSetMinWidthPercentJNI(long p0,float p1);
    public static native void jni_YGNodeStyleSetOverflowJNI(long p0,int p1);
    public static native void jni_YGNodeStyleSetPaddingJNI(long p0,int p1,float p2);
    public static native void jni_YGNodeStyleSetPaddingPercentJNI(long p0,int p1,float p2);
    public static native void jni_YGNodeStyleSetPositionJNI(long p0,int p1,float p2);
    public static native void jni_YGNodeStyleSetPositionPercentJNI(long p0,int p1,float p2);
    public static native void jni_YGNodeStyleSetPositionTypeJNI(long p0,int p1);
    public static native void jni_YGNodeStyleSetWidthAutoJNI(long p0);
    public static native void jni_YGNodeStyleSetWidthJNI(long p0,float p1);
    public static native void jni_YGNodeStyleSetWidthPercentJNI(long p0,float p1);
}
