package com.kwai.video.krtc.render.GLDrawer$GLDrawerFrame;
import java.lang.Object;

public class GLDrawer$GLDrawerFrame	// class@0007d8
{
    public int bitsPerComp;
    public float blurSigma;
    public int blurSize;
    public int colorSpace;
    public int fboH;
    public int fboId;
    public int fboTexId;
    public int fboTgtId;
    public int fboW;
    public boolean flip;
    public int format;
    public int height;
    public float hqThreshold;
    public int hqType;
    public float[] matrix;
    public boolean mirror;
    public boolean needBind;
    public byte[] plane0;
    public byte[] plane1;
    public byte[] plane2;
    public boolean redrawIsNeed;
    public float regressAlpha;
    public int rotation;
    public float scaleFactor;
    public int scaleMode;
    public int shaderType;
    public int stride0;
    public int stride1;
    public int stride2;
    public int texType;
    public int textureId;
    public float translateX;
    public float translateY;
    public int viewH;
    public int viewW;
    public int viewX;
    public int viewY;
    public int width;

    public void GLDrawer$GLDrawerFrame(int p0,int p1,float[] p2,int p3,int p4,int p5,int p6,int p7,int p8,int p9,boolean p10,boolean p11){
       super();
       this.shaderType = 0;
       this.colorSpace = 0;
       this.format = 0;
       this.texType = 0;
       this.textureId = 0;
       this.plane0 = null;
       this.plane1 = null;
       this.plane2 = null;
       this.stride0 = 0;
       this.stride1 = 0;
       this.stride2 = 0;
       this.bitsPerComp = 8;
       this.rotation = 0;
       this.width = 0;
       this.height = 0;
       this.viewX = 0;
       this.viewY = 0;
       this.viewW = 0;
       this.viewH = 0;
       this.translateX = 0;
       this.translateY = 0;
       this.scaleFactor = 0x3f800000;
       this.flip = false;
       this.mirror = false;
       this.matrix = null;
       this.scaleMode = 0;
       this.fboId = 0;
       this.needBind = false;
       this.fboW = 0;
       this.fboH = 0;
       this.fboTgtId = 0;
       this.fboTexId = 0;
       this.hqType = 0;
       this.hqThreshold = 2.00f;
       this.blurSize = 3;
       this.blurSigma = 0x3f800000;
       this.regressAlpha = 0x3f99999a;
       this.redrawIsNeed = false;
       this.format = 7;
       this.texType = p0;
       this.textureId = p1;
       this.rotation = p3;
       this.matrix = p2;
       this.width = p4;
       this.height = p5;
       this.viewX = p6;
       this.viewY = p7;
       this.viewW = p8;
       this.viewH = p9;
       this.flip = p10;
       this.mirror = p11;
    }
    public void GLDrawer$GLDrawerFrame(int p0,int p1,byte[][] p2,int[] p3,float[] p4,int p5,int p6,int p7,int p8,int p9,int p10,int p11,boolean p12,boolean p13){
       int i = this;
       int i1 = p0;
       super();
       i.shaderType = 0;
       i.colorSpace = 0;
       i.format = 0;
       i.texType = 0;
       i.textureId = 0;
       i.plane0 = null;
       i.plane1 = null;
       i.plane2 = null;
       i.stride0 = 0;
       i.stride1 = 0;
       i.stride2 = 0;
       i.bitsPerComp = 8;
       i.rotation = 0;
       i.width = 0;
       i.height = 0;
       i.viewX = 0;
       i.viewY = 0;
       i.viewW = 0;
       i.viewH = 0;
       i.translateX = 0;
       i.translateY = 0;
       float f = 0x3f800000;
       i.scaleFactor = f;
       i.flip = false;
       i.mirror = false;
       i.matrix = null;
       i.scaleMode = 0;
       i.fboId = 0;
       i.needBind = false;
       i.fboW = 0;
       i.fboH = 0;
       i.fboTgtId = 0;
       i.fboTexId = 0;
       i.hqType = 0;
       i.hqThreshold = 2.00f;
       i.blurSize = 3;
       i.blurSigma = f;
       i.regressAlpha = 0x3f99999a;
       i.redrawIsNeed = false;
       i.format = i1;
       i.plane0 = p2[0];
       i.stride0 = p3[0];
       if (i1 <= 2) {
          i.plane1 = p2[1];
          i.stride1 = p3[1];
          if (!i1) {
             i.plane2 = p2[2];
             i.stride2 = p3[2];
          }
          i.colorSpace = p1;
       }
       i.rotation = p5;
       i.matrix = p4;
       i.width = p6;
       i.height = p7;
       i.viewX = p8;
       i.viewY = p9;
       i.viewW = p10;
       i.viewH = p11;
       i.flip = p12;
       i.mirror = p13;
       return;
    }
}
