package com.kwai.social.startup.reminder.model.IMConfigInfo;
import java.io.Serializable;
import java.lang.Object;
import java.lang.String;
import java.lang.Class;
import com.kwai.robust.PatchProxy;
import com.kwai.robust.PatchProxyResult;
import java.lang.StringBuilder;

public class IMConfigInfo implements Serializable	// class@000f58
{
    public boolean enableIMImageCompressOptimize;
    public boolean enableIMSceneMonitor;
    public long imSceneMonitorDelayMillis;
    public long imSceneMonitorInterval;
    public int mBatchGetBasicReqMaxSize;
    public boolean mCallResetStateWhenNetworkRecovery;
    public int mCallVideoFps;
    public CallVideoResolution mCallVideoResolution;
    public Map mCategoryAggregationConfig;
    public List mChatOnlineStateAutoRefreshConfig;
    public boolean mCloseImRtcNotificationInterceptor;
    public List mConversationDetailWhitelist;
    public double mConversationListRefreshOnlineStatusDelay;
    public Map mCustomEmotionIcon;
    public Map mCustomerServiceChatDetailConfig;
    public boolean mDisableAdoptContextTrack;
    public boolean mDisableImVideoChatRestoreLastBeauty;
    public boolean mDisableKeyboardHeightCheck;
    public boolean mDisableOfficialEmotion;
    public boolean mDisableSyncInBackground;
    public EmotionSearchConfig mEmotionSearchConfig;
    public List mEnableAutoRefreshGroupMemberOnlineConfig;
    public boolean mEnableBlockRequestCallForLastEndedCall;
    public boolean mEnableBugFixLog;
    public boolean mEnableChatListRefreshOptimize;
    public List mEnableChatQuickTabSubbiz;
    public boolean mEnableConversationListScrollOpt;
    public boolean mEnableEmotionMessageOptimize;
    public boolean mEnableFloatWindowExtraYOffset;
    public boolean mEnableForceRefreshAnonymousTokenWhenEmpty;
    public boolean mEnableGroupWhatsUp;
    public boolean mEnableIMAudio;
    public boolean mEnableIMBigEmotionAddToFavorite;
    public boolean mEnableIMOnlineStateOptimize;
    public boolean mEnableIMRTCQosLog;
    public boolean mEnableIMRtcFullScreenPush;
    public boolean mEnableIMSDKDeleteAbnormalMsg;
    public boolean mEnableIMSharePhotoNewStyle;
    public boolean mEnableImMagicRenderViewTimeOut;
    public boolean mEnableImRtcCameraPerfReport;
    public boolean mEnableImRtcOutPushRingVibrate;
    public boolean mEnableImVideoChatBeauty;
    public boolean mEnableImVideoChatFilter;
    public boolean mEnableImVideoChatMagicFace;
    public boolean mEnableImVideoChatMakeup;
    public boolean mEnableImVideoChatPrettify;
    public boolean mEnableImsdkFTSCompatibilityCollect;
    public boolean mEnableInitIMFromPushImmediately;
    public boolean mEnableMessageChatPageLaunchOptimize;
    public boolean mEnableMessageChatPageLaunchOptimizeV2;
    public boolean mEnableMessageSearch;
    public boolean mEnableMsgLocateAnim;
    public boolean mEnableNewCallMessageStyle;
    public boolean mEnableNewMsgCacheSeqConsecutive;
    public boolean mEnableNewWhatsUpQuickBarUI;
    public boolean mEnableOnlineDebugLog;
    public boolean mEnablePhotoCardPLCShowMerchant;
    public boolean mEnablePhotoNowTimeInQuickBar;
    public boolean mEnablePreloadOfficialBigEmotion;
    public boolean mEnablePrivateMessageListRealTimeRefresh;
    public boolean mEnableReactionShowGif;
    public boolean mEnableReplaceCustomEmotionIcon;
    public int mEnableRtcCallingSharePhoto;
    public boolean mEnableSendLatestVisitedPhoto;
    public boolean mEnableSendOriginalImage;
    public boolean mEnableSyncConfigOptimize;
    public boolean mEnableUnfollowSendMessageLimit;
    public boolean mEnableUpdateMsgLocalInfoWhenInsert;
    public boolean mEnableWhatsUp;
    public boolean mEnableWhatsUpBackupTips;
    public List mGroupOnlineEnableTypes;
    public GroupOnlineFetchConfig mGroupOnlineFetchConfig;
    public int mGroupWhatsUpABConfig;
    public boolean mHasRecommendedSession;
    public boolean mIMEnableShareToFollow;
    public boolean mIMMoreMsgTypeToFollow;
    public IMPluginLoggerConfig mIMPluginLoggerConfig;
    public IMPhotoMsgQuickReplyConfig mIMQuickReplyConfig;
    public IMVideoTalkConfig mIMVideoTalkConfig;
    public ImAudioRecordAutoResumeConfig mImAudioRecordAutoResumeConfig;
    public boolean mImEnableRequestPhotoStates;
    public ImPhotoConsumeEmotionsGuideConfig mImPhotoConsumeEmotionsGuideConfig;
    public int mImQuickBarAb;
    public QuickBarDefaultConfig mImQuickBarDefaultConfig;
    public int mImQuickBarMaxCaches;
    public int mImageThumbDisplayMaxSize;
    public IMInAppAddedUnreadConfig mInAppAddedUnreadMessageCountConfig;
    public InAppPushRestrainConfig mInAppPushRestrainConfig;
    public Map mIntimateRelationStyleConfig;
    public boolean mInvalidPostEntryForbidden;
    public boolean mIsBanUserMessageInvisible;
    public String mKtraceConfig;
    public LatestVisitedQuickSendConfig mLatestVisitedQuickSendConfig;
    public IMMagicFaceConfig mMagicFaceConfig;
    public int mMaxShareUserCount;
    public float mMediaMessageMonitorRate;
    public int mMessagePluginExpVersion;
    public int mMessagePluginLoadType;
    public MessageSearchConfig mMessageSearchConfig;
    public long mMessageUploadMaxSize;
    public int mMissCallPermissionGuideMaxTimes;
    public OnlineStatusCacheConfig mOnlineStatusCacheConfig;
    public PageLazyInitConfig mPageLazyInitConfig;
    public List mPhotoCardPLCSupportBizTypes;
    public PictureQuickSendConfig mPictureQuickSendConfig;
    public PokeResourceConfig mPokeResourceConfig;
    public long mPreloadOfficialBigEmotionLimitCount;
    public int mPrivateGroupMaxUnconfirmedInviteMemberCount;
    public int mPublicGroupMaxUnconfirmedInviteMemberCount;
    public double mRTCCallMediaVolumeRatio;
    public List mReactionCommonEmotionBackup;
    public String mReactionDoubleTabEmoji;
    public Map mRedPointLabConfig;
    public boolean mReduceHandleThread;
    public boolean mResetReferenceOriginMsgTargetId;
    public long mSendEmotionMessageTimeCostThreshold;
    public SessionRedDotRestrainConfig mSessionRedDotRestrainConfig;
    public List mSessionTagEnabledSubbizs;
    public int mSessionUnreadCountKeepTime;
    public ShareActiveSessionIMConfig mShareActiveSessionIMConfig;
    public ShareHeapIMConfig mShareHeapIMConfig;
    public ShareIMConfig mShareIMConfig;
    public ShareIMIntimacyConfig mShareIMIntimacyConfig;
    public ShareIMRecoWeights mShareIMRecoWeights;
    public int mShareSessionCount;
    public long mSiXinServiceTokenIntervalSeconds;
    public StartupShortLinkPushConfig mStartupShortLinkPushConfig;
    public int mStrangerRecoCountLimit;
    public List mSupportQuickSendMsgTypes;
    public List mSupportSubBizs;
    public ThirdPartyConfigSwitch mThirdPartyConfigSwitch;
    public boolean mTopBarBindOnlineStatus;
    public int mUnfollowSendMessageCount;
    public Map mUnsupportedMsgTypeFallbacks;
    public long mVideoMessageMaxDuration;
    public VideoMessageSendingPermission mVideoMessageSendingPermission;
    public long mVoiceChangeToEarpieceDelay;
    public long mVoiceSensorEventIgnoreInterval;
    public long mWhatsUpExpireDurationMs;
    public static final long serialVersionUID = 0x8166bf4299a8cef9;

    public void IMConfigInfo(){
       super();
       this.mMessageUploadMaxSize = 500;
       this.imSceneMonitorInterval = 300;
       this.imSceneMonitorDelayMillis = 3000;
       this.enableIMImageCompressOptimize = false;
       this.mVoiceSensorEventIgnoreInterval = 0;
       this.mVoiceChangeToEarpieceDelay = 0;
       this.mBatchGetBasicReqMaxSize = 50;
    }
    public String toString(){
       Object obj = PatchProxy.apply(null, this, IMConfigInfo.class, "1");
       if (obj != PatchProxyResult.class) {
          return obj;
       }
       return "IMConfigInfo{mMaxShareUserCount="+this.mMaxShareUserCount+", mPokeResourceConfig="+this.mPokeResourceConfig+", mConversationDetailWhitelist="+this.mConversationDetailWhitelist+", mPrivateGroupMaxUnconfirmedInviteMemberCount="+this.mPrivateGroupMaxUnconfirmedInviteMemberCount+", mPublicGroupMaxUnconfirmedInviteMemberCount="+this.mPublicGroupMaxUnconfirmedInviteMemberCount+", mSiXinServiceTokenIntervalSeconds="+this.mSiXinServiceTokenIntervalSeconds+", mVideoMessageMaxDuration="+this.mVideoMessageMaxDuration+", mMessageUploadMaxSize="+this.mMessageUploadMaxSize+", mVideoMessageSendingPermission="+this.mVideoMessageSendingPermission+", mSupportSubBizs="+this.mSupportSubBizs+", mCustomerServiceChatDetailConfig="+this.mCustomerServiceChatDetailConfig+", enableIMSceneMonitor="+this.enableIMSceneMonitor+", imSceneMonitorInterval="+this.imSceneMonitorInterval+", imSceneMonitorDelayMillis="+this.imSceneMonitorDelayMillis+", enableIMImageCompressOptimize="+this.enableIMImageCompressOptimize+", mShareIMConfig="+this.mShareIMConfig+", mPictureQuickSendConfig="+this.mPictureQuickSendConfig+", mEnableChatQuickTabSubbiz="+this.mEnableChatQuickTabSubbiz+", mMediaMessageMonitorRate="+this.mMediaMessageMonitorRate+", mDisableSyncInBackground="+this.mDisableSyncInBackground+", mEnableBugFixLog="+this.mEnableBugFixLog+", mEnableSendLatestVisitedPhoto="+this.mEnableSendLatestVisitedPhoto+'}';
    }
}
