package com.kuaishou.android.model.ads.PhotoAdvertisement$AdData;
import java.io.Serializable;
import java.lang.Object;
import com.kuaishou.android.model.ads.PhotoAdvertisement$ActionbarInfo;
import com.kuaishou.android.model.ads.PhotoAdvertisement$HalfPageBannerInfo;
import com.kuaishou.android.model.ads.PhotoAdvertisement$MixBarInfo;
import com.kuaishou.android.model.ads.PhotoAdvertisement$AdSurveyInfo;
import java.util.HashMap;
import java.util.ArrayList;

public class PhotoAdvertisement$AdData implements Serializable	// class@0008a4
{
    public PhotoAdvertisement$ActionbarInfo mActionbarInfo;
    public PhotoAdvertisement$AdApkMd5Info mAdApkMd5Info;
    public PhotoAdvertisement$AdBottomBanner mAdBottomBannerInfo;
    public PhotoAdvertisement$AdBridgeInfo mAdBridgeInfo;
    public PhotoAdvertisement$AdCacheStrategyInfo mAdCacheInfo;
    public PhotoAdvertisement$AdCardTemplateInfo mAdCardTemplateInfo;
    public int mAdCoverPageButtonControl;
    public String mAdExposedInfo;
    public int mAdPageButtonControl;
    public PhotoAdvertisement$AdSurveyInfo mAdSurveyInfo;
    public PhotoAdvertisement$AdWeakData mAdWeakData;
    public PhotoAdvertisement$AdWebCardInfo mAdWebCardInfo;
    public AnimationVideoInfo mAnimationVideoInfo;
    public PhotoAdvertisement$AppDetailInfo mAppDetailInfo;
    public PhotoAdvertisement$AppLinkToastInfo mAppLinkToastInfo;
    public float mAppScore;
    public BrokenFrameInfo mBrokenFrameInfo;
    public PhotoAdvertisement$CaptionAdvertisementInfo mCaptionAdvertisementInfo;
    public PhotoAdvertisement$CommentActionBarInfo mCommentActionBarInfo;
    public PhotoAdvertisement$CommentEmojiInfo mCommentEmojiInfo;
    public PhotoAdvertisement$CommentTopBarInfo mCommentTopBarInfo;
    public PhotoAdvertisement$ConvertInfo mConvertInfo;
    public PhotoAdvertisement$CoronaBrandInfo mCoronaBrandInfo;
    public PhotoAdvertisement$CouponInfo mCouponInfo;
    public PhotoAdvertisement$CoverActionBarInfo mCoverActionbarInfo;
    public PhotoAdvertisement$CoverMediaInfo mCoverMediaInfo;
    public PhotoAdvertisement$CoverPlayEndInfo mCoverPlayEndInfo;
    public PhotoAdvertisement$CoverStickerInfo mCoverStickerInfo;
    public boolean mCreateByDefault;
    public PhotoAdvertisement$DanmakuInfo mDanmakuInfo;
    public boolean mDeepLinkFinishWebView;
    public boolean mDisableDSPSoftErrorMonitor;
    public int mDisplayInTopPageNum;
    public boolean mEnableAppDownloadPause;
    public boolean mEnableLeftSlideOpenLive;
    public int mEnableVpnInterception;
    public PhotoAdvertisement$ExitDialogInfo mExitDialogInfo;
    public PhotoAdvertisement$ExtraDisplayInfo mExtraDisplayInfo;
    public PhotoAdvertisement$FakeCommentInfo mFakeCommentInfo;
    public boolean mForbidAutoOpenApp;
    public PhotoAdvertisement$H5ControlInfo mH5ControlInfo;
    public String mH5Data;
    public String mH5Url;
    public PhotoAdvertisement$HalfLandingPageInfo mHalfLandingPageInfo;
    public PhotoAdvertisement$HalfPageBannerInfo mHalfPageBannerInfo;
    public PhotoAdvertisement$InspireAdInfo mInspireAdInfo;
    public PhotoAdvertisement$InstreamAdBarInfo mInstreamAdBarInfo;
    public PhotoAdvertisement$InteractionInfo mInteractionInfo;
    public String mIpAddress;
    public boolean mIsNegativeFilter;
    public boolean mIsOrderedApp;
    public List mItemClickItemList;
    public PhotoAdvertisement$ItemClickUrlGroup mItemClickUrls;
    public PhotoAdvertisement$JointInstreamAdBarInfo mJointInstreamAdBarInfo;
    public PhotoAdvertisement$JumpLiveInfo mJumpLiveInfo;
    public PhotoAdvertisement$LandingPageInfo mLandingPageInfo;
    public HashMap mLiveAdRerankContext;
    public String mLiveRouterScheme;
    public String mLiveStreamId;
    public final Map mLocalAdExposedMap;
    public String mMarketUri;
    public PhotoAdvertisement$MerchandiseInfo mMerchandiseInfo;
    public PhotoAdvertisement$MixBarInfo mMixBarInfo;
    public PhotoAdvertisement$NegativeMenuInfo mNegativeMenuInfo;
    public int mNewUserAgentStyle;
    public PhotoAdvertisement$NovelCardInfo mNovelBannerInfo;
    public PhotoAdvertisement$PendantInfo mPendantInfo;
    public PhotoAdvertisement$PlayEndInfo mPlayEndInfo;
    public PhotoAdvertisement$PlayPauseInfo mPlayPauseInfo;
    public List mPlayedReportRate;
    public List mPlayedReportTime;
    public List mPlayedTotalReportTime;
    public PhotoAdvertisement$PopARInfo mPopARInfo;
    public PhotoAdvertisement$PopPlayInfo mPopPlayInfo;
    public long mPosId;
    public PhotoAdvertisement$PrivacyOption mPrivacyOption;
    public PhotoAdvertisement$ProfileBottomBannerInfo mProfileBottomBannerInfo;
    public int mPutType;
    public HashMap mRateInfo;
    public PhotoAdvertisement$RequestEApiInfo mRequestEApiInfo;
    public PhotoAdvertisement$AdRerankInfo mRerankInfo;
    public PhotoAdvertisement$SearchBigvLive mSearchBigvLive;
    public PhotoAdvertisement$SearchBrandInfo mSearchBrandInfo;
    public PhotoAdvertisement$SearchExtraInfo mSearchExtraInfo;
    public String mSearchRecommendReason;
    public PhotoAdvertisement$SearchSuspendedBallInfo mSearchSuspendedBallInfo;
    public PhotoAdvertisement$ShareInfo mShareInfo;
    public boolean mShouldReplaceIpdx;
    public boolean mShowLiveIcon;
    public SideWindowInfo mSideWindowInfo;
    public SplashInfo mSplashInfo;
    public List mTkTemplateData;
    public PhotoAdvertisement$TkTemplateInfo mTkTemplateInfo;
    public PhotoAdvertisement$TopActionbarInfo mTopActionbarInfo;
    public PhotoAdvertisement$TopTagInfo mTopTagInfo;
    public PhotoAdvertisement$TryGameInfo mTryGameInfo;
    public PhotoAdvertisement$TvcInfo mTvcInfo;
    public int mUseTrackType;
    public PhotoAdvertisement$VideoClipInfo mVideoClipInfo;
    public List mVideoQUalityInfoList;
    public PhotoAdvertisement$WebViewNavigationBarInfo mWebViewNavigationBarInfo;
    public int mWebViewType;
    public PhotoAdvertisement$WidgetInfo mWidgetInfo;
    public static final long serialVersionUID = 0x4ce8b638171957be;

    public void PhotoAdvertisement$AdData(){
       super();
       this.mActionbarInfo = new PhotoAdvertisement$ActionbarInfo();
       this.mHalfPageBannerInfo = new PhotoAdvertisement$HalfPageBannerInfo();
       this.mMixBarInfo = new PhotoAdvertisement$MixBarInfo();
       this.mAdSurveyInfo = new PhotoAdvertisement$AdSurveyInfo();
       this.mLocalAdExposedMap = new HashMap();
       this.mEnableVpnInterception = 0;
       this.mTkTemplateData = new ArrayList();
       this.mDisableDSPSoftErrorMonitor = false;
    }
    public void PhotoAdvertisement$AdData(boolean p0){
       super();
       this.mActionbarInfo = new PhotoAdvertisement$ActionbarInfo();
       this.mHalfPageBannerInfo = new PhotoAdvertisement$HalfPageBannerInfo();
       this.mMixBarInfo = new PhotoAdvertisement$MixBarInfo();
       this.mAdSurveyInfo = new PhotoAdvertisement$AdSurveyInfo();
       this.mLocalAdExposedMap = new HashMap();
       this.mEnableVpnInterception = 0;
       this.mTkTemplateData = new ArrayList();
       this.mDisableDSPSoftErrorMonitor = false;
       this.mCreateByDefault = p0;
    }
    public boolean isAdPageButtonControlDisable(int p0){
       boolean b = ((this.mAdPageButtonControl & p0) == p0)? true: false;
       return b;
    }
}
