package fs3.g;
import tkd.b;
import com.smile.gifmaker.mvps.presenter.PresenterV2;
import java.lang.String;
import brd.t;
import java.util.List;
import com.kuaishou.merchant.api.live.sandeabiz.SandeaBizType;
import ps3.b;
import androidx.fragment.app.Fragment;
import com.kuaishou.merchant.api.core.model.Commodity;
import com.kuaishou.merchant.api.core.LiveMerchantBaseContext;
import erd.g;
import us3.f;
import crd.b;
import android.view.View;
import com.kwai.framework.model.user.UserInfo;
import com.kuaishou.merchant.api.core.model.MerchantInfo;
import android.app.Activity;
import java.util.Map;
import androidx.fragment.app.c;
import androidx.fragment.app.KwaiDialogFragment;
import ps3.a;
import o63.j;
import androidx.fragment.app.FragmentActivity;
import android.content.DialogInterface$OnShowListener;
import is3.b;

public interface abstract g implements b	// class@002940
{

    boolean BQ();
    PresenterV2 BW(boolean p0);
    PresenterV2 D(int p0);
    t FF(String p0,String p1,String p2,String p3,int p4);
    boolean GQ();
    List Ib();
    void Ix(SandeaBizType p0,String p1,boolean p2);
    b J9();
    b Kd(Fragment p0,Commodity p1,LiveMerchantBaseContext p2,int p3,g p4,f p5);
    List Na();
    void O7(View p0);
    b OC(String p0,String p1);
    PresenterV2 OL();
    List Qs();
    void T50(String p0);
    void W(String p0,UserInfo p1);
    void WN(MerchantInfo p0,String p1,Activity p2);
    t Xp(String p0,UserInfo p1);
    PresenterV2 ZT();
    Map a0();
    void aa(Activity p0,c p1,KwaiDialogFragment p2,String p3);
    List af();
    a bW();
    List bv();
    b c00(Fragment p0,Commodity p1,LiveMerchantBaseContext p2,int p3,g p4);
    void dm(String p0,long p1);
    j gb();
    boolean gc(String p0);
    List gz(boolean p0,boolean p1);
    int i1();
    List iv();
    b la(FragmentActivity p0,Commodity p1,LiveMerchantBaseContext p2,int p3,DialogInterface$OnShowListener p4,g p5);
    void mO(View p0);
    String nG();
    String p3();
    String qn(int p0,int p1);
    PresenterV2 qy(boolean p0);
    void tf(View p0);
    b x30();
}
