package pr4.k;
import com.google.protobuf.MessageLiteOrBuilder;
import java.lang.String;
import java.util.Map;
import com.kuaishou.protobuf.photo.funnel.Action;
import java.util.List;
import com.kuaishou.protobuf.photo.funnel.AiCutStat;
import com.kuaishou.protobuf.photo.funnel.AlbumStat;
import com.kuaishou.protobuf.photo.funnel.ViewClick;
import com.kuaishou.protobuf.photo.funnel.CoverStat;
import com.kuaishou.protobuf.photo.funnel.BeautyStat;
import com.kuaishou.protobuf.photo.funnel.BodyStat;
import com.kuaishou.protobuf.photo.funnel.FilterStat;
import com.kuaishou.protobuf.photo.funnel.MakeUpStat;
import com.kuaishou.protobuf.photo.funnel.MusicStat;
import com.kuaishou.protobuf.photo.funnel.EncodeStat;
import com.kuaishou.protobuf.photo.funnel.PageInfo;
import com.kuaishou.protobuf.photo.funnel.Performance;
import com.google.protobuf.ByteString;
import com.kuaishou.protobuf.photo.funnel.PublishStat;
import com.kuaishou.protobuf.photo.funnel.RecordStat;
import com.kuaishou.protobuf.photo.funnel.ResourceDownloadStat;
import com.kuaishou.protobuf.photo.funnel.StickerStat;
import com.kuaishou.protobuf.photo.funnel.SubtitleStat;
import com.kuaishou.protobuf.photo.funnel.TemplateStat;
import com.kuaishou.protobuf.photo.funnel.TextStat;

public interface abstract k implements MessageLiteOrBuilder	// class@002e10
{

    boolean containsAbValues(String p0);
    boolean containsPayloads(String p0);
    Map getAbValues();
    int getAbValuesCount();
    Map getAbValuesMap();
    String getAbValuesOrDefault(String p0,String p1);
    String getAbValuesOrThrow(String p0);
    Action getActions(int p0);
    int getActionsCount();
    List getActionsList();
    AiCutStat getAiCut();
    AlbumStat getAlbum();
    ViewClick getClickEvents(int p0);
    int getClickEventsCount();
    List getClickEventsList();
    CoverStat getCover();
    BeautyStat getEditBeauty();
    BodyStat getEditBody();
    FilterStat getEditFilter();
    MakeUpStat getEditMakeup();
    MusicStat getEditMusic();
    EncodeStat getEncode();
    boolean getIsEditEnter();
    boolean getIsPhoto();
    PageInfo getPages(int p0);
    int getPagesCount();
    List getPagesList();
    Map getPayloads();
    int getPayloadsCount();
    Map getPayloadsMap();
    String getPayloadsOrDefault(String p0,String p1);
    String getPayloadsOrThrow(String p0);
    Performance getPerfs(int p0);
    int getPerfsCount();
    List getPerfsList();
    String getPreTaskId();
    ByteString getPreTaskIdBytes();
    PublishStat getPublish();
    RecordStat getRecord();
    ResourceDownloadStat getResourceDownloadStat(int p0);
    int getResourceDownloadStatCount();
    List getResourceDownloadStatList();
    String getSourcePath(int p0);
    ByteString getSourcePathBytes(int p0);
    int getSourcePathCount();
    List getSourcePathList();
    StickerStat getSticker();
    SubtitleStat getSubtitle();
    String getTaskId();
    ByteString getTaskIdBytes();
    TemplateStat getTemplate();
    TextStat getText();
    long getType();
    boolean hasAiCut();
    boolean hasAlbum();
    boolean hasCover();
    boolean hasEditBeauty();
    boolean hasEditBody();
    boolean hasEditFilter();
    boolean hasEditMakeup();
    boolean hasEditMusic();
    boolean hasEncode();
    boolean hasPublish();
    boolean hasRecord();
    boolean hasSticker();
    boolean hasSubtitle();
    boolean hasTemplate();
    boolean hasText();
}
