package com.kwai.video.wayne.player.main.IMediaPlayerApi;
import com.kwai.video.player.kwai_player.AspectAwesomeCache;
import com.kwai.video.player.kwai_player.AspectKwaiVodAdaptive;
import java.lang.String;
import android.graphics.Bitmap;
import com.kwai.player.qos.KwaiQosInfo;
import android.view.Surface;
import android.view.MotionEvent;
import android.graphics.SurfaceTexture;

public interface abstract IMediaPlayerApi	// class@000d62
{

    boolean checkCanStartPlay();
    void enableLoopOnBlock(int p0,int p1,long p2);
    boolean getAPJoySoundSwitchStatus();
    AspectAwesomeCache getAspectAwesomeCache();
    AspectKwaiVodAdaptive getAspectVodAdaptive();
    String getBriefVodStatJson();
    long getCurrentPosition();
    String getCurrentTranscodeType();
    long getCurrentVideoPosition();
    int getDownloadedPercent();
    long getDuration();
    long getFirstVideoPts();
    long getKernalPlayedDuration();
    long getLastVideoPts();
    int getOrientationDegrees();
    String getPlayerTsJson();
    Bitmap getScreenShot();
    float getSpeed(float p0);
    KwaiQosInfo getStreamQosInfo();
    Surface getSurface();
    int getVideoAlphaType();
    int getVideoHeight();
    int getVideoSarDen();
    int getVideoSarNum();
    int getVideoWidth();
    String getVodAdaptiveCacheKey();
    int getVodAdaptiveRepID();
    String getVodAdaptiveUrl();
    String getVodStatJson();
    boolean handleTouchEvent(MotionEvent p0);
    boolean isMediaPlayerValid();
    boolean isRepresentationEnableAdaptive(int p0);
    void pause();
    void prepareAsync();
    void registerSensorEvent();
    void releaseAsync();
    void reset();
    void seekTo(long p0);
    void setAPJoySoundSwitchStatus(boolean p0);
    void setAbLoop(long p0,long p1,int p2);
    void setAbLoop(long p0,long p1,int p2,boolean p3);
    void setCencKey(String p0);
    void setDrmKeyInfo(String p0,int p1,int p2);
    void setEnableAudioSpectrum(boolean p0);
    void setInteractiveMode(int p0);
    void setKwaivppExtJson(int p0,String p1);
    void setKwaivppFilters(int p0,String p1);
    void setLastTryFlag(boolean p0);
    void setLooping(boolean p0);
    void setMediacodecDummyEnable(boolean p0);
    void setPlayerMute(boolean p0);
    void setScreenOnWhilePlaying(boolean p0);
    void setSpeed(float p0);
    void setSurfaceTexture(SurfaceTexture p0);
    void setTag1(int p0);
    void setTone(int p0);
    void setVideoScalingMode(int p0);
    void setViewSize(int p0,int p1);
    void setVolume(float p0,float p1);
    void start();
    void stepFrame();
    void stop();
    void unRegisterSensorEvent();
    void updateAdaptiveMode(int p0);
    void updateRepresentationAdaptiveFlag(int p0,boolean p1);
}
