package com.kwai.video.wayne.player.main.IPlayerListener;
import com.kwai.video.cache.AwesomeCacheCallback;
import com.kwai.video.player.IMediaPlayer$OnABLoopEndOfCounterListener;
import com.kwai.video.player.IMediaPlayer$OnBufferingUpdateListener;
import com.kwai.video.player.IMediaPlayer$OnCompletionListener;
import com.kwai.video.player.IMediaPlayer$OnDecodeFirstFrameListener;
import com.kwai.video.player.IMediaPlayer$OnErrorListener;
import com.kwai.video.player.IMediaPlayer$OnFftDataCaptureListener;
import com.kwai.video.wayne.player.listeners.OnFirstFrameListener;
import com.kwai.video.player.IMediaPlayer$OnInfoListener;
import com.kwai.video.wayne.player.listeners.OnPauseListener;
import com.kwai.video.wayne.player.listeners.OnPlayerLoadingChangedListener;
import com.kwai.video.wayne.player.listeners.OnBuildDataChangedListener;
import com.kwai.video.player.IMediaPlayer$OnPreparedListener;
import com.kwai.video.wayne.player.listeners.OnProgressChangeListener;
import com.kwai.video.wayne.player.listeners.OnQualityChangeListener;
import com.kwai.video.player.IMediaPlayer$OnRenderingStartListener;
import com.kwai.video.player.IMediaPlayer$OnSeekCompleteListener;
import com.kwai.video.wayne.player.listeners.OnSeekListener;
import com.kwai.video.wayne.player.listeners.OnStartListener;
import com.kwai.video.wayne.player.listeners.OnStopListener;
import com.kwai.video.wayne.player.listeners.OnSurfaceChangedListener;
import com.kwai.video.player.IMediaPlayer$OnVideoSizeChangedListener;
import com.kwai.video.wayne.player.listeners.OnWayneErrorListener;
import com.kwai.video.wayne.player.listeners.OnPlayerStateChangedListener;
import com.kwai.video.wayne.player.listeners.CacheListener;
import com.kwai.video.player.CdnEventLogCallback;
import com.kwai.video.player.IKwaiRepresentationListener;
import com.kwai.video.player.OnQosEventInfoListener;

public interface abstract IPlayerListener	// class@000d63
{

    void addAwesomeCallBack(AwesomeCacheCallback p0);
    void addAwesomeNoClearCallBack(AwesomeCacheCallback p0);
    void addOnABLoopEndOfCounterListener(IMediaPlayer$OnABLoopEndOfCounterListener p0);
    void addOnBufferingUpdateListener(IMediaPlayer$OnBufferingUpdateListener p0);
    void addOnCompletionListener(IMediaPlayer$OnCompletionListener p0);
    void addOnDecodeFirstFrameListener(IMediaPlayer$OnDecodeFirstFrameListener p0);
    void addOnErrorListener(IMediaPlayer$OnErrorListener p0);
    void addOnFftDataCaptureListener(IMediaPlayer$OnFftDataCaptureListener p0);
    void addOnFirstFrameListener(OnFirstFrameListener p0);
    void addOnInfoListener(IMediaPlayer$OnInfoListener p0);
    void addOnPauseListener(OnPauseListener p0);
    void addOnPlayerLoadingChangedListener(OnPlayerLoadingChangedListener p0);
    void addOnPlayerVodBuildDataChangedListener(OnBuildDataChangedListener p0);
    void addOnPreparedListener(IMediaPlayer$OnPreparedListener p0);
    void addOnProgressChangeListener(OnProgressChangeListener p0);
    void addOnQualityChangedListener(OnQualityChangeListener p0);
    void addOnRenderingStartListener(IMediaPlayer$OnRenderingStartListener p0);
    void addOnSeekCompleteListener(IMediaPlayer$OnSeekCompleteListener p0);
    void addOnSeekListener(OnSeekListener p0);
    void addOnStartListener(OnStartListener p0);
    void addOnStopListener(OnStopListener p0);
    void addOnSurfaceChangedListener(OnSurfaceChangedListener p0);
    void addOnVideoSizeChangedListener(IMediaPlayer$OnVideoSizeChangedListener p0);
    void addOnWayneErrorListener(OnWayneErrorListener p0);
    void registerPlayerStateChangedListener(OnPlayerStateChangedListener p0);
    void removeAwesomeCallBack(AwesomeCacheCallback p0);
    void removeAwesomeNoClearCallBack(AwesomeCacheCallback p0);
    void removeOnABLoopEndOfCounterListener(IMediaPlayer$OnABLoopEndOfCounterListener p0);
    void removeOnBufferingUpdateListener(IMediaPlayer$OnBufferingUpdateListener p0);
    void removeOnCompletionListener(IMediaPlayer$OnCompletionListener p0);
    void removeOnDecodeFirstFrameListener(IMediaPlayer$OnDecodeFirstFrameListener p0);
    void removeOnErrorListener(IMediaPlayer$OnErrorListener p0);
    void removeOnFftDataCaptureListener(IMediaPlayer$OnFftDataCaptureListener p0);
    void removeOnFirstFrameListener(OnFirstFrameListener p0);
    void removeOnInfoListener(IMediaPlayer$OnInfoListener p0);
    void removeOnPauseListener(OnPauseListener p0);
    void removeOnPlayerLoadingChangedListener(OnPlayerLoadingChangedListener p0);
    void removeOnPlayerVodBuildDataChangedListener(OnBuildDataChangedListener p0);
    void removeOnPreparedListener(IMediaPlayer$OnPreparedListener p0);
    void removeOnProgressChangeListener(OnProgressChangeListener p0);
    void removeOnQualityChangedListener(OnQualityChangeListener p0);
    void removeOnRenderingStartListener(IMediaPlayer$OnRenderingStartListener p0);
    void removeOnSeekCompleteListener(IMediaPlayer$OnSeekCompleteListener p0);
    void removeOnSeekListener(OnSeekListener p0);
    void removeOnStartListener(OnStartListener p0);
    void removeOnStopListener(OnStopListener p0);
    void removeOnSurfaceChangedListener(OnSurfaceChangedListener p0);
    void removeOnVideoSizeChangedListener(IMediaPlayer$OnVideoSizeChangedListener p0);
    void removeOnWayneErrorListener(OnWayneErrorListener p0);
    void setCacheSessionListener(CacheListener p0);
    void setCdnEventLogCallBack(CdnEventLogCallback p0);
    void setKwaiAudioRepresentationListener(IKwaiRepresentationListener p0);
    void setOnQosEventInfoListener(OnQosEventInfoListener p0);
    void unregisterPlayerStateChangedListener(OnPlayerStateChangedListener p0);
}
