package com.google.gson.internal.bind.TypeAdapters;
import com.google.gson.internal.bind.TypeAdapters$1;
import com.google.gson.TypeAdapter;
import java.lang.Class;
import zk.j;
import com.google.gson.internal.bind.TypeAdapters$2;
import java.util.BitSet;
import com.google.gson.internal.bind.TypeAdapters$3;
import com.google.gson.internal.bind.TypeAdapters$4;
import java.lang.Boolean;
import com.google.gson.internal.bind.TypeAdapters$5;
import java.lang.Byte;
import com.google.gson.internal.bind.TypeAdapters$6;
import java.lang.Short;
import com.google.gson.internal.bind.TypeAdapters$7;
import java.lang.Integer;
import com.google.gson.internal.bind.TypeAdapters$8;
import java.util.concurrent.atomic.AtomicInteger;
import com.google.gson.internal.bind.TypeAdapters$9;
import java.util.concurrent.atomic.AtomicBoolean;
import com.google.gson.internal.bind.TypeAdapters$10;
import java.util.concurrent.atomic.AtomicIntegerArray;
import com.google.gson.internal.bind.TypeAdapters$11;
import com.google.gson.internal.bind.TypeAdapters$12;
import com.google.gson.internal.bind.TypeAdapters$13;
import com.google.gson.internal.bind.TypeAdapters$14;
import java.lang.Number;
import com.google.gson.internal.bind.TypeAdapters$15;
import java.lang.Character;
import com.google.gson.internal.bind.TypeAdapters$16;
import com.google.gson.internal.bind.TypeAdapters$17;
import com.google.gson.internal.bind.TypeAdapters$18;
import java.lang.String;
import com.google.gson.internal.bind.TypeAdapters$19;
import java.lang.StringBuilder;
import com.google.gson.internal.bind.TypeAdapters$20;
import java.lang.StringBuffer;
import com.google.gson.internal.bind.TypeAdapters$21;
import java.net.URL;
import com.google.gson.internal.bind.TypeAdapters$22;
import java.net.URI;
import com.google.gson.internal.bind.TypeAdapters$23;
import java.net.InetAddress;
import com.google.gson.internal.bind.TypeAdapters$24;
import java.util.UUID;
import com.google.gson.internal.bind.TypeAdapters$25;
import java.util.Currency;
import com.google.gson.internal.bind.TypeAdapters$26;
import com.google.gson.internal.bind.TypeAdapters$27;
import java.util.Calendar;
import java.util.GregorianCalendar;
import com.google.gson.internal.bind.TypeAdapters$34;
import com.google.gson.internal.bind.TypeAdapters$28;
import java.util.Locale;
import com.google.gson.internal.bind.TypeAdapters$29;
import com.google.gson.JsonElement;
import com.google.gson.internal.bind.TypeAdapters$30;
import el.a;
import com.google.gson.internal.bind.TypeAdapters$31;
import com.google.gson.internal.bind.TypeAdapters$32;
import com.google.gson.internal.bind.TypeAdapters$33;
import com.google.gson.internal.bind.TypeAdapters$35;

public final class TypeAdapters	// class@0005b1
{
    public static final TypeAdapter A;
    public static final TypeAdapter B;
    public static final TypeAdapter C;
    public static final j D;
    public static final TypeAdapter E;
    public static final j F;
    public static final TypeAdapter G;
    public static final j H;
    public static final TypeAdapter I;
    public static final j J;
    public static final TypeAdapter K;
    public static final j L;
    public static final TypeAdapter M;
    public static final j N;
    public static final TypeAdapter O;
    public static final j P;
    public static final TypeAdapter Q;
    public static final j R;
    public static final j S;
    public static final TypeAdapter T;
    public static final j U;
    public static final TypeAdapter V;
    public static final j W;
    public static final TypeAdapter X;
    public static final j Y;
    public static final j Z;
    public static final TypeAdapter a;
    public static final j b;
    public static final TypeAdapter c;
    public static final j d;
    public static final TypeAdapter e;
    public static final TypeAdapter f;
    public static final j g;
    public static final TypeAdapter h;
    public static final j i;
    public static final TypeAdapter j;
    public static final j k;
    public static final TypeAdapter l;
    public static final j m;
    public static final TypeAdapter n;
    public static final j o;
    public static final TypeAdapter p;
    public static final j q;
    public static final TypeAdapter r;
    public static final j s;
    public static final TypeAdapter t;
    public static final TypeAdapter u;
    public static final TypeAdapter v;
    public static final TypeAdapter w;
    public static final j x;
    public static final TypeAdapter y;
    public static final j z;

    static {
       TypeAdapter typeAdapter = new TypeAdapters$1().nullSafe();
       TypeAdapters.a = typeAdapter;
       TypeAdapters.b = TypeAdapters.b(Class.class, typeAdapter);
       typeAdapter = new TypeAdapters$2().nullSafe();
       TypeAdapters.c = typeAdapter;
       TypeAdapters.d = TypeAdapters.b(BitSet.class, typeAdapter);
       TypeAdapters$3 u3 = new TypeAdapters$3();
       TypeAdapters.e = u3;
       TypeAdapters.f = new TypeAdapters$4();
       TypeAdapters.g = TypeAdapters.c(Boolean.TYPE, Boolean.class, u3);
       TypeAdapters$5 u5 = new TypeAdapters$5();
       TypeAdapters.h = u5;
       TypeAdapters.i = TypeAdapters.c(Byte.TYPE, Byte.class, u5);
       TypeAdapters$6 u6 = new TypeAdapters$6();
       TypeAdapters.j = u6;
       TypeAdapters.k = TypeAdapters.c(Short.TYPE, Short.class, u6);
       TypeAdapters$7 u7 = new TypeAdapters$7();
       TypeAdapters.l = u7;
       TypeAdapters.m = TypeAdapters.c(Integer.TYPE, Integer.class, u7);
       typeAdapter = new TypeAdapters$8().nullSafe();
       TypeAdapters.n = typeAdapter;
       TypeAdapters.o = TypeAdapters.b(AtomicInteger.class, typeAdapter);
       typeAdapter = new TypeAdapters$9().nullSafe();
       TypeAdapters.p = typeAdapter;
       TypeAdapters.q = TypeAdapters.b(AtomicBoolean.class, typeAdapter);
       typeAdapter = new TypeAdapters$10().nullSafe();
       TypeAdapters.r = typeAdapter;
       TypeAdapters.s = TypeAdapters.b(AtomicIntegerArray.class, typeAdapter);
       TypeAdapters.t = new TypeAdapters$11();
       TypeAdapters.u = new TypeAdapters$12();
       TypeAdapters.v = new TypeAdapters$13();
       TypeAdapters$14 u14 = new TypeAdapters$14();
       TypeAdapters.w = u14;
       TypeAdapters.x = TypeAdapters.b(Number.class, u14);
       TypeAdapters$15 u15 = new TypeAdapters$15();
       TypeAdapters.y = u15;
       TypeAdapters.z = TypeAdapters.c(Character.TYPE, Character.class, u15);
       TypeAdapters$16 u16 = new TypeAdapters$16();
       TypeAdapters.A = u16;
       TypeAdapters.B = new TypeAdapters$17();
       TypeAdapters.C = new TypeAdapters$18();
       TypeAdapters.D = TypeAdapters.b(String.class, u16);
       TypeAdapters$19 u19 = new TypeAdapters$19();
       TypeAdapters.E = u19;
       TypeAdapters.F = TypeAdapters.b(StringBuilder.class, u19);
       TypeAdapters$20 u20 = new TypeAdapters$20();
       TypeAdapters.G = u20;
       TypeAdapters.H = TypeAdapters.b(StringBuffer.class, u20);
       TypeAdapters$21 u21 = new TypeAdapters$21();
       TypeAdapters.I = u21;
       TypeAdapters.J = TypeAdapters.b(URL.class, u21);
       TypeAdapters$22 u22 = new TypeAdapters$22();
       TypeAdapters.K = u22;
       TypeAdapters.L = TypeAdapters.b(URI.class, u22);
       TypeAdapters$23 u23 = new TypeAdapters$23();
       TypeAdapters.M = u23;
       TypeAdapters.N = TypeAdapters.d(InetAddress.class, u23);
       TypeAdapters$24 u24 = new TypeAdapters$24();
       TypeAdapters.O = u24;
       TypeAdapters.P = TypeAdapters.b(UUID.class, u24);
       typeAdapter = new TypeAdapters$25().nullSafe();
       TypeAdapters.Q = typeAdapter;
       TypeAdapters.R = TypeAdapters.b(Currency.class, typeAdapter);
       TypeAdapters.S = new TypeAdapters$26();
       TypeAdapters$27 u27 = new TypeAdapters$27();
       TypeAdapters.T = u27;
       TypeAdapters.U = new TypeAdapters$34(Calendar.class, GregorianCalendar.class, u27);
       TypeAdapters$28 u28 = new TypeAdapters$28();
       TypeAdapters.V = u28;
       TypeAdapters.W = TypeAdapters.b(Locale.class, u28);
       TypeAdapters$29 u29 = new TypeAdapters$29();
       TypeAdapters.X = u29;
       TypeAdapters.Y = TypeAdapters.d(JsonElement.class, u29);
       TypeAdapters.Z = new TypeAdapters$30();
    }
    public static j a(a p0,TypeAdapter p1){
       return new TypeAdapters$31(p0, p1);
    }
    public static j b(Class p0,TypeAdapter p1){
       return new TypeAdapters$32(p0, p1);
    }
    public static j c(Class p0,Class p1,TypeAdapter p2){
       return new TypeAdapters$33(p0, p1, p2);
    }
    public static j d(Class p0,TypeAdapter p1){
       return new TypeAdapters$35(p0, p1);
    }
}
