package com.kuaishou.live.core.show.photoalbum.cropper.CropImageOptions;
import android.os.Parcelable;
import com.kuaishou.live.core.show.photoalbum.cropper.CropImageOptions$a;
import java.lang.Object;
import android.content.res.Resources;
import android.util.DisplayMetrics;
import cw9.c;
import com.kuaishou.live.core.show.photoalbum.cropper.CropImageView$CropShape;
import android.util.TypedValue;
import com.kuaishou.live.core.show.photoalbum.cropper.CropImageView$Guidelines;
import com.kuaishou.live.core.show.photoalbum.cropper.CropImageView$ScaleType;
import android.graphics.Color;
import android.net.Uri;
import android.graphics.Bitmap$CompressFormat;
import com.kuaishou.live.core.show.photoalbum.cropper.CropImageView$RequestSizeOptions;
import android.os.Parcel;
import android.text.TextUtils;
import android.os.Parcelable$Creator;
import java.lang.CharSequence;
import java.lang.ClassLoader;
import java.lang.Class;
import java.lang.String;
import android.graphics.Rect;
import com.kwai.robust.PatchProxy;
import java.lang.Integer;
import java.lang.Enum;

public class CropImageOptions implements Parcelable	// class@000d56
{
    public int A;
    public int B;
    public int C;
    public int D;
    public CharSequence E;
    public int F;
    public Uri G;
    public Bitmap$CompressFormat H;
    public int I;
    public int J;
    public int K;
    public CropImageView$RequestSizeOptions L;
    public boolean M;
    public Rect N;
    public int O;
    public boolean P;
    public boolean Q;
    public boolean R;
    public int S;
    public boolean T;
    public boolean U;
    public CropImageView$CropShape b;
    public float c;
    public float d;
    public CropImageView$Guidelines e;
    public CropImageView$ScaleType f;
    public boolean g;
    public boolean h;
    public boolean i;
    public boolean j;
    public int k;
    public float l;
    public boolean m;
    public int n;
    public int o;
    public float p;
    public int q;
    public float r;
    public float s;
    public float t;
    public int u;
    public float v;
    public int w;
    public int x;
    public int y;
    public int z;
    public static final Parcelable$Creator CREATOR;

    static {
       CropImageOptions.CREATOR = new CropImageOptions$a();
    }
    public void CropImageOptions(){
       super();
       DisplayMetrics uDisplayMetr = c.c(Resources.getSystem());
       this.b = CropImageView$CropShape.RECTANGLE;
       this.c = TypedValue.applyDimension(1, 3.00f, uDisplayMetr);
       this.d = TypedValue.applyDimension(1, 24.00f, uDisplayMetr);
       this.e = CropImageView$Guidelines.ON_TOUCH;
       this.f = CropImageView$ScaleType.FIT_CENTER;
       this.g = true;
       this.h = true;
       this.i = true;
       this.j = false;
       this.k = 4;
       this.l = 0.10f;
       this.m = false;
       this.n = 1;
       this.o = 1;
       this.p = TypedValue.applyDimension(1, 3.00f, uDisplayMetr);
       this.q = Color.argb(170, 255, 255, 255);
       this.r = TypedValue.applyDimension(1, 2.00f, uDisplayMetr);
       this.s = TypedValue.applyDimension(1, 5.00f, uDisplayMetr);
       this.t = TypedValue.applyDimension(1, 14.00f, uDisplayMetr);
       this.u = -1;
       this.v = TypedValue.applyDimension(1, 0x3f800000, uDisplayMetr);
       this.w = Color.argb(170, 255, 255, 255);
       this.x = Color.argb(119, false, false, false);
       this.y = (int)TypedValue.applyDimension(1, 42.00f, uDisplayMetr);
       this.z = (int)TypedValue.applyDimension(1, 42.00f, uDisplayMetr);
       this.A = 40;
       this.B = 40;
       this.C = 0x1869f;
       this.D = 0x1869f;
       this.E = "";
       this.F = 0;
       this.G = Uri.EMPTY;
       this.H = Bitmap$CompressFormat.JPEG;
       this.I = 90;
       this.J = 0;
       this.K = 0;
       this.L = CropImageView$RequestSizeOptions.NONE;
       this.M = false;
       this.N = null;
       this.O = -1;
       this.P = true;
       this.Q = true;
       this.R = false;
       this.S = 90;
       this.T = false;
       this.U = false;
    }
    public void CropImageOptions(Parcel p0){
       super();
       this.b = CropImageView$CropShape.values()[p0.readInt()];
       this.c = p0.readFloat();
       this.d = p0.readFloat();
       this.e = CropImageView$Guidelines.values()[p0.readInt()];
       this.f = CropImageView$ScaleType.values()[p0.readInt()];
       boolean b = true;
       boolean b1 = (p0.readByte())? true: false;
       this.g = b1;
       b1 = (p0.readByte())? true: false;
       this.h = b1;
       b1 = (p0.readByte())? true: false;
       this.i = b1;
       b1 = (p0.readByte())? true: false;
       this.j = b1;
       this.k = p0.readInt();
       this.l = p0.readFloat();
       b1 = (p0.readByte())? true: false;
       this.m = b1;
       this.n = p0.readInt();
       this.o = p0.readInt();
       this.p = p0.readFloat();
       this.q = p0.readInt();
       this.r = p0.readFloat();
       this.s = p0.readFloat();
       this.t = p0.readFloat();
       this.u = p0.readInt();
       this.v = p0.readFloat();
       this.w = p0.readInt();
       this.x = p0.readInt();
       this.y = p0.readInt();
       this.z = p0.readInt();
       this.A = p0.readInt();
       this.B = p0.readInt();
       this.C = p0.readInt();
       this.D = p0.readInt();
       this.E = TextUtils.CHAR_SEQUENCE_CREATOR.createFromParcel(p0);
       this.F = p0.readInt();
       this.G = p0.readParcelable(Uri.class.getClassLoader());
       this.H = Bitmap$CompressFormat.valueOf(p0.readString());
       this.I = p0.readInt();
       this.J = p0.readInt();
       this.K = p0.readInt();
       this.L = CropImageView$RequestSizeOptions.values()[p0.readInt()];
       b1 = (p0.readByte())? true: false;
       this.M = b1;
       this.N = p0.readParcelable(Rect.class.getClassLoader());
       this.O = p0.readInt();
       b1 = (p0.readByte())? true: false;
       this.P = b1;
       b1 = (p0.readByte())? true: false;
       this.Q = b1;
       b1 = (p0.readByte())? true: false;
       this.R = b1;
       this.S = p0.readInt();
       b1 = (p0.readByte())? true: false;
       this.T = b1;
       if (!p0.readByte()) {
          b = false;
       }
       this.U = b;
       return;
    }
    public int describeContents(){
       return 0;
    }
    public void writeToParcel(Parcel p0,int p1){
       if (PatchProxy.isSupport(CropImageOptions.class) && PatchProxy.applyVoidTwoRefs(p0, Integer.valueOf(p1), this, CropImageOptions.class, "1")) {
          return;
       }
       p0.writeInt(this.b.ordinal());
       p0.writeFloat(this.c);
       p0.writeFloat(this.d);
       p0.writeInt(this.e.ordinal());
       p0.writeInt(this.f.ordinal());
       p0.writeByte((byte)this.g);
       p0.writeByte((byte)this.h);
       p0.writeByte((byte)this.i);
       p0.writeByte((byte)this.j);
       p0.writeInt(this.k);
       p0.writeFloat(this.l);
       p0.writeByte((byte)this.m);
       p0.writeInt(this.n);
       p0.writeInt(this.o);
       p0.writeFloat(this.p);
       p0.writeInt(this.q);
       p0.writeFloat(this.r);
       p0.writeFloat(this.s);
       p0.writeFloat(this.t);
       p0.writeInt(this.u);
       p0.writeFloat(this.v);
       p0.writeInt(this.w);
       p0.writeInt(this.x);
       p0.writeInt(this.y);
       p0.writeInt(this.z);
       p0.writeInt(this.A);
       p0.writeInt(this.B);
       p0.writeInt(this.C);
       p0.writeInt(this.D);
       TextUtils.writeToParcel(this.E, p0, p1);
       p0.writeInt(this.F);
       p0.writeParcelable(this.G, p1);
       p0.writeString(this.H.name());
       p0.writeInt(this.I);
       p0.writeInt(this.J);
       p0.writeInt(this.K);
       p0.writeInt(this.L.ordinal());
       p0.writeInt(this.M);
       p0.writeParcelable(this.N, p1);
       p0.writeInt(this.O);
       p0.writeByte((byte)this.P);
       p0.writeByte((byte)this.Q);
       p0.writeByte((byte)this.R);
       p0.writeInt(this.S);
       p0.writeByte((byte)this.T);
       p0.writeByte((byte)this.U);
       return;
    }
}
