package com.kuaishou.live.lite.debuglog.LiveLiteLogTag;
import pp.c;
import java.lang.Enum;
import java.lang.String;
import java.lang.StringBuilder;
import com.kuaishou.android.live.log.LiveLogTag;
import java.lang.Object;
import java.lang.Class;
import com.kwai.robust.PatchProxy;
import com.kwai.robust.PatchProxyResult;
import java.util.List;
import com.kuaishou.android.live.log.a;

public final class LiveLiteLogTag extends Enum implements c	// class@0008d5
{
    public final String _name;
    public static final LiveLiteLogTag[] $VALUES;
    public static final LiveLiteLogTag ANONYMITY;
    public static final LiveLiteLogTag BENEFIT_CARD;
    public static final LiveLiteLogTag BIDIRECTIONAL_DATA_TRANSFER;
    public static final LiveLiteLogTag BOTTOM_BAR;
    public static final LiveLiteLogTag BOTTOM_BAR_EDITOR;
    public static final LiveLiteLogTag CLOSE_LIFE_CYCLE;
    public static final LiveLiteLogTag COVER;
    public static final LiveLiteLogTag GESTURE;
    public static final LiveLiteLogTag HIGH_FREQUENCY;
    public static final LiveLiteLogTag HOURLY_RANK;
    public static final LiveLiteLogTag INTERACTIVE_MESSAGE;
    public static final LiveLiteLogTag LAYOUT_AX2C;
    public static final LiveLiteLogTag LAYOUT_MANAGER;
    public static final LiveLiteLogTag LIFECYCLE;
    public static final LiveLiteLogTag LITE_ANCHOR_AVATAR;
    public static final LiveLiteLogTag LITE_ANCHOR_INFO;
    public static final LiveLiteLogTag LITE_ANCHOR_INFO_FOLLOW;
    public static final LiveLiteLogTag LITE_BACKGROUND;
    public static final LiveLiteLogTag LITE_CLASS_WARMUP;
    public static final LiveLiteLogTag LITE_COMBO_COMMENT;
    public static final LiveLiteLogTag LITE_COMMENT_NOTICE;
    public static final LiveLiteLogTag LITE_FANS_GROUP;
    public static final LiveLiteLogTag LITE_FEEDBACK;
    public static final LiveLiteLogTag LITE_FRAGMENT_LIFE;
    public static final LiveLiteLogTag LITE_FRAMEWORK;
    public static final LiveLiteLogTag LITE_FRAMEWORK_LOADER;
    public static final LiveLiteLogTag LITE_GUIDANCE;
    public static final LiveLiteLogTag LITE_HOUSE_BOTTOM;
    public static final LiveLiteLogTag LITE_LIKE;
    public static final LiveLiteLogTag LITE_LIKE_PARTICLE;
    public static final LiveLiteLogTag LITE_MERCHANT_FORBIDDEN;
    public static final LiveLiteLogTag LITE_MULTI_CHAT;
    public static final LiveLiteLogTag LITE_MULTI_LINE;
    public static final LiveLiteLogTag LITE_RECOMMEND_PANEL;
    public static final LiveLiteLogTag LITE_RECOMMEND_SERVICE;
    public static final LiveLiteLogTag LITE_RECRUIT_BOTTOM;
    public static final LiveLiteLogTag LITE_SLIDE_MANAGER;
    public static final LiveLiteLogTag LITE_STATE_CHART;
    public static final LiveLiteLogTag LIVE_FOLLOW_GUIDE;
    public static final LiveLiteLogTag LIVE_LITE_END;
    public static final LiveLiteLogTag LIVE_LITE_HORIZONTAL_SWIPE;
    public static final LiveLiteLogTag LIVE_LITE_LUCKY_STAR;
    public static final LiveLiteLogTag LIVE_LITE_PROFIT_INFO;
    public static final LiveLiteLogTag LIVE_LITE_RED_PACK;
    public static final LiveLiteLogTag LIVE_LITE_TASK;
    public static final LiveLiteLogTag LIVE_LITE_TEMP_PLAY;
    public static final LiveLiteLogTag PERFORMANCE_TRACE;
    public static final LiveLiteLogTag PLAYER;
    public static final LiveLiteLogTag PLAYER_DEBUG_INFO;
    public static final LiveLiteLogTag PROFIT_INFO_AREA;
    public static final LiveLiteLogTag QUESTIONNAIRE;
    public static final LiveLiteLogTag QUICK_INTERACTIVE;
    public static final LiveLiteLogTag ROOT_VIEW;
    public static final LiveLiteLogTag SHARE;
    public static final LiveLiteLogTag SIDE_BAR;
    public static final LiveLiteLogTag SIDE_BAR_SHRINK;
    public static final LiveLiteLogTag SQUARE;
    public static final LiveLiteLogTag TEMP_PLAY_AREA;
    public static final LiveLiteLogTag USER_STATUS;

    static {
       LiveLiteLogTag[] liveLiteLogT = new LiveLiteLogTag[59];
       LiveLiteLogTag liveLiteLogT1 = new LiveLiteLogTag("ROOT_VIEW", 0, "LiteRootView");
       LiveLiteLogTag.ROOT_VIEW = liveLiteLogT1;
       liveLiteLogT[0] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("PLAYER", 1, LiveLogTag.PLAYER.getName()+"_Lite");
       LiveLiteLogTag.PLAYER = liveLiteLogT1;
       liveLiteLogT[1] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("LITE_SLIDE_MANAGER", 2, "LiteSlideManager");
       LiveLiteLogTag.LITE_SLIDE_MANAGER = liveLiteLogT1;
       liveLiteLogT[2] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("LIFECYCLE", 3, "LiteLifecycle");
       LiveLiteLogTag.LIFECYCLE = liveLiteLogT1;
       liveLiteLogT[3] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("PERFORMANCE_TRACE", 4, "LiteTrace");
       LiveLiteLogTag.PERFORMANCE_TRACE = liveLiteLogT1;
       liveLiteLogT[4] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("LIVE_LITE_TASK", 5, "LiteTask");
       LiveLiteLogTag.LIVE_LITE_TASK = liveLiteLogT1;
       liveLiteLogT[5] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("CLOSE_LIFE_CYCLE", 6, "LiteCloseLifecycle");
       LiveLiteLogTag.CLOSE_LIFE_CYCLE = liveLiteLogT1;
       liveLiteLogT[6] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("LITE_FRAMEWORK", 7, "LiteFramework");
       LiveLiteLogTag.LITE_FRAMEWORK = liveLiteLogT1;
       liveLiteLogT[7] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("LITE_FRAMEWORK_LOADER", 8, "LiteFrameworkLoader");
       LiveLiteLogTag.LITE_FRAMEWORK_LOADER = liveLiteLogT1;
       liveLiteLogT[8] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("LIVE_LITE_END", 9, "LiveLiteClose");
       LiveLiteLogTag.LIVE_LITE_END = liveLiteLogT1;
       liveLiteLogT[9] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("LIVE_LITE_PROFIT_INFO", 10, "LiveLiteProfitInfo");
       LiveLiteLogTag.LIVE_LITE_PROFIT_INFO = liveLiteLogT1;
       liveLiteLogT[10] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("LIVE_LITE_LUCKY_STAR", 11, "LiveLiteLuckyStar");
       LiveLiteLogTag.LIVE_LITE_LUCKY_STAR = liveLiteLogT1;
       liveLiteLogT[11] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("LIVE_LITE_RED_PACK", 12, "LiveLiteRedPack");
       LiveLiteLogTag.LIVE_LITE_RED_PACK = liveLiteLogT1;
       liveLiteLogT[12] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("LIVE_LITE_TEMP_PLAY", 13, "LiveLiteTempPlay");
       LiveLiteLogTag.LIVE_LITE_TEMP_PLAY = liveLiteLogT1;
       liveLiteLogT[13] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("LIVE_LITE_HORIZONTAL_SWIPE", 14, "LiveLiteHorizontalSwipe");
       LiveLiteLogTag.LIVE_LITE_HORIZONTAL_SWIPE = liveLiteLogT1;
       liveLiteLogT[14] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("LITE_ANCHOR_AVATAR", 15, "LiteAnchorAvatar");
       LiveLiteLogTag.LITE_ANCHOR_AVATAR = liveLiteLogT1;
       liveLiteLogT[15] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("LITE_ANCHOR_INFO", 16, "LiteAnchorInfoArea");
       LiveLiteLogTag.LITE_ANCHOR_INFO = liveLiteLogT1;
       liveLiteLogT[16] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("LITE_ANCHOR_INFO_FOLLOW", 17, "LiteAnchorInfoFollow");
       LiveLiteLogTag.LITE_ANCHOR_INFO_FOLLOW = liveLiteLogT1;
       liveLiteLogT[17] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("LITE_FRAGMENT_LIFE", 18, "LiteFragmentLife");
       LiveLiteLogTag.LITE_FRAGMENT_LIFE = liveLiteLogT1;
       liveLiteLogT[18] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("USER_STATUS", 19, "LiteUserStatus");
       LiveLiteLogTag.USER_STATUS = liveLiteLogT1;
       liveLiteLogT[19] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("LAYOUT_MANAGER", 20, "LiveLiteLayoutManager");
       LiveLiteLogTag.LAYOUT_MANAGER = liveLiteLogT1;
       liveLiteLogT[20] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("SHARE", 21, "LiteShare");
       LiveLiteLogTag.SHARE = liveLiteLogT1;
       liveLiteLogT[21] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("SIDE_BAR", 22, "LiteSideBar");
       LiveLiteLogTag.SIDE_BAR = liveLiteLogT1;
       liveLiteLogT[22] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("SIDE_BAR_SHRINK", 23, "LiteSideBarShrink");
       LiveLiteLogTag.SIDE_BAR_SHRINK = liveLiteLogT1;
       liveLiteLogT[23] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("BOTTOM_BAR", 24, "LiteBottomBar");
       LiveLiteLogTag.BOTTOM_BAR = liveLiteLogT1;
       liveLiteLogT[24] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("BOTTOM_BAR_EDITOR", 25, "LiteBottomBarEditor");
       LiveLiteLogTag.BOTTOM_BAR_EDITOR = liveLiteLogT1;
       liveLiteLogT[25] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("GESTURE", 26, "LiteGesture");
       LiveLiteLogTag.GESTURE = liveLiteLogT1;
       liveLiteLogT[26] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("LITE_MULTI_CHAT", 27, "LiveLiteMultiChat");
       LiveLiteLogTag.LITE_MULTI_CHAT = liveLiteLogT1;
       liveLiteLogT[27] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("LITE_MULTI_LINE", 28, "LiveLiteMultiLine");
       LiveLiteLogTag.LITE_MULTI_LINE = liveLiteLogT1;
       liveLiteLogT[28] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("LITE_MERCHANT_FORBIDDEN", 29, "LiteMerchantForbidden");
       LiveLiteLogTag.LITE_MERCHANT_FORBIDDEN = liveLiteLogT1;
       liveLiteLogT[29] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("LITE_LIKE", 30, "LiteLike");
       LiveLiteLogTag.LITE_LIKE = liveLiteLogT1;
       liveLiteLogT[30] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("LITE_RECRUIT_BOTTOM", 31, "LiteRecruitBottom");
       LiveLiteLogTag.LITE_RECRUIT_BOTTOM = liveLiteLogT1;
       liveLiteLogT[31] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("LITE_HOUSE_BOTTOM", 32, "LiteHouseBottom");
       LiveLiteLogTag.LITE_HOUSE_BOTTOM = liveLiteLogT1;
       liveLiteLogT[32] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("LITE_RECOMMEND_PANEL", 33, "LiteRecommendPanelLog");
       LiveLiteLogTag.LITE_RECOMMEND_PANEL = liveLiteLogT1;
       liveLiteLogT[33] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("LITE_RECOMMEND_SERVICE", 34, "LiteRecommendService");
       LiveLiteLogTag.LITE_RECOMMEND_SERVICE = liveLiteLogT1;
       liveLiteLogT[34] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("LITE_LIKE_PARTICLE", 35, "LiteLikeParticle");
       LiveLiteLogTag.LITE_LIKE_PARTICLE = liveLiteLogT1;
       liveLiteLogT[35] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("LITE_FEEDBACK", 36, "LiteFeedback");
       LiveLiteLogTag.LITE_FEEDBACK = liveLiteLogT1;
       liveLiteLogT[36] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("SQUARE", 37, "LiteSquare");
       LiveLiteLogTag.SQUARE = liveLiteLogT1;
       liveLiteLogT[37] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("LITE_BACKGROUND", 38, "LiteBackground");
       LiveLiteLogTag.LITE_BACKGROUND = liveLiteLogT1;
       liveLiteLogT[38] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("HOURLY_RANK", 39, "LiteHourlyRank");
       LiveLiteLogTag.HOURLY_RANK = liveLiteLogT1;
       liveLiteLogT[39] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("ANONYMITY", 40, "LiteAnonymity");
       LiveLiteLogTag.ANONYMITY = liveLiteLogT1;
       liveLiteLogT[40] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("INTERACTIVE_MESSAGE", 41, "LiteInteractiveMessage");
       LiveLiteLogTag.INTERACTIVE_MESSAGE = liveLiteLogT1;
       liveLiteLogT[41] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("TEMP_PLAY_AREA", 42, "LiteTempPlayArea");
       LiveLiteLogTag.TEMP_PLAY_AREA = liveLiteLogT1;
       liveLiteLogT[42] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("PROFIT_INFO_AREA", 43, "LiteProfitInfoArea");
       LiveLiteLogTag.PROFIT_INFO_AREA = liveLiteLogT1;
       liveLiteLogT[43] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("LAYOUT_AX2C", 44, "LiteLayoutAX2C");
       LiveLiteLogTag.LAYOUT_AX2C = liveLiteLogT1;
       liveLiteLogT[44] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("PLAYER_DEBUG_INFO", 45, "LitePlayerDebugInfo");
       LiveLiteLogTag.PLAYER_DEBUG_INFO = liveLiteLogT1;
       liveLiteLogT[45] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("LITE_FANS_GROUP", 46, "LiteFansGroup");
       LiveLiteLogTag.LITE_FANS_GROUP = liveLiteLogT1;
       liveLiteLogT[46] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("COVER", 47, "LiveLiteCover");
       LiveLiteLogTag.COVER = liveLiteLogT1;
       liveLiteLogT[47] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("LITE_GUIDANCE", 48, "LiteGuidance");
       LiveLiteLogTag.LITE_GUIDANCE = liveLiteLogT1;
       liveLiteLogT[48] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("LITE_COMMENT_NOTICE", 49, "LiteCommentNotice");
       LiveLiteLogTag.LITE_COMMENT_NOTICE = liveLiteLogT1;
       liveLiteLogT[49] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("BIDIRECTIONAL_DATA_TRANSFER", 50, "BidirectionalDataTransfer");
       LiveLiteLogTag.BIDIRECTIONAL_DATA_TRANSFER = liveLiteLogT1;
       liveLiteLogT[50] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("QUICK_INTERACTIVE", 51, "LiteQuickInteractive");
       LiveLiteLogTag.QUICK_INTERACTIVE = liveLiteLogT1;
       liveLiteLogT[51] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("HIGH_FREQUENCY", 52, "highFrequency");
       LiveLiteLogTag.HIGH_FREQUENCY = liveLiteLogT1;
       liveLiteLogT[52] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("LITE_COMBO_COMMENT", 53, "LiteComboComment");
       LiveLiteLogTag.LITE_COMBO_COMMENT = liveLiteLogT1;
       liveLiteLogT[53] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("LIVE_FOLLOW_GUIDE", 54, "liteFollowGuide");
       LiveLiteLogTag.LIVE_FOLLOW_GUIDE = liveLiteLogT1;
       liveLiteLogT[54] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("BENEFIT_CARD", 55, "LiteBenefitCard");
       LiveLiteLogTag.BENEFIT_CARD = liveLiteLogT1;
       liveLiteLogT[55] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("LITE_CLASS_WARMUP", 56, "LiteClassWarmup");
       LiveLiteLogTag.LITE_CLASS_WARMUP = liveLiteLogT1;
       liveLiteLogT[56] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("QUESTIONNAIRE", 57, "LiteQuestionnaire");
       LiveLiteLogTag.QUESTIONNAIRE = liveLiteLogT1;
       liveLiteLogT[57] = liveLiteLogT1;
       liveLiteLogT1 = new LiveLiteLogTag("LITE_STATE_CHART", 58, "LiteStateChart");
       LiveLiteLogTag.LITE_STATE_CHART = liveLiteLogT1;
       liveLiteLogT[58] = liveLiteLogT1;
       LiveLiteLogTag.$VALUES = liveLiteLogT;
    }
    public void LiveLiteLogTag(String p0,int p1,String p2){
       super(p0, p1);
       this._name = p2;
    }
    public static LiveLiteLogTag valueOf(String p0){
       Object obj = PatchProxy.applyOneRefs(p0, null, LiveLiteLogTag.class, "2");
       if (obj != PatchProxyResult.class) {
          return obj;
       }
       return Enum.valueOf(LiveLiteLogTag.class, p0);
    }
    public static LiveLiteLogTag[] values(){
       Object obj = PatchProxy.apply(null, null, LiveLiteLogTag.class, "1");
       if (obj != PatchProxyResult.class) {
          return obj;
       }
       return LiveLiteLogTag.$VALUES.clone();
    }
    public List appendTag(String p0){
       return a.a(this, p0);
    }
    public String getName(){
       return this._name;
    }
}
