package com.kuaishou.live.core.basic.model.LiveTimeConsumingUserStatusResponse;
import java.io.Serializable;
import java.lang.Object;
import java.util.ArrayList;

public class LiveTimeConsumingUserStatusResponse implements Serializable	// class@00089a
{
    public List mActivityPendant;
    public LiveAudienceBlessBagConfig mBlessBagConfig;
    public LiveTimeConsumingUserStatusResponse$BlindDateConfig mBlindDateConfig;
    public int mCanSendBulletCommentMinLevel;
    public LiveTimeConsumingUserStatusResponse$ComboBatchSendGiftConfig mComboBatchSendGiftConfig;
    public LiveTimeConsumingUserStatusResponse$LiveCommentBoxConfig mCommentBoxConfig;
    public LiveCommentsAreaConfig mCommentsAreaConfig;
    public LiveCustomPkSkinTheme mCustomPkSkinTheme;
    public boolean mDisableBroadcastBannerMessage;
    public boolean mEnableAudienceContributionRank;
    public boolean mEnableBackpackHasFreeTicketRedDot;
    public boolean mEnablePcMultiChatVideo;
    public boolean mEnableReportLiveStreamFeedStats;
    public boolean mEnableSendGiftNotifyAnimation;
    public boolean mEnableVoicePartyGuestFollowAuthorGuideCard;
    public boolean mEnableVoicePartyMicSeatsShareGuide;
    public LiveAudienceInteractiveSystemFeedbackTips mInteractiveSystemFeedbackTips;
    public boolean mIsCityRankEnable;
    public boolean mIsHourlyQuarterRankEnable;
    public boolean mIsHourlyRankEntryEnable;
    public boolean mIsHourlyRankStrengthNoticeEnable;
    public boolean mIsNewHourlyRankResultEnable;
    public LiveHourlyRankPendantPriorityInfo mLeftTopHourlyRankPendantPriorityInfo;
    public LiveActivityCommentConfig mLiveActivityCommentConfig;
    public LiveActivityInfo mLiveActivityInfo;
    public LiveAnnounceInfo mLiveAnnounceInfo;
    public LiveAudienceAuthorAuthentication mLiveAudienceAuthorAuthentication;
    public LiveTimeConsumingUserStatusResponse$LiveAudienceGiftRewardManageInfo mLiveAudienceGiftRewardManageInfo;
    public LiveAudienceHighValueUserConfig mLiveAudienceHighValueUserConfig;
    public LiveAudienceRedPacketConfig mLiveAudienceRedPacketConfig;
    public LiveAudienceShareGuideConfig mLiveAudienceShareGuideConfig;
    public LiveAudienceShareHighlightInfo mLiveAudienceShareHighlightInfo;
    public LiveCarouselPendantInfo mLiveCarouselPendantInfo;
    public LiveAudienceChatStatConfig mLiveChatStat;
    public LiveTimeConsumingUserStatusResponse$LiveCohesionPkJoinState mLiveCohesionPkJoinState;
    public LiveEffectConfig mLiveEffectConfig;
    public LiveExperienceOptimizationConfig mLiveExperienceOptimizationConfig;
    public List mLiveFeatureForbidInfo;
    public LiveFellowInfo mLiveFellowInfo;
    public LiveGiftConfig mLiveGiftConfig;
    public LiveGiftGuideConfig mLiveGiftGuideConfig;
    public LiveGiftOutsideConfigResponse mLiveGiftOutsideConfigResponse;
    public LiveGiftPanelRefreshConfig mLiveGiftPanelRefresh;
    public LiveTimeConsumingUserStatusResponse$LiveGiftPanelWarningConfig mLiveGiftPanelWarningConfig;
    public List mLiveGiftSlotGrades;
    public List mLiveGiftSlotSpecialComboList;
    public LiveGoldCoinInfoConfig mLiveGoldCoinInfoConfig;
    public LiveIntelligentDeliveryRedPacketConfig mLiveIntelligentDeliveryRedPacketConfig;
    public LiveLikeNewStyleConfig mLiveLikeNewStyleConfig;
    public LiveNebulaCreditPayResponse mLiveNebulaCreditPayResponse;
    public LivePayBulletResponse mLivePayBulletResponse;
    public LivePkRecommendGiftInfo mLivePkRecommendGiftInfo;
    public LiveHourlyRankConfig mLivePopularityRankConfig;
    public LiveTimeConsumingUserStatusResponse$LivePullRequestInfo mLivePullRequestInfo;
    public List mLiveRecruitAppliedJobIds;
    public LiveRecruitQuestionnaireConfig mLiveRecruitQuestionnaireConfig;
    public LiveRevenueConfigResponse mLiveRevenueConfigResponse;
    public List mLiveStreamTypeList;
    public LiveUserPrivilegeInfo mLiveUserPrivilegeInfo;
    public LiveVerticalSceneConfig mLiveVerticalSceneConfig;
    public LiveTimeConsumingUserStatusResponse$LiveVoicePartyConfig mLiveVoicePartyConfig;
    public LiveWealthGradeInfo mLiveWealthGradeInfo;
    public LiveWishLightGiftGuideConfig mLiveWishLightGiftGuideConfig;
    public LiveTimeConsumingUserStatusResponse$LiveMiniProgramConfig mMiniProgramConfig;
    public String mPrivilegeInfoH5Url;
    public LiveRecruitShareInfo mRecruitShareInfo;
    public LiveTimeConsumingUserStatusResponse$LiveAudienceFlowerInfo mRedFlowerInfo;
    public List mRoleInfos;
    public LiveAudienceShareToIMGuideConfig mShareToIMGuideConfig;
    public List mSignalBlockConfig;
    public String mSpringCeremonyNamingData;
    public List mSubscribeInfo;
    public TempIndicatorPendantConfig mTempIndicatorPendantConfig;
    public LiveAudienceTaskConfig mUserTaskConfig;
    public LiveAudienceVoiceCommentConfig mVoiceCommentConfig;
    public VoicePartyMicSeatsShareConfig mVoicePartyMicSeatsShareConfig;
    public LiveTimeConsumingUserStatusResponse$TopUserToastConfig topUserToastConfig;
    public List userConditionStates;
    public static final long serialVersionUID = 0x5438a203afa69fd3;

    public void LiveTimeConsumingUserStatusResponse(){
       super();
       this.mLiveStreamTypeList = new ArrayList();
       this.mCanSendBulletCommentMinLevel = -1;
       this.mLiveFeatureForbidInfo = new ArrayList();
    }
}
