package add.e;

public class e	// class@0000e2
{
    public static final int A;
    public static final int A0;
    public static final int B;
    public static final int B0;
    public static final int C;
    public static final int C0;
    public static final int D;
    public static final int D0;
    public static final int E;
    public static final int E0;
    public static final int F;
    public static final int F0;
    public static final int G;
    public static final int G0;
    public static final int H;
    public static final int H0;
    public static final int I;
    public static final int I0;
    public static final int J;
    public static final int J0;
    public static final int K;
    public static final int K0;
    public static final int L;
    public static final int L0;
    public static final int M;
    public static final int M0;
    public static final int N;
    public static final int N0;
    public static final int O;
    public static final int O0;
    public static final int P;
    public static final int P0;
    public static final int Q;
    public static final int Q0;
    public static final int R;
    public static final int R0;
    public static final int S;
    public static final int S0;
    public static final int T;
    public static final int T0;
    public static final int U;
    public static final int U0;
    public static final int V;
    public static final int V0;
    public static final int W;
    public static final int W0;
    public static final int X;
    public static final int X0;
    public static final int Y;
    public static final int Y0;
    public static final int Z;
    public static int a;
    public static final int a0;
    public static final int b;
    public static final int b0;
    public static final int c;
    public static final int c0;
    public static final int d;
    public static final int d0;
    public static final int e;
    public static final int e0;
    public static final int f;
    public static final int f0;
    public static final int g;
    public static final int g0;
    public static final int h;
    public static final int h0;
    public static final int i;
    public static final int i0;
    public static final int j;
    public static final int j0;
    public static final int k;
    public static final int k0;
    public static final int l;
    public static final int l0;
    public static final int m;
    public static final int m0;
    public static final int n;
    public static final int n0;
    public static final int o;
    public static final int o0;
    public static final int p;
    public static final int p0;
    public static final int q;
    public static final int q0;
    public static final int r;
    public static final int r0;
    public static final int s;
    public static final int s0;
    public static final int t;
    public static final int t0;
    public static final int u;
    public static final int u0;
    public static final int v;
    public static final int v0;
    public static final int w;
    public static final int w0;
    public static final int x;
    public static final int x0;
    public static final int y;
    public static final int y0;
    public static final int z;
    public static final int z0;

    static {
       e.b = e.a();
       e.c = e.a();
       e.d = e.a();
       e.e = e.a();
       e.f = e.a();
       e.h = e.a();
       e.g = e.a();
       e.i = e.a();
       e.j = e.a();
       e.k = e.a();
       e.l = e.a();
       e.m = e.a();
       e.n = e.a();
       e.o = e.a();
       e.p = e.a();
       e.q = e.a();
       e.r = e.a();
       e.s = e.a();
       e.t = e.a();
       e.u = e.a();
       e.v = e.a();
       e.w = e.a();
       e.x = e.a();
       e.y = e.a();
       e.z = e.a();
       e.B = e.a();
       e.C = e.a();
       e.D = e.a();
       e.E = e.a();
       e.F = e.a();
       e.G = e.a();
       e.H = e.a();
       e.I = e.a();
       e.J = e.a();
       e.K = e.a();
       e.L = e.a();
       e.Y = e.a();
       e.Z = e.a();
       e.a0 = e.a();
       e.b0 = e.a();
       e.h0 = e.a();
       e.d0 = e.a();
       e.e0 = e.a();
       e.f0 = e.a();
       e.g0 = e.a();
       e.i0 = e.a();
       e.M = e.a();
       e.j0 = e.a();
       e.k0 = e.a();
       e.l0 = e.a();
       e.N = e.a();
       e.O = e.a();
       e.Q = e.a();
       e.P = e.a();
       e.J0 = e.a();
       e.m0 = e.a();
       e.R = e.a();
       e.n0 = e.a();
       e.o0 = e.a();
       e.p0 = e.a();
       e.S = e.a();
       e.q0 = e.a();
       e.r0 = e.a();
       e.s0 = e.a();
       e.t0 = e.a();
       e.u0 = e.a();
       e.v0 = e.a();
       e.w0 = e.a();
       e.x0 = e.a();
       e.y0 = e.a();
       e.z0 = e.a();
       e.A0 = e.a();
       e.A = e.a();
       e.E0 = e.a();
       e.F0 = e.a();
       e.G0 = e.a();
       e.Q0 = e.a();
       e.R0 = e.a();
       e.S0 = e.a();
       e.T0 = e.a();
       e.H0 = e.a();
       e.I0 = e.a();
       e.T = e.a();
       e.K0 = e.a();
       e.L0 = e.a();
       e.B0 = e.a();
       e.N0 = e.a();
       e.M0 = e.a();
       e.O0 = e.a();
       e.P0 = e.a();
       e.U = e.a();
       e.c0 = e.a();
       e.U0 = e.a();
       e.V = e.a();
       e.W = e.a();
       e.C0 = e.a();
       e.D0 = e.a();
       e.V0 = e.a();
       e.W0 = e.a();
       e.X0 = e.a();
       e.Y0 = e.a();
       e.X = e.a();
    }
    public static int a(){
       int a = e.a;
       e.a = a + 1;
       return a;
    }
}
