package nl9.d;
import tkd.b;
import java.lang.Throwable;
import brd.t;
import com.yxcorp.gifshow.photoad.model.AdDataWrapper;
import java.lang.String;
import android.app.Activity;
import msd.l;
import mxb.j0;
import com.yxcorp.gifshow.commercial.model.APKDownloadTask;
import com.yxcorp.download.b;
import vq4.c;
import com.yxcorp.gifshow.commercial.model.APKDownloadTask$DownloadStatus;
import com.yxcorp.gifshow.entity.QPhoto;
import android.content.Context;
import com.yxcorp.gifshow.commercial.model.AdDownloadCenterSource;
import android.view.View;
import com.yxcorp.download.DownloadTask$DownloadRequest;
import com.yxcorp.gifshow.commercial.model.ApkDownloadTaskInfo;
import com.yxcorp.gifshow.commercial.model.AdDownloaderType;
import java.util.List;
import z1.a;
import com.kwai.framework.model.feed.BaseFeed;

public interface abstract d implements b	// class@0031aa
{

    t Ay(int p0,long p1,Throwable p2);
    t D40();
    void D5(int p0);
    boolean D6(AdDataWrapper p0);
    t EJ(int p0);
    String FZ(Throwable p0);
    void Fg(Activity p0,AdDataWrapper p1,l p2);
    void J10(String p0,AdDataWrapper p1,String p2,j0 p3);
    int Je();
    APKDownloadTask KK(String p0);
    String L9(String p0);
    void LA();
    void MH(String p0,b p1);
    void PZ(c p0);
    void Q5(int p0,long p1);
    APKDownloadTask$DownloadStatus QT(String p0);
    void TJ(String p0);
    t TR(QPhoto p0);
    void W10(Context p0,AdDownloadCenterSource p1);
    String Wz();
    void YN(Context p0,View p1);
    String Z20();
    boolean bp(AdDataWrapper p0);
    void by();
    void dk(AdDataWrapper p0,String p1);
    void fc(String p0,b p1);
    t g30(int p0,DownloadTask$DownloadRequest p1,ApkDownloadTaskInfo p2,AdDownloaderType p3);
    t g70(int p0,DownloadTask$DownloadRequest p1,QPhoto p2);
    t h60();
    t hR();
    boolean jZ(Activity p0,AdDataWrapper p1,List p2,a p3);
    t kP(int p0,long p1,long p2);
    boolean l30(Activity p0,AdDataWrapper p1,a p2);
    void mY(DownloadTask$DownloadRequest p0,AdDataWrapper p1,AdDownloaderType p2,List p3,boolean p4);
    void t10(int p0);
    t ti(int p0,long p1,long p2);
    t um(int p0,long p1,long p2);
    b wj(BaseFeed p0);
    void wn(Activity p0,AdDataWrapper p1);
    t yP(int p0);
}
