package nl9.h0;
import tkd.b;
import android.content.Context;
import com.kuaishou.gifshow.network.degrade.RequestTiming;
import tjc.d;
import java.util.List;
import com.kwai.framework.model.feed.BaseFeed;
import java.lang.String;
import com.kuaishou.android.model.ads.PhotoAdvertisement;
import jg5.c;
import nl9.h0$d;
import android.app.Activity;
import com.yxcorp.gifshow.photoad.model.AdDataWrapper;
import z1.a;
import android.widget.FrameLayout;
import com.smile.gifmaker.mvps.presenter.PresenterV2;
import tjc.b;
import com.yxcorp.gifshow.entity.QPhoto;
import nl9.h0$b;
import com.kuaishou.android.model.ads.SplashInfo;
import com.yxcorp.gifshow.recycler.fragment.BaseFragment;

public interface abstract h0 implements b	// class@0031b5
{

    boolean BJ();
    boolean Cb();
    boolean D2();
    void Dx();
    void ED(Context p0,RequestTiming p1);
    boolean GV();
    d Hv();
    boolean LG();
    boolean Li(boolean p0);
    boolean Q4();
    List QV();
    void Qu(BaseFeed p0);
    void R3(RequestTiming p0,String p1);
    void RK();
    PhotoAdvertisement RR();
    c RW();
    void VE(RequestTiming p0,h0$d p1);
    boolean VP();
    void Vd();
    void Vn(boolean p0);
    void WK(Activity p0,AdDataWrapper p1,a p2);
    boolean Xe();
    void YZ(RequestTiming p0,h0$d p1);
    boolean Ym();
    FrameLayout ZP(Context p0);
    PresenterV2 aN(boolean p0);
    void b70(b p0);
    boolean bY(BaseFeed p0);
    boolean c70(Context p0);
    void d0(RequestTiming p0);
    c dS(RequestTiming p0);
    boolean e0();
    QPhoto e9();
    boolean hV();
    boolean isEnabled();
    boolean je(Context p0);
    boolean m30();
    void mA(h0$b p0);
    void mB(RequestTiming p0,h0$d p1);
    boolean mI();
    SplashInfo ob();
    void onBackground();
    void pe(boolean p0);
    BaseFragment qz();
    boolean si();
    void u5();
    boolean uc(BaseFeed p0,Context p1);
    void v00(h0$b p0);
    String w0(RequestTiming p0);
    PresenterV2 yj();
    boolean yz();
    boolean zV();
}
