package nl9.r;
import tkd.b;
import com.kwai.framework.model.feed.BaseFeed;
import com.smile.gifmaker.mvps.presenter.PresenterV2;
import android.app.Activity;
import android.view.View;
import java.lang.String;
import com.yxcorp.gifshow.commercial.pendant.NeoLiveCountDown$SCENE;
import com.yxcorp.gifshow.commercial.pendant.NeoLiveCountDown;
import java.lang.Object;
import com.kuaishou.android.model.feed.LiveStreamFeed;
import com.kuaishou.android.model.feed.LiveStreamFeedWrapper;
import com.yxcorp.gifshow.entity.QPhoto;
import com.kuaishou.live.jsbridge.AbstractLiveJsCommand;
import com.kuaishou.live.ad.social.t;
import zl9.b;
import mxb.e;
import com.kuaishou.live.common.ad.fanstop.UpdateFansTopStatusListener$FansTopStatus;
import com.kuaishou.live.common.ad.fanstop.UpdateFansTopStatusListener;
import java.util.Map;
import java.util.List;
import java.lang.Runnable;
import com.kuaishou.client.log.content.packages.nano.ClientContent$LiveStreamPackage;
import zl0.q1;
import zl0.r1;
import androidx.fragment.app.c;
import androidx.fragment.app.KwaiDialogFragment;

public interface abstract r implements b	// class@0031c6
{

    void D0();
    boolean DH(BaseFeed p0);
    PresenterV2 DV();
    boolean E4();
    boolean Ea(BaseFeed p0);
    NeoLiveCountDown Ef(Activity p0,View p1,BaseFeed p2,String p3,NeoLiveCountDown$SCENE p4);
    void Ep(BaseFeed p0);
    String FP(String p0);
    float GN(String p0,float p1);
    PresenterV2 GP(int p0);
    boolean II(Object p0,LiveStreamFeed p1,boolean p2);
    PresenterV2 Kl();
    boolean LX(LiveStreamFeed p0);
    String La();
    void NG(boolean p0);
    boolean OB(LiveStreamFeedWrapper p0);
    float OW(String p0,float p1);
    PresenterV2 P6();
    String QK(QPhoto p0);
    PresenterV2 QR();
    AbstractLiveJsCommand SR();
    b TQ(t p0);
    void UW(Object p0,Object p1);
    e Uw();
    UpdateFansTopStatusListener$FansTopStatus XK();
    boolean Xx(int p0);
    void YS(UpdateFansTopStatusListener p0);
    void Z6(Map p0,List p1,List p2,QPhoto p3);
    boolean ZX(LiveStreamFeed p0);
    void a6(BaseFeed p0,Runnable p1);
    void aI(ClientContent$LiveStreamPackage p0);
    void aT(QPhoto p0,String p1,Map p2);
    void bn(Object p0);
    boolean cf(LiveStreamFeed p0);
    void ck(BaseFeed p0,int p1,int p2,int p3,int p4);
    b d8(q1 p0);
    void dT(BaseFeed p0,int p1,int p2,int p3,int p4);
    void eI(Map p0);
    PresenterV2 eR();
    int fZ();
    PresenterV2 hW();
    void jx(ClientContent$LiveStreamPackage p0);
    b kC(r1 p0);
    PresenterV2 kJ();
    PresenterV2 ks();
    String o50(boolean p0,boolean p1);
    PresenterV2 qq();
    Object qu(int p0);
    PresenterV2 sA();
    void uk(ClientContent$LiveStreamPackage p0);
    KwaiDialogFragment vi(Activity p0,c p1,String p2,String p3,String p4,int p5);
    void yT(int p0,QPhoto p1,int p2,String p3,Map p4);
    void z7();
}
