package nl9.u;
import tkd.b;
import ml8.c;
import mxb.q;
import java.lang.String;
import com.kwai.framework.model.feed.BaseFeed;
import com.yxcorp.gifshow.entity.QPhoto;
import android.text.SpannableStringBuilder;
import z1.a;
import com.kuaishou.android.model.mix.PlcEntryStyleInfo;
import android.app.Activity;
import com.yxcorp.gifshow.photoad.model.AdDataWrapper;
import com.yxcorp.download.b;
import brd.t;
import crd.b;
import com.yxcorp.gifshow.activity.GifshowActivity;
import com.kwai.framework.model.user.User;
import com.yxcorp.gifshow.commercial.common.model.AdUnionFollowInfo;
import android.content.Context;
import nl9.f;
import android.content.DialogInterface$OnDismissListener;
import com.yxcorp.gifshow.fragment.DialogContainerFragment;
import com.smile.gifmaker.mvps.presenter.PresenterV2;
import androidx.fragment.app.Fragment;
import kotlin.Triple;
import java.util.List;
import com.yxcorp.gifshow.recycler.fragment.BaseFragment;
import msd.a;
import java.lang.Object;
import org.json.JSONObject;
import nl9.i0;
import zl9.c;
import erd.g;
import androidx.fragment.app.DialogFragment;
import java.lang.Class;
import android.widget.ImageButton;
import android.view.ViewGroup;
import android.view.View;

public interface abstract u implements b	// class@0031c9
{

    void A2(c p0);
    void BV();
    boolean Bo(q p0);
    void DB(boolean p0,String p1,BaseFeed p2);
    String Fi(String p0,BaseFeed p1);
    void KM(QPhoto p0,SpannableStringBuilder p1,String p2,a p3);
    void Kh(BaseFeed p0,PlcEntryStyleInfo p1,String p2);
    void Ko(QPhoto p0,QPhoto p1,int p2,a p3);
    boolean LN(BaseFeed p0);
    void LU(Activity p0,AdDataWrapper p1,boolean p2,a p3,b[] p4);
    t MN(String p0);
    void MW(QPhoto p0,String p1);
    void Nb(String p0,int p1,int p2);
    b Ob(Activity p0,QPhoto p1);
    boolean Op(QPhoto p0);
    void Qd(GifshowActivity p0,QPhoto p1,User p2,AdUnionFollowInfo p3,String p4,String p5);
    void RQ(Context p0,BaseFeed p1,String p2);
    DialogContainerFragment ST(Activity p0,BaseFeed p1,String p2,f p3,DialogInterface$OnDismissListener p4);
    void Un();
    void Vb(PresenterV2 p0);
    void WE();
    String Y2(QPhoto p0);
    void YX(QPhoto p0,String p1);
    Triple ZF(Fragment p0);
    int Zx();
    void a60(QPhoto p0,Fragment p1,int p2);
    List b9();
    void bC(BaseFeed p0,String p1,String p2);
    void bJ(c p0);
    String e7(QPhoto p0,SpannableStringBuilder p1);
    void eW();
    b f30(BaseFragment p0,QPhoto p1,a p2,a p3);
    int gi(boolean p0);
    Object hI(BaseFeed p0,String p1,Object p2);
    String i4(QPhoto p0);
    void jD(QPhoto p0);
    void jM(JSONObject p0);
    void js(c p0);
    void k9(String p0,int p1,int p2,boolean p3);
    void l4(QPhoto p0,BaseFeed p1);
    boolean lh();
    DialogFragment lp(i0 p0,c p1,BaseFeed p2,g p3);
    void n1();
    boolean n3();
    String nZ(QPhoto p0);
    int nz(Activity p0,QPhoto p1,int p2);
    b of(QPhoto p0,a p1,a p2);
    void oh(c p0,boolean p1);
    List om();
    Class pS();
    void q60(QPhoto p0);
    boolean rN(QPhoto p0);
    Object tg(QPhoto p0,Activity p1);
    void tr(ImageButton p0,Activity p1,QPhoto p2);
    void uB(BaseFeed p0,PlcEntryStyleInfo p1,String p2);
    void v6(Activity p0,AdDataWrapper p1,a p2,b[] p3);
    boolean v7(int p0);
    void vh(boolean p0,QPhoto p1,PresenterV2 p2);
    int vq(QPhoto p0);
    b w4(BaseFragment p0,QPhoto p1,a p2,a p3);
    View wK(Activity p0,ViewGroup p1,BaseFeed p2,boolean p3);
    boolean wh(QPhoto p0);
    void wq(List p0);
    void xf(QPhoto p0,String p1);
    int yq(Fragment p0);
    boolean zT(Object p0);
}
