package nl9.v;
import tkd.b;
import ml8.c;
import com.yxcorp.gifshow.entity.QPhoto;
import java.lang.String;
import iw.a;
import android.view.View;
import android.app.Activity;
import bm9.a;
import com.yxcorp.gifshow.activity.GifshowActivity;
import com.google.gson.JsonObject;
import nl9.a;
import java.lang.Object;
import com.smile.gifmaker.mvps.presenter.PresenterV2;
import rl9.c;
import com.kuaishou.android.model.ads.PhotoAdvertisement$SearchBrandInfo;
import rl9.f;
import com.kwai.framework.model.feed.BaseFeed;
import android.view.ViewGroup;
import rl9.b;
import androidx.recyclerview.widget.RecyclerView;
import y8c.g;
import y8c.q;
import rl9.d;
import com.kuaishou.android.model.ads.PhotoAdvertisement;
import com.yxcorp.gifshow.plugin.impl.search.BannerEntity;
import k2b.e0;
import jm9.b;
import jm9.a;
import rl9.e;

public interface abstract v implements b	// class@0031ca
{

    void A2(c p0);
    String AO(QPhoto p0);
    String Ap(QPhoto p0);
    void C30(a p0);
    void Ce(c p0);
    void D00(c p0);
    void EK(View p0,View p1,Activity p2,QPhoto p3);
    boolean EP(Activity p0,a p1);
    void Ge(c p0);
    void Gf(c p0);
    boolean Gx(QPhoto p0,a p1);
    void JH(GifshowActivity p0,JsonObject p1,a p2);
    String LL(a p0);
    void N10(c p0,boolean p1);
    int N5(QPhoto p0);
    PresenterV2 O20(Object p0,boolean p1);
    void TK(c p0);
    void Tb(c p0);
    c UE();
    PhotoAdvertisement$SearchBrandInfo Ui(QPhoto p0);
    f VW();
    void Vh(c p0);
    void Xo(BaseFeed p0);
    String Y2(QPhoto p0);
    View Yl(ViewGroup p0,int p1,b p2);
    void ZC(RecyclerView p0,g p1,q p2);
    void ZK(int p0,QPhoto p1,boolean p2);
    void Zo(c p0);
    int aK(QPhoto p0);
    PresenterV2 bf(int p0);
    d cA();
    boolean cN(QPhoto p0);
    void d6(Activity p0,c p1,String p2);
    boolean dB();
    boolean gU(BaseFeed p0);
    void gZ(c p0);
    String i4(QPhoto p0);
    boolean iE(PhotoAdvertisement p0);
    boolean iI(QPhoto p0);
    void jN(c p0);
    a kb(ViewGroup p0,BannerEntity p1,e0 p2,b p3);
    void m6(c p0);
    void mG(PhotoAdvertisement p0,boolean p1);
    void nC(c p0);
    boolean nh();
    View o6(ViewGroup p0,boolean p1);
    boolean pQ(QPhoto p0);
    void qL(c p0);
    e v4();
    void v50(c p0);
    boolean w8(QPhoto p0);
    boolean x9(a p0);
}
