package com.kuaishou.bowl.event.utils.StageName;
import java.lang.Enum;
import java.lang.String;
import java.lang.Object;
import java.lang.Class;
import com.kwai.robust.PatchProxy;
import com.kwai.robust.PatchProxyResult;

public final class StageName extends Enum	// class@001201
{
    public static final StageName[] $VALUES;
    public static final StageName dynamic_jump_loss_event;
    public static final StageName link_match_end;
    public static final StageName link_match_start;
    public static final StageName link_render_end;
    public static final StageName link_render_start;
    public static final StageName link_request_end;
    public static final StageName link_request_start;
    public static final StageName link_trigger_end;
    public static final StageName link_trigger_start;
    public static final StageName pdy_component_create_rootview_end;
    public static final StageName pdy_component_create_rootview_start;
    public static final StageName pdy_component_update_rootview_end;
    public static final StageName pdy_component_update_rootview_start;
    public static final StageName pdy_create_rootview;
    public static final StageName pdy_parse_end;
    public static final StageName pdy_request_end;
    public static final StageName pdy_request_start;
    public static final StageName pendant_create_view_end;
    public static final StageName pendant_create_view_start;
    public static final StageName pendant_determine_show;
    public static final StageName pendant_match_end;
    public static final StageName pendant_match_start;
    public static final StageName pendant_mount_view_end;
    public static final StageName pendant_mount_view_start;
    public static final StageName pendant_page_agreement_request_end;
    public static final StageName pendant_page_agreement_request_start;
    public static final StageName pendant_page_match_end;
    public static final StageName pendant_page_match_start;
    public static final StageName pendant_page_trigger_end;
    public static final StageName pendant_page_trigger_start;
    public static final StageName pendant_render_view_end;
    public static final StageName pendant_render_view_start;
    public static final StageName pendant_request_end;
    public static final StageName pendant_request_start;
    public static final StageName pendant_should_show;
    public static final StageName pendant_trigger_end;
    public static final StageName pendant_trigger_start;
    public static final StageName pgy_bundle_preload_fail;
    public static final StageName pgy_bundle_preload_start;
    public static final StageName pgy_bundle_preload_success;
    public static final StageName pgy_component_bridge_dispatch;
    public static final StageName pgy_component_bridge_regis;
    public static final StageName pgy_component_degrade;
    public static final StageName pgy_component_render_fail;
    public static final StageName pgy_component_render_start;
    public static final StageName pgy_component_render_success;
    public static final StageName pgy_component_tk_render_success;
    public static final StageName pgy_component_update_end;
    public static final StageName pgy_component_update_start;
    public static final StageName pgy_engine_share_hit;
    public static final StageName pgy_feed_consume;
    public static final StageName pgy_feed_parse_end;
    public static final StageName pgy_feed_render_end;
    public static final StageName pgy_feed_request;
    public static final StageName pgy_feed_request_end;
    public static final StageName pgy_feed_request_start;
    public static final StageName pgy_init_end;
    public static final StageName pgy_init_start;
    public static final StageName pgy_mode_debug_use;
    public static final StageName pgy_page_cache_hit;
    public static final StageName pgy_page_first_request;
    public static final StageName pgy_page_network_end;
    public static final StageName pgy_page_parse_end;
    public static final StageName pgy_page_prefetch;
    public static final StageName pgy_page_prefetch_hit;
    public static final StageName pgy_page_render_end;
    public static final StageName pgy_page_request_end;

    static {
       StageName stageName = new StageName("link_trigger_start", 0, "link_trigger_start");
       StageName.link_trigger_start = stageName;
       StageName stageName1 = new StageName("link_trigger_end", 1, "link_trigger_end");
       StageName.link_trigger_end = stageName1;
       StageName stageName2 = new StageName("link_match_start", 2, "link_match_start");
       StageName.link_match_start = stageName2;
       StageName stageName3 = new StageName("link_match_end", 3, "link_match_end");
       StageName.link_match_end = stageName3;
       StageName stageName4 = new StageName("link_request_start", 4, "link_request_start");
       StageName.link_request_start = stageName4;
       StageName stageName5 = new StageName("link_request_end", 5, "link_request_end");
       StageName.link_request_end = stageName5;
       StageName stageName6 = new StageName("link_render_start", 6, "link_render_start");
       StageName.link_render_start = stageName6;
       StageName stageName7 = new StageName("link_render_end", 7, "link_render_end");
       StageName.link_render_end = stageName7;
       StageName stageName8 = new StageName("dynamic_jump_loss_event", 8, "DYNAMIC_JUMP_LOSS_EVENT");
       StageName.dynamic_jump_loss_event = stageName8;
       StageName stageName9 = new StageName("pdy_request_start", 9, "pdy_request_start");
       StageName.pdy_request_start = stageName9;
       StageName stageName10 = new StageName("pdy_request_end", 10, "pdy_request_end");
       StageName.pdy_request_end = stageName10;
       StageName stageName11 = new StageName("pdy_parse_end", 11, "pdy_parse_end");
       StageName.pdy_parse_end = stageName11;
       StageName stageName12 = new StageName("pdy_create_rootview", 12, "pdy_create_rootview");
       StageName.pdy_create_rootview = stageName12;
       StageName stageName13 = stageName12;
       StageName stageName14 = new StageName("pdy_component_create_rootview_start", 13, "pdy_component_create_rootview_start");
       StageName.pdy_component_create_rootview_start = stageName14;
       StageName stageName15 = stageName14;
       StageName stageName16 = new StageName("pdy_component_create_rootview_end", 14, "pdy_component_create_rootview_end");
       StageName.pdy_component_create_rootview_end = stageName16;
       StageName stageName17 = stageName16;
       stageName14 = new StageName("pdy_component_update_rootview_start", 15, "pdy_component_update_rootview_start");
       StageName.pdy_component_update_rootview_start = stageName14;
       StageName stageName18 = stageName14;
       stageName16 = new StageName("pdy_component_update_rootview_end", 16, "pdy_component_update_rootview_end");
       StageName.pdy_component_update_rootview_end = stageName16;
       StageName stageName19 = stageName16;
       stageName14 = new StageName("pgy_component_render_start", 17, "pgy_component_render_start");
       StageName.pgy_component_render_start = stageName14;
       StageName stageName20 = stageName14;
       stageName16 = new StageName("pgy_component_render_success", 18, "pgy_component_render_success");
       StageName.pgy_component_render_success = stageName16;
       StageName stageName21 = stageName16;
       stageName14 = new StageName("pgy_component_tk_render_success", 19, "pgy_component_tk_render_success");
       StageName.pgy_component_tk_render_success = stageName14;
       StageName stageName22 = stageName14;
       stageName16 = new StageName("pgy_component_render_fail", 20, "pgy_component_render_fail");
       StageName.pgy_component_render_fail = stageName16;
       StageName stageName23 = stageName16;
       stageName14 = new StageName("pgy_component_update_start", 21, "pgy_component_update_start");
       StageName.pgy_component_update_start = stageName14;
       StageName stageName24 = stageName14;
       stageName16 = new StageName("pgy_component_update_end", 22, "pgy_component_update_end");
       StageName.pgy_component_update_end = stageName16;
       StageName stageName25 = stageName16;
       stageName14 = new StageName("pgy_engine_share_hit", 23, "pgy_engine_share_hit");
       StageName.pgy_engine_share_hit = stageName14;
       StageName stageName26 = stageName14;
       stageName16 = new StageName("pgy_component_degrade", 24, "pgy_component_degrade");
       StageName.pgy_component_degrade = stageName16;
       StageName stageName27 = stageName16;
       stageName14 = new StageName("pgy_page_first_request", 25, "pgy_page_first_request");
       StageName.pgy_page_first_request = stageName14;
       StageName stageName28 = stageName14;
       stageName16 = new StageName("pgy_page_cache_hit", 26, "pgy_page_cache_hit");
       StageName.pgy_page_cache_hit = stageName16;
       StageName stageName29 = stageName16;
       stageName14 = new StageName("pgy_page_prefetch_hit", 27, "pgy_page_prefetch_hit");
       StageName.pgy_page_prefetch_hit = stageName14;
       StageName stageName30 = stageName14;
       stageName16 = new StageName("pgy_page_prefetch", 28, "pgy_page_prefetch");
       StageName.pgy_page_prefetch = stageName16;
       StageName stageName31 = stageName16;
       stageName14 = new StageName("pgy_bundle_preload_start", 29, "pgy_bundle_preload_start");
       StageName.pgy_bundle_preload_start = stageName14;
       StageName stageName32 = stageName14;
       stageName16 = new StageName("pgy_bundle_preload_success", 30, "pgy_bundle_preload_success");
       StageName.pgy_bundle_preload_success = stageName16;
       StageName stageName33 = stageName16;
       stageName14 = new StageName("pgy_bundle_preload_fail", 31, "pgy_bundle_preload_fail");
       StageName.pgy_bundle_preload_fail = stageName14;
       StageName stageName34 = stageName14;
       stageName16 = new StageName("pgy_init_start", 32, "pgy_init_start");
       StageName.pgy_init_start = stageName16;
       StageName stageName35 = stageName16;
       stageName14 = new StageName("pgy_init_end", 33, "pgy_init_end");
       StageName.pgy_init_end = stageName14;
       StageName stageName36 = stageName14;
       stageName16 = new StageName("pgy_page_request_end", 34, "pgy_page_request_end");
       StageName.pgy_page_request_end = stageName16;
       StageName stageName37 = stageName16;
       stageName14 = new StageName("pgy_page_parse_end", 35, "pgy_page_parse_end");
       StageName.pgy_page_parse_end = stageName14;
       StageName stageName38 = stageName14;
       stageName16 = new StageName("pgy_page_render_end", 36, "pgy_page_render_end");
       StageName.pgy_page_render_end = stageName16;
       StageName stageName39 = stageName16;
       stageName14 = new StageName("pgy_page_network_end", 37, "pgy_page_network_end");
       StageName.pgy_page_network_end = stageName14;
       StageName stageName40 = stageName14;
       stageName16 = new StageName("pgy_feed_request_start", 38, "pgy_feed_request_start");
       StageName.pgy_feed_request_start = stageName16;
       StageName stageName41 = stageName16;
       stageName14 = new StageName("pgy_feed_request_end", 39, "pgy_feed_request_end");
       StageName.pgy_feed_request_end = stageName14;
       StageName stageName42 = stageName14;
       stageName16 = new StageName("pgy_feed_parse_end", 40, "pgy_feed_parse_end");
       StageName.pgy_feed_parse_end = stageName16;
       StageName stageName43 = stageName16;
       stageName14 = new StageName("pgy_feed_render_end", 41, "pgy_feed_render_end");
       StageName.pgy_feed_render_end = stageName14;
       StageName stageName44 = stageName14;
       stageName16 = new StageName("pgy_feed_request", 42, "pgy_feed_request");
       StageName.pgy_feed_request = stageName16;
       StageName stageName45 = stageName16;
       stageName14 = new StageName("pgy_feed_consume", 43, "pgy_feed_consume");
       StageName.pgy_feed_consume = stageName14;
       StageName stageName46 = stageName14;
       stageName16 = new StageName("pgy_component_bridge_dispatch", 44, "pgy_component_bridge_dispatch");
       StageName.pgy_component_bridge_dispatch = stageName16;
       StageName stageName47 = stageName16;
       stageName14 = new StageName("pgy_component_bridge_regis", 45, "pgy_component_bridge_regis");
       StageName.pgy_component_bridge_regis = stageName14;
       StageName stageName48 = stageName14;
       stageName16 = new StageName("pendant_page_agreement_request_start", 46, "pendant_page_agreement_request_start");
       StageName.pendant_page_agreement_request_start = stageName16;
       StageName stageName49 = stageName16;
       stageName14 = new StageName("pendant_page_agreement_request_end", 47, "pendant_page_agreement_request_end");
       StageName.pendant_page_agreement_request_end = stageName14;
       StageName stageName50 = stageName14;
       stageName16 = new StageName("pendant_page_trigger_start", 48, "pendent_page_trigger_start");
       StageName.pendant_page_trigger_start = stageName16;
       StageName stageName51 = stageName16;
       stageName14 = new StageName("pendant_page_trigger_end", 49, "pendant_page_trigger_end");
       StageName.pendant_page_trigger_end = stageName14;
       StageName stageName52 = stageName14;
       stageName16 = new StageName("pendant_page_match_start", 50, "pendant_page_match_start");
       StageName.pendant_page_match_start = stageName16;
       StageName stageName53 = stageName16;
       stageName14 = new StageName("pendant_page_match_end", 51, "pendant_page_match_end");
       StageName.pendant_page_match_end = stageName14;
       StageName stageName54 = stageName14;
       stageName16 = new StageName("pendant_trigger_start", 52, "pendant_trigger_start");
       StageName.pendant_trigger_start = stageName16;
       StageName stageName55 = stageName16;
       stageName14 = new StageName("pendant_trigger_end", 53, "pendant_trigger_end");
       StageName.pendant_trigger_end = stageName14;
       StageName stageName56 = stageName14;
       stageName16 = new StageName("pendant_match_start", 54, "pendant_match_start");
       StageName.pendant_match_start = stageName16;
       StageName stageName57 = stageName16;
       stageName14 = new StageName("pendant_match_end", 55, "pendant_match_end");
       StageName.pendant_match_end = stageName14;
       StageName stageName58 = stageName14;
       stageName16 = new StageName("pendant_request_start", 56, "pendant_request_start");
       StageName.pendant_request_start = stageName16;
       StageName stageName59 = stageName16;
       stageName14 = new StageName("pendant_request_end", 57, "pendant_request_end");
       StageName.pendant_request_end = stageName14;
       StageName stageName60 = stageName14;
       stageName16 = new StageName("pendant_determine_show", 58, "pendant_determine_show");
       StageName.pendant_determine_show = stageName16;
       StageName stageName61 = stageName16;
       stageName14 = new StageName("pendant_should_show", 59, "pendant_should_show");
       StageName.pendant_should_show = stageName14;
       StageName stageName62 = stageName14;
       stageName16 = new StageName("pendant_create_view_start", 60, "pendant_create_view_start");
       StageName.pendant_create_view_start = stageName16;
       StageName stageName63 = stageName16;
       stageName14 = new StageName("pendant_create_view_end", 61, "pendant_create_view_end");
       StageName.pendant_create_view_end = stageName14;
       StageName stageName64 = stageName14;
       stageName16 = new StageName("pendant_render_view_start", 62, "pendant_render_view_start");
       StageName.pendant_render_view_start = stageName16;
       StageName stageName65 = stageName16;
       stageName14 = new StageName("pendant_render_view_end", 63, "pendant_render_view_end");
       StageName.pendant_render_view_end = stageName14;
       StageName stageName66 = stageName14;
       stageName16 = new StageName("pendant_mount_view_start", 64, "pendant_mount_view_start");
       StageName.pendant_mount_view_start = stageName16;
       StageName stageName67 = stageName16;
       stageName14 = new StageName("pendant_mount_view_end", 65, "pendant_mount_view_end");
       StageName.pendant_mount_view_end = stageName14;
       StageName stageName68 = stageName14;
       stageName16 = new StageName("pgy_mode_debug_use", 66, "pgy_mode_debug_use");
       StageName.pgy_mode_debug_use = stageName16;
       StageName[] stageNameArr = new StageName[67];
       stageNameArr[0] = stageName;
       stageNameArr[1] = stageName1;
       stageNameArr[2] = stageName2;
       stageNameArr[3] = stageName3;
       stageNameArr[4] = stageName4;
       stageNameArr[5] = stageName5;
       stageNameArr[6] = stageName6;
       stageNameArr[7] = stageName7;
       stageNameArr[8] = stageName8;
       stageNameArr[9] = stageName9;
       stageNameArr[10] = stageName10;
       stageNameArr[11] = stageName11;
       stageNameArr[12] = stageName13;
       stageNameArr[13] = stageName15;
       stageNameArr[14] = stageName17;
       stageNameArr[15] = stageName18;
       stageNameArr[16] = stageName19;
       stageNameArr[17] = stageName20;
       stageNameArr[18] = stageName21;
       stageNameArr[19] = stageName22;
       stageNameArr[20] = stageName23;
       stageNameArr[21] = stageName24;
       stageNameArr[22] = stageName25;
       stageNameArr[23] = stageName26;
       stageNameArr[24] = stageName27;
       stageNameArr[25] = stageName28;
       stageNameArr[26] = stageName29;
       stageNameArr[27] = stageName30;
       stageNameArr[28] = stageName31;
       stageNameArr[29] = stageName32;
       stageNameArr[30] = stageName33;
       stageNameArr[31] = stageName34;
       stageNameArr[32] = stageName35;
       stageNameArr[33] = stageName36;
       stageNameArr[34] = stageName37;
       stageNameArr[35] = stageName38;
       stageNameArr[36] = stageName39;
       stageNameArr[37] = stageName40;
       stageNameArr[38] = stageName41;
       stageNameArr[39] = stageName42;
       stageNameArr[40] = stageName43;
       stageNameArr[41] = stageName44;
       stageNameArr[42] = stageName45;
       stageNameArr[43] = stageName46;
       stageNameArr[44] = stageName47;
       stageNameArr[45] = stageName48;
       stageNameArr[46] = stageName49;
       stageNameArr[47] = stageName50;
       stageNameArr[48] = stageName51;
       stageNameArr[49] = stageName52;
       stageNameArr[50] = stageName53;
       stageNameArr[51] = stageName54;
       stageNameArr[52] = stageName55;
       stageNameArr[53] = stageName56;
       stageNameArr[54] = stageName57;
       stageNameArr[55] = stageName58;
       stageNameArr[56] = stageName59;
       stageNameArr[57] = stageName60;
       stageNameArr[58] = stageName61;
       stageNameArr[59] = stageName62;
       stageNameArr[60] = stageName63;
       stageNameArr[61] = stageName64;
       stageNameArr[62] = stageName65;
       stageNameArr[63] = stageName66;
       stageNameArr[64] = stageName67;
       stageNameArr[65] = stageName68;
       stageNameArr[66] = stageName16;
       StageName.$VALUES = stageNameArr;
    }
    public void StageName(String p0,int p1,String p2){
       super(p0, p1);
    }
    public static StageName valueOf(String p0){
       Object obj = PatchProxy.applyOneRefs(p0, null, StageName.class, "2");
       if (obj != PatchProxyResult.class) {
          return obj;
       }
       return Enum.valueOf(StageName.class, p0);
    }
    public static StageName[] values(){
       Object obj = PatchProxy.apply(null, null, StageName.class, "1");
       if (obj != PatchProxyResult.class) {
          return obj;
       }
       return StageName.$VALUES.clone();
    }
}
