package com.kwai.player.qos.KwaiQosInfo;
import java.lang.Object;
import android.os.Bundle;
import java.lang.Class;
import java.lang.String;
import com.kwai.robust.PatchProxy;
import com.kwai.robust.PatchProxyResult;

public class KwaiQosInfo	// class@0012fa
{
    public String aencInit;
    public int audioBufferByteLength;
    public int audioBufferTimeLength;
    public int audioDelay;
    public long audioTotalDataSize;
    public long cachedBytes;
    public String comment;
    public String currentReadUri;
    public int firstScreenTimeAllPrepared;
    public int firstScreenTimeCodecOpen;
    public int firstScreenTimeDecode;
    public int firstScreenTimeDnsAnalyze;
    public int firstScreenTimeDroppedDuration;
    public int firstScreenTimeHttpConnect;
    public int firstScreenTimeHttpFirstData;
    public int firstScreenTimeInputOpen;
    public int firstScreenTimePktReceive;
    public int firstScreenTimePreDecode;
    public int firstScreenTimeRender;
    public int firstScreenTimeStreamFind;
    public int firstScreenTimeTotal;
    public int firstScreenTimeWaitForPlay;
    public String hostInfo;
    public int reopenCntBySeek;
    public int repSwitchCnt;
    public long totalBytes;
    public long totalDataSize;
    public int totalDroppedDuration;
    public String vencDynamic;
    public String vencInit;
    public int videoBufferByteLength;
    public int videoBufferTimeLength;
    public int videoDelayAftDec;
    public int videoDelayBefDec;
    public int videoDelayRecv;
    public int videoDelayRender;
    public long videoTotalDataSize;
    public static final String AENC_INIT = "aenc_init";
    public static final String AUDIO_BUFFER_BYTE = "audio_buffer_byte";
    public static final String AUDIO_BUFFER_TIME = "audio_buffer_time";
    public static final String AUDIO_DELAY = "audio_delay";
    public static final String AUDIO_TOTAL_DATA_SIZE = "audio_total_data_size";
    public static final String CACHED_BYTES = "cached_bytes";
    public static final String COMMENT = "comment";
    public static final String CURRENT_READ_URI = "current_read_uri";
    public static final String DROPPED_DURATION = "dropped_duration";
    public static final String FST_ALL_PREPARED = "fst_all_prepared";
    public static final String FST_CODEC_OPEN = "fst_codec_open";
    public static final String FST_DNA_ANALYZE = "fst_dns_analyze";
    public static final String FST_DROPPED_DURATION = "fst_dropped_duration";
    public static final String FST_HTTP_CONNECT = "fst_http_connect";
    public static final String FST_HTTP_FIRST_DATA = "fst_http_first_data";
    public static final String FST_INPUT_OPEN = "fst_input_open";
    public static final String FST_STREAM_FIND = "fst_stream_find";
    public static final String FST_TOTAL = "fst_total";
    public static final String FST_VIDEO_DEC = "fst_video_dec";
    public static final String FST_VIDEO_PKT_RECV = "fst_video_pkt_recv";
    public static final String FST_VIDEO_PRE_DEC = "fst_video_pre_dec";
    public static final String FST_VIDEO_RENDER = "fst_video_render";
    public static final String FST_WAIT_FOR_PLAY = "fst_wait_for_play";
    public static final String HOST_INFO = "host_info";
    public static final String LIVE_ADAPTIVE_REP_SWITCH_CNT = "live_adaptive_rep_switch_cnt";
    public static final String REOPEN_CNT_BY_SEEK = "reopen_cnt_by_seek";
    public static final String TOTAL_BYTES = "total_bytes";
    public static final String TOTAL_DATA_BYTES = "total_data_bytes";
    public static final String VENC_DYNAMIC = "venc_dynamic";
    public static final String VENC_INIT = "venc_init";
    public static final String VIDEO_BUFFER_BYTE = "video_buffer_byte";
    public static final String VIDEO_BUFFER_TIME = "video_buffer_time";
    public static final String VIDEO_DELAY_AFT_DEC = "video_delay_aft_dec";
    public static final String VIDEO_DELAY_BEF_DEC = "video_delay_bef_dec";
    public static final String VIDEO_DELAY_RECV = "video_delay_recv";
    public static final String VIDEO_DELAY_RENDER = "video_delay_render";
    public static final String VIDEO_TOTAL_DATA_SIZE = "video_total_data_size";

    public void KwaiQosInfo(){
       super();
       this.audioBufferByteLength = 0;
       this.audioBufferTimeLength = 0;
       this.audioTotalDataSize = 0;
       this.videoBufferByteLength = 0;
       this.videoBufferTimeLength = 0;
       this.videoTotalDataSize = 0;
       this.totalDataSize = 0;
       this.audioDelay = 0;
       this.videoDelayRecv = 0;
       this.videoDelayBefDec = 0;
       this.videoDelayAftDec = 0;
       this.videoDelayRender = 0;
       this.firstScreenTimeTotal = 0;
       this.firstScreenTimeDnsAnalyze = 0;
       this.firstScreenTimeHttpConnect = 0;
       this.firstScreenTimeHttpFirstData = 0;
       this.firstScreenTimeInputOpen = 0;
       this.firstScreenTimeStreamFind = 0;
       this.firstScreenTimeCodecOpen = 0;
       this.firstScreenTimePktReceive = 0;
       this.firstScreenTimePreDecode = 0;
       this.firstScreenTimeDecode = 0;
       this.firstScreenTimeRender = 0;
       this.hostInfo = "";
       this.vencInit = "";
       this.vencDynamic = "";
       this.repSwitchCnt = 0;
    }
    public static KwaiQosInfo fromBundle(Bundle p0){
       Object obj = null;
       KwaiQosInfo obj1 = PatchProxy.applyOneRefs(p0, obj, KwaiQosInfo.class, "1");
       if (obj1 != PatchProxyResult.class) {
          return obj1;
       }
       if (p0 == null) {
          return obj;
       }
       obj1 = new KwaiQosInfo();
       obj1.audioBufferByteLength = p0.getInt("audio_buffer_byte", 0);
       obj1.audioBufferTimeLength = p0.getInt("audio_buffer_time", 0);
       obj1.audioTotalDataSize = p0.getLong("audio_total_data_size", 0);
       obj1.videoBufferByteLength = p0.getInt("video_buffer_byte", 0);
       obj1.videoBufferTimeLength = p0.getInt("video_buffer_time", 0);
       obj1.videoTotalDataSize = p0.getLong("video_total_data_size", 0);
       obj1.totalDataSize = p0.getLong("total_data_bytes", 0);
       obj1.audioDelay = p0.getInt("audio_delay", 0);
       obj1.videoDelayRecv = p0.getInt("video_delay_recv", 0);
       obj1.videoDelayBefDec = p0.getInt("video_delay_bef_dec", 0);
       obj1.videoDelayAftDec = p0.getInt("video_delay_aft_dec", 0);
       obj1.videoDelayRender = p0.getInt("video_delay_render", 0);
       obj1.firstScreenTimeTotal = p0.getInt("fst_total", 0);
       obj1.firstScreenTimeDnsAnalyze = p0.getInt("fst_dns_analyze", 0);
       obj1.firstScreenTimeHttpConnect = p0.getInt("fst_http_connect", 0);
       obj1.firstScreenTimeHttpFirstData = p0.getInt("fst_http_first_data", 0);
       obj1.firstScreenTimeInputOpen = p0.getInt("fst_input_open", 0);
       obj1.firstScreenTimeStreamFind = p0.getInt("fst_stream_find", 0);
       obj1.firstScreenTimeCodecOpen = p0.getInt("fst_codec_open", 0);
       obj1.firstScreenTimeAllPrepared = p0.getInt("fst_all_prepared", 0);
       obj1.firstScreenTimeWaitForPlay = p0.getInt("fst_wait_for_play", 0);
       obj1.firstScreenTimePktReceive = p0.getInt("fst_video_pkt_recv", 0);
       obj1.firstScreenTimePreDecode = p0.getInt("fst_video_pre_dec", 0);
       obj1.firstScreenTimeDecode = p0.getInt("fst_video_dec", 0);
       obj1.firstScreenTimeRender = p0.getInt("fst_video_render", 0);
       obj1.firstScreenTimeDroppedDuration = p0.getInt("fst_dropped_duration", 0);
       obj1.totalDroppedDuration = p0.getInt("dropped_duration", 0);
       obj1.hostInfo = p0.getString("host_info");
       obj1.vencInit = p0.getString("venc_init");
       obj1.aencInit = p0.getString("aenc_init");
       obj1.vencDynamic = p0.getString("venc_dynamic");
       obj1.comment = p0.getString("comment");
       obj1.currentReadUri = p0.getString("current_read_uri");
       obj1.cachedBytes = p0.getLong("cached_bytes", 0);
       obj1.totalBytes = p0.getLong("total_bytes", 0);
       obj1.reopenCntBySeek = p0.getInt("reopen_cnt_by_seek");
       obj1.repSwitchCnt = p0.getInt("live_adaptive_rep_switch_cnt");
       return obj1;
    }
}
