package com.kuaishou.edit.draft.c;
import com.google.protobuf.MessageLiteOrBuilder;
import com.kuaishou.edit.draft.AEEffect;
import java.util.List;
import java.lang.String;
import com.google.protobuf.ByteString;
import com.kuaishou.edit.draft.AuditFrame;
import com.kuaishou.edit.draft.AssetSegment;
import com.kuaishou.edit.draft.Template;
import com.kuaishou.edit.draft.Attributes;
import com.kuaishou.edit.draft.Beauty;
import com.kuaishou.edit.draft.ColorFilter;
import com.kuaishou.edit.draft.CropOptions;
import com.kuaishou.edit.draft.Encode;
import com.kuaishou.edit.draft.FineTuningParam;
import com.kuaishou.edit.draft.GeoLocation;
import com.kuaishou.edit.draft.Makeup;
import com.kuaishou.edit.draft.Asset$PositionType;
import com.kuaishou.edit.draft.TimeRange;
import com.kuaishou.edit.draft.Asset$ShootInfo;
import com.kuaishou.edit.draft.Asset;
import com.kuaishou.edit.draft.Transform;
import com.kuaishou.edit.draft.AssetTransition;
import com.kuaishou.edit.draft.Asset$Type;
import com.kuaishou.edit.draft.VisualEffect;

public interface abstract c implements MessageLiteOrBuilder	// class@001929
{

    AEEffect getAe2Effects(int p0);
    int getAe2EffectsCount();
    List getAe2EffectsList();
    String getAlbumId();
    ByteString getAlbumIdBytes();
    AuditFrame getAssetAuditFrame(int p0);
    int getAssetAuditFrameCount();
    List getAssetAuditFrameList();
    AssetSegment getAssetSegment(int p0);
    int getAssetSegmentCount();
    List getAssetSegmentList();
    Template getAtlasTemplate();
    Attributes getAttributes();
    String getAudioPath();
    ByteString getAudioPathBytes();
    Beauty getBeauty(int p0);
    int getBeautyCount();
    List getBeautyList();
    ColorFilter getColorFilter(int p0);
    int getColorFilterCount();
    List getColorFilterList();
    CropOptions getCropOptions();
    boolean getDisableThemeEffect();
    double getDuration();
    Encode getEncodeInfo();
    String getFile();
    ByteString getFileBytes();
    FineTuningParam getFineTuningParam();
    String getIdentifier();
    ByteString getIdentifierBytes();
    boolean getIsSolitaire();
    boolean getIsVocal();
    GeoLocation getLocation();
    Makeup getMakeup(int p0);
    int getMakeupCount();
    List getMakeupList();
    double getOriginPicHeight();
    double getOriginPicWidth();
    String getPictureCropFile();
    ByteString getPictureCropFileBytes();
    Asset$PositionType getPositionType();
    int getPositionTypeValue();
    double getPreviewPicHeight();
    double getPreviewPicWidth();
    int getRotate();
    TimeRange getSelectedRange();
    Asset$ShootInfo getShootInfo();
    double getSpeed();
    Asset getSubAsset(int p0);
    int getSubAssetCount();
    List getSubAssetList();
    Transform getTransform();
    AssetTransition getTransition();
    Asset$Type getType();
    int getTypeValue();
    VisualEffect getVisualEffects(int p0);
    int getVisualEffectsCount();
    List getVisualEffectsList();
    boolean hasAtlasTemplate();
    boolean hasAttributes();
    boolean hasCropOptions();
    boolean hasEncodeInfo();
    boolean hasFineTuningParam();
    boolean hasLocation();
    boolean hasSelectedRange();
    boolean hasShootInfo();
    boolean hasTransform();
    boolean hasTransition();
}
