package bs2.a;
import java.lang.String;
import brd.t;
import java.lang.Integer;
import okhttp3.MultipartBody$Part;
import java.lang.Boolean;

public interface abstract a	// class@00043d
{

    t A(String p0,String p1,String p2);
    t A0(String p0,String p1);
    t B(String p0,String p1,String p2);
    t B0(String p0,String p1,int p2);
    t C(int p0);
    t C0(String p0,String p1,String p2);
    t D(String p0,String p1);
    t D0();
    t E(String p0,String p1);
    t E0(String p0,String p1,Integer p2);
    t F(String p0,String p1,String p2);
    t F0(String p0,String p1,String p2);
    t G(String p0,String p1,int p2,int p3);
    t G0(String p0,String p1,String p2);
    t H(String p0,String p1,MultipartBody$Part p2);
    t H0(String p0,String p1,MultipartBody$Part p2,String p3,boolean p4);
    t I(String p0,String p1);
    t I0(String p0,String p1,String p2,String p3);
    t J(String p0,String p1,boolean p2);
    t J0(String p0,String p1);
    t K(String p0,String p1);
    t L(String p0,String p1,String p2,String p3);
    t M(String p0,String p1);
    t N(String p0,String p1,long p2);
    t O(String p0,String p1);
    t P(String p0,String p1);
    t Q(String p0,String p1,int p2,int p3,String p4);
    t R(String p0,String p1,String p2,int p3);
    t S(String p0,String p1,String p2,String p3);
    t T(String p0);
    t U(String p0,String p1);
    t V(String p0,String p1,String p2);
    t W(String p0,String p1);
    t X(String p0,String p1,String p2,String p3);
    t Y(String p0,String p1);
    t Z(String p0);
    t a(String p0);
    t a0(String p0,boolean p1,String p2,int p3,long p4,String p5);
    t b(String p0,String p1,int p2,int p3,String p4);
    t b0(String p0,String p1,String p2);
    t c(String p0,String p1,String p2,String p3,String p4);
    t c0();
    t d();
    t d0(String p0,String p1,int p2,boolean p3);
    t e(String p0,String p1,String p2);
    t e0(String p0,String p1,String p2,int p3);
    t f(String p0);
    t f0(String p0,String p1);
    t g(String p0,String p1,String p2);
    t g0(String p0,String p1,int p2,boolean p3);
    t h(String p0,String p1);
    t h0(String p0,String p1,boolean p2);
    t i(String p0,String p1,long p2,Integer p3,Integer p4,String p5);
    t i0(String p0,String p1,int p2);
    t j(String p0,String p1);
    t j0(String p0);
    t k(String p0,String p1);
    t k0(String p0,String p1);
    t l(String p0,String p1,String p2);
    t l0(int p0,String p1,int p2,String p3,String p4);
    t m(String p0,String p1,int p2);
    t m0(String p0,String p1,int p2);
    t n(String p0,String p1);
    t n0(String p0,String p1);
    t o(String p0,String p1,int p2);
    t o0(String p0,String p1);
    t p(String p0,String p1,int p2);
    t p0(String p0,String p1,String p2,String p3);
    t q(String p0,String p1,int p2);
    t q0(String p0,String p1);
    t r(String p0,String p1,int p2,String p3,int p4);
    t r0(String p0,String p1);
    t s(String p0,String p1,String p2,String p3);
    t s0(String p0,String p1,String p2);
    t t(String p0,String p1,int p2);
    t t0(String p0,String p1,String p2);
    t u(String p0,String p1,long p2);
    t u0(String p0,String p1,String p2);
    t v(String p0,String p1);
    t v0(String p0,String p1,int p2,int p3,String p4);
    t w(String p0,String p1,String p2,int p3);
    t w0(int p0,int p1,String p2);
    t x(String p0,String p1,String p2,String p3);
    t x0(String p0,String p1,int p2);
    t y(String p0,String p1,boolean p2);
    t y0(String p0,String p1,int p2,String p3,int p4);
    t z(long p0);
    t z0(String p0,String p1,String p2,int p3,int p4,Boolean p5,Boolean p6,Boolean p7);
}
