package com.kwai.feature.api.live.merchant.authority.LiveAnchorFunction;
import java.lang.Enum;
import java.lang.String;
import java.lang.Object;
import java.lang.Class;
import com.kwai.robust.PatchProxy;
import com.kwai.robust.PatchProxyResult;

public final class LiveAnchorFunction extends Enum	// class@000fd4
{
    public static final LiveAnchorFunction[] $VALUES;
    public static final LiveAnchorFunction APPLY_MUSIC_STATION;
    public static final LiveAnchorFunction AUDIO_LIVE;
    public static final LiveAnchorFunction BACKGROUND_MUSIC_TIP;
    public static final LiveAnchorFunction CHAT_AUDIENCE_APPLY;
    public static final LiveAnchorFunction CHAT_BETWEEN_ANCHORS;
    public static final LiveAnchorFunction COMMON_RED_PACKET;
    public static final LiveAnchorFunction GIFT_EFFECT_DURING_PK;
    public static final LiveAnchorFunction LINE_LIVE;
    public static final LiveAnchorFunction LIVE_4GQCI;
    public static final LiveAnchorFunction LIVE_ANCHOR_BUY_PUSH;
    public static final LiveAnchorFunction LIVE_ANCHOR_REPORT_USER_H5;
    public static final LiveAnchorFunction LIVE_ANCHOR_VOTE;
    public static final LiveAnchorFunction LIVE_ANNOUNCE;
    public static final LiveAnchorFunction LIVE_ANONYMOUS_LIVE;
    public static final LiveAnchorFunction LIVE_ANONYMOUS_LIVE_DEFAULT_SWITCH;
    public static final LiveAnchorFunction LIVE_ASK;
    public static final LiveAnchorFunction LIVE_BLIND_DATE;
    public static final LiveAnchorFunction LIVE_CHAT_WITH_GUEST_DEFAULT_OPEN;
    public static final LiveAnchorFunction LIVE_COMMENT_MERGE_GIFT_FEED;
    public static final LiveAnchorFunction LIVE_DISABLE_COMMON_RED_PACKET_NEW_STYLE;
    public static final LiveAnchorFunction LIVE_DISABLE_FANS_GROUP_CONDITION_RED_PACKET;
    public static final LiveAnchorFunction LIVE_DISABLE_GIFT_CONDITION_RED_PACKET;
    public static final LiveAnchorFunction LIVE_DISABLE_SHARE_CONDITION_RED_PACKET;
    public static final LiveAnchorFunction LIVE_ESCROW;
    public static final LiveAnchorFunction LIVE_GIFT_SENDER_TOP;
    public static final LiveAnchorFunction LIVE_HIGH_LIGHT_IN_BOTTOM_BAR;
    public static final LiveAnchorFunction LIVE_MERCHANT_STICKER;
    public static final LiveAnchorFunction LIVE_NORMAL_STICKER;
    public static final LiveAnchorFunction LIVE_PAID_SHOW;
    public static final LiveAnchorFunction LIVE_PK_CHANGE_FORMAT;
    public static final LiveAnchorFunction LIVE_PK_RECOMMEND_REPORT;
    public static final LiveAnchorFunction LIVE_PLAYBACK_SWITCH;
    public static final LiveAnchorFunction LIVE_PRIVATE;
    public static final LiveAnchorFunction LIVE_QUIT_LIVE_GUIDE;
    public static final LiveAnchorFunction LIVE_RE_PUSH;
    public static final LiveAnchorFunction LIVE_SHOP_ENTRANCE;
    public static final LiveAnchorFunction LIVE_TOPIC;
    public static final LiveAnchorFunction LIVE_VIP_GRADE;
    public static final LiveAnchorFunction LIVE_VIP_GRADE_WATCHING_LIST;
    public static final LiveAnchorFunction LIVE_WEEKLY_RANK_SHOW;
    public static final LiveAnchorFunction LUCKY_STAR;
    public static final LiveAnchorFunction Live_PK_ENTRY_PANEL_TAB_SELECT_REMEMBER;
    public static final LiveAnchorFunction MAGIC_GIFT_LOCAL_RENDER;
    public static final LiveAnchorFunction MULTI_CHAT;
    public static final LiveAnchorFunction MULTI_PK;
    public static final LiveAnchorFunction ONE_KS_COIN_DRAWING_GIFT;
    public static final LiveAnchorFunction PET;
    public static final LiveAnchorFunction PK;
    public static final LiveAnchorFunction PROFESSIONAL_MERCHANT;
    public static final LiveAnchorFunction RED_PACKET_LIVE_CLOSE_TIP;
    public static final LiveAnchorFunction ROBOT;
    public static final LiveAnchorFunction SHARE_GUIDE;
    public static final LiveAnchorFunction SHARE_RED_PACKET;
    public static final LiveAnchorFunction START_CHAT_BETWEEN_ANCHORS_GUIDE;
    public static final LiveAnchorFunction START_PK_GUIDE;
    public static final LiveAnchorFunction VOICE_COMMENT;
    public static final LiveAnchorFunction VOICE_PARTY;
    public static final LiveAnchorFunction VOICE_PARTY_AUTO_INVITE_SETTING;
    public static final LiveAnchorFunction VOICE_PARTY_DEFAULT_OPEN_VIDEO;
    public static final LiveAnchorFunction VOICE_PARTY_ENTRANCE_ON_VOICE_PARTY_TAB;
    public static final LiveAnchorFunction VOICE_PARTY_KTV;
    public static final LiveAnchorFunction VOICE_PARTY_OPEN_VIDEO;
    public static final LiveAnchorFunction VOICE_PARTY_SEND_GIFT_TO_GUEST_COMMISSION;
    public static final LiveAnchorFunction VOICE_PARTY_TEAM_PK;
    public static final LiveAnchorFunction VOICE_PARTY_THEATRE;
    public static final LiveAnchorFunction VOICE_PARTY_UPLOAD_BACKGROUND;

    static {
       LiveAnchorFunction liveAnchorFu = new LiveAnchorFunction("VOICE_COMMENT", 0);
       LiveAnchorFunction.VOICE_COMMENT = liveAnchorFu;
       LiveAnchorFunction liveAnchorFu1 = new LiveAnchorFunction("VOICE_PARTY", 1);
       LiveAnchorFunction.VOICE_PARTY = liveAnchorFu1;
       LiveAnchorFunction liveAnchorFu2 = new LiveAnchorFunction("AUDIO_LIVE", 2);
       LiveAnchorFunction.AUDIO_LIVE = liveAnchorFu2;
       LiveAnchorFunction liveAnchorFu3 = new LiveAnchorFunction("LINE_LIVE", 3);
       LiveAnchorFunction.LINE_LIVE = liveAnchorFu3;
       LiveAnchorFunction liveAnchorFu4 = new LiveAnchorFunction("PK", 4);
       LiveAnchorFunction.PK = liveAnchorFu4;
       LiveAnchorFunction liveAnchorFu5 = new LiveAnchorFunction("MULTI_PK", 5);
       LiveAnchorFunction.MULTI_PK = liveAnchorFu5;
       LiveAnchorFunction liveAnchorFu6 = new LiveAnchorFunction("MULTI_CHAT", 6);
       LiveAnchorFunction.MULTI_CHAT = liveAnchorFu6;
       LiveAnchorFunction liveAnchorFu7 = new LiveAnchorFunction("ROBOT", 7);
       LiveAnchorFunction.ROBOT = liveAnchorFu7;
       LiveAnchorFunction liveAnchorFu8 = new LiveAnchorFunction("BACKGROUND_MUSIC_TIP", 8);
       LiveAnchorFunction.BACKGROUND_MUSIC_TIP = liveAnchorFu8;
       LiveAnchorFunction liveAnchorFu9 = new LiveAnchorFunction("RED_PACKET_LIVE_CLOSE_TIP", 9);
       LiveAnchorFunction.RED_PACKET_LIVE_CLOSE_TIP = liveAnchorFu9;
       LiveAnchorFunction liveAnchorFu10 = new LiveAnchorFunction("APPLY_MUSIC_STATION", 10);
       LiveAnchorFunction.APPLY_MUSIC_STATION = liveAnchorFu10;
       LiveAnchorFunction liveAnchorFu11 = new LiveAnchorFunction("START_PK_GUIDE", 11);
       LiveAnchorFunction.START_PK_GUIDE = liveAnchorFu11;
       LiveAnchorFunction liveAnchorFu12 = new LiveAnchorFunction("CHAT_BETWEEN_ANCHORS", 12);
       LiveAnchorFunction.CHAT_BETWEEN_ANCHORS = liveAnchorFu12;
       LiveAnchorFunction liveAnchorFu13 = new LiveAnchorFunction("START_CHAT_BETWEEN_ANCHORS_GUIDE", 13);
       LiveAnchorFunction.START_CHAT_BETWEEN_ANCHORS_GUIDE = liveAnchorFu13;
       LiveAnchorFunction liveAnchorFu14 = liveAnchorFu13;
       LiveAnchorFunction liveAnchorFu15 = new LiveAnchorFunction("CHAT_AUDIENCE_APPLY", 14);
       LiveAnchorFunction.CHAT_AUDIENCE_APPLY = liveAnchorFu15;
       LiveAnchorFunction liveAnchorFu16 = liveAnchorFu15;
       LiveAnchorFunction liveAnchorFu17 = new LiveAnchorFunction("VOICE_PARTY_OPEN_VIDEO", 15);
       LiveAnchorFunction.VOICE_PARTY_OPEN_VIDEO = liveAnchorFu17;
       LiveAnchorFunction liveAnchorFu18 = liveAnchorFu17;
       liveAnchorFu13 = new LiveAnchorFunction("VOICE_PARTY_DEFAULT_OPEN_VIDEO", 16);
       LiveAnchorFunction.VOICE_PARTY_DEFAULT_OPEN_VIDEO = liveAnchorFu13;
       LiveAnchorFunction liveAnchorFu19 = liveAnchorFu13;
       liveAnchorFu15 = new LiveAnchorFunction("GIFT_EFFECT_DURING_PK", 17);
       LiveAnchorFunction.GIFT_EFFECT_DURING_PK = liveAnchorFu15;
       LiveAnchorFunction liveAnchorFu20 = liveAnchorFu15;
       liveAnchorFu17 = new LiveAnchorFunction("VOICE_PARTY_ENTRANCE_ON_VOICE_PARTY_TAB", 18);
       LiveAnchorFunction.VOICE_PARTY_ENTRANCE_ON_VOICE_PARTY_TAB = liveAnchorFu17;
       LiveAnchorFunction liveAnchorFu21 = liveAnchorFu17;
       liveAnchorFu13 = new LiveAnchorFunction("ONE_KS_COIN_DRAWING_GIFT", 19);
       LiveAnchorFunction.ONE_KS_COIN_DRAWING_GIFT = liveAnchorFu13;
       LiveAnchorFunction liveAnchorFu22 = liveAnchorFu13;
       liveAnchorFu15 = new LiveAnchorFunction("VOICE_PARTY_UPLOAD_BACKGROUND", 20);
       LiveAnchorFunction.VOICE_PARTY_UPLOAD_BACKGROUND = liveAnchorFu15;
       LiveAnchorFunction liveAnchorFu23 = liveAnchorFu15;
       liveAnchorFu17 = new LiveAnchorFunction("VOICE_PARTY_SEND_GIFT_TO_GUEST_COMMISSION", 21);
       LiveAnchorFunction.VOICE_PARTY_SEND_GIFT_TO_GUEST_COMMISSION = liveAnchorFu17;
       LiveAnchorFunction liveAnchorFu24 = liveAnchorFu17;
       liveAnchorFu13 = new LiveAnchorFunction("SHARE_GUIDE", 22);
       LiveAnchorFunction.SHARE_GUIDE = liveAnchorFu13;
       LiveAnchorFunction liveAnchorFu25 = liveAnchorFu13;
       liveAnchorFu17 = new LiveAnchorFunction("COMMON_RED_PACKET", 23);
       LiveAnchorFunction.COMMON_RED_PACKET = liveAnchorFu17;
       LiveAnchorFunction liveAnchorFu26 = liveAnchorFu17;
       liveAnchorFu15 = new LiveAnchorFunction("SHARE_RED_PACKET", 24);
       LiveAnchorFunction.SHARE_RED_PACKET = liveAnchorFu15;
       LiveAnchorFunction liveAnchorFu27 = liveAnchorFu15;
       liveAnchorFu17 = new LiveAnchorFunction("VOICE_PARTY_KTV", 25);
       LiveAnchorFunction.VOICE_PARTY_KTV = liveAnchorFu17;
       LiveAnchorFunction liveAnchorFu28 = liveAnchorFu17;
       liveAnchorFu15 = new LiveAnchorFunction("VOICE_PARTY_THEATRE", 26);
       LiveAnchorFunction.VOICE_PARTY_THEATRE = liveAnchorFu15;
       LiveAnchorFunction liveAnchorFu29 = liveAnchorFu15;
       liveAnchorFu17 = new LiveAnchorFunction("VOICE_PARTY_TEAM_PK", 27);
       LiveAnchorFunction.VOICE_PARTY_TEAM_PK = liveAnchorFu17;
       LiveAnchorFunction liveAnchorFu30 = liveAnchorFu17;
       liveAnchorFu15 = new LiveAnchorFunction("PET", 28);
       LiveAnchorFunction.PET = liveAnchorFu15;
       LiveAnchorFunction liveAnchorFu31 = liveAnchorFu15;
       liveAnchorFu17 = new LiveAnchorFunction("LIVE_SHOP_ENTRANCE", 29);
       LiveAnchorFunction.LIVE_SHOP_ENTRANCE = liveAnchorFu17;
       LiveAnchorFunction liveAnchorFu32 = liveAnchorFu17;
       liveAnchorFu15 = new LiveAnchorFunction("PROFESSIONAL_MERCHANT", 30);
       LiveAnchorFunction.PROFESSIONAL_MERCHANT = liveAnchorFu15;
       LiveAnchorFunction liveAnchorFu33 = liveAnchorFu15;
       liveAnchorFu17 = new LiveAnchorFunction("MAGIC_GIFT_LOCAL_RENDER", 31);
       LiveAnchorFunction.MAGIC_GIFT_LOCAL_RENDER = liveAnchorFu17;
       LiveAnchorFunction liveAnchorFu34 = liveAnchorFu17;
       liveAnchorFu15 = new LiveAnchorFunction("LIVE_ANCHOR_REPORT_USER_H5", 32);
       LiveAnchorFunction.LIVE_ANCHOR_REPORT_USER_H5 = liveAnchorFu15;
       LiveAnchorFunction liveAnchorFu35 = liveAnchorFu15;
       liveAnchorFu17 = new LiveAnchorFunction("LIVE_ANCHOR_VOTE", 33);
       LiveAnchorFunction.LIVE_ANCHOR_VOTE = liveAnchorFu17;
       LiveAnchorFunction liveAnchorFu36 = liveAnchorFu17;
       liveAnchorFu15 = new LiveAnchorFunction("VOICE_PARTY_AUTO_INVITE_SETTING", 34);
       LiveAnchorFunction.VOICE_PARTY_AUTO_INVITE_SETTING = liveAnchorFu15;
       LiveAnchorFunction liveAnchorFu37 = liveAnchorFu15;
       liveAnchorFu17 = new LiveAnchorFunction("LIVE_PRIVATE", 35);
       LiveAnchorFunction.LIVE_PRIVATE = liveAnchorFu17;
       LiveAnchorFunction liveAnchorFu38 = liveAnchorFu17;
       liveAnchorFu15 = new LiveAnchorFunction("LIVE_ASK", 36);
       LiveAnchorFunction.LIVE_ASK = liveAnchorFu15;
       LiveAnchorFunction liveAnchorFu39 = liveAnchorFu15;
       liveAnchorFu17 = new LiveAnchorFunction("LIVE_ESCROW", 37);
       LiveAnchorFunction.LIVE_ESCROW = liveAnchorFu17;
       LiveAnchorFunction liveAnchorFu40 = liveAnchorFu17;
       liveAnchorFu15 = new LiveAnchorFunction("LIVE_PK_CHANGE_FORMAT", 38);
       LiveAnchorFunction.LIVE_PK_CHANGE_FORMAT = liveAnchorFu15;
       LiveAnchorFunction liveAnchorFu41 = liveAnchorFu15;
       liveAnchorFu17 = new LiveAnchorFunction("LUCKY_STAR", 39);
       LiveAnchorFunction.LUCKY_STAR = liveAnchorFu17;
       LiveAnchorFunction liveAnchorFu42 = liveAnchorFu17;
       liveAnchorFu15 = new LiveAnchorFunction("LIVE_COMMENT_MERGE_GIFT_FEED", 40);
       LiveAnchorFunction.LIVE_COMMENT_MERGE_GIFT_FEED = liveAnchorFu15;
       LiveAnchorFunction liveAnchorFu43 = liveAnchorFu15;
       liveAnchorFu17 = new LiveAnchorFunction("LIVE_NORMAL_STICKER", 41);
       LiveAnchorFunction.LIVE_NORMAL_STICKER = liveAnchorFu17;
       LiveAnchorFunction liveAnchorFu44 = liveAnchorFu17;
       liveAnchorFu15 = new LiveAnchorFunction("LIVE_MERCHANT_STICKER", 42);
       LiveAnchorFunction.LIVE_MERCHANT_STICKER = liveAnchorFu15;
       LiveAnchorFunction liveAnchorFu45 = liveAnchorFu15;
       liveAnchorFu17 = new LiveAnchorFunction("LIVE_4GQCI", 43);
       LiveAnchorFunction.LIVE_4GQCI = liveAnchorFu17;
       LiveAnchorFunction liveAnchorFu46 = liveAnchorFu17;
       liveAnchorFu15 = new LiveAnchorFunction("LIVE_PAID_SHOW", 44);
       LiveAnchorFunction.LIVE_PAID_SHOW = liveAnchorFu15;
       LiveAnchorFunction liveAnchorFu47 = liveAnchorFu15;
       liveAnchorFu17 = new LiveAnchorFunction("LIVE_GIFT_SENDER_TOP", 45);
       LiveAnchorFunction.LIVE_GIFT_SENDER_TOP = liveAnchorFu17;
       LiveAnchorFunction liveAnchorFu48 = liveAnchorFu17;
       liveAnchorFu15 = new LiveAnchorFunction("LIVE_PK_RECOMMEND_REPORT", 46);
       LiveAnchorFunction.LIVE_PK_RECOMMEND_REPORT = liveAnchorFu15;
       LiveAnchorFunction liveAnchorFu49 = liveAnchorFu15;
       liveAnchorFu17 = new LiveAnchorFunction("Live_PK_ENTRY_PANEL_TAB_SELECT_REMEMBER", 47);
       LiveAnchorFunction.Live_PK_ENTRY_PANEL_TAB_SELECT_REMEMBER = liveAnchorFu17;
       LiveAnchorFunction liveAnchorFu50 = liveAnchorFu17;
       liveAnchorFu15 = new LiveAnchorFunction("LIVE_ANCHOR_BUY_PUSH", 48);
       LiveAnchorFunction.LIVE_ANCHOR_BUY_PUSH = liveAnchorFu15;
       LiveAnchorFunction liveAnchorFu51 = liveAnchorFu15;
       liveAnchorFu17 = new LiveAnchorFunction("LIVE_WEEKLY_RANK_SHOW", 49);
       LiveAnchorFunction.LIVE_WEEKLY_RANK_SHOW = liveAnchorFu17;
       LiveAnchorFunction liveAnchorFu52 = liveAnchorFu17;
       liveAnchorFu15 = new LiveAnchorFunction("LIVE_CHAT_WITH_GUEST_DEFAULT_OPEN", 50);
       LiveAnchorFunction.LIVE_CHAT_WITH_GUEST_DEFAULT_OPEN = liveAnchorFu15;
       LiveAnchorFunction liveAnchorFu53 = liveAnchorFu15;
       liveAnchorFu17 = new LiveAnchorFunction("LIVE_DISABLE_COMMON_RED_PACKET_NEW_STYLE", 51);
       LiveAnchorFunction.LIVE_DISABLE_COMMON_RED_PACKET_NEW_STYLE = liveAnchorFu17;
       LiveAnchorFunction liveAnchorFu54 = liveAnchorFu17;
       liveAnchorFu15 = new LiveAnchorFunction("LIVE_DISABLE_FANS_GROUP_CONDITION_RED_PACKET", 52);
       LiveAnchorFunction.LIVE_DISABLE_FANS_GROUP_CONDITION_RED_PACKET = liveAnchorFu15;
       LiveAnchorFunction liveAnchorFu55 = liveAnchorFu15;
       liveAnchorFu17 = new LiveAnchorFunction("LIVE_DISABLE_GIFT_CONDITION_RED_PACKET", 53);
       LiveAnchorFunction.LIVE_DISABLE_GIFT_CONDITION_RED_PACKET = liveAnchorFu17;
       LiveAnchorFunction liveAnchorFu56 = liveAnchorFu17;
       liveAnchorFu15 = new LiveAnchorFunction("LIVE_DISABLE_SHARE_CONDITION_RED_PACKET", 54);
       LiveAnchorFunction.LIVE_DISABLE_SHARE_CONDITION_RED_PACKET = liveAnchorFu15;
       LiveAnchorFunction liveAnchorFu57 = liveAnchorFu15;
       liveAnchorFu17 = new LiveAnchorFunction("LIVE_ANONYMOUS_LIVE", 55);
       LiveAnchorFunction.LIVE_ANONYMOUS_LIVE = liveAnchorFu17;
       LiveAnchorFunction liveAnchorFu58 = liveAnchorFu17;
       liveAnchorFu15 = new LiveAnchorFunction("LIVE_ANONYMOUS_LIVE_DEFAULT_SWITCH", 56);
       LiveAnchorFunction.LIVE_ANONYMOUS_LIVE_DEFAULT_SWITCH = liveAnchorFu15;
       LiveAnchorFunction liveAnchorFu59 = liveAnchorFu15;
       liveAnchorFu17 = new LiveAnchorFunction("LIVE_PLAYBACK_SWITCH", 57);
       LiveAnchorFunction.LIVE_PLAYBACK_SWITCH = liveAnchorFu17;
       LiveAnchorFunction liveAnchorFu60 = liveAnchorFu17;
       liveAnchorFu15 = new LiveAnchorFunction("LIVE_QUIT_LIVE_GUIDE", 58);
       LiveAnchorFunction.LIVE_QUIT_LIVE_GUIDE = liveAnchorFu15;
       LiveAnchorFunction liveAnchorFu61 = liveAnchorFu15;
       liveAnchorFu17 = new LiveAnchorFunction("LIVE_ANNOUNCE", 59);
       LiveAnchorFunction.LIVE_ANNOUNCE = liveAnchorFu17;
       LiveAnchorFunction liveAnchorFu62 = liveAnchorFu17;
       liveAnchorFu15 = new LiveAnchorFunction("LIVE_TOPIC", 60);
       LiveAnchorFunction.LIVE_TOPIC = liveAnchorFu15;
       LiveAnchorFunction liveAnchorFu63 = liveAnchorFu15;
       liveAnchorFu17 = new LiveAnchorFunction("LIVE_RE_PUSH", 61);
       LiveAnchorFunction.LIVE_RE_PUSH = liveAnchorFu17;
       LiveAnchorFunction liveAnchorFu64 = liveAnchorFu17;
       liveAnchorFu15 = new LiveAnchorFunction("LIVE_HIGH_LIGHT_IN_BOTTOM_BAR", 62);
       LiveAnchorFunction.LIVE_HIGH_LIGHT_IN_BOTTOM_BAR = liveAnchorFu15;
       LiveAnchorFunction liveAnchorFu65 = liveAnchorFu15;
       liveAnchorFu17 = new LiveAnchorFunction("LIVE_VIP_GRADE", 63);
       LiveAnchorFunction.LIVE_VIP_GRADE = liveAnchorFu17;
       LiveAnchorFunction liveAnchorFu66 = liveAnchorFu17;
       liveAnchorFu15 = new LiveAnchorFunction("LIVE_VIP_GRADE_WATCHING_LIST", 64);
       LiveAnchorFunction.LIVE_VIP_GRADE_WATCHING_LIST = liveAnchorFu15;
       LiveAnchorFunction liveAnchorFu67 = liveAnchorFu15;
       liveAnchorFu17 = new LiveAnchorFunction("LIVE_BLIND_DATE", 65);
       LiveAnchorFunction.LIVE_BLIND_DATE = liveAnchorFu17;
       LiveAnchorFunction[] liveAnchorFu68 = new LiveAnchorFunction[66];
       liveAnchorFu68[0] = liveAnchorFu;
       liveAnchorFu68[1] = liveAnchorFu1;
       liveAnchorFu68[2] = liveAnchorFu2;
       liveAnchorFu68[3] = liveAnchorFu3;
       liveAnchorFu68[4] = liveAnchorFu4;
       liveAnchorFu68[5] = liveAnchorFu5;
       liveAnchorFu68[6] = liveAnchorFu6;
       liveAnchorFu68[7] = liveAnchorFu7;
       liveAnchorFu68[8] = liveAnchorFu8;
       liveAnchorFu68[9] = liveAnchorFu9;
       liveAnchorFu68[10] = liveAnchorFu10;
       liveAnchorFu68[11] = liveAnchorFu11;
       liveAnchorFu68[12] = liveAnchorFu12;
       liveAnchorFu68[13] = liveAnchorFu14;
       liveAnchorFu68[14] = liveAnchorFu16;
       liveAnchorFu68[15] = liveAnchorFu18;
       liveAnchorFu68[16] = liveAnchorFu19;
       liveAnchorFu68[17] = liveAnchorFu20;
       liveAnchorFu68[18] = liveAnchorFu21;
       liveAnchorFu68[19] = liveAnchorFu22;
       liveAnchorFu68[20] = liveAnchorFu23;
       liveAnchorFu68[21] = liveAnchorFu24;
       liveAnchorFu68[22] = liveAnchorFu25;
       liveAnchorFu68[23] = liveAnchorFu26;
       liveAnchorFu68[24] = liveAnchorFu27;
       liveAnchorFu68[25] = liveAnchorFu28;
       liveAnchorFu68[26] = liveAnchorFu29;
       liveAnchorFu68[27] = liveAnchorFu30;
       liveAnchorFu68[28] = liveAnchorFu31;
       liveAnchorFu68[29] = liveAnchorFu32;
       liveAnchorFu68[30] = liveAnchorFu33;
       liveAnchorFu68[31] = liveAnchorFu34;
       liveAnchorFu68[32] = liveAnchorFu35;
       liveAnchorFu68[33] = liveAnchorFu36;
       liveAnchorFu68[34] = liveAnchorFu37;
       liveAnchorFu68[35] = liveAnchorFu38;
       liveAnchorFu68[36] = liveAnchorFu39;
       liveAnchorFu68[37] = liveAnchorFu40;
       liveAnchorFu68[38] = liveAnchorFu41;
       liveAnchorFu68[39] = liveAnchorFu42;
       liveAnchorFu68[40] = liveAnchorFu43;
       liveAnchorFu68[41] = liveAnchorFu44;
       liveAnchorFu68[42] = liveAnchorFu45;
       liveAnchorFu68[43] = liveAnchorFu46;
       liveAnchorFu68[44] = liveAnchorFu47;
       liveAnchorFu68[45] = liveAnchorFu48;
       liveAnchorFu68[46] = liveAnchorFu49;
       liveAnchorFu68[47] = liveAnchorFu50;
       liveAnchorFu68[48] = liveAnchorFu51;
       liveAnchorFu68[49] = liveAnchorFu52;
       liveAnchorFu68[50] = liveAnchorFu53;
       liveAnchorFu68[51] = liveAnchorFu54;
       liveAnchorFu68[52] = liveAnchorFu55;
       liveAnchorFu68[53] = liveAnchorFu56;
       liveAnchorFu68[54] = liveAnchorFu57;
       liveAnchorFu68[55] = liveAnchorFu58;
       liveAnchorFu68[56] = liveAnchorFu59;
       liveAnchorFu68[57] = liveAnchorFu60;
       liveAnchorFu68[58] = liveAnchorFu61;
       liveAnchorFu68[59] = liveAnchorFu62;
       liveAnchorFu68[60] = liveAnchorFu63;
       liveAnchorFu68[61] = liveAnchorFu64;
       liveAnchorFu68[62] = liveAnchorFu65;
       liveAnchorFu68[63] = liveAnchorFu66;
       liveAnchorFu68[64] = liveAnchorFu67;
       liveAnchorFu68[65] = liveAnchorFu17;
       LiveAnchorFunction.$VALUES = liveAnchorFu68;
    }
    public void LiveAnchorFunction(String p0,int p1){
       super(p0, p1);
    }
    public static LiveAnchorFunction valueOf(String p0){
       Object obj = PatchProxy.applyOneRefs(p0, null, LiveAnchorFunction.class, "2");
       if (obj != PatchProxyResult.class) {
          return obj;
       }
       return Enum.valueOf(LiveAnchorFunction.class, p0);
    }
    public static LiveAnchorFunction[] values(){
       Object obj = PatchProxy.apply(null, null, LiveAnchorFunction.class, "1");
       if (obj != PatchProxyResult.class) {
          return obj;
       }
       return LiveAnchorFunction.$VALUES.clone();
    }
}
