package com.kwai.player.debuginfo.model.AppLiveQosDebugInfo;
import java.lang.Object;
import android.os.Bundle;
import java.lang.Class;
import java.lang.String;
import com.kwai.robust.PatchProxy;
import com.kwai.robust.PatchProxyResult;

public class AppLiveQosDebugInfo	// class@0012e3
{
    public String aencInit;
    public int audioBufferByteLength;
    public int audioBufferTimeLength;
    public String audioDecoder;
    public int audioDelay;
    public long audioTotalDataSize;
    public int blockCnt;
    public long blockDuration;
    public String comment;
    public long firstFrameReceived;
    public long firstScreenTimeCodecOpen;
    public long firstScreenTimeDecode;
    public long firstScreenTimeDnsAnalyze;
    public int firstScreenTimeDroppedDuration;
    public long firstScreenTimeHttpConnect;
    public long firstScreenTimeInputOpen;
    public long firstScreenTimePktReceive;
    public long firstScreenTimePreDecode;
    public long firstScreenTimeRender;
    public long firstScreenTimeStreamFind;
    public long firstScreenTimeTotal;
    public long firstScreenTimeWaitForPlay;
    public String host;
    public String hostInfo;
    public boolean isLiveManifest;
    public int kflvBandwidthCurrent;
    public int kflvBandwidthFragment;
    public int kflvCurrentBufferMs;
    public int kflvEstimateBufferMs;
    public int kflvPlayingBitrate;
    public int kflvPredictedBufferMs;
    public int kflvSpeedupThresholdMs;
    public int sourceDeviceType;
    public long totalDataSize;
    public int totalDroppedDuration;
    public String vencDynamic;
    public String vencInit;
    public int videoBufferByteLength;
    public int videoBufferTimeLength;
    public float videoDecodeFramesPerSecond;
    public String videoDecoder;
    public int videoDelayAftDec;
    public int videoDelayBefDec;
    public int videoDelayRecv;
    public int videoDelayRender;
    public float videoDisplayFramesPerSecond;
    public float videoReadFramesPerSecond;
    public long videoTotalDataSize;
    public static final String LiveQosDebugInfo_aencInit = "aencInit";
    public static final String LiveQosDebugInfo_audioBufferByteLength = "audioBufferByteLength";
    public static final String LiveQosDebugInfo_audioBufferTimeLength = "audioBufferTimeLength";
    public static final String LiveQosDebugInfo_audioDecoder = "audioDecoder";
    public static final String LiveQosDebugInfo_audioDelay = "audioDelay";
    public static final String LiveQosDebugInfo_audioTotalDataSize = "audioTotalDataSize";
    public static final String LiveQosDebugInfo_blockCnt = "blockCnt";
    public static final String LiveQosDebugInfo_blockDuration = "blockDuration";
    public static final String LiveQosDebugInfo_comment = "comment";
    public static final String LiveQosDebugInfo_droppedDurationBefFirstScreen = "droppedDurationBefFirstScreen";
    public static final String LiveQosDebugInfo_droppedDurationTotal = "droppedDurationTotal";
    public static final String LiveQosDebugInfo_firstFrameReceived = "firstFrameReceived";
    public static final String LiveQosDebugInfo_firstScreenTimeCodecOpen = "firstScreenTimeCodecOpen";
    public static final String LiveQosDebugInfo_firstScreenTimeDecode = "firstScreenTimeDecode";
    public static final String LiveQosDebugInfo_firstScreenTimeDnsAnalyze = "firstScreenTimeDnsAnalyze";
    public static final String LiveQosDebugInfo_firstScreenTimeHttpConnect = "firstScreenTimeHttpConnect";
    public static final String LiveQosDebugInfo_firstScreenTimeInputOpen = "firstScreenTimeInputOpen";
    public static final String LiveQosDebugInfo_firstScreenTimePktReceive = "firstScreenTimePktReceive";
    public static final String LiveQosDebugInfo_firstScreenTimePreDecode = "firstScreenTimePreDecode";
    public static final String LiveQosDebugInfo_firstScreenTimeRender = "firstScreenTimeRender";
    public static final String LiveQosDebugInfo_firstScreenTimeStreamFind = "firstScreenTimeStreamFind";
    public static final String LiveQosDebugInfo_firstScreenTimeTotal = "firstScreenTimeTotal";
    public static final String LiveQosDebugInfo_firstScreenTimeWaitForPlay = "firstScreenTimeWaitForPlay";
    public static final String LiveQosDebugInfo_host = "host";
    public static final String LiveQosDebugInfo_hostInfo = "hostInfo";
    public static final String LiveQosDebugInfo_isLiveManifest = "isLiveManifest";
    public static final String LiveQosDebugInfo_kflvBandwidthCurrent = "kflvBandwidthCurrent";
    public static final String LiveQosDebugInfo_kflvBandwidthFragment = "kflvBandwidthFragment";
    public static final String LiveQosDebugInfo_kflvCurrentBufferMs = "kflvCurrentBufferMs";
    public static final String LiveQosDebugInfo_kflvEstimateBufferMs = "kflvEstimateBufferMs";
    public static final String LiveQosDebugInfo_kflvPlayingBitrate = "kflvPlayingBitrate";
    public static final String LiveQosDebugInfo_kflvPredictedBufferMs = "kflvPredictedBufferMs";
    public static final String LiveQosDebugInfo_kflvSpeedupThresholdMs = "kflvSpeedupThresholdMs";
    public static final String LiveQosDebugInfo_sourceDeviceType = "sourceDeviceType";
    public static final String LiveQosDebugInfo_totalDataSize = "totalDataSize";
    public static final String LiveQosDebugInfo_vencDynamic = "vencDynamic";
    public static final String LiveQosDebugInfo_vencInit = "vencInit";
    public static final String LiveQosDebugInfo_videoBufferByteLength = "videoBufferByteLength";
    public static final String LiveQosDebugInfo_videoBufferTimeLength = "videoBufferTimeLength";
    public static final String LiveQosDebugInfo_videoDecodeFramesPerSecond = "videoDecodeFramesPerSecond";
    public static final String LiveQosDebugInfo_videoDecoder = "videoDecoder";
    public static final String LiveQosDebugInfo_videoDelayAftDec = "videoDelayAftDec";
    public static final String LiveQosDebugInfo_videoDelayBefDec = "videoDelayBefDec";
    public static final String LiveQosDebugInfo_videoDelayRecv = "videoDelayRecv";
    public static final String LiveQosDebugInfo_videoDelayRender = "videoDelayRender";
    public static final String LiveQosDebugInfo_videoDisplayFramesPerSecond = "videoDisplayFramesPerSecond";
    public static final String LiveQosDebugInfo_videoReadFramesPerSecond = "videoReadFramesPerSecond";
    public static final String LiveQosDebugInfo_videoTotalDataSize = "videoTotalDataSize";

    public void AppLiveQosDebugInfo(){
       super();
    }
    public static AppLiveQosDebugInfo from(Bundle p0){
       Object obj = null;
       AppLiveQosDebugInfo obj1 = PatchProxy.applyOneRefs(p0, obj, AppLiveQosDebugInfo.class, "1");
       if (obj1 != PatchProxyResult.class) {
          return obj1;
       }
       if (p0 == null) {
          return obj;
       }
       obj1 = new AppLiveQosDebugInfo();
       obj1.comment = p0.getString("comment", "");
       obj1.videoDecoder = p0.getString("videoDecoder", "");
       obj1.audioDecoder = p0.getString("audioDecoder", "");
       obj1.vencDynamic = p0.getString("vencDynamic", "");
       obj1.hostInfo = p0.getString("hostInfo", "");
       obj1.host = p0.getString("host", "");
       obj1.vencInit = p0.getString("vencInit", "");
       obj1.aencInit = p0.getString("aencInit", "");
       obj1.audioBufferTimeLength = p0.getInt("audioBufferTimeLength", 0);
       obj1.videoBufferTimeLength = p0.getInt("videoBufferTimeLength", 0);
       obj1.audioDelay = p0.getInt("audioDelay", 0);
       obj1.videoDelayRecv = p0.getInt("videoDelayRecv", 0);
       obj1.videoDelayBefDec = p0.getInt("videoDelayBefDec", 0);
       obj1.videoDelayAftDec = p0.getInt("videoDelayAftDec", 0);
       obj1.videoDelayRender = p0.getInt("videoDelayRender", 0);
       obj1.firstScreenTimeDroppedDuration = p0.getInt("droppedDurationBefFirstScreen", 0);
       obj1.totalDroppedDuration = p0.getInt("droppedDurationTotal", 0);
       obj1.audioBufferByteLength = p0.getInt("audioBufferByteLength", 0);
       obj1.videoBufferByteLength = p0.getInt("videoBufferByteLength", 0);
       long l = 0;
       obj1.audioTotalDataSize = p0.getLong("audioTotalDataSize", l);
       obj1.videoTotalDataSize = p0.getLong("videoTotalDataSize", l);
       obj1.totalDataSize = p0.getLong("totalDataSize", l);
       boolean b = true;
       if (p0.getInt("isLiveManifest", 0) != b) {
          b = false;
       }
       obj1.isLiveManifest = b;
       obj1.kflvPlayingBitrate = p0.getInt("kflvPlayingBitrate", 0);
       obj1.kflvBandwidthCurrent = p0.getInt("kflvBandwidthCurrent", 0);
       obj1.kflvBandwidthFragment = p0.getInt("kflvBandwidthFragment", 0);
       obj1.kflvCurrentBufferMs = p0.getInt("kflvCurrentBufferMs", 0);
       obj1.kflvEstimateBufferMs = p0.getInt("kflvEstimateBufferMs", 0);
       obj1.kflvPredictedBufferMs = p0.getInt("kflvPredictedBufferMs", 0);
       obj1.kflvSpeedupThresholdMs = p0.getInt("kflvSpeedupThresholdMs", 0);
       obj1.firstScreenTimeDnsAnalyze = p0.getLong("firstScreenTimeDnsAnalyze", l);
       obj1.firstScreenTimeHttpConnect = p0.getLong("firstScreenTimeHttpConnect", l);
       obj1.firstScreenTimePktReceive = p0.getLong("firstScreenTimePktReceive", l);
       obj1.firstScreenTimeTotal = p0.getLong("firstScreenTimeTotal", l);
       obj1.firstScreenTimeWaitForPlay = p0.getLong("firstScreenTimeWaitForPlay", l);
       obj1.firstScreenTimeInputOpen = p0.getLong("firstScreenTimeInputOpen", l);
       obj1.firstScreenTimeStreamFind = p0.getLong("firstScreenTimeStreamFind", l);
       obj1.firstScreenTimeCodecOpen = p0.getLong("firstScreenTimeCodecOpen", l);
       obj1.firstScreenTimePreDecode = p0.getLong("firstScreenTimePreDecode", l);
       obj1.firstScreenTimeDecode = p0.getLong("firstScreenTimeDecode", l);
       obj1.firstScreenTimeRender = p0.getLong("firstScreenTimeRender", l);
       obj1.firstFrameReceived = p0.getLong("firstFrameReceived", l);
       obj1.blockCnt = p0.getInt("blockCnt", 0);
       obj1.blockDuration = p0.getLong("blockDuration", l);
       obj1.videoReadFramesPerSecond = p0.getFloat("videoReadFramesPerSecond", 0);
       obj1.videoDecodeFramesPerSecond = p0.getFloat("videoDecodeFramesPerSecond", 0);
       obj1.videoDisplayFramesPerSecond = p0.getFloat("videoDisplayFramesPerSecond", 0);
       obj1.sourceDeviceType = p0.getInt("sourceDeviceType", 0);
       return obj1;
    }
}
