package lqd.i;
import java.lang.Iterable;
import java.lang.Throwable;
import yqd.f;
import java.lang.String;
import io.netty.channel.g;
import lqd.f;
import io.netty.channel.r;
import io.netty.channel.e;
import java.net.SocketAddress;
import java.lang.Object;
import java.util.Map;
import lqd.e;
import java.lang.Class;
import java.util.List;
import io.netty.channel.d;

public interface abstract i implements Iterable	// class@001c9d
{

    i A(Throwable p0);
    i A0(f p0,String p1,String p2,g p3);
    i C();
    i C2(f p0,String p1,g p2);
    i D1(f p0,String p1,String p2,g p3);
    i G0(g[] p0);
    e I(r p0);
    i I2(f p0,String p1,String p2,g p3);
    e K(SocketAddress p0,r p1);
    e L(Object p0,r p1);
    e M(r p0);
    i M1(f p0,String p1,g p2);
    i N1(f p0,g[] p1);
    Map N3();
    e O(SocketAddress p0,SocketAddress p1,r p2);
    i O0(f p0,String p1,g p2);
    e P();
    e Q(Object p0);
    e R(Object p0);
    i R1(g[] p0);
    e S(r p0);
    e T(Object p0,r p1);
    i T2(g p0);
    e U(SocketAddress p0,SocketAddress p1);
    e V(SocketAddress p0,r p1);
    e Y(SocketAddress p0);
    i Y2(f p0,String p1,String p2,g p3);
    e Z0();
    e Z2(g p0);
    g a(Class p0);
    e a4(String p0);
    e b0(SocketAddress p0);
    i b1(String p0,String p1,g p2);
    e close();
    e disconnect();
    i e1(String p0,String p1,g p2);
    i f0();
    i f3(String p0,g p1);
    g first();
    i flush();
    g get(String p0);
    i h0(Object p0);
    i i2(g p0,String p1,g p2);
    e i3();
    i i4(f p0,g[] p1);
    i j0();
    i j1(String p0,g p1);
    i k0();
    e k1(Class p0);
    i l0();
    g last();
    g n0(Class p0);
    List names();
    d o();
    i p2(f p0,g[] p1);
    i read();
    g remove(String p0);
    g removeFirst();
    g removeLast();
    i s3(f p0,String p1,g p2);
    i x();
    g x0(Class p0,String p1,g p2);
    i y(Object p0);
    g y0(String p0,String p1,g p2);
    i z2(f p0,g[] p1);
}
