package com.kuaishou.live.core.show.redpacket.LiveRedPacketResourcePathConstant;
import l12.d;
import java.lang.Enum;
import java.lang.String;
import java.lang.Object;
import java.lang.Class;
import com.kwai.robust.PatchProxy;
import com.kwai.robust.PatchProxyResult;

public final class LiveRedPacketResourcePathConstant extends Enum implements d	// class@000e4e
{
    public final String resourceName;
    public final String resourcePath;
    public static final LiveRedPacketResourcePathConstant[] $VALUES;
    public static final LiveRedPacketResourcePathConstant LITE_RED_PACKET_WIDGET_COVER;
    public static final LiveRedPacketResourcePathConstant LIVE_ACTIVITY_RED_PACKET_DISABLE_SNATCH_ICON;
    public static final LiveRedPacketResourcePathConstant LIVE_ACTIVITY_RED_PACKET_OPENED_ACTION_BUTTON;
    public static final LiveRedPacketResourcePathConstant LIVE_ACTIVITY_RED_PACKET_PRAPARE_FOLLOW_BUTTON;
    public static final LiveRedPacketResourcePathConstant LIVE_ACTIVITY_RED_PACKET_PREPARE_BOTTOM_BACKGROUND;
    public static final LiveRedPacketResourcePathConstant LIVE_ACTIVITY_RED_PACKET_PREPARE_FOLLOWED_BUTTON;
    public static final LiveRedPacketResourcePathConstant LIVE_ACTIVITY_RED_PACKET_PREPARE_TIP_BUTTON;
    public static final LiveRedPacketResourcePathConstant LIVE_ACTIVITY_RED_PACKET_PREPARE_TOP_BACKGROUND;
    public static final LiveRedPacketResourcePathConstant LIVE_ACTIVITY_RED_PACKET_SNATCH_ICON;
    public static final LiveRedPacketResourcePathConstant LIVE_CONDITION_RED_PACKET_CURRENT_INFO_INVITE_USER;
    public static final LiveRedPacketResourcePathConstant LIVE_CONDITION_RED_PACKET_CURRENT_INFO_NETWORK_ERROR;
    public static final LiveRedPacketResourcePathConstant LIVE_CONDITION_RED_PACKET_CURRENT_INFO_TIP_ICON_LARGE;
    public static final LiveRedPacketResourcePathConstant LIVE_CONDITION_RED_PACKET_OLD_PENDANT_FANS_GROUP_ICON;
    public static final LiveRedPacketResourcePathConstant LIVE_CONDITION_RED_PACKET_OLD_PENDANT_GIFT_ICON;
    public static final LiveRedPacketResourcePathConstant LIVE_CONDITION_RED_PACKET_OLD_PENDANT_SHARE_ICON;
    public static final LiveRedPacketResourcePathConstant LIVE_CONDITION_RED_PACKET_PANEL_RESULT_SEND_TO_ANCHOR_BUTTON_BACKGROUND;
    public static final LiveRedPacketResourcePathConstant LIVE_CONDITION_RED_PACKET_RESULT_NETWORK_ERROR;
    public static final LiveRedPacketResourcePathConstant LIVE_FELLOW_REDPACK_DOUBLE_REDPACK_ICON;
    public static final LiveRedPacketResourcePathConstant LIVE_FELLOW_REDPACK_KCOIN_ICON;
    public static final LiveRedPacketResourcePathConstant LIVE_FELLOW_RED_PACK_INTELLIGENT_DELIVERY_APPEND_BUTTON;
    public static final LiveRedPacketResourcePathConstant LIVE_FELLOW_RED_PACK_INTELLIGENT_DELIVERY_BACKGROUND;
    public static final LiveRedPacketResourcePathConstant LIVE_FELLOW_RED_PACK_INTELLIGENT_DELIVERY_SEND_BUTTON;
    public static final LiveRedPacketResourcePathConstant LIVE_IC_ARROW_RED_PACK_CLOSE;
    public static final LiveRedPacketResourcePathConstant LIVE_MOREFUNCTIONS_REDENVELOPES_ENTRANCE;
    public static final LiveRedPacketResourcePathConstant LIVE_NORMAL_RED_PACKET_ITEM_DECORATE;
    public static final LiveRedPacketResourcePathConstant LIVE_RED_PACKET_BACKGROUND;
    public static final LiveRedPacketResourcePathConstant LIVE_RED_PACKET_BOTTOM_COVER;
    public static final LiveRedPacketResourcePathConstant LIVE_RED_PACKET_CONDITON_PREPARE_NO_NET;
    public static final LiveRedPacketResourcePathConstant LIVE_RED_PACKET_CONDITON_RESULT_NO_NET;
    public static final LiveRedPacketResourcePathConstant LIVE_RED_PACKET_CONTAINER_TIPS_LEFT;
    public static final LiveRedPacketResourcePathConstant LIVE_RED_PACKET_COVER_OPEN;
    public static final LiveRedPacketResourcePathConstant LIVE_RED_PACKET_INNER_PAGE_BACKGROUND;
    public static final LiveRedPacketResourcePathConstant LIVE_RED_PACKET_NO_ONES_WIN_EMPTY_COVER;
    public static final LiveRedPacketResourcePathConstant LIVE_RED_PACKET_POPUP_BTN_COIN_LIGHT;
    public static final LiveRedPacketResourcePathConstant LIVE_RED_PACKET_POP_BOTTOM_COVER;
    public static final LiveRedPacketResourcePathConstant LIVE_RED_PACKET_POP_TOP_COVER;
    public static final LiveRedPacketResourcePathConstant LIVE_RED_PACKET_SCROLL_AND_RESULT_DIALOG_COVER;
    public static final LiveRedPacketResourcePathConstant LIVE_RED_PACKET_SCROLL_AND_RESULT_DIALOG_FOREGROUND_COVER;
    public static final LiveRedPacketResourcePathConstant LIVE_RED_PACKET_SNATCH_ANIMATION;
    public static final LiveRedPacketResourcePathConstant LIVE_RED_PACKET_TOP_COVER;
    public static final LiveRedPacketResourcePathConstant LIVE_RED_PACKET_WHITE_SPECTRUM;
    public static final LiveRedPacketResourcePathConstant LIVE_RED_PACK_RECOMMEND_LEFT_TOP_ICON;
    public static final LiveRedPacketResourcePathConstant LIVE_RED_PACK_SNATCH_ICON;
    public static final LiveRedPacketResourcePathConstant LIVE_RED_PACK_STAR;

    static {
       LiveRedPacketResourcePathConstant[] liveRedPacke = new LiveRedPacketResourcePathConstant[44];
       LiveRedPacketResourcePathConstant liveRedPacke1 = new LiveRedPacketResourcePathConstant("LIVE_RED_PACKET_CONTAINER_TIPS_LEFT", 0, "LIVE_RED_PACKET_CONTAINER_TIPS_LEFT", "udata/pkg/kwai-client-image/live_revenue_redpack/live_redpacks_scrolltip_arrow_left.json");
       LiveRedPacketResourcePathConstant.LIVE_RED_PACKET_CONTAINER_TIPS_LEFT = liveRedPacke1;
       liveRedPacke[0] = liveRedPacke1;
       liveRedPacke1 = new LiveRedPacketResourcePathConstant("LIVE_RED_PACKET_WHITE_SPECTRUM", 1, "LIVE_RED_PACKET_WHITE_SPECTRUM", "udata/pkg/kwai-client-image/live_revenue_redpack/live_fellow_red_pack_living_sign.json");
       LiveRedPacketResourcePathConstant.LIVE_RED_PACKET_WHITE_SPECTRUM = liveRedPacke1;
       liveRedPacke[1] = liveRedPacke1;
       liveRedPacke1 = new LiveRedPacketResourcePathConstant("LIVE_RED_PACK_STAR", 2, "LIVE_RED_PACK_STAR", "udata/pkg/kwai-client-image/live_revenue_redpack/live_red_pack_star.json");
       LiveRedPacketResourcePathConstant.LIVE_RED_PACK_STAR = liveRedPacke1;
       liveRedPacke[2] = liveRedPacke1;
       liveRedPacke1 = new LiveRedPacketResourcePathConstant("LIVE_ACTIVITY_RED_PACKET_SNATCH_ICON", 3, "LIVE_ACTIVITY_RED_PACKET_SNATCH_ICON", "udata/pkg/kwai-client-image/live_revenue_redpack/live_activity_red_packet_snatch_icon.webp");
       LiveRedPacketResourcePathConstant.LIVE_ACTIVITY_RED_PACKET_SNATCH_ICON = liveRedPacke1;
       liveRedPacke[3] = liveRedPacke1;
       liveRedPacke1 = new LiveRedPacketResourcePathConstant("LIVE_ACTIVITY_RED_PACKET_DISABLE_SNATCH_ICON", 4, "LIVE_ACTIVITY_RED_PACKET_DISABLE_SNATCH_ICON", "udata/pkg/kwai-client-image/live_revenue_redpack/live_activity_red_packet_disable_snatch_icon.webp");
       LiveRedPacketResourcePathConstant.LIVE_ACTIVITY_RED_PACKET_DISABLE_SNATCH_ICON = liveRedPacke1;
       liveRedPacke[4] = liveRedPacke1;
       liveRedPacke1 = new LiveRedPacketResourcePathConstant("LIVE_RED_PACK_SNATCH_ICON", 5, "LIVE_RED_PACK_SNATCH_ICON", "udata/pkg/kwai-client-image/live_revenue_redpack/live_red_pack_open_icon.png");
       LiveRedPacketResourcePathConstant.LIVE_RED_PACK_SNATCH_ICON = liveRedPacke1;
       liveRedPacke[5] = liveRedPacke1;
       liveRedPacke1 = new LiveRedPacketResourcePathConstant("LIVE_RED_PACKET_SNATCH_ANIMATION", 6, "LIVE_RED_PACKET_SNATCH_ANIMATION", "udata/pkg/kwai-client-image/live_revenue_redpack/live_red_pack_open_animation.webp");
       LiveRedPacketResourcePathConstant.LIVE_RED_PACKET_SNATCH_ANIMATION = liveRedPacke1;
       liveRedPacke[6] = liveRedPacke1;
       liveRedPacke1 = new LiveRedPacketResourcePathConstant("LITE_RED_PACKET_WIDGET_COVER", 7, "LITE_RED_PACKET_WIDGET_COVER", "udata/pkg/kwai-client-image/live_revenue_redpack/live_red_pack_widget_cover.png");
       LiveRedPacketResourcePathConstant.LITE_RED_PACKET_WIDGET_COVER = liveRedPacke1;
       liveRedPacke[7] = liveRedPacke1;
       liveRedPacke1 = new LiveRedPacketResourcePathConstant("LIVE_ACTIVITY_RED_PACKET_PREPARE_TIP_BUTTON", 8, "LIVE_ACTIVITY_RED_PACKET_PREPARE_TIP_BUTTON", "udata/pkg/kwai-client-image/live_revenue_redpack/live_activity_red_packet_prepare_tip_button.webp");
       LiveRedPacketResourcePathConstant.LIVE_ACTIVITY_RED_PACKET_PREPARE_TIP_BUTTON = liveRedPacke1;
       liveRedPacke[8] = liveRedPacke1;
       liveRedPacke1 = new LiveRedPacketResourcePathConstant("LIVE_FELLOW_RED_PACK_INTELLIGENT_DELIVERY_SEND_BUTTON", 9, "LIVE_FELLOW_RED_PACK_INTELLIGENT_DELIVERY_SEND_BUTTON", "udata/pkg/kwai-client-image/live_revenue_redpack/live_fellow_red_pack_intelligent_delivery_send_button.webp");
       LiveRedPacketResourcePathConstant.LIVE_FELLOW_RED_PACK_INTELLIGENT_DELIVERY_SEND_BUTTON = liveRedPacke1;
       liveRedPacke[9] = liveRedPacke1;
       liveRedPacke1 = new LiveRedPacketResourcePathConstant("LIVE_FELLOW_RED_PACK_INTELLIGENT_DELIVERY_APPEND_BUTTON", 10, "LIVE_FELLOW_RED_PACK_INTELLIGENT_DELIVERY_APPEND_BUTTON", "udata/pkg/kwai-client-image/live_revenue_redpack/live_fellow_red_pack_intelligent_delivery_append_button.webp");
       LiveRedPacketResourcePathConstant.LIVE_FELLOW_RED_PACK_INTELLIGENT_DELIVERY_APPEND_BUTTON = liveRedPacke1;
       liveRedPacke[10] = liveRedPacke1;
       liveRedPacke1 = new LiveRedPacketResourcePathConstant("LIVE_RED_PACKET_BOTTOM_COVER", 11, "LIVE_RED_PACKET_BOTTOM_COVER", "udata/pkg/kwai-client-image/live_revenue_redpack/live_red_packet_bottom_cover.webp");
       LiveRedPacketResourcePathConstant.LIVE_RED_PACKET_BOTTOM_COVER = liveRedPacke1;
       liveRedPacke[11] = liveRedPacke1;
       liveRedPacke1 = new LiveRedPacketResourcePathConstant("LIVE_RED_PACKET_TOP_COVER", 12, "LIVE_RED_PACKET_TOP_COVER", "udata/pkg/kwai-client-image/live_revenue_redpack/live_red_packet_top_cover.webp");
       LiveRedPacketResourcePathConstant.LIVE_RED_PACKET_TOP_COVER = liveRedPacke1;
       liveRedPacke[12] = liveRedPacke1;
       liveRedPacke1 = new LiveRedPacketResourcePathConstant("LIVE_RED_PACKET_BACKGROUND", 13, "  LIVE_RED_PACKET_BACKGROUND", "udata/pkg/kwai-client-image/live_revenue_redpack/live_red_packet_background.webp");
       LiveRedPacketResourcePathConstant.LIVE_RED_PACKET_BACKGROUND = liveRedPacke1;
       liveRedPacke[13] = liveRedPacke1;
       liveRedPacke1 = new LiveRedPacketResourcePathConstant("LIVE_MOREFUNCTIONS_REDENVELOPES_ENTRANCE", 14, "LIVE_MOREFUNCTIONS_REDENVELOPES_ENTRANCE", "udata/pkg/kwai-client-image/live_revenue_redpack/live_morefunctions_redenvelopes_entrance.png");
       LiveRedPacketResourcePathConstant.LIVE_MOREFUNCTIONS_REDENVELOPES_ENTRANCE = liveRedPacke1;
       liveRedPacke[14] = liveRedPacke1;
       liveRedPacke1 = new LiveRedPacketResourcePathConstant("LIVE_CONDITION_RED_PACKET_PANEL_RESULT_SEND_TO_ANCHOR_BUTTON_BACKGROUND", 15, "LIVE_CONDITION_RED_PACKET_PANEL_RESULT_SEND_TO_ANCHOR_BUTTON_BACKGROUND", "udata/pkg/kwai-client-image/live_revenue_redpack/live_condition_red_packet_panel_result_send_to_anchor_button_background.webp");
       LiveRedPacketResourcePathConstant.LIVE_CONDITION_RED_PACKET_PANEL_RESULT_SEND_TO_ANCHOR_BUTTON_BACKGROUND = liveRedPacke1;
       liveRedPacke[15] = liveRedPacke1;
       liveRedPacke1 = new LiveRedPacketResourcePathConstant("LIVE_CONDITION_RED_PACKET_RESULT_NETWORK_ERROR", 16, "LIVE_CONDITION_RED_PACKET_RESULT_NETWORK_ERROR", "udata/pkg/kwai-client-image/live_revenue_redpack/live_condition_red_pack_no_net_yellow.png");
       LiveRedPacketResourcePathConstant.LIVE_CONDITION_RED_PACKET_RESULT_NETWORK_ERROR = liveRedPacke1;
       liveRedPacke[16] = liveRedPacke1;
       liveRedPacke1 = new LiveRedPacketResourcePathConstant("LIVE_CONDITION_RED_PACKET_CURRENT_INFO_NETWORK_ERROR", 17, "LIVE_CONDITION_RED_PACKET_CURRENT_INFO_NETWORK_ERROR", "udata/pkg/kwai-client-image/live_revenue_redpack/live_condition_red_pack_no_net_white.png");
       LiveRedPacketResourcePathConstant.LIVE_CONDITION_RED_PACKET_CURRENT_INFO_NETWORK_ERROR = liveRedPacke1;
       liveRedPacke[17] = liveRedPacke1;
       liveRedPacke1 = new LiveRedPacketResourcePathConstant("LIVE_NORMAL_RED_PACKET_ITEM_DECORATE", 18, "LIVE_NORMAL_RED_PACKET_ITEM_DECORATE", "udata/pkg/kwai-client-image/live_revenue_redpack/live_red_pack_grade_icon.png");
       LiveRedPacketResourcePathConstant.LIVE_NORMAL_RED_PACKET_ITEM_DECORATE = liveRedPacke1;
       liveRedPacke[18] = liveRedPacke1;
       liveRedPacke1 = new LiveRedPacketResourcePathConstant("LIVE_RED_PACKET_COVER_OPEN", 19, "LIVE_RED_PACKET_COVER_OPEN", "udata/pkg/kwai-client-image/live_revenue_redpack/live_red_packet_cover_open.webp");
       LiveRedPacketResourcePathConstant.LIVE_RED_PACKET_COVER_OPEN = liveRedPacke1;
       liveRedPacke[19] = liveRedPacke1;
       liveRedPacke1 = new LiveRedPacketResourcePathConstant("LIVE_CONDITION_RED_PACKET_CURRENT_INFO_TIP_ICON_LARGE", 20, "LIVE_CONDITION_RED_PACKET_CURRENT_INFO_TIP_ICON_LARGE", "udata/pkg/kwai-client-image/live_revenue_redpack/live_condition_red_pack_gold_center_audience.png");
       LiveRedPacketResourcePathConstant.LIVE_CONDITION_RED_PACKET_CURRENT_INFO_TIP_ICON_LARGE = liveRedPacke1;
       liveRedPacke[20] = liveRedPacke1;
       liveRedPacke1 = new LiveRedPacketResourcePathConstant("LIVE_ACTIVITY_RED_PACKET_PRAPARE_FOLLOW_BUTTON", 21, "LIVE_ACTIVITY_RED_PACKET_PRAPARE_FOLLOW_BUTTON", "udata/pkg/kwai-client-image/live_revenue_redpack/live_activity_red_packet_prapare_follow_button.webp");
       LiveRedPacketResourcePathConstant.LIVE_ACTIVITY_RED_PACKET_PRAPARE_FOLLOW_BUTTON = liveRedPacke1;
       liveRedPacke[21] = liveRedPacke1;
       liveRedPacke1 = new LiveRedPacketResourcePathConstant("LIVE_FELLOW_REDPACK_KCOIN_ICON", 22, "LIVE_FELLOW_REDPACK_KCOIN_ICON", "udata/pkg/kwai-client-image/live_revenue_redpack/loadimage.png");
       LiveRedPacketResourcePathConstant.LIVE_FELLOW_REDPACK_KCOIN_ICON = liveRedPacke1;
       liveRedPacke[22] = liveRedPacke1;
       liveRedPacke1 = new LiveRedPacketResourcePathConstant("LIVE_CONDITION_RED_PACKET_CURRENT_INFO_INVITE_USER", 23, "LIVE_CONDITION_RED_PACKET_CURRENT_INFO_INVITE_USER", "udata/pkg/kwai-client-image/live_revenue_redpack/live_condition_red_packet_current_info_invite_user.webp\n");
       LiveRedPacketResourcePathConstant.LIVE_CONDITION_RED_PACKET_CURRENT_INFO_INVITE_USER = liveRedPacke1;
       liveRedPacke[23] = liveRedPacke1;
       liveRedPacke1 = new LiveRedPacketResourcePathConstant("LIVE_ACTIVITY_RED_PACKET_PREPARE_TOP_BACKGROUND", 24, "LIVE_ACTIVITY_RED_PACKET_PREPARE_TOP_BACKGROUND", "udata/pkg/kwai-client-image/live_revenue_redpack/live_activity_red_packet_prepare_top_background.webp");
       LiveRedPacketResourcePathConstant.LIVE_ACTIVITY_RED_PACKET_PREPARE_TOP_BACKGROUND = liveRedPacke1;
       liveRedPacke[24] = liveRedPacke1;
       liveRedPacke1 = new LiveRedPacketResourcePathConstant("LIVE_ACTIVITY_RED_PACKET_PREPARE_BOTTOM_BACKGROUND", 25, "LIVE_ACTIVITY_RED_PACKET_PREPARE_BOTTOM_BACKGROUND", "udata/pkg/kwai-client-image/live_revenue_redpack/live_activity_red_packet_prepare_bottom_background.webp");
       LiveRedPacketResourcePathConstant.LIVE_ACTIVITY_RED_PACKET_PREPARE_BOTTOM_BACKGROUND = liveRedPacke1;
       liveRedPacke[25] = liveRedPacke1;
       liveRedPacke1 = new LiveRedPacketResourcePathConstant("LIVE_FELLOW_REDPACK_DOUBLE_REDPACK_ICON", 26, "LIVE_FELLOW_REDPACK_DOUBLE_REDPACK_ICON", "udata/pkg/kwai-client-image/live_revenue_redpack/live_fellow_redpack_double_redpack_icon.webp");
       LiveRedPacketResourcePathConstant.LIVE_FELLOW_REDPACK_DOUBLE_REDPACK_ICON = liveRedPacke1;
       liveRedPacke[26] = liveRedPacke1;
       liveRedPacke1 = new LiveRedPacketResourcePathConstant("LIVE_RED_PACKET_INNER_PAGE_BACKGROUND", 27, "LIVE_RED_PACKET_INNER_PAGE_BACKGROUND", "udata/pkg/kwai-client-image/live_revenue_redpack/live_red_packet_inner_page_background.webp");
       LiveRedPacketResourcePathConstant.LIVE_RED_PACKET_INNER_PAGE_BACKGROUND = liveRedPacke1;
       liveRedPacke[27] = liveRedPacke1;
       liveRedPacke1 = new LiveRedPacketResourcePathConstant("LIVE_CONDITION_RED_PACKET_OLD_PENDANT_FANS_GROUP_ICON", 28, "LIVE_CONDITION_RED_PACKET_OLD_PENDANT_FANS_GROUP_ICON", "udata/pkg/kwai-client-image/live_revenue_redpack/live_condition_red_packet_old_pendant_fans_group_icon.webp");
       LiveRedPacketResourcePathConstant.LIVE_CONDITION_RED_PACKET_OLD_PENDANT_FANS_GROUP_ICON = liveRedPacke1;
       liveRedPacke[28] = liveRedPacke1;
       liveRedPacke1 = new LiveRedPacketResourcePathConstant("LIVE_CONDITION_RED_PACKET_OLD_PENDANT_GIFT_ICON", 29, "LIVE_CONDITION_RED_PACKET_OLD_PENDANT_GIFT_ICON", "udata/pkg/kwai-client-image/live_revenue_redpack/live_condition_red_packet_old_pendant_gift_icon.webp");
       LiveRedPacketResourcePathConstant.LIVE_CONDITION_RED_PACKET_OLD_PENDANT_GIFT_ICON = liveRedPacke1;
       liveRedPacke[29] = liveRedPacke1;
       liveRedPacke1 = new LiveRedPacketResourcePathConstant("LIVE_CONDITION_RED_PACKET_OLD_PENDANT_SHARE_ICON", 30, "LIVE_CONDITION_RED_PACKET_OLD_PENDANT_SHARE_ICON", "udata/pkg/kwai-client-image/live_revenue_redpack/live_condition_red_packet_old_pendant_share_icon.webp");
       LiveRedPacketResourcePathConstant.LIVE_CONDITION_RED_PACKET_OLD_PENDANT_SHARE_ICON = liveRedPacke1;
       liveRedPacke[30] = liveRedPacke1;
       liveRedPacke1 = new LiveRedPacketResourcePathConstant("LIVE_ACTIVITY_RED_PACKET_OPENED_ACTION_BUTTON", 31, "LIVE_ACTIVITY_RED_PACKET_OPENED_ACTION_BUTTON", "udata/pkg/kwai-client-image/live_revenue_redpack/live_activity_red_packet_opened_action_button.webp");
       LiveRedPacketResourcePathConstant.LIVE_ACTIVITY_RED_PACKET_OPENED_ACTION_BUTTON = liveRedPacke1;
       liveRedPacke[31] = liveRedPacke1;
       liveRedPacke1 = new LiveRedPacketResourcePathConstant("LIVE_ACTIVITY_RED_PACKET_PREPARE_FOLLOWED_BUTTON", 32, "LIVE_ACTIVITY_RED_PACKET_PREPARE_FOLLOWED_BUTTON", "udata/pkg/kwai-client-image/live_revenue_redpack/live_activity_red_packet_prepare_followed_button.webp");
       LiveRedPacketResourcePathConstant.LIVE_ACTIVITY_RED_PACKET_PREPARE_FOLLOWED_BUTTON = liveRedPacke1;
       liveRedPacke[32] = liveRedPacke1;
       liveRedPacke1 = new LiveRedPacketResourcePathConstant("LIVE_RED_PACK_RECOMMEND_LEFT_TOP_ICON", 33, "LIVE_RED_PACK_RECOMMEND_LEFT_TOP_ICON", "udata/pkg/kwai-client-image/live_revenue_redpack/live_red_pack_recommend_left_top_icon.webp");
       LiveRedPacketResourcePathConstant.LIVE_RED_PACK_RECOMMEND_LEFT_TOP_ICON = liveRedPacke1;
       liveRedPacke[33] = liveRedPacke1;
       liveRedPacke1 = new LiveRedPacketResourcePathConstant("LIVE_FELLOW_RED_PACK_INTELLIGENT_DELIVERY_BACKGROUND", 34, "LIVE_FELLOW_RED_PACK_INTELLIGENT_DELIVERY_BACKGROUND", "udata/pkg/kwai-client-image/live_revenue_redpack/live_redpack_smart_decoration.png");
       LiveRedPacketResourcePathConstant.LIVE_FELLOW_RED_PACK_INTELLIGENT_DELIVERY_BACKGROUND = liveRedPacke1;
       liveRedPacke[34] = liveRedPacke1;
       liveRedPacke1 = new LiveRedPacketResourcePathConstant("LIVE_IC_ARROW_RED_PACK_CLOSE", 35, "LIVE_IC_ARROW_RED_PACK_CLOSE", "udata/pkg/kwai-client-image/live_revenue_redpack/live_ic_arrow_red_pack_close.webp");
       LiveRedPacketResourcePathConstant.LIVE_IC_ARROW_RED_PACK_CLOSE = liveRedPacke1;
       liveRedPacke[35] = liveRedPacke1;
       liveRedPacke1 = new LiveRedPacketResourcePathConstant("LIVE_RED_PACKET_POPUP_BTN_COIN_LIGHT", 36, "LIVE_RED_PACKET_POPUP_BTN_COIN_LIGHT", "udata/pkg/kwai-client-image/live_revenue_redpack/live_red_packet_popup_btn_coin_light.webp");
       LiveRedPacketResourcePathConstant.LIVE_RED_PACKET_POPUP_BTN_COIN_LIGHT = liveRedPacke1;
       liveRedPacke[36] = liveRedPacke1;
       liveRedPacke1 = new LiveRedPacketResourcePathConstant("LIVE_RED_PACKET_POP_TOP_COVER", 37, "LIVE_RED_PACKET_POP_TOP_COVER", "udata/pkg/kwai-client-image/live_revenue_redpack/live_redpacket_pop_top_cover.webp");
       LiveRedPacketResourcePathConstant.LIVE_RED_PACKET_POP_TOP_COVER = liveRedPacke1;
       liveRedPacke[37] = liveRedPacke1;
       liveRedPacke1 = new LiveRedPacketResourcePathConstant("LIVE_RED_PACKET_POP_BOTTOM_COVER", 38, "LIVE_RED_PACKET_POP_BOTTOM_COVER", "udata/pkg/kwai-client-image/live_revenue_redpack/live_redpacket_pop_bottom_cover.webp");
       LiveRedPacketResourcePathConstant.LIVE_RED_PACKET_POP_BOTTOM_COVER = liveRedPacke1;
       liveRedPacke[38] = liveRedPacke1;
       liveRedPacke1 = new LiveRedPacketResourcePathConstant("LIVE_RED_PACKET_SCROLL_AND_RESULT_DIALOG_COVER", 39, "LIVE_RED_PACKET_SCROLL_AND_RESULT_DIALOG_COVER", "udata/pkg/kwai-client-image/live_revenue_redpack/live_red_packet_scroll_and_result_dialog_cover.webp");
       LiveRedPacketResourcePathConstant.LIVE_RED_PACKET_SCROLL_AND_RESULT_DIALOG_COVER = liveRedPacke1;
       liveRedPacke[39] = liveRedPacke1;
       liveRedPacke1 = new LiveRedPacketResourcePathConstant("LIVE_RED_PACKET_SCROLL_AND_RESULT_DIALOG_FOREGROUND_COVER", 40, "LIVE_RED_PACKET_SCROLL_AND_RESULT_DIALOG_FOREGROUND_COVER", "udata/pkg/kwai-client-image/live_revenue_redpack/live_red_packet_scroll_and_result_dialog_foreground_cover.webp");
       LiveRedPacketResourcePathConstant.LIVE_RED_PACKET_SCROLL_AND_RESULT_DIALOG_FOREGROUND_COVER = liveRedPacke1;
       liveRedPacke[40] = liveRedPacke1;
       liveRedPacke1 = new LiveRedPacketResourcePathConstant("LIVE_RED_PACKET_NO_ONES_WIN_EMPTY_COVER", 41, "LIVE_RED_PACKET_SCROLL_AND_RESULT_DIALOG_FOREGROUND_COVER", "udata/pkg/kwai-client-image/live_revenue_redpack/live_red_packet_no_ones_win_empty_cover.webp");
       LiveRedPacketResourcePathConstant.LIVE_RED_PACKET_NO_ONES_WIN_EMPTY_COVER = liveRedPacke1;
       liveRedPacke[41] = liveRedPacke1;
       liveRedPacke1 = new LiveRedPacketResourcePathConstant("LIVE_RED_PACKET_CONDITON_PREPARE_NO_NET", 42, "LIVE_RED_PACKET_CONDITON_PREPARE_NO_NET", "udata/pkg/kwai-client-image/live_revenue_redpack/live_red_packet_conditon_prepare_no_net.png");
       LiveRedPacketResourcePathConstant.LIVE_RED_PACKET_CONDITON_PREPARE_NO_NET = liveRedPacke1;
       liveRedPacke[42] = liveRedPacke1;
       liveRedPacke1 = new LiveRedPacketResourcePathConstant("LIVE_RED_PACKET_CONDITON_RESULT_NO_NET", 43, "LIVE_RED_PACKET_CONDITON_RESULT_NO_NET", "udata/pkg/kwai-client-image/live_revenue_redpack/live_red_packet_conditon_result_no_net.png");
       LiveRedPacketResourcePathConstant.LIVE_RED_PACKET_CONDITON_RESULT_NO_NET = liveRedPacke1;
       liveRedPacke[43] = liveRedPacke1;
       LiveRedPacketResourcePathConstant.$VALUES = liveRedPacke;
    }
    public void LiveRedPacketResourcePathConstant(String p0,int p1,String p2,String p3){
       super(p0, p1);
       this.resourceName = p2;
       this.resourcePath = p3;
    }
    public static LiveRedPacketResourcePathConstant valueOf(String p0){
       Object obj = PatchProxy.applyOneRefs(p0, null, LiveRedPacketResourcePathConstant.class, "2");
       if (obj != PatchProxyResult.class) {
          return obj;
       }
       return Enum.valueOf(LiveRedPacketResourcePathConstant.class, p0);
    }
    public static LiveRedPacketResourcePathConstant[] values(){
       Object obj = PatchProxy.apply(null, null, LiveRedPacketResourcePathConstant.class, "1");
       if (obj != PatchProxyResult.class) {
          return obj;
       }
       return LiveRedPacketResourcePathConstant.$VALUES.clone();
    }
    public String getResourceName(){
       return this.resourceName;
    }
    public String getResourcePath(){
       return this.resourcePath;
    }
}
