package com.kuaishou.live.bottombarapi.LiveAnchorBottomBarId;
import java.lang.Enum;
import java.lang.String;
import java.lang.Object;
import java.lang.Class;
import com.kwai.robust.PatchProxy;
import com.kwai.robust.PatchProxyResult;

public final class LiveAnchorBottomBarId extends Enum	// class@000d67
{
    public final int mFeatureType;
    public static final LiveAnchorBottomBarId[] $VALUES;
    public static final LiveAnchorBottomBarId FEATURE_BOTTOM_LIVE_INTERACTIVE_FUNCTION_AGGREGATION;
    public static final LiveAnchorBottomBarId FEATURE_ITEM_ID_VOICE_PARTY_ENTRY_BEAUTIFY;
    public static final LiveAnchorBottomBarId FEATURE_ITEM_ID_VOICE_PARTY_PLAY_TYPE_CROSS_ROOM_PK;
    public static final LiveAnchorBottomBarId FEATURE_ITEM_ID_VOICE_PARTY_PLAY_TYPE_GRID_CHAT;
    public static final LiveAnchorBottomBarId FEATURE_ITEM_ID_VOICE_PARTY_PLAY_TYPE_KTV;
    public static final LiveAnchorBottomBarId FEATURE_ITEM_ID_VOICE_PARTY_PLAY_TYPE_SIX_AUDIO;
    public static final LiveAnchorBottomBarId FEATURE_ITEM_ID_VOICE_PARTY_PLAY_TYPE_SIX_VIDEO;
    public static final LiveAnchorBottomBarId FEATURE_ITEM_ID_VOICE_PARTY_PLAY_TYPE_TEAM_PK;
    public static final LiveAnchorBottomBarId FEATURE_ITEM_ID_VOICE_PARTY_PLAY_TYPE_THEATER;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_ADMIN_MANAGE;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_ADMIN_RECORD;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_ANCHOR_CENTER;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_ANCHOR_TASK;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_ANNOUNCE;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_ANONYMOUS_LIVE;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_ASK;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_AUTO_INVITATION_AUDIENCE_MIC;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_AUTO_PLAY_VOICE_COMMENT;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_AUTO_WELCOME_AUDIENCE;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_BACKGROUND_MUSIC;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_BEAUTIFY;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_BLOCK_HISTORY;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_BUY_PUSH;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_COMMENT;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_CONVERSION_TASK;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_COUPON_RED_PACK;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_DECORATION;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_ENTRY_PROMPT;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_ESCROW;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_GIFT;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_GIFT_EFFECT_AUDIENCE;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_GIFT_EFFECT_AUTHOR;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_GIFT_MAGIC;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_HOUSE;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_KTV;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_KTV_ROOM;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_LIVE_CHAT_APPLY;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_LIVE_INCREASE_FANS;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_LIVE_PAY_BULLET;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_LIVE_PLAYBACK;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_LIVE_PORTAL;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_LIVE_PROMOTION;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_LIVE_SUBSCRIBE;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_LIVE_VIP_GRADE;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_LIVE_VOICE_PARTY;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_LIVE_VOICE_PARTY_GUEST_OPEN_VIDEO;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_LIVE_VOTE;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_LOCAL_LIFE;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_LUCKY_STAR;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_MAGIC_FACE;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_MIRROR;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_MORE;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_MORE_CONVERSION_TASK;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_MORE_LIVE_PROMOTION;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_MORE_PAGE_ANCHOR_TASK;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_MORE_PAGE_SELL;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_MUSIC;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_NEW_LIVE_CHAT_APPLY;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_NOTIFY_FOLLOWERS;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_PK;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_RED_PACK;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_RED_PACKAGE_SETTING;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_REVENUE_DELIVERY_FLOW_DIVERSION;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_ROBOT;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_SCREEN_RECORD;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_SELL;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_SENSITIVE_WORDS;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_SETTINGS;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_SHARE;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_SOUND_EFFECT;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_STICKER;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_SWITCH_CAMERA;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_TOPIC;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_TUHAO_OFFLINE;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_TUNA;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_UNKNOWN;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_VOICE_COMMENT;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_VOICE_PARTY_BACKGROUND;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_VOICE_PARTY_CROSS_ROOM_PK_WAITING;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_VOICE_PARTY_DECORATION;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_VOICE_PARTY_EMOJI;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_VOICE_PARTY_KTV_ORDER_MUSIC;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_VOICE_PARTY_MIC_ABOARD_SWITCH;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_VOICE_PARTY_MIC_INVITE;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_VOICE_PARTY_MUTE;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_VOICE_PARTY_PLAY_AGGREGATION;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_VOICE_PARTY_SETTING;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_VOICE_PARTY_TEAM_PK;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_VOICE_PARTY_THEATER_PLAY_LIST;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_WALLET;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_WEEKLY_RANK;
    public static final LiveAnchorBottomBarId FUNCTION_ITEM_ID_WISH_LIST;
    public static final LiveAnchorBottomBarId FUNCTION_ITME_ID_LIVE_VOICE_PARTY_FANS_ABOARD;

    static {
       LiveAnchorBottomBarId liveAnchorBo = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_UNKNOWN", 0, 0);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_UNKNOWN = liveAnchorBo;
       LiveAnchorBottomBarId liveAnchorBo1 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_BACKGROUND_MUSIC", 1, 1);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_BACKGROUND_MUSIC = liveAnchorBo1;
       LiveAnchorBottomBarId liveAnchorBo2 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_KTV", 2, 2);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_KTV = liveAnchorBo2;
       LiveAnchorBottomBarId liveAnchorBo3 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_KTV_ROOM", 3, 3);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_KTV_ROOM = liveAnchorBo3;
       LiveAnchorBottomBarId liveAnchorBo4 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_SOUND_EFFECT", 4, 4);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_SOUND_EFFECT = liveAnchorBo4;
       LiveAnchorBottomBarId liveAnchorBo5 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_MAGIC_FACE", 5, 5);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_MAGIC_FACE = liveAnchorBo5;
       LiveAnchorBottomBarId liveAnchorBo6 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_BEAUTIFY", 6, 6);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_BEAUTIFY = liveAnchorBo6;
       LiveAnchorBottomBarId liveAnchorBo7 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_STICKER", 7, 7);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_STICKER = liveAnchorBo7;
       LiveAnchorBottomBarId liveAnchorBo8 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_RED_PACK", 8, 8);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_RED_PACK = liveAnchorBo8;
       LiveAnchorBottomBarId liveAnchorBo9 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_WISH_LIST", 9, 9);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_WISH_LIST = liveAnchorBo9;
       LiveAnchorBottomBarId liveAnchorBo10 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_ROBOT", 10, 10);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_ROBOT = liveAnchorBo10;
       LiveAnchorBottomBarId liveAnchorBo11 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_LUCKY_STAR", 11, 11);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_LUCKY_STAR = liveAnchorBo11;
       LiveAnchorBottomBarId liveAnchorBo12 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_LIVE_VOTE", 12, 12);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_LIVE_VOTE = liveAnchorBo12;
       LiveAnchorBottomBarId liveAnchorBo13 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_ASK", 13, 13);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_ASK = liveAnchorBo13;
       LiveAnchorBottomBarId liveAnchorBo14 = liveAnchorBo13;
       LiveAnchorBottomBarId liveAnchorBo15 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_LIVE_VOICE_PARTY", 14, 14);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_LIVE_VOICE_PARTY = liveAnchorBo15;
       LiveAnchorBottomBarId liveAnchorBo16 = liveAnchorBo15;
       LiveAnchorBottomBarId liveAnchorBo17 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_VOICE_PARTY_TEAM_PK", 15, 15);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_VOICE_PARTY_TEAM_PK = liveAnchorBo17;
       LiveAnchorBottomBarId liveAnchorBo18 = liveAnchorBo17;
       liveAnchorBo13 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_WALLET", 16, 16);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_WALLET = liveAnchorBo13;
       LiveAnchorBottomBarId liveAnchorBo19 = liveAnchorBo13;
       liveAnchorBo15 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_MIRROR", 17, 17);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_MIRROR = liveAnchorBo15;
       LiveAnchorBottomBarId liveAnchorBo20 = liveAnchorBo15;
       liveAnchorBo17 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_LIVE_SUBSCRIBE", 18, 18);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_LIVE_SUBSCRIBE = liveAnchorBo17;
       LiveAnchorBottomBarId liveAnchorBo21 = liveAnchorBo17;
       liveAnchorBo13 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_SETTINGS", 19, 19);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_SETTINGS = liveAnchorBo13;
       LiveAnchorBottomBarId liveAnchorBo22 = liveAnchorBo13;
       LiveAnchorBottomBarId liveAnchorBo23 = liveAnchorBo12;
       liveAnchorBo15 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_ANCHOR_TASK", 20, 57);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_ANCHOR_TASK = liveAnchorBo15;
       LiveAnchorBottomBarId liveAnchorBo24 = liveAnchorBo15;
       liveAnchorBo17 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_MORE_PAGE_ANCHOR_TASK", 21, 20);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_MORE_PAGE_ANCHOR_TASK = liveAnchorBo17;
       LiveAnchorBottomBarId liveAnchorBo25 = liveAnchorBo17;
       liveAnchorBo15 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_SELL", 22, 58);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_SELL = liveAnchorBo15;
       LiveAnchorBottomBarId liveAnchorBo26 = liveAnchorBo15;
       liveAnchorBo17 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_MORE_PAGE_SELL", 23, 21);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_MORE_PAGE_SELL = liveAnchorBo17;
       LiveAnchorBottomBarId liveAnchorBo27 = liveAnchorBo17;
       liveAnchorBo15 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_CONVERSION_TASK", 24, 59);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_CONVERSION_TASK = liveAnchorBo15;
       LiveAnchorBottomBarId liveAnchorBo28 = liveAnchorBo15;
       liveAnchorBo17 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_MORE_CONVERSION_TASK", 25, 22);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_MORE_CONVERSION_TASK = liveAnchorBo17;
       LiveAnchorBottomBarId liveAnchorBo29 = liveAnchorBo17;
       liveAnchorBo15 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_LIVE_PROMOTION", 26, 60);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_LIVE_PROMOTION = liveAnchorBo15;
       LiveAnchorBottomBarId liveAnchorBo30 = liveAnchorBo15;
       liveAnchorBo17 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_MORE_LIVE_PROMOTION", 27, 23);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_MORE_LIVE_PROMOTION = liveAnchorBo17;
       LiveAnchorBottomBarId liveAnchorBo31 = liveAnchorBo17;
       liveAnchorBo15 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_COMMENT", 28, 24);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_COMMENT = liveAnchorBo15;
       LiveAnchorBottomBarId liveAnchorBo32 = liveAnchorBo15;
       liveAnchorBo17 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_GIFT", 29, 25);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_GIFT = liveAnchorBo17;
       LiveAnchorBottomBarId liveAnchorBo33 = liveAnchorBo17;
       liveAnchorBo15 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_SWITCH_CAMERA", 30, 26);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_SWITCH_CAMERA = liveAnchorBo15;
       LiveAnchorBottomBarId liveAnchorBo34 = liveAnchorBo15;
       liveAnchorBo17 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_SHARE", 31, 27);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_SHARE = liveAnchorBo17;
       LiveAnchorBottomBarId liveAnchorBo35 = liveAnchorBo17;
       liveAnchorBo15 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_ESCROW", 32, 28);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_ESCROW = liveAnchorBo15;
       LiveAnchorBottomBarId liveAnchorBo36 = liveAnchorBo15;
       liveAnchorBo17 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_VOICE_PARTY_BACKGROUND", 33, 29);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_VOICE_PARTY_BACKGROUND = liveAnchorBo17;
       LiveAnchorBottomBarId liveAnchorBo37 = liveAnchorBo17;
       liveAnchorBo15 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_ANCHOR_CENTER", 34, 30);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_ANCHOR_CENTER = liveAnchorBo15;
       LiveAnchorBottomBarId liveAnchorBo38 = liveAnchorBo15;
       liveAnchorBo17 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_PK", 35, 31);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_PK = liveAnchorBo17;
       LiveAnchorBottomBarId liveAnchorBo39 = liveAnchorBo17;
       liveAnchorBo15 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_NEW_LIVE_CHAT_APPLY", 36, 32);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_NEW_LIVE_CHAT_APPLY = liveAnchorBo15;
       liveAnchorBo17 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_LIVE_CHAT_APPLY", 37);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_LIVE_CHAT_APPLY = liveAnchorBo17;
       LiveAnchorBottomBarId liveAnchorBo40 = liveAnchorBo17;
       LiveAnchorBottomBarId liveAnchorBo41 = liveAnchorBo15;
       liveAnchorBo13 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_MUSIC", 38, 33);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_MUSIC = liveAnchorBo13;
       LiveAnchorBottomBarId liveAnchorBo42 = liveAnchorBo13;
       liveAnchorBo17 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_DECORATION", 39, 34);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_DECORATION = liveAnchorBo17;
       LiveAnchorBottomBarId liveAnchorBo43 = liveAnchorBo17;
       liveAnchorBo15 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_MORE", 40, 35);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_MORE = liveAnchorBo15;
       LiveAnchorBottomBarId liveAnchorBo44 = liveAnchorBo15;
       liveAnchorBo17 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_GIFT_MAGIC", 41, 36);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_GIFT_MAGIC = liveAnchorBo17;
       LiveAnchorBottomBarId liveAnchorBo45 = liveAnchorBo17;
       liveAnchorBo15 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_TUHAO_OFFLINE", 42, 37);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_TUHAO_OFFLINE = liveAnchorBo15;
       LiveAnchorBottomBarId liveAnchorBo46 = liveAnchorBo15;
       liveAnchorBo17 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_WEEKLY_RANK", 43, 38);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_WEEKLY_RANK = liveAnchorBo17;
       LiveAnchorBottomBarId liveAnchorBo47 = liveAnchorBo17;
       liveAnchorBo15 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_RED_PACKAGE_SETTING", 44, 39);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_RED_PACKAGE_SETTING = liveAnchorBo15;
       LiveAnchorBottomBarId liveAnchorBo48 = liveAnchorBo15;
       liveAnchorBo17 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_VOICE_COMMENT", 45, 40);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_VOICE_COMMENT = liveAnchorBo17;
       LiveAnchorBottomBarId liveAnchorBo49 = liveAnchorBo17;
       liveAnchorBo15 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_ENTRY_PROMPT", 46, 41);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_ENTRY_PROMPT = liveAnchorBo15;
       LiveAnchorBottomBarId liveAnchorBo50 = liveAnchorBo15;
       liveAnchorBo17 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_SCREEN_RECORD", 47, 42);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_SCREEN_RECORD = liveAnchorBo17;
       LiveAnchorBottomBarId liveAnchorBo51 = liveAnchorBo17;
       liveAnchorBo15 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_SENSITIVE_WORDS", 48, 43);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_SENSITIVE_WORDS = liveAnchorBo15;
       LiveAnchorBottomBarId liveAnchorBo52 = liveAnchorBo15;
       liveAnchorBo17 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_ADMIN_MANAGE", 49, 44);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_ADMIN_MANAGE = liveAnchorBo17;
       LiveAnchorBottomBarId liveAnchorBo53 = liveAnchorBo17;
       liveAnchorBo15 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_ADMIN_RECORD", 50, 45);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_ADMIN_RECORD = liveAnchorBo15;
       LiveAnchorBottomBarId liveAnchorBo54 = liveAnchorBo15;
       liveAnchorBo17 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_BLOCK_HISTORY", 51, 46);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_BLOCK_HISTORY = liveAnchorBo17;
       LiveAnchorBottomBarId liveAnchorBo55 = liveAnchorBo17;
       liveAnchorBo15 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_ANONYMOUS_LIVE", 52, 47);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_ANONYMOUS_LIVE = liveAnchorBo15;
       LiveAnchorBottomBarId liveAnchorBo56 = liveAnchorBo15;
       liveAnchorBo17 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_AUTO_INVITATION_AUDIENCE_MIC", 53, 48);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_AUTO_INVITATION_AUDIENCE_MIC = liveAnchorBo17;
       LiveAnchorBottomBarId liveAnchorBo57 = liveAnchorBo17;
       liveAnchorBo15 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_AUTO_WELCOME_AUDIENCE", 54, 49);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_AUTO_WELCOME_AUDIENCE = liveAnchorBo15;
       LiveAnchorBottomBarId liveAnchorBo58 = liveAnchorBo15;
       liveAnchorBo17 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_NOTIFY_FOLLOWERS", 55, 50);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_NOTIFY_FOLLOWERS = liveAnchorBo17;
       LiveAnchorBottomBarId liveAnchorBo59 = liveAnchorBo17;
       liveAnchorBo15 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_COUPON_RED_PACK", 56, 51);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_COUPON_RED_PACK = liveAnchorBo15;
       LiveAnchorBottomBarId liveAnchorBo60 = liveAnchorBo15;
       liveAnchorBo17 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_TUNA", 57, 52);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_TUNA = liveAnchorBo17;
       LiveAnchorBottomBarId liveAnchorBo61 = liveAnchorBo17;
       liveAnchorBo15 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_VOICE_PARTY_SETTING", 58, 54);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_VOICE_PARTY_SETTING = liveAnchorBo15;
       LiveAnchorBottomBarId liveAnchorBo62 = liveAnchorBo15;
       liveAnchorBo17 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_BUY_PUSH", 59, 55);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_BUY_PUSH = liveAnchorBo17;
       LiveAnchorBottomBarId liveAnchorBo63 = liveAnchorBo17;
       liveAnchorBo15 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_LIVE_PLAYBACK", 60, 56);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_LIVE_PLAYBACK = liveAnchorBo15;
       LiveAnchorBottomBarId liveAnchorBo64 = liveAnchorBo15;
       liveAnchorBo17 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_ANNOUNCE", 61, 61);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_ANNOUNCE = liveAnchorBo17;
       LiveAnchorBottomBarId liveAnchorBo65 = liveAnchorBo17;
       liveAnchorBo15 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_TOPIC", 62, 70);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_TOPIC = liveAnchorBo15;
       LiveAnchorBottomBarId liveAnchorBo66 = liveAnchorBo15;
       liveAnchorBo17 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_VOICE_PARTY_MIC_ABOARD_SWITCH", 63, 71);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_VOICE_PARTY_MIC_ABOARD_SWITCH = liveAnchorBo17;
       LiveAnchorBottomBarId liveAnchorBo67 = liveAnchorBo17;
       liveAnchorBo15 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_LIVE_INCREASE_FANS", 64, 73);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_LIVE_INCREASE_FANS = liveAnchorBo15;
       LiveAnchorBottomBarId liveAnchorBo68 = liveAnchorBo15;
       liveAnchorBo17 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_REVENUE_DELIVERY_FLOW_DIVERSION", 65, 75);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_REVENUE_DELIVERY_FLOW_DIVERSION = liveAnchorBo17;
       LiveAnchorBottomBarId liveAnchorBo69 = liveAnchorBo17;
       liveAnchorBo15 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_LIVE_PAY_BULLET", 66, 78);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_LIVE_PAY_BULLET = liveAnchorBo15;
       LiveAnchorBottomBarId liveAnchorBo70 = liveAnchorBo15;
       liveAnchorBo17 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_LIVE_PORTAL", 67, 76);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_LIVE_PORTAL = liveAnchorBo17;
       LiveAnchorBottomBarId liveAnchorBo71 = liveAnchorBo17;
       liveAnchorBo15 = new LiveAnchorBottomBarId("FUNCTION_ITME_ID_LIVE_VOICE_PARTY_FANS_ABOARD", 68, 79);
       LiveAnchorBottomBarId.FUNCTION_ITME_ID_LIVE_VOICE_PARTY_FANS_ABOARD = liveAnchorBo15;
       LiveAnchorBottomBarId liveAnchorBo72 = liveAnchorBo15;
       liveAnchorBo17 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_LIVE_VOICE_PARTY_GUEST_OPEN_VIDEO", 69, 82);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_LIVE_VOICE_PARTY_GUEST_OPEN_VIDEO = liveAnchorBo17;
       LiveAnchorBottomBarId liveAnchorBo73 = liveAnchorBo17;
       liveAnchorBo15 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_VOICE_PARTY_MIC_INVITE", 70, 89);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_VOICE_PARTY_MIC_INVITE = liveAnchorBo15;
       LiveAnchorBottomBarId liveAnchorBo74 = liveAnchorBo15;
       liveAnchorBo17 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_VOICE_PARTY_MUTE", 71, 90);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_VOICE_PARTY_MUTE = liveAnchorBo17;
       LiveAnchorBottomBarId liveAnchorBo75 = liveAnchorBo17;
       liveAnchorBo15 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_VOICE_PARTY_PLAY_AGGREGATION", 72, 91);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_VOICE_PARTY_PLAY_AGGREGATION = liveAnchorBo15;
       LiveAnchorBottomBarId liveAnchorBo76 = liveAnchorBo15;
       liveAnchorBo17 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_VOICE_PARTY_EMOJI", 73, 92);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_VOICE_PARTY_EMOJI = liveAnchorBo17;
       LiveAnchorBottomBarId liveAnchorBo77 = liveAnchorBo17;
       liveAnchorBo15 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_VOICE_PARTY_KTV_ORDER_MUSIC", 74, 93);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_VOICE_PARTY_KTV_ORDER_MUSIC = liveAnchorBo15;
       LiveAnchorBottomBarId liveAnchorBo78 = liveAnchorBo15;
       liveAnchorBo17 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_VOICE_PARTY_THEATER_PLAY_LIST", 75, 94);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_VOICE_PARTY_THEATER_PLAY_LIST = liveAnchorBo17;
       LiveAnchorBottomBarId liveAnchorBo79 = liveAnchorBo17;
       liveAnchorBo15 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_VOICE_PARTY_DECORATION", 76, 95);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_VOICE_PARTY_DECORATION = liveAnchorBo15;
       LiveAnchorBottomBarId liveAnchorBo80 = liveAnchorBo15;
       liveAnchorBo17 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_VOICE_PARTY_CROSS_ROOM_PK_WAITING", 77, 96);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_VOICE_PARTY_CROSS_ROOM_PK_WAITING = liveAnchorBo17;
       LiveAnchorBottomBarId liveAnchorBo81 = liveAnchorBo17;
       liveAnchorBo15 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_AUTO_PLAY_VOICE_COMMENT", 78, 98);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_AUTO_PLAY_VOICE_COMMENT = liveAnchorBo15;
       LiveAnchorBottomBarId liveAnchorBo82 = liveAnchorBo15;
       liveAnchorBo17 = new LiveAnchorBottomBarId("FEATURE_ITEM_ID_VOICE_PARTY_PLAY_TYPE_SIX_AUDIO", 79, 101);
       LiveAnchorBottomBarId.FEATURE_ITEM_ID_VOICE_PARTY_PLAY_TYPE_SIX_AUDIO = liveAnchorBo17;
       LiveAnchorBottomBarId liveAnchorBo83 = liveAnchorBo17;
       liveAnchorBo15 = new LiveAnchorBottomBarId("FEATURE_ITEM_ID_VOICE_PARTY_PLAY_TYPE_SIX_VIDEO", 80, 102);
       LiveAnchorBottomBarId.FEATURE_ITEM_ID_VOICE_PARTY_PLAY_TYPE_SIX_VIDEO = liveAnchorBo15;
       LiveAnchorBottomBarId liveAnchorBo84 = liveAnchorBo15;
       liveAnchorBo17 = new LiveAnchorBottomBarId("FEATURE_ITEM_ID_VOICE_PARTY_PLAY_TYPE_GRID_CHAT", 81, 103);
       LiveAnchorBottomBarId.FEATURE_ITEM_ID_VOICE_PARTY_PLAY_TYPE_GRID_CHAT = liveAnchorBo17;
       LiveAnchorBottomBarId liveAnchorBo85 = liveAnchorBo17;
       liveAnchorBo15 = new LiveAnchorBottomBarId("FEATURE_ITEM_ID_VOICE_PARTY_PLAY_TYPE_KTV", 82, 104);
       LiveAnchorBottomBarId.FEATURE_ITEM_ID_VOICE_PARTY_PLAY_TYPE_KTV = liveAnchorBo15;
       LiveAnchorBottomBarId liveAnchorBo86 = liveAnchorBo15;
       liveAnchorBo17 = new LiveAnchorBottomBarId("FEATURE_ITEM_ID_VOICE_PARTY_PLAY_TYPE_THEATER", 83, 105);
       LiveAnchorBottomBarId.FEATURE_ITEM_ID_VOICE_PARTY_PLAY_TYPE_THEATER = liveAnchorBo17;
       LiveAnchorBottomBarId liveAnchorBo87 = liveAnchorBo17;
       liveAnchorBo15 = new LiveAnchorBottomBarId("FEATURE_ITEM_ID_VOICE_PARTY_PLAY_TYPE_TEAM_PK", 84, 106);
       LiveAnchorBottomBarId.FEATURE_ITEM_ID_VOICE_PARTY_PLAY_TYPE_TEAM_PK = liveAnchorBo15;
       LiveAnchorBottomBarId liveAnchorBo88 = liveAnchorBo15;
       liveAnchorBo17 = new LiveAnchorBottomBarId("FEATURE_ITEM_ID_VOICE_PARTY_PLAY_TYPE_CROSS_ROOM_PK", 85, 107);
       LiveAnchorBottomBarId.FEATURE_ITEM_ID_VOICE_PARTY_PLAY_TYPE_CROSS_ROOM_PK = liveAnchorBo17;
       LiveAnchorBottomBarId liveAnchorBo89 = liveAnchorBo17;
       liveAnchorBo15 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_LIVE_VIP_GRADE", 86, 108);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_LIVE_VIP_GRADE = liveAnchorBo15;
       LiveAnchorBottomBarId liveAnchorBo90 = liveAnchorBo15;
       liveAnchorBo17 = new LiveAnchorBottomBarId("FEATURE_ITEM_ID_VOICE_PARTY_ENTRY_BEAUTIFY", 87, 110);
       LiveAnchorBottomBarId.FEATURE_ITEM_ID_VOICE_PARTY_ENTRY_BEAUTIFY = liveAnchorBo17;
       LiveAnchorBottomBarId liveAnchorBo91 = liveAnchorBo17;
       liveAnchorBo15 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_GIFT_EFFECT_AUTHOR", 88, 111);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_GIFT_EFFECT_AUTHOR = liveAnchorBo15;
       LiveAnchorBottomBarId liveAnchorBo92 = liveAnchorBo15;
       liveAnchorBo17 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_GIFT_EFFECT_AUDIENCE", 89, 112);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_GIFT_EFFECT_AUDIENCE = liveAnchorBo17;
       LiveAnchorBottomBarId liveAnchorBo93 = liveAnchorBo17;
       liveAnchorBo15 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_LOCAL_LIFE", 90, 122);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_LOCAL_LIFE = liveAnchorBo15;
       LiveAnchorBottomBarId liveAnchorBo94 = liveAnchorBo15;
       liveAnchorBo17 = new LiveAnchorBottomBarId("FUNCTION_ITEM_ID_HOUSE", 91, 125);
       LiveAnchorBottomBarId.FUNCTION_ITEM_ID_HOUSE = liveAnchorBo17;
       LiveAnchorBottomBarId liveAnchorBo95 = liveAnchorBo17;
       liveAnchorBo15 = new LiveAnchorBottomBarId("FEATURE_BOTTOM_LIVE_INTERACTIVE_FUNCTION_AGGREGATION", 92, 126);
       LiveAnchorBottomBarId.FEATURE_BOTTOM_LIVE_INTERACTIVE_FUNCTION_AGGREGATION = liveAnchorBo15;
       LiveAnchorBottomBarId[] liveAnchorBo96 = new LiveAnchorBottomBarId[93];
       liveAnchorBo96[0] = liveAnchorBo;
       liveAnchorBo96[1] = liveAnchorBo1;
       liveAnchorBo96[2] = liveAnchorBo2;
       liveAnchorBo96[3] = liveAnchorBo3;
       liveAnchorBo96[4] = liveAnchorBo4;
       liveAnchorBo96[5] = liveAnchorBo5;
       liveAnchorBo96[6] = liveAnchorBo6;
       liveAnchorBo96[7] = liveAnchorBo7;
       liveAnchorBo96[8] = liveAnchorBo8;
       liveAnchorBo96[9] = liveAnchorBo9;
       liveAnchorBo96[10] = liveAnchorBo10;
       liveAnchorBo96[11] = liveAnchorBo11;
       liveAnchorBo96[12] = liveAnchorBo23;
       liveAnchorBo96[13] = liveAnchorBo14;
       liveAnchorBo96[14] = liveAnchorBo16;
       liveAnchorBo96[15] = liveAnchorBo18;
       liveAnchorBo96[16] = liveAnchorBo19;
       liveAnchorBo96[17] = liveAnchorBo20;
       liveAnchorBo96[18] = liveAnchorBo21;
       liveAnchorBo96[19] = liveAnchorBo22;
       liveAnchorBo96[20] = liveAnchorBo24;
       liveAnchorBo96[21] = liveAnchorBo25;
       liveAnchorBo96[22] = liveAnchorBo26;
       liveAnchorBo96[23] = liveAnchorBo27;
       liveAnchorBo96[24] = liveAnchorBo28;
       liveAnchorBo96[25] = liveAnchorBo29;
       liveAnchorBo96[26] = liveAnchorBo30;
       liveAnchorBo96[27] = liveAnchorBo31;
       liveAnchorBo96[28] = liveAnchorBo32;
       liveAnchorBo96[29] = liveAnchorBo33;
       liveAnchorBo96[30] = liveAnchorBo34;
       liveAnchorBo96[31] = liveAnchorBo35;
       liveAnchorBo96[32] = liveAnchorBo36;
       liveAnchorBo96[33] = liveAnchorBo37;
       liveAnchorBo96[34] = liveAnchorBo38;
       liveAnchorBo96[35] = liveAnchorBo39;
       liveAnchorBo96[36] = liveAnchorBo41;
       liveAnchorBo96[37] = liveAnchorBo40;
       liveAnchorBo96[38] = liveAnchorBo42;
       liveAnchorBo96[39] = liveAnchorBo43;
       liveAnchorBo96[40] = liveAnchorBo44;
       liveAnchorBo96[41] = liveAnchorBo45;
       liveAnchorBo96[42] = liveAnchorBo46;
       liveAnchorBo96[43] = liveAnchorBo47;
       liveAnchorBo96[44] = liveAnchorBo48;
       liveAnchorBo96[45] = liveAnchorBo49;
       liveAnchorBo96[46] = liveAnchorBo50;
       liveAnchorBo96[47] = liveAnchorBo51;
       liveAnchorBo96[48] = liveAnchorBo52;
       liveAnchorBo96[49] = liveAnchorBo53;
       liveAnchorBo96[50] = liveAnchorBo54;
       liveAnchorBo96[51] = liveAnchorBo55;
       liveAnchorBo96[52] = liveAnchorBo56;
       liveAnchorBo96[53] = liveAnchorBo57;
       liveAnchorBo96[54] = liveAnchorBo58;
       liveAnchorBo96[55] = liveAnchorBo59;
       liveAnchorBo96[56] = liveAnchorBo60;
       liveAnchorBo96[57] = liveAnchorBo61;
       liveAnchorBo96[58] = liveAnchorBo62;
       liveAnchorBo96[59] = liveAnchorBo63;
       liveAnchorBo96[60] = liveAnchorBo64;
       liveAnchorBo96[61] = liveAnchorBo65;
       liveAnchorBo96[62] = liveAnchorBo66;
       liveAnchorBo96[63] = liveAnchorBo67;
       liveAnchorBo96[64] = liveAnchorBo68;
       liveAnchorBo96[65] = liveAnchorBo69;
       liveAnchorBo96[66] = liveAnchorBo70;
       liveAnchorBo96[67] = liveAnchorBo71;
       liveAnchorBo96[68] = liveAnchorBo72;
       liveAnchorBo96[69] = liveAnchorBo73;
       liveAnchorBo96[70] = liveAnchorBo74;
       liveAnchorBo96[71] = liveAnchorBo75;
       liveAnchorBo96[72] = liveAnchorBo76;
       liveAnchorBo96[73] = liveAnchorBo77;
       liveAnchorBo96[74] = liveAnchorBo78;
       liveAnchorBo96[75] = liveAnchorBo79;
       liveAnchorBo96[76] = liveAnchorBo80;
       liveAnchorBo96[77] = liveAnchorBo81;
       liveAnchorBo96[78] = liveAnchorBo82;
       liveAnchorBo96[79] = liveAnchorBo83;
       liveAnchorBo96[80] = liveAnchorBo84;
       liveAnchorBo96[81] = liveAnchorBo85;
       liveAnchorBo96[82] = liveAnchorBo86;
       liveAnchorBo96[83] = liveAnchorBo87;
       liveAnchorBo96[84] = liveAnchorBo88;
       liveAnchorBo96[85] = liveAnchorBo89;
       liveAnchorBo96[86] = liveAnchorBo90;
       liveAnchorBo96[87] = liveAnchorBo91;
       liveAnchorBo96[88] = liveAnchorBo92;
       liveAnchorBo96[89] = liveAnchorBo93;
       liveAnchorBo96[90] = liveAnchorBo94;
       liveAnchorBo96[91] = liveAnchorBo95;
       liveAnchorBo96[92] = liveAnchorBo15;
       LiveAnchorBottomBarId.$VALUES = liveAnchorBo96;
    }
    public void LiveAnchorBottomBarId(String p0,int p1){
       super(p0, p1, 0);
    }
    public void LiveAnchorBottomBarId(String p0,int p1,int p2){
       super(p0, p1);
       this.mFeatureType = p2;
    }
    public static LiveAnchorBottomBarId valueOf(String p0){
       Object obj = PatchProxy.applyOneRefs(p0, null, LiveAnchorBottomBarId.class, "2");
       if (obj != PatchProxyResult.class) {
          return obj;
       }
       return Enum.valueOf(LiveAnchorBottomBarId.class, p0);
    }
    public static LiveAnchorBottomBarId[] values(){
       Object obj = PatchProxy.apply(null, null, LiveAnchorBottomBarId.class, "1");
       if (obj != PatchProxyResult.class) {
          return obj;
       }
       return LiveAnchorBottomBarId.$VALUES.clone();
    }
    public int getFeatureType(){
       return this.mFeatureType;
    }
}
