package w0.k;
import android.view.ViewGroup;
import androidx.appcompat.view.menu.j$a;
import androidx.appcompat.view.menu.e$a;
import android.widget.SpinnerAdapter;
import android.widget.AdapterView$OnItemSelectedListener;
import android.view.View;
import android.graphics.drawable.Drawable;
import android.util.SparseArray;
import android.view.Menu;
import androidx.appcompat.widget.ScrollingTabContainerView;
import android.content.Context;
import java.lang.CharSequence;
import android.view.Window$Callback;
import a2.m0;

public interface abstract k	// class@002ea7
{

    ViewGroup A();
    void B(boolean p0);
    void C(int p0);
    boolean D();
    void E(int p0);
    void F(j$a p0,e$a p1);
    void G(SpinnerAdapter p0,AdapterView$OnItemSelectedListener p1);
    boolean H();
    int I();
    View J();
    void K(Drawable p0);
    void L(SparseArray p0);
    void M(View p0);
    void N();
    void O(int p0);
    Menu P();
    void Q(ScrollingTabContainerView p0);
    void R(SparseArray p0);
    boolean a();
    void b(Menu p0,j$a p1);
    boolean c();
    void collapseActionView();
    boolean d();
    void e(Drawable p0);
    boolean f();
    boolean g();
    Context getContext();
    int getHeight();
    CharSequence getSubtitle();
    CharSequence getTitle();
    int getVisibility();
    boolean h();
    void i();
    boolean j();
    boolean k();
    void l(int p0);
    void m(CharSequence p0);
    int n();
    void o(int p0);
    void p(int p0);
    void q();
    int r();
    void s(boolean p0);
    void setIcon(int p0);
    void setIcon(Drawable p0);
    void setLogo(int p0);
    void setTitle(CharSequence p0);
    void setVisibility(int p0);
    void setWindowCallback(Window$Callback p0);
    void setWindowTitle(CharSequence p0);
    void t();
    void u(Drawable p0);
    void v(int p0);
    int w();
    void x(Drawable p0);
    void y(CharSequence p0);
    m0 z(int p0,long p1);
}
