package com.kwai.feature.api.live.base.service.model.LiveStreamClickType;
import java.lang.Enum;
import java.lang.String;
import java.lang.Object;
import java.lang.Class;
import com.kwai.robust.PatchProxy;
import com.kwai.robust.PatchProxyResult;

public final class LiveStreamClickType extends Enum	// class@000f9a
{
    public final int value;
    public static final LiveStreamClickType[] $VALUES;
    public static final LiveStreamClickType ANCHOR_FANS_LIST;
    public static final LiveStreamClickType FEED_LIST;
    public static final LiveStreamClickType GIFT_SLOT;
    public static final LiveStreamClickType LITE_ANCHOR_INFO;
    public static final LiveStreamClickType LITE_INTERACTIVE_MESSAGE;
    public static final LiveStreamClickType LIVE_AUCTION;
    public static final LiveStreamClickType LIVE_AUDIENCE_FOLLOW_CARD_PREFETCH;
    public static final LiveStreamClickType LIVE_CHAT;
    public static final LiveStreamClickType LIVE_CHAT_BETWEEN_ANCHORS;
    public static final LiveStreamClickType LIVE_COMMENT_NOTICE_FANS_INCREASE;
    public static final LiveStreamClickType LIVE_COMMON_NOTIFICATION;
    public static final LiveStreamClickType LIVE_DISTRICT_RANK;
    public static final LiveStreamClickType LIVE_FANS_GROUP;
    public static final LiveStreamClickType LIVE_GUEST_ACTIVITY;
    public static final LiveStreamClickType LIVE_GZONE_ACCOMPANY;
    public static final LiveStreamClickType LIVE_GZONE_KSHELL_RANK_USER;
    public static final LiveStreamClickType LIVE_GZONE_RANK_USER;
    public static final LiveStreamClickType LIVE_HOT_SPOT;
    public static final LiveStreamClickType LIVE_INTERACTIVE_GUIDE;
    public static final LiveStreamClickType LIVE_KWAI_VOICE;
    public static final LiveStreamClickType LIVE_LINE;
    public static final LiveStreamClickType LIVE_MULTI_PK;
    public static final LiveStreamClickType LIVE_PK_ANCHOR;
    public static final LiveStreamClickType LIVE_PK_HISTORY;
    public static final LiveStreamClickType LIVE_PK_PEER;
    public static final LiveStreamClickType LIVE_PK_TOP_SCORE_USER;
    public static final LiveStreamClickType LIVE_PROFILE_GUARD_USER;
    public static final LiveStreamClickType LIVE_WISH_LIST;
    public static final LiveStreamClickType LUCKY_STAR;
    public static final LiveStreamClickType MUSIC_STATION_MESSAGE;
    public static final LiveStreamClickType PK_FIRST_BLOOD;
    public static final LiveStreamClickType PK_INVITE_LIST;
    public static final LiveStreamClickType SANDEAPY;
    public static final LiveStreamClickType TOP_AUTHOR_HEAD_PERSONAL_CARD;
    public static final LiveStreamClickType UNKNOWN;
    public static final LiveStreamClickType VOICE_PARTY;
    public static final LiveStreamClickType VOICE_PARTY_TEAM_PK;
    public static final LiveStreamClickType VOICE_PARTY_THEATER;
    public static final LiveStreamClickType WATCHING_LIST;

    static {
       LiveStreamClickType liveStreamCl = new LiveStreamClickType("UNKNOWN", 0, 0);
       LiveStreamClickType.UNKNOWN = liveStreamCl;
       LiveStreamClickType liveStreamCl1 = new LiveStreamClickType("FEED_LIST", 1, 1);
       LiveStreamClickType.FEED_LIST = liveStreamCl1;
       LiveStreamClickType liveStreamCl2 = new LiveStreamClickType("GIFT_SLOT", 2, 2);
       LiveStreamClickType.GIFT_SLOT = liveStreamCl2;
       LiveStreamClickType liveStreamCl3 = new LiveStreamClickType("WATCHING_LIST", 3, 3);
       LiveStreamClickType.WATCHING_LIST = liveStreamCl3;
       LiveStreamClickType liveStreamCl4 = new LiveStreamClickType("LIVE_CHAT", 4, 4);
       LiveStreamClickType.LIVE_CHAT = liveStreamCl4;
       LiveStreamClickType liveStreamCl5 = new LiveStreamClickType("LIVE_PK_PEER", 5, 6);
       LiveStreamClickType.LIVE_PK_PEER = liveStreamCl5;
       LiveStreamClickType liveStreamCl6 = new LiveStreamClickType("LIVE_WISH_LIST", 6, 7);
       LiveStreamClickType.LIVE_WISH_LIST = liveStreamCl6;
       LiveStreamClickType liveStreamCl7 = new LiveStreamClickType("MUSIC_STATION_MESSAGE", 7, 8);
       LiveStreamClickType.MUSIC_STATION_MESSAGE = liveStreamCl7;
       LiveStreamClickType liveStreamCl8 = new LiveStreamClickType("LIVE_PK_ANCHOR", 8, 9);
       LiveStreamClickType.LIVE_PK_ANCHOR = liveStreamCl8;
       LiveStreamClickType liveStreamCl9 = new LiveStreamClickType("VOICE_PARTY", 9, 10);
       LiveStreamClickType.VOICE_PARTY = liveStreamCl9;
       LiveStreamClickType liveStreamCl10 = new LiveStreamClickType("LIVE_CHAT_BETWEEN_ANCHORS", 10, 11);
       LiveStreamClickType.LIVE_CHAT_BETWEEN_ANCHORS = liveStreamCl10;
       LiveStreamClickType liveStreamCl11 = new LiveStreamClickType("LIVE_PK_HISTORY", 11, 12);
       LiveStreamClickType.LIVE_PK_HISTORY = liveStreamCl11;
       LiveStreamClickType liveStreamCl12 = new LiveStreamClickType("LIVE_PK_TOP_SCORE_USER", 12, 13);
       LiveStreamClickType.LIVE_PK_TOP_SCORE_USER = liveStreamCl12;
       LiveStreamClickType liveStreamCl13 = liveStreamCl12;
       LiveStreamClickType liveStreamCl14 = new LiveStreamClickType("LIVE_COMMON_NOTIFICATION", 13, 14);
       LiveStreamClickType.LIVE_COMMON_NOTIFICATION = liveStreamCl14;
       LiveStreamClickType liveStreamCl15 = liveStreamCl14;
       LiveStreamClickType liveStreamCl16 = new LiveStreamClickType("LIVE_FANS_GROUP", 14, 15);
       LiveStreamClickType.LIVE_FANS_GROUP = liveStreamCl16;
       LiveStreamClickType liveStreamCl17 = liveStreamCl16;
       LiveStreamClickType liveStreamCl18 = new LiveStreamClickType("LIVE_DISTRICT_RANK", 15, 17);
       LiveStreamClickType.LIVE_DISTRICT_RANK = liveStreamCl18;
       LiveStreamClickType liveStreamCl19 = liveStreamCl18;
       liveStreamCl12 = new LiveStreamClickType("LIVE_KWAI_VOICE", 16, 18);
       LiveStreamClickType.LIVE_KWAI_VOICE = liveStreamCl12;
       LiveStreamClickType liveStreamCl20 = liveStreamCl12;
       liveStreamCl16 = new LiveStreamClickType("LIVE_AUDIENCE_FOLLOW_CARD_PREFETCH", 17, 21);
       LiveStreamClickType.LIVE_AUDIENCE_FOLLOW_CARD_PREFETCH = liveStreamCl16;
       LiveStreamClickType liveStreamCl21 = liveStreamCl16;
       liveStreamCl14 = new LiveStreamClickType("TOP_AUTHOR_HEAD_PERSONAL_CARD", 18, 22);
       LiveStreamClickType.TOP_AUTHOR_HEAD_PERSONAL_CARD = liveStreamCl14;
       LiveStreamClickType liveStreamCl22 = liveStreamCl14;
       liveStreamCl16 = new LiveStreamClickType("VOICE_PARTY_THEATER", 19, 23);
       LiveStreamClickType.VOICE_PARTY_THEATER = liveStreamCl16;
       LiveStreamClickType liveStreamCl23 = liveStreamCl16;
       liveStreamCl18 = new LiveStreamClickType("VOICE_PARTY_TEAM_PK", 20, 24);
       LiveStreamClickType.VOICE_PARTY_TEAM_PK = liveStreamCl18;
       LiveStreamClickType liveStreamCl24 = liveStreamCl18;
       liveStreamCl14 = new LiveStreamClickType("LUCKY_STAR", 21, 25);
       LiveStreamClickType.LUCKY_STAR = liveStreamCl14;
       LiveStreamClickType liveStreamCl25 = liveStreamCl14;
       liveStreamCl18 = new LiveStreamClickType("PK_FIRST_BLOOD", 22, 27);
       LiveStreamClickType.PK_FIRST_BLOOD = liveStreamCl18;
       LiveStreamClickType liveStreamCl26 = liveStreamCl18;
       liveStreamCl16 = new LiveStreamClickType("PK_INVITE_LIST", 23, 28);
       LiveStreamClickType.PK_INVITE_LIST = liveStreamCl16;
       LiveStreamClickType liveStreamCl27 = liveStreamCl16;
       liveStreamCl18 = new LiveStreamClickType("SANDEAPY", 24, 29);
       LiveStreamClickType.SANDEAPY = liveStreamCl18;
       LiveStreamClickType liveStreamCl28 = liveStreamCl18;
       liveStreamCl16 = new LiveStreamClickType("ANCHOR_FANS_LIST", 25, 30);
       LiveStreamClickType.ANCHOR_FANS_LIST = liveStreamCl16;
       LiveStreamClickType liveStreamCl29 = liveStreamCl16;
       liveStreamCl18 = new LiveStreamClickType("LIVE_PROFILE_GUARD_USER", 26, 31);
       LiveStreamClickType.LIVE_PROFILE_GUARD_USER = liveStreamCl18;
       LiveStreamClickType liveStreamCl30 = liveStreamCl18;
       liveStreamCl16 = new LiveStreamClickType("LIVE_GZONE_RANK_USER", 27, 32);
       LiveStreamClickType.LIVE_GZONE_RANK_USER = liveStreamCl16;
       LiveStreamClickType liveStreamCl31 = liveStreamCl16;
       liveStreamCl18 = new LiveStreamClickType("LIVE_GUEST_ACTIVITY", 28, 33);
       LiveStreamClickType.LIVE_GUEST_ACTIVITY = liveStreamCl18;
       LiveStreamClickType liveStreamCl32 = liveStreamCl18;
       liveStreamCl16 = new LiveStreamClickType("LIVE_COMMENT_NOTICE_FANS_INCREASE", 29, 34);
       LiveStreamClickType.LIVE_COMMENT_NOTICE_FANS_INCREASE = liveStreamCl16;
       LiveStreamClickType liveStreamCl33 = liveStreamCl16;
       liveStreamCl18 = new LiveStreamClickType("LIVE_LINE", 30, 35);
       LiveStreamClickType.LIVE_LINE = liveStreamCl18;
       LiveStreamClickType liveStreamCl34 = liveStreamCl18;
       liveStreamCl16 = new LiveStreamClickType("LIVE_GZONE_ACCOMPANY", 31, 36);
       LiveStreamClickType.LIVE_GZONE_ACCOMPANY = liveStreamCl16;
       LiveStreamClickType liveStreamCl35 = liveStreamCl16;
       liveStreamCl18 = new LiveStreamClickType("LIVE_AUCTION", 32, 37);
       LiveStreamClickType.LIVE_AUCTION = liveStreamCl18;
       LiveStreamClickType liveStreamCl36 = liveStreamCl18;
       liveStreamCl16 = new LiveStreamClickType("LIVE_GZONE_KSHELL_RANK_USER", 33, 38);
       LiveStreamClickType.LIVE_GZONE_KSHELL_RANK_USER = liveStreamCl16;
       LiveStreamClickType liveStreamCl37 = liveStreamCl16;
       liveStreamCl18 = new LiveStreamClickType("LIVE_INTERACTIVE_GUIDE", 34, 39);
       LiveStreamClickType.LIVE_INTERACTIVE_GUIDE = liveStreamCl18;
       LiveStreamClickType liveStreamCl38 = liveStreamCl18;
       liveStreamCl16 = new LiveStreamClickType("LIVE_MULTI_PK", 35, 40);
       LiveStreamClickType.LIVE_MULTI_PK = liveStreamCl16;
       LiveStreamClickType liveStreamCl39 = liveStreamCl16;
       liveStreamCl18 = new LiveStreamClickType("LIVE_HOT_SPOT", 36, 41);
       LiveStreamClickType.LIVE_HOT_SPOT = liveStreamCl18;
       LiveStreamClickType liveStreamCl40 = liveStreamCl18;
       liveStreamCl16 = new LiveStreamClickType("LITE_ANCHOR_INFO", 37, 42);
       LiveStreamClickType.LITE_ANCHOR_INFO = liveStreamCl16;
       LiveStreamClickType liveStreamCl41 = liveStreamCl16;
       liveStreamCl18 = new LiveStreamClickType("LITE_INTERACTIVE_MESSAGE", 38, 43);
       LiveStreamClickType.LITE_INTERACTIVE_MESSAGE = liveStreamCl18;
       LiveStreamClickType[] liveStreamCl42 = new LiveStreamClickType[39];
       liveStreamCl42[0] = liveStreamCl;
       liveStreamCl42[1] = liveStreamCl1;
       liveStreamCl42[2] = liveStreamCl2;
       liveStreamCl42[3] = liveStreamCl3;
       liveStreamCl42[4] = liveStreamCl4;
       liveStreamCl42[5] = liveStreamCl5;
       liveStreamCl42[6] = liveStreamCl6;
       liveStreamCl42[7] = liveStreamCl7;
       liveStreamCl42[8] = liveStreamCl8;
       liveStreamCl42[9] = liveStreamCl9;
       liveStreamCl42[10] = liveStreamCl10;
       liveStreamCl42[11] = liveStreamCl11;
       liveStreamCl42[12] = liveStreamCl13;
       liveStreamCl42[13] = liveStreamCl15;
       liveStreamCl42[14] = liveStreamCl17;
       liveStreamCl42[15] = liveStreamCl19;
       liveStreamCl42[16] = liveStreamCl20;
       liveStreamCl42[17] = liveStreamCl21;
       liveStreamCl42[18] = liveStreamCl22;
       liveStreamCl42[19] = liveStreamCl23;
       liveStreamCl42[20] = liveStreamCl24;
       liveStreamCl42[21] = liveStreamCl25;
       liveStreamCl42[22] = liveStreamCl26;
       liveStreamCl42[23] = liveStreamCl27;
       liveStreamCl42[24] = liveStreamCl28;
       liveStreamCl42[25] = liveStreamCl29;
       liveStreamCl42[26] = liveStreamCl30;
       liveStreamCl42[27] = liveStreamCl31;
       liveStreamCl42[28] = liveStreamCl32;
       liveStreamCl42[29] = liveStreamCl33;
       liveStreamCl42[30] = liveStreamCl34;
       liveStreamCl42[31] = liveStreamCl35;
       liveStreamCl42[32] = liveStreamCl36;
       liveStreamCl42[33] = liveStreamCl37;
       liveStreamCl42[34] = liveStreamCl38;
       liveStreamCl42[35] = liveStreamCl39;
       liveStreamCl42[36] = liveStreamCl40;
       liveStreamCl42[37] = liveStreamCl41;
       liveStreamCl42[38] = liveStreamCl18;
       LiveStreamClickType.$VALUES = liveStreamCl42;
    }
    public void LiveStreamClickType(String p0,int p1,int p2){
       super(p0, p1);
       this.value = p2;
    }
    public static LiveStreamClickType valueOf(String p0){
       Object obj = PatchProxy.applyOneRefs(p0, null, LiveStreamClickType.class, "2");
       if (obj != PatchProxyResult.class) {
          return obj;
       }
       return Enum.valueOf(LiveStreamClickType.class, p0);
    }
    public static LiveStreamClickType[] values(){
       Object obj = PatchProxy.apply(null, null, LiveStreamClickType.class, "1");
       if (obj != PatchProxyResult.class) {
          return obj;
       }
       return LiveStreamClickType.$VALUES.clone();
    }
    public int getValue(){
       return this.value;
    }
}
