package com.kuaishou.live.core.show.startup.LiveConfigStartupResponse;
import java.io.Serializable;
import java.lang.Object;
import com.kuaishou.live.core.show.startup.LiveConfigStartupResponse$LiveMerchantForbiddenConfig;
import com.kuaishou.live.core.show.startup.LiveConfigStartupResponse$LiveNebulaSendGiftTaskConfig;

public class LiveConfigStartupResponse implements Serializable	// class@00108b
{
    public LiveConfigStartupResponse$LiveQuizSf2023Config liveQuizSf2023Config;
    public Map liveSwitchesConfig;
    public long mAnchorBackgroundQueryLiveStatusIntervalMs;
    public long mAudienceAssociateRequestMaxDelayMillis;
    public LiveConfigStartupResponse$LiteComboCommentConfig mComboCommentConfig;
    public LiveConfigStartupResponse$LiveLiteCommonGuideConfig mCommonGuideConfig;
    public boolean mDisableAuthorWeeklyReportSubscribe;
    public boolean mDisableLiveAnchorFrameMetrics;
    public boolean mDisableLivePlayWithTextureView;
    public boolean mDisableLivePushFpsMonitor;
    public boolean mDisableRequestProfileFeedIgnorePublicPhotoCount;
    public boolean mDisableSettingReservationItem;
    public boolean mDisableShowWealthGrade;
    public boolean mDisableToAudienceGiftSlotDisplay;
    public boolean mDisableUseOldToken;
    public Map mEffectMap;
    public LiveConfigStartupResponse$LiveGiftPanelRechargeButtonConfig mGiftPanelRechargeButtonConfig;
    public LiveConfigStartupResponse$LiveLineChatConfig mLineLiveConfig;
    public LiteCommentAreaShowEmojiConfig mLiteCommentAreaShowEmojiConfig;
    public LiveConfigStartupResponse$LiteBottomBarConfig mLiteLiveBottomPanelConfig;
    public LiveConfigStartupResponse$LiveAgreementConfig mLiveAgreementConfig;
    public LiveAnchorBottomServerConfig mLiveAnchorBottomServerConfig;
    public long mLiveAnchorFrameMetricsIntervalMs;
    public LiveAnchorUvcConfig mLiveAnchorUVCConfig;
    public LiveConfigStartupResponse$LiveAudienceDelayInfosRequestDelayConfig mLiveAudienceDelayInfosRequestDelayConfig;
    public LiveConfigStartupResponse$LiveAudienceGiftConfig mLiveAudienceGiftConfig;
    public LiveAudienceShareHighlightConfig mLiveAudienceShareHighlightConfig;
    public LiveBackgroundMusicTipConfig mLiveBackgroundMusicTipConfig;
    public LiveBackgroundTtsConfig mLiveBackgroundTtsConfig;
    public LiveBeautifyConfig mLiveBeautifyConfig;
    public LiveChatBetweenAnchorsConfig mLiveChatBetweenAnchorsConfig;
    public LiveCheckStatusConfig mLiveCheckStatusConfig;
    public LiveConfigStartupResponse$LiveCny23GiftConfig mLiveCny23GiftConfig;
    public LiveConfigStartupResponse$LiveCollectionConfig mLiveCollectionConfig;
    public LiveCommentNoticeConfig mLiveCommentNoticeConfig;
    public LiveConfigStartupResponse$LiveCommentPlaceholderConfig mLiveCommentPlaceholderConfig;
    public LiveConfigStartupResponse$LiveCommonActivityWidgetConfig mLiveCommonActivityWidgetConfig;
    public LiveCommonShareConfig mLiveCommonShareConfig;
    public LiveConfigStartupResponse$LiveControlFileDownloadConfig mLiveControlFileDownloadConfig;
    public String mLiveDefaultBackgroundColor;
    public LiveConfigStartupResponse$LiveDisplayCountStyle mLiveDisplayCountStyle;
    public LiveConfigStartupResponse$LiveDisplayUserStateConfig mLiveDisplayUserStateConfig;
    public LiveConfigStartupResponse$LiveDistrictRankConfig mLiveDistrictRankConfig;
    public LiveDivertPushV2Config mLiveDivertPushV2Config;
    public LiveConfigStartupResponse$LiveEntryCoverGuideConfig mLiveEntryCoverGuideConfig;
    public LiveConfigStartupResponse$LiveEscrowNoticeConfig mLiveEscrowNoticeConfig;
    public LiveExperienceOptimizationConfig mLiveExperienceOptimizationConfig;
    public LiveConfigStartupResponse$LiveFansGroupConfig mLiveFansGroupConfig;
    public LiveConfigStartupResponse$LiveFloatingWindowConfig mLiveFloatingWindowConfig;
    public LiveConfigStartupResponse$LiveFollowGuideConfig mLiveFollowGuideConfig;
    public LiveConfigStartupResponse$LiveFollowUserPhotoFeedConfig mLiveFollowUserPhotoFeedConfig;
    public LiveConfigStartupResponse$LiveFriendFeedConfig mLiveFriendFeedConfig;
    public LiveConfigStartupResponse$LiveGRConfig mLiveGRConfig;
    public LiveConfigStartupResponse$LiveGiftPanelRefresh mLiveGiftPanelRefresh;
    public LiveConfigStartupResponse$LiveInteractiveUserTagConfig mLiveInteractiveUserTagConfig;
    public LiveConfigStartupResponse$LiveInteractiveWidgetConfig mLiveInteractiveWidgetConfig;
    public LiveConfigStartupResponse$LiveLiteRecoGuideConfig mLiveLiteRecoGuideConfig;
    public LiveLiteSideBarConfig mLiveLiteSideBarConfig;
    public LiveConfigStartupResponse$LiveLuckyStarConfig mLiveLuckyStarConfig;
    public LiveConfigStartupResponse$LiveMagicBoxConfig mLiveMagicBoxConfig;
    public LiveMakeupTipConfig mLiveMakeupTipConfig;
    public LiveConfigStartupResponse$LiveMerchantForbiddenConfig mLiveMerchantForbiddenConfig;
    public LiveConfigStartupResponse$LiveMmuConfig mLiveMmuConfig;
    public LiveMultiChatConfig mLiveMultiChat;
    public LiveMultiLineConfig mLiveMultiLineConfig;
    public LiveConfigStartupResponse$LiveMultiPkConfig mLiveMultiPkConfig;
    public LiveConfigStartupResponse$LivePkConfig mLivePkConfig;
    public LiveConfigStartupResponse$LivePreFollowConfig mLivePreFollowConfig;
    public LiveConfigStartupResponse$LivePreparePageConfig mLivePreparePageConfig;
    public LiveConfigStartupResponse$LiveProfileConfig mLiveProfileConfig;
    public LiveRaceConfig mLiveRaceConfig;
    public LiveConfigStartupResponse$LiveRecruitRepeatApplyConfig mLiveRecruitRepeatApplyConfig;
    public LiveConfigStartupResponse$LiveRedPackConfig mLiveRedPackConfig;
    public LiveConfigStartupResponse$LiveRevenueActivityConfig mLiveRevenueActivityConfig;
    public LiveConfigStartupResponse$LiveRevenueDeliveryConfig mLiveRevenueDeliveryConfig;
    public LiveConfigStartupResponse$LiveRobotConfig mLiveRobotConfig;
    public LiveConfigStartupResponse$LiveSquareConfig mLiveSquareConfig;
    public LiveConfigStartupResponse$LiveSquareFeedConfig mLiveSquareFeedConfig;
    public LiveConfigStartupResponse$LiveSquareSideBarNoticeConfig mLiveSquareSideBarNoticeConfig;
    public LiveConfigStartupResponse$LiveTopUserForbiddenInfo mLiveTopUserForbiddenInfo;
    public LiveConfigStartupResponse$LiveTopicConfig mLiveTopicConfig;
    public LiveConfigStartupResponse$LiveVipGradeConfig mLiveVipGradeConfig;
    public LiveConfigStartupResponse$LiveWishRoomConfig mLiveWishRoomConfig;
    public LiveConfigStartupResponse$LiveMaintenanceConfig mMaintenanceConfig;
    public NebulaLiveAudienceAdWidgetConfig mNebulaLiveAdConfig;
    public LiveConfigStartupResponse$PrepareConfigStrategy mPrepareConfigStrategy;
    public LiveConfigStartupResponse$LiveNebulaSendGiftTaskConfig mSendGiftTaskConfig;
    public LiveVoicePartyCommonConfig mVoicePartyConfig;
    public LiveConfigStartupResponse$LiveVoicePartyCrossRoomPkConfig mVoicePartyCrossRoomPkConfig;
    public LiveVoicePartyKtvCommonConfig mVoicePartyKtvConfig;
    public LiveVoicePartyTheaterCommonConfig mVoicePartyTheaterConfig;
    public static final long serialVersionUID = 0xde8d167feb91f491;

    public void LiveConfigStartupResponse(){
       super();
       this.mAnchorBackgroundQueryLiveStatusIntervalMs = 3000;
       this.mLiveAnchorFrameMetricsIntervalMs = 0x2710;
       this.mLiveMerchantForbiddenConfig = new LiveConfigStartupResponse$LiveMerchantForbiddenConfig();
       this.mSendGiftTaskConfig = new LiveConfigStartupResponse$LiveNebulaSendGiftTaskConfig();
    }
}
