package k4b.a;
import com.kwai.video.westeros.v2.faceless.FaceMagicController$FaceMagicLoadEffectFailedListener;
import java.lang.String;
import com.kwai.video.westeros.v2.faceless.FaceMagicController$FaceMagicMagicAlbumListener;
import android.view.MotionEvent;
import java.util.List;
import com.kwai.video.westeros.v2.faceless.FaceMagicController$FaceMagicUserInfoListener;
import com.kwai.video.westeros.models.AdjustIntensityConfig;
import com.kwai.video.westeros.models.TitleDatas;
import com.yxcorp.gifshow.model.MagicEmoji$MagicFace;
import com.kwai.video.westeros.v2.faceless.FaceMagicController$FaceMagicLockExposureListener;
import com.kwai.video.westeros.v2.faceless.FaceMagicController$FaceMagicPickFaceImageListener;
import com.kwai.video.westeros.models.UserInfo;
import com.kwai.video.westeros.models.EffectDescription;
import com.kwai.video.westeros.models.SafeUIArea;

public interface abstract a	// class@0032b7
{

    void A0(FaceMagicController$FaceMagicLoadEffectFailedListener p0);
    boolean B();
    void B0();
    boolean C0();
    boolean D0();
    int E0();
    String F0();
    boolean G0();
    void H0(String p0);
    void I(FaceMagicController$FaceMagicMagicAlbumListener p0);
    boolean I0();
    void J0(MotionEvent p0);
    boolean K0(String p0,int p1);
    void M(String p0);
    boolean N();
    void b(String p0);
    String c(boolean p0);
    void d(List p0);
    String e();
    void f(FaceMagicController$FaceMagicUserInfoListener p0);
    List g();
    AdjustIntensityConfig getAdjustIntensityConfig();
    String getLanguage();
    void h(int p0,String p1,String p2);
    TitleDatas i();
    boolean isFrontCamera();
    boolean isPreviewing();
    boolean isRecording();
    void j(MagicEmoji$MagicFace p0,String p1);
    void k(List p0);
    void l();
    boolean l0(String p0);
    List m();
    void n(FaceMagicController$FaceMagicLockExposureListener p0);
    void n0(FaceMagicController$FaceMagicLoadEffectFailedListener p0);
    void p(FaceMagicController$FaceMagicPickFaceImageListener p0);
    void q(String p0);
    boolean r();
    void s(UserInfo p0);
    boolean setAutoExposureLock(boolean p0);
    void switchCamera(boolean p0);
    boolean t();
    void u(String p0);
    void v(int p0);
    boolean w();
    EffectDescription w0();
    void x(SafeUIArea p0);
}
