package android.support.v4.media.session.b;
import android.os.IInterface;
import android.support.v4.media.MediaDescriptionCompat;
import java.lang.String;
import android.os.Bundle;
import java.util.List;
import android.app.PendingIntent;
import android.net.Uri;
import android.support.v4.media.RatingCompat;
import android.support.v4.media.session.MediaSessionCompat$ResultReceiverWrapper;
import android.support.v4.media.session.a;
import android.support.v4.media.session.PlaybackStateCompat;
import android.support.v4.media.session.ParcelableVolumeInfo;
import android.support.v4.media.MediaMetadataCompat;
import android.view.KeyEvent;
import java.lang.CharSequence;

public interface abstract b implements IInterface	// class@000407
{

    void D(MediaDescriptionCompat p0);
    void E(MediaDescriptionCompat p0);
    void E0(String p0,Bundle p1);
    boolean F0();
    List G();
    void G1(int p0,int p1,String p2);
    PendingIntent H0();
    void I(int p0);
    void J(Uri p0,Bundle p1);
    void L(String p0,Bundle p1);
    void N(String p0,Bundle p1);
    void P0(RatingCompat p0,Bundle p1);
    void T(int p0);
    void T0(String p0,Bundle p1,MediaSessionCompat$ResultReceiverWrapper p2);
    void V0(boolean p0);
    void Y0(a p0);
    boolean a0();
    void c1(a p0);
    void e();
    PlaybackStateCompat g();
    ParcelableVolumeInfo g0();
    Bundle getExtras();
    long getFlags();
    MediaMetadataCompat getMetadata();
    String getPackageName();
    String getTag();
    boolean j();
    void k1(String p0,Bundle p1);
    void l();
    boolean l0(KeyEvent p0);
    CharSequence m();
    void m0(MediaDescriptionCompat p0,int p1);
    void n(boolean p0);
    void n1(Uri p0,Bundle p1);
    void next();
    int p();
    void pause();
    void play();
    void previous();
    void q0(long p0);
    int r();
    void s(int p0);
    void seekTo(long p0);
    void stop();
    void t0(RatingCompat p0);
    void u0(int p0,int p1,String p2);
    void u1(String p0,Bundle p1);
    int w();
    void x1();
    void y0(float p0);
    Bundle z();
}
