package com.yxcorp.gifshow.w;
import java.lang.String;
import com.kuaishou.client.log.stat.packages.nano.ClientStat$ApiCostDetailStatEvent;
import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.content.Context;
import com.yxcorp.gifshow.w$b;
import android.app.Application;
import uv8.e1;

public interface abstract w	// class@001350
{

    void A(int p0);
    void B();
    void C();
    void D(long p0,long p1,long p2,long p3,String p4,long p5,double p6,String p7,String p8,String p9,String p10,boolean p11);
    void E(ClientStat$ApiCostDetailStatEvent p0);
    void F();
    void G();
    void H(String p0);
    String I();
    void J(Activity p0,Intent p1,Bundle p2);
    void K(String p0);
    void L(Context p0);
    void M(String p0);
    void N(long p0);
    void O();
    boolean P();
    void Q(long p0);
    void R();
    void S();
    void T();
    boolean U(String p0,long p1);
    void V(String p0,long p1);
    void W(w$b p0);
    void X(int p0);
    void Y();
    void Z(long p0);
    boolean a();
    void a0();
    int b();
    void b0(long p0);
    void c();
    void c0();
    void d(Activity p0);
    void d0();
    void e();
    void e0(Context p0,long p1);
    void f(int p0);
    void f0(int p0);
    void g();
    long g0();
    long getAppStartTime();
    long getHomeStartTime();
    int getLaunchSource();
    void h();
    void h0();
    void i(String p0,long p1);
    void i0();
    boolean isColdStart();
    void j(w$b p0);
    void j0();
    void k();
    void k0(String p0,long p1);
    void l(int p0);
    void l0(Application p0);
    void m(long p0);
    void m0();
    int n(Intent p0,Activity p1);
    void n0(Activity p0,Bundle p1);
    void o(String p0);
    void o0();
    void onActivityDestroyed(Activity p0);
    void onBackground();
    void p();
    void p0(int p0);
    void q(String p0);
    void q0();
    void r();
    void r0(boolean p0);
    void s(long p0,long p1);
    void s0();
    boolean t();
    void t0(Application p0);
    void u(String p0);
    boolean v(String p0);
    void w();
    void x(String p0);
    void y(boolean p0);
    e1 z();
}
