package kshark.lite.HprofRecordTag;
import java.lang.Enum;
import java.lang.String;
import kshark.lite.HprofRecordTag$a;
import nsd.u;
import java.util.EnumSet;
import java.lang.Object;
import kotlin.jvm.internal.a;
import java.lang.Class;

public final class HprofRecordTag extends Enum	// class@001ba1
{
    public final int tag;
    public static final HprofRecordTag[] $VALUES;
    public static final HprofRecordTag ALLOC_SITES;
    public static final HprofRecordTag CLASS_DUMP;
    public static final HprofRecordTag CONTROL_SETTINGS;
    public static final HprofRecordTag CPU_SAMPLES;
    public static final HprofRecordTag$a Companion;
    public static final HprofRecordTag END_THREAD;
    public static final HprofRecordTag HEAP_DUMP;
    public static final HprofRecordTag HEAP_DUMP_END;
    public static final HprofRecordTag HEAP_DUMP_INFO;
    public static final HprofRecordTag HEAP_DUMP_SEGMENT;
    public static final HprofRecordTag HEAP_SUMMARY;
    public static final HprofRecordTag INSTANCE_DUMP;
    public static final HprofRecordTag LOAD_CLASS;
    public static final HprofRecordTag OBJECT_ARRAY_DUMP;
    public static final HprofRecordTag PRIMITIVE_ARRAY_DUMP;
    public static final HprofRecordTag PRIMITIVE_ARRAY_NODATA;
    public static final HprofRecordTag ROOT_DEBUGGER;
    public static final HprofRecordTag ROOT_FINALIZING;
    public static final HprofRecordTag ROOT_INTERNED_STRING;
    public static final HprofRecordTag ROOT_JAVA_FRAME;
    public static final HprofRecordTag ROOT_JNI_GLOBAL;
    public static final HprofRecordTag ROOT_JNI_LOCAL;
    public static final HprofRecordTag ROOT_JNI_MONITOR;
    public static final HprofRecordTag ROOT_MONITOR_USED;
    public static final HprofRecordTag ROOT_NATIVE_STACK;
    public static final HprofRecordTag ROOT_REFERENCE_CLEANUP;
    public static final HprofRecordTag ROOT_STICKY_CLASS;
    public static final HprofRecordTag ROOT_THREAD_BLOCK;
    public static final HprofRecordTag ROOT_THREAD_OBJECT;
    public static final HprofRecordTag ROOT_UNKNOWN;
    public static final HprofRecordTag ROOT_UNREACHABLE;
    public static final HprofRecordTag ROOT_VM_INTERNAL;
    public static final HprofRecordTag STACK_FRAME;
    public static final HprofRecordTag STACK_TRACE;
    public static final HprofRecordTag START_THREAD;
    public static final HprofRecordTag STRING_IN_UTF8;
    public static final HprofRecordTag UNLOAD_CLASS;
    public static final EnumSet rootTags;

    static {
       HprofRecordTag[] hprofRecordT = new HprofRecordTag[36];
       HprofRecordTag hprofRecordT1 = new HprofRecordTag("STRING_IN_UTF8", 0, 1);
       HprofRecordTag.STRING_IN_UTF8 = hprofRecordT1;
       hprofRecordT[0] = hprofRecordT1;
       hprofRecordT1 = new HprofRecordTag("LOAD_CLASS", 1, 2);
       HprofRecordTag.LOAD_CLASS = hprofRecordT1;
       hprofRecordT[1] = hprofRecordT1;
       hprofRecordT1 = new HprofRecordTag("UNLOAD_CLASS", 2, 3);
       HprofRecordTag.UNLOAD_CLASS = hprofRecordT1;
       hprofRecordT[2] = hprofRecordT1;
       hprofRecordT1 = new HprofRecordTag("STACK_FRAME", 3, 4);
       HprofRecordTag.STACK_FRAME = hprofRecordT1;
       hprofRecordT[3] = hprofRecordT1;
       hprofRecordT1 = new HprofRecordTag("STACK_TRACE", 4, 5);
       HprofRecordTag.STACK_TRACE = hprofRecordT1;
       hprofRecordT[4] = hprofRecordT1;
       hprofRecordT1 = new HprofRecordTag("ALLOC_SITES", 5, 6);
       HprofRecordTag.ALLOC_SITES = hprofRecordT1;
       hprofRecordT[5] = hprofRecordT1;
       hprofRecordT1 = new HprofRecordTag("HEAP_SUMMARY", 6, 7);
       HprofRecordTag.HEAP_SUMMARY = hprofRecordT1;
       hprofRecordT[6] = hprofRecordT1;
       hprofRecordT1 = new HprofRecordTag("START_THREAD", 7, 10);
       HprofRecordTag.START_THREAD = hprofRecordT1;
       hprofRecordT[7] = hprofRecordT1;
       hprofRecordT1 = new HprofRecordTag("END_THREAD", 8, 11);
       HprofRecordTag.END_THREAD = hprofRecordT1;
       hprofRecordT[8] = hprofRecordT1;
       hprofRecordT1 = new HprofRecordTag("HEAP_DUMP", 9, 12);
       HprofRecordTag.HEAP_DUMP = hprofRecordT1;
       hprofRecordT[9] = hprofRecordT1;
       hprofRecordT1 = new HprofRecordTag("HEAP_DUMP_SEGMENT", 10, 28);
       HprofRecordTag.HEAP_DUMP_SEGMENT = hprofRecordT1;
       hprofRecordT[10] = hprofRecordT1;
       hprofRecordT1 = new HprofRecordTag("HEAP_DUMP_END", 11, 44);
       HprofRecordTag.HEAP_DUMP_END = hprofRecordT1;
       hprofRecordT[11] = hprofRecordT1;
       hprofRecordT1 = new HprofRecordTag("CPU_SAMPLES", 12, 13);
       HprofRecordTag.CPU_SAMPLES = hprofRecordT1;
       hprofRecordT[12] = hprofRecordT1;
       hprofRecordT1 = new HprofRecordTag("CONTROL_SETTINGS", 13, 14);
       HprofRecordTag.CONTROL_SETTINGS = hprofRecordT1;
       hprofRecordT[13] = hprofRecordT1;
       hprofRecordT1 = new HprofRecordTag("ROOT_UNKNOWN", 14, 255);
       HprofRecordTag.ROOT_UNKNOWN = hprofRecordT1;
       hprofRecordT[14] = hprofRecordT1;
       HprofRecordTag hprofRecordT2 = new HprofRecordTag("ROOT_JNI_GLOBAL", 15, 1);
       HprofRecordTag.ROOT_JNI_GLOBAL = hprofRecordT2;
       hprofRecordT[15] = hprofRecordT2;
       HprofRecordTag hprofRecordT3 = new HprofRecordTag("ROOT_JNI_LOCAL", 16, 2);
       HprofRecordTag.ROOT_JNI_LOCAL = hprofRecordT3;
       hprofRecordT[16] = hprofRecordT3;
       HprofRecordTag hprofRecordT4 = new HprofRecordTag("ROOT_JAVA_FRAME", 17, 3);
       HprofRecordTag.ROOT_JAVA_FRAME = hprofRecordT4;
       hprofRecordT[17] = hprofRecordT4;
       HprofRecordTag hprofRecordT5 = new HprofRecordTag("ROOT_NATIVE_STACK", 18, 4);
       HprofRecordTag.ROOT_NATIVE_STACK = hprofRecordT5;
       hprofRecordT[18] = hprofRecordT5;
       HprofRecordTag hprofRecordT6 = new HprofRecordTag("ROOT_STICKY_CLASS", 19, 5);
       HprofRecordTag.ROOT_STICKY_CLASS = hprofRecordT6;
       hprofRecordT[19] = hprofRecordT6;
       HprofRecordTag hprofRecordT7 = new HprofRecordTag("ROOT_THREAD_BLOCK", 20, 6);
       HprofRecordTag.ROOT_THREAD_BLOCK = hprofRecordT7;
       hprofRecordT[20] = hprofRecordT7;
       HprofRecordTag hprofRecordT8 = new HprofRecordTag("ROOT_MONITOR_USED", 21, 7);
       HprofRecordTag.ROOT_MONITOR_USED = hprofRecordT8;
       hprofRecordT[21] = hprofRecordT8;
       HprofRecordTag hprofRecordT9 = new HprofRecordTag("ROOT_THREAD_OBJECT", 22, 8);
       HprofRecordTag.ROOT_THREAD_OBJECT = hprofRecordT9;
       hprofRecordT[22] = hprofRecordT9;
       HprofRecordTag hprofRecordT10 = new HprofRecordTag("HEAP_DUMP_INFO", 23, 254);
       HprofRecordTag.HEAP_DUMP_INFO = hprofRecordT10;
       hprofRecordT[23] = hprofRecordT10;
       HprofRecordTag hprofRecordT11 = new HprofRecordTag("ROOT_INTERNED_STRING", 24, 137);
       HprofRecordTag.ROOT_INTERNED_STRING = hprofRecordT11;
       hprofRecordT[24] = hprofRecordT11;
       hprofRecordT10 = new HprofRecordTag("ROOT_FINALIZING", 25, 138);
       HprofRecordTag.ROOT_FINALIZING = hprofRecordT10;
       hprofRecordT[25] = hprofRecordT10;
       HprofRecordTag hprofRecordT12 = new HprofRecordTag("ROOT_DEBUGGER", 26, 139);
       HprofRecordTag.ROOT_DEBUGGER = hprofRecordT12;
       hprofRecordT[26] = hprofRecordT12;
       HprofRecordTag hprofRecordT13 = hprofRecordT1;
       HprofRecordTag hprofRecordT14 = new HprofRecordTag("ROOT_REFERENCE_CLEANUP", 27, 140);
       HprofRecordTag.ROOT_REFERENCE_CLEANUP = hprofRecordT14;
       hprofRecordT[27] = hprofRecordT14;
       HprofRecordTag hprofRecordT15 = hprofRecordT14;
       hprofRecordT1 = new HprofRecordTag("ROOT_VM_INTERNAL", 28, 141);
       HprofRecordTag.ROOT_VM_INTERNAL = hprofRecordT1;
       hprofRecordT[28] = hprofRecordT1;
       HprofRecordTag hprofRecordT16 = hprofRecordT1;
       hprofRecordT14 = new HprofRecordTag("ROOT_JNI_MONITOR", 29, 142);
       HprofRecordTag.ROOT_JNI_MONITOR = hprofRecordT14;
       hprofRecordT[29] = hprofRecordT14;
       HprofRecordTag hprofRecordT17 = hprofRecordT14;
       hprofRecordT1 = new HprofRecordTag("ROOT_UNREACHABLE", 30, 144);
       HprofRecordTag.ROOT_UNREACHABLE = hprofRecordT1;
       hprofRecordT[30] = hprofRecordT1;
       HprofRecordTag hprofRecordT18 = hprofRecordT1;
       hprofRecordT14 = new HprofRecordTag("PRIMITIVE_ARRAY_NODATA", 31, 195);
       HprofRecordTag.PRIMITIVE_ARRAY_NODATA = hprofRecordT14;
       hprofRecordT[31] = hprofRecordT14;
       hprofRecordT1 = new HprofRecordTag("CLASS_DUMP", 32, 32);
       HprofRecordTag.CLASS_DUMP = hprofRecordT1;
       hprofRecordT[32] = hprofRecordT1;
       hprofRecordT1 = new HprofRecordTag("INSTANCE_DUMP", 33, 33);
       HprofRecordTag.INSTANCE_DUMP = hprofRecordT1;
       hprofRecordT[33] = hprofRecordT1;
       hprofRecordT1 = new HprofRecordTag("OBJECT_ARRAY_DUMP", 34, 34);
       HprofRecordTag.OBJECT_ARRAY_DUMP = hprofRecordT1;
       hprofRecordT[34] = hprofRecordT1;
       hprofRecordT1 = new HprofRecordTag("PRIMITIVE_ARRAY_DUMP", 35, 35);
       HprofRecordTag.PRIMITIVE_ARRAY_DUMP = hprofRecordT1;
       hprofRecordT[35] = hprofRecordT1;
       HprofRecordTag.$VALUES = hprofRecordT;
       HprofRecordTag.Companion = new HprofRecordTag$a(null);
       hprofRecordT = new HprofRecordTag[15];
       hprofRecordT[0] = hprofRecordT2;
       hprofRecordT[1] = hprofRecordT3;
       hprofRecordT[2] = hprofRecordT4;
       hprofRecordT[3] = hprofRecordT5;
       hprofRecordT[4] = hprofRecordT6;
       hprofRecordT[5] = hprofRecordT7;
       hprofRecordT[6] = hprofRecordT8;
       hprofRecordT[7] = hprofRecordT9;
       hprofRecordT[8] = hprofRecordT11;
       hprofRecordT[9] = hprofRecordT10;
       hprofRecordT[10] = hprofRecordT12;
       hprofRecordT[11] = hprofRecordT15;
       hprofRecordT[12] = hprofRecordT16;
       hprofRecordT[13] = hprofRecordT17;
       hprofRecordT[14] = hprofRecordT18;
       EnumSet uEnumSet = EnumSet.of(hprofRecordT13, hprofRecordT);
       a.o(uEnumSet, "EnumSet.of\(\n      ROOT_U¡­   ROOT_UNREACHABLE\n    \)");
       HprofRecordTag.rootTags = uEnumSet;
    }
    public void HprofRecordTag(String p0,int p1,int p2){
       super(p0, p1);
       this.tag = p2;
    }
    public static HprofRecordTag valueOf(String p0){
       return Enum.valueOf(HprofRecordTag.class, p0);
    }
    public static HprofRecordTag[] values(){
       return HprofRecordTag.$VALUES.clone();
    }
    public final int getTag(){
       return this.tag;
    }
}
