package com.kwai.video.player.kwai_player.IBuildKwaiPlayer;
import com.kwai.video.player.kwai_player.AspectAwesomeCache;
import java.lang.Object;
import com.kwai.player.KwaiPlayerConfig;
import java.lang.String;
import android.content.Context;
import com.kwai.video.player.kwai_player.ProductContext;

public interface abstract IBuildKwaiPlayer	// class@000b2f
{

    void enableMultiSurface();
    void enablePipenodeV2(boolean p0);
    void enablePreDemux(int p0,long p1);
    AspectAwesomeCache getAspectAwesomeCache();
    boolean isLiveManifestNative();
    void setAbLoop(long p0,long p1,int p2,boolean p3);
    void setAudioLatency(int p0);
    void setAwesomeCacheCallback(Object p0);
    void setBufferSize(int p0);
    void setCdnStatEvent(Object p0);
    void setCodecFlag(int p0);
    void setConfig(KwaiPlayerConfig p0);
    void setConfigJson(String p0);
    void setConnectionTimeout(int p0);
    void setContext(Context p0);
    void setDisableHlsAbr(boolean p0);
    void setEnableAudioConvert(boolean p0);
    void setEnableAudioMix(boolean p0);
    void setEnableBulletScreenCache(boolean p0);
    void setEnableManifestRetry(boolean p0);
    void setEnablePlaylistCache(boolean p0);
    void setEnableSegmentCache(boolean p0);
    void setExtOption(int p0,int p1);
    void setExtOption(int p0,String p1);
    void setHevcCodecName(String p0);
    void setHlsEnableMediaCodecBytebuffer(boolean p0);
    void setHlsSegmentAlignThreshold(int p0);
    void setHttpResponseErrorCallback(Object p0);
    void setInteractiveMode(int p0);
    void setIsLive(boolean p0);
    void setIsVR(boolean p0);
    void setIsVodAdaptive(boolean p0);
    void setKwaivppFilters(int p0,String p1);
    void setKwaivppKswitchJson(int p0,String p1);
    void setLiveLowDelayConfigJson(String p0);
    void setOption(int p0,String p1,long p2);
    void setOption(int p0,String p1,String p2);
    void setProductContext(ProductContext p0);
    void setPropertyFloat(int p0,float p1);
    void setQy265Context(Context p0);
    void setReadTimeout(int p0);
    void setSegmentCacheCount(int p0);
    void setStartPlayBlockBufferMs(int p0,int p1);
    void setStartPlayBlockBufferStrategy(int p0);
    void setStereoType(int p0);
    void setUseSegmentPreload(boolean p0);
    void setupAspectKlv(boolean p0);
    void setupAspectKwaiVodAdaptive(boolean p0);
    void setupAspectLiveRealTimeReporter(boolean p0,KwaiPlayerConfig p1);
    void setupAspectNativeCache(boolean p0);
    void setupCacheSessionListener(Object p0);
    void setupGpuContext();
}
