package com.kwai.video.waynelive.mediaplayer.LivePlayerConfigProvider;
import java.lang.String;
import java.lang.Boolean;
import com.kwai.player.KwaiPlayerConfig$EnumBufferStrategy;
import com.kwai.video.waynelive.qosmoniter.QosMonitorConfig;
import ai7.d;

public interface abstract LivePlayerConfigProvider	// class@000e0a
{

    boolean enableAlignedPts();
    boolean enableAudioConvert();
    boolean enableStartPlayForLive();
    boolean enableWebRTCManifestForLive();
    String getAemonConfig();
    Boolean getBoolean(String p0,boolean p1);
    int getBufferTimeMaxSecForHlsLive();
    float getBufferTimeSizeMs();
    double getDeviceGeneralScore();
    boolean getEnableLiveAdaptiveAdditionalQos();
    boolean getEnableLiveAdaptiveQos();
    boolean getEnableLiveGuestRtQosLog();
    int getFFmpegConnectionTimeoutSec();
    int getHeightLimit264Hw();
    int getHeightLimit265Hw();
    int getHodorTaskRetryType();
    int getInt(String p0,int p1);
    String getKs265DecExtraParams();
    String getKwaiVPPKSwitch();
    int getKwaiplayerFunctionOption();
    String getLiveAdaptiveConfig();
    long getLiveAdaptiveQosDuration();
    int getLiveCacheConnectTimeoutMs();
    int getLiveCacheReadTimeoutMs();
    int getLiveCacheUpstreamType();
    boolean getLiveEnableBatteryInfo();
    long getLiveGuestRtQosInterval();
    String getLiveHevcCodecName();
    boolean getLiveHwSupportAudioOnlyMode();
    int getLiveMaxBufferTime();
    int getLiveMaxCnt();
    String getLiveNetDownConfig();
    int getLivePlayerBufferIncrementStep();
    int getLivePlayerBufferSmoothTime();
    KwaiPlayerConfig$EnumBufferStrategy getLivePlayerBufferStrategy();
    int getLivePlayerFirstBufferTime();
    int getLivePlayerMinBufferTime();
    String getLowDelayConfig();
    int getMediaCodecInvalidateVersion();
    String getMediaPlayerConfig();
    int getOverlayOutputPixelFormat();
    QosMonitorConfig getQosMonitorConfig();
    int getStartPlayMaxCostMsForLive();
    int getStartPlayThForLive();
    String getString(String p0,String p1);
    d getSwitchProvider();
    boolean getUseLive264HwForPcPush();
    boolean getUseLive265HwForPcPush();
    boolean getUseMediaCodecDummySurface();
    String getWebRTCConfigForGame();
    String getWebRTCConfigForLive();
    int getWidthLimit264Hw();
    int getWidthLimit265Hw();
    boolean isEnableAsyncStreamOpen();
    int isEnableHttpConnectTimeout();
    boolean isLiveAdaptiveEnableCache();
    boolean isLiveEnableAvSyncOpt();
    boolean isLiveEnableAvSyncOpt4();
    boolean isLiveEnableMultiAudioDetector();
    boolean isLiveH264SupportMediacodec();
    boolean isLiveH265SupportMediacodec();
    boolean isLiveNormalUseNativeCache();
    boolean shouldUseKLP();
}
