package com.kwai.feature.post.api.componet.prettify.beauty.BeautifyPart;
import java.lang.Enum;
import java.lang.String;
import java.lang.Object;
import java.lang.Class;
import com.kwai.robust.PatchProxy;
import com.kwai.robust.PatchProxyResult;

public final class BeautifyPart extends Enum	// class@0012cd
{
    public int mGroupId;
    public String mGroupName;
    public int mId;
    public int mSubFeature;
    public static final BeautifyPart[] $VALUES;
    public static final BeautifyPart APPLE_FACE;
    public static final BeautifyPart BEAUTIFY_LIPS;
    public static final BeautifyPart BRIGHT;
    public static final BeautifyPart CLARITY;
    public static final BeautifyPart CUT_FACE;
    public static final BeautifyPart DOUBLE_EYE_LID;
    public static final BeautifyPart DUDU_LIP;
    public static final BeautifyPart ENLARGE_EYE;
    public static final BeautifyPart EYEBROW_WIDTH;
    public static final BeautifyPart EYE_BAG_REMOVE;
    public static final BeautifyPart EYE_BRIGHTEN;
    public static final BeautifyPart EYE_CORNER;
    public static final BeautifyPart EYE_DISTANCE;
    public static final BeautifyPart EYE_HEIGHT;
    public static final BeautifyPart EYE_POSITION;
    public static final BeautifyPart EYE_WIDTH;
    public static final BeautifyPart FACE_SHORT;
    public static final BeautifyPart FORE_HEAD;
    public static final BeautifyPart HAIR_LINE;
    public static final BeautifyPart HIGH_SKULL;
    public static final BeautifyPart JAW;
    public static final BeautifyPart JAW_LINE;
    public static final BeautifyPart JAW_THIN;
    public static final BeautifyPart LONG_NOSE;
    public static final BeautifyPart LOWER_JAWBONE;
    public static final BeautifyPart MOUTH;
    public static final BeautifyPart MOUTH_HEIGHT;
    public static final BeautifyPart MOUTH_WIDTH;
    public static final BeautifyPart NARROW_FACE;
    public static final BeautifyPart NOSE_BRIDGE;
    public static final BeautifyPart NOSE_LENGTH;
    public static final BeautifyPart NOSE_SHADOW;
    public static final BeautifyPart PHILTRUM;
    public static final BeautifyPart PRESET;
    public static final BeautifyPart RUDDY;
    public static final BeautifyPart SHORT_FACE;
    public static final BeautifyPart SHRINK_PHILTRUM;
    public static final BeautifyPart SMALL_HEAD;
    public static final BeautifyPart SOFTEN;
    public static final BeautifyPart STEREO;
    public static final BeautifyPart TEETH_BRIGHTEN;
    public static final BeautifyPart TEMPLE;
    public static final BeautifyPart THIN_CHEEKBONE;
    public static final BeautifyPart THIN_FACE;
    public static final BeautifyPart THIN_LOWER_JAW;
    public static final BeautifyPart THIN_NOSE;
    public static final BeautifyPart TINY_FACE;
    public static final BeautifyPart WATER_SKIN;
    public static final BeautifyPart WO_CAN;
    public static final BeautifyPart WRINKLE_REMOVE;

    static {
       BeautifyPart uBeautifyPar = new BeautifyPart("PRESET", 0, -1, 0, 0, "");
       BeautifyPart.PRESET = v7;
       BeautifyPart uBeautifyPar1 = new BeautifyPart("BRIGHT", 1, 0, 2, 1, "皮肤");
       BeautifyPart.BRIGHT = uBeautifyPar;
       BeautifyPart uBeautifyPar2 = new BeautifyPart("SOFTEN", 2, 1, 1, 1, "皮肤");
       BeautifyPart.SOFTEN = v1;
       uBeautifyPar1 = new BeautifyPart("THIN_FACE", 3, 2, 3, 2, "脸型");
       BeautifyPart.THIN_FACE = v2;
       uBeautifyPar2 = new BeautifyPart("JAW", 4, 3, 4, 2, "脸型");
       BeautifyPart.JAW = v3;
       uBeautifyPar1 = new BeautifyPart("ENLARGE_EYE", 5, 4, 5, 3, "眼睛");
       BeautifyPart.ENLARGE_EYE = v4;
       uBeautifyPar2 = new BeautifyPart("THIN_NOSE", 6, 5, 20, 4, "鼻子");
       BeautifyPart.THIN_NOSE = v5;
       uBeautifyPar1 = new BeautifyPart("CUT_FACE", 7, 6, 12, 0, "");
       BeautifyPart.CUT_FACE = v6;
       uBeautifyPar2 = new BeautifyPart("TINY_FACE", 8, 7, 13, 0, "");
       BeautifyPart.TINY_FACE = uBeautifyPar1;
       BeautifyPart uBeautifyPar3 = new BeautifyPart("EYE_DISTANCE", 9, 8, 19, 0, "");
       BeautifyPart.EYE_DISTANCE = v16;
       BeautifyPart uBeautifyPar4 = new BeautifyPart("FORE_HEAD", 10, 9, 29, 0, "");
       BeautifyPart.FORE_HEAD = uBeautifyPar3;
       BeautifyPart uBeautifyPar5 = new BeautifyPart("WRINKLE_REMOVE", 11, 10, 6, 5, "嘴巴");
       BeautifyPart.WRINKLE_REMOVE = v10;
       uBeautifyPar4 = new BeautifyPart("EYE_BAG_REMOVE", 12, 11, 7, 3, "眼睛");
       BeautifyPart.EYE_BAG_REMOVE = v11;
       uBeautifyPar5 = new BeautifyPart("EYE_BRIGHTEN", 13, 12, 8, 3, "眼睛");
       BeautifyPart.EYE_BRIGHTEN = v12;
       uBeautifyPar4 = new BeautifyPart("TEETH_BRIGHTEN", 14, 13, 9, 5, "嘴巴");
       BeautifyPart.TEETH_BRIGHTEN = v13;
       uBeautifyPar5 = new BeautifyPart("BEAUTIFY_LIPS", 15, 14, 10, 0, "");
       BeautifyPart.BEAUTIFY_LIPS = v14;
       uBeautifyPar4 = new BeautifyPart("NOSE_SHADOW", 16, 15, 11, 0, "");
       BeautifyPart.NOSE_SHADOW = uBeautifyPar2;
       uBeautifyPar5 = new BeautifyPart("SHORT_FACE", 17, 16, 14, 2, "脸型");
       BeautifyPart.SHORT_FACE = uBeautifyPar4;
       BeautifyPart uBeautifyPar6 = new BeautifyPart("NARROW_FACE", 18, 17, 15, 2, "脸型");
       BeautifyPart.NARROW_FACE = v25;
       BeautifyPart uBeautifyPar7 = new BeautifyPart("THIN_LOWER_JAW", 19, 18, 16, 2, "脸型");
       BeautifyPart.THIN_LOWER_JAW = uBeautifyPar6;
       BeautifyPart uBeautifyPar8 = new BeautifyPart("LOWER_JAWBONE", 20, 19, 17, 2, "脸型");
       BeautifyPart.LOWER_JAWBONE = v19;
       uBeautifyPar7 = new BeautifyPart("THIN_CHEEKBONE", 21, 20, 18, 2, "脸型");
       BeautifyPart.THIN_CHEEKBONE = v20;
       uBeautifyPar8 = new BeautifyPart("LONG_NOSE", 22, 21, 21, 4, "鼻子");
       BeautifyPart.LONG_NOSE = v21;
       uBeautifyPar7 = new BeautifyPart("PHILTRUM", 23, 22, 22, 5, "嘴巴");
       BeautifyPart.PHILTRUM = v22;
       uBeautifyPar8 = new BeautifyPart("EYE_WIDTH", 24, 23, 23, 0, "");
       BeautifyPart.EYE_WIDTH = v23;
       uBeautifyPar7 = new BeautifyPart("EYE_HEIGHT", 25, 24, 24, 0, "");
       BeautifyPart.EYE_HEIGHT = uBeautifyPar5;
       uBeautifyPar8 = new BeautifyPart("EYE_CORNER", 26, 25, 25, 0, "");
       BeautifyPart.EYE_CORNER = uBeautifyPar7;
       BeautifyPart uBeautifyPar9 = new BeautifyPart("MOUTH", 27, 26, 26, 5, "嘴巴");
       BeautifyPart.MOUTH = v34;
       BeautifyPart uBeautifyPar10 = new BeautifyPart("MOUTH_WIDTH", 28, 27, 27, 0, "");
       BeautifyPart.MOUTH_WIDTH = uBeautifyPar9;
       BeautifyPart uBeautifyPar11 = new BeautifyPart("MOUTH_HEIGHT", 29, 28, 28, 0, "");
       BeautifyPart.MOUTH_HEIGHT = v28;
       uBeautifyPar10 = new BeautifyPart("CLARITY", 30, 29, 30, 1, "皮肤");
       BeautifyPart.CLARITY = v29;
       uBeautifyPar11 = new BeautifyPart("STEREO", 31, 30, 31, 1, "皮肤");
       BeautifyPart.STEREO = v30;
       uBeautifyPar10 = new BeautifyPart("HAIR_LINE", 32, 32, 32, 2, "脸型");
       BeautifyPart.HAIR_LINE = v31;
       uBeautifyPar11 = new BeautifyPart("NOSE_BRIDGE", 33, 33, 34, 4, "鼻子");
       BeautifyPart.NOSE_BRIDGE = v32;
       uBeautifyPar10 = new BeautifyPart("TEMPLE", 34, 34, 35, 2, "脸型");
       BeautifyPart.TEMPLE = uBeautifyPar8;
       uBeautifyPar11 = new BeautifyPart("EYEBROW_WIDTH", 35, 35, 36, 3, "眼睛");
       BeautifyPart.EYEBROW_WIDTH = uBeautifyPar10;
       BeautifyPart uBeautifyPar12 = new BeautifyPart("EYE_POSITION", 36, 36, 37, 3, "眼睛");
       BeautifyPart.EYE_POSITION = v43;
       BeautifyPart uBeautifyPar13 = new BeautifyPart("NOSE_LENGTH", 37, 37, 38, 4, "鼻子");
       BeautifyPart.NOSE_LENGTH = uBeautifyPar12;
       BeautifyPart uBeautifyPar14 = new BeautifyPart("JAW_THIN", 38, 38, 39, 2, "脸型");
       BeautifyPart.JAW_THIN = v37;
       uBeautifyPar13 = new BeautifyPart("FACE_SHORT", 39, 39, 40, 2, "脸型");
       BeautifyPart.FACE_SHORT = v38;
       uBeautifyPar14 = new BeautifyPart("SHRINK_PHILTRUM", 40, 40, 22, 0, "");
       BeautifyPart.SHRINK_PHILTRUM = v39;
       uBeautifyPar13 = new BeautifyPart("SMALL_HEAD", 41, 42, 44, 2, "脸型");
       BeautifyPart.SMALL_HEAD = v40;
       uBeautifyPar14 = new BeautifyPart("HIGH_SKULL", 42, 43, 45, 2, "脸型");
       BeautifyPart.HIGH_SKULL = v41;
       uBeautifyPar13 = new BeautifyPart("RUDDY", 43, 99, 43, 0, "皮肤");
       BeautifyPart.RUDDY = uBeautifyPar11;
       uBeautifyPar14 = new BeautifyPart("WO_CAN", 44, 111, 47, 5, "医美级");
       BeautifyPart.WO_CAN = uBeautifyPar13;
       BeautifyPart uBeautifyPar15 = new BeautifyPart("WATER_SKIN", 45, 112, 48, 5, "医美级");
       BeautifyPart.WATER_SKIN = v52;
       BeautifyPart uBeautifyPar16 = new BeautifyPart("JAW_LINE", 46, 113, 49, 5, "医美级");
       BeautifyPart.JAW_LINE = uBeautifyPar15;
       BeautifyPart uBeautifyPar17 = new BeautifyPart("DUDU_LIP", 47, 114, 50, 5, "医美级");
       BeautifyPart.DUDU_LIP = v46;
       uBeautifyPar16 = new BeautifyPart("APPLE_FACE", 48, 116, 51, 5, "医美级");
       BeautifyPart.APPLE_FACE = v47;
       uBeautifyPar17 = new BeautifyPart("DOUBLE_EYE_LID", 49, 117, 52, 5, "医美级");
       BeautifyPart.DOUBLE_EYE_LID = v48;
       BeautifyPart uBeautifyPar18 = uBeautifyPar2;
       BeautifyPart[] uBeautifyPar19 = new BeautifyPart[50];
       uBeautifyPar19[0] = v7;
       uBeautifyPar19[1] = uBeautifyPar;
       uBeautifyPar19[2] = v1;
       uBeautifyPar19[3] = v2;
       uBeautifyPar19[4] = v3;
       uBeautifyPar19[5] = v4;
       uBeautifyPar19[6] = v5;
       uBeautifyPar19[7] = v6;
       uBeautifyPar19[8] = uBeautifyPar1;
       uBeautifyPar19[9] = v16;
       uBeautifyPar19[10] = uBeautifyPar3;
       uBeautifyPar19[11] = v10;
       uBeautifyPar19[12] = v11;
       uBeautifyPar19[13] = v12;
       uBeautifyPar19[14] = v13;
       uBeautifyPar19[15] = v14;
       uBeautifyPar19[16] = uBeautifyPar18;
       uBeautifyPar19[17] = uBeautifyPar4;
       uBeautifyPar19[18] = v25;
       uBeautifyPar19[19] = uBeautifyPar6;
       uBeautifyPar19[20] = v19;
       uBeautifyPar19[21] = v20;
       uBeautifyPar19[22] = v21;
       uBeautifyPar19[23] = v22;
       uBeautifyPar19[24] = v23;
       uBeautifyPar19[25] = uBeautifyPar5;
       uBeautifyPar19[26] = uBeautifyPar7;
       uBeautifyPar19[27] = v34;
       uBeautifyPar19[28] = uBeautifyPar9;
       uBeautifyPar19[29] = v28;
       uBeautifyPar19[30] = v29;
       uBeautifyPar19[31] = v30;
       uBeautifyPar19[32] = v31;
       uBeautifyPar19[33] = v32;
       uBeautifyPar19[34] = uBeautifyPar8;
       uBeautifyPar19[35] = uBeautifyPar10;
       uBeautifyPar19[36] = v43;
       uBeautifyPar19[37] = uBeautifyPar12;
       uBeautifyPar19[38] = v37;
       uBeautifyPar19[39] = v38;
       uBeautifyPar19[40] = v39;
       uBeautifyPar19[41] = v40;
       uBeautifyPar19[42] = v41;
       uBeautifyPar19[43] = uBeautifyPar11;
       uBeautifyPar19[44] = uBeautifyPar13;
       uBeautifyPar19[45] = v52;
       uBeautifyPar19[46] = uBeautifyPar15;
       uBeautifyPar19[47] = v46;
       uBeautifyPar19[48] = v47;
       uBeautifyPar19[49] = v48;
       BeautifyPart.$VALUES = uBeautifyPar19;
    }
    public void BeautifyPart(String p0,int p1,int p2,int p3,int p4,String p5){
       super(p0, p1);
       this.mId = p2;
       this.mSubFeature = p3;
       this.mGroupId = p4;
       this.mGroupName = p5;
    }
    public static BeautifyPart valueOf(String p0){
       Object obj = PatchProxy.applyOneRefs(p0, null, BeautifyPart.class, "2");
       if (obj != PatchProxyResult.class) {
          return obj;
       }
       return Enum.valueOf(BeautifyPart.class, p0);
    }
    public static BeautifyPart[] values(){
       Object obj = PatchProxy.apply(null, null, BeautifyPart.class, "1");
       if (obj != PatchProxyResult.class) {
          return obj;
       }
       return BeautifyPart.$VALUES.clone();
    }
}
