package com.kuaishou.live.common.core.component.authority.LiveAnchorCommonAuthority;
import java.io.Serializable;
import java.lang.Object;
import com.kuaishou.live.core.show.fansgroup.LiveFansGroupInfo;
import com.kuaishou.live.ad.model.LiveAnchorBuyPushInfo;
import java.lang.Class;
import java.lang.String;
import com.kwai.robust.PatchProxy;
import com.kwai.robust.PatchProxyResult;

public class LiveAnchorCommonAuthority implements Serializable	// class@000f68
{
    public AnchorInfoAreaConfig mAnchorInfoAreaConfig;
    public LiveAnchorCommonAuthority$LiveAnonymousConfig mAnonymousLiveConfig;
    public boolean mAnonymousLiveSwitchStatus;
    public List mBannedFunctionList;
    public LiveDataAnalysisResponse$DataAnalysisInfo mDataAnalysisInfo;
    public LiveDefaultDecorationConfig mDefaultDecorationConfig;
    public boolean mDisableAuthorTaskExitRetain;
    public boolean mDisableCommonRedPacketNewStyle;
    public boolean mDisableFansGroupConditionRedPacket;
    public boolean mDisableGiftConditionRedPacket;
    public boolean mDisableLiveShopEntrance;
    public boolean mDisableMerchantForbiddenWhenChat;
    public boolean mDisableMerchantForbiddenWhenPk;
    public boolean mDisableOpenMultiPk;
    public boolean mDisablePkRecommendReport;
    public boolean mDisableShareConditionRedPacket;
    public boolean mDisableStartFormatPk;
    public boolean mDisableVoicePartyKtv;
    public boolean mDisableVoicePartyTeamPk;
    public boolean mDisableVoicePartyTheater;
    public boolean mEnable4GQos;
    public boolean mEnableAnonymousLive;
    public boolean mEnableApplyMusicStation;
    public boolean mEnableBackgroundMusicTip;
    public boolean mEnableChatBetweenAnchors;
    public boolean mEnableCommentAreaOptimization;
    public boolean mEnableCommentMergeGiftFeed;
    public boolean mEnableCommonRedPack;
    public boolean mEnableDefaultBeautyLevel;
    public boolean mEnableGiftSenderTop;
    public boolean mEnableKrnSendRedPacketPanel;
    public boolean mEnableLightBeauty;
    public boolean mEnableLiveAnnounce;
    public boolean mEnableLiveChatAudienceApply;
    public boolean mEnableLiveEscrow;
    public boolean mEnableLiveLuckyStar;
    public boolean mEnableLiveProfessionalMerchant;
    public boolean mEnableLiveSticker;
    public boolean mEnableLiveVipGrade;
    public boolean mEnableLiveVipGradeWatchingList;
    public boolean mEnableLiveVote;
    public boolean mEnableMerchantSticker;
    public boolean mEnableMultiChat;
    public boolean mEnableOneKsCoinDrawingGift;
    public boolean mEnableOpenAskAuthor;
    public boolean mEnablePkPanelTabSelectRemember;
    public boolean mEnablePrivateLive;
    public boolean mEnableRePush;
    public boolean mEnableRedPacketLiveCloseTip;
    public boolean mEnableSetVoicePartyAutoInvitation;
    public boolean mEnableShowAnchorLivePlaybackSwitch;
    public boolean mEnableShowLiveAgreement;
    public boolean mEnableShowLiveTopic;
    public boolean mEnableShowPkGiftEffectDuringPK;
    public boolean mEnableShowShareGuide;
    public boolean mEnableShowWeekRankSwitch;
    public boolean mEnableStartChatBetweenAnchorsGuide;
    public boolean mEnableStartPkGuide;
    public boolean mEnableStartPushFeedback;
    public boolean mEnableStartRobot;
    public boolean mEnableVoiceComment;
    public boolean mEnableVoiceParty;
    public boolean mEnableVoicePartyBombGame;
    public boolean mEnableVoicePartyCrossRoomPk;
    public boolean mEnableVoicePartyDefaultOpenVideo;
    public boolean mEnableVoicePartyNearbyEntranceOpen;
    public boolean mEnableVoicePartyOpenVideo;
    public boolean mEnableVoicePartySendGiftToGuestCommission;
    public boolean mEnableVoicePartyUploadBackground;
    public boolean mIsChatWithGuestDefaultOpen;
    public boolean mIsCityRankEnable;
    public boolean mIsHourlyQuarterRankEnable;
    public boolean mIsHourlyRankEntryEnable;
    public boolean mIsHourlyRankStrengthNoticeEnable;
    public boolean mIsNewHourlyRankResultEnable;
    public boolean mIsShowingConsumptionDataEnabled;
    public String mKrnSendRedPacketPanelRouter;
    public LiveAdminAssistantConfig mLiveAdminAssistantConfig;
    public LiveAnchorBlindDateConfig mLiveAnchorBlindDateConfig;
    public LiveAnchorBuyPushInfo mLiveAnchorBuyPushInfo;
    public LiveAnchorRecruitConfig mLiveAnchorRecruitConfig;
    public LiveAnchorStartPushEntryResponse mLiveAnchorStartPushEntryResponse;
    public LiveAnchorTaskResponse mLiveAnchorTaskResponse;
    public LiveAuthorBannerInfo mLiveAuthorBannerInfo;
    public LiveAnchorChatConfig mLiveChatConfig;
    public LiveFansGroupInfo mLiveFansGroupInfo;
    public LiveMmuHighlightConfig mLiveMmuHighLightConfig;
    public LivePaidShowInfo mLivePaidShowInfo;
    public LiveAnchorCommonAuthority$LiveWishListInfo mLiveWishListInfo;
    public LiveAnchorMagicFaceExpression mMagicFaceExpression;
    public LiveAnchorVoiceCommentConfig mVoiceCommentConfig;
    public String mVoiceCommentNotice;

    public void LiveAnchorCommonAuthority(){
       super();
       this.mEnableOpenAskAuthor = false;
       this.mEnablePrivateLive = false;
       this.mEnableLiveEscrow = false;
       this.mEnableVoicePartyOpenVideo = true;
       this.mEnableShowLiveAgreement = false;
       this.mEnableVoicePartyDefaultOpenVideo = false;
       this.mEnableVoicePartyUploadBackground = true;
       this.mEnableLiveVote = false;
       this.mDisableLiveShopEntrance = false;
       this.mLiveFansGroupInfo = new LiveFansGroupInfo();
       this.mLiveAnchorBuyPushInfo = new LiveAnchorBuyPushInfo();
       this.mEnableLiveProfessionalMerchant = false;
       this.mDisableMerchantForbiddenWhenPk = false;
       this.mDisableMerchantForbiddenWhenChat = false;
       this.mDisableStartFormatPk = true;
       this.mEnableLiveLuckyStar = false;
       this.mEnableCommentMergeGiftFeed = false;
       this.mEnableLiveSticker = false;
       this.mEnableMerchantSticker = false;
       this.mEnable4GQos = false;
       this.mEnableGiftSenderTop = false;
    }
    public static LiveAnchorCommonAuthority createDefault(){
       Object obj = PatchProxy.apply(null, null, LiveAnchorCommonAuthority.class, "1");
       if (obj != PatchProxyResult.class) {
          return obj;
       }
       return new LiveAnchorCommonAuthority();
    }
}
