package com.yxcorp.image.callercontext.UpBizFt;
import java.lang.Enum;
import java.lang.String;
import java.lang.Object;
import java.lang.Class;
import com.kwai.robust.PatchProxy;
import com.kwai.robust.PatchProxyResult;

public final class UpBizFt extends Enum	// class@001a02
{
    public static final UpBizFt[] $VALUES;
    public static final UpBizFt FT_Commercial;
    public static final UpBizFt FT_Corona;
    public static final UpBizFt FT_Design;
    public static final UpBizFt FT_Double;
    public static final UpBizFt FT_Feed;
    public static final UpBizFt FT_Game;
    public static final UpBizFt FT_Growth;
    public static final UpBizFt FT_KRN;
    public static final UpBizFt FT_Live;
    public static final UpBizFt FT_Local;
    public static final UpBizFt FT_MMU;
    public static final UpBizFt FT_Merchant;
    public static final UpBizFt FT_Mini;
    public static final UpBizFt FT_Multiple;
    public static final UpBizFt FT_Performance;
    public static final UpBizFt FT_Platform;
    public static final UpBizFt FT_Post;
    public static final UpBizFt FT_Resource;
    public static final UpBizFt FT_Search;
    public static final UpBizFt FT_SearchSchema;
    public static final UpBizFt FT_Security;
    public static final UpBizFt FT_Service;
    public static final UpBizFt FT_Social;
    public static final UpBizFt FT_Statistics;
    public static final UpBizFt FT_TK;
    public static final UpBizFt FT_Tuna;
    public static final UpBizFt FT_Unknown;
    public static final UpBizFt FT_Video;
    public static final UpBizFt FT_Weapon;
    public static final UpBizFt FT_X;
    public static final UpBizFt FT_YTech;
    public static final UpBizFt FT_Yoda;
    public static final UpBizFt Growthup2022;

    static {
       UpBizFt upBizFt = new UpBizFt("FT_Unknown", 0);
       UpBizFt.FT_Unknown = upBizFt;
       UpBizFt upBizFt1 = new UpBizFt("FT_Feed", 1);
       UpBizFt.FT_Feed = upBizFt1;
       UpBizFt upBizFt2 = new UpBizFt("FT_Social", 2);
       UpBizFt.FT_Social = upBizFt2;
       UpBizFt upBizFt3 = new UpBizFt("FT_Post", 3);
       UpBizFt.FT_Post = upBizFt3;
       UpBizFt upBizFt4 = new UpBizFt("FT_Search", 4);
       UpBizFt.FT_Search = upBizFt4;
       UpBizFt upBizFt5 = new UpBizFt("FT_Game", 5);
       UpBizFt.FT_Game = upBizFt5;
       UpBizFt upBizFt6 = new UpBizFt("FT_Growth", 6);
       UpBizFt.FT_Growth = upBizFt6;
       UpBizFt upBizFt7 = new UpBizFt("FT_Live", 7);
       UpBizFt.FT_Live = upBizFt7;
       UpBizFt upBizFt8 = new UpBizFt("FT_Commercial", 8);
       UpBizFt.FT_Commercial = upBizFt8;
       UpBizFt upBizFt9 = new UpBizFt("FT_Merchant", 9);
       UpBizFt.FT_Merchant = upBizFt9;
       UpBizFt upBizFt10 = new UpBizFt("FT_Tuna", 10);
       UpBizFt.FT_Tuna = upBizFt10;
       UpBizFt upBizFt11 = new UpBizFt("FT_Mini", 11);
       UpBizFt.FT_Mini = upBizFt11;
       UpBizFt upBizFt12 = new UpBizFt("FT_Video", 12);
       UpBizFt.FT_Video = upBizFt12;
       UpBizFt upBizFt13 = new UpBizFt("FT_YTech", 13);
       UpBizFt.FT_YTech = upBizFt13;
       UpBizFt upBizFt14 = upBizFt13;
       UpBizFt upBizFt15 = new UpBizFt("FT_MMU", 14);
       UpBizFt.FT_MMU = upBizFt15;
       UpBizFt upBizFt16 = upBizFt15;
       UpBizFt upBizFt17 = new UpBizFt("FT_Platform", 15);
       UpBizFt.FT_Platform = upBizFt17;
       UpBizFt upBizFt18 = upBizFt17;
       upBizFt13 = new UpBizFt("FT_KRN", 16);
       UpBizFt.FT_KRN = upBizFt13;
       UpBizFt upBizFt19 = upBizFt13;
       upBizFt15 = new UpBizFt("FT_TK", 17);
       UpBizFt.FT_TK = upBizFt15;
       UpBizFt upBizFt20 = upBizFt15;
       upBizFt17 = new UpBizFt("FT_Yoda", 18);
       UpBizFt.FT_Yoda = upBizFt17;
       UpBizFt upBizFt21 = upBizFt17;
       upBizFt13 = new UpBizFt("FT_Performance", 19);
       UpBizFt.FT_Performance = upBizFt13;
       UpBizFt upBizFt22 = upBizFt13;
       upBizFt15 = new UpBizFt("FT_Design", 20);
       UpBizFt.FT_Design = upBizFt15;
       UpBizFt upBizFt23 = upBizFt15;
       upBizFt17 = new UpBizFt("FT_Security", 21);
       UpBizFt.FT_Security = upBizFt17;
       UpBizFt upBizFt24 = upBizFt17;
       upBizFt13 = new UpBizFt("FT_Weapon", 22);
       UpBizFt.FT_Weapon = upBizFt13;
       UpBizFt upBizFt25 = upBizFt13;
       upBizFt17 = new UpBizFt("FT_Corona", 23);
       UpBizFt.FT_Corona = upBizFt17;
       UpBizFt upBizFt26 = upBizFt17;
       upBizFt15 = new UpBizFt("FT_Local", 24);
       UpBizFt.FT_Local = upBizFt15;
       UpBizFt upBizFt27 = upBizFt15;
       upBizFt17 = new UpBizFt("FT_Multiple", 25);
       UpBizFt.FT_Multiple = upBizFt17;
       UpBizFt upBizFt28 = upBizFt17;
       upBizFt15 = new UpBizFt("FT_Resource", 26);
       UpBizFt.FT_Resource = upBizFt15;
       UpBizFt upBizFt29 = upBizFt15;
       upBizFt17 = new UpBizFt("FT_Service", 27);
       UpBizFt.FT_Service = upBizFt17;
       UpBizFt upBizFt30 = upBizFt17;
       upBizFt15 = new UpBizFt("FT_Statistics", 28);
       UpBizFt.FT_Statistics = upBizFt15;
       UpBizFt upBizFt31 = upBizFt15;
       upBizFt17 = new UpBizFt("FT_X", 29);
       UpBizFt.FT_X = upBizFt17;
       UpBizFt upBizFt32 = upBizFt17;
       upBizFt15 = new UpBizFt("FT_SearchSchema", 30);
       UpBizFt.FT_SearchSchema = upBizFt15;
       UpBizFt upBizFt33 = upBizFt15;
       upBizFt17 = new UpBizFt("FT_Double", 31);
       UpBizFt.FT_Double = upBizFt17;
       UpBizFt upBizFt34 = upBizFt17;
       upBizFt15 = new UpBizFt("Growthup2022", 32);
       UpBizFt.Growthup2022 = upBizFt15;
       UpBizFt[] upBizFtArray = new UpBizFt[33];
       upBizFtArray[0] = upBizFt;
       upBizFtArray[1] = upBizFt1;
       upBizFtArray[2] = upBizFt2;
       upBizFtArray[3] = upBizFt3;
       upBizFtArray[4] = upBizFt4;
       upBizFtArray[5] = upBizFt5;
       upBizFtArray[6] = upBizFt6;
       upBizFtArray[7] = upBizFt7;
       upBizFtArray[8] = upBizFt8;
       upBizFtArray[9] = upBizFt9;
       upBizFtArray[10] = upBizFt10;
       upBizFtArray[11] = upBizFt11;
       upBizFtArray[12] = upBizFt12;
       upBizFtArray[13] = upBizFt14;
       upBizFtArray[14] = upBizFt16;
       upBizFtArray[15] = upBizFt18;
       upBizFtArray[16] = upBizFt19;
       upBizFtArray[17] = upBizFt20;
       upBizFtArray[18] = upBizFt21;
       upBizFtArray[19] = upBizFt22;
       upBizFtArray[20] = upBizFt23;
       upBizFtArray[21] = upBizFt24;
       upBizFtArray[22] = upBizFt25;
       upBizFtArray[23] = upBizFt26;
       upBizFtArray[24] = upBizFt27;
       upBizFtArray[25] = upBizFt28;
       upBizFtArray[26] = upBizFt29;
       upBizFtArray[27] = upBizFt30;
       upBizFtArray[28] = upBizFt31;
       upBizFtArray[29] = upBizFt32;
       upBizFtArray[30] = upBizFt33;
       upBizFtArray[31] = upBizFt34;
       upBizFtArray[32] = upBizFt15;
       UpBizFt.$VALUES = upBizFtArray;
    }
    public void UpBizFt(String p0,int p1){
       super(p0, p1);
    }
    public static UpBizFt valueOf(String p0){
       Object obj = PatchProxy.applyOneRefs(p0, null, UpBizFt.class, "2");
       if (obj != PatchProxyResult.class) {
          return obj;
       }
       return Enum.valueOf(UpBizFt.class, p0);
    }
    public static UpBizFt[] values(){
       Object obj = PatchProxy.apply(null, null, UpBizFt.class, "1");
       if (obj != PatchProxyResult.class) {
          return obj;
       }
       return UpBizFt.$VALUES.clone();
    }
}
