package ze.x;
import java.lang.Iterable;
import com.facebook.react.uimanager.j;
import ze.n;
import java.lang.Integer;
import java.lang.String;
import com.facebook.yoga.YogaDirection;
import com.facebook.react.bridge.JavaOnlyArray;
import com.facebook.react.uimanager.NativeKind;
import ze.y;
import ze.k0;
import lg.i;
import ze.z;
import ze.n0;
import com.facebook.yoga.YogaAlign;
import lg.a;
import com.facebook.yoga.YogaDisplay;
import com.facebook.yoga.YogaFlexDirection;
import com.facebook.yoga.YogaWrap;
import com.facebook.yoga.YogaJustify;
import java.lang.Object;
import lg.e;
import com.facebook.yoga.YogaOverflow;
import com.facebook.yoga.YogaPositionType;
import com.facebook.react.uimanager.ViewManager;
import android.view.View;

public interface abstract x	// class@003220
{

    void addChildAt(x p0,int p1);
    void addNativeChildAt(x p0,int p1);
    void calculateLayout();
    void calculateLayout(float p0,float p1);
    Iterable calculateLayoutOnChildren();
    void dirty();
    boolean dispatchUpdates(float p0,float p1,j p2,n p3);
    void dispose();
    int getAbsoluteX();
    int getAbsoluteY();
    x getChildAt(int p0);
    int getChildCount();
    Integer getHeightMeasureSpec();
    String getHierarchyInfo();
    int getLayoutCount();
    YogaDirection getLayoutDirection();
    float getLayoutHeight();
    x getLayoutParent();
    long getLayoutTime();
    float getLayoutWidth();
    float getLayoutX();
    float getLayoutY();
    JavaOnlyArray getMovedOutFixedChildTags();
    int getNativeChildCount();
    NativeKind getNativeKind();
    int getNativeOffsetForChild(x p0);
    x getNativeParent();
    y getNodeWrapper();
    k0 getNodeWrapperRegistry();
    int getOriginalParentTag();
    float getPadding(int p0);
    x getParent();
    int getReactTag();
    int getRootTag();
    int getScreenHeight();
    int getScreenWidth();
    int getScreenX();
    int getScreenY();
    boolean getSelfLayoutFlag();
    i getStyleHeight();
    i getStylePadding(int p0);
    i getStyleWidth();
    z getStylesMap();
    int getSyncRenderDataCellRootTag();
    int getSyncRenderDataTag();
    n0 getThemedContext();
    int getTotalNativeChildren();
    String getViewClass();
    Integer getWidthMeasureSpec();
    boolean hasNewLayout();
    boolean hasSetSnapShotShadowTree();
    boolean hasUnseenUpdates();
    boolean hasUpdates();
    boolean hoistNativeChildren();
    void increaseLayoutCount();
    int indexOf(x p0);
    int indexOfNativeChild(x p0);
    boolean isBindingVirtualNode();
    boolean isDataViewShadowNode();
    boolean isDescendantOf(x p0);
    boolean isDirty();
    boolean isFixedNode();
    boolean isLayoutOnly();
    boolean isMeasureDefined();
    boolean isSyncRenderDataRelativeNode();
    boolean isVirtual();
    boolean isVirtualAnchor();
    boolean isYogaLeafNode();
    void markLayoutSeen();
    void markUpdateSeen();
    void markUpdated();
    void onAfterUpdateTransaction();
    void onBeforeLayout(n p0);
    void onCollectExtraUpdates(j p0);
    void removeAllNativeChildren();
    void removeAndDisposeAllChildren();
    x removeChildAt(int p0);
    x removeNativeChildAt(int p0);
    void resetLayoutCount();
    void resetMovedOutFixedChildTags(JavaOnlyArray p0);
    void setAlignContent(YogaAlign p0);
    void setAlignItems(YogaAlign p0);
    void setAlignSelf(YogaAlign p0);
    void setBaselineFunction(a p0);
    void setBindingVirtualNode(boolean p0);
    void setBorder(int p0,float p1);
    void setDefaultPadding(int p0,float p1);
    void setDisplay(YogaDisplay p0);
    void setFlex(float p0);
    void setFlexBasis(float p0);
    void setFlexBasisAuto();
    void setFlexBasisPercent(float p0);
    void setFlexDirection(YogaFlexDirection p0);
    void setFlexGrow(float p0);
    void setFlexShrink(float p0);
    void setFlexWrap(YogaWrap p0);
    void setIsLayoutOnly(boolean p0);
    void setJustifyContent(YogaJustify p0);
    void setLayoutDirection(YogaDirection p0);
    void setLayoutParent(x p0);
    void setLayoutTime(long p0);
    void setLocalData(Object p0);
    void setMargin(int p0,float p1);
    void setMarginAuto(int p0);
    void setMarginPercent(int p0,float p1);
    void setMeasureFunction(e p0);
    void setMeasureSpecs(int p0,int p1);
    void setMovedOutFixedChildTag(int p0);
    void setOriginalParentTag(int p0);
    void setOverflow(YogaOverflow p0);
    void setPadding(int p0,float p1);
    void setPaddingPercent(int p0,float p1);
    void setPosition(int p0,float p1);
    void setPositionPercent(int p0,float p1);
    void setPositionType(YogaPositionType p0);
    void setReactTag(int p0);
    void setRootTag(int p0);
    void setShouldNotifyOnLayout(boolean p0);
    void setSnapShotShadowTree(y p0,k0 p1);
    void setSnapShotShadowTree(boolean p0);
    void setStyleAspectRatio(float p0);
    void setStyleHeight(float p0);
    void setStyleHeightAuto();
    void setStyleHeightPercent(float p0);
    void setStyleMaxHeight(float p0);
    void setStyleMaxHeightPercent(float p0);
    void setStyleMaxWidth(float p0);
    void setStyleMaxWidthPercent(float p0);
    void setStyleMinHeight(float p0);
    void setStyleMinHeightPercent(float p0);
    void setStyleMinWidth(float p0);
    void setStyleMinWidthPercent(float p0);
    void setStyleWidth(float p0);
    void setStyleWidthAuto();
    void setStyleWidthPercent(float p0);
    void setSyncRenderDataCellRootTag(int p0);
    void setSyncRenderDataTag(int p0);
    void setThemedContext(n0 p0);
    void setViewClassName(String p0);
    boolean shouldNotifyOnLayout();
    void synchronouslyUpdateLayoutInfoForKdsList(ViewManager p0,View p1);
    void updateProperties(z p0);
}
