package com.yxcorp.gifshow.v3.EditorItemFunc;
import ooc.g;
import java.lang.Enum;
import java.lang.String;
import java.lang.Object;
import java.lang.Class;
import com.kwai.robust.PatchProxy;
import com.kwai.robust.PatchProxyResult;

public final class EditorItemFunc extends Enum implements g	// class@000d1c
{
    public static final EditorItemFunc[] $VALUES;
    public static final EditorItemFunc AICUT;
    public static final EditorItemFunc ALBUM;
    public static final EditorItemFunc BACKGROUND;
    public static final EditorItemFunc BEAT_SYNC;
    public static final EditorItemFunc CLIP_V3;
    public static final EditorItemFunc COVER_PHOTO;
    public static final EditorItemFunc COVER_VIDEO;
    public static final EditorItemFunc CROP;
    public static final EditorItemFunc DECORATION;
    public static final EditorItemFunc DOODLE;
    public static final EditorItemFunc EFFECT;
    public static final EditorItemFunc EFFECT_V2;
    public static final EditorItemFunc ENHANCE_FILTER;
    public static final EditorItemFunc FILTER;
    public static final EditorItemFunc FINE_TUNING;
    public static final EditorItemFunc FRAME;
    public static final EditorItemFunc FRAME_V2;
    public static final EditorItemFunc KS_THEME;
    public static final EditorItemFunc KTV;
    public static final EditorItemFunc KTV_CLIP;
    public static final EditorItemFunc KTV_LYRIC;
    public static final EditorItemFunc KUAISHAN_SEGMENT;
    public static final EditorItemFunc MODEL_MAGIC_FINGER;
    public static final EditorItemFunc MORE;
    public static final EditorItemFunc MOSAIC;
    public static final EditorItemFunc MUSIC_V2;
    public static final EditorItemFunc PIC_TEMPLATE;
    public static final EditorItemFunc PIC_TEMPLATE_V2;
    public static final EditorItemFunc PRETTIFY;
    public static final EditorItemFunc PREVIEW;
    public static final EditorItemFunc RELAY_PHOTO;
    public static final EditorItemFunc RELAY_VIDEO;
    public static final EditorItemFunc REORDER;
    public static final EditorItemFunc SEGMENT;
    public static final EditorItemFunc STICKER_V2;
    public static final EditorItemFunc STYLE;
    public static final EditorItemFunc SUBTITLE_V2;
    public static final EditorItemFunc TEXT;
    public static final EditorItemFunc TEXT_V2;
    public static final EditorItemFunc TEXT_V3;
    public static final EditorItemFunc THEME;

    static {
       EditorItemFunc uEditorItemF = new EditorItemFunc("FILTER", 0);
       EditorItemFunc.FILTER = uEditorItemF;
       EditorItemFunc uEditorItemF1 = new EditorItemFunc("PRETTIFY", 1);
       EditorItemFunc.PRETTIFY = uEditorItemF1;
       EditorItemFunc uEditorItemF2 = new EditorItemFunc("COVER_VIDEO", 2);
       EditorItemFunc.COVER_VIDEO = uEditorItemF2;
       EditorItemFunc uEditorItemF3 = new EditorItemFunc("COVER_PHOTO", 3);
       EditorItemFunc.COVER_PHOTO = uEditorItemF3;
       EditorItemFunc uEditorItemF4 = new EditorItemFunc("MUSIC_V2", 4);
       EditorItemFunc.MUSIC_V2 = uEditorItemF4;
       EditorItemFunc uEditorItemF5 = new EditorItemFunc("EFFECT", 5);
       EditorItemFunc.EFFECT = uEditorItemF5;
       EditorItemFunc uEditorItemF6 = new EditorItemFunc("EFFECT_V2", 6);
       EditorItemFunc.EFFECT_V2 = uEditorItemF6;
       EditorItemFunc uEditorItemF7 = new EditorItemFunc("CLIP_V3", 7);
       EditorItemFunc.CLIP_V3 = uEditorItemF7;
       EditorItemFunc uEditorItemF8 = new EditorItemFunc("TEXT", 8);
       EditorItemFunc.TEXT = uEditorItemF8;
       EditorItemFunc uEditorItemF9 = new EditorItemFunc("TEXT_V2", 9);
       EditorItemFunc.TEXT_V2 = uEditorItemF9;
       EditorItemFunc uEditorItemF10 = new EditorItemFunc("TEXT_V3", 10);
       EditorItemFunc.TEXT_V3 = uEditorItemF10;
       EditorItemFunc uEditorItemF11 = new EditorItemFunc("DECORATION", 11);
       EditorItemFunc.DECORATION = uEditorItemF11;
       EditorItemFunc uEditorItemF12 = new EditorItemFunc("STICKER_V2", 12);
       EditorItemFunc.STICKER_V2 = uEditorItemF12;
       EditorItemFunc uEditorItemF13 = new EditorItemFunc("MODEL_MAGIC_FINGER", 13);
       EditorItemFunc.MODEL_MAGIC_FINGER = uEditorItemF13;
       EditorItemFunc uEditorItemF14 = uEditorItemF13;
       EditorItemFunc uEditorItemF15 = new EditorItemFunc("CROP", 14);
       EditorItemFunc.CROP = uEditorItemF15;
       EditorItemFunc uEditorItemF16 = uEditorItemF15;
       EditorItemFunc uEditorItemF17 = new EditorItemFunc("FINE_TUNING", 15);
       EditorItemFunc.FINE_TUNING = uEditorItemF17;
       EditorItemFunc uEditorItemF18 = uEditorItemF17;
       uEditorItemF13 = new EditorItemFunc("THEME", 16);
       EditorItemFunc.THEME = uEditorItemF13;
       EditorItemFunc uEditorItemF19 = uEditorItemF13;
       uEditorItemF15 = new EditorItemFunc("KS_THEME", 17);
       EditorItemFunc.KS_THEME = uEditorItemF15;
       EditorItemFunc uEditorItemF20 = uEditorItemF15;
       uEditorItemF17 = new EditorItemFunc("KTV", 18);
       EditorItemFunc.KTV = uEditorItemF17;
       EditorItemFunc uEditorItemF21 = uEditorItemF17;
       uEditorItemF13 = new EditorItemFunc("KTV_CLIP", 19);
       EditorItemFunc.KTV_CLIP = uEditorItemF13;
       EditorItemFunc uEditorItemF22 = uEditorItemF13;
       uEditorItemF15 = new EditorItemFunc("KTV_LYRIC", 20);
       EditorItemFunc.KTV_LYRIC = uEditorItemF15;
       EditorItemFunc uEditorItemF23 = uEditorItemF15;
       uEditorItemF17 = new EditorItemFunc("SEGMENT", 21);
       EditorItemFunc.SEGMENT = uEditorItemF17;
       EditorItemFunc uEditorItemF24 = uEditorItemF17;
       uEditorItemF13 = new EditorItemFunc("STYLE", 22);
       EditorItemFunc.STYLE = uEditorItemF13;
       EditorItemFunc uEditorItemF25 = uEditorItemF13;
       uEditorItemF17 = new EditorItemFunc("ENHANCE_FILTER", 23);
       EditorItemFunc.ENHANCE_FILTER = uEditorItemF17;
       EditorItemFunc uEditorItemF26 = uEditorItemF17;
       uEditorItemF15 = new EditorItemFunc("MORE", 24);
       EditorItemFunc.MORE = uEditorItemF15;
       EditorItemFunc uEditorItemF27 = uEditorItemF15;
       uEditorItemF17 = new EditorItemFunc("FRAME", 25);
       EditorItemFunc.FRAME = uEditorItemF17;
       EditorItemFunc uEditorItemF28 = uEditorItemF17;
       uEditorItemF15 = new EditorItemFunc("FRAME_V2", 26);
       EditorItemFunc.FRAME_V2 = uEditorItemF15;
       EditorItemFunc uEditorItemF29 = uEditorItemF15;
       uEditorItemF17 = new EditorItemFunc("REORDER", 27);
       EditorItemFunc.REORDER = uEditorItemF17;
       EditorItemFunc uEditorItemF30 = uEditorItemF17;
       uEditorItemF15 = new EditorItemFunc("DOODLE", 28);
       EditorItemFunc.DOODLE = uEditorItemF15;
       EditorItemFunc uEditorItemF31 = uEditorItemF15;
       uEditorItemF17 = new EditorItemFunc("MOSAIC", 29);
       EditorItemFunc.MOSAIC = uEditorItemF17;
       EditorItemFunc uEditorItemF32 = uEditorItemF17;
       uEditorItemF15 = new EditorItemFunc("AICUT", 30);
       EditorItemFunc.AICUT = uEditorItemF15;
       EditorItemFunc uEditorItemF33 = uEditorItemF15;
       uEditorItemF17 = new EditorItemFunc("PIC_TEMPLATE", 31);
       EditorItemFunc.PIC_TEMPLATE = uEditorItemF17;
       EditorItemFunc uEditorItemF34 = uEditorItemF17;
       uEditorItemF15 = new EditorItemFunc("PIC_TEMPLATE_V2", 32);
       EditorItemFunc.PIC_TEMPLATE_V2 = uEditorItemF15;
       EditorItemFunc uEditorItemF35 = uEditorItemF15;
       uEditorItemF17 = new EditorItemFunc("ALBUM", 33);
       EditorItemFunc.ALBUM = uEditorItemF17;
       EditorItemFunc uEditorItemF36 = uEditorItemF17;
       uEditorItemF15 = new EditorItemFunc("BACKGROUND", 34);
       EditorItemFunc.BACKGROUND = uEditorItemF15;
       EditorItemFunc uEditorItemF37 = uEditorItemF15;
       uEditorItemF17 = new EditorItemFunc("RELAY_VIDEO", 35);
       EditorItemFunc.RELAY_VIDEO = uEditorItemF17;
       EditorItemFunc uEditorItemF38 = uEditorItemF17;
       uEditorItemF15 = new EditorItemFunc("RELAY_PHOTO", 36);
       EditorItemFunc.RELAY_PHOTO = uEditorItemF15;
       EditorItemFunc uEditorItemF39 = uEditorItemF15;
       uEditorItemF17 = new EditorItemFunc("KUAISHAN_SEGMENT", 37);
       EditorItemFunc.KUAISHAN_SEGMENT = uEditorItemF17;
       EditorItemFunc uEditorItemF40 = uEditorItemF17;
       uEditorItemF15 = new EditorItemFunc("SUBTITLE_V2", 38);
       EditorItemFunc.SUBTITLE_V2 = uEditorItemF15;
       EditorItemFunc uEditorItemF41 = uEditorItemF15;
       uEditorItemF17 = new EditorItemFunc("PREVIEW", 39);
       EditorItemFunc.PREVIEW = uEditorItemF17;
       EditorItemFunc uEditorItemF42 = uEditorItemF17;
       uEditorItemF15 = new EditorItemFunc("BEAT_SYNC", 40);
       EditorItemFunc.BEAT_SYNC = uEditorItemF15;
       EditorItemFunc[] uEditorItemF43 = new EditorItemFunc[41];
       uEditorItemF43[0] = uEditorItemF;
       uEditorItemF43[1] = uEditorItemF1;
       uEditorItemF43[2] = uEditorItemF2;
       uEditorItemF43[3] = uEditorItemF3;
       uEditorItemF43[4] = uEditorItemF4;
       uEditorItemF43[5] = uEditorItemF5;
       uEditorItemF43[6] = uEditorItemF6;
       uEditorItemF43[7] = uEditorItemF7;
       uEditorItemF43[8] = uEditorItemF8;
       uEditorItemF43[9] = uEditorItemF9;
       uEditorItemF43[10] = uEditorItemF10;
       uEditorItemF43[11] = uEditorItemF11;
       uEditorItemF43[12] = uEditorItemF12;
       uEditorItemF43[13] = uEditorItemF14;
       uEditorItemF43[14] = uEditorItemF16;
       uEditorItemF43[15] = uEditorItemF18;
       uEditorItemF43[16] = uEditorItemF19;
       uEditorItemF43[17] = uEditorItemF20;
       uEditorItemF43[18] = uEditorItemF21;
       uEditorItemF43[19] = uEditorItemF22;
       uEditorItemF43[20] = uEditorItemF23;
       uEditorItemF43[21] = uEditorItemF24;
       uEditorItemF43[22] = uEditorItemF25;
       uEditorItemF43[23] = uEditorItemF26;
       uEditorItemF43[24] = uEditorItemF27;
       uEditorItemF43[25] = uEditorItemF28;
       uEditorItemF43[26] = uEditorItemF29;
       uEditorItemF43[27] = uEditorItemF30;
       uEditorItemF43[28] = uEditorItemF31;
       uEditorItemF43[29] = uEditorItemF32;
       uEditorItemF43[30] = uEditorItemF33;
       uEditorItemF43[31] = uEditorItemF34;
       uEditorItemF43[32] = uEditorItemF35;
       uEditorItemF43[33] = uEditorItemF36;
       uEditorItemF43[34] = uEditorItemF37;
       uEditorItemF43[35] = uEditorItemF38;
       uEditorItemF43[36] = uEditorItemF39;
       uEditorItemF43[37] = uEditorItemF40;
       uEditorItemF43[38] = uEditorItemF41;
       uEditorItemF43[39] = uEditorItemF42;
       uEditorItemF43[40] = uEditorItemF15;
       EditorItemFunc.$VALUES = uEditorItemF43;
    }
    public void EditorItemFunc(String p0,int p1){
       super(p0, p1);
    }
    public static EditorItemFunc valueOf(String p0){
       Object obj = PatchProxy.applyOneRefs(p0, null, EditorItemFunc.class, "2");
       if (obj != PatchProxyResult.class) {
          return obj;
       }
       return Enum.valueOf(EditorItemFunc.class, p0);
    }
    public static EditorItemFunc[] values(){
       Object obj = PatchProxy.apply(null, null, EditorItemFunc.class, "1");
       if (obj != PatchProxyResult.class) {
          return obj;
       }
       return EditorItemFunc.$VALUES.clone();
    }
}
