package f12.d;
import z41.b;
import e12.a;
import com.kwai.component.photo.detail.slide.DetailSlidePlayFragment;
import java.lang.Object;
import com.kuaishou.android.model.feed.LiveStreamFeed;
import com.yxcorp.gifshow.detail.slideplay.SlidePlayConfig;
import java.lang.String;
import com.kwai.feature.api.live.base.service.slideplay.LiveSlidePlayEnterParam$b;
import com.kwai.feature.api.live.service.basic.bizrelation.LiveBizParam;
import android.app.Activity;
import com.kuaishou.android.model.feed.LiveStreamFeedWrapper;
import com.kwai.feature.api.live.base.service.slideplay.LiveSlidePlayEnterParam;
import android.view.View;
import androidx.viewpager.widget.ViewPager$i;
import java.util.List;
import kp3.e;
import ge5.d;
import androidx.fragment.app.Fragment;

public interface abstract d implements b	// class@002832
{

    boolean A();
    void B(a p0);
    boolean C(DetailSlidePlayFragment p0);
    void D(boolean p0);
    boolean E();
    boolean F();
    void G(boolean p0);
    Object H();
    void I(int p0,boolean p1);
    int J(DetailSlidePlayFragment p0,LiveStreamFeed p1);
    boolean K();
    void L(SlidePlayConfig p0,String p1,int p2);
    void M(LiveStreamFeed p0);
    LiveStreamFeed N();
    void O(a p0);
    int P(LiveStreamFeed p0);
    LiveSlidePlayEnterParam Q(LiveSlidePlayEnterParam$b p0,LiveBizParam p1,Activity p2,LiveStreamFeedWrapper p3);
    View R(int p0);
    void S(Activity p0,View p1);
    int c();
    void d(boolean p0,int p1);
    int f();
    void g(ViewPager$i p0);
    int getCurrentPosition();
    List getDataList();
    void i(ViewPager$i p0);
    boolean isEmpty();
    e l();
    void m(int p0,List p1,String p2);
    d p();
    int q(int p0);
    void r(LiveStreamFeed p0);
    void s();
    Fragment t();
    void u(int p0,boolean p1);
    void v(List p0,LiveStreamFeed p1,String p2);
    void w(boolean p0);
    long x();
    int y(LiveStreamFeed p0);
    void z(Activity p0,View p1);
}
