package com.kuaishou.live.bridge.LiveJsKwaiLiveCommands;
import o63.k;
import java.lang.Enum;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$1;
import o63.r;
import java.lang.String;
import msd.a;
import nsd.u;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$2;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$3;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$4;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$5;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$6;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$7;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$8;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$9;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$10;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$11;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$12;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$13;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$14;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$15;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$16;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$17;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$18;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$19;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$20;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$21;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$22;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$23;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$24;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$25;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$26;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$27;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$28;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$29;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$30;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$31;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$32;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$33;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$34;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$35;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$36;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$37;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$38;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$39;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$40;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$41;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$42;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$43;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$44;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$45;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$46;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$47;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$48;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$49;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$50;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$51;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$52;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$53;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$54;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$55;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$56;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$57;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$58;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$59;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$60;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$61;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$62;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$63;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$64;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$65;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$66;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$67;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$68;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$69;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$70;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$71;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$72;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$73;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$74;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$75;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$76;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$77;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$78;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$79;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$80;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$81;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$82;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$83;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$84;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$85;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$86;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$87;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$88;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$89;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$90;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$91;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$92;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$93;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$94;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$95;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$96;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$97;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$98;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$99;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$100;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$101;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$102;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$103;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$104;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$105;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$106;
import com.kuaishou.live.bridge.LiveJsKwaiLiveCommands$a;
import trd.s0;
import usd.q;
import java.util.LinkedHashMap;
import java.lang.Object;
import java.util.Map;
import java.util.Collection;
import com.kwai.robust.PatchProxyResult;
import java.lang.Class;
import com.kwai.robust.PatchProxy;
import java.util.Objects;
import kotlin.jvm.internal.a;

public final class LiveJsKwaiLiveCommands extends Enum implements k	// class@000dda
{
    public final String commandName;
    public final a commandProvider;
    public final String nameSpace;
    public final r supportedScene;
    public static final LiveJsKwaiLiveCommands[] $VALUES;
    public static final LiveJsKwaiLiveCommands AcceptChatInvitation;
    public static final LiveJsKwaiLiveCommands AcceptLineInvitation;
    public static final LiveJsKwaiLiveCommands AcceptMultiLineInvitation;
    public static final LiveJsKwaiLiveCommands AcceptPKInvitation;
    public static final LiveJsKwaiLiveCommands AcceptPkOneMoreGame;
    public static final LiveJsKwaiLiveCommands AddBarrage;
    public static final LiveJsKwaiLiveCommands AppendNormalLEEE;
    public static final LiveJsKwaiLiveCommands ApplyMagicFace;
    public static final LiveJsKwaiLiveCommands BatchFetchResourcePath;
    public static final LiveJsKwaiLiveCommands BatchQueryFollowStatus;
    public static final LiveJsKwaiLiveCommands CancelApplyChat;
    public static final LiveJsKwaiLiveCommands ClosePage;
    public static final LiveJsKwaiLiveCommands$a Companion;
    public static final LiveJsKwaiLiveCommands DispatchLiveRouter;
    public static final LiveJsKwaiLiveCommands EditAndGetLineUserTag;
    public static final LiveJsKwaiLiveCommands EditChatGuestLabel;
    public static final LiveJsKwaiLiveCommands EnableDismissTouchOutside;
    public static final LiveJsKwaiLiveCommands EndMultiLineChatMode;
    public static final LiveJsKwaiLiveCommands EndPkInAdvance;
    public static final LiveJsKwaiLiveCommands FetchMaterialResourceImgPath;
    public static final LiveJsKwaiLiveCommands FlowDiversionPayDescriptionConfirmInvite;
    public static final LiveJsKwaiLiveCommands FollowUser;
    public static final LiveJsKwaiLiveCommands GetCurrentMagicFaceId;
    public static final LiveJsKwaiLiveCommands GetDevicePerformanceScore;
    public static final LiveJsKwaiLiveCommands GetInteractChatMediaInfo;
    public static final LiveJsKwaiLiveCommands GetInteractMagicFaceInfo;
    public static final LiveJsKwaiLiveCommands GetInteractRoomInfo;
    public static final LiveJsKwaiLiveCommands GetLiveRoomInfo;
    public static final LiveJsKwaiLiveCommands GetLiveSceneInfo;
    public static final LiveJsKwaiLiveCommands GetMagicFacePath;
    public static final LiveJsKwaiLiveCommands GetMagicFaceSDKInfo;
    public static final LiveJsKwaiLiveCommands GetMaterialResourcePath;
    public static final LiveJsKwaiLiveCommands GetServerTime;
    public static final LiveJsKwaiLiveCommands InjectCache;
    public static final LiveJsKwaiLiveCommands InvitePkOneMoreGame;
    public static final LiveJsKwaiLiveCommands IsFirstInstall;
    public static final LiveJsKwaiLiveCommands JoinFansGroup;
    public static final LiveJsKwaiLiveCommands LeaveLiveChat;
    public static final LiveJsKwaiLiveCommands LiveAbility;
    public static final LiveJsKwaiLiveCommands LiveEncourageTreasureShowResultDialog;
    public static final LiveJsKwaiLiveCommands LiveEncourageTreasureTimerQuery;
    public static final LiveJsKwaiLiveCommands LiveGzoneChangeWebViewDisplayMode;
    public static final LiveJsKwaiLiveCommands LiveGzoneGetWebViewDisplayMode;
    public static final LiveJsKwaiLiveCommands LiveJsCmdInviteMultiPkOneMoreGame;
    public static final LiveJsKwaiLiveCommands LiveMerchantBridgeRouter;
    public static final LiveJsKwaiLiveCommands LiveMerchantPendant;
    public static final LiveJsKwaiLiveCommands LiveRouter;
    public static final LiveJsKwaiLiveCommands LiveWatchTimerPause;
    public static final LiveJsKwaiLiveCommands LiveWatchTimerQuery;
    public static final LiveJsKwaiLiveCommands LiveWatchTimerStart;
    public static final LiveJsKwaiLiveCommands LiveWatchTimerStop;
    public static final LiveJsKwaiLiveCommands LogLivePageEnter;
    public static final LiveJsKwaiLiveCommands Logger;
    public static final LiveJsKwaiLiveCommands MockEffectInfo;
    public static final LiveJsKwaiLiveCommands MockSelfSendGiftEffect;
    public static final LiveJsKwaiLiveCommands MultiChatSwitchStatusChanged;
    public static final LiveJsKwaiLiveCommands NavigateToH5;
    public static final LiveJsKwaiLiveCommands NotifyAddFansPriceChanged;
    public static final LiveJsKwaiLiveCommands NotifyFlowDiversionSettingCompletion;
    public static final LiveJsKwaiLiveCommands NotifyMultiChatLayoutChanged;
    public static final LiveJsKwaiLiveCommands NotifySendGiftSuccess;
    public static final LiveJsKwaiLiveCommands NotifySendGiftSuccessV2;
    public static final LiveJsKwaiLiveCommands OpenCart;
    public static final LiveJsKwaiLiveCommands OpenCustomH5;
    public static final LiveJsKwaiLiveCommands OpenLiveGiftPanel;
    public static final LiveJsKwaiLiveCommands OpenLiveGzoneFloatWindow;
    public static final LiveJsKwaiLiveCommands OpenLiveProfileCard;
    public static final LiveJsKwaiLiveCommands OpenNonImmersiveH5;
    public static final LiveJsKwaiLiveCommands PopPage;
    public static final LiveJsKwaiLiveCommands ProvideCache;
    public static final LiveJsKwaiLiveCommands ProvidePhoneInfo;
    public static final LiveJsKwaiLiveCommands ProvideTreasureBoxParams;
    public static final LiveJsKwaiLiveCommands QueryFollowStatus;
    public static final LiveJsKwaiLiveCommands QueryUserChatInviteStatus;
    public static final LiveJsKwaiLiveCommands QueryWalletBalance;
    public static final LiveJsKwaiLiveCommands QuitLive;
    public static final LiveJsKwaiLiveCommands RecruitNotifyJobApplySuccess;
    public static final LiveJsKwaiLiveCommands RejectLineInvitation;
    public static final LiveJsKwaiLiveCommands RejectMultiLineInvitation;
    public static final LiveJsKwaiLiveCommands RejectPKInvitation;
    public static final LiveJsKwaiLiveCommands RejectPkOneMoreGame;
    public static final LiveJsKwaiLiveCommands RemoveMagicFace;
    public static final LiveJsKwaiLiveCommands RemoveRedPacket;
    public static final LiveJsKwaiLiveCommands ReportAdLog;
    public static final LiveJsKwaiLiveCommands SendGifStToGuest;
    public static final LiveJsKwaiLiveCommands SendGiftToAnchor;
    public static final LiveJsKwaiLiveCommands SendGiftToAnchorV2;
    public static final LiveJsKwaiLiveCommands SendNormalLEEE;
    public static final LiveJsKwaiLiveCommands SendTextComment;
    public static final LiveJsKwaiLiveCommands ShowApplyChatDialog;
    public static final LiveJsKwaiLiveCommands ShowApplyChatWaitingDialog;
    public static final LiveJsKwaiLiveCommands ShowMultiLineClosePanel;
    public static final LiveJsKwaiLiveCommands ShowMultiLinePuzzleAnim;
    public static final LiveJsKwaiLiveCommands StartChatInvitation;
    public static final LiveJsKwaiLiveCommands StartMultiPK;
    public static final LiveJsKwaiLiveCommands StartPKInvitation;
    public static final LiveJsKwaiLiveCommands StartSpecificLineMatch;
    public static final LiveJsKwaiLiveCommands SuspendLineInvitation;
    public static final LiveJsKwaiLiveCommands SwitchBlindDateEntranceState;
    public static final LiveJsKwaiLiveCommands SwitchEffectRenderBannedBizBit;
    public static final LiveJsKwaiLiveCommands SwitchLineChatMode;
    public static final LiveJsKwaiLiveCommands SwitchLiveHouseBlindDateState;
    public static final LiveJsKwaiLiveCommands SwitchMultiInteractBiz;
    public static final LiveJsKwaiLiveCommands SyncWealthGradeStatus;
    public static final LiveJsKwaiLiveCommands Toast;
    public static final LiveJsKwaiLiveCommands UpdateBarrage;
    public static final LiveJsKwaiLiveCommands UpdateMuteState;
    public static final Collection allCommandIds;
    public static final Map mapping;

    static {
       LiveJsKwaiLiveCommands[] liveJsKwaiLi = new LiveJsKwaiLiveCommands[106];
       r d = r.d;
       r e = r.e;
       LiveJsKwaiLiveCommands.GetLiveRoomInfo = v10;
       int i = 0;
       liveJsKwaiLi[i] = v10;
       r c = r.c;
       LiveJsKwaiLiveCommands liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("DispatchLiveRouter", 1, "dispatchLiveRouter", LiveJsKwaiLiveCommands$2.INSTANCE, d.b(e).b(c), null, 8, null);
       LiveJsKwaiLiveCommands.DispatchLiveRouter = v2;
       liveJsKwaiLi[1] = v2;
       liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("NotifySendGiftSuccess", 2, "notifySendGiftSuccess", LiveJsKwaiLiveCommands$3.INSTANCE, d.b(e), null, 8, null);
       LiveJsKwaiLiveCommands.NotifySendGiftSuccess = v2;
       liveJsKwaiLi[2] = v2;
       liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("NotifySendGiftSuccessV2", 3, "notifySendGiftSuccessV2", LiveJsKwaiLiveCommands$4.INSTANCE, d.b(e), null, 8, null);
       LiveJsKwaiLiveCommands.NotifySendGiftSuccessV2 = v2;
       liveJsKwaiLi[3] = v2;
       liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("InjectCache", 4, "injectCache", LiveJsKwaiLiveCommands$5.INSTANCE, d.b(e).b(c), null, 8, null);
       LiveJsKwaiLiveCommands.InjectCache = v2;
       liveJsKwaiLi[4] = v2;
       liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("ProvideCache", 5, "provideCache", LiveJsKwaiLiveCommands$6.INSTANCE, d.b(e).b(c), null, 8, null);
       LiveJsKwaiLiveCommands.ProvideCache = v2;
       liveJsKwaiLi[5] = v2;
       liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("ProvideTreasureBoxParams", 6, "provideTreasureBoxParams", LiveJsKwaiLiveCommands$7.INSTANCE, d.b(e), null, 8, null);
       LiveJsKwaiLiveCommands.ProvideTreasureBoxParams = v2;
       liveJsKwaiLi[6] = v2;
       liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("OpenLiveProfileCard", 7, "openLiveProfileCard", LiveJsKwaiLiveCommands$8.INSTANCE, d.b(e), null, 8, null);
       LiveJsKwaiLiveCommands.OpenLiveProfileCard = v2;
       liveJsKwaiLi[7] = v2;
       liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("OpenCustomH5", 8, "openCustomH5", LiveJsKwaiLiveCommands$9.INSTANCE, d.b(e), null, 8, null);
       LiveJsKwaiLiveCommands.OpenCustomH5 = v2;
       liveJsKwaiLi[8] = v2;
       liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("OpenNonImmersiveH5", 9, "openNonImmersiveH5", LiveJsKwaiLiveCommands$10.INSTANCE, d.b(e), null, 8, null);
       LiveJsKwaiLiveCommands.OpenNonImmersiveH5 = v2;
       liveJsKwaiLi[9] = v2;
       r or = e;
       r or1 = d;
       r or2 = or1;
       LiveJsKwaiLiveCommands liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("SyncWealthGradeStatus", 10, "syncWealthGradeStatus", LiveJsKwaiLiveCommands$11.INSTANCE, or2, null, 8, null);
       LiveJsKwaiLiveCommands.SyncWealthGradeStatus = v2;
       liveJsKwaiLi[10] = v2;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("MockSelfSendGiftEffect", 11, "mockSelfSendGiftEffect", LiveJsKwaiLiveCommands$12.INSTANCE, or2, null, 8, null);
       LiveJsKwaiLiveCommands.MockSelfSendGiftEffect = v2;
       liveJsKwaiLi[11] = v2;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("GetMaterialResourcePath", 12, "getMaterialResourcePath", LiveJsKwaiLiveCommands$13.INSTANCE, or1.b(or).b(c), null, 8, null);
       LiveJsKwaiLiveCommands.GetMaterialResourcePath = v2;
       liveJsKwaiLi[12] = v2;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("MockEffectInfo", 13, "mockEffectInfo", LiveJsKwaiLiveCommands$14.INSTANCE, or1.b(or), null, 8, null);
       LiveJsKwaiLiveCommands.MockEffectInfo = v2;
       liveJsKwaiLi[13] = v2;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("RemoveRedPacket", 14, "removeLEEE", LiveJsKwaiLiveCommands$15.INSTANCE, or1.b(or), null, 8, null);
       LiveJsKwaiLiveCommands.RemoveRedPacket = v2;
       liveJsKwaiLi[14] = v2;
       or2 = or1;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("OpenLiveGiftPanel", 15, "openLiveGiftPanel", LiveJsKwaiLiveCommands$16.INSTANCE, or2, null, 8, null);
       LiveJsKwaiLiveCommands.OpenLiveGiftPanel = v2;
       liveJsKwaiLi[15] = v2;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("SendGifStToGuest", 16, "sendGiftToGuest", LiveJsKwaiLiveCommands$17.INSTANCE, or2, null, 8, null);
       LiveJsKwaiLiveCommands.SendGifStToGuest = v2;
       liveJsKwaiLi[16] = v2;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("OpenCart", 17, "openCart", LiveJsKwaiLiveCommands$18.INSTANCE, or2, null, 8, null);
       LiveJsKwaiLiveCommands.OpenCart = v2;
       liveJsKwaiLi[17] = v2;
       liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("NotifyAddFansPriceChanged", 18, "notifyAddFansPriceChanged", LiveJsKwaiLiveCommands$19.INSTANCE, or, null, 8, null);
       LiveJsKwaiLiveCommands.NotifyAddFansPriceChanged = v2;
       liveJsKwaiLi[18] = v2;
       r g = r.g;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("LiveRouter", 19, "liveRouter", LiveJsKwaiLiveCommands$20.INSTANCE, or1.b(or).b(c).b(g), null, 8, null);
       LiveJsKwaiLiveCommands.LiveRouter = v2;
       liveJsKwaiLi[19] = v2;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("Toast", 20, "toast", LiveJsKwaiLiveCommands$21.INSTANCE, or1.b(or).b(c).b(g), null, 8, null);
       LiveJsKwaiLiveCommands.Toast = v2;
       liveJsKwaiLi[20] = v2;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("ClosePage", 21, "closePage", LiveJsKwaiLiveCommands$22.INSTANCE, or1.b(or).b(c).b(g), null, 8, null);
       LiveJsKwaiLiveCommands.ClosePage = v2;
       liveJsKwaiLi[21] = v2;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("PopPage", 22, "popPage", LiveJsKwaiLiveCommands$23.INSTANCE, or1.b(or).b(c), null, 8, null);
       LiveJsKwaiLiveCommands.PopPage = v2;
       liveJsKwaiLi[22] = v2;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("Logger", 23, "logger", LiveJsKwaiLiveCommands$24.INSTANCE, or1.b(or).b(g), null, 8, null);
       LiveJsKwaiLiveCommands.Logger = v2;
       liveJsKwaiLi[23] = v2;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("LogLivePageEnter", 24, "logLivePageEnter", LiveJsKwaiLiveCommands$25.INSTANCE, or1.b(or), null, 8, null);
       LiveJsKwaiLiveCommands.LogLivePageEnter = v2;
       liveJsKwaiLi[24] = v2;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("LiveMerchantBridgeRouter", 25, "liveMerchantBridgeCommand", LiveJsKwaiLiveCommands$26.INSTANCE, or1.b(or), null, 8, null);
       LiveJsKwaiLiveCommands.LiveMerchantBridgeRouter = v2;
       liveJsKwaiLi[25] = v2;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("LiveMerchantPendant", 26, "liveMerchantPendant", LiveJsKwaiLiveCommands$27.INSTANCE, or1.b(or), null, 8, null);
       LiveJsKwaiLiveCommands.LiveMerchantPendant = v2;
       liveJsKwaiLi[26] = v2;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("EnableDismissTouchOutside", 27, "enableDismissTouchOutside", LiveJsKwaiLiveCommands$28.INSTANCE, or1.b(or).b(c), null, 8, null);
       LiveJsKwaiLiveCommands.EnableDismissTouchOutside = v2;
       liveJsKwaiLi[27] = v2;
       r b = r.b;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("NotifyFlowDiversionSettingCompletion", 28, "notifyFlowDiversionSettingCompletion", LiveJsKwaiLiveCommands$29.INSTANCE, b, null, 8, null);
       LiveJsKwaiLiveCommands.NotifyFlowDiversionSettingCompletion = v2;
       liveJsKwaiLi[28] = v2;
       liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("FlowDiversionPayDescriptionConfirmInvite", 29, "flowDiversionPayDescriptionConfirmInvite", LiveJsKwaiLiveCommands$30.INSTANCE, b, null, 8, null);
       LiveJsKwaiLiveCommands.FlowDiversionPayDescriptionConfirmInvite = v2;
       liveJsKwaiLi[29] = v2;
       b = or;
       liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("StartSpecificLineMatch", 30, "startSpecificLineMatch", LiveJsKwaiLiveCommands$31.INSTANCE, b, null, 8, null);
       LiveJsKwaiLiveCommands.StartSpecificLineMatch = v2;
       liveJsKwaiLi[30] = v2;
       liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("AcceptLineInvitation", 31, "acceptLineInvitation", LiveJsKwaiLiveCommands$32.INSTANCE, b, null, 8, null);
       LiveJsKwaiLiveCommands.AcceptLineInvitation = v2;
       liveJsKwaiLi[31] = v2;
       liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("RejectLineInvitation", 32, "rejectLineInvitation", LiveJsKwaiLiveCommands$33.INSTANCE, b, null, 8, null);
       LiveJsKwaiLiveCommands.RejectLineInvitation = v2;
       liveJsKwaiLi[32] = v2;
       liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("SuspendLineInvitation", 33, "suspendLineInvitation", LiveJsKwaiLiveCommands$34.INSTANCE, b, null, 8, null);
       LiveJsKwaiLiveCommands.SuspendLineInvitation = v2;
       liveJsKwaiLi[33] = v2;
       or2 = or1;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("OpenLiveGzoneFloatWindow", 34, "openLiveGzoneFloatWindow", LiveJsKwaiLiveCommands$35.INSTANCE, or2, "game");
       LiveJsKwaiLiveCommands.OpenLiveGzoneFloatWindow = v2;
       liveJsKwaiLi[34] = v2;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("LiveGzoneGetWebViewDisplayMode", 35, "getWebViewDisplayMode", LiveJsKwaiLiveCommands$36.INSTANCE, or2, "Kwai");
       LiveJsKwaiLiveCommands.LiveGzoneGetWebViewDisplayMode = v2;
       liveJsKwaiLi[35] = v2;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("LiveGzoneChangeWebViewDisplayMode", 36, "changeWebViewDisplayMode", LiveJsKwaiLiveCommands$37.INSTANCE, or2, "Kwai");
       LiveJsKwaiLiveCommands.LiveGzoneChangeWebViewDisplayMode = v2;
       liveJsKwaiLi[36] = v2;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("GetLiveSceneInfo", 37, "getLiveSceneInfo", LiveJsKwaiLiveCommands$38.INSTANCE, or1.b(or), null, 8, null);
       LiveJsKwaiLiveCommands.GetLiveSceneInfo = v2;
       liveJsKwaiLi[37] = v2;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("NavigateToH5", 38, "navigateToH5", LiveJsKwaiLiveCommands$39.INSTANCE, or1.b(or), null, 8, null);
       LiveJsKwaiLiveCommands.NavigateToH5 = v2;
       liveJsKwaiLi[38] = v2;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("FetchMaterialResourceImgPath", 39, "fetchResourcePath", LiveJsKwaiLiveCommands$40.INSTANCE, or1.b(or).b(c), null, 8, null);
       LiveJsKwaiLiveCommands.FetchMaterialResourceImgPath = v2;
       liveJsKwaiLi[39] = v2;
       or2 = or1;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("SendGiftToAnchor", 40, "sendGiftToAnchor", LiveJsKwaiLiveCommands$41.INSTANCE, or2, null, 8, null);
       LiveJsKwaiLiveCommands.SendGiftToAnchor = v2;
       liveJsKwaiLi[40] = v2;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("QuitLive", 41, "quitLive", LiveJsKwaiLiveCommands$42.INSTANCE, or2, null, 8, null);
       LiveJsKwaiLiveCommands.QuitLive = v2;
       liveJsKwaiLi[41] = v2;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("FollowUser", 42, "followUser", LiveJsKwaiLiveCommands$43.INSTANCE, or1.b(or).b(g), null, 8, null);
       LiveJsKwaiLiveCommands.FollowUser = v2;
       liveJsKwaiLi[42] = v2;
       or2 = or1;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("RecruitNotifyJobApplySuccess", 43, "recruitNotifyJobApplySuccess", LiveJsKwaiLiveCommands$44.INSTANCE, or2, null, 8, null);
       LiveJsKwaiLiveCommands.RecruitNotifyJobApplySuccess = v2;
       liveJsKwaiLi[43] = v2;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("UpdateBarrage", 44, "updateBarrage", LiveJsKwaiLiveCommands$45.INSTANCE, or2, null, 8, null);
       LiveJsKwaiLiveCommands.UpdateBarrage = v2;
       liveJsKwaiLi[44] = v2;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("AddBarrage", 45, "addBarrage", LiveJsKwaiLiveCommands$46.INSTANCE, or2, null, 8, null);
       LiveJsKwaiLiveCommands.AddBarrage = v2;
       liveJsKwaiLi[45] = v2;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("ProvidePhoneInfo", 46, "providePhoneInfo", LiveJsKwaiLiveCommands$47.INSTANCE, or1.b(or).b(c), null, 8, null);
       LiveJsKwaiLiveCommands.ProvidePhoneInfo = v2;
       liveJsKwaiLi[46] = v2;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("SendTextComment", 47, "sendTextComment", LiveJsKwaiLiveCommands$48.INSTANCE, or1, null, 8, null);
       LiveJsKwaiLiveCommands.SendTextComment = v2;
       liveJsKwaiLi[47] = v2;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("QueryWalletBalance", 48, "queryWalletBalance", LiveJsKwaiLiveCommands$49.INSTANCE, or1.b(or), null, 8, null);
       LiveJsKwaiLiveCommands.QueryWalletBalance = v2;
       liveJsKwaiLi[48] = v2;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("JoinFansGroup", 49, "joinFansGroup", LiveJsKwaiLiveCommands$50.INSTANCE, or1, null, 8, null);
       LiveJsKwaiLiveCommands.JoinFansGroup = v2;
       liveJsKwaiLi[49] = v2;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("QueryFollowStatus", 50, "queryFollowStatus", LiveJsKwaiLiveCommands$51.INSTANCE, or1.b(or).b(g), null, 8, null);
       LiveJsKwaiLiveCommands.QueryFollowStatus = v2;
       liveJsKwaiLi[50] = v2;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("BatchQueryFollowStatus", 51, "batchQueryFollowStatus", LiveJsKwaiLiveCommands$52.INSTANCE, or1.b(or).b(g), null, 8, null);
       LiveJsKwaiLiveCommands.BatchQueryFollowStatus = v2;
       liveJsKwaiLi[51] = v2;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("BatchFetchResourcePath", 52, "batchFetchResourcePath", LiveJsKwaiLiveCommands$53.INSTANCE, or.b(or1).b(c).b(g), null, 8, null);
       LiveJsKwaiLiveCommands.BatchFetchResourcePath = v2;
       liveJsKwaiLi[52] = v2;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("LiveWatchTimerStart", 53, "liveWatchTimerStart", LiveJsKwaiLiveCommands$54.INSTANCE, or1.b(or), null, 8, null);
       LiveJsKwaiLiveCommands.LiveWatchTimerStart = v2;
       liveJsKwaiLi[53] = v2;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("LiveWatchTimerPause", 54, "liveWatchTimerPause", LiveJsKwaiLiveCommands$55.INSTANCE, or1.b(or), null, 8, null);
       LiveJsKwaiLiveCommands.LiveWatchTimerPause = v2;
       liveJsKwaiLi[54] = v2;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("LiveWatchTimerStop", 55, "liveWatchTimerStop", LiveJsKwaiLiveCommands$56.INSTANCE, or1.b(or), null, 8, null);
       LiveJsKwaiLiveCommands.LiveWatchTimerStop = v2;
       liveJsKwaiLi[55] = v2;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("LiveWatchTimerQuery", 56, "liveWatchTimerQuery", LiveJsKwaiLiveCommands$57.INSTANCE, or1.b(or), null, 8, null);
       LiveJsKwaiLiveCommands.LiveWatchTimerQuery = v2;
       liveJsKwaiLi[56] = v2;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("GetServerTime", 57, "getServerTime", LiveJsKwaiLiveCommands$58.INSTANCE, or1.b(or).b(c), null, 8, null);
       LiveJsKwaiLiveCommands.GetServerTime = v2;
       liveJsKwaiLi[57] = v2;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("GetMagicFaceSDKInfo", 58, "getMagicFaceSDKInfo", LiveJsKwaiLiveCommands$59.INSTANCE, or1.b(or), null, 8, null);
       LiveJsKwaiLiveCommands.GetMagicFaceSDKInfo = v2;
       liveJsKwaiLi[58] = v2;
       liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("GetInteractMagicFaceInfo", 59, "getInteractiveMagicFaceInfo", LiveJsKwaiLiveCommands$60.INSTANCE, b, null, 8, null);
       LiveJsKwaiLiveCommands.GetInteractMagicFaceInfo = v2;
       liveJsKwaiLi[59] = v2;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("IsFirstInstall", 60, "isFirstInstall", LiveJsKwaiLiveCommands$61.INSTANCE, or1.b(or), null, 8, null);
       LiveJsKwaiLiveCommands.IsFirstInstall = v2;
       liveJsKwaiLi[60] = v2;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("GetDevicePerformanceScore", 61, "getDevicePerformanceScore", LiveJsKwaiLiveCommands$62.INSTANCE, or1.b(or), null, 8, null);
       LiveJsKwaiLiveCommands.GetDevicePerformanceScore = v2;
       liveJsKwaiLi[61] = v2;
       liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("StartPKInvitation", 62, "startPKInvitation", LiveJsKwaiLiveCommands$63.INSTANCE, b, null, 8, null);
       LiveJsKwaiLiveCommands.StartPKInvitation = v2;
       liveJsKwaiLi[62] = v2;
       liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("AcceptPKInvitation", 63, "acceptPKInvitation", LiveJsKwaiLiveCommands$64.INSTANCE, b, null, 8, null);
       LiveJsKwaiLiveCommands.AcceptPKInvitation = v2;
       liveJsKwaiLi[63] = v2;
       liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("RejectPKInvitation", 64, "rejectPKInvitation", LiveJsKwaiLiveCommands$65.INSTANCE, b, null, 8, null);
       LiveJsKwaiLiveCommands.RejectPKInvitation = v2;
       liveJsKwaiLi[64] = v2;
       liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("InvitePkOneMoreGame", 65, "invitePkOneMoreGame", LiveJsKwaiLiveCommands$66.INSTANCE, b, null, 8, null);
       LiveJsKwaiLiveCommands.InvitePkOneMoreGame = v2;
       liveJsKwaiLi[65] = v2;
       liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("AcceptPkOneMoreGame", 66, "acceptPkOneMoreGame", LiveJsKwaiLiveCommands$67.INSTANCE, b, null, 8, null);
       LiveJsKwaiLiveCommands.AcceptPkOneMoreGame = v2;
       liveJsKwaiLi[66] = v2;
       liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("RejectPkOneMoreGame", 67, "rejectPkOneMoreGame", LiveJsKwaiLiveCommands$68.INSTANCE, b, null, 8, null);
       LiveJsKwaiLiveCommands.RejectPkOneMoreGame = v2;
       liveJsKwaiLi[67] = v2;
       liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("LiveJsCmdInviteMultiPkOneMoreGame", 68, "inviteMultiPkOneMoreGame", LiveJsKwaiLiveCommands$69.INSTANCE, b, null, 8, null);
       LiveJsKwaiLiveCommands.LiveJsCmdInviteMultiPkOneMoreGame = v2;
       liveJsKwaiLi[68] = v2;
       liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("ApplyMagicFace", 69, "applyMagicFace", LiveJsKwaiLiveCommands$70.INSTANCE, b, null, 8, null);
       LiveJsKwaiLiveCommands.ApplyMagicFace = v2;
       liveJsKwaiLi[69] = v2;
       liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("GetCurrentMagicFaceId", 70, "getCurrentMagicFaceId", LiveJsKwaiLiveCommands$71.INSTANCE, b, null, 8, null);
       LiveJsKwaiLiveCommands.GetCurrentMagicFaceId = v2;
       liveJsKwaiLi[70] = v2;
       liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("RemoveMagicFace", 71, "removeMagicFace", LiveJsKwaiLiveCommands$72.INSTANCE, b, null, 8, null);
       LiveJsKwaiLiveCommands.RemoveMagicFace = v2;
       liveJsKwaiLi[71] = v2;
       liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("StartMultiPK", 72, "startMultiPK", LiveJsKwaiLiveCommands$73.INSTANCE, b, null, 8, null);
       LiveJsKwaiLiveCommands.StartMultiPK = v2;
       liveJsKwaiLi[72] = v2;
       or2 = or1;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("ShowApplyChatDialog", 73, "showApplyChatDialog", LiveJsKwaiLiveCommands$74.INSTANCE, or2, null, 8, null);
       LiveJsKwaiLiveCommands.ShowApplyChatDialog = v2;
       liveJsKwaiLi[73] = v2;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("ShowApplyChatWaitingDialog", 74, "showApplyChatWaitingDialog", LiveJsKwaiLiveCommands$75.INSTANCE, or2, null, 8, null);
       LiveJsKwaiLiveCommands.ShowApplyChatWaitingDialog = v2;
       liveJsKwaiLi[74] = v2;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("CancelApplyChat", 75, "cancelApplyChat", LiveJsKwaiLiveCommands$76.INSTANCE, or2, null, 8, null);
       LiveJsKwaiLiveCommands.CancelApplyChat = v2;
       liveJsKwaiLi[75] = v2;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("EditChatGuestLabel", 76, "editChatGuestLabel", LiveJsKwaiLiveCommands$77.INSTANCE, or.b(or1), null, 8, null);
       LiveJsKwaiLiveCommands.EditChatGuestLabel = v2;
       liveJsKwaiLi[76] = v2;
       or2 = or1;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("SendGiftToAnchorV2", 77, "sendGiftToAnchorV2", LiveJsKwaiLiveCommands$78.INSTANCE, or2, null, 8, null);
       LiveJsKwaiLiveCommands.SendGiftToAnchorV2 = v2;
       liveJsKwaiLi[77] = v2;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("LeaveLiveChat", 78, "leaveLiveChat", LiveJsKwaiLiveCommands$79.INSTANCE, or2, null, 8, null);
       LiveJsKwaiLiveCommands.LeaveLiveChat = v2;
       liveJsKwaiLi[78] = v2;
       liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("StartChatInvitation", 79, "startChatInvitation", LiveJsKwaiLiveCommands$80.INSTANCE, b, null, 8, null);
       LiveJsKwaiLiveCommands.StartChatInvitation = v2;
       liveJsKwaiLi[79] = v2;
       liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("AcceptChatInvitation", 80, "acceptChatInvitation", LiveJsKwaiLiveCommands$81.INSTANCE, b, null, 8, null);
       LiveJsKwaiLiveCommands.AcceptChatInvitation = v2;
       liveJsKwaiLi[80] = v2;
       liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("NotifyMultiChatLayoutChanged", 81, "notifyMultiChatLayoutChanged", LiveJsKwaiLiveCommands$82.INSTANCE, b, null, 8, null);
       LiveJsKwaiLiveCommands.NotifyMultiChatLayoutChanged = v2;
       liveJsKwaiLi[81] = v2;
       liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("MultiChatSwitchStatusChanged", 82, "setMultiChatSwitchStatus", LiveJsKwaiLiveCommands$83.INSTANCE, b, null, 8, null);
       LiveJsKwaiLiveCommands.MultiChatSwitchStatusChanged = v2;
       liveJsKwaiLi[82] = v2;
       liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("QueryUserChatInviteStatus", 83, "queryUserChatInviteStatus", LiveJsKwaiLiveCommands$84.INSTANCE, b, null, 8, null);
       LiveJsKwaiLiveCommands.QueryUserChatInviteStatus = v2;
       liveJsKwaiLi[83] = v2;
       liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("SwitchLiveHouseBlindDateState", 84, "switchLiveHouseBlindDateState", LiveJsKwaiLiveCommands$85.INSTANCE, b, null, 8, null);
       LiveJsKwaiLiveCommands.SwitchLiveHouseBlindDateState = v2;
       liveJsKwaiLi[84] = v2;
       d = or1;
       r or3 = or;
       r or4 = or3;
       r or5 = or4;
       LiveJsKwaiLiveCommands liveJsKwaiLi4 = new LiveJsKwaiLiveCommands("SwitchBlindDateEntranceState", 85, "switchBlindDateEntranceState", LiveJsKwaiLiveCommands$86.INSTANCE, c, 0, 8, null);
       LiveJsKwaiLiveCommands.SwitchBlindDateEntranceState = v2;
       liveJsKwaiLi[85] = v2;
       b = or5;
       liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("EditAndGetLineUserTag", 86, "editAndGetLineUserTag", LiveJsKwaiLiveCommands$87.INSTANCE, b, null, 8, null);
       LiveJsKwaiLiveCommands.EditAndGetLineUserTag = v2;
       liveJsKwaiLi[86] = v2;
       liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("RejectMultiLineInvitation", 87, "rejectMultiLineInvitation", LiveJsKwaiLiveCommands$88.INSTANCE, b, null, 8, null);
       LiveJsKwaiLiveCommands.RejectMultiLineInvitation = v2;
       liveJsKwaiLi[87] = v2;
       liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("AcceptMultiLineInvitation", 88, "acceptMultiLineInvitation", LiveJsKwaiLiveCommands$89.INSTANCE, b, null, 8, null);
       LiveJsKwaiLiveCommands.AcceptMultiLineInvitation = v2;
       liveJsKwaiLi[88] = v2;
       liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("SwitchLineChatMode", 89, "switchLineChatMode", LiveJsKwaiLiveCommands$90.INSTANCE, b, null, 8, null);
       LiveJsKwaiLiveCommands.SwitchLineChatMode = v2;
       liveJsKwaiLi[89] = v2;
       liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("SwitchMultiInteractBiz", 90, "interactSwitchBiz", LiveJsKwaiLiveCommands$91.INSTANCE, b, null, 8, null);
       LiveJsKwaiLiveCommands.SwitchMultiInteractBiz = v2;
       liveJsKwaiLi[90] = v2;
       liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("ShowMultiLinePuzzleAnim", 91, "showPuzzleAnimation", LiveJsKwaiLiveCommands$92.INSTANCE, b, null, 8, null);
       LiveJsKwaiLiveCommands.ShowMultiLinePuzzleAnim = v2;
       liveJsKwaiLi[91] = v2;
       liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("ShowMultiLineClosePanel", 92, "showLineCloseMenu", LiveJsKwaiLiveCommands$93.INSTANCE, b, null, 8, null);
       LiveJsKwaiLiveCommands.ShowMultiLineClosePanel = v2;
       liveJsKwaiLi[92] = v2;
       liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("EndPkInAdvance", 93, "endPkInAdvance", LiveJsKwaiLiveCommands$94.INSTANCE, b, null, 8, null);
       LiveJsKwaiLiveCommands.EndPkInAdvance = v2;
       liveJsKwaiLi[93] = v2;
       liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("GetInteractChatMediaInfo", 94, "getInteractChatMediaInfo", LiveJsKwaiLiveCommands$95.INSTANCE, d.b(or5), null, 8, null);
       LiveJsKwaiLiveCommands.GetInteractChatMediaInfo = v2;
       liveJsKwaiLi[94] = v2;
       liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("UpdateMuteState", 95, "updateMuteState", LiveJsKwaiLiveCommands$96.INSTANCE, d.b(or5), null, 8, null);
       LiveJsKwaiLiveCommands.UpdateMuteState = v2;
       liveJsKwaiLi[95] = v2;
       liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("GetInteractRoomInfo", 96, "getInteractRoomInfo", LiveJsKwaiLiveCommands$97.INSTANCE, d.b(or5), null, 8, null);
       LiveJsKwaiLiveCommands.GetInteractRoomInfo = v2;
       liveJsKwaiLi[96] = v2;
       b = or5;
       liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("SendNormalLEEE", 97, "sendNormalLEEE", LiveJsKwaiLiveCommands$98.INSTANCE, b, null, 8, null);
       LiveJsKwaiLiveCommands.SendNormalLEEE = v2;
       liveJsKwaiLi[97] = v2;
       liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("AppendNormalLEEE", 98, "appendNormalLEEE", LiveJsKwaiLiveCommands$99.INSTANCE, b, null, 8, null);
       LiveJsKwaiLiveCommands.AppendNormalLEEE = v2;
       liveJsKwaiLi[98] = v2;
       r or6 = or5;
       g = d;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("ReportAdLog", 99, "reportAdLog", LiveJsKwaiLiveCommands$100.INSTANCE, g, null, 8, null);
       LiveJsKwaiLiveCommands.ReportAdLog = v2;
       liveJsKwaiLi[99] = v2;
       liveJsKwaiLi2 = new LiveJsKwaiLiveCommands("EndMultiLineChatMode", 100, "endMultiLineChatMode", LiveJsKwaiLiveCommands$101.INSTANCE, or6, null, 8, null);
       LiveJsKwaiLiveCommands.EndMultiLineChatMode = v2;
       liveJsKwaiLi[100] = v2;
       LiveJsKwaiLiveCommands liveJsKwaiLi5 = new LiveJsKwaiLiveCommands("SwitchEffectRenderBannedBizBit", 101, "switchEffectRenderBannedBizBit", LiveJsKwaiLiveCommands$102.INSTANCE, g.b(or6), null, 8, null);
       LiveJsKwaiLiveCommands.SwitchEffectRenderBannedBizBit = v2;
       liveJsKwaiLi[101] = v2;
       or2 = g;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("LiveAbility", 102, "liveAbility", LiveJsKwaiLiveCommands$103.INSTANCE, or2, null, 8, null);
       LiveJsKwaiLiveCommands.LiveAbility = v2;
       liveJsKwaiLi[102] = v2;
       liveJsKwaiLi5 = new LiveJsKwaiLiveCommands("GetMagicFacePath", 103, "getMagicFacePath", LiveJsKwaiLiveCommands$104.INSTANCE, g.b(or6), null, 8, null);
       LiveJsKwaiLiveCommands.GetMagicFacePath = v2;
       liveJsKwaiLi[103] = v2;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("LiveEncourageTreasureShowResultDialog", 104, "LiveEncourageTreasureShowResultDialog", LiveJsKwaiLiveCommands$105.INSTANCE, or2, null, 8, null);
       LiveJsKwaiLiveCommands.LiveEncourageTreasureShowResultDialog = v2;
       liveJsKwaiLi[104] = v2;
       liveJsKwaiLi3 = new LiveJsKwaiLiveCommands("LiveEncourageTreasureTimerQuery", 105, "LiveEncourageTreasureTimerQuery", LiveJsKwaiLiveCommands$106.INSTANCE, or2, null, 8, null);
       LiveJsKwaiLiveCommands.LiveEncourageTreasureTimerQuery = v2;
       liveJsKwaiLi[105] = v2;
       LiveJsKwaiLiveCommands.$VALUES = liveJsKwaiLi;
       LiveJsKwaiLiveCommands.Companion = new LiveJsKwaiLiveCommands$a(null);
       liveJsKwaiLi = LiveJsKwaiLiveCommands.values();
       LinkedHashMap linkedHashMa = new LinkedHashMap(q.n(s0.j(liveJsKwaiLi.length), 16));
       int len = liveJsKwaiLi.length;
       for (LiveJsKwaiLiveCommands liveJsKwaiLi1 = new LiveJsKwaiLiveCommands("GetLiveRoomInfo", 0, "getLiveRoomInfo", LiveJsKwaiLiveCommands$1.INSTANCE, d.b(e), null, 8, null); i < len; i = i + 1) {
          object oobject = liveJsKwaiLi[i];
          linkedHashMa.put(oobject.getCommandName(), oobject);
       }
       LiveJsKwaiLiveCommands.mapping = linkedHashMa;
       LiveJsKwaiLiveCommands.allCommandIds = linkedHashMa.values();
    }
    public void LiveJsKwaiLiveCommands(String p0,int p1,String p2,a p3,r p4,String p5){
       super(p0, p1);
       this.commandName = p2;
       this.commandProvider = p3;
       this.supportedScene = p4;
       this.nameSpace = p5;
    }
    public void LiveJsKwaiLiveCommands(String p0,int p1,String p2,a p3,r p4,String p5,int p6,u p7){
       if (p6 & 0x08) {
          p5 = "KwaiLive";
       }
       super(p0, p1, p2, p3, p4, p5);
       return;
    }
    public static final LiveJsKwaiLiveCommands fromName(String p0){
       PatchProxyResult patchProxyRe = PatchProxyResult.class;
       LiveJsKwaiLiveCommands$a obj = PatchProxy.applyOneRefs(p0, null, LiveJsKwaiLiveCommands.class, "3");
       if (obj != patchProxyRe) {
          return obj;
       }
       obj = LiveJsKwaiLiveCommands.Companion;
       Objects.requireNonNull(obj);
       Object obj1 = PatchProxy.applyOneRefs(p0, obj, LiveJsKwaiLiveCommands$a.class, "1");
       if (obj1 != patchProxyRe) {
       }else {
          a.p(p0, "commandName");
          obj1 = LiveJsKwaiLiveCommands.mapping.get(p0);
       }
       return obj1;
    }
    public static final Collection getAllCommandIds(){
       return LiveJsKwaiLiveCommands.allCommandIds;
    }
    public static LiveJsKwaiLiveCommands valueOf(String p0){
       Object obj = PatchProxy.applyOneRefs(p0, null, LiveJsKwaiLiveCommands.class, "2");
       if (obj != PatchProxyResult.class) {
          return obj;
       }
       return Enum.valueOf(LiveJsKwaiLiveCommands.class, p0);
    }
    public static LiveJsKwaiLiveCommands[] values(){
       Object obj = PatchProxy.apply(null, null, LiveJsKwaiLiveCommands.class, "1");
       if (obj != PatchProxyResult.class) {
          return obj;
       }
       return LiveJsKwaiLiveCommands.$VALUES.clone();
    }
    public String getCommandName(){
       return this.commandName;
    }
    public a getCommandProvider(){
       return this.commandProvider;
    }
    public String getNameSpace(){
       return this.nameSpace;
    }
    public r getSupportedScene(){
       return this.supportedScene;
    }
}
