package com.kuaishou.live.common.core.component.pk.LivePkResource$PkSkinResource;
import java.lang.Enum;
import com.kuaishou.live.common.core.component.pk.LivePkResourcePathConstant;
import java.lang.String;
import java.lang.Object;
import java.lang.Class;
import com.kwai.robust.PatchProxy;
import com.kwai.robust.PatchProxyResult;

public final class LivePkResource$PkSkinResource extends Enum	// class@001728
{
    public String mBackUpCdnUrl;
    public int mBackUpDrawableRes;
    public String mLocalFileResPath;
    public String mLottieImageResFolderPath;
    public int mResourceScopeType;
    public static final LivePkResource$PkSkinResource[] $VALUES;
    public static final LivePkResource$PkSkinResource CHAT_ICON;
    public static final LivePkResource$PkSkinResource END_PK_ICON;
    public static final LivePkResource$PkSkinResource LIVE_PK_COHESION_PK_RESULT_HEART;
    public static final LivePkResource$PkSkinResource LIVE_PK_COHESION_PK_RESULT_LOSE_BACKGROUND;
    public static final LivePkResource$PkSkinResource LIVE_PK_COHESION_PK_RESULT_TIE_BACKGROUND;
    public static final LivePkResource$PkSkinResource LIVE_PK_COHESION_PK_RESULT_WIN_BACKGROUND;
    public static final LivePkResource$PkSkinResource LIVE_PK_COHESION_PK_START;
    public static final LivePkResource$PkSkinResource LIVE_PK_COMBO_WIN;
    public static final LivePkResource$PkSkinResource LIVE_PK_GIFT_MOMENT_ENTER_ANIM;
    public static final LivePkResource$PkSkinResource LIVE_PK_GIFT_MOMENT_TIP_ICON;
    public static final LivePkResource$PkSkinResource LIVE_PK_RANK_OPPONENT_EMPTY;
    public static final LivePkResource$PkSkinResource LIVE_PK_RANK_OPPONENT_FIRST;
    public static final LivePkResource$PkSkinResource LIVE_PK_RANK_OPPONENT_SECOND;
    public static final LivePkResource$PkSkinResource LIVE_PK_RANK_OPPONENT_THIRD;
    public static final LivePkResource$PkSkinResource LIVE_PK_RANK_SELF_EMPTY;
    public static final LivePkResource$PkSkinResource LIVE_PK_RANK_SELF_FIRST;
    public static final LivePkResource$PkSkinResource LIVE_PK_RANK_SELF_SECOND;
    public static final LivePkResource$PkSkinResource LIVE_PK_RANK_SELF_THIRD;
    public static final LivePkResource$PkSkinResource LIVE_PK_SCORE_LIMIT_BOTTOM_BAR_ANIM;
    public static final LivePkResource$PkSkinResource PK_BIG_SPARK_BLUE;
    public static final LivePkResource$PkSkinResource PK_BIG_SPARK_ORANGE;
    public static final LivePkResource$PkSkinResource PK_COUNT_DOWN_AREA_SMALL_TALK__ICON;
    public static final LivePkResource$PkSkinResource PK_DIVIDERS;
    public static final LivePkResource$PkSkinResource PK_EMOJI_DRAW;
    public static final LivePkResource$PkSkinResource PK_EMOJI_FAIL;
    public static final LivePkResource$PkSkinResource PK_EMOJI_WIN;
    public static final LivePkResource$PkSkinResource PK_HEALTH_BAR_HONOR;
    public static final LivePkResource$PkSkinResource PK_ICON_V2;
    public static final LivePkResource$PkSkinResource PK_RESOURCE_FAIL_SMALL;
    public static final LivePkResource$PkSkinResource PK_RESOURCE_FINAL_LOSE;
    public static final LivePkResource$PkSkinResource PK_RESOURCE_FINAL_TIE;
    public static final LivePkResource$PkSkinResource PK_RESOURCE_FINAL_WIN;
    public static final LivePkResource$PkSkinResource PK_RESOURCE_NORMAL_LOSE;
    public static final LivePkResource$PkSkinResource PK_RESOURCE_NORMAL_TIE;
    public static final LivePkResource$PkSkinResource PK_RESOURCE_NORMAL_WIN;
    public static final LivePkResource$PkSkinResource PK_RESOURCE_SCORE_LIMIE_RESULT_LOSE;
    public static final LivePkResource$PkSkinResource PK_RESOURCE_SCORE_LIMIE_RESULT_LOSE_SMALL;
    public static final LivePkResource$PkSkinResource PK_RESOURCE_SCORE_LIMIE_RESULT_TIE;
    public static final LivePkResource$PkSkinResource PK_RESOURCE_SCORE_LIMIE_RESULT_TIE_SMALL;
    public static final LivePkResource$PkSkinResource PK_RESOURCE_SCORE_LIMIE_RESULT_WIN;
    public static final LivePkResource$PkSkinResource PK_RESOURCE_SCORE_LIMIE_RESULT_WIN_SMALL;
    public static final LivePkResource$PkSkinResource PK_RESOURCE_TEAM_PK_VS;
    public static final LivePkResource$PkSkinResource PK_RESOURCE_TIE_SMALL;
    public static final LivePkResource$PkSkinResource PK_RESOURCE_VS;
    public static final LivePkResource$PkSkinResource PK_RESOURCE_WIN_SMALL;
    public static final LivePkResource$PkSkinResource PK_SCORE_RANK_BATTLE_SPARK_LOTTIE;
    public static final LivePkResource$PkSkinResource PK_SMALL_SPARK_BLUE;
    public static final LivePkResource$PkSkinResource PK_SMALL_SPARK_ORANGE;
    public static final LivePkResource$PkSkinResource PK_SMALL_WINDOW_SCORE_PANEL_BG;
    public static final LivePkResource$PkSkinResource PK_SMALL_WINDOW_SCORE_PANEL_PK_ICON;
    public static final LivePkResource$PkSkinResource PK_SMALL_WINDOW_SCORE_PANEL_PUNISH_ICON;
    public static final LivePkResource$PkSkinResource PK_SMALL_WINDOW_SCORE_PANEL_RESULT_DRAW_ICON;
    public static final LivePkResource$PkSkinResource PK_SMALL_WINDOW_SCORE_PANEL_RESULT_FAIL_ICON;
    public static final LivePkResource$PkSkinResource PK_SMALL_WINDOW_SCORE_PANEL_RESULT_WIN_ICON;
    public static final LivePkResource$PkSkinResource PK_SMALL_WINDOW_SCORE_PANEL_SCORE_BEHIND_ICON;
    public static final LivePkResource$PkSkinResource PK_SMALL_WINDOW_SCORE_PANEL_SCORE_EQUAL_ICON;
    public static final LivePkResource$PkSkinResource PK_SMALL_WINDOW_SCORE_PANEL_SCORE_LEAD_ICON;
    public static final LivePkResource$PkSkinResource VOICE_PARTY_PK_RESOURCE_FINAL_TIE;
    public static final LivePkResource$PkSkinResource VOICE_PARTY_PK_RESOURCE_FINAL_WIN;

    static {
       LivePkResourcePathConstant lIVE_PK_STAR = LivePkResourcePathConstant.LIVE_PK_START_V3_BACKUP_V3_PATH;
       LivePkResource$PkSkinResource pkSkinResour = new LivePkResource$PkSkinResource("PK_RESOURCE_VS", 0, "live_pk_animation_files_v3/live_pk_start_vs_v3.webp", lIVE_PK_STAR.getResourcePath(), -1);
       LivePkResource$PkSkinResource.PK_RESOURCE_VS = v6;
       LivePkResource$PkSkinResource pkSkinResour1 = new LivePkResource$PkSkinResource("PK_RESOURCE_TEAM_PK_VS", 1, "live_pk_start_vs_image/", "live_pk_start_vs_image/live_team_pk_start_vs.webp", LivePkResourcePathConstant.LIVE_PK_START_VS_BACKUP_PATH.getResourcePath(), -1);
       LivePkResource$PkSkinResource.PK_RESOURCE_TEAM_PK_VS = pkSkinResour;
       LivePkResource$PkSkinResource pkSkinResour2 = new LivePkResource$PkSkinResource("PK_BIG_SPARK_ORANGE", 2, "live_pk_big_spark_orange_image/", "live_pk_big_spark_orange_image/live_pk_big_spark_orange.json", "", -1, 1);
       LivePkResource$PkSkinResource.PK_BIG_SPARK_ORANGE = v1;
       pkSkinResour1 = new LivePkResource$PkSkinResource("PK_BIG_SPARK_BLUE", 3, "live_pk_big_spark_blue_image/", "live_pk_big_spark_blue_image/live_pk_big_spark_blue.json", "", -1, 2);
       LivePkResource$PkSkinResource.PK_BIG_SPARK_BLUE = v2;
       LivePkResource$PkSkinResource pkSkinResour3 = new LivePkResource$PkSkinResource("PK_DIVIDERS", 4, "live_pk_dividers_image/", "live_pk_dividers_image/live_pk_dividers.json", "", -1, 1);
       LivePkResource$PkSkinResource.PK_DIVIDERS = v3;
       pkSkinResour1 = new LivePkResource$PkSkinResource("PK_SMALL_SPARK_ORANGE", 5, "live_pk_small_spark_orange_image/", "live_pk_small_spark_orange_image/live_pk_small_spark_orange.json", "", -1, 1);
       LivePkResource$PkSkinResource.PK_SMALL_SPARK_ORANGE = v4;
       pkSkinResour3 = new LivePkResource$PkSkinResource("PK_SMALL_SPARK_BLUE", 6, "live_pk_small_spark_blue_image/", "live_pk_small_spark_blue_image/live_pk_small_spark_blue.json", "", -1, 2);
       LivePkResource$PkSkinResource.PK_SMALL_SPARK_BLUE = v5;
       pkSkinResour1 = new LivePkResource$PkSkinResource("PK_HEALTH_BAR_HONOR", 7, "live_pk_health_bar_honor_image/", "live_pk_health_bar_honor_image/live_pk_health_bar_honor.json", "", -1);
       LivePkResource$PkSkinResource.PK_HEALTH_BAR_HONOR = pkSkinResour2;
       pkSkinResour3 = new LivePkResource$PkSkinResource("PK_EMOJI_WIN", 8, "live_pk_emoji_win_image/", "live_pk_emoji_win_image/live_pk_emoji_win.json", "", -1, 1);
       LivePkResource$PkSkinResource.PK_EMOJI_WIN = pkSkinResour1;
       LivePkResource$PkSkinResource pkSkinResour4 = new LivePkResource$PkSkinResource("PK_EMOJI_FAIL", 9, "live_pk_emoji_fail_image/", "live_pk_emoji_fail_image/live_pk_emoji_fail.json", "", -1, 1);
       LivePkResource$PkSkinResource.PK_EMOJI_FAIL = v9;
       pkSkinResour3 = new LivePkResource$PkSkinResource("PK_EMOJI_DRAW", 10, "live_pk_emoji_draw_image/", "live_pk_emoji_draw_image/live_pk_emoji_draw.json", "", -1, 1);
       LivePkResource$PkSkinResource.PK_EMOJI_DRAW = v10;
       pkSkinResour4 = new LivePkResource$PkSkinResource("PK_ICON_V2", 11, "live_pk_count_down_area/live_pk_icon_v2.webp", "", 0x7f0813bd);
       LivePkResource$PkSkinResource.PK_ICON_V2 = v11;
       pkSkinResour3 = new LivePkResource$PkSkinResource("END_PK_ICON", 12, "live_pk_count_down_area/live_end_pk_icon.webp", "", 0x7f081193);
       LivePkResource$PkSkinResource.END_PK_ICON = v12;
       LivePkResource$PkSkinResource pkSkinResour5 = new LivePkResource$PkSkinResource("CHAT_ICON", 13, "live_pk_count_down_area/live_pk_chat_icon.webp", "", 0x7f0813b9);
       LivePkResource$PkSkinResource.CHAT_ICON = v13;
       pkSkinResour3 = new LivePkResource$PkSkinResource("LIVE_PK_RANK_SELF_EMPTY", 14, null, "live_pk_rank_image/live_pk_rank_self_empty.webp", LivePkResourcePathConstant.LIVE_PK_RANK_SELF_EMPTY_PATH.getResourcePath(), -1);
       LivePkResource$PkSkinResource.LIVE_PK_RANK_SELF_EMPTY = v14;
       LivePkResource$PkSkinResource pkSkinResour6 = new LivePkResource$PkSkinResource("LIVE_PK_RANK_SELF_FIRST", 15, null, "live_pk_rank_image/live_pk_rank_self_first.webp", LivePkResourcePathConstant.LIVE_PK_RANK_SELF_FIRST_PATH.getResourcePath(), 0x7f08135f);
       LivePkResource$PkSkinResource.LIVE_PK_RANK_SELF_FIRST = pkSkinResour3;
       LivePkResource$PkSkinResource pkSkinResour7 = new LivePkResource$PkSkinResource("LIVE_PK_RANK_SELF_SECOND", 16, null, "live_pk_rank_image/live_pk_rank_self_second.webp", LivePkResourcePathConstant.LIVE_PK_RANK_SELF_SECOND_PATH.getResourcePath(), 0x7f081360);
       LivePkResource$PkSkinResource.LIVE_PK_RANK_SELF_SECOND = pkSkinResour4;
       LivePkResource$PkSkinResource pkSkinResour8 = new LivePkResource$PkSkinResource("LIVE_PK_RANK_SELF_THIRD", 17, null, "live_pk_rank_image/live_pk_rank_self_third.webp", LivePkResourcePathConstant.LIVE_PK_RANK_SELF_THIRD_PATH.getResourcePath(), 0x7f081361);
       LivePkResource$PkSkinResource.LIVE_PK_RANK_SELF_THIRD = pkSkinResour7;
       LivePkResource$PkSkinResource pkSkinResour9 = new LivePkResource$PkSkinResource("LIVE_PK_RANK_OPPONENT_EMPTY", 18, null, "live_pk_rank_image/live_pk_rank_opponent_empty.webp", LivePkResourcePathConstant.LIVE_PK_RANK_OPPONENT_EMPTY_PATH.getResourcePath(), -1);
       LivePkResource$PkSkinResource.LIVE_PK_RANK_OPPONENT_EMPTY = v18;
       pkSkinResour8 = new LivePkResource$PkSkinResource("LIVE_PK_RANK_OPPONENT_FIRST", 19, null, "live_pk_rank_image/live_pk_rank_opponent_first.webp", LivePkResourcePathConstant.LIVE_PK_RANK_OPPONENT_FIRST_PATH.getResourcePath(), 0x7f08132a);
       LivePkResource$PkSkinResource.LIVE_PK_RANK_OPPONENT_FIRST = v19;
       pkSkinResour9 = new LivePkResource$PkSkinResource("LIVE_PK_RANK_OPPONENT_SECOND", 20, null, "live_pk_rank_image/live_pk_rank_opponent_second.webp", LivePkResourcePathConstant.LIVE_PK_RANK_OPPONENT_SECOND_PATH.getResourcePath(), 0x7f08132b);
       LivePkResource$PkSkinResource.LIVE_PK_RANK_OPPONENT_SECOND = v20;
       pkSkinResour8 = new LivePkResource$PkSkinResource("LIVE_PK_RANK_OPPONENT_THIRD", 21, null, "live_pk_rank_image/live_pk_rank_opponent_third.webp", LivePkResourcePathConstant.LIVE_PK_RANK_OPPONENT_THIRD_PATH.getResourcePath(), 0x7f08132c);
       LivePkResource$PkSkinResource.LIVE_PK_RANK_OPPONENT_THIRD = v21;
       pkSkinResour9 = new LivePkResource$PkSkinResource("PK_SMALL_WINDOW_SCORE_PANEL_BG", 22, "live_pk_small_window_score_panel/live_pk_small_window_score_panel_bg.webp", LivePkResourcePathConstant.LIVE_LIVE_PKNARROW_PATH.getResourcePath(), -1);
       LivePkResource$PkSkinResource.PK_SMALL_WINDOW_SCORE_PANEL_BG = pkSkinResour5;
       pkSkinResour8 = new LivePkResource$PkSkinResource("PK_SMALL_WINDOW_SCORE_PANEL_PK_ICON", 23, "live_pk_small_window_score_panel/live_pk_small_window_score_panel_pk_icon.webp", "", 0x7f081309);
       LivePkResource$PkSkinResource.PK_SMALL_WINDOW_SCORE_PANEL_PK_ICON = pkSkinResour6;
       LivePkResource$PkSkinResource pkSkinResour10 = new LivePkResource$PkSkinResource("PK_SMALL_WINDOW_SCORE_PANEL_PUNISH_ICON", 24, "live_pk_small_window_score_panel/live_pk_small_window_score_panel_punish_icon.webp", "", 0x7f08130a);
       LivePkResource$PkSkinResource.PK_SMALL_WINDOW_SCORE_PANEL_PUNISH_ICON = pkSkinResour8;
       LivePkResource$PkSkinResource pkSkinResour11 = new LivePkResource$PkSkinResource("PK_SMALL_WINDOW_SCORE_PANEL_RESULT_WIN_ICON", 25, "live_pk_small_window_score_panel/live_pk_small_window_score_panel_win_icon.webp", "", 0x7f0813c9);
       LivePkResource$PkSkinResource.PK_SMALL_WINDOW_SCORE_PANEL_RESULT_WIN_ICON = pkSkinResour9;
       LivePkResource$PkSkinResource pkSkinResour12 = new LivePkResource$PkSkinResource("PK_SMALL_WINDOW_SCORE_PANEL_RESULT_FAIL_ICON", 26, "live_pk_small_window_score_panel/live_pk_small_window_score_panel_fail_icon.webp", "", 0x7f0813c8);
       LivePkResource$PkSkinResource.PK_SMALL_WINDOW_SCORE_PANEL_RESULT_FAIL_ICON = pkSkinResour11;
       LivePkResource$PkSkinResource pkSkinResour13 = new LivePkResource$PkSkinResource("PK_SMALL_WINDOW_SCORE_PANEL_RESULT_DRAW_ICON", 27, "live_pk_small_window_score_panel/live_pk_small_window_score_panel_draw_icon.webp", "", 0x7f0813c7);
       LivePkResource$PkSkinResource.PK_SMALL_WINDOW_SCORE_PANEL_RESULT_DRAW_ICON = v27;
       pkSkinResour12 = new LivePkResource$PkSkinResource("LIVE_PK_GIFT_MOMENT_ENTER_ANIM", 28, null, "live_pk_gift_moment/live_pk_enter_gift_moment_anim.webp", LivePkResourcePathConstant.LIVE_PK_GIFT_MOMENT_BACKUP_ANIM_PATH.getResourcePath(), -1);
       LivePkResource$PkSkinResource.LIVE_PK_GIFT_MOMENT_ENTER_ANIM = v28;
       LivePkResource$PkSkinResource pkSkinResour14 = new LivePkResource$PkSkinResource("LIVE_PK_GIFT_MOMENT_TIP_ICON", 29, "live_pk_gift_moment/live_pk_gift_moment_tip_icon.webp", LivePkResourcePathConstant.LIVE_PK_GIFT_MOMENT_RULE_BACKUP.getResourcePath(), -1);
       LivePkResource$PkSkinResource.LIVE_PK_GIFT_MOMENT_TIP_ICON = v29;
       pkSkinResour12 = new LivePkResource$PkSkinResource("LIVE_PK_COMBO_WIN", 30, null, "live_sign_icon_pk_winning_trophy.webp", "", 0x7f08147c);
       LivePkResource$PkSkinResource.LIVE_PK_COMBO_WIN = v30;
       pkSkinResour14 = new LivePkResource$PkSkinResource("PK_SCORE_RANK_BATTLE_SPARK_LOTTIE", 31, "live_pk_score_rank_battle_image/", "live_pk_score_rank_battle_image/live_pk_score_rank_battle.json", "", -1);
       LivePkResource$PkSkinResource.PK_SCORE_RANK_BATTLE_SPARK_LOTTIE = pkSkinResour10;
       LivePkResourcePathConstant lIVE_PK_WIN_ = LivePkResourcePathConstant.LIVE_PK_WIN_BACKUP_V3_PATH;
       pkSkinResour12 = new LivePkResource$PkSkinResource("PK_RESOURCE_FINAL_WIN", 32, "live_pk_animation_files_v3/live_pk_result_win_v3.webp", lIVE_PK_WIN_.getResourcePath(), -1);
       LivePkResource$PkSkinResource.PK_RESOURCE_FINAL_WIN = pkSkinResour13;
       LivePkResourcePathConstant lIVE_PK_LOSE = LivePkResourcePathConstant.LIVE_PK_LOSE_BACKUP_V3_PATH;
       LivePkResource$PkSkinResource pkSkinResour15 = new LivePkResource$PkSkinResource("PK_RESOURCE_FINAL_LOSE", 33, "live_pk_animation_files_v3/live_pk_result_fail_v3.webp", lIVE_PK_LOSE.getResourcePath(), -1);
       LivePkResource$PkSkinResource.PK_RESOURCE_FINAL_LOSE = pkSkinResour12;
       LivePkResourcePathConstant lIVE_PK_TIE_ = LivePkResourcePathConstant.LIVE_PK_TIE_BACKUP_V3_PATH;
       LivePkResource$PkSkinResource pkSkinResour16 = new LivePkResource$PkSkinResource("PK_RESOURCE_FINAL_TIE", 34, "live_pk_animation_files_v3/live_pk_result_tie_v3.webp", lIVE_PK_TIE_.getResourcePath(), -1);
       LivePkResource$PkSkinResource.PK_RESOURCE_FINAL_TIE = v35;
       pkSkinResour15 = new LivePkResource$PkSkinResource("PK_RESOURCE_WIN_SMALL", 35, "live_pk_result_small/live_pk_result_win_small.png", lIVE_PK_WIN_.getResourcePath(), -1);
       LivePkResource$PkSkinResource.PK_RESOURCE_WIN_SMALL = v37;
       pkSkinResour16 = new LivePkResource$PkSkinResource("PK_RESOURCE_FAIL_SMALL", 36, "live_pk_result_small/live_pk_result_fail_small.png", lIVE_PK_LOSE.getResourcePath(), -1);
       LivePkResource$PkSkinResource.PK_RESOURCE_FAIL_SMALL = v38;
       pkSkinResour14 = new LivePkResource$PkSkinResource("PK_RESOURCE_TIE_SMALL", 37, "live_pk_result_small/live_pk_result_tie_small.png", lIVE_PK_TIE_.getResourcePath(), -1);
       LivePkResource$PkSkinResource.PK_RESOURCE_TIE_SMALL = lIVE_PK_LOSE;
       LivePkResource$PkSkinResource pkSkinResour17 = new LivePkResource$PkSkinResource("VOICE_PARTY_PK_RESOURCE_FINAL_WIN", 38, "live_pk_win_image/", "live_pk_win_image/live_pk_win.json", LivePkResourcePathConstant.LIVE_PK_WIN_BACKUP_PATH.getResourcePath(), -1);
       LivePkResource$PkSkinResource.VOICE_PARTY_PK_RESOURCE_FINAL_WIN = lIVE_PK_TIE_;
       pkSkinResour14 = new LivePkResource$PkSkinResource("VOICE_PARTY_PK_RESOURCE_FINAL_TIE", 39, "live_pk_tie_image/", "live_pk_tie_image/live_pk_tie.json", LivePkResourcePathConstant.LIVE_PK_TIE_BACKUP_PATH.getResourcePath(), -1);
       LivePkResource$PkSkinResource.VOICE_PARTY_PK_RESOURCE_FINAL_TIE = pkSkinResour16;
       LivePkResource$PkSkinResource pkSkinResour18 = new LivePkResource$PkSkinResource("PK_RESOURCE_NORMAL_WIN", 40, "live_pk_win_normal_image/", "live_pk_win_normal_image/live_pk_win_normal.json", LivePkResourcePathConstant.LIVE_PK_WIN_NORMAL_BACKUP_PATH.getResourcePath(), -1);
       LivePkResource$PkSkinResource.PK_RESOURCE_NORMAL_WIN = pkSkinResour14;
       LivePkResource$PkSkinResource pkSkinResour19 = new LivePkResource$PkSkinResource("PK_RESOURCE_NORMAL_LOSE", 41, "live_pk_lose_normal_image/", "live_pk_lose_normal_image/live_pk_lose_normal.json", LivePkResourcePathConstant.LIVE_PK_LOSE_NORMAL_BACKUP_PATH.getResourcePath(), -1);
       LivePkResource$PkSkinResource.PK_RESOURCE_NORMAL_LOSE = pkSkinResour15;
       pkSkinResour18 = new LivePkResource$PkSkinResource("PK_RESOURCE_NORMAL_TIE", 42, "live_pk_tie_normal_image/", "live_pk_tie_normal_image/live_pk_tie_normal.json", LivePkResourcePathConstant.LIVE_PK_TIE_NORMAL_BACKUP_PATH.getResourcePath(), -1);
       LivePkResource$PkSkinResource.PK_RESOURCE_NORMAL_TIE = v42;
       pkSkinResour19 = new LivePkResource$PkSkinResource("PK_RESOURCE_SCORE_LIMIE_RESULT_WIN", 43, "live_pk_score_limit_res_dir/result/live_pk_result_win.webp", LivePkResourcePathConstant.LIVE_PK_SCORE_LIMIT_RESULT_WIN_BACKUP_PATH.getResourcePath(), -1);
       LivePkResource$PkSkinResource.PK_RESOURCE_SCORE_LIMIE_RESULT_WIN = v43;
       pkSkinResour18 = new LivePkResource$PkSkinResource("PK_RESOURCE_SCORE_LIMIE_RESULT_LOSE", 44, "live_pk_score_limit_res_dir/result/live_pk_result_fail.webp", LivePkResourcePathConstant.LIVE_PK_SCORE_LIMIT_RESULT_FAIL_BACKUP_PATH.getResourcePath(), -1);
       LivePkResource$PkSkinResource.PK_RESOURCE_SCORE_LIMIE_RESULT_LOSE = v44;
       LivePkResource$PkSkinResource pkSkinResour20 = new LivePkResource$PkSkinResource("PK_RESOURCE_SCORE_LIMIE_RESULT_TIE", 45, "live_pk_score_limit_res_dir/result/live_pk_result_tie.webp", LivePkResourcePathConstant.LIVE_PK_SCORE_LIMIT_RESULT_TIE_BACKUP_PATH.getResourcePath(), -1);
       LivePkResource$PkSkinResource.PK_RESOURCE_SCORE_LIMIE_RESULT_TIE = v45;
       pkSkinResour18 = new LivePkResource$PkSkinResource("PK_RESOURCE_SCORE_LIMIE_RESULT_WIN_SMALL", 46, "live_pk_score_limit_res_dir/result/live_pk_result_win_small.png", LivePkResourcePathConstant.LIVE_PK_SCORE_LIMIT_RESULT_WIN_BACKUP_SMALL_PATH.getResourcePath(), -1);
       LivePkResource$PkSkinResource.PK_RESOURCE_SCORE_LIMIE_RESULT_WIN_SMALL = pkSkinResour17;
       pkSkinResour20 = new LivePkResource$PkSkinResource("PK_RESOURCE_SCORE_LIMIE_RESULT_LOSE_SMALL", 47, "live_pk_score_limit_res_dir/result/live_pk_result_fail_small.png", LivePkResourcePathConstant.LIVE_PK_SCORE_LIMIT_RESULT_FAIL_BACKUP_SMALL_PATH.getResourcePath(), -1);
       LivePkResource$PkSkinResource.PK_RESOURCE_SCORE_LIMIE_RESULT_LOSE_SMALL = pkSkinResour18;
       LivePkResource$PkSkinResource pkSkinResour21 = new LivePkResource$PkSkinResource("PK_RESOURCE_SCORE_LIMIE_RESULT_TIE_SMALL", 48, "live_pk_score_limit_res_dir/result/live_pk_result_tie_small.png", LivePkResourcePathConstant.LIVE_PK_SCORE_LIMIT_RESULT_TIE_BACKUP_SMALL_PATH.getResourcePath(), -1);
       LivePkResource$PkSkinResource.PK_RESOURCE_SCORE_LIMIE_RESULT_TIE_SMALL = pkSkinResour19;
       LivePkResource$PkSkinResource pkSkinResour22 = new LivePkResource$PkSkinResource("PK_SMALL_WINDOW_SCORE_PANEL_SCORE_LEAD_ICON", 49, "live_pk_score_limit_res_dir/pk_small_window_score_panel/live_pk_small_window_score_panel_score_lead_icon.webp", LivePkResourcePathConstant.PK_SMALL_WINDOW_SCORE_PANEL_SCORE_LEAD_BACKUP_PATH.getResourcePath(), -1);
       LivePkResource$PkSkinResource.PK_SMALL_WINDOW_SCORE_PANEL_SCORE_LEAD_ICON = pkSkinResour21;
       LivePkResource$PkSkinResource pkSkinResour23 = new LivePkResource$PkSkinResource("PK_SMALL_WINDOW_SCORE_PANEL_SCORE_BEHIND_ICON", 50, "live_pk_score_limit_res_dir/pk_small_window_score_panel/live_pk_small_window_score_panel_score_behind_icon.webp", LivePkResourcePathConstant.PK_SMALL_WINDOW_SCORE_PANEL_SCORE_BEHIND_BACKUP_PATH.getResourcePath(), -1);
       LivePkResource$PkSkinResource.PK_SMALL_WINDOW_SCORE_PANEL_SCORE_BEHIND_ICON = v50;
       pkSkinResour22 = new LivePkResource$PkSkinResource("PK_SMALL_WINDOW_SCORE_PANEL_SCORE_EQUAL_ICON", 51, "live_pk_score_limit_res_dir/pk_small_window_score_panel/live_pk_small_window_score_panel_score_equal_icon.webp", LivePkResourcePathConstant.PK_SMALL_WINDOW_SCORE_PANEL_SCORE_EQUAL_BACKUP_PATH.getResourcePath(), -1);
       LivePkResource$PkSkinResource.PK_SMALL_WINDOW_SCORE_PANEL_SCORE_EQUAL_ICON = v51;
       pkSkinResour23 = new LivePkResource$PkSkinResource("LIVE_PK_SCORE_LIMIT_BOTTOM_BAR_ANIM", 52, null, "live_pk_revenge/live_pk_revenge_support_bar_lottie.json", "", 0x7f0813c1);
       LivePkResource$PkSkinResource.LIVE_PK_SCORE_LIMIT_BOTTOM_BAR_ANIM = v52;
       pkSkinResour22 = new LivePkResource$PkSkinResource("LIVE_PK_COHESION_PK_START", 53, "live_pk_score_limit_res_dir/result/live_pk_cohesion_start_animation.webp", lIVE_PK_STAR.getResourcePath(), -1);
       LivePkResource$PkSkinResource.LIVE_PK_COHESION_PK_START = v53;
       pkSkinResour23 = new LivePkResource$PkSkinResource("LIVE_PK_COHESION_PK_RESULT_WIN_BACKGROUND", 54, "live_pk_score_limit_res_dir/result/live_pk_cohesion_result_win_support_view.9.png", "", -1);
       LivePkResource$PkSkinResource.LIVE_PK_COHESION_PK_RESULT_WIN_BACKGROUND = lIVE_PK_STAR;
       pkSkinResour22 = new LivePkResource$PkSkinResource("LIVE_PK_COHESION_PK_RESULT_LOSE_BACKGROUND", 55, "live_pk_score_limit_res_dir/result/live_pk_cohesion_result_lose_support_view.9.png", "", -1);
       LivePkResource$PkSkinResource.LIVE_PK_COHESION_PK_RESULT_LOSE_BACKGROUND = pkSkinResour20;
       pkSkinResour23 = new LivePkResource$PkSkinResource("LIVE_PK_COHESION_PK_RESULT_TIE_BACKGROUND", 56, "live_pk_score_limit_res_dir/result/live_pk_cohesion_result_tie_support_view.9.png", "", -1);
       LivePkResource$PkSkinResource.LIVE_PK_COHESION_PK_RESULT_TIE_BACKGROUND = pkSkinResour22;
       LivePkResource$PkSkinResource pkSkinResour24 = new LivePkResource$PkSkinResource("LIVE_PK_COHESION_PK_RESULT_HEART", 57, "live_pk_score_limit_res_dir/result/live_pk_cohesion_result_heart.png", "", -1);
       LivePkResource$PkSkinResource.LIVE_PK_COHESION_PK_RESULT_HEART = v63;
       LivePkResource$PkSkinResource pkSkinResour25 = new LivePkResource$PkSkinResource("PK_COUNT_DOWN_AREA_SMALL_TALK__ICON", 58, "live_pk_score_limit_res_dir/pk_small_talk_res_dir/count_down_area_res/live_pk_small_talk_icon.webp", LivePkResourcePathConstant.PK_SMALL_TALK_ICON_BACKUP_PATH.getResourcePath(), -1);
       LivePkResource$PkSkinResource.PK_COUNT_DOWN_AREA_SMALL_TALK__ICON = pkSkinResour24;
       LivePkResource$PkSkinResource pkSkinResour26 = lIVE_PK_STAR;
       LivePkResource$PkSkinResource[] pkSkinResour27 = new LivePkResource$PkSkinResource[59];
       pkSkinResour27[0] = v6;
       pkSkinResour27[1] = pkSkinResour;
       pkSkinResour27[2] = v1;
       pkSkinResour27[3] = v2;
       pkSkinResour27[4] = v3;
       pkSkinResour27[5] = v4;
       pkSkinResour27[6] = v5;
       pkSkinResour27[7] = pkSkinResour2;
       pkSkinResour27[8] = pkSkinResour1;
       pkSkinResour27[9] = v9;
       pkSkinResour27[10] = v10;
       pkSkinResour27[11] = v11;
       pkSkinResour27[12] = v12;
       pkSkinResour27[13] = v13;
       pkSkinResour27[14] = v14;
       pkSkinResour27[15] = pkSkinResour3;
       pkSkinResour27[16] = pkSkinResour4;
       pkSkinResour27[17] = pkSkinResour7;
       pkSkinResour27[18] = v18;
       pkSkinResour27[19] = v19;
       pkSkinResour27[20] = v20;
       pkSkinResour27[21] = v21;
       pkSkinResour27[22] = pkSkinResour5;
       pkSkinResour27[23] = pkSkinResour6;
       pkSkinResour27[24] = pkSkinResour8;
       pkSkinResour27[25] = pkSkinResour9;
       pkSkinResour27[26] = pkSkinResour11;
       pkSkinResour27[27] = v27;
       pkSkinResour27[28] = v28;
       pkSkinResour27[29] = v29;
       pkSkinResour27[30] = v30;
       pkSkinResour27[31] = pkSkinResour10;
       pkSkinResour27[32] = pkSkinResour13;
       pkSkinResour27[33] = pkSkinResour12;
       pkSkinResour27[34] = v35;
       pkSkinResour27[35] = v37;
       pkSkinResour27[36] = v38;
       pkSkinResour27[37] = lIVE_PK_LOSE;
       pkSkinResour27[38] = lIVE_PK_TIE_;
       pkSkinResour27[39] = pkSkinResour16;
       pkSkinResour27[40] = pkSkinResour14;
       pkSkinResour27[41] = pkSkinResour15;
       pkSkinResour27[42] = v42;
       pkSkinResour27[43] = v43;
       pkSkinResour27[44] = v44;
       pkSkinResour27[45] = v45;
       pkSkinResour27[46] = pkSkinResour17;
       pkSkinResour27[47] = pkSkinResour18;
       pkSkinResour27[48] = pkSkinResour19;
       pkSkinResour27[49] = pkSkinResour21;
       pkSkinResour27[50] = v50;
       pkSkinResour27[51] = v51;
       pkSkinResour27[52] = v52;
       pkSkinResour27[53] = v53;
       pkSkinResour27[54] = pkSkinResour26;
       pkSkinResour27[55] = pkSkinResour20;
       pkSkinResour27[56] = pkSkinResour22;
       pkSkinResour27[57] = v63;
       pkSkinResour27[58] = pkSkinResour24;
       LivePkResource$PkSkinResource.$VALUES = pkSkinResour27;
    }
    public void LivePkResource$PkSkinResource(String p0,int p1,String p2,String p3,int p4){
       super(p0, p1, "", p2, p3, p4);
    }
    public void LivePkResource$PkSkinResource(String p0,int p1,String p2,String p3,String p4,int p5){
       super(p0, p1, p2, p3, p4, p5, 0);
    }
    public void LivePkResource$PkSkinResource(String p0,int p1,String p2,String p3,String p4,int p5,int p6){
       super(p0, p1);
       this.mLottieImageResFolderPath = p2;
       this.mLocalFileResPath = p3;
       this.mBackUpCdnUrl = p4;
       this.mBackUpDrawableRes = p5;
       this.mResourceScopeType = p6;
    }
    public static LivePkResource$PkSkinResource valueOf(String p0){
       Object obj = PatchProxy.applyOneRefs(p0, null, LivePkResource$PkSkinResource.class, "2");
       if (obj != PatchProxyResult.class) {
          return obj;
       }
       return Enum.valueOf(LivePkResource$PkSkinResource.class, p0);
    }
    public static LivePkResource$PkSkinResource[] values(){
       Object obj = PatchProxy.apply(null, null, LivePkResource$PkSkinResource.class, "1");
       if (obj != PatchProxyResult.class) {
          return obj;
       }
       return LivePkResource$PkSkinResource.$VALUES.clone();
    }
}
