package com.kuaishou.live.common.core.component.pk.LivePkResourcePathConstant;
import l12.d;
import java.lang.Enum;
import java.lang.String;
import java.lang.Object;
import java.lang.Class;
import com.kwai.robust.PatchProxy;
import com.kwai.robust.PatchProxyResult;

public final class LivePkResourcePathConstant extends Enum implements d	// class@001729
{
    public final String resourceName;
    public final String resourcePath;
    public static final LivePkResourcePathConstant[] $VALUES;
    public static final LivePkResourcePathConstant COHESION_PK;
    public static final LivePkResourcePathConstant LIVE_ANCHOR_PK_INVITE_AVATAR_RING_PATH;
    public static final LivePkResourcePathConstant LIVE_ANCHOR_PK_RANDOM_MATCH_AVATAR_RING_PATH;
    public static final LivePkResourcePathConstant LIVE_COMMENT_NOTICE_PK_GIFT_PROMPT_BACKGROUND_BACKUP;
    public static final LivePkResourcePathConstant LIVE_COMMENT_NOTICE_PK_GIFT_PROMPT_BACKGROUND_BACKUP_PATH;
    public static final LivePkResourcePathConstant LIVE_ICON_PK_HISTORY_DRAW_PATH;
    public static final LivePkResourcePathConstant LIVE_ICON_PK_HISTORY_FAILURE_PATH;
    public static final LivePkResourcePathConstant LIVE_ICON_PK_HISTORY_LINE_PATH;
    public static final LivePkResourcePathConstant LIVE_ICON_PK_HISTORY_VICTORY_PATH;
    public static final LivePkResourcePathConstant LIVE_LIVE_KUAFANGPK_PATH;
    public static final LivePkResourcePathConstant LIVE_LIVE_PKBLUETEAM_PATH;
    public static final LivePkResourcePathConstant LIVE_LIVE_PKNARROW_PATH;
    public static final LivePkResourcePathConstant LIVE_LIVE_PKYELLOWTEAM_PATH;
    public static final LivePkResourcePathConstant LIVE_LIVE_RECOMMENDEDGIFTS_CRITICALHIT01;
    public static final LivePkResourcePathConstant LIVE_LIVE_RECOMMENDEDGIFTS_CRITICALHIT02;
    public static final LivePkResourcePathConstant LIVE_LIVE_RECOMMENDEDGIFTS_STEALTOWER01;
    public static final LivePkResourcePathConstant LIVE_LIVE_RECOMMENDEDGIFTS_STEALTOWER02;
    public static final LivePkResourcePathConstant LIVE_PK_BG_CONNECTING_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_CHANGE_FORMAT_MODE_1_FOREGROUND_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_CHANGE_FORMAT_MODE_1_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_CHANGE_FORMAT_MODE_2_FOREGROUND_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_CHANGE_FORMAT_MODE_2_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_CHOOSE_FRIENDS_ITEM_WARNING_ICON_NEW_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_FIRST_BLOOD_APPEAR_BACKUP_ANIM_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_FIRST_BLOOD_TIP_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_GIFT_MOMENT_BACKUP_ANIM_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_GIFT_MOMENT_RULE_BACKUP;
    public static final LivePkResourcePathConstant LIVE_PK_LOSE_BACKGROUND_BACKUP_V2_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_LOSE_BACKUP_V2_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_LOSE_BACKUP_V3_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_LOSE_NORMAL_BACKUP_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_MASK_RIPPLE_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_PANEL_RANDOM_PK_BANNER_BG;
    public static final LivePkResourcePathConstant LIVE_PK_RANK_FIRST_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_RANK_OPPONENT_EMPTY_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_RANK_OPPONENT_FIRST_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_RANK_OPPONENT_SECOND_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_RANK_OPPONENT_THIRD_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_RANK_SECOND_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_RANK_SELF_EMPTY_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_RANK_SELF_FIRST_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_RANK_SELF_SECOND_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_RANK_SELF_THIRD_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_RANK_THIRD_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_RECEIVE_INVITE_PROTECTION_FEE_TIP_BACKGROUND_ICON_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_SCORE_LIMIT_RESULT_FAIL_BACKUP_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_SCORE_LIMIT_RESULT_FAIL_BACKUP_SMALL_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_SCORE_LIMIT_RESULT_TIE_BACKUP_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_SCORE_LIMIT_RESULT_TIE_BACKUP_SMALL_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_SCORE_LIMIT_RESULT_WIN_BACKUP_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_SCORE_LIMIT_RESULT_WIN_BACKUP_SMALL_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_SELLING_SETTING_MORE;
    public static final LivePkResourcePathConstant LIVE_PK_START_BACKGROUND_BACKUP_V2_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_START_V3_BACKUP_V3_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_START_VS_BACKUP_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_THREE_OUT_OF_FIVE_BACKGROUD_BACKUP_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_TIE_BACKGROUND_BACKUP_V2_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_TIE_BACKUP_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_TIE_BACKUP_V2_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_TIE_BACKUP_V3_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_TIE_NORMAL_BACKUP_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_TWO_OUT_OF_THREE_BACKGROUND_BACKUP_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_VALUE_DAILY_STATISTIC_TITLE_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_VOICE_PARTY_CROSS_ROOM_PK_INVITATION_WAITING_DIALOG_TEAM_INFO_BG_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_WIN_BACKGROUND_BACKUP_V2_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_WIN_BACKUP_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_WIN_BACKUP_V2_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_WIN_BACKUP_V3_PATH;
    public static final LivePkResourcePathConstant LIVE_PK_WIN_NORMAL_BACKUP_PATH;
    public static final LivePkResourcePathConstant LIVE_SIGN_ICON_PK_WINNING_FLAG_PATH;
    public static final LivePkResourcePathConstant LIVE_VOICE_PARTY_CROSS_ROOM_COUNT_DOWN_LEFT_ICON;
    public static final LivePkResourcePathConstant LIVE_VOICE_PARTY_CROSS_ROOM_PK_START_ANIM_PATH;
    public static final LivePkResourcePathConstant PK_SMALL_TALK_ICON_BACKUP_PATH;
    public static final LivePkResourcePathConstant PK_SMALL_WINDOW_SCORE_PANEL_SCORE_BEHIND_BACKUP_PATH;
    public static final LivePkResourcePathConstant PK_SMALL_WINDOW_SCORE_PANEL_SCORE_EQUAL_BACKUP_PATH;
    public static final LivePkResourcePathConstant PK_SMALL_WINDOW_SCORE_PANEL_SCORE_LEAD_BACKUP_PATH;
    public static final LivePkResourcePathConstant VOICE_PARTY_CROSS_ROOM_PK_INVITATION_WAITING_DIALOG_TEAM_INFO_BG_PATH;

    static {
       LivePkResourcePathConstant[] livePkResour = new LivePkResourcePathConstant[77];
       LivePkResourcePathConstant livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_START_V3_BACKUP_V3_PATH", 0, "LIVE_PK_START_V3_BACKUP_V3_PATH", "/udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_start_vs_backup_v3.webp");
       LivePkResourcePathConstant.LIVE_PK_START_V3_BACKUP_V3_PATH = livePkResour1;
       livePkResour[0] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_WIN_BACKUP_V3_PATH", 1, "LIVE_PK_WIN_BACKUP_V3_PATH", "/udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_win_backup_v3.webp");
       LivePkResourcePathConstant.LIVE_PK_WIN_BACKUP_V3_PATH = livePkResour1;
       livePkResour[1] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_LOSE_BACKUP_V3_PATH", 2, "LIVE_PK_LOSE_BACKUP_V3_PATH", "/udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_lose_backup_v3.webp");
       LivePkResourcePathConstant.LIVE_PK_LOSE_BACKUP_V3_PATH = livePkResour1;
       livePkResour[2] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_TIE_BACKUP_V3_PATH", 3, "LIVE_PK_TIE_BACKUP_V3_PATH", "/udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_tie_backup_v3.webp");
       LivePkResourcePathConstant.LIVE_PK_TIE_BACKUP_V3_PATH = livePkResour1;
       livePkResour[3] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_SCORE_LIMIT_RESULT_WIN_BACKUP_PATH", 4, "LIVE_PK_SCORE_LIMIT_RESULT_WIN_BACKUP_PATH", "/udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_score_limit_result_win_back.webp");
       LivePkResourcePathConstant.LIVE_PK_SCORE_LIMIT_RESULT_WIN_BACKUP_PATH = livePkResour1;
       livePkResour[4] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_SCORE_LIMIT_RESULT_FAIL_BACKUP_PATH", 5, "LIVE_PK_SCORE_LIMIT_RESULT_FAIL_BACKUP_PATH", "/udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_score_limit_result_fail_back.webp");
       LivePkResourcePathConstant.LIVE_PK_SCORE_LIMIT_RESULT_FAIL_BACKUP_PATH = livePkResour1;
       livePkResour[5] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_SCORE_LIMIT_RESULT_TIE_BACKUP_PATH", 6, "LIVE_PK_SCORE_LIMIT_RESULT_TIE_BACKUP_PATH", "/udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_score_limit_result_tie_back.webp");
       LivePkResourcePathConstant.LIVE_PK_SCORE_LIMIT_RESULT_TIE_BACKUP_PATH = livePkResour1;
       livePkResour[6] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_SCORE_LIMIT_RESULT_WIN_BACKUP_SMALL_PATH", 7, "LIVE_PK_SCORE_LIMIT_RESULT_WIN_BACKUP_SMALL_PATH", "/udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_score_limit_result_win_back_small.webp");
       LivePkResourcePathConstant.LIVE_PK_SCORE_LIMIT_RESULT_WIN_BACKUP_SMALL_PATH = livePkResour1;
       livePkResour[7] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_SCORE_LIMIT_RESULT_FAIL_BACKUP_SMALL_PATH", 8, "LIVE_PK_SCORE_LIMIT_RESULT_FAIL_BACKUP_SMALL_PATH", "/udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_score_limit_result_fail_back_small.webp");
       LivePkResourcePathConstant.LIVE_PK_SCORE_LIMIT_RESULT_FAIL_BACKUP_SMALL_PATH = livePkResour1;
       livePkResour[8] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_SCORE_LIMIT_RESULT_TIE_BACKUP_SMALL_PATH", 9, "LIVE_PK_SCORE_LIMIT_RESULT_TIE_BACKUP_SMALL_PATH", "/udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_score_limit_result_tie_back_small.webp");
       LivePkResourcePathConstant.LIVE_PK_SCORE_LIMIT_RESULT_TIE_BACKUP_SMALL_PATH = livePkResour1;
       livePkResour[9] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("PK_SMALL_WINDOW_SCORE_PANEL_SCORE_LEAD_BACKUP_PATH", 10, "PK_SMALL_WINDOW_SCORE_PANEL_SCORE_LEAD_BACKUP_PATH", "/udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_small_window_score_panel_score_lead_icon.webp");
       LivePkResourcePathConstant.PK_SMALL_WINDOW_SCORE_PANEL_SCORE_LEAD_BACKUP_PATH = livePkResour1;
       livePkResour[10] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("PK_SMALL_WINDOW_SCORE_PANEL_SCORE_BEHIND_BACKUP_PATH", 11, "PK_SMALL_WINDOW_SCORE_PANEL_SCORE_BEHIND_BACKUP_PATH", "/udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_small_window_score_panel_score_behind_icon.webp");
       LivePkResourcePathConstant.PK_SMALL_WINDOW_SCORE_PANEL_SCORE_BEHIND_BACKUP_PATH = livePkResour1;
       livePkResour[11] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("PK_SMALL_WINDOW_SCORE_PANEL_SCORE_EQUAL_BACKUP_PATH", 12, "PK_SMALL_WINDOW_SCORE_PANEL_SCORE_EQUAL_BACKUP_PATH", "/udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_small_window_score_panel_score_equal_icon.webp");
       LivePkResourcePathConstant.PK_SMALL_WINDOW_SCORE_PANEL_SCORE_EQUAL_BACKUP_PATH = livePkResour1;
       livePkResour[12] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("PK_SMALL_TALK_ICON_BACKUP_PATH", 13, "PK_SMALL_TALK_ICON_BACKUP_PATH", "/udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_small_talk.png");
       LivePkResourcePathConstant.PK_SMALL_TALK_ICON_BACKUP_PATH = livePkResour1;
       livePkResour[13] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_TIE_BACKUP_PATH", 14, "LIVE_PK_TIE_BACKUP_PATH", "/udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_tie_backup.webp");
       LivePkResourcePathConstant.LIVE_PK_TIE_BACKUP_PATH = livePkResour1;
       livePkResour[14] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_WIN_BACKUP_PATH", 15, "LIVE_PK_WIN_BACKUP_PATH", "/udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_win_backup.png");
       LivePkResourcePathConstant.LIVE_PK_WIN_BACKUP_PATH = livePkResour1;
       livePkResour[15] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_WIN_NORMAL_BACKUP_PATH", 16, "LIVE_PK_WIN_NORMAL_BACKUP_PATH", "/udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_win_normal_backup.webp");
       LivePkResourcePathConstant.LIVE_PK_WIN_NORMAL_BACKUP_PATH = livePkResour1;
       livePkResour[16] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_THREE_OUT_OF_FIVE_BACKGROUD_BACKUP_PATH", 17, "LIVE_PK_THREE_OUT_OF_FIVE_BACKGROUD_BACKUP_PATH", "udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_three_out_of_five_backgroud_backup.png");
       LivePkResourcePathConstant.LIVE_PK_THREE_OUT_OF_FIVE_BACKGROUD_BACKUP_PATH = livePkResour1;
       livePkResour[17] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_GIFT_MOMENT_BACKUP_ANIM_PATH", 18, "LIVE_PK_GIFT_MOMENT_LOTTIE_BACKUP_PATH", "udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_gift_moment_backup_anim.webp");
       LivePkResourcePathConstant.LIVE_PK_GIFT_MOMENT_BACKUP_ANIM_PATH = livePkResour1;
       livePkResour[18] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_TIE_BACKUP_V2_PATH", 19, "LIVE_PK_TIE_BACKUP_V2_PATH", "udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_tie_backup_v2.webp");
       LivePkResourcePathConstant.LIVE_PK_TIE_BACKUP_V2_PATH = livePkResour1;
       livePkResour[19] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_TWO_OUT_OF_THREE_BACKGROUND_BACKUP_PATH", 20, "LIVE_PK_TWO_OUT_OF_THREE_BACKGROUND_BACKUP_PATH", "udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_two_out_of_three_background_backup.png");
       LivePkResourcePathConstant.LIVE_PK_TWO_OUT_OF_THREE_BACKGROUND_BACKUP_PATH = livePkResour1;
       livePkResour[20] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_FIRST_BLOOD_APPEAR_BACKUP_ANIM_PATH", 21, "LIVE_PK_FIRST_BLOOD_APPEAR_BACKUP_ANIM_PATH", "udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_first_blood_appear_backup_anim.webp");
       LivePkResourcePathConstant.LIVE_PK_FIRST_BLOOD_APPEAR_BACKUP_ANIM_PATH = livePkResour1;
       livePkResour[21] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_LIVE_KUAFANGPK_PATH", 22, "LIVE_LIVE_KUAFANGPK_PATH", "udata/pkg/kwai-client-image/pk_revenue_pk/live_live_kuafangpk.png");
       LivePkResourcePathConstant.LIVE_LIVE_KUAFANGPK_PATH = livePkResour1;
       livePkResour[22] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_START_VS_BACKUP_PATH", 23, "LIVE_PK_START_VS_BACKUP_PATH", "udata/pkg/kwai-client-image/pk_revenue_pk/live_team_pk_start_vs.webp");
       LivePkResourcePathConstant.LIVE_PK_START_VS_BACKUP_PATH = livePkResour1;
       livePkResour[23] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_WIN_BACKUP_V2_PATH", 24, "LIVE_PK_WIN_BACKUP_V2_PATH", "udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_win_backup_v2.webp");
       LivePkResourcePathConstant.LIVE_PK_WIN_BACKUP_V2_PATH = livePkResour1;
       livePkResour[24] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_LOSE_BACKUP_V2_PATH", 25, "LIVE_PK_LOSE_BACKUP_V2_PATH", "udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_lose_backup_v2.webp");
       LivePkResourcePathConstant.LIVE_PK_LOSE_BACKUP_V2_PATH = livePkResour1;
       livePkResour[25] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_LOSE_NORMAL_BACKUP_PATH", 26, "LIVE_PK_LOSE_NORMAL_BACKUP_PATH", "udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_lose_normal_backup.webp");
       LivePkResourcePathConstant.LIVE_PK_LOSE_NORMAL_BACKUP_PATH = livePkResour1;
       livePkResour[26] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_TIE_NORMAL_BACKUP_PATH", 27, "LIVE_PK_TIE_NORMAL_BACKUP_PATH", "udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_tie_normal_backup.webp");
       LivePkResourcePathConstant.LIVE_PK_TIE_NORMAL_BACKUP_PATH = livePkResour1;
       livePkResour[27] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_FIRST_BLOOD_TIP_PATH", 28, "LIVE_PK_FIRST_BLOOD_TIP_PATH", "udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_first_blood_tip.webp");
       LivePkResourcePathConstant.LIVE_PK_FIRST_BLOOD_TIP_PATH = livePkResour1;
       livePkResour[28] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_WIN_BACKGROUND_BACKUP_V2_PATH", 29, "LIVE_PK_WIN_BACKGROUND_BACKUP_V2_PATH", "udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_win_background_backup_v2.webp");
       LivePkResourcePathConstant.LIVE_PK_WIN_BACKGROUND_BACKUP_V2_PATH = livePkResour1;
       livePkResour[29] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_LOSE_BACKGROUND_BACKUP_V2_PATH", 30, "LIVE_PK_LOSE_BACKGROUND_BACKUP_V2_PATH", "udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_lose_background_backup_v2.webp");
       LivePkResourcePathConstant.LIVE_PK_LOSE_BACKGROUND_BACKUP_V2_PATH = livePkResour1;
       livePkResour[30] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_TIE_BACKGROUND_BACKUP_V2_PATH", 31, "LIVE_PK_TIE_BACKGROUND_BACKUP_V2_PATH", "udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_tie_background_backup_v2.webp");
       LivePkResourcePathConstant.LIVE_PK_TIE_BACKGROUND_BACKUP_V2_PATH = livePkResour1;
       livePkResour[31] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_START_BACKGROUND_BACKUP_V2_PATH", 32, "LIVE_PK_START_BACKGROUND_BACKUP_V2_PATH", "udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_start_background_backup_v2.webp");
       LivePkResourcePathConstant.LIVE_PK_START_BACKGROUND_BACKUP_V2_PATH = livePkResour1;
       livePkResour[32] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_RANK_SELF_THIRD_PATH", 33, "LIVE_PK_RANK_SELF_THIRD_PATH", "udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_rank_self_third.webp");
       LivePkResourcePathConstant.LIVE_PK_RANK_SELF_THIRD_PATH = livePkResour1;
       livePkResour[33] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_RANK_SELF_SECOND_PATH", 34, "LIVE_PK_RANK_SELF_SECOND_PATH", "udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_rank_self_second.webp");
       LivePkResourcePathConstant.LIVE_PK_RANK_SELF_SECOND_PATH = livePkResour1;
       livePkResour[34] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_RANK_SELF_FIRST_PATH", 35, "LIVE_PK_RANK_SELF_FIRST_PATH", "udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_rank_self_first.webp");
       LivePkResourcePathConstant.LIVE_PK_RANK_SELF_FIRST_PATH = livePkResour1;
       livePkResour[35] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_RANK_OPPONENT_THIRD_PATH", 36, "LIVE_PK_RANK_OPPONENT_THIRD_PATH", "udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_rank_opponent_third.webp");
       LivePkResourcePathConstant.LIVE_PK_RANK_OPPONENT_THIRD_PATH = livePkResour1;
       livePkResour[36] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_RANK_OPPONENT_SECOND_PATH", 37, "LIVE_PK_RANK_OPPONENT_SECOND_PATH", "udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_rank_opponent_second.webp");
       LivePkResourcePathConstant.LIVE_PK_RANK_OPPONENT_SECOND_PATH = livePkResour1;
       livePkResour[37] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_RANK_OPPONENT_FIRST_PATH", 38, "LIVE_PK_RANK_OPPONENT_FIRST_PATH", "udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_rank_opponent_first.webp");
       LivePkResourcePathConstant.LIVE_PK_RANK_OPPONENT_FIRST_PATH = livePkResour1;
       livePkResour[38] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_ICON_PK_HISTORY_FAILURE_PATH", 39, "LIVE_ICON_PK_HISTORY_FAILURE_PATH", "udata/pkg/kwai-client-image/pk_revenue_pk/live_icon_pk_history_failure.webp");
       LivePkResourcePathConstant.LIVE_ICON_PK_HISTORY_FAILURE_PATH = livePkResour1;
       livePkResour[39] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_ICON_PK_HISTORY_VICTORY_PATH", 40, "LIVE_ICON_PK_HISTORY_VICTORY_PATH", "udata/pkg/kwai-client-image/pk_revenue_pk/live_icon_pk_history_victory.webp");
       LivePkResourcePathConstant.LIVE_ICON_PK_HISTORY_VICTORY_PATH = livePkResour1;
       livePkResour[40] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_ICON_PK_HISTORY_DRAW_PATH", 41, "LIVE_ICON_PK_HISTORY_DRAW_PATH", "udata/pkg/kwai-client-image/pk_revenue_pk/live_icon_pk_history_draw.webp");
       LivePkResourcePathConstant.LIVE_ICON_PK_HISTORY_DRAW_PATH = livePkResour1;
       livePkResour[41] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_ICON_PK_HISTORY_LINE_PATH", 42, "LIVE_ICON_PK_HISTORY_LINE_PATH", "udata/pkg/kwai-client-image/pk_revenue_pk/live_icon_pk_history_line.webp");
       LivePkResourcePathConstant.LIVE_ICON_PK_HISTORY_LINE_PATH = livePkResour1;
       livePkResour[42] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("VOICE_PARTY_CROSS_ROOM_PK_INVITATION_WAITING_DIALOG_TEAM_INFO_BG_PATH", 43, "VOICE_PARTY_CROSS_ROOM_PK_INVITATION_WAITING_DIALOG_TEAM_INFO_BG_PATH", "udata/pkg/kwai-client-image/pk_revenue_pk/voice_party_cross_room_pk_invitation_waiting_dialog_team_info_bg.webp");
       LivePkResourcePathConstant.VOICE_PARTY_CROSS_ROOM_PK_INVITATION_WAITING_DIALOG_TEAM_INFO_BG_PATH = livePkResour1;
       livePkResour[43] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_LIVE_PKYELLOWTEAM_PATH", 44, "LIVE_LIVE_PKYELLOWTEAM_PATH", "udata/pkg/kwai-client-image/pk_revenue_pk/live_live_pkyellowteam.png");
       LivePkResourcePathConstant.LIVE_LIVE_PKYELLOWTEAM_PATH = livePkResour1;
       livePkResour[44] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_LIVE_PKBLUETEAM_PATH", 45, "LIVE_LIVE_PKBLUETEAM_PATH", "udata/pkg/kwai-client-image/pk_revenue_pk/live_live_pkblueteam.png");
       LivePkResourcePathConstant.LIVE_LIVE_PKBLUETEAM_PATH = livePkResour1;
       livePkResour[45] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_SIGN_ICON_PK_WINNING_FLAG_PATH", 46, "LIVE_SIGN_ICON_PK_WINNING_FLAG_PATH", "udata/pkg/kwai-client-image/pk_revenue_pk/live_sign_icon_pk_winning_flag.webp");
       LivePkResourcePathConstant.LIVE_SIGN_ICON_PK_WINNING_FLAG_PATH = livePkResour1;
       livePkResour[46] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_COMMENT_NOTICE_PK_GIFT_PROMPT_BACKGROUND_BACKUP_PATH", 47, "LIVE_COMMENT_NOTICE_PK_GIFT_PROMPT_BACKGROUND_BACKUP_PATH", "udata/pkg/kwai-client-image/pk_revenue_pk/live_comment_notice_pk_gift_prompt_background_backup.webp");
       LivePkResourcePathConstant.LIVE_COMMENT_NOTICE_PK_GIFT_PROMPT_BACKGROUND_BACKUP_PATH = livePkResour1;
       livePkResour[47] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_CHANGE_FORMAT_MODE_1_FOREGROUND_PATH", 48, "LIVE_PK_CHANGE_FORMAT_MODE_1_FOREGROUND_PATH", "udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_change_format_mode_1_foreground.webp");
       LivePkResourcePathConstant.LIVE_PK_CHANGE_FORMAT_MODE_1_FOREGROUND_PATH = livePkResour1;
       livePkResour[48] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_CHANGE_FORMAT_MODE_2_FOREGROUND_PATH", 49, "LIVE_PK_CHANGE_FORMAT_MODE_2_FOREGROUND_PATH", "udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_change_format_mode_2_foreground.webp");
       LivePkResourcePathConstant.LIVE_PK_CHANGE_FORMAT_MODE_2_FOREGROUND_PATH = livePkResour1;
       livePkResour[49] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_CHANGE_FORMAT_MODE_2_PATH", 50, "LIVE_PK_CHANGE_FORMAT_MODE_2_PATH", "udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_change_format_mode_2.webp");
       LivePkResourcePathConstant.LIVE_PK_CHANGE_FORMAT_MODE_2_PATH = livePkResour1;
       livePkResour[50] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_CHANGE_FORMAT_MODE_1_PATH", 51, "LIVE_PK_CHANGE_FORMAT_MODE_1_PATH", "udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_change_format_mode_1.webp");
       LivePkResourcePathConstant.LIVE_PK_CHANGE_FORMAT_MODE_1_PATH = livePkResour1;
       livePkResour[51] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_RANK_OPPONENT_EMPTY_PATH", 52, "LIVE_PK_RANK_OPPONENT_EMPTY_PATH", "udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_rank_opponent_empty.webp");
       LivePkResourcePathConstant.LIVE_PK_RANK_OPPONENT_EMPTY_PATH = livePkResour1;
       livePkResour[52] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_RANK_SELF_EMPTY_PATH", 53, "LIVE_PK_RANK_SELF_EMPTY_PATH", "udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_rank_self_empty.webp");
       LivePkResourcePathConstant.LIVE_PK_RANK_SELF_EMPTY_PATH = livePkResour1;
       livePkResour[53] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_RANK_FIRST_PATH", 54, "LIVE_PK_RANK_FIRST_PATH", "udata/pkg/kwai-client-image/live_pk_avatar_first.png");
       LivePkResourcePathConstant.LIVE_PK_RANK_FIRST_PATH = livePkResour1;
       livePkResour[54] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_RANK_SECOND_PATH", 55, "LIVE_PK_RANK_SECOND_PATH", "udata/pkg/kwai-client-image/live_pk_avatar_second.png");
       LivePkResourcePathConstant.LIVE_PK_RANK_SECOND_PATH = livePkResour1;
       livePkResour[55] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_RANK_THIRD_PATH", 56, "LIVE_PK_RANK_THIRD_PATH", "udata/pkg/kwai-client-image/live_pk_avatar_third.png");
       LivePkResourcePathConstant.LIVE_PK_RANK_THIRD_PATH = livePkResour1;
       livePkResour[56] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_BG_CONNECTING_PATH", 57, "LIVE_PK_BG_CONNECTING_PATH", "udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_bg_connecting.webp");
       LivePkResourcePathConstant.LIVE_PK_BG_CONNECTING_PATH = livePkResour1;
       livePkResour[57] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_ANCHOR_PK_INVITE_AVATAR_RING_PATH", 58, "LIVE_ANCHOR_PK_INVITE_AVATAR_RING_PATH", "udata/pkg/kwai-client-image/pk_revenue_pk/live_anchor_pk_invite_avatar_ring.json");
       LivePkResourcePathConstant.LIVE_ANCHOR_PK_INVITE_AVATAR_RING_PATH = livePkResour1;
       livePkResour[58] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_ANCHOR_PK_RANDOM_MATCH_AVATAR_RING_PATH", 59, "LIVE_ANCHOR_PK_RANDOM_MATCH_AVATAR_RING_PATH", "udata/pkg/kwai-client-image/pk_revenue_pk/live_anchor_pk_random_match_avatar_ring.json");
       LivePkResourcePathConstant.LIVE_ANCHOR_PK_RANDOM_MATCH_AVATAR_RING_PATH = livePkResour1;
       livePkResour[59] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_VALUE_DAILY_STATISTIC_TITLE_PATH", 60, "LIVE_PK_VALUE_DAILY_STATISTIC_TITLE_PATH", "udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_value_daily_statistic_title.webp");
       LivePkResourcePathConstant.LIVE_PK_VALUE_DAILY_STATISTIC_TITLE_PATH = livePkResour1;
       livePkResour[60] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_RECEIVE_INVITE_PROTECTION_FEE_TIP_BACKGROUND_ICON_PATH", 61, "LIVE_PK_RECEIVE_INVITE_PROTECTION_FEE_TIP_BACKGROUND_ICON_PATH", "udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_receive_invite_protection_fee_tip_background_icon.webp");
       LivePkResourcePathConstant.LIVE_PK_RECEIVE_INVITE_PROTECTION_FEE_TIP_BACKGROUND_ICON_PATH = livePkResour1;
       livePkResour[61] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_MASK_RIPPLE_PATH", 62, "LIVE_PK_MASK_RIPPLE_PATH", "udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_mask_ripple.json");
       LivePkResourcePathConstant.LIVE_PK_MASK_RIPPLE_PATH = livePkResour1;
       livePkResour[62] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_LIVE_PKNARROW_PATH", 63, "LIVE_LIVE_PKNARROW_PATH", "udata/pkg/kwai-client-image/live_live_pknarrow_40.png");
       LivePkResourcePathConstant.LIVE_LIVE_PKNARROW_PATH = livePkResour1;
       livePkResour[63] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_VOICE_PARTY_CROSS_ROOM_PK_INVITATION_WAITING_DIALOG_TEAM_INFO_BG_PATH", 64, "LIVE_PK_VOICE_PARTY_CROSS_ROOM_PK_INVITATION_WAITING_DIALOG_TEAM_INFO_BG_PATH", "udata/pkg/kwai-client-image/pk_revenue_pk/invitation_waiting_dialog_team_info_bg_new.png");
       LivePkResourcePathConstant.LIVE_PK_VOICE_PARTY_CROSS_ROOM_PK_INVITATION_WAITING_DIALOG_TEAM_INFO_BG_PATH = livePkResour1;
       livePkResour[64] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_VOICE_PARTY_CROSS_ROOM_PK_START_ANIM_PATH", 65, "LIVE_VOICE_PARTY_CROSS_ROOM_PK_START_ANIM_PATH", "udata/pkg/kwai-client-image/pk_revenue_pk/cross_room_pk_start_anim.webp");
       LivePkResourcePathConstant.LIVE_VOICE_PARTY_CROSS_ROOM_PK_START_ANIM_PATH = livePkResour1;
       livePkResour[65] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_VOICE_PARTY_CROSS_ROOM_COUNT_DOWN_LEFT_ICON", 66, "LIVE_VOICE_PARTY_CROSS_ROOM_COUNT_DOWN_LEFT_ICON", "udata/pkg/kwai-client-image/live_pk_icon_battle.png");
       LivePkResourcePathConstant.LIVE_VOICE_PARTY_CROSS_ROOM_COUNT_DOWN_LEFT_ICON = livePkResour1;
       livePkResour[66] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_CHOOSE_FRIENDS_ITEM_WARNING_ICON_NEW_PATH", 67, "LIVE_PK_CHOOSE_FRIENDS_ITEM_WARNING_ICON_NEW_PATH", "udata/pkg/kwai-client-image/pk_revenue_pk/live_pk_choose_friends_item_warning_icon_new.webp");
       LivePkResourcePathConstant.LIVE_PK_CHOOSE_FRIENDS_ITEM_WARNING_ICON_NEW_PATH = livePkResour1;
       livePkResour[67] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_GIFT_MOMENT_RULE_BACKUP", 68, "LIVE_PK_GIFT_MOMENT_RULE_BACKUP", "udata/pkg/kwai-client-image/live_revenue_gift/live_pk_gift_moment_rule_backup.webp");
       LivePkResourcePathConstant.LIVE_PK_GIFT_MOMENT_RULE_BACKUP = livePkResour1;
       livePkResour[68] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_LIVE_RECOMMENDEDGIFTS_CRITICALHIT02", 69, "LIVE_LIVE_RECOMMENDEDGIFTS_CRITICALHIT02", "udata/pkg/kwai-client-image/live_revenue_gift/live_live_recommendedgifts_criticalhit02.webp");
       LivePkResourcePathConstant.LIVE_LIVE_RECOMMENDEDGIFTS_CRITICALHIT02 = livePkResour1;
       livePkResour[69] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_LIVE_RECOMMENDEDGIFTS_STEALTOWER02", 70, "LIVE_LIVE_RECOMMENDEDGIFTS_STEALTOWER02", "udata/pkg/kwai-client-image/live_revenue_gift/live_live_recommendedgifts_stealtower02.webp");
       LivePkResourcePathConstant.LIVE_LIVE_RECOMMENDEDGIFTS_STEALTOWER02 = livePkResour1;
       livePkResour[70] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_LIVE_RECOMMENDEDGIFTS_CRITICALHIT01", 71, "LIVE_LIVE_RECOMMENDEDGIFTS_CRITICALHIT01", "udata/pkg/kwai-client-image/live_revenue_gift/live_live_recommendedgifts_criticalhit01.webp");
       LivePkResourcePathConstant.LIVE_LIVE_RECOMMENDEDGIFTS_CRITICALHIT01 = livePkResour1;
       livePkResour[71] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_LIVE_RECOMMENDEDGIFTS_STEALTOWER01", 72, "LIVE_LIVE_RECOMMENDEDGIFTS_STEALTOWER01", "udata/pkg/kwai-client-image/live_revenue_gift/live_live_recommendedgifts_stealtower01.webp");
       LivePkResourcePathConstant.LIVE_LIVE_RECOMMENDEDGIFTS_STEALTOWER01 = livePkResour1;
       livePkResour[72] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_COMMENT_NOTICE_PK_GIFT_PROMPT_BACKGROUND_BACKUP", 73, "LIVE_COMMENT_NOTICE_PK_GIFT_PROMPT_BACKGROUND_BACKUP", "udata/pkg/kwai-client-image/live_revenue_gift/live_comment_notice_pk_gift_prompt_background_backup.webp");
       LivePkResourcePathConstant.LIVE_COMMENT_NOTICE_PK_GIFT_PROMPT_BACKGROUND_BACKUP = livePkResour1;
       livePkResour[73] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_SELLING_SETTING_MORE", 74, "LIVE_PK_SELLING_SETTING_MORE", "/udata/pkg/kwai-client-image/live_pk/live_pk_selling_setting_more.png");
       LivePkResourcePathConstant.LIVE_PK_SELLING_SETTING_MORE = livePkResour1;
       livePkResour[74] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("LIVE_PK_PANEL_RANDOM_PK_BANNER_BG", 75, "LIVE_PK_PANEL_RANDOM_PK_BANNER_BG", "/udata/pkg/kwai-client-image/pk/pk_match_banner2.aa40d58ccdbf3da0.png");
       LivePkResourcePathConstant.LIVE_PK_PANEL_RANDOM_PK_BANNER_BG = livePkResour1;
       livePkResour[75] = livePkResour1;
       livePkResour1 = new LivePkResourcePathConstant("COHESION_PK", 76, "LIVE_PK_COHESION_PK", "/udata/pkg/kwai-client-image/pk_revenue_pk/live_cohesion_pk_score_board_text_icon.png");
       LivePkResourcePathConstant.COHESION_PK = livePkResour1;
       livePkResour[76] = livePkResour1;
       LivePkResourcePathConstant.$VALUES = livePkResour;
    }
    public void LivePkResourcePathConstant(String p0,int p1,String p2,String p3){
       super(p0, p1);
       this.resourceName = p2;
       this.resourcePath = p3;
    }
    public static LivePkResourcePathConstant valueOf(String p0){
       Object obj = PatchProxy.applyOneRefs(p0, null, LivePkResourcePathConstant.class, "2");
       if (obj != PatchProxyResult.class) {
          return obj;
       }
       return Enum.valueOf(LivePkResourcePathConstant.class, p0);
    }
    public static LivePkResourcePathConstant[] values(){
       Object obj = PatchProxy.apply(null, null, LivePkResourcePathConstant.class, "1");
       if (obj != PatchProxyResult.class) {
          return obj;
       }
       return LivePkResourcePathConstant.$VALUES.clone();
    }
    public String getResourceName(){
       return this.resourceName;
    }
    public String getResourcePath(){
       return this.resourcePath;
    }
}
