package com.kuaishou.webkit.WebViewProvider;
import java.lang.Object;
import java.lang.String;
import android.graphics.Picture;
import com.kuaishou.webkit.WebView$CapturePictureAsyncCallback;
import com.kuaishou.webkit.WebBackForwardList;
import android.print.PrintDocumentAdapter;
import com.kuaishou.webkit.WebMessagePort;
import android.os.Message;
import java.io.BufferedWriter;
import com.kuaishou.webkit.ValueCallback;
import com.kuaishou.webkit.extension.jscore.PackageFile$EvaluateCallback;
import android.view.View;
import android.net.http.SslCertificate;
import android.graphics.Bitmap;
import com.kuaishou.webkit.WebView$HitTestResult;
import com.kuaishou.webkit.extension.KsWebViewClient;
import android.os.Bundle;
import com.kuaishou.webkit.WebViewProvider$ScrollDelegate;
import com.kuaishou.webkit.WebSettings;
import com.kuaishou.webkit.WebViewProvider$ViewDelegate;
import com.kuaishou.webkit.WebChromeClient;
import com.kuaishou.webkit.WebViewClient;
import com.kuaishou.webkit.WebViewRenderProcess;
import com.kuaishou.webkit.WebViewRenderProcessClient;
import java.util.Map;
import com.kuaishou.webkit.WebView$VisualStateCallback;
import com.kuaishou.webkit.WebMessage;
import android.net.Uri;
import java.io.File;
import com.kuaishou.webkit.DownloadListener;
import com.kuaishou.webkit.WebView$FindListener;
import com.kuaishou.webkit.WebView$PictureListener;
import java.util.concurrent.Executor;

public interface abstract WebViewProvider	// class@00129f
{

    void addJavascriptInterface(Object p0,String p1);
    boolean canGoBack();
    boolean canGoBackOrForward(int p0);
    boolean canGoForward();
    boolean canZoomIn();
    boolean canZoomOut();
    Picture capturePicture();
    boolean capturePictureAsync(WebView$CapturePictureAsyncCallback p0);
    void clearCache(boolean p0);
    void clearFormData();
    void clearHistory();
    void clearMatches();
    void clearSslPreferences();
    void clearView();
    void compileJsAndGenCodeCache(String p0,byte[] p1,String p2);
    WebBackForwardList copyBackForwardList();
    PrintDocumentAdapter createPrintDocumentAdapter(String p0);
    WebMessagePort[] createWebMessageChannel();
    void destroy();
    void documentHasImages(Message p0);
    void dumpViewHierarchyWithProperties(BufferedWriter p0,int p1);
    void evaluateJavaScript(String p0,ValueCallback p1);
    void evaluateJsList(long p0,String[] p1,boolean p2);
    void evaluateJsList(long p0,String[] p1,boolean p2,PackageFile$EvaluateCallback[] p3);
    int findAll(String p0);
    void findAllAsync(String p0);
    View findHierarchyView(String p0,int p1);
    void findNext(boolean p0);
    void flingScroll(int p0,int p1);
    void freeMemory();
    SslCertificate getCertificate();
    int getContentHeight();
    int getContentWidth();
    Bitmap getFavicon();
    WebView$HitTestResult getHitTestResult();
    String[] getHttpAuthUsernamePassword(String p0,String p1);
    KsWebViewClient getKsWebViewClient();
    Object getMiscObject(int p0);
    Object getMiscObjectWithArgs(int p0,Bundle p1,Object p2);
    String getOriginalUrl();
    int getProgress();
    boolean getRendererPriorityWaivedWhenNotVisible();
    int getRendererRequestedPriority();
    float getScale();
    WebViewProvider$ScrollDelegate getScrollDelegate();
    int getScrollX();
    int getScrollY();
    WebSettings getSettings();
    Object getTextClassifier();
    String getTitle();
    String getTouchIconUrl();
    String getUrl();
    WebViewProvider$ViewDelegate getViewDelegate();
    int getVisibleTitleHeight();
    WebChromeClient getWebChromeClient();
    WebViewClient getWebViewClient();
    WebViewRenderProcess getWebViewRenderProcess();
    WebViewRenderProcessClient getWebViewRenderProcessClient();
    View getZoomControls();
    void goBack();
    void goBackOrForward(int p0);
    void goForward();
    void init(Map p0,boolean p1);
    void insertVisualStateCallback(long p0,WebView$VisualStateCallback p1);
    void invokeZoomPicker();
    boolean isPaused();
    boolean isPrivateBrowsingEnabled();
    void loadData(String p0,String p1,String p2);
    void loadDataFromKsWebView(String p0,String p1,String p2);
    void loadDataWithBaseURL(String p0,String p1,String p2,String p3,String p4);
    void loadDataWithBaseURLFromKsWebView(String p0,String p1,String p2,String p3,String p4);
    void loadUrl(String p0);
    void loadUrl(String p0,Map p1);
    void notifyFindDialogDismissed();
    void onPause();
    void onResume();
    boolean overScrollBy(int p0,int p1,int p2,int p3,int p4,int p5,int p6,int p7,boolean p8);
    boolean overlayHorizontalScrollbar();
    boolean overlayVerticalScrollbar();
    boolean pageDown(boolean p0);
    boolean pageUp(boolean p0);
    void pauseTimers();
    void postMessageToMainFrame(WebMessage p0,Uri p1);
    void postUrl(String p0,byte[] p1);
    void reload();
    void removeJavascriptInterface(String p0);
    void requestFocusNodeHref(Message p0);
    void requestImageRef(Message p0);
    boolean restorePicture(Bundle p0,File p1);
    WebBackForwardList restoreState(Bundle p0);
    void resumeTimers();
    void savePassword(String p0,String p1,String p2);
    boolean savePicture(Bundle p0,File p1);
    WebBackForwardList saveState(Bundle p0);
    void saveWebArchive(String p0);
    void saveWebArchive(String p0,boolean p1,ValueCallback p2);
    void scrollBy(int p0,int p1);
    void scrollTo(int p0,int p1);
    void setCertificate(SslCertificate p0);
    void setDownloadListener(DownloadListener p0);
    void setFindListener(WebView$FindListener p0);
    void setHorizontalScrollbarOverlay(boolean p0);
    void setHttpAuthUsernamePassword(String p0,String p1,String p2,String p3);
    void setInitialScale(int p0);
    void setKsWebViewClient(KsWebViewClient p0);
    void setMapTrackballToArrowKeys(boolean p0);
    boolean setMiscBoolean(int p0,boolean p1);
    boolean setMiscBundle(int p0,Bundle p1);
    boolean setMiscInt(int p0,int p1);
    boolean setMiscMessage(Message p0);
    boolean setMiscObject(int p0,Object p1);
    boolean setMiscString(int p0,String p1);
    void setNetworkAvailable(boolean p0);
    void setPictureListener(WebView$PictureListener p0);
    void setRendererPriorityPolicy(int p0,boolean p1);
    void setTextClassifier(Object p0);
    void setVerticalScrollbarOverlay(boolean p0);
    void setWebChromeClient(WebChromeClient p0);
    void setWebViewClient(WebViewClient p0);
    void setWebViewRenderProcessClient(Executor p0,WebViewRenderProcessClient p1);
    boolean showFindDialog(String p0,boolean p1);
    void stopLoading();
    boolean zoomBy(float p0);
    boolean zoomIn();
    boolean zoomOut();
}
