package com.kuaishou.webkit.WebViewProvider$ViewDelegate;
import android.util.SparseArray;
import android.view.KeyEvent;
import android.view.View;
import android.view.accessibility.AccessibilityNodeProvider;
import android.os.Handler;
import android.content.Intent;
import android.content.res.Configuration;
import android.view.inputmethod.EditorInfo;
import android.view.inputmethod.InputConnection;
import android.view.DragEvent;
import android.graphics.Canvas;
import android.graphics.drawable.Drawable;
import android.graphics.Rect;
import android.view.MotionEvent;
import android.view.accessibility.AccessibilityEvent;
import android.view.accessibility.AccessibilityNodeInfo;
import java.lang.Object;
import android.os.Bundle;
import android.graphics.Paint;
import android.view.ViewGroup$LayoutParams;

public interface abstract WebViewProvider$ViewDelegate	// class@00129e
{

    void autofill(SparseArray p0);
    boolean dispatchKeyEvent(KeyEvent p0);
    View findFocus(View p0);
    AccessibilityNodeProvider getAccessibilityNodeProvider();
    Handler getHandler(Handler p0);
    boolean isVisibleToUserForAutofill(int p0);
    void onActivityResult(int p0,int p1,Intent p2);
    void onAttachedToWindow();
    boolean onCheckIsTextEditor();
    void onConfigurationChanged(Configuration p0);
    InputConnection onCreateInputConnection(EditorInfo p0);
    void onDetachedFromWindow();
    boolean onDragEvent(DragEvent p0);
    void onDraw(Canvas p0);
    void onDrawVerticalScrollBar(Canvas p0,Drawable p1,int p2,int p3,int p4,int p5);
    void onFinishTemporaryDetach();
    void onFocusChanged(boolean p0,int p1,Rect p2);
    boolean onGenericMotionEvent(MotionEvent p0);
    boolean onHoverEvent(MotionEvent p0);
    void onInitializeAccessibilityEvent(AccessibilityEvent p0);
    void onInitializeAccessibilityNodeInfo(AccessibilityNodeInfo p0);
    boolean onKeyDown(int p0,KeyEvent p1);
    boolean onKeyMultiple(int p0,int p1,KeyEvent p2);
    boolean onKeyUp(int p0,KeyEvent p1);
    void onMeasure(int p0,int p1);
    void onMovedToDisplay(int p0,Configuration p1);
    void onOverScrolled(int p0,int p1,boolean p2,boolean p3);
    void onProvideAutofillVirtualStructure(Object p0,int p1);
    void onProvideContentCaptureStructure(Object p0,int p1);
    void onProvideVirtualStructure(Object p0);
    void onScrollChanged(int p0,int p1,int p2,int p3);
    void onSizeChanged(int p0,int p1,int p2,int p3);
    void onStartTemporaryDetach();
    boolean onTouchEvent(MotionEvent p0);
    boolean onTrackballEvent(MotionEvent p0);
    void onVisibilityChanged(View p0,int p1);
    void onWindowFocusChanged(boolean p0);
    void onWindowVisibilityChanged(int p0);
    boolean performAccessibilityAction(int p0,Bundle p1);
    boolean performLongClick();
    void preDispatchDraw(Canvas p0);
    boolean requestChildRectangleOnScreen(View p0,Rect p1,boolean p2);
    boolean requestFocus(int p0,Rect p1);
    void setBackgroundColor(int p0);
    boolean setFrame(int p0,int p1,int p2,int p3);
    void setLayerType(int p0,Paint p1);
    void setLayoutParams(ViewGroup$LayoutParams p0);
    void setOverScrollMode(int p0);
    void setScrollBarStyle(int p0);
    boolean shouldDelayChildPressedState();
}
