package com.kwai.video.waynelive.ILivePlayerStatusMonitor;
import com.kwai.video.waynelive.listeners.LivePlayerBufferListener;
import com.kwai.video.waynelive.listeners.LivePlayerKwaivppListener;
import com.kwai.video.waynelive.listeners.LivePlayerEventListener;
import com.kwai.video.player.IKwaiMediaPlayer$OnLiveExtraInfoListener;
import com.kwai.video.player.IKwaiMediaPlayer$OnLiveInterActiveListener;
import com.kwai.video.waynelive.listeners.LivePlayerErrorListener;
import com.kwai.video.waynelive.listeners.LivePlayerTypeChangeListener;
import com.kwai.video.player.IKwaiMediaPlayer$OnLiveSeiInfoListener;
import com.kwai.video.waynelive.datasource.LiveUrlSwitchListener;
import com.kwai.video.waynelive.listeners.LivePlayerOnAudioProcessPCMAvailableListener;
import com.kwai.video.waynelive.listeners.LivePlayerCompleteListener;
import com.kwai.video.player.IKwaiMediaPlayer$OnLiveSrvTsptInfoListener;
import com.kwai.video.waynelive.listeners.LivePlayerRenderAfterBufferStartListener;
import com.kwai.video.player.IMediaPlayer$OnVideoSizeChangedListener;
import com.kwai.video.waynelive.qosmoniter.LivePlayerQosListener;
import com.kwai.video.waynelive.quality.LiveQualityChangeListener;
import com.kwai.video.waynelive.listeners.LivePlayerRenderListener;
import com.kwai.video.waynelive.listeners.LivePlayerStateChangeListener;
import com.kwai.video.cache.AwesomeCacheCallback;
import com.kwai.video.waynelive.listeners.LivePlayerQosLogListener;
import com.kwai.video.player.IMediaPlayer$OnLiveVoiceCommentListener;

public interface abstract ILivePlayerStatusMonitor	// class@000dc7
{

    void addBufferListener(LivePlayerBufferListener p0);
    void addKwaivppListener(LivePlayerKwaivppListener p0);
    void addLiveEventListener(LivePlayerEventListener p0);
    void addLiveExtraListener(IKwaiMediaPlayer$OnLiveExtraInfoListener p0);
    void addLiveInterActiveTsptListener(IKwaiMediaPlayer$OnLiveInterActiveListener p0);
    void addLivePlayerErrorListener(LivePlayerErrorListener p0);
    void addLivePlayerTypeChangeListener(LivePlayerTypeChangeListener p0);
    void addLiveSeiListener(IKwaiMediaPlayer$OnLiveSeiInfoListener p0);
    void addLiveUrlSwitchListener(LiveUrlSwitchListener p0);
    void addOnAudioProcessPCMAvailableListener(LivePlayerOnAudioProcessPCMAvailableListener p0);
    void addOnCompletionListener(LivePlayerCompleteListener p0);
    void addOnLiveSrvTsptInfoListener(IKwaiMediaPlayer$OnLiveSrvTsptInfoListener p0);
    void addOnVideoRendingStartAfterBufferingListener(LivePlayerRenderAfterBufferStartListener p0);
    void addOnVideoSizeChangedListener(IMediaPlayer$OnVideoSizeChangedListener p0);
    void addQosMonitorListener(LivePlayerQosListener p0);
    void addQualityChangeListener(LiveQualityChangeListener p0);
    void addRenderListener(LivePlayerRenderListener p0);
    void addStateChangeListener(LivePlayerStateChangeListener p0);
    void clearAllListener();
    void removeBufferListener(LivePlayerBufferListener p0);
    void removeKwaivppListener(LivePlayerKwaivppListener p0);
    void removeLiveEventListener(LivePlayerEventListener p0);
    void removeLiveExtraListener(IKwaiMediaPlayer$OnLiveExtraInfoListener p0);
    void removeLiveInterActiveTsptListener(IKwaiMediaPlayer$OnLiveInterActiveListener p0);
    void removeLivePlayerErrorListener(LivePlayerErrorListener p0);
    void removeLivePlayerTypeChangeListener(LivePlayerTypeChangeListener p0);
    void removeLiveSeiListener(IKwaiMediaPlayer$OnLiveSeiInfoListener p0);
    void removeLiveUrlSwitchListener(LiveUrlSwitchListener p0);
    void removeOnAudioProcessPCMAvailableListener(LivePlayerOnAudioProcessPCMAvailableListener p0);
    void removeOnCompletionListener(LivePlayerCompleteListener p0);
    void removeOnLiveSrvTsptInfoListener(IKwaiMediaPlayer$OnLiveSrvTsptInfoListener p0);
    void removeOnVideoRendingStartAfterBufferingListener(LivePlayerRenderAfterBufferStartListener p0);
    void removeOnVideoSizeChangedListener(IMediaPlayer$OnVideoSizeChangedListener p0);
    void removeQosMonitorListener(LivePlayerQosListener p0);
    void removeQualityChangeListener(LiveQualityChangeListener p0);
    void removeRenderListener(LivePlayerRenderListener p0);
    void removeStateChangeListener(LivePlayerStateChangeListener p0);
    void setCdnLoggerCallback(AwesomeCacheCallback p0);
    void setLivePlayerQosLogListener(LivePlayerQosLogListener p0);
    void setLiveVoiceCommentListener(IMediaPlayer$OnLiveVoiceCommentListener p0);
}
