package com.kwai.video.waynelive.LivePlayerController;
import com.kwai.video.waynelive.ILivePlayerStatusMonitor;
import com.kwai.video.waynelive.quality.LiveQualityItem;
import com.kwai.video.waynelive.LivePlayUrlInfo;
import java.lang.String;
import com.kwai.video.waynelive.util.SeiExtraData;
import com.kwai.video.player.IKwaiMediaPlayer;
import java.util.List;
import com.kwai.video.waynelive.cache.LivePlayerCacheType;
import com.kwai.video.waynelive.cache.LivePlayerCacheController;
import com.kwai.video.waynelive.LiveRestartReason;
import com.kwai.player.debuginfo.IDebugView;
import com.kwai.video.waynelive.LivePlayerExtOption;
import android.graphics.SurfaceTexture;
import com.kwai.video.waynelive.datasource.LiveDataSourceFetcher;
import com.kwai.video.waynelive.listeners.OnLiveRtcSpeakerChangedListener;
import com.kwai.video.player.IKwaiMediaPlayer$OnLiveSeiInfoListener;
import com.kwai.video.waynelive.listeners.LivePlayerTypeChangeListener;
import com.kwai.video.waynelive.listeners.QosExtraInterface;
import android.view.Surface;
import com.yxcorp.gifshow.live.widget.LivePlayTextureView;
import com.kwai.video.waynelive.datasource.ILiveDatasource;
import com.kwai.video.waynelive.datasource.LiveDataSource;

public interface abstract LivePlayerController implements ILivePlayerStatusMonitor	// class@000dcf
{

    void destroy();
    int getCurrentLiveManifestRepId();
    LiveQualityItem getCurrentLiveQualityItem();
    int getCurrentLiveStreamType();
    LivePlayUrlInfo getCurrentPlayUrlInfo();
    String getCurrentPlayingUrl();
    long getCurrentVideoPosition();
    long getLastVideoPts();
    byte[] getLatestAACExtraData();
    SeiExtraData getLatestSeiExtraData();
    byte[] getLatestTsptExtraData();
    IKwaiMediaPlayer getLiveMediaPlayer();
    List getLiveQualityList();
    int getPkLiveStreamType();
    SeiExtraData getPkSeiCache();
    long getPlayDuration();
    int getTotalRetryCount();
    int getVideoHeight();
    float getVideoSizeRatio();
    int getVideoWidth();
    boolean isBuffering();
    boolean isDestroyed();
    boolean isEnableReusePlayerOptimize();
    boolean isEnableWebRTCManifest();
    boolean isLiveDataSourceContainsWebRTC();
    boolean isPlayerMute();
    boolean isPlaying();
    boolean isPreparing();
    boolean isSideBySideStream();
    boolean isStop();
    boolean isUsingSurfaceView();
    void mute();
    boolean preInit();
    void prepareForStartAnim();
    void prepareForStopAnim();
    void registerCacheController(LivePlayerCacheType p0,LivePlayerCacheController p1);
    void removeStopPlayToken(String p0);
    void resetRetryCount();
    void restartPlay(LiveRestartReason p0);
    void setDebugView(IDebugView p0);
    void setEnableAutoUpdateViewSize(boolean p0);
    void setEnterTimeForPreload(long p0);
    void setExtOption(LivePlayerExtOption p0,int p1);
    void setExtSurfaceCrop(float p0,float p1,float p2,float p3);
    void setExtSurfaceCrop(int p0,int p1,int p2,int p3);
    void setExtSurfaceTexture(SurfaceTexture p0);
    void setKwaivppExtJson(int p0,String p1);
    void setLiveDataSourceFetcher(LiveDataSourceFetcher p0);
    void setLiveQualityItem(LiveQualityItem p0);
    void setNetworkRetryScene(String p0);
    void setOnLiveRtcSpeakerChangedListener(OnLiveRtcSpeakerChangedListener p0);
    void setPkSeiListener(IKwaiMediaPlayer$OnLiveSeiInfoListener p0);
    void setPkStreamTypeChangeListener(LivePlayerTypeChangeListener p0);
    void setPlayerReleaseReason(int p0);
    void setPriorLowQuality(int p0);
    void setQosExtraData(String p0);
    void setQosExtraInterface(QosExtraInterface p0);
    void setSurface(Surface p0);
    void setTextureView(LivePlayTextureView p0);
    void setTextureView(LivePlayTextureView p0,boolean p1);
    void setTextureView(LivePlayTextureView p0,boolean p1,boolean p2);
    void setViewPixelSize(int p0,int p1);
    void setVolume(float p0,float p1);
    void startAudioOnlyMode();
    void startCache();
    boolean startPlay();
    boolean startPlay(String p0);
    void stopAudioOnlyMode();
    void stopCache();
    void stopPlay();
    void stopPlay(String p0);
    void unMute();
    void updateDataSource(ILiveDatasource p0);
    void updateDataSource(LiveDataSource p0);
    void updateWebRTCParams(boolean p0,String p1);
}
