package com.yxcorp.gifshow.v3.editor.EditorDelegate;
import android.view.View;
import java.lang.Object;
import tyc.b2;
import com.yxcorp.gifshow.v3.EditorItemFunc;
import com.yxcorp.gifshow.v3.customizer.preview.BaseEditorPreviewContainerLayout;
import voc.v;
import mrd.a;
import com.yxcorp.gifshow.edit.draft.model.workspace.c;
import aw9.c0;
import com.yxcorp.gifshow.v3.editor.BaseEditor;
import com.yxcorp.gifshow.v3.editor.EditorDelegate$ShowLoggerType;
import k2b.s$b;
import android.os.Bundle;
import x59.g;
import xvc.f;
import evc.c;
import android.app.Activity;
import android.content.Intent;
import java.lang.String;
import com.kuaishou.edit.draft.Workspace$Type;
import t36.f;
import com.kuaishou.android.model.music.Music;
import yvc.a;
import com.yxcorp.gifshow.recycler.fragment.BaseFragment;
import java.lang.Class;
import androidx.lifecycle.ViewModel;
import java.util.Map;
import android.widget.RelativeLayout;
import voc.o;

public interface abstract EditorDelegate	// class@000d97
{

    int A();
    boolean B();
    View C();
    Object D();
    boolean E();
    b2 F();
    void G(int p0,int p1,int p2,boolean p3,boolean p4);
    EditorItemFunc H();
    int I();
    BaseEditorPreviewContainerLayout J();
    v K(EditorItemFunc p0);
    a L();
    void M(int p0,int p1,int p2,boolean p3);
    c N();
    c0 O();
    BaseEditor P(EditorItemFunc p0);
    void Q(int p0,int p1,int p2,int p3,boolean p4);
    s$b a(EditorDelegate$ShowLoggerType p0);
    void b();
    Bundle c();
    g d();
    void e();
    f f();
    void g(c p0);
    Activity getContext();
    Intent getIntent();
    String getTaskId();
    Workspace$Type getType();
    boolean h();
    void i(EditorItemFunc p0);
    f j();
    void k(Music p0,int p1,String p2);
    void l();
    int m();
    boolean n();
    void o(a p0);
    boolean p();
    BaseFragment q();
    void r();
    ViewModel s(Class p0);
    void t(double p0);
    Map u();
    RelativeLayout v();
    void w();
    o x();
    void y(boolean p0);
    View z();
}
