package bo5.a;
import java.lang.Integer;
import co5.g;
import java.lang.Float;
import java.lang.Boolean;
import zq6.p;
import zq6.m;
import java.lang.String;
import java.lang.Class;
import java.lang.Object;
import zq6.o;
import co5.r;
import gsa.e0;
import co5.d;
import zq6.e;
import com.kwai.robust.PatchProxy;
import com.kwai.robust.PatchProxyResult;
import com.kwai.library.widget.popup.bubble.a$c;
import co5.a;
import jo5.b;
import com.kwai.feature.api.feed.home.kcubehome.top.common.state.TopTabViewType;
import wn5.b;
import co5.i;
import co5.o;
import co5.e;
import co5.n;
import co5.m;
import co5.j;
import co5.p;
import co5.c;
import co5.f;
import co5.l;
import co5.h;
import co5.q;
import com.yxcorp.gifshow.model.FollowTabNotify;
import co5.k;
import co5.b;

public interface abstract a	// class@0004fa
{
    public static final p A;
    public static final p B;
    public static final p C;
    public static final p D;
    public static final p E;
    public static final p F;
    public static final p G;
    public static final p H;
    public static final p I;
    public static final p J;
    public static final p K;
    public static final p L;
    public static final p M;
    public static final p N;
    public static final p a;
    public static final p b;
    public static final p c;
    public static final p d;
    public static final p e;
    public static final p f;
    public static final p g;
    public static final p h;
    public static final p i;
    public static final p j;
    public static final p k;
    public static final p l;
    public static final p m;
    public static final p n;
    public static final p o;
    public static final p p;
    public static final p q;
    public static final p r;
    public static final p s;
    public static final p t;
    public static final p u;
    public static final p v;
    public static final p w;
    public static final p x;
    public static final p y;
    public static final p z;

    static {
       o a;
       Integer integer = Integer.class;
       g og = g.class;
       Float uFloat = Float.class;
       Boolean uBoolean = Boolean.class;
       int i = 0;
       o b = m.b;
       a.a = new p("LOGIN_TEXT_BTN_VISIBILITY", integer, Integer.valueOf(i), b);
       Boolean fALSE = Boolean.FALSE;
       a.b = new p("SEARCH_MOVE_HIDE", uBoolean, fALSE, b);
       a.c = new p("VIEW_PAGER_SCROLLABLE", r.class, new r(true, true), b);
       Boolean tRUE = Boolean.TRUE;
       a.d = new p("TAB_CLICKABLE", uBoolean, tRUE, b);
       a.e = new p("TAB_BAR_VIEW_INFO", e0.class, e0.f0, m.a(new d()));
       a.f = new p("TAB_BAR_SHOW", uBoolean, tRUE, b);
       a.g = new p("TAB_TOP_BAR_STRIP_SHOW", uBoolean, tRUE, b);
       a.h = new p("LIVE_ENTRY_SHOW", uBoolean, tRUE, b);
       Object[] objArray = null;
       g og1 = PatchProxy.apply(objArray, objArray, og, "9");
       if (og1 != PatchProxyResult.class) {
       }else {
          og1 = new g(i, objArray);
       }
       a.i = new p("ACTION_BAR_SEARCH_ENTRY_BUBBLE", og, og1, b);
       a.j = new p("RIGHT_BTN_ALPHA", uFloat, Float.valueOf(0x3f800000), b);
       a.k = new p("RIGHT_BTN_CLICKABLE", uBoolean, tRUE, b);
       a.l = new p("ACTION_BAR_ALPHA", uFloat, Float.valueOf(0x3f800000), m.c);
       a.m = new p("ACTION_BAR_TRANS_Y", uFloat, Float.valueOf(0), b);
       a.n = new p("CLEAR_SCREEN_PROGRESS", uFloat, Float.valueOf(0x3f800000), b);
       a.o = new p("CURRENT_FEED", a.class, a.b, b);
       a = m.a;
       a.p = new p("ACTION_BAR_INFO", b.class, b.a, a);
       a.q = new p("BAR_BACKGROUND_ALPHA", uFloat, Float.valueOf(0x3f800000), b);
       a.r = new p("TAB_VIEW_TYPE", TopTabViewType.class, TopTabViewType.NORMAL, a);
       a.s = new p("TAB_TEXT", b.class, b.b("Unknown"), a);
       a.t = new p("TAB_IMAGE", i.class, a);
       a.u = new p("TAB_TEXT_TYPEFACE", o.class, o.b, a);
       a.v = new p("TAB_VIEW_SUPPORT_DOUBLE_CLICK", uBoolean, fALSE, a);
       a.w = new p("TAB_BUBBLE", og, a);
       a.x = new p("TAB_ANIMATE", e.class, a);
       a.y = new p("TAB_RED_DOT_NOTIFY", n.class, a);
       a.z = new p("TAB_NUMBER_NOTIFY", m.class, a);
       a.A = new p("TAB_IMAGE_NOTIFY", j.class, a);
       a.B = new p("TAB_TRIANGLE_NOTIFY", p.class, a);
       a.C = new p("TAB_TRIANGLE_COLOR", integer, a);
       a.D = new p("TAB_ROTATE_DEGREES", uBoolean, fALSE, a);
       a.E = new p("TAB_TRIANGLE_ALPHA", uFloat, Float.valueOf(0x3f800000), a);
       a.F = new p("TAB_TRIANGLE_ALPHA_WITH_DIRECTION", c.class, a);
       a.G = new p("TAB_AVATAR", f.class, a);
       a.H = new p("TAB_AVATAR_SCALE", uFloat, Float.valueOf(0x3f800000), a);
       a.I = new p("TAB_LOTTIE", l.class, a);
       a.J = new p("TAB_DOUBLE_AVATAR", h.class, a);
       a.K = new p("TAB_TRIPLE_AVATAR", q.class, a);
       a.L = new p("TAB_FOLLOW_NOTIFY", FollowTabNotify.class, a);
       a.M = new p("TAB_IMAGE_TITLE", k.class, a);
       a.N = new p("TabCommonLottie", b.class, a);
    }
}
