package sy6.a;
import android.view.View;
import androidx.fragment.app.Fragment;
import vy6.a;
import com.yxcorp.gifshow.entity.QPhoto;
import java.lang.String;
import java.util.List;
import tw6.c;
import ew6.b;
import qvb.q;
import tw6.e;
import androidx.viewpager.widget.ViewPager$i;
import fw6.c;
import qw6.a;
import java.lang.Object;
import android.database.DataSetObserver;
import com.kwai.library.widget.viewpager.VerticalViewPager;

public interface abstract a	// class@003772
{

    void A(View p0);
    void B(int p0);
    boolean C();
    void D(Fragment p0,a p1);
    void E(a p0);
    void G(QPhoto p0,String p1);
    int G0(int p0);
    boolean H(QPhoto p0);
    boolean I();
    void J(List p0,QPhoto p1,String p2);
    void K(View p0);
    void L(boolean p0);
    int M(QPhoto p0);
    void N(c p0);
    void O(b p0);
    void P(Fragment p0,a p1);
    int Q();
    void R(b p0);
    void S(int p0,List p1,String p2);
    void T(boolean p0);
    void U(int p0,QPhoto p1,String p2);
    String V();
    void W(int p0);
    void X(List p0,String p1);
    void Y(boolean p0);
    int Z();
    int a();
    int a0();
    void b(q p0);
    void b0(List p0,QPhoto p1,String p2);
    int c();
    void c0(e p0);
    void d(boolean p0,int p1);
    void d0(e p0);
    void e(q p0);
    List e0();
    void f(int p0);
    boolean f0(QPhoto p0);
    void g(ViewPager$i p0);
    void g0(a p0);
    QPhoto getCurrentPhoto();
    c getDataSource();
    void h(a p0);
    Object h0();
    void i(ViewPager$i p0);
    List i0();
    int j();
    int j0();
    void k(int p0,boolean p1);
    QPhoto k0(int p0);
    void l(a p0);
    boolean l0();
    void m(int p0,List p1,String p2);
    int m0();
    QPhoto n(int p0);
    boolean n0();
    void o(QPhoto p0,boolean p1,String p2);
    void o0(Fragment p0,a p1);
    void p(boolean p0);
    boolean p0();
    int q(int p0);
    void q0(Fragment p0,a p1);
    boolean r();
    void r0(Fragment p0,a p1);
    void registerDataSetObserver(DataSetObserver p0);
    void s(boolean p0);
    void s0(c p0);
    VerticalViewPager s2();
    Fragment t();
    void u(boolean p0);
    void unregisterDataSetObserver(DataSetObserver p0);
    void v(QPhoto p0);
    int w();
    void x(List p0,QPhoto p1,boolean p2,String p3);
    void y(Fragment p0,a p1);
    int z();
}
