package ayb.i;
import tkd.b;
import com.smile.gifmaker.mvps.presenter.PresenterV2;
import com.google.gson.JsonObject;
import com.kwai.feature.api.feed.detail.router.biz.nasa.NasaBizParam;
import java.lang.String;
import pr6.d;
import android.app.Activity;
import java.lang.Object;
import com.smile.gifmaker.mvps.presenter.MainThreadScatterPresenterGroup;
import dyb.a;
import com.yxcorp.gifshow.recycler.fragment.BaseFragment;
import android.content.Intent;
import com.kwai.framework.init.a;
import pw6.d;
import mvb.c;
import brd.t;
import com.kwai.feature.api.feed.growth.model.XinhuiDetailSurveyModel;
import kotlin.Triple;
import androidx.fragment.app.FragmentActivity;

public interface abstract i implements b	// class@000358
{

    void AX();
    void AZ(PresenterV2 p0);
    void B20(JsonObject p0);
    void BD(int p0);
    boolean BS();
    void C20(JsonObject p0);
    boolean CJ();
    boolean CN();
    boolean CP();
    void CX(PresenterV2 p0,boolean p1);
    boolean Cw(NasaBizParam p0,String p1);
    void Dm();
    boolean EC(int p0);
    void El(d p0,PresenterV2 p1);
    void IW(JsonObject p0);
    boolean Ii(boolean p0,String p1);
    void Il(Activity p0,Object p1);
    void JB(MainThreadScatterPresenterGroup p0);
    boolean L10(int p0);
    void N7(MainThreadScatterPresenterGroup p0);
    void OA(PresenterV2 p0);
    JsonObject OD(JsonObject p0,String p1);
    boolean Pe(int p0);
    void Pq(PresenterV2 p0);
    void QU(Activity p0,Object p1);
    void Qz(boolean p0);
    void Rb(String p0,String p1,String p2);
    boolean Rx(Activity p0,String p1,int p2,int p3);
    void S60();
    void UU(Activity p0);
    boolean UV(Activity p0);
    boolean VD();
    void VY(Activity p0,String p1);
    int Ve();
    void Vj(PresenterV2 p0);
    void WO(boolean p0,boolean p1);
    String Wk(String p0);
    void Ww(JsonObject p0);
    boolean XC();
    boolean XG(Activity p0,a p1);
    PresenterV2 Xz();
    void b30(BaseFragment p0,Intent p1);
    PresenterV2 bw(boolean p0);
    a cd();
    int dC();
    void dO(int p0,String p1);
    boolean ds(int p0);
    boolean fS();
    void fq(PresenterV2 p0);
    d hJ();
    void i20(c p0,int p1);
    boolean iM();
    t iS(String p0,String p1,String p2,int p3,String p4);
    boolean l0();
    boolean oF();
    void onPushPermissionElementEvent(int p0,String p1,int p2);
    boolean op();
    t p2(String p0);
    Object qB(String p0,Object p1);
    boolean qW();
    void qp();
    a rQ();
    boolean sN(NasaBizParam p0,String p1);
    XinhuiDetailSurveyModel sR();
    void st(PresenterV2 p0);
    boolean t4();
    void tB(PresenterV2 p0);
    Triple u8();
    PresenterV2 uF();
    void uU(PresenterV2 p0);
    void ud(String p0,String p1);
    boolean v30(String p0,int p1);
    void vp(PresenterV2 p0);
    boolean xG();
    void xL(boolean p0,String p1);
    void y30(FragmentActivity p0);
    PresenterV2 yB();
    void zH(int p0);
    boolean zO();
    a zP();
    void zz(XinhuiDetailSurveyModel p0);
}
