package etd.b$a;
import etd.b;
import java.lang.Object;
import java.lang.String;
import kotlin.jvm.internal.a;
import kotlin.NotImplementedError;

public final class b$a	// class@000dde
{

    public static Object[] a(b p0,int p1){
       a.p(p0, "this");
       throw new NotImplementedError("Generated by Android Extensions automatically");
    }
}
