package com.yxcorp.download.DownloadConfig;
import java.lang.Object;
import com.yxcorp.download.DownloadTask$DownloadTaskType;
import java.lang.Enum;
import java.util.Collections;
import com.yxcorp.download.DownloadConfig$1;
import com.yxcorp.download.DownloadConfig$2;
import com.yxcorp.download.DownloadConfig$3;

public class DownloadConfig	// class@0011a3
{
    public boolean A;
    public boolean B;
    public boolean C;
    public HashMap D;
    public HashMap E;
    public ArrayList F;
    public c G;
    public Context a;
    public File b;
    public int c;
    public int d;
    public boolean e;
    public boolean f;
    public boolean g;
    public boolean h;
    public boolean i;
    public boolean j;
    public boolean k;
    public List l;
    public float m;
    public float n;
    public float o;
    public float p;
    public boolean q;
    public DownloadConfig$a r;
    public List s;
    public List t;
    public Map u;
    public Map v;
    public int w;
    public int x;
    public boolean y;
    public boolean z;

    public void DownloadConfig(){
       super();
       this.c = 1200;
       this.d = DownloadTask$DownloadTaskType.PRE_DOWNLOAD.ordinal();
       this.e = false;
       this.f = true;
       this.g = true;
       this.h = false;
       this.i = true;
       this.j = false;
       this.k = false;
       List eMPTY_LIST = Collections.EMPTY_LIST;
       this.l = eMPTY_LIST;
       this.m = Float.NaN;
       this.n = Float.NaN;
       this.o = 0x3f800000;
       this.p = 0x3f800000;
       this.q = false;
       this.r = null;
       this.s = eMPTY_LIST;
       this.t = eMPTY_LIST;
       Map eMPTY_MAP = Collections.EMPTY_MAP;
       this.u = eMPTY_MAP;
       this.v = eMPTY_MAP;
       this.w = 30;
       this.x = 1500;
       this.y = false;
       this.z = false;
       this.A = false;
       this.B = false;
       this.C = false;
       this.D = new DownloadConfig$1(this);
       this.E = new DownloadConfig$2(this);
       this.F = new DownloadConfig$3(this);
    }
    public void DownloadConfig(DownloadConfig$1 p0){
       super();
       this.c = 1200;
       this.d = DownloadTask$DownloadTaskType.PRE_DOWNLOAD.ordinal();
       this.e = false;
       this.f = true;
       this.g = true;
       this.h = false;
       this.i = true;
       this.j = false;
       this.k = false;
       List eMPTY_LIST = Collections.EMPTY_LIST;
       this.l = eMPTY_LIST;
       this.m = Float.NaN;
       this.n = Float.NaN;
       this.o = 0x3f800000;
       this.p = 0x3f800000;
       this.q = false;
       this.r = null;
       this.s = eMPTY_LIST;
       this.t = eMPTY_LIST;
       Map eMPTY_MAP = Collections.EMPTY_MAP;
       this.u = eMPTY_MAP;
       this.v = eMPTY_MAP;
       this.w = 30;
       this.x = 1500;
       this.y = false;
       this.z = false;
       this.A = false;
       this.B = false;
       this.C = false;
       this.D = new DownloadConfig$1(this);
       this.E = new DownloadConfig$2(this);
       this.F = new DownloadConfig$3(this);
    }
}
