package com.facebook.react.bridge.ReactMarkerConstants;
import java.lang.Enum;
import java.lang.String;
import java.lang.Object;
import java.lang.Class;
import com.kwai.robust.PatchProxy;
import com.kwai.robust.PatchProxyResult;

public final class ReactMarkerConstants extends Enum	// class@001227
{
    public static final ReactMarkerConstants[] $VALUES;
    public static final ReactMarkerConstants ATTACH_MEASURED_ROOT_VIEWS_END;
    public static final ReactMarkerConstants ATTACH_MEASURED_ROOT_VIEWS_START;
    public static final ReactMarkerConstants BATCH_COMPLETE_END;
    public static final ReactMarkerConstants BATCH_COMPLETE_START;
    public static final ReactMarkerConstants BUILD_NATIVE_MODULE_REGISTRY_END;
    public static final ReactMarkerConstants BUILD_NATIVE_MODULE_REGISTRY_START;
    public static final ReactMarkerConstants BUILD_REACT_INSTANCE_MANAGER_END;
    public static final ReactMarkerConstants BUILD_REACT_INSTANCE_MANAGER_START;
    public static final ReactMarkerConstants CHANGE_THREAD_PRIORITY;
    public static final ReactMarkerConstants CONTENT_APPEARED;
    public static final ReactMarkerConstants CONVERT_CONSTANTS_END;
    public static final ReactMarkerConstants CONVERT_CONSTANTS_START;
    public static final ReactMarkerConstants CREATE_CATALYST_INSTANCE_END;
    public static final ReactMarkerConstants CREATE_CATALYST_INSTANCE_START;
    public static final ReactMarkerConstants CREATE_I18N_ASSETS_MODULE_END;
    public static final ReactMarkerConstants CREATE_I18N_ASSETS_MODULE_START;
    public static final ReactMarkerConstants CREATE_I18N_MODULE_CONSTANTS_END;
    public static final ReactMarkerConstants CREATE_I18N_MODULE_CONSTANTS_START;
    public static final ReactMarkerConstants CREATE_MC_MODULE_END;
    public static final ReactMarkerConstants CREATE_MC_MODULE_GET_METADATA_END;
    public static final ReactMarkerConstants CREATE_MC_MODULE_GET_METADATA_START;
    public static final ReactMarkerConstants CREATE_MC_MODULE_START;
    public static final ReactMarkerConstants CREATE_MODULE_END;
    public static final ReactMarkerConstants CREATE_MODULE_START;
    public static final ReactMarkerConstants CREATE_REACT_CONTEXT_END;
    public static final ReactMarkerConstants CREATE_REACT_CONTEXT_START;
    public static final ReactMarkerConstants CREATE_UI_MANAGER_MODULE_CONSTANTS_END;
    public static final ReactMarkerConstants CREATE_UI_MANAGER_MODULE_CONSTANTS_START;
    public static final ReactMarkerConstants CREATE_UI_MANAGER_MODULE_END;
    public static final ReactMarkerConstants CREATE_UI_MANAGER_MODULE_START;
    public static final ReactMarkerConstants CREATE_VIEW_END;
    public static final ReactMarkerConstants CREATE_VIEW_MANAGERS_END;
    public static final ReactMarkerConstants CREATE_VIEW_MANAGERS_START;
    public static final ReactMarkerConstants CREATE_VIEW_START;
    public static final ReactMarkerConstants DESTROY_CATALYST_INSTANCE_END;
    public static final ReactMarkerConstants DESTROY_CATALYST_INSTANCE_START;
    public static final ReactMarkerConstants DOWNLOAD_END;
    public static final ReactMarkerConstants DOWNLOAD_START;
    public static final ReactMarkerConstants FABRIC_BATCH_EXECUTION_END;
    public static final ReactMarkerConstants FABRIC_BATCH_EXECUTION_START;
    public static final ReactMarkerConstants FABRIC_COMMIT_END;
    public static final ReactMarkerConstants FABRIC_COMMIT_START;
    public static final ReactMarkerConstants FABRIC_DIFF_END;
    public static final ReactMarkerConstants FABRIC_DIFF_START;
    public static final ReactMarkerConstants FABRIC_FINISH_TRANSACTION_END;
    public static final ReactMarkerConstants FABRIC_FINISH_TRANSACTION_START;
    public static final ReactMarkerConstants FABRIC_LAYOUT_END;
    public static final ReactMarkerConstants FABRIC_LAYOUT_START;
    public static final ReactMarkerConstants FABRIC_UPDATE_UI_MAIN_THREAD_END;
    public static final ReactMarkerConstants FABRIC_UPDATE_UI_MAIN_THREAD_START;
    public static final ReactMarkerConstants FMP_ON_DRAW;
    public static final ReactMarkerConstants GET_CONSTANTS_END;
    public static final ReactMarkerConstants GET_CONSTANTS_START;
    public static final ReactMarkerConstants GET_REACT_INSTANCE_HOLDER_SPEC_END;
    public static final ReactMarkerConstants GET_REACT_INSTANCE_HOLDER_SPEC_START;
    public static final ReactMarkerConstants GET_REACT_INSTANCE_MANAGER_END;
    public static final ReactMarkerConstants GET_REACT_INSTANCE_MANAGER_START;
    public static final ReactMarkerConstants I18N_MODULE_CONSTANTS_CONVERT_END;
    public static final ReactMarkerConstants I18N_MODULE_CONSTANTS_CONVERT_START;
    public static final ReactMarkerConstants INITIALIZE_MODULE_END;
    public static final ReactMarkerConstants INITIALIZE_MODULE_START;
    public static final ReactMarkerConstants JAVASCRIPT_EXECUTOR_FACTORY_INJECT_END;
    public static final ReactMarkerConstants JAVASCRIPT_EXECUTOR_FACTORY_INJECT_START;
    public static final ReactMarkerConstants LCP_ON_DRAW;
    public static final ReactMarkerConstants LOAD_FIRST_PAGE_END;
    public static final ReactMarkerConstants LOAD_FIRST_PAGE_START;
    public static final ReactMarkerConstants LOAD_JS_BUNDLE_SIZE;
    public static final ReactMarkerConstants LOAD_REACT_NATIVE_FABRIC_SO_FILE_END;
    public static final ReactMarkerConstants LOAD_REACT_NATIVE_FABRIC_SO_FILE_START;
    public static final ReactMarkerConstants LOAD_REACT_NATIVE_SO_FILE_END;
    public static final ReactMarkerConstants LOAD_REACT_NATIVE_SO_FILE_START;
    public static final ReactMarkerConstants MANAGE_CHILDREN_END;
    public static final ReactMarkerConstants MANAGE_CHILDREN_START;
    public static final ReactMarkerConstants NATIVE_MODULE_INITIALIZE_END;
    public static final ReactMarkerConstants NATIVE_MODULE_INITIALIZE_START;
    public static final ReactMarkerConstants NATIVE_MODULE_SETUP_END;
    public static final ReactMarkerConstants NATIVE_MODULE_SETUP_START;
    public static final ReactMarkerConstants ON_FRAGMENT_CREATE;
    public static final ReactMarkerConstants ON_HOST_PAUSE_END;
    public static final ReactMarkerConstants ON_HOST_PAUSE_START;
    public static final ReactMarkerConstants ON_HOST_RESUME_END;
    public static final ReactMarkerConstants ON_HOST_RESUME_START;
    public static final ReactMarkerConstants PRE_REACT_CONTEXT_END;
    public static final ReactMarkerConstants PRE_RUN_JS_BUNDLE_START;
    public static final ReactMarkerConstants PRE_SETUP_REACT_CONTEXT_END;
    public static final ReactMarkerConstants PRE_SETUP_REACT_CONTEXT_START;
    public static final ReactMarkerConstants PROCESS_CORE_REACT_PACKAGE_END;
    public static final ReactMarkerConstants PROCESS_CORE_REACT_PACKAGE_START;
    public static final ReactMarkerConstants PROCESS_INFRA_PACKAGE_END;
    public static final ReactMarkerConstants PROCESS_INFRA_PACKAGE_START;
    public static final ReactMarkerConstants PROCESS_PACKAGES_END;
    public static final ReactMarkerConstants PROCESS_PACKAGES_START;
    public static final ReactMarkerConstants PROCESS_PRODUCT_PACKAGE_END;
    public static final ReactMarkerConstants PROCESS_PRODUCT_PACKAGE_START;
    public static final ReactMarkerConstants REACT_CONTEXT_THREAD_END;
    public static final ReactMarkerConstants REACT_CONTEXT_THREAD_START;
    public static final ReactMarkerConstants REGISTER_JS_SEGMENT_START;
    public static final ReactMarkerConstants REGISTER_JS_SEGMENT_STOP;
    public static final ReactMarkerConstants RELOAD;
    public static final ReactMarkerConstants RUN_APPLICATION_END;
    public static final ReactMarkerConstants RUN_APPLICATION_START;
    public static final ReactMarkerConstants RUN_JS_BUNDLE_END;
    public static final ReactMarkerConstants RUN_JS_BUNDLE_START;
    public static final ReactMarkerConstants SETUP_REACT_CONTEXT_END;
    public static final ReactMarkerConstants SETUP_REACT_CONTEXT_START;
    public static final ReactMarkerConstants SET_CHILDREN_END;
    public static final ReactMarkerConstants SET_CHILDREN_START;
    public static final ReactMarkerConstants UNPACKING_JS_BUNDLE_LOADER_BLOCKED;
    public static final ReactMarkerConstants UNPACKING_JS_BUNDLE_LOADER_CHECK_END;
    public static final ReactMarkerConstants UNPACKING_JS_BUNDLE_LOADER_CHECK_START;
    public static final ReactMarkerConstants UNPACKING_JS_BUNDLE_LOADER_EXTRACTED;
    public static final ReactMarkerConstants UPDATE_VIEW_END;
    public static final ReactMarkerConstants UPDATE_VIEW_START;
    public static final ReactMarkerConstants VM_INIT;
    public static final ReactMarkerConstants asyncMethodCallArgConversionEnd;
    public static final ReactMarkerConstants asyncMethodCallArgConversionStart;
    public static final ReactMarkerConstants asyncMethodCallBatchPreprocessEnd;
    public static final ReactMarkerConstants asyncMethodCallBatchPreprocessStart;
    public static final ReactMarkerConstants asyncMethodCallDispatch;
    public static final ReactMarkerConstants asyncMethodCallEnd;
    public static final ReactMarkerConstants asyncMethodCallExecutionArgConversionEnd;
    public static final ReactMarkerConstants asyncMethodCallExecutionArgConversionStart;
    public static final ReactMarkerConstants asyncMethodCallExecutionEnd;
    public static final ReactMarkerConstants asyncMethodCallExecutionFail;
    public static final ReactMarkerConstants asyncMethodCallExecutionStart;
    public static final ReactMarkerConstants asyncMethodCallFail;
    public static final ReactMarkerConstants asyncMethodCallStart;
    public static final ReactMarkerConstants loadApplicationScript_endStringConvert;
    public static final ReactMarkerConstants loadApplicationScript_startStringConvert;
    public static final ReactMarkerConstants moduleCreateCacheHit;
    public static final ReactMarkerConstants moduleCreateConstructEnd;
    public static final ReactMarkerConstants moduleCreateConstructStart;
    public static final ReactMarkerConstants moduleCreateEnd;
    public static final ReactMarkerConstants moduleCreateFail;
    public static final ReactMarkerConstants moduleCreateSetUpEnd;
    public static final ReactMarkerConstants moduleCreateSetUpStart;
    public static final ReactMarkerConstants moduleCreateStart;
    public static final ReactMarkerConstants moduleDataCreateEnd;
    public static final ReactMarkerConstants moduleDataCreateStart;
    public static final ReactMarkerConstants moduleJSRequireBeginningCacheHit;
    public static final ReactMarkerConstants moduleJSRequireBeginningEnd;
    public static final ReactMarkerConstants moduleJSRequireBeginningFail;
    public static final ReactMarkerConstants moduleJSRequireBeginningStart;
    public static final ReactMarkerConstants moduleJSRequireEndingEnd;
    public static final ReactMarkerConstants moduleJSRequireEndingFail;
    public static final ReactMarkerConstants moduleJSRequireEndingStart;
    public static final ReactMarkerConstants registerModulesEnd;
    public static final ReactMarkerConstants registerModulesStart;
    public static final ReactMarkerConstants syncMethodCallArgConversionEnd;
    public static final ReactMarkerConstants syncMethodCallArgConversionStart;
    public static final ReactMarkerConstants syncMethodCallEnd;
    public static final ReactMarkerConstants syncMethodCallExecutionEnd;
    public static final ReactMarkerConstants syncMethodCallExecutionStart;
    public static final ReactMarkerConstants syncMethodCallFail;
    public static final ReactMarkerConstants syncMethodCallReturnConversionEnd;
    public static final ReactMarkerConstants syncMethodCallReturnConversionStart;
    public static final ReactMarkerConstants syncMethodCallStart;

    static {
       ReactMarkerConstants reactMarkerC = new ReactMarkerConstants("CREATE_REACT_CONTEXT_START", 0);
       ReactMarkerConstants.CREATE_REACT_CONTEXT_START = reactMarkerC;
       ReactMarkerConstants reactMarkerC1 = new ReactMarkerConstants("CREATE_REACT_CONTEXT_END", 1);
       ReactMarkerConstants.CREATE_REACT_CONTEXT_END = reactMarkerC1;
       ReactMarkerConstants reactMarkerC2 = new ReactMarkerConstants("PROCESS_PACKAGES_START", 2);
       ReactMarkerConstants.PROCESS_PACKAGES_START = reactMarkerC2;
       ReactMarkerConstants reactMarkerC3 = new ReactMarkerConstants("PROCESS_PACKAGES_END", 3);
       ReactMarkerConstants.PROCESS_PACKAGES_END = reactMarkerC3;
       ReactMarkerConstants reactMarkerC4 = new ReactMarkerConstants("BUILD_NATIVE_MODULE_REGISTRY_START", 4);
       ReactMarkerConstants.BUILD_NATIVE_MODULE_REGISTRY_START = reactMarkerC4;
       ReactMarkerConstants reactMarkerC5 = new ReactMarkerConstants("BUILD_NATIVE_MODULE_REGISTRY_END", 5);
       ReactMarkerConstants.BUILD_NATIVE_MODULE_REGISTRY_END = reactMarkerC5;
       ReactMarkerConstants reactMarkerC6 = new ReactMarkerConstants("CREATE_CATALYST_INSTANCE_START", 6);
       ReactMarkerConstants.CREATE_CATALYST_INSTANCE_START = reactMarkerC6;
       ReactMarkerConstants reactMarkerC7 = new ReactMarkerConstants("CREATE_CATALYST_INSTANCE_END", 7);
       ReactMarkerConstants.CREATE_CATALYST_INSTANCE_END = reactMarkerC7;
       ReactMarkerConstants reactMarkerC8 = new ReactMarkerConstants("DESTROY_CATALYST_INSTANCE_START", 8);
       ReactMarkerConstants.DESTROY_CATALYST_INSTANCE_START = reactMarkerC8;
       ReactMarkerConstants reactMarkerC9 = new ReactMarkerConstants("DESTROY_CATALYST_INSTANCE_END", 9);
       ReactMarkerConstants.DESTROY_CATALYST_INSTANCE_END = reactMarkerC9;
       ReactMarkerConstants reactMarkerC10 = new ReactMarkerConstants("LCP_ON_DRAW", 10);
       ReactMarkerConstants.LCP_ON_DRAW = reactMarkerC10;
       ReactMarkerConstants reactMarkerC11 = new ReactMarkerConstants("FMP_ON_DRAW", 11);
       ReactMarkerConstants.FMP_ON_DRAW = reactMarkerC11;
       ReactMarkerConstants reactMarkerC12 = new ReactMarkerConstants("RUN_JS_BUNDLE_START", 12);
       ReactMarkerConstants.RUN_JS_BUNDLE_START = reactMarkerC12;
       ReactMarkerConstants reactMarkerC13 = new ReactMarkerConstants("RUN_JS_BUNDLE_END", 13);
       ReactMarkerConstants.RUN_JS_BUNDLE_END = reactMarkerC13;
       ReactMarkerConstants reactMarkerC14 = reactMarkerC13;
       ReactMarkerConstants reactMarkerC15 = new ReactMarkerConstants("LOAD_JS_BUNDLE_SIZE", 14);
       ReactMarkerConstants.LOAD_JS_BUNDLE_SIZE = reactMarkerC15;
       ReactMarkerConstants reactMarkerC16 = reactMarkerC15;
       ReactMarkerConstants reactMarkerC17 = new ReactMarkerConstants("NATIVE_MODULE_INITIALIZE_START", 15);
       ReactMarkerConstants.NATIVE_MODULE_INITIALIZE_START = reactMarkerC17;
       ReactMarkerConstants reactMarkerC18 = reactMarkerC17;
       reactMarkerC13 = new ReactMarkerConstants("NATIVE_MODULE_INITIALIZE_END", 16);
       ReactMarkerConstants.NATIVE_MODULE_INITIALIZE_END = reactMarkerC13;
       ReactMarkerConstants reactMarkerC19 = reactMarkerC13;
       reactMarkerC15 = new ReactMarkerConstants("SETUP_REACT_CONTEXT_START", 17);
       ReactMarkerConstants.SETUP_REACT_CONTEXT_START = reactMarkerC15;
       ReactMarkerConstants reactMarkerC20 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("SETUP_REACT_CONTEXT_END", 18);
       ReactMarkerConstants.SETUP_REACT_CONTEXT_END = reactMarkerC17;
       ReactMarkerConstants reactMarkerC21 = reactMarkerC17;
       reactMarkerC13 = new ReactMarkerConstants("CHANGE_THREAD_PRIORITY", 19);
       ReactMarkerConstants.CHANGE_THREAD_PRIORITY = reactMarkerC13;
       ReactMarkerConstants reactMarkerC22 = reactMarkerC13;
       reactMarkerC15 = new ReactMarkerConstants("CREATE_UI_MANAGER_MODULE_START", 20);
       ReactMarkerConstants.CREATE_UI_MANAGER_MODULE_START = reactMarkerC15;
       ReactMarkerConstants reactMarkerC23 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("CREATE_UI_MANAGER_MODULE_END", 21);
       ReactMarkerConstants.CREATE_UI_MANAGER_MODULE_END = reactMarkerC17;
       ReactMarkerConstants reactMarkerC24 = reactMarkerC17;
       reactMarkerC13 = new ReactMarkerConstants("CREATE_VIEW_MANAGERS_START", 22);
       ReactMarkerConstants.CREATE_VIEW_MANAGERS_START = reactMarkerC13;
       ReactMarkerConstants reactMarkerC25 = reactMarkerC13;
       reactMarkerC17 = new ReactMarkerConstants("CREATE_VIEW_MANAGERS_END", 23);
       ReactMarkerConstants.CREATE_VIEW_MANAGERS_END = reactMarkerC17;
       ReactMarkerConstants reactMarkerC26 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("CREATE_UI_MANAGER_MODULE_CONSTANTS_START", 24);
       ReactMarkerConstants.CREATE_UI_MANAGER_MODULE_CONSTANTS_START = reactMarkerC15;
       ReactMarkerConstants reactMarkerC27 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("CREATE_UI_MANAGER_MODULE_CONSTANTS_END", 25);
       ReactMarkerConstants.CREATE_UI_MANAGER_MODULE_CONSTANTS_END = reactMarkerC17;
       ReactMarkerConstants reactMarkerC28 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("NATIVE_MODULE_SETUP_START", 26);
       ReactMarkerConstants.NATIVE_MODULE_SETUP_START = reactMarkerC15;
       ReactMarkerConstants reactMarkerC29 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("NATIVE_MODULE_SETUP_END", 27);
       ReactMarkerConstants.NATIVE_MODULE_SETUP_END = reactMarkerC17;
       ReactMarkerConstants reactMarkerC30 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("CREATE_MODULE_START", 28);
       ReactMarkerConstants.CREATE_MODULE_START = reactMarkerC15;
       ReactMarkerConstants reactMarkerC31 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("CREATE_MODULE_END", 29);
       ReactMarkerConstants.CREATE_MODULE_END = reactMarkerC17;
       ReactMarkerConstants reactMarkerC32 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("PROCESS_CORE_REACT_PACKAGE_START", 30);
       ReactMarkerConstants.PROCESS_CORE_REACT_PACKAGE_START = reactMarkerC15;
       ReactMarkerConstants reactMarkerC33 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("PROCESS_CORE_REACT_PACKAGE_END", 31);
       ReactMarkerConstants.PROCESS_CORE_REACT_PACKAGE_END = reactMarkerC17;
       ReactMarkerConstants reactMarkerC34 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("CREATE_I18N_MODULE_CONSTANTS_START", 32);
       ReactMarkerConstants.CREATE_I18N_MODULE_CONSTANTS_START = reactMarkerC15;
       ReactMarkerConstants reactMarkerC35 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("CREATE_I18N_MODULE_CONSTANTS_END", 33);
       ReactMarkerConstants.CREATE_I18N_MODULE_CONSTANTS_END = reactMarkerC17;
       ReactMarkerConstants reactMarkerC36 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("I18N_MODULE_CONSTANTS_CONVERT_START", 34);
       ReactMarkerConstants.I18N_MODULE_CONSTANTS_CONVERT_START = reactMarkerC15;
       ReactMarkerConstants reactMarkerC37 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("I18N_MODULE_CONSTANTS_CONVERT_END", 35);
       ReactMarkerConstants.I18N_MODULE_CONSTANTS_CONVERT_END = reactMarkerC17;
       ReactMarkerConstants reactMarkerC38 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("CREATE_I18N_ASSETS_MODULE_START", 36);
       ReactMarkerConstants.CREATE_I18N_ASSETS_MODULE_START = reactMarkerC15;
       ReactMarkerConstants reactMarkerC39 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("CREATE_I18N_ASSETS_MODULE_END", 37);
       ReactMarkerConstants.CREATE_I18N_ASSETS_MODULE_END = reactMarkerC17;
       ReactMarkerConstants reactMarkerC40 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("GET_CONSTANTS_START", 38);
       ReactMarkerConstants.GET_CONSTANTS_START = reactMarkerC15;
       ReactMarkerConstants reactMarkerC41 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("GET_CONSTANTS_END", 39);
       ReactMarkerConstants.GET_CONSTANTS_END = reactMarkerC17;
       ReactMarkerConstants reactMarkerC42 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("INITIALIZE_MODULE_START", 40);
       ReactMarkerConstants.INITIALIZE_MODULE_START = reactMarkerC15;
       ReactMarkerConstants reactMarkerC43 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("INITIALIZE_MODULE_END", 41);
       ReactMarkerConstants.INITIALIZE_MODULE_END = reactMarkerC17;
       ReactMarkerConstants reactMarkerC44 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("ON_HOST_RESUME_START", 42);
       ReactMarkerConstants.ON_HOST_RESUME_START = reactMarkerC15;
       ReactMarkerConstants reactMarkerC45 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("ON_HOST_RESUME_END", 43);
       ReactMarkerConstants.ON_HOST_RESUME_END = reactMarkerC17;
       ReactMarkerConstants reactMarkerC46 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("ON_HOST_PAUSE_START", 44);
       ReactMarkerConstants.ON_HOST_PAUSE_START = reactMarkerC15;
       ReactMarkerConstants reactMarkerC47 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("ON_HOST_PAUSE_END", 45);
       ReactMarkerConstants.ON_HOST_PAUSE_END = reactMarkerC17;
       ReactMarkerConstants reactMarkerC48 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("CONVERT_CONSTANTS_START", 46);
       ReactMarkerConstants.CONVERT_CONSTANTS_START = reactMarkerC15;
       ReactMarkerConstants reactMarkerC49 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("CONVERT_CONSTANTS_END", 47);
       ReactMarkerConstants.CONVERT_CONSTANTS_END = reactMarkerC17;
       ReactMarkerConstants reactMarkerC50 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("PRE_REACT_CONTEXT_END", 48);
       ReactMarkerConstants.PRE_REACT_CONTEXT_END = reactMarkerC15;
       ReactMarkerConstants reactMarkerC51 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("UNPACKING_JS_BUNDLE_LOADER_CHECK_START", 49);
       ReactMarkerConstants.UNPACKING_JS_BUNDLE_LOADER_CHECK_START = reactMarkerC17;
       ReactMarkerConstants reactMarkerC52 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("UNPACKING_JS_BUNDLE_LOADER_CHECK_END", 50);
       ReactMarkerConstants.UNPACKING_JS_BUNDLE_LOADER_CHECK_END = reactMarkerC15;
       ReactMarkerConstants reactMarkerC53 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("UNPACKING_JS_BUNDLE_LOADER_EXTRACTED", 51);
       ReactMarkerConstants.UNPACKING_JS_BUNDLE_LOADER_EXTRACTED = reactMarkerC17;
       ReactMarkerConstants reactMarkerC54 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("UNPACKING_JS_BUNDLE_LOADER_BLOCKED", 52);
       ReactMarkerConstants.UNPACKING_JS_BUNDLE_LOADER_BLOCKED = reactMarkerC15;
       ReactMarkerConstants reactMarkerC55 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("loadApplicationScript_startStringConvert", 53);
       ReactMarkerConstants.loadApplicationScript_startStringConvert = reactMarkerC17;
       ReactMarkerConstants reactMarkerC56 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("loadApplicationScript_endStringConvert", 54);
       ReactMarkerConstants.loadApplicationScript_endStringConvert = reactMarkerC15;
       ReactMarkerConstants reactMarkerC57 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("PRE_SETUP_REACT_CONTEXT_START", 55);
       ReactMarkerConstants.PRE_SETUP_REACT_CONTEXT_START = reactMarkerC17;
       ReactMarkerConstants reactMarkerC58 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("PRE_SETUP_REACT_CONTEXT_END", 56);
       ReactMarkerConstants.PRE_SETUP_REACT_CONTEXT_END = reactMarkerC15;
       ReactMarkerConstants reactMarkerC59 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("PRE_RUN_JS_BUNDLE_START", 57);
       ReactMarkerConstants.PRE_RUN_JS_BUNDLE_START = reactMarkerC17;
       ReactMarkerConstants reactMarkerC60 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("ATTACH_MEASURED_ROOT_VIEWS_START", 58);
       ReactMarkerConstants.ATTACH_MEASURED_ROOT_VIEWS_START = reactMarkerC15;
       ReactMarkerConstants reactMarkerC61 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("ATTACH_MEASURED_ROOT_VIEWS_END", 59);
       ReactMarkerConstants.ATTACH_MEASURED_ROOT_VIEWS_END = reactMarkerC17;
       ReactMarkerConstants reactMarkerC62 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("CONTENT_APPEARED", 60);
       ReactMarkerConstants.CONTENT_APPEARED = reactMarkerC15;
       ReactMarkerConstants reactMarkerC63 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("RELOAD", 61);
       ReactMarkerConstants.RELOAD = reactMarkerC17;
       ReactMarkerConstants reactMarkerC64 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("DOWNLOAD_START", 62);
       ReactMarkerConstants.DOWNLOAD_START = reactMarkerC15;
       ReactMarkerConstants reactMarkerC65 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("DOWNLOAD_END", 63);
       ReactMarkerConstants.DOWNLOAD_END = reactMarkerC17;
       ReactMarkerConstants reactMarkerC66 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("REACT_CONTEXT_THREAD_START", 64);
       ReactMarkerConstants.REACT_CONTEXT_THREAD_START = reactMarkerC15;
       ReactMarkerConstants reactMarkerC67 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("REACT_CONTEXT_THREAD_END", 65);
       ReactMarkerConstants.REACT_CONTEXT_THREAD_END = reactMarkerC17;
       ReactMarkerConstants reactMarkerC68 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("GET_REACT_INSTANCE_MANAGER_START", 66);
       ReactMarkerConstants.GET_REACT_INSTANCE_MANAGER_START = reactMarkerC15;
       ReactMarkerConstants reactMarkerC69 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("GET_REACT_INSTANCE_MANAGER_END", 67);
       ReactMarkerConstants.GET_REACT_INSTANCE_MANAGER_END = reactMarkerC17;
       ReactMarkerConstants reactMarkerC70 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("GET_REACT_INSTANCE_HOLDER_SPEC_START", 68);
       ReactMarkerConstants.GET_REACT_INSTANCE_HOLDER_SPEC_START = reactMarkerC15;
       ReactMarkerConstants reactMarkerC71 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("GET_REACT_INSTANCE_HOLDER_SPEC_END", 69);
       ReactMarkerConstants.GET_REACT_INSTANCE_HOLDER_SPEC_END = reactMarkerC17;
       ReactMarkerConstants reactMarkerC72 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("BUILD_REACT_INSTANCE_MANAGER_START", 70);
       ReactMarkerConstants.BUILD_REACT_INSTANCE_MANAGER_START = reactMarkerC15;
       ReactMarkerConstants reactMarkerC73 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("BUILD_REACT_INSTANCE_MANAGER_END", 71);
       ReactMarkerConstants.BUILD_REACT_INSTANCE_MANAGER_END = reactMarkerC17;
       ReactMarkerConstants reactMarkerC74 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("PROCESS_INFRA_PACKAGE_START", 72);
       ReactMarkerConstants.PROCESS_INFRA_PACKAGE_START = reactMarkerC15;
       ReactMarkerConstants reactMarkerC75 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("PROCESS_INFRA_PACKAGE_END", 73);
       ReactMarkerConstants.PROCESS_INFRA_PACKAGE_END = reactMarkerC17;
       ReactMarkerConstants reactMarkerC76 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("PROCESS_PRODUCT_PACKAGE_START", 74);
       ReactMarkerConstants.PROCESS_PRODUCT_PACKAGE_START = reactMarkerC15;
       ReactMarkerConstants reactMarkerC77 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("PROCESS_PRODUCT_PACKAGE_END", 75);
       ReactMarkerConstants.PROCESS_PRODUCT_PACKAGE_END = reactMarkerC17;
       ReactMarkerConstants reactMarkerC78 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("CREATE_MC_MODULE_START", 76);
       ReactMarkerConstants.CREATE_MC_MODULE_START = reactMarkerC15;
       ReactMarkerConstants reactMarkerC79 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("CREATE_MC_MODULE_END", 77);
       ReactMarkerConstants.CREATE_MC_MODULE_END = reactMarkerC17;
       ReactMarkerConstants reactMarkerC80 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("CREATE_MC_MODULE_GET_METADATA_START", 78);
       ReactMarkerConstants.CREATE_MC_MODULE_GET_METADATA_START = reactMarkerC15;
       ReactMarkerConstants reactMarkerC81 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("CREATE_MC_MODULE_GET_METADATA_END", 79);
       ReactMarkerConstants.CREATE_MC_MODULE_GET_METADATA_END = reactMarkerC17;
       ReactMarkerConstants reactMarkerC82 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("REGISTER_JS_SEGMENT_START", 80);
       ReactMarkerConstants.REGISTER_JS_SEGMENT_START = reactMarkerC15;
       ReactMarkerConstants reactMarkerC83 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("REGISTER_JS_SEGMENT_STOP", 81);
       ReactMarkerConstants.REGISTER_JS_SEGMENT_STOP = reactMarkerC17;
       ReactMarkerConstants reactMarkerC84 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("VM_INIT", 82);
       ReactMarkerConstants.VM_INIT = reactMarkerC15;
       ReactMarkerConstants reactMarkerC85 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("ON_FRAGMENT_CREATE", 83);
       ReactMarkerConstants.ON_FRAGMENT_CREATE = reactMarkerC17;
       ReactMarkerConstants reactMarkerC86 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("JAVASCRIPT_EXECUTOR_FACTORY_INJECT_START", 84);
       ReactMarkerConstants.JAVASCRIPT_EXECUTOR_FACTORY_INJECT_START = reactMarkerC15;
       ReactMarkerConstants reactMarkerC87 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("JAVASCRIPT_EXECUTOR_FACTORY_INJECT_END", 85);
       ReactMarkerConstants.JAVASCRIPT_EXECUTOR_FACTORY_INJECT_END = reactMarkerC17;
       ReactMarkerConstants reactMarkerC88 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("LOAD_REACT_NATIVE_SO_FILE_START", 86);
       ReactMarkerConstants.LOAD_REACT_NATIVE_SO_FILE_START = reactMarkerC15;
       ReactMarkerConstants reactMarkerC89 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("LOAD_REACT_NATIVE_SO_FILE_END", 87);
       ReactMarkerConstants.LOAD_REACT_NATIVE_SO_FILE_END = reactMarkerC17;
       ReactMarkerConstants reactMarkerC90 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("LOAD_REACT_NATIVE_FABRIC_SO_FILE_START", 88);
       ReactMarkerConstants.LOAD_REACT_NATIVE_FABRIC_SO_FILE_START = reactMarkerC15;
       ReactMarkerConstants reactMarkerC91 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("LOAD_REACT_NATIVE_FABRIC_SO_FILE_END", 89);
       ReactMarkerConstants.LOAD_REACT_NATIVE_FABRIC_SO_FILE_END = reactMarkerC17;
       ReactMarkerConstants reactMarkerC92 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("FABRIC_COMMIT_START", 90);
       ReactMarkerConstants.FABRIC_COMMIT_START = reactMarkerC15;
       ReactMarkerConstants reactMarkerC93 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("FABRIC_COMMIT_END", 91);
       ReactMarkerConstants.FABRIC_COMMIT_END = reactMarkerC17;
       ReactMarkerConstants reactMarkerC94 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("FABRIC_FINISH_TRANSACTION_START", 92);
       ReactMarkerConstants.FABRIC_FINISH_TRANSACTION_START = reactMarkerC15;
       ReactMarkerConstants reactMarkerC95 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("FABRIC_FINISH_TRANSACTION_END", 93);
       ReactMarkerConstants.FABRIC_FINISH_TRANSACTION_END = reactMarkerC17;
       ReactMarkerConstants reactMarkerC96 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("FABRIC_DIFF_START", 94);
       ReactMarkerConstants.FABRIC_DIFF_START = reactMarkerC15;
       ReactMarkerConstants reactMarkerC97 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("FABRIC_DIFF_END", 95);
       ReactMarkerConstants.FABRIC_DIFF_END = reactMarkerC17;
       ReactMarkerConstants reactMarkerC98 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("FABRIC_LAYOUT_START", 96);
       ReactMarkerConstants.FABRIC_LAYOUT_START = reactMarkerC15;
       ReactMarkerConstants reactMarkerC99 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("FABRIC_LAYOUT_END", 97);
       ReactMarkerConstants.FABRIC_LAYOUT_END = reactMarkerC17;
       ReactMarkerConstants reactMarkerC100 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("FABRIC_BATCH_EXECUTION_START", 98);
       ReactMarkerConstants.FABRIC_BATCH_EXECUTION_START = reactMarkerC15;
       ReactMarkerConstants reactMarkerC101 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("FABRIC_BATCH_EXECUTION_END", 99);
       ReactMarkerConstants.FABRIC_BATCH_EXECUTION_END = reactMarkerC17;
       ReactMarkerConstants reactMarkerC102 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("FABRIC_UPDATE_UI_MAIN_THREAD_START", 100);
       ReactMarkerConstants.FABRIC_UPDATE_UI_MAIN_THREAD_START = reactMarkerC15;
       ReactMarkerConstants reactMarkerC103 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("FABRIC_UPDATE_UI_MAIN_THREAD_END", 101);
       ReactMarkerConstants.FABRIC_UPDATE_UI_MAIN_THREAD_END = reactMarkerC17;
       ReactMarkerConstants reactMarkerC104 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("CREATE_VIEW_START", 102);
       ReactMarkerConstants.CREATE_VIEW_START = reactMarkerC15;
       ReactMarkerConstants reactMarkerC105 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("CREATE_VIEW_END", 103);
       ReactMarkerConstants.CREATE_VIEW_END = reactMarkerC17;
       ReactMarkerConstants reactMarkerC106 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("UPDATE_VIEW_START", 104);
       ReactMarkerConstants.UPDATE_VIEW_START = reactMarkerC15;
       ReactMarkerConstants reactMarkerC107 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("UPDATE_VIEW_END", 105);
       ReactMarkerConstants.UPDATE_VIEW_END = reactMarkerC17;
       ReactMarkerConstants reactMarkerC108 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("SET_CHILDREN_START", 106);
       ReactMarkerConstants.SET_CHILDREN_START = reactMarkerC15;
       ReactMarkerConstants reactMarkerC109 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("SET_CHILDREN_END", 107);
       ReactMarkerConstants.SET_CHILDREN_END = reactMarkerC17;
       ReactMarkerConstants reactMarkerC110 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("MANAGE_CHILDREN_START", 108);
       ReactMarkerConstants.MANAGE_CHILDREN_START = reactMarkerC15;
       ReactMarkerConstants reactMarkerC111 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("MANAGE_CHILDREN_END", 109);
       ReactMarkerConstants.MANAGE_CHILDREN_END = reactMarkerC17;
       ReactMarkerConstants reactMarkerC112 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("BATCH_COMPLETE_START", 110);
       ReactMarkerConstants.BATCH_COMPLETE_START = reactMarkerC15;
       ReactMarkerConstants reactMarkerC113 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("BATCH_COMPLETE_END", 111);
       ReactMarkerConstants.BATCH_COMPLETE_END = reactMarkerC17;
       ReactMarkerConstants reactMarkerC114 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("moduleDataCreateStart", 112);
       ReactMarkerConstants.moduleDataCreateStart = reactMarkerC15;
       ReactMarkerConstants reactMarkerC115 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("moduleDataCreateEnd", 113);
       ReactMarkerConstants.moduleDataCreateEnd = reactMarkerC17;
       ReactMarkerConstants reactMarkerC116 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("moduleCreateStart", 114);
       ReactMarkerConstants.moduleCreateStart = reactMarkerC15;
       ReactMarkerConstants reactMarkerC117 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("moduleCreateCacheHit", 115);
       ReactMarkerConstants.moduleCreateCacheHit = reactMarkerC17;
       ReactMarkerConstants reactMarkerC118 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("moduleCreateConstructStart", 116);
       ReactMarkerConstants.moduleCreateConstructStart = reactMarkerC15;
       ReactMarkerConstants reactMarkerC119 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("moduleCreateConstructEnd", 117);
       ReactMarkerConstants.moduleCreateConstructEnd = reactMarkerC17;
       ReactMarkerConstants reactMarkerC120 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("moduleCreateSetUpStart", 118);
       ReactMarkerConstants.moduleCreateSetUpStart = reactMarkerC15;
       ReactMarkerConstants reactMarkerC121 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("moduleCreateSetUpEnd", 119);
       ReactMarkerConstants.moduleCreateSetUpEnd = reactMarkerC17;
       ReactMarkerConstants reactMarkerC122 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("moduleCreateEnd", 120);
       ReactMarkerConstants.moduleCreateEnd = reactMarkerC15;
       ReactMarkerConstants reactMarkerC123 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("moduleCreateFail", 121);
       ReactMarkerConstants.moduleCreateFail = reactMarkerC17;
       ReactMarkerConstants reactMarkerC124 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("moduleJSRequireBeginningStart", 122);
       ReactMarkerConstants.moduleJSRequireBeginningStart = reactMarkerC15;
       ReactMarkerConstants reactMarkerC125 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("moduleJSRequireBeginningCacheHit", 123);
       ReactMarkerConstants.moduleJSRequireBeginningCacheHit = reactMarkerC17;
       ReactMarkerConstants reactMarkerC126 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("moduleJSRequireBeginningEnd", 124);
       ReactMarkerConstants.moduleJSRequireBeginningEnd = reactMarkerC15;
       ReactMarkerConstants reactMarkerC127 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("moduleJSRequireBeginningFail", 125);
       ReactMarkerConstants.moduleJSRequireBeginningFail = reactMarkerC17;
       ReactMarkerConstants reactMarkerC128 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("moduleJSRequireEndingStart", 126);
       ReactMarkerConstants.moduleJSRequireEndingStart = reactMarkerC15;
       ReactMarkerConstants reactMarkerC129 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("moduleJSRequireEndingEnd", 127);
       ReactMarkerConstants.moduleJSRequireEndingEnd = reactMarkerC17;
       ReactMarkerConstants reactMarkerC130 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("moduleJSRequireEndingFail", 128);
       ReactMarkerConstants.moduleJSRequireEndingFail = reactMarkerC15;
       ReactMarkerConstants reactMarkerC131 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("syncMethodCallStart", 129);
       ReactMarkerConstants.syncMethodCallStart = reactMarkerC17;
       ReactMarkerConstants reactMarkerC132 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("syncMethodCallArgConversionStart", 130);
       ReactMarkerConstants.syncMethodCallArgConversionStart = reactMarkerC15;
       ReactMarkerConstants reactMarkerC133 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("syncMethodCallArgConversionEnd", 131);
       ReactMarkerConstants.syncMethodCallArgConversionEnd = reactMarkerC17;
       ReactMarkerConstants reactMarkerC134 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("syncMethodCallExecutionStart", 132);
       ReactMarkerConstants.syncMethodCallExecutionStart = reactMarkerC15;
       ReactMarkerConstants reactMarkerC135 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("syncMethodCallExecutionEnd", 133);
       ReactMarkerConstants.syncMethodCallExecutionEnd = reactMarkerC17;
       ReactMarkerConstants reactMarkerC136 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("syncMethodCallReturnConversionStart", 134);
       ReactMarkerConstants.syncMethodCallReturnConversionStart = reactMarkerC15;
       ReactMarkerConstants reactMarkerC137 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("syncMethodCallReturnConversionEnd", 135);
       ReactMarkerConstants.syncMethodCallReturnConversionEnd = reactMarkerC17;
       ReactMarkerConstants reactMarkerC138 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("syncMethodCallEnd", 136);
       ReactMarkerConstants.syncMethodCallEnd = reactMarkerC15;
       ReactMarkerConstants reactMarkerC139 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("syncMethodCallFail", 137);
       ReactMarkerConstants.syncMethodCallFail = reactMarkerC17;
       ReactMarkerConstants reactMarkerC140 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("asyncMethodCallStart", 138);
       ReactMarkerConstants.asyncMethodCallStart = reactMarkerC15;
       ReactMarkerConstants reactMarkerC141 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("asyncMethodCallArgConversionStart", 139);
       ReactMarkerConstants.asyncMethodCallArgConversionStart = reactMarkerC17;
       ReactMarkerConstants reactMarkerC142 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("asyncMethodCallArgConversionEnd", 140);
       ReactMarkerConstants.asyncMethodCallArgConversionEnd = reactMarkerC15;
       ReactMarkerConstants reactMarkerC143 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("asyncMethodCallDispatch", 141);
       ReactMarkerConstants.asyncMethodCallDispatch = reactMarkerC17;
       ReactMarkerConstants reactMarkerC144 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("asyncMethodCallEnd", 142);
       ReactMarkerConstants.asyncMethodCallEnd = reactMarkerC15;
       ReactMarkerConstants reactMarkerC145 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("asyncMethodCallFail", 143);
       ReactMarkerConstants.asyncMethodCallFail = reactMarkerC17;
       ReactMarkerConstants reactMarkerC146 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("asyncMethodCallBatchPreprocessStart", 144);
       ReactMarkerConstants.asyncMethodCallBatchPreprocessStart = reactMarkerC15;
       ReactMarkerConstants reactMarkerC147 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("asyncMethodCallBatchPreprocessEnd", 145);
       ReactMarkerConstants.asyncMethodCallBatchPreprocessEnd = reactMarkerC17;
       ReactMarkerConstants reactMarkerC148 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("asyncMethodCallExecutionStart", 146);
       ReactMarkerConstants.asyncMethodCallExecutionStart = reactMarkerC15;
       ReactMarkerConstants reactMarkerC149 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("asyncMethodCallExecutionArgConversionStart", 147);
       ReactMarkerConstants.asyncMethodCallExecutionArgConversionStart = reactMarkerC17;
       ReactMarkerConstants reactMarkerC150 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("asyncMethodCallExecutionArgConversionEnd", 148);
       ReactMarkerConstants.asyncMethodCallExecutionArgConversionEnd = reactMarkerC15;
       ReactMarkerConstants reactMarkerC151 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("asyncMethodCallExecutionEnd", 149);
       ReactMarkerConstants.asyncMethodCallExecutionEnd = reactMarkerC17;
       ReactMarkerConstants reactMarkerC152 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("asyncMethodCallExecutionFail", 150);
       ReactMarkerConstants.asyncMethodCallExecutionFail = reactMarkerC15;
       ReactMarkerConstants reactMarkerC153 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("registerModulesStart", 151);
       ReactMarkerConstants.registerModulesStart = reactMarkerC17;
       ReactMarkerConstants reactMarkerC154 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("registerModulesEnd", 152);
       ReactMarkerConstants.registerModulesEnd = reactMarkerC15;
       ReactMarkerConstants reactMarkerC155 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("LOAD_FIRST_PAGE_START", 153);
       ReactMarkerConstants.LOAD_FIRST_PAGE_START = reactMarkerC17;
       ReactMarkerConstants reactMarkerC156 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("LOAD_FIRST_PAGE_END", 154);
       ReactMarkerConstants.LOAD_FIRST_PAGE_END = reactMarkerC15;
       ReactMarkerConstants reactMarkerC157 = reactMarkerC15;
       reactMarkerC17 = new ReactMarkerConstants("RUN_APPLICATION_START", 155);
       ReactMarkerConstants.RUN_APPLICATION_START = reactMarkerC17;
       ReactMarkerConstants reactMarkerC158 = reactMarkerC17;
       reactMarkerC15 = new ReactMarkerConstants("RUN_APPLICATION_END", 156);
       ReactMarkerConstants.RUN_APPLICATION_END = reactMarkerC15;
       ReactMarkerConstants[] reactMarkerC159 = new ReactMarkerConstants[157];
       reactMarkerC159[0] = reactMarkerC;
       reactMarkerC159[1] = reactMarkerC1;
       reactMarkerC159[2] = reactMarkerC2;
       reactMarkerC159[3] = reactMarkerC3;
       reactMarkerC159[4] = reactMarkerC4;
       reactMarkerC159[5] = reactMarkerC5;
       reactMarkerC159[6] = reactMarkerC6;
       reactMarkerC159[7] = reactMarkerC7;
       reactMarkerC159[8] = reactMarkerC8;
       reactMarkerC159[9] = reactMarkerC9;
       reactMarkerC159[10] = reactMarkerC10;
       reactMarkerC159[11] = reactMarkerC11;
       reactMarkerC159[12] = reactMarkerC12;
       reactMarkerC159[13] = reactMarkerC14;
       reactMarkerC159[14] = reactMarkerC16;
       reactMarkerC159[15] = reactMarkerC18;
       reactMarkerC159[16] = reactMarkerC19;
       reactMarkerC159[17] = reactMarkerC20;
       reactMarkerC159[18] = reactMarkerC21;
       reactMarkerC159[19] = reactMarkerC22;
       reactMarkerC159[20] = reactMarkerC23;
       reactMarkerC159[21] = reactMarkerC24;
       reactMarkerC159[22] = reactMarkerC25;
       reactMarkerC159[23] = reactMarkerC26;
       reactMarkerC159[24] = reactMarkerC27;
       reactMarkerC159[25] = reactMarkerC28;
       reactMarkerC159[26] = reactMarkerC29;
       reactMarkerC159[27] = reactMarkerC30;
       reactMarkerC159[28] = reactMarkerC31;
       reactMarkerC159[29] = reactMarkerC32;
       reactMarkerC159[30] = reactMarkerC33;
       reactMarkerC159[31] = reactMarkerC34;
       reactMarkerC159[32] = reactMarkerC35;
       reactMarkerC159[33] = reactMarkerC36;
       reactMarkerC159[34] = reactMarkerC37;
       reactMarkerC159[35] = reactMarkerC38;
       reactMarkerC159[36] = reactMarkerC39;
       reactMarkerC159[37] = reactMarkerC40;
       reactMarkerC159[38] = reactMarkerC41;
       reactMarkerC159[39] = reactMarkerC42;
       reactMarkerC159[40] = reactMarkerC43;
       reactMarkerC159[41] = reactMarkerC44;
       reactMarkerC159[42] = reactMarkerC45;
       reactMarkerC159[43] = reactMarkerC46;
       reactMarkerC159[44] = reactMarkerC47;
       reactMarkerC159[45] = reactMarkerC48;
       reactMarkerC159[46] = reactMarkerC49;
       reactMarkerC159[47] = reactMarkerC50;
       reactMarkerC159[48] = reactMarkerC51;
       reactMarkerC159[49] = reactMarkerC52;
       reactMarkerC159[50] = reactMarkerC53;
       reactMarkerC159[51] = reactMarkerC54;
       reactMarkerC159[52] = reactMarkerC55;
       reactMarkerC159[53] = reactMarkerC56;
       reactMarkerC159[54] = reactMarkerC57;
       reactMarkerC159[55] = reactMarkerC58;
       reactMarkerC159[56] = reactMarkerC59;
       reactMarkerC159[57] = reactMarkerC60;
       reactMarkerC159[58] = reactMarkerC61;
       reactMarkerC159[59] = reactMarkerC62;
       reactMarkerC159[60] = reactMarkerC63;
       reactMarkerC159[61] = reactMarkerC64;
       reactMarkerC159[62] = reactMarkerC65;
       reactMarkerC159[63] = reactMarkerC66;
       reactMarkerC159[64] = reactMarkerC67;
       reactMarkerC159[65] = reactMarkerC68;
       reactMarkerC159[66] = reactMarkerC69;
       reactMarkerC159[67] = reactMarkerC70;
       reactMarkerC159[68] = reactMarkerC71;
       reactMarkerC159[69] = reactMarkerC72;
       reactMarkerC159[70] = reactMarkerC73;
       reactMarkerC159[71] = reactMarkerC74;
       reactMarkerC159[72] = reactMarkerC75;
       reactMarkerC159[73] = reactMarkerC76;
       reactMarkerC159[74] = reactMarkerC77;
       reactMarkerC159[75] = reactMarkerC78;
       reactMarkerC159[76] = reactMarkerC79;
       reactMarkerC159[77] = reactMarkerC80;
       reactMarkerC159[78] = reactMarkerC81;
       reactMarkerC159[79] = reactMarkerC82;
       reactMarkerC159[80] = reactMarkerC83;
       reactMarkerC159[81] = reactMarkerC84;
       reactMarkerC159[82] = reactMarkerC85;
       reactMarkerC159[83] = reactMarkerC86;
       reactMarkerC159[84] = reactMarkerC87;
       reactMarkerC159[85] = reactMarkerC88;
       reactMarkerC159[86] = reactMarkerC89;
       reactMarkerC159[87] = reactMarkerC90;
       reactMarkerC159[88] = reactMarkerC91;
       reactMarkerC159[89] = reactMarkerC92;
       reactMarkerC159[90] = reactMarkerC93;
       reactMarkerC159[91] = reactMarkerC94;
       reactMarkerC159[92] = reactMarkerC95;
       reactMarkerC159[93] = reactMarkerC96;
       reactMarkerC159[94] = reactMarkerC97;
       reactMarkerC159[95] = reactMarkerC98;
       reactMarkerC159[96] = reactMarkerC99;
       reactMarkerC159[97] = reactMarkerC100;
       reactMarkerC159[98] = reactMarkerC101;
       reactMarkerC159[99] = reactMarkerC102;
       reactMarkerC159[100] = reactMarkerC103;
       reactMarkerC159[101] = reactMarkerC104;
       reactMarkerC159[102] = reactMarkerC105;
       reactMarkerC159[103] = reactMarkerC106;
       reactMarkerC159[104] = reactMarkerC107;
       reactMarkerC159[105] = reactMarkerC108;
       reactMarkerC159[106] = reactMarkerC109;
       reactMarkerC159[107] = reactMarkerC110;
       reactMarkerC159[108] = reactMarkerC111;
       reactMarkerC159[109] = reactMarkerC112;
       reactMarkerC159[110] = reactMarkerC113;
       reactMarkerC159[111] = reactMarkerC114;
       reactMarkerC159[112] = reactMarkerC115;
       reactMarkerC159[113] = reactMarkerC116;
       reactMarkerC159[114] = reactMarkerC117;
       reactMarkerC159[115] = reactMarkerC118;
       reactMarkerC159[116] = reactMarkerC119;
       reactMarkerC159[117] = reactMarkerC120;
       reactMarkerC159[118] = reactMarkerC121;
       reactMarkerC159[119] = reactMarkerC122;
       reactMarkerC159[120] = reactMarkerC123;
       reactMarkerC159[121] = reactMarkerC124;
       reactMarkerC159[122] = reactMarkerC125;
       reactMarkerC159[123] = reactMarkerC126;
       reactMarkerC159[124] = reactMarkerC127;
       reactMarkerC159[125] = reactMarkerC128;
       reactMarkerC159[126] = reactMarkerC129;
       reactMarkerC159[127] = reactMarkerC130;
       reactMarkerC159[128] = reactMarkerC131;
       reactMarkerC159[129] = reactMarkerC132;
       reactMarkerC159[130] = reactMarkerC133;
       reactMarkerC159[131] = reactMarkerC134;
       reactMarkerC159[132] = reactMarkerC135;
       reactMarkerC159[133] = reactMarkerC136;
       reactMarkerC159[134] = reactMarkerC137;
       reactMarkerC159[135] = reactMarkerC138;
       reactMarkerC159[136] = reactMarkerC139;
       reactMarkerC159[137] = reactMarkerC140;
       reactMarkerC159[138] = reactMarkerC141;
       reactMarkerC159[139] = reactMarkerC142;
       reactMarkerC159[140] = reactMarkerC143;
       reactMarkerC159[141] = reactMarkerC144;
       reactMarkerC159[142] = reactMarkerC145;
       reactMarkerC159[143] = reactMarkerC146;
       reactMarkerC159[144] = reactMarkerC147;
       reactMarkerC159[145] = reactMarkerC148;
       reactMarkerC159[146] = reactMarkerC149;
       reactMarkerC159[147] = reactMarkerC150;
       reactMarkerC159[148] = reactMarkerC151;
       reactMarkerC159[149] = reactMarkerC152;
       reactMarkerC159[150] = reactMarkerC153;
       reactMarkerC159[151] = reactMarkerC154;
       reactMarkerC159[152] = reactMarkerC155;
       reactMarkerC159[153] = reactMarkerC156;
       reactMarkerC159[154] = reactMarkerC157;
       reactMarkerC159[155] = reactMarkerC158;
       reactMarkerC159[156] = reactMarkerC15;
       ReactMarkerConstants.$VALUES = reactMarkerC159;
    }
    public void ReactMarkerConstants(String p0,int p1){
       super(p0, p1);
    }
    public static ReactMarkerConstants valueOf(String p0){
       Object obj = PatchProxy.applyOneRefs(p0, null, ReactMarkerConstants.class, "2");
       if (obj != PatchProxyResult.class) {
          return obj;
       }
       return Enum.valueOf(ReactMarkerConstants.class, p0);
    }
    public static ReactMarkerConstants[] values(){
       Object obj = PatchProxy.apply(null, null, ReactMarkerConstants.class, "1");
       if (obj != PatchProxyResult.class) {
          return obj;
       }
       return ReactMarkerConstants.$VALUES.clone();
    }
}
